import {requireUser,assertMembership} from '../_shared/auth.ts'
import {enforceRateLimit} from '../_shared/rate-limit.ts'
import {negativeValidationHandler,type NegativeComparison} from '../_shared/negative-validation-api.ts'
import {NEGATIVE_ESTABLISHMENT,NEGATIVE_NAME,type NegativeRun,type NegativeCandidate,type NegativeReview,type NegativeLabel} from '../_shared/negative-validation-core.ts'
import type {NegativeTask} from '../_shared/negative-validation-score.ts'
Deno.serve(negativeValidationHandler(async request=>{
  const ctx=await requireUser(request);if(request.method==='POST')enforceRateLimit('negative-validation:'+ctx.user.id,120,60_000)
  const {data:e,error}=await ctx.client.from('establishments').select('id,organization_id').eq('id',NEGATIVE_ESTABLISHMENT).single();if(error||!e)throw new Error('FORBIDDEN');const org=e.organization_id;await assertMembership(ctx.client,ctx.user.id,org,['owner','admin','manager'])
  const get=async(id?:string)=>{let q=ctx.admin.from('analysis_negative_validation_runs').select('*').eq('organization_id',org).eq('establishment_id',e.id).eq('name',NEGATIVE_NAME);if(id)q=q.eq('id',id);const {data,error}=await q.maybeSingle();if(error)throw new Error('NEGATIVE_READ_FAILED');if(id&&!data)throw new Error('NEGATIVE_NOT_FOUND');return data as NegativeRun|null}
  const children=async(table:string,id:string)=>{await get(id);const result=[];for(let offset=0;;offset+=500){let q=ctx.admin.from(table).select('*').eq('experiment_id',id);q=table==='analysis_negative_validation_labels'?q.order('review_id').order('theme_key'):table==='analysis_negative_validation_reviews'?q.order('review_id'):q.order('id');const {data,error}=await q.range(offset,offset+499);if(error)throw new Error('NEGATIVE_READ_FAILED');result.push(...data??[]);if((data?.length??0)<500)break}return result}
  return {user:ctx.user.id,get,configured:()=>!!Deno.env.get('TYPESAFE_API_KEY')?.trim(),
    live:async()=>{const rows:NegativeCandidate[]=[];for(let offset=0;;offset+=500){const {data,error}=await ctx.admin.from('reviews').select('id,rating,original_text,original_language,published_at,review_detailed_rating,review_translations(language,translated_text)').eq('establishment_id',e.id).eq('organization_id',org).order('id').range(offset,offset+499);if(error)throw new Error('NEGATIVE_SOURCE_READ_FAILED');rows.push(...data as NegativeCandidate[]??[]);if((data?.length??0)<500)break}return rows},
    items:async id=>await children('analysis_negative_validation_reviews',id) as NegativeReview[],labels:async id=>await children('analysis_negative_validation_labels',id) as NegativeLabel[],tasks:async id=>await children('analysis_negative_validation_tasks',id) as NegativeTask[],
    result:async id=>{await get(id);const {data,error}=await ctx.admin.from('analysis_negative_validation_results').select('comparison').eq('experiment_id',id).maybeSingle();if(error)throw new Error('NEGATIVE_READ_FAILED');return data?.comparison as NegativeComparison|null},
    backfill:async()=>{const {data,error}=await ctx.admin.from('english_translation_backfill_jobs').select('id,status,error_code,provider_requests').eq('organization_id',org).eq('establishment_id',e.id).order('created_at',{ascending:false}).order('id',{ascending:false}).limit(1).maybeSingle();if(error)throw new Error('NEGATIVE_PREPARATION_READ_FAILED');return data},
    create:async payload=>{const rate=Number(Deno.env.get('JEV_INPUT_USD_PER_MILLION')??.042);const {data,error}=await ctx.admin.rpc('create_negative_validation',{...payload,p_organization:org,p_establishment:e.id,p_rates:{jev_input:Number.isFinite(rate)&&rate>=0?rate:.042}});if(error||!data)throw new Error('NEGATIVE_CREATE_FAILED');return data as string},
    write:async(id,revision,action,payload)=>{const {error}=await ctx.admin.rpc('write_negative_validation',{p_user:ctx.user.id,p_id:id,p_revision:revision,p_action:action,p_payload:payload});if(error){const code=['FORBIDDEN','NEGATIVE_HUMAN_IMMUTABLE','NEGATIVE_REVISION_CHANGED','NEGATIVE_ENGLISH_REQUIRED','NEGATIVE_ANNOTATION_INCOMPLETE','NEGATIVE_INTEGRITY_CHANGED','NEGATIVE_BENCHMARK_ALREADY_STARTED'].find(c=>error.message.includes(c));throw new Error(code??'NEGATIVE_SAVE_FAILED')}},
  }
}))
