import {test,expect} from '@playwright/test'
test('V8 entry is visible above historical V7, with current coverage; opening sends GET only',async({page})=>{const methods:string[]=[];await page.route('https://english-fixture.supabase.co/functions/v1/**',async route=>{methods.push(route.request().method());const english=route.request().url().includes('backfill-review-english-translations');await route.fulfill({status:200,headers:{'Access-Control-Allow-Origin':'*','Content-Type':'application/json'},body:JSON.stringify(english?{coverage:{stored_reviews:102,reviews_with_text:96,original_english:9,english_translation_found:87,english_translation_missing:0,coverage_percent:100},job:null}:{eligibility:{available:true},run:null})})});for(const language of ['fr','vi']){await page.goto('/tests/e2e/fixtures/v8.html?phase=entry&language='+language);const button=page.getByRole('button',{name:language==='fr'?'Lancer le rapport V8':'Tạo báo cáo V8',exact:true});await expect(button).toBeEnabled();expect(await button.evaluate(e=>e.closest('details'))).toBeNull();const y=await button.boundingBox(),old=await page.getByRole('heading',{name:'PHASE 2 V7 · ENGLISH'}).boundingBox();expect(y!.y).toBeLessThan(old!.y);expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);await page.screenshot({path:`test-results/v8-entry-${language}-${test.info().project.name}.png`,fullPage:true})}expect(methods.every(m=>m==='GET')).toBe(true)})
test('manager V8 FR/VI at mobile sizes: separate sources, explicit unexplained/hidden signals, no Price score and no overflow',async({page})=>{
  const external:string[]=[];page.on('request',r=>{if(/api\.typesafe|api\.openai|apify|functions\/v1|rest\/v1/.test(r.url()))external.push(r.url())})
  for(const language of ['fr','vi']){await page.goto('/tests/e2e/fixtures/v8.html?language='+language);await expect(page.getByRole('heading',{name:language==='fr'?'Lecture croisée des notes':'Đối chiếu điểm đánh giá'})).toBeVisible();await expect(page.locator('.v8-rating-card')).toHaveCount(4);expect(await page.locator('[data-category=price]').textContent()).not.toMatch(/\/ 5/);await expect(page.locator('[data-high-signal=unexplained]')).toContainText(language==='fr'?'Note faible sans explication textuelle':'Điểm thấp nhưng nội dung không giải thích');await expect(page.locator('[data-high-signal=unexplained] li')).toHaveCount(0);await expect(page.locator('[data-high-signal=hidden]')).toContainText('45 minutes');expect(await page.locator('.v8-high-signal').count()).toBeLessThanOrEqual(5);await page.locator('.v8-cross-info summary').click();await expect(page.locator('.v8-cross-info p')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);await page.screenshot({path:`test-results/cross-v8-${language}-${test.info().project.name}.png`,fullPage:true})}
  expect(external).toEqual([])
})
test('manual V8 FR/VI double tap, server polling and PWA reopening never make a second POST',async({page})=>{
  let started=false;const posts:Record<string,unknown>[]=[];const providerCalls:string[]=[];page.on('request',r=>{if(/api\.typesafe|api\.openai|apify/.test(r.url()))providerCalls.push(r.url())});await page.route('https://english-fixture.supabase.co/functions/v1/**',async route=>{const request=route.request();if(request.method()==='POST'){posts.push(request.postDataJSON());started=true}await route.fulfill({status:started&&request.method()==='POST'?202:200,headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'*','Content-Type':'application/json'},body:JSON.stringify({eligibility:{available:true},run:started?{generation_id:'v8-mobile-fixture',status:'running',progress:1,total_steps:2}:null})})})
  for(const language of ['fr','vi']){started=false;const before=posts.length;await page.goto('/tests/e2e/fixtures/v8.html?phase=start&language='+language);const button=page.getByRole('button',{name:language==='fr'?'Lancer le rapport V8':'Tạo báo cáo V8',exact:true});await expect(button).toBeEnabled();expect(posts.length).toBe(before);await button.evaluate((el:HTMLButtonElement)=>{el.click();el.click()});await expect(page.getByRole('heading',{name:language==='fr'?'Rapport V8 en cours':'Báo cáo V8 đang được tạo'})).toBeVisible();expect(posts.length).toBe(before+1);await page.reload();await expect(page.getByRole('heading',{name:language==='fr'?'Rapport V8 en cours':'Báo cáo V8 đang được tạo'})).toBeVisible();await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));expect(posts.length).toBe(before+1);expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);await page.evaluate(()=>localStorage.clear())}
  expect(posts.every(p=>p.first_v8===true&&p.establishment_id==='synthetic-establishment')).toBe(true);expect(providerCalls).toEqual([])
})
