import { expect,test } from '@playwright/test'
test('compiled PWA cold-boots offline to its cached report without an API cache or forced reload',async({page,context})=>{
  page.on('pageerror',error=>console.error('PWA_TEST_PAGE_ERROR',error.message))
  page.on('requestfailed',request=>console.error('PWA_TEST_REQUEST_FAILED',request.url(),request.failure()?.errorText))
  await page.goto('/#/analyses?establishment=place-account-a&mode=historical')
  await expect(page.getByText('Cached historical summary').first()).toBeVisible()
  await page.evaluate(()=>navigator.serviceWorker.ready)
  await expect.poll(()=>page.evaluate(()=>Boolean(navigator.serviceWorker.controller))).toBe(true)
  await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))))
  await page.evaluate(()=>scrollTo(0,650))
  await expect.poll(()=>page.evaluate(()=>scrollY)).toBeGreaterThan(500)
  await page.waitForTimeout(300)
  const cachedRequests=await page.evaluate(async()=>{
    const requests=await Promise.all((await caches.keys()).map(async key=>(await(await caches.open(key)).keys()).map(r=>r.url)))
    return requests.flat()
  })
  expect(cachedRequests.some(value=>{const url=new URL(value);return url.hostname.endsWith('.supabase.co') || /\/(rest|auth|functions)\/v1\//.test(url.pathname)})).toBe(false)
  expect(cachedRequests.some(url=>/assets\/.*\.js$/.test(url))).toBe(true)
  await context.setOffline(true)
  await page.goto('about:blank')
  await page.goto('/#/')
  await expect(page).toHaveURL(/mode=historical/)
  await expect(page.getByText('Cached historical summary').first()).toBeAttached()
  await expect(page.locator('.route-loading')).toHaveCount(0)
  await expect(page.locator('.offline-banner')).toBeVisible()
  await expect.poll(()=>page.evaluate(()=>scrollY)).toBeGreaterThan(500)
  await context.setOffline(false)
  await expect(page.locator('.offline-banner')).toHaveCount(0)
})
