import {test,expect} from '@playwright/test'
test('blind representative annotation FR/VI:25 themes, sparse choices, server save, replacement and reopening on mobile',async({page})=>{
  const external:string[]=[];page.on('request',r=>{if(/api\.typesafe|api\.openai|apify|functions\/v1|rest\/v1/.test(r.url()))external.push(r.url())})
  for(const language of ['fr','vi']){
    await page.goto('/tests/e2e/fixtures/representative.html?language='+language);await expect(page.locator('[data-holdout-theme]')).toHaveCount(25);await expect(page.locator('[aria-pressed=true]')).toHaveCount(25)
    expect(await page.locator('body').textContent()).not.toMatch(/Gold v1|Gold actuel|Sol|Jev|rating|probabilities|original_language/)
    const card=page.locator('[data-holdout-theme=attentiveness]');await card.getByRole('button',{name:/Info/}).click();await expect(card.locator('p')).toBeVisible();await card.getByRole('button',{name:language==='fr'?'Incertain':'Chưa chắc',exact:true}).click()
    await page.getByRole('button',{name:language==='fr'?'Valider cet avis':'Xác nhận đánh giá này',exact:true}).click();await expect(page.getByRole('heading',{name:/1 \/ 12/})).toBeVisible();await page.reload();await expect(page.getByRole('heading',{name:language==='fr'?'Avis 2 / 12':'Đánh giá 2 / 12'})).toBeVisible()
    await page.getByRole('button',{name:language==='fr'?'Précédent':'Trước',exact:true}).click();await expect(card.getByRole('button',{name:language==='fr'?'Incertain':'Chưa chắc',exact:true})).toHaveAttribute('aria-pressed','true')
    const old=await page.locator('.gold-text').textContent();await page.getByRole('button',{name:language==='fr'?'Traduction anglaise incorrecte':'Bản dịch tiếng Anh không chính xác',exact:true}).click();await page.getByRole('alertdialog').getByRole('button',{name:language==='fr'?'Confirmer':'Xác nhận',exact:true}).click();await expect(page.locator('.gold-text')).not.toHaveText(old!)
    await page.getByRole('button',{name:language==='fr'?'Aucun thème explicite':'Không có chủ đề rõ ràng',exact:true}).click();const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('representative-fixture-server')!).labels);expect(saved.some((l:{choice:string})=>l.choice==='absent')).toBe(true)
    expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);await page.screenshot({path:`test-results/representative-draft-${language}-${test.info().project.name}.png`,fullPage:true});await page.evaluate(()=>localStorage.clear())
  }
  expect(external).toEqual([])
})
test('completed representative results FR/VI: microF1 primary, paired CI, separate difficult sample and no edit buttons',async({page})=>{for(const language of ['fr','vi']){await page.goto('/tests/e2e/fixtures/representative.html?phase=results&language='+language);await expect(page.getByRole('heading',{name:language==='fr'?'Résultat du test représentatif':'Kết quả kiểm tra đại diện'})).toBeVisible();await expect(page.getByRole('heading',{name:language==='fr'?'Test difficile':'Kiểm tra trường hợp khó'})).toBeVisible();await expect(page.getByText(language==='fr'?'IC 95 % du delta':'Khoảng tin cậy 95% của chênh lệch',{exact:true})).toBeVisible();await expect(page.getByRole('button')).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);await page.screenshot({path:`test-results/representative-results-${language}-${test.info().project.name}.png`,fullPage:true})}})
