import type {SupabaseClient} from 'npm:@supabase/supabase-js@2.117.2'
import {createJevClient} from './jev.ts'
import {parseThemes} from './jev-themes.ts'
import {negativePayload,NEGATIVE_MODEL_CONFIG,type NegativeTask} from './negative-validation-score.ts'
import {verifyAiBenchmark,scoreAiBenchmark,type AiBenchmarkRun} from './ai-exploratory-benchmark.ts'
const safe=(e:unknown)=>e instanceof Error&&/^[A-Z0-9_]+$/.test(e.message)?e.message:'AI_BENCHMARK_NETWORK_ERROR'
export async function processAiBenchmark(admin:SupabaseClient,run:AiBenchmarkRun,worker:string){const begin=Date.now(),rpc=async(name:string,args:Record<string,unknown>)=>{const {data,error}=await admin.rpc(name,args);if(error)throw new Error('AI_BENCHMARK_SAVE_FAILED');return data},finish=async(comparison:unknown=null,error:string|null=null)=>{if(await rpc('finish_negative_ai_benchmark',{p_id:run.id,p_worker:worker,p_comparison:comparison,p_error:error})!==true)throw new Error('AI_BENCHMARK_LEASE_LOST')};try{await verifyAiBenchmark(run);const key=Deno.env.get('TYPESAFE_API_KEY');if(!key?.trim())throw new Error('JEV_NOT_CONFIGURED');let processed=0
 while(Date.now()-begin<70_000){const tasks=await rpc('claim_negative_ai_tasks',{p_id:run.id,p_worker:worker}) as NegativeTask[];if(!tasks.length)break;if(tasks.length>8)throw new Error('AI_BENCHMARK_CONCURRENCY_INVALID');const outcomes=await Promise.allSettled(tasks.map(async t=>{const i=run.dataset_snapshot.find(i=>i.review_id===t.review_id);if(!i||t.question_set_version!==NEGATIVE_MODEL_CONFIG[t.model_version].question_set)throw new Error('AI_BENCHMARK_TASK_INVALID');let input=0,output=0,requests=0,retries=0,model:string|null=null,response:unknown=null,code:string|null=null,complete=true;const start=Date.now(),client=createJevClient(key,{maxAttempts:1,onUsage:(u,m)=>{input+=u.input_tokens;output+=u.output_tokens;model=m},onAttempt:()=>requests++,onRetry:()=>retries++});try{const result=await client.evaluatePayload(negativePayload(t.model_version,t.review_alias,i.analysis_text),parseThemes);response=result.decision;model=result.model}catch(e){code=safe(e);if(['JEV_NETWORK_ERROR','JEV_INVALID_USAGE','JEV_INVALID_RESPONSE'].includes(code))complete=false}if(await rpc('complete_negative_ai_task',{p_id:run.id,p_worker:worker,p_task:t.id,p_values:{status:code?'failed':'completed',response,served_model:model,input_tokens:input,output_tokens:output,request_count:requests,retry_count:retries,duration_ms:Date.now()-start,error_code:code,usage_complete:complete}})!==true)throw new Error('AI_BENCHMARK_LEASE_LOST');processed++}));const rejected=outcomes.find(o=>o.status==='rejected');if(rejected?.status==='rejected')throw rejected.reason}
 if(processed){await finish();return {status:'running'}}const {data:tasks,error}=await admin.from('analysis_negative_ai_exploratory_tasks').select('*').eq('run_id',run.id).limit(500);if(error||!tasks)throw new Error('AI_BENCHMARK_READ_FAILED');if(tasks.some(t=>['pending','running'].includes(t.status))){await finish();return {status:'running'}}await finish(scoreAiBenchmark({...run,completed_at:new Date().toISOString()},tasks as NegativeTask[]));return {status:'completed'}
 }catch(e){const code=safe(e);if(code!=='AI_BENCHMARK_LEASE_LOST')try{await finish(null,code)}catch{/* Unconfirmed paid responses are not replayed. */}return {status:'error',error_code:code}}
}
