import {preflight,json} from './cors.ts'
import {prepareAiBenchmark,verifyAiBenchmark,ARTISAN_AI_SOURCE,type AiPreannotation,type AiBenchmarkRun,scoreAiBenchmark} from './ai-exploratory-benchmark.ts'
import type {NegativeReview} from './negative-validation-core.ts'
export interface AiBenchmarkRepository {items:()=>Promise<NegativeReview[]>;reference:()=>Promise<AiPreannotation[]>;protectedIds:()=>Promise<string[]>;get:()=>Promise<AiBenchmarkRun|null>;result:(id:string)=>Promise<ReturnType<typeof scoreAiBenchmark>|null>;start:(prepared:Awaited<ReturnType<typeof prepareAiBenchmark>>)=>Promise<string>;configured:()=>boolean;progress:(id:string)=>Promise<{completed:number;failed:number;total:number}>}
export function aiBenchmarkHandler(repository:(r:Request)=>Promise<AiBenchmarkRepository>){return async(request:Request)=>{const pre=preflight(request);if(pre)return pre;try{if(!['GET','POST'].includes(request.method))return json({error:'METHOD_NOT_ALLOWED'},405);const repo=await repository(request);let run=await repo.get(),prepared:Awaited<ReturnType<typeof prepareAiBenchmark>>|null=null,eligibility_error:string|null=null
  if(!run){try{prepared=await prepareAiBenchmark(await repo.items(),await repo.reference(),await repo.protectedIds())}catch(e){eligibility_error=e instanceof Error?e.message:'AI_BENCHMARK_REFERENCE_INVALID'}}else await verifyAiBenchmark(run)
  if(request.method==='POST'){const body=await request.json();if(body.action!=='start'||body.confirm!==true)throw new Error('AI_BENCHMARK_PAYMENT_CONFIRMATION_REQUIRED');if(body.source_experiment_id!==ARTISAN_AI_SOURCE)throw new Error('FORBIDDEN');if(!run){if(!prepared)throw new Error(eligibility_error??'AI_BENCHMARK_REFERENCE_INVALID');if(!repo.configured())throw new Error('JEV_NOT_CONFIGURED');await repo.start(prepared);run=await repo.get();if(!run)throw new Error('AI_BENCHMARK_SAVE_FAILED')}}
  const reference=run?.reference_snapshot??prepared?.reference??[],items=run?.dataset_snapshot??prepared?.items??[];return json({source_experiment_id:ARTISAN_AI_SOURCE,run:run?{id:run.id,status:run.status,created_at:run.created_at,error_code:run.error_code}:null,ready:!!prepared||!!run,eligibility_error,english_ready:items.length,reference_reviews:reference.length,reference_labels:reference.reduce((n,a)=>n+Object.keys(a.theme_choices).length,0),reference_models:[...new Set(reference.map(a=>a.model_source))],reference_type:'chatgpt_ai_preannotations',human_validated:false,comparison:run?.status==='completed'?await repo.result(run.id):null,progress:run?await repo.progress(run.id):{completed:0,failed:0,total:0}})
}catch(e){const code=e instanceof Error&&/^[A-Z0-9_]+$/.test(e.message)?e.message:'AI_BENCHMARK_REQUEST_FAILED';return json({error:code},code==='UNAUTHORIZED'?401:code==='FORBIDDEN'?403:code==='JEV_NOT_CONFIGURED'||/CHANGED/.test(code)?409:code.startsWith('AI_BENCHMARK_')&&!code.endsWith('_FAILED')?400:500)}}}
export type AiBenchmarkData=Awaited<ReturnType<typeof scoreAiBenchmark>>
