// @vitest-environment node
import {describe,it,expect,vi} from 'vitest'
import {analysisTextForReview,analysisTextForFreshReview,analysisTextSha256,analysisInputStats,benchmarkText,ENGLISH_OVERRIDE_POLICY,type AnalysisReview,type EnglishTranslationOverride} from './analysis-text'
import {freshEnglishAnalysisInputs} from './analysis-text-overrides-server'
import {processHistoricalRun,type HistoricalJob} from './historical-report-worker'
import {readFileSync} from 'node:fs'
const asOf='2026-10-09T12:00:00Z'
async function fixtures(){const scenarios=[{n:26,error:'hallucinated_currency',original:'Счёт 450000 вместо 400000. Не стоит своих денег.',provider:'The bill was 450,000 rubles instead of 400,000 rubles. Not worth the money.',corrected:'The bill was 450,000 instead of 400,000. Not worth the money.'},{n:28,error:'menu_item_as_location',original:'Наверное я выбрала не то блюдо. Картофель был обычный.',provider:'Maybe I chose the wrong location. The potatoes were ordinary.',corrected:'Maybe I chose the wrong menu item. The potatoes were ordinary.'},{n:29,error:'sentiment_reversal',original:'Напитки отличные, но еда невкусная.',provider:'The drinks were awful. The food was tasteless.',corrected:'The drinks are excellent. The food was tasteless.'}];return await Promise.all(scenarios.map(async s=>{const id='00000000-0000-4000-8000-'+String(s.n).padStart(12,'0'),review:AnalysisReview&{id:string}={id,original_text:s.original,original_language:'ru',review_translations:[{id:'provider-'+s.n,language:'en',translated_text:s.provider,created_at:'2026-10-08T00:00:00Z',updated_at:'2026-10-08T00:00:00Z'},{language:'vi',translated_text:'Bản tiếng Việt được giữ nguyên.'}]},override:EnglishTranslationOverride={review_id:id,original_text_sha256:await analysisTextSha256(s.original),provider_translation_sha256:await analysisTextSha256(s.provider),corrected_english_text:s.corrected,corrected_english_sha256:await analysisTextSha256(s.corrected),correction_language:'en',source:'chatgpt_gpt_6_manual_audit',status:'candidate_for_future_analysis',benchmark_policy:'do_not_change_frozen_v9_v11_inputs',error_type:s.error,evidence_fr:'Fixture synthétique, aucune annotation réelle.',created_at:'2026-10-09T05:32:41Z'};return {review,override,s}}))}
describe('verified English translation overrides, fresh input only',()=>{
 it('refuses a stored snapshot before querying corrections',async()=>{const f=(await fixtures())[0],frozen={...f.review,...analysisTextForReview(f.review)},rpc=vi.fn();await expect(analysisTextForFreshReview(frozen,f.override,asOf)).rejects.toThrow('ENGLISH_OVERRIDE_FROZEN_INPUT');await expect(freshEnglishAnalysisInputs({rpc} as never,[frozen],'org',asOf)).rejects.toThrow('ENGLISH_OVERRIDE_FROZEN_INPUT');expect(rpc).not.toHaveBeenCalled()})
 it.each([26,28,29])('applies the correction for review %i with all 3 verified hashes',async n=>{const f=(await fixtures()).find(f=>f.s.n===n)!,before=JSON.stringify(f.review),r=await analysisTextForFreshReview(f.review,f.override,asOf);expect(r.analysis_text).toBe(f.s.corrected);expect(r.analysis_source).toBe('verified_translation_override_en');expect(r.analysis_language).toBe('en');expect(r).toMatchObject({analysis_translation_override:{status:'applied',review_id:f.review.id,errors:[],provider_translation:{translated_text:f.s.provider,sha256:f.override.provider_translation_sha256,id:'provider-'+n},correction:{source:f.override.source,corrected_english_sha256:f.override.corrected_english_sha256}}});expect(JSON.stringify(f.review)).toBe(before);if(n===26)expect(r.analysis_text).not.toContain('rubles');if(n===28)expect(r.analysis_text).toContain('wrong menu item');if(n===29)expect(r.analysis_text).toContain('drinks are excellent')})
 it.each(['original_text_sha256','provider_translation_sha256','corrected_english_sha256'] as const)('rejects a mismatch in %s and retains provider text with an anomaly',async field=>{const f=(await fixtures())[0],r=await analysisTextForFreshReview(f.review,{...f.override,[field]:'0'.repeat(64)},asOf);expect(r.analysis_text).toBe(f.s.provider);expect(r).toMatchObject({analysis_translation_override:{status:'rejected'}})})
 it('checks review_id even if the entire original/provider pair is identical on another review',async()=>{const f=(await fixtures())[0],r=await analysisTextForFreshReview({...f.review,id:'00000000-0000-4000-8000-000000000027'},f.override,asOf);expect(r.analysis_text).toBe(f.s.provider);expect(r).toMatchObject({analysis_translation_override:{errors:['REVIEW_ID_MISMATCH'],status:'rejected'}})})
 it('never applies another review’s correction',async()=>{const f=await fixtures();for(let a=0;a<3;a++)for(let b=0;b<3;b++)if(a!==b){const r=await analysisTextForFreshReview(f[a].review,f[b].override,asOf);expect(r.analysis_text).toBe(f[a].s.provider);expect(r.analysis_source).toBe('google_translation_en')}})
 it('rejects non-English, wrong source/policy, empty text and corrections newer than the run',async()=>{const f=(await fixtures())[0];for(const change of [{correction_language:'ru'},{source:'unknown_ai'},{status:'disabled'},{benchmark_policy:'overwrite_old_benchmarks'},{corrected_english_text:''},{created_at:'2026-10-10T00:00:00Z'}]){const r=await analysisTextForFreshReview(f.review,{...f.override,...change},asOf);expect(r.analysis_text).toBe(f.s.provider);expect(r).toMatchObject({analysis_translation_override:{status:'rejected'}})}})
 it('hashes UTF-8 bytes exactly; whitespace or original/provider edits invalidate a correction',async()=>{const f=(await fixtures())[0];for(const review of [{...f.review,original_text:f.review.original_text+' '},{...f.review,review_translations:[{language:'en',translated_text:f.s.provider+'\n'}]}])expect(await analysisTextForFreshReview(review,f.override,asOf)).toMatchObject({analysis_source:'google_translation_en',analysis_translation_override:{status:'rejected'}})})
 it('preserves original-English and textless behavior',async()=>{const f=(await fixtures())[0];expect((await analysisTextForFreshReview({...f.review,original_language:'en'},f.override,asOf)).analysis_source).toBe('original_en');expect((await analysisTextForFreshReview({...f.review,original_text:''},f.override,asOf)).analysis_source).toBe('textless');expect(await analysisTextForFreshReview(f.review,undefined,asOf)).toEqual(analysisTextForReview(f.review))})
 it('keeps all frozen benchmark inputs and V6 grounding unchanged',async()=>{const f=(await fixtures())[0],frozen={...f.review,...analysisTextForReview(f.review)};const corrected=await analysisTextForFreshReview(f.review,f.override,asOf);for(const v of [7,8,9,10,11])expect(benchmarkText(frozen,v)).toBe(f.s.provider);expect(benchmarkText(frozen,6)).toBe(f.s.original);expect(corrected.analysis_text).not.toBe(benchmarkText(frozen,11))})
 it('counts corrected English coverage correctly and preserves old stats shape without overrides',async()=>{const f=await fixtures(),resolved=await Promise.all(f.map(i=>analysisTextForFreshReview(i.review,i.override,asOf))),rows=f.map((f,i)=>({...f.review,...resolved[i]}));expect(analysisInputStats(rows)).toMatchObject({reviews_with_text:3,verified_english_override_count:3,google_english_translation_count:0,english_override_anomaly_count:0,english_analysis_coverage_percent:100});expect(analysisInputStats(f.map(i=>i.review))).not.toHaveProperty('verified_english_override_count')})
 it('loads only requested tenant review IDs and logs rejection codes, not customer text',async()=>{const f=await fixtures(),warn=vi.spyOn(console,'warn').mockImplementation(()=>{}),rpc=vi.fn().mockResolvedValue({data:[{...f[0].override,original_text_sha256:'0'.repeat(64)},f[1].override,f[2].override],error:null});try{const results=await freshEnglishAnalysisInputs({rpc} as never,f.map(f=>f.review),'org',asOf);expect(rpc).toHaveBeenCalledWith('read_analysis_english_translation_overrides',{p_organization:'org',p_review_ids:f.map(f=>f.review.id),p_as_of:asOf});expect(results[0].analysis_text).toBe(f[0].s.provider);expect(warn).toHaveBeenCalledWith('ENGLISH_TRANSLATION_OVERRIDE_REJECTED',{review_id:f[0].review.id,errors:['ORIGINAL_HASH_MISMATCH']});expect(JSON.stringify(warn.mock.calls)).not.toContain(f[0].s.provider)}finally{warn.mockRestore()}})
 it('fails before analysis if the reader fails or returns foreign/duplicate IDs',async()=>{const f=await fixtures();for(const reply of [{data:null,error:{message:'network'}},{data:[{...f[0].override,review_id:'foreign'}],error:null},{data:[f[0].override,f[0].override],error:null}])await expect(freshEnglishAnalysisInputs({rpc:async()=>reply} as never,[f[0].review],'org',asOf)).rejects.toThrow('ENGLISH_OVERRIDE_')})
 it('the server preparation boundary applies overrides only to tagged new snapshots, never reads them on old jobs',async()=>{const f=(await fixtures())[0];for(const tagged of [false,true]){const row={...f.review,rating:3,text:f.s.original,review_reply_drafts:[],status:'new',historical_import:true,published_at:null,review_context:null,review_detailed_rating:null},run={id:'run',generation_id:'gen',organization_id:'org',establishment_id:'place',language:'fr',created_at:asOf,status:'running',model:'gpt-6.1-sol',cursor:0,attempt_count:0,ai_calls:0,findings:[],classifications:[],snapshot:{analysis_version:7,...(tagged?{english_translation_override_policy:ENGLISH_OVERRIDE_POLICY}:{})}} as unknown as HistoricalJob,read=vi.fn(),q={select(){return this},eq(){return this},gte(){return this},lte(){return this},order(){return this},range:async()=>({data:[row],error:null}),single:async()=>({data:{id:'place',organization_id:'org',total_reviews:1,rating:3,created_at:asOf},error:null})},admin={from:()=>q,rpc:async(name:string,args:Record<string,unknown>)=>{if(name==='read_analysis_english_translation_overrides'){read();return {data:[f.override],error:null}}Object.assign(run,args.p_values);return {data:true,error:null}}};await processHistoricalRun(admin as never,run,'worker');expect(run.snapshot.reviews![0].analysis_text).toBe(tagged?f.s.corrected:f.s.provider);expect(read).toHaveBeenCalledTimes(tagged?1:0);expect(run.ai_calls).toBe(0)}})
 it('has no model/provider calls or translation writes in the new resolver',()=>{const code=readFileSync('supabase/functions/_shared/analysis-text-overrides-server.ts','utf8');expect(code).not.toMatch(/\.update\(|\.insert\(|\.upsert\(|fetch\(|createJevClient|OPENAI|APIFY/);expect(readFileSync('supabase/functions/_shared/historical-v11-worker.ts','utf8')).not.toContain('freshEnglishAnalysisInputs')})
})
