// @vitest-environment node
import {it,expect} from 'vitest'
import {syntheticV9,completeSyntheticTasks,fakeThemeDecision} from '../../../tests/fixtures/historical-v9'
import {V9_CONFIG,v9Payload,deriveV9,v9Costs,compareV8V9,parseV9Sentiment} from './historical-v9-core'
import {v9NarrativeContext,assembleV9Narrative} from './historical-v9-narrative'
import {validateV9Snapshot} from './historical-v9-worker'
import {benchmarkPayload,jevPayload} from './jev'
import {themePayload} from './jev-themes'
it('copies exactly103 frozen review IDs/97 English texts and keeps the V8 source entirely unchanged',()=>{const h=syntheticV9(),before=JSON.stringify(h.source);validateV9Snapshot(h.job);expect(h.job.snapshot.reviews).toEqual(h.source.snapshot.reviews);expect(h.job.snapshot.reviews).toHaveLength(103);expect(h.job.snapshot.reviews.filter(r=>r.analysis_text?.trim())).toHaveLength(97);h.job.snapshot.reviews[0].analysis_text='tampered';expect(()=>validateV9Snapshot(h.job)).toThrow('REPORT_V9_SOURCE_CHANGED');expect(JSON.stringify(h.source)).toBe(before)})
it('theme payload/questions equal Phase2 V7 exactly, sentiment equals Phase1 overall only, no stars/metadata/original text',()=>{const theme=v9Payload('themes','r1','English'),sent=v9Payload('sentiment','r1','English');expect(theme).toEqual(benchmarkPayload(themePayload('jev-latest','r1','English'),7));expect(Object.keys(theme.questions)).toHaveLength(25);expect(sent.questions).toEqual({overall:jevPayload('jev-latest','r1','English').questions.overall});expect(sent.state).toEqual({review_alias:'r1',analysis_text:'English'});expect(JSON.stringify(theme)).not.toMatch(/"rating"|food_rating|service_rating|review_context|original_text|original_language/);expect(V9_CONFIG).toMatchObject({theme_repeat_count:3,sentiment_repeat_count:1,concurrency:8,threshold:.5})})
it('averages all3 reps at0.50, both yields two findings with explicit Jev provenance and null evidence',()=>{const h=syntheticV9();completeSyntheticTasks(h.tasks);for(const t of h.tasks.filter(t=>t.review_id===h.reviews[0].id&&t.kind==='themes')){const d=fakeThemeDecision();d.themes.attentiveness={choice:'both',probabilities:{absent:.1,positive:.2,negative:.2,both:.5}};t.result=d}const d=deriveV9(h.reviews,h.tasks),f=d.findings.filter(f=>f.review_id===h.reviews[0].id&&f.theme_key==='attentiveness');expect(f).toHaveLength(2);expect(f[0]).toMatchObject({evidence:null,analysis_source:'jev',repeat_stable:true});expect(f[0].probability_positive).toBeCloseTo(.7);expect(f[0].probability_negative).toBeCloseTo(.7);expect(d.classifications).toHaveLength(103);expect(d.classifications.filter(c=>c.basis==='rating')).toHaveLength(6)})
it('low Service score cannot fabricate any theme; Jev failure/insufficient is unavailable, not Sol or textual-star fallback',()=>{const h=syntheticV9();completeSyntheticTasks(h.tasks);const d=deriveV9(h.reviews,h.tasks);expect(d.cross_rating_analysis.review_analyses[0].axes.service.status).toBe('low_score_unexplained');expect(d.findings.filter(f=>f.review_id===h.reviews[0].id&&f.theme_key==='attentiveness')).toEqual([]);h.tasks.find(t=>t.kind==='sentiment')!.result={overall_choice:'insufficient',overall_probabilities:{positive:0,negative:0,insufficient:1},overall_confidence:1};h.tasks.find(t=>t.kind==='themes')!.status='failed';const partial=deriveV9(h.reviews,h.tasks);expect(partial.classifications[0]).toMatchObject({sentiment:'unavailable',basis:'unavailable'});expect(partial.unavailable_theme_reviews).toBe(1);expect(partial.findings.some(f=>f.review_id===h.reviews[0].id)).toBe(false);expect(partial.cross_rating_analysis.axes.service.low_score_unexplained_count).toBe(0);expect(JSON.stringify(partial.cross_rating_analysis)).not.toMatch(/price_rating/)})
it('Sol narrative input contains aggregates only, never customer texts or findings evidence; fallback stays FR/VI',()=>{const h=syntheticV9();completeSyntheticTasks(h.tasks);const d=deriveV9(h.reviews,h.tasks);for(const lang of ['fr','vi'] as const){const c=v9NarrativeContext(d,h.reviews,h.job.snapshot.base,lang);expect(JSON.stringify(c.input)).not.toMatch(/ENGLISH_CUSTOMER_SENTINEL|Русский|analysis_text|original_text|evidence|review_ids/);expect(c.input).toHaveProperty('cross_rating_summary');expect(c.input).toHaveProperty('structured_context_stats');const r=assembleV9Narrative(d,h.job.snapshot.base,lang,null);expect(r.version).toBe(9);expect(r.language).toBe(lang);expect(r.positive).toBe(103);expect(r.analysis_engine).toBe('jev_hybrid')}})
it('costs are separate/usage based; V8/V9 comparison reads source counts/costs rather than benchmark constants',()=>{const h=syntheticV9();completeSyntheticTasks(h.tasks);const d=deriveV9(h.reviews,h.tasks),c=v9Costs({...h.usage,jev_input_tokens:1_000_000,jev_output_tokens:2000,sol_narrative_input_tokens:2000,sol_narrative_output_tokens:1000},10000);expect(c.jev_cost_usd).toBe(.042);expect(c.sol_narrative_cost_usd).toBe(.014);expect(c.total_estimated_cost_usd).toBe(.056);const p=compareV8V9(h.source as never,h.reviews,d,c);expect(p.dataset).toMatchObject({v8:103,v9:103,common:103,v8_only:0,v9_only:0,identical:true,identical_analysis_text:103});expect(p.axes.service.v8).toBe(97);expect(p.axes.service.v9).toBe(0);expect(p.cost.v8_estimated_cost_usd).toBe(.007)})
it('parses the exact Phase1 sentiment choice/probabilities',()=>{expect(parseV9Sentiment({model:'jev-1',usage:{input_tokens:10,output_tokens:2},answers:{overall:{type:'choice',choice:'negative',probabilities:{positive:.1,negative:.8,insufficient:.1},confidence:.8}}}).decision.overall_choice).toBe('negative')})
