// @vitest-environment node
import {it,expect} from 'vitest'
import {readFileSync} from 'node:fs'
import {syntheticV11} from '../../../tests/fixtures/historical-v11'
import {completeSyntheticTasks,fakeThemeDecision} from '../../../tests/fixtures/historical-v9'
import {THEME_KEYS,type ThemeDecision} from './jev-themes'
import {v9Payload,deriveV9} from './historical-v9-core'
import {validateV11Snapshot,deriveV11,replayV11Audit,compareV11Sources,v11Costs,V11_CONFIG} from './historical-v11-core'
import {V11_THRESHOLDS,V11_DEFAULT_THRESHOLD,V11_INTERPRETATIONS,v11Payload,v11Threshold,meetsV11Threshold} from './jev-v11-calibration'
it('source is the entire frozen V9 snapshot, never V10:103 identities/texts/ratings, immutable config and audit lineage',()=>{const h=syntheticV11(),before=JSON.stringify(h.source);validateV11Snapshot(h.job);expect(h.job.snapshot.reviews).toEqual(h.source.snapshot.reviews);expect(h.reviews).toHaveLength(103);expect(h.reviews.filter(r=>r.analysis_text)).toHaveLength(97);h.job.snapshot.reviews[0].rating=1;expect(()=>validateV11Snapshot(h.job)).toThrow('SOURCE_CHANGED');expect(JSON.stringify(h.source)).toBe(before);const next=syntheticV11();next.job.snapshot.v11_config.thresholds.professionalism.negative_threshold=.75;expect(()=>validateV11Snapshot(next.job)).toThrow('CONFIG_CHANGED');next.job.snapshot.calibration_audit.status='draft';expect(()=>validateV11Snapshot(next.job)).toThrow('AUDIT_REQUIRED')})
it('exact21 V9 questions preserved, only4 human interpretations change, same Phase1 sentiment and no Google/original input',()=>{const a=v9Payload('themes','r1','English'),b=v11Payload('themes','r1','English');expect(Object.keys(b.questions)).toEqual(THEME_KEYS);let exact=0;for(const key of THEME_KEYS)if(!(key in V11_INTERPRETATIONS)){expect(b.questions[key]).toEqual(a.questions[key]);exact++}expect(exact).toBe(21);expect(b.state).toEqual({review_alias:'r1',analysis_text:'English'});expect(v11Payload('sentiment','r1','English')).toEqual(v9Payload('sentiment','r1','English'));expect(JSON.stringify(b.state)).not.toMatch(/rating|review_context|original|findings/);expect(V11_CONFIG).toMatchObject({analysis_engine:'jev_hybrid_human_aligned',question_set:'themes_v11_human_aligned_v1',threshold_version:'jev-theme-thresholds-v2',theme_repeat_count:3,sentiment_repeat_count:1,concurrency:8})})
it.each([
  ['professionalism','excellent service','Do NOT require the words professional'],
  ['professionalism','The waitress is very nice','must NOT automatically create professionalism'],
  ['coordination','excellent service','overall service execution'],
  ['coordination','Everything arrived quickly','must NOT automatically create coordination from speed alone'],
  ['communication','They speak Russian','ALONE is absent'],
  ['communication','The waiter clearly explained how the menu worked','is positive'],
  ['communication','They could not understand our order','is negative'],
  ['attentiveness','Very good service and warm pleasant staff','can express positive customer care'],
] as const)('offline prompt contract for %s: %s', (theme,example,rule)=>{const q=v11Payload('themes','r1',example).questions[theme] as {instructions:string};expect(q.instructions.toLowerCase()).toContain(example.toLowerCase());expect(q.instructions).toContain(rule);expect(q.instructions).not.toContain('Generic good service alone does not establish');expect(q.instructions).toContain('untrusted')})
it('asymmetric thresholds support light positive service and remove only the intended negative probabilities',()=>{expect(V11_DEFAULT_THRESHOLD).toBe(.60);expect(Object.keys(V11_THRESHOLDS)).toHaveLength(25);expect(V11_THRESHOLDS).toMatchObject({food_quality:{positive_threshold:.60,negative_threshold:.60},friendly_staff:{positive_threshold:.55,negative_threshold:.55},attentiveness:{positive_threshold:.60,negative_threshold:.70},professionalism:{positive_threshold:.60,negative_threshold:.80},coordination:{positive_threshold:.50,negative_threshold:.70},communication:{positive_threshold:.85,negative_threshold:.85},wait_time:{positive_threshold:.55,negative_threshold:.55},atmosphere:{positive_threshold:.55,negative_threshold:.55}});expect(meetsV11Threshold((.6+.6+.6)/3,v11Threshold('attentiveness','positive'))).toBe(true);expect(meetsV11Threshold(.60-1e-10,.60)).toBe(false)
 const h=syntheticV11();completeSyntheticTasks(h.tasks);for(const t of h.tasks.filter(t=>t.kind==='themes')){const d=fakeThemeDecision();d.themes.attentiveness={choice:'both',probabilities:{absent:.06,positive:.283,negative:.24,both:.417}};d.themes.professionalism={choice:'both',probabilities:{absent:.05,positive:.16,negative:.19,both:.60}};d.themes.coordination={choice:'positive',probabilities:{absent:.49,positive:.51,negative:0,both:0}};d.themes.communication={choice:'positive',probabilities:{absent:.20,positive:.80,negative:0,both:0}};t.result=d}
 const d=deriveV11(h.reviews,h.tasks),themes=d.findings.filter(f=>f.review_id===h.reviews[0].id);expect(themes).toEqual(expect.arrayContaining([expect.objectContaining({theme_key:'attentiveness',sentiment:'positive'}),expect.objectContaining({theme_key:'professionalism',sentiment:'positive'}),expect.objectContaining({theme_key:'coordination',sentiment:'positive'})]));expect(themes.some(f=>['attentiveness','professionalism'].includes(f.theme_key)&&f.sentiment==='negative')).toBe(false);expect(themes.some(f=>f.theme_key==='communication')).toBe(false);expect(deriveV9(h.reviews,h.tasks).findings.length).toBeGreaterThan(d.findings.length);expect(themes[0]).toMatchObject({evidence:null,threshold_version:'jev-theme-thresholds-v2'})})
it('human replay supports both polarities/uncertain, meaningful retention and conditional experimental interpretation',()=>{const h=syntheticV11();completeSyntheticTasks(h.tasks);const d=deriveV11(h.reviews,h.tasks);d.findings=d.findings.filter(f=>!h.reviews.slice(18,30).some(r=>r.id===f.review_id));const r=replayV11Audit(h.audit,d);expect(r).toMatchObject({human_valid:20,human_rejected:10,human_valid_retained:18,human_valid_removed:2,human_rejected_removed:10,observed_validation_rate:1,valid_signal_retention:.9,target_valid_retained:16,preferred_valid_retained:18,interpretation:'NEEDS_REVIEW'});h.audit.labels[0].choice='uncertain';d.cross_rating_analysis.analysis_unavailable_review_ids=[h.reviews[1].id];const partial=replayV11Audit(h.audit,d);expect(partial.uncertain).toBe(1);expect(partial.unavailable).toBe(1);expect(partial.comparable).toBe(28);expect(partial.retention_target_met).toBeNull();expect(partial.interpretation).toBe('NEEDS_REVIEW')})
it('PROMISING needs all three conditions:>=80%true retention,>=5rejected removed,>=2/3communication rejected removed',()=>{const h=syntheticV11();completeSyntheticTasks(h.tasks);const d=deriveV11(h.reviews,h.tasks);for(const i of h.audit.items.slice(20,23))i.theme_key='communication';h.audit.items.slice(20).forEach(i=>{d.findings=d.findings.filter(f=>f.review_id!==i.review_id)});expect(replayV11Audit(h.audit,d).interpretation).toBe('PROMISING');d.findings=d.findings.filter(f=>!h.reviews.slice(0,5).some(r=>r.id===f.review_id));expect(replayV11Audit(h.audit,d).interpretation).toBe('NEEDS_REVIEW')})
it('cross ratings remain text-driven, unavailable is never a fabricated issue; no Price score',()=>{const h=syntheticV11();completeSyntheticTasks(h.tasks);const d=deriveV11(h.reviews,h.tasks);expect(d.cross_rating_analysis.review_analyses[0].axes.service.status).toBe('low_score_unexplained');expect(d.findings.some(f=>f.theme_key==='attentiveness')).toBe(false);expect(JSON.stringify(d.cross_rating_analysis)).not.toMatch(/price_rating/)})
it('V9/V11 and V10/V11 compare only persisted sources, costs, timings, models and audited true-signal recovery',()=>{const h=syntheticV11();completeSyntheticTasks(h.tasks);const d=deriveV11(h.reviews,h.tasks),cost=v11Costs({...h.usage,served_models:['jev-new'],jev_input_tokens:1_000_000,sol_narrative_input_tokens:2000,sol_narrative_output_tokens:1000,jev_elapsed_ms:10000,sol_narrative_elapsed_ms:1000},120000),c=compareV11Sources(h.source,h.comparison10,h.reviews,d,cost,h.audit);for(const r of [c.v9,c.v10]){expect(r.dataset).toMatchObject({reference:103,v11:103,common:103,reference_only:0,v11_only:0,identical:true,identical_analysis_text:103});expect(r.models.different).toBe(true);expect(r.cross_rating.service.statuses).toHaveProperty('confirmed_negative');expect(r.elapsed).toHaveProperty('sol_narrative')};expect(c.findings_totals).toEqual({v9:97,v10:6,v11:97});expect(c.v10_valid_signal_recovery).toMatchObject({human_valid_lost_by_v10:14,recovered_by_v11:14,still_missing:0});expect(c.v9.cost.total.reference).toBe(h.source.snapshot.publication.consultant_report.analysis_pipeline.total_estimated_cost_usd);expect(cost.jev_cost_usd).toBe(.042);expect(cost.sol_narrative_cost_usd).toBe(.014)})
it('schema protects existing resources, has no automatic model/report/audit launch, and no promotion of manager reports',()=>{const sql=readFileSync(new URL('../../migrations/20261008093023_historical_jev_human_aligned_v11.sql',import.meta.url),'utf8');expect(sql).not.toMatch(/from public\.(reviews|review_translations)|insert into public\.historical_establishment_reports|update public\.analysis_v9_finding|cron\./);expect(sql).toContain("'source_snapshot',s.snapshot");expect(sql).toContain("'comparison_v10_generation_id'");expect(sql).toContain('least(p_limit,8)');expect(sql).toContain('REPORT_V11_SOURCE_IMMUTABLE');expect(sql).toContain('complete_experimental_v11_report');expect(sql).toContain('pg_advisory_xact_lock');expect(sql).toContain('revoke all')})
