import {AXES,type Axis,type ConsultantReportData} from './consultant-contract.ts'
import {deriveV9,V9_THEME_AXES,type V9Job,type V9Task,type V9Usage} from './historical-v9-core.ts'
import {V10_THRESHOLD_VERSION,V10_QUESTION_SET,V10_THRESHOLDS,v10Threshold,meetsV10Threshold} from './jev-v10-calibration.ts'
import {GOLD_CHOICES,type GoldChoice} from './gold-taxonomy.ts'
import {type AuditItem,type AuditLabel} from './v9-finding-audit-core.ts'
import type {ReputationReview} from './reputation-metrics.ts'
const findingKey=(f:{review_id:string;theme_key:string;sentiment:string})=>f.review_id+':'+f.theme_key+':'+f.sentiment
export const FIRST_V10_SOURCE='91b77ec8-b58c-4735-a96d-496fa1a5404a',FIRST_V10_AUDIT='9da6153d-3501-4df1-8266-f27398d3f0de',FIRST_V10_ESTABLISHMENT='d57ed022-5924-41f2-a53f-685eb4de4d50'
export const V10_CONFIG={analysis_engine:'jev_hybrid_calibrated',requested_model:'jev-latest',theme_repeat_count:3,sentiment_repeat_count:1,concurrency:8,threshold_version:V10_THRESHOLD_VERSION,question_set:V10_QUESTION_SET,thresholds:V10_THRESHOLDS} as const
export interface CalibrationAudit {id:string;status:string;source_v8_generation_id:string;source_v9_generation_id:string;taxonomy_version:string;comparison:Record<string,unknown>;items:AuditItem[];labels:AuditLabel[]}
export interface V10Job extends Omit<V9Job,'snapshot'>{snapshot:V9Job['snapshot']&{source_snapshot:V9Job['snapshot']['source_snapshot']&{analysis_version:number};v10_config:typeof V10_CONFIG;calibration_audit:CalibrationAudit}}
export function validateV10Snapshot(run:V10Job){const s=run.snapshot,a=s.calibration_audit;if(s.analysis_version!==10||s.analysis_engine!==V10_CONFIG.analysis_engine||s.source_generation_id!==FIRST_V10_SOURCE||s.source_snapshot.analysis_version!==9||JSON.stringify(s.reviews)!==JSON.stringify(s.source_snapshot.reviews)||new Set(s.reviews.map(r=>r.id)).size!==s.reviews.length||s.reviews.some(r=>typeof r.analysis_text!=='string'||r.analysis_text.trim()&&r.analysis_language!=='en'))throw new Error('REPORT_V10_SOURCE_CHANGED')
  if(!a||a.id!==FIRST_V10_AUDIT||a.status!=='completed'||a.source_v9_generation_id!==FIRST_V10_SOURCE||a.taxonomy_version!=='gold-taxonomy-v1'||a.items.length!==30||new Set(a.items.map(findingKey)).size!==30||a.labels.length!==30||new Set(a.labels.map(l=>l.item_id)).size!==30||a.items.some(i=>!s.reviews.some(r=>r.id===i.review_id)||!GOLD_CHOICES.includes(a.labels.find(l=>l.item_id===i.id)?.choice as GoldChoice)))throw new Error('REPORT_V10_AUDIT_REQUIRED')
  // JSONB reorders keys, so compare the versioned configuration semantically.
  const c=s.v10_config;if(!c||Object.entries(V10_CONFIG).some(([key,value])=>key!=='thresholds'&&c[key as keyof typeof c]!==value)||Object.keys(c.thresholds).length!==25||Object.keys(V10_THRESHOLDS).some(key=>{const k=key as keyof typeof V10_THRESHOLDS;return c.thresholds[k]?.positive_threshold!==V10_THRESHOLDS[k].positive_threshold||c.thresholds[k]?.negative_threshold!==V10_THRESHOLDS[k].negative_threshold}))throw new Error('REPORT_V10_CONFIG_CHANGED')
}
export function deriveV10(reviews:ReputationReview[],tasks:V9Task[]){const d=deriveV9(reviews,tasks,v10Threshold,meetsV10Threshold);return {...d,findings:d.findings.map(f=>({...f,threshold_used:v10Threshold(f.theme_key as keyof typeof V10_THRESHOLDS,f.sentiment),threshold_version:V10_THRESHOLD_VERSION,question_set_version:V10_QUESTION_SET}))}}
export type V10Usage=Omit<V9Usage,'threshold'>&{threshold_version:string;question_set:string;thresholds:typeof V10_THRESHOLDS}
export function v10Costs(m:V10Usage,endToEnd:number|null){const jev_cost_usd=m.jev_input_tokens/1_000_000*m.rates.jev_input,sol_narrative_cost_usd=(m.sol_narrative_input_tokens*m.rates.sol_input+m.sol_narrative_output_tokens*m.rates.sol_output)/1_000_000;return {...m,jev_cost_usd,sol_narrative_cost_usd,total_estimated_cost_usd:jev_cost_usd+sol_narrative_cost_usd,end_to_end_elapsed_ms:endToEnd,cost_label:'ESTIMATION_AT_CONFIGURED_RATE',per_review_sol_extraction_calls:0}}
export function replayV10Audit(a:CalibrationAudit,d:ReturnType<typeof deriveV10>){const findings=new Set(d.findings.map(findingKey)),unknown=new Set(d.cross_rating_analysis.analysis_unavailable_review_ids)
  const cases=a.items.map(i=>{const human=a.labels.find(l=>l.item_id===i.id)?.choice;if(!human)throw new Error('REPORT_V10_AUDIT_REQUIRED');const valid=human!=='uncertain'&&(human===i.sentiment||human==='both'),v10_retained=findings.has(findingKey(i)),unavailable=unknown.has(i.review_id),positive=findings.has(i.review_id+':'+i.theme_key+':positive'),negative=findings.has(i.review_id+':'+i.theme_key+':negative');return {review_id:i.review_id,theme_key:i.theme_key,v9_sentiment:i.sentiment,human,v10_choice:unavailable?null:positive?negative?'both':'positive':negative?'negative':'absent',v9_human_valid:valid,v10_retained:unavailable?null:v10_retained,uncertain:human==='uncertain',unavailable}})
  const tally=(rows:typeof cases)=>{const comparable=rows.filter(r=>!r.uncertain&&!r.unavailable),valid=comparable.filter(r=>r.v9_human_valid),rejected=comparable.filter(r=>!r.v9_human_valid),valid_retained=valid.filter(r=>r.v10_retained).length,rejected_retained=rejected.filter(r=>r.v10_retained).length;return {controlled:rows.length,uncertain:rows.filter(r=>r.uncertain).length,unavailable:rows.filter(r=>r.unavailable).length,comparable:comparable.length,human_valid:valid.length,human_rejected:rejected.length,human_valid_retained:valid_retained,human_valid_removed:valid.length-valid_retained,human_rejected_removed:rejected.length-rejected_retained,human_rejected_retained:rejected_retained,observed_validation_rate:valid_retained+rejected_retained?valid_retained/(valid_retained+rejected_retained):null,valid_signal_retention:valid.length?valid_retained/valid.length:null,target_valid_retained:Math.ceil(valid.length*.8),retention_target_met:rows.some(r=>r.unavailable)?null:valid.length?valid_retained/valid.length>=.8:null}}
  return {source_audit_id:a.id,source_observed_comparison:a.comparison,...tally(cases),by_theme:Object.fromEntries([...new Set(cases.map(c=>c.theme_key))].map(theme=>[theme,tally(cases.filter(c=>c.theme_key===theme))])),cases,note:'Replay on the same human cases used for calibration; sample-specific, not independent global validation. Unavailable and uncertain cases are not treated as removed findings.'}
}
export interface V10ComparisonSource {generation_id:string;findings:{review_id:string;theme_key:string;sentiment:'positive'|'negative'}[];snapshot:{reviews:ReputationReview[];analysis_version?:number;publication?:{consultant_report?:ConsultantReportData}}}
export function compareV9V10(source:V10ComparisonSource,reviews:ReputationReview[],d:ReturnType<typeof deriveV10>,cost:ReturnType<typeof v10Costs>,audit:CalibrationAudit){const a=new Set(source.snapshot.reviews.map(r=>r.id)),b=new Set(reviews.map(r=>r.id)),commonIds=new Set([...a].filter(id=>b.has(id))),counts=(x:Set<string>,y:Set<string>)=>({v9:x.size,v10:y.size,common:[...x].filter(v=>y.has(v)).length,v9_only:[...x].filter(v=>!y.has(v)).length,v10_only:[...y].filter(v=>!x.has(v)).length}),match=(theme?:string,axis?:Axis)=>counts(new Set(source.findings.filter(f=>commonIds.has(f.review_id)&&(!theme||f.theme_key===theme)&&(!axis||V9_THEME_AXES[f.theme_key]===axis)).map(findingKey)),new Set(d.findings.filter(f=>commonIds.has(f.review_id)&&(!theme||f.theme_key===theme)&&(!axis||V9_THEME_AXES[f.theme_key]===axis)).map(findingKey))),old=source.snapshot.publication?.consultant_report?.analysis_pipeline,models9=[...old?.served_models??[]].sort(),models10=[...cost.served_models].sort(),delta=(x:number|null,y:number|null)=>({v9:x,v10:y,delta:x===null||y===null?null:y-x,delta_percent:x===null||y===null||x===0?null:(y-x)/x*100})
  return {source_generation_id:source.generation_id,dataset:{...counts(a,b),identical:a.size===commonIds.size&&b.size===commonIds.size,identical_analysis_text:reviews.filter(r=>source.snapshot.reviews.find(s=>s.id===r.id)?.analysis_text===r.analysis_text).length,identical_google_context:reviews.filter(r=>{const s=source.snapshot.reviews.find(s=>s.id===r.id);return JSON.stringify(s?.normalized_category_ratings)===JSON.stringify(r.normalized_category_ratings)&&JSON.stringify(s?.review_detailed_rating)===JSON.stringify(r.review_detailed_rating)&&JSON.stringify(s?.review_context)===JSON.stringify(r.review_context)}).length},findings:match(),axes:Object.fromEntries(AXES.map(axis=>[axis,match(undefined,axis)])),themes:Object.fromEntries(['attentiveness','professionalism','coordination','communication','atmosphere','friendly_staff','wait_time'].map(theme=>{const c=match(theme);return [theme,{...c,retained_count:c.common,removed_count:c.v9_only,added_count:c.v10_only}]})),audit_replay:replayV10Audit(audit,d),cost:{total:delta(old?.total_estimated_cost_usd??null,cost.total_estimated_cost_usd),jev:delta(old?.jev_cost_usd??null,cost.jev_cost_usd),sol_narrative:delta(old?.sol_narrative_cost_usd??null,cost.sol_narrative_cost_usd)},elapsed:delta(old?.end_to_end_elapsed_ms??null,cost.end_to_end_elapsed_ms),models:{v9:models9,v10:models10,different:JSON.stringify(models9)!==JSON.stringify(models10)},threshold_version:V10_THRESHOLD_VERSION,question_set:V10_QUESTION_SET}
}
