// @vitest-environment node
import {it,expect} from 'vitest'
import {readFileSync} from 'node:fs'
import {syntheticV10} from '../../../tests/fixtures/historical-v10'
import {completeSyntheticTasks,fakeThemeDecision} from '../../../tests/fixtures/historical-v9'
import {THEME_KEYS} from './jev-themes'
import {v9Payload,deriveV9} from './historical-v9-core'
import {V10_CONFIG,validateV10Snapshot,deriveV10,replayV10Audit,compareV9V10,v10Costs} from './historical-v10-core'
import {V10_DEFINITIONS,V10_DEFAULT_THRESHOLD,V10_THRESHOLDS,v10Threshold,v10Payload,meetsV10Threshold} from './jev-v10-calibration'
it('decimal averaging does not drop a signal precisely on its threshold',()=>{expect(meetsV10Threshold((.7+.7+.7)/3,.7)).toBe(true);expect(meetsV10Threshold(.7-1e-10,.7)).toBe(false);expect(meetsV10Threshold(.5,.7)).toBe(false)})
it('V10 copies exact V9 review IDs, English texts and Google metadata, protects frozen sources/config/audit',()=>{const h=syntheticV10(),before=JSON.stringify(h.source);validateV10Snapshot(h.job);expect(h.job.snapshot.reviews).toEqual(h.source.snapshot.reviews);expect(h.reviews).toHaveLength(103);expect(h.reviews.filter(r=>r.analysis_text)).toHaveLength(97);h.job.snapshot.reviews[0].rating=1;expect(()=>validateV10Snapshot(h.job)).toThrow('SOURCE_CHANGED');expect(JSON.stringify(h.source)).toBe(before);const next=syntheticV10();next.job.snapshot.v10_config.thresholds.communication.positive_threshold=.5;expect(()=>validateV10Snapshot(next.job)).toThrow('CONFIG_CHANGED');next.job.snapshot.calibration_audit.status='draft';expect(()=>validateV10Snapshot(next.job)).toThrow('AUDIT_REQUIRED')})
it('25 versioned questions: unchanged questions stay exact, only four requested definitions change; ratings never reach Jev',()=>{const a=v9Payload('themes','r1','English'),b=v10Payload('themes','r1','English');expect(Object.keys(b.questions)).toEqual(THEME_KEYS);expect(b.state).toEqual({review_alias:'r1',analysis_text:'English'});for(const theme of THEME_KEYS)if(!(theme in V10_DEFINITIONS))expect(b.questions[theme]).toEqual(a.questions[theme]);else expect(b.questions[theme]).not.toEqual(a.questions[theme]);expect(JSON.stringify(b.state)).not.toMatch(/rating|original|review_context/);expect(v10Payload('sentiment','r1','English')).toEqual(v9Payload('sentiment','r1','English'));expect(JSON.stringify(b.questions.communication)).toContain('Do NOT infer communication');expect(JSON.stringify(b.questions.professionalism)).toContain('competence');expect(JSON.stringify(b.questions.attentiveness)).toContain('do not require a detailed incident');expect(V10_CONFIG).toMatchObject({question_set:'themes_v10_calibrated_v1',threshold_version:'jev-theme-thresholds-v1',theme_repeat_count:3,sentiment_repeat_count:1,concurrency:8})})
it('centralized thresholds have two polarities and generic0.70; calibrated filtering changes only V10 outputs',()=>{expect(V10_DEFAULT_THRESHOLD).toBe(.7);for(const theme of THEME_KEYS)expect(v10Threshold(theme,'positive')).toBe(v10Threshold(theme,'negative'));expect(V10_THRESHOLDS).toMatchObject({attentiveness:{positive_threshold:.6},professionalism:{positive_threshold:.75},coordination:{positive_threshold:.7},communication:{positive_threshold:.85},food_quality:{positive_threshold:.7},friendly_staff:{positive_threshold:.6},wait_time:{positive_threshold:.6},atmosphere:{positive_threshold:.6}});const h=syntheticV10();completeSyntheticTasks(h.tasks);for(const t of h.tasks.filter(t=>t.kind==='themes')){const d=fakeThemeDecision();for(const key of ['attentiveness','communication'] as const)d.themes[key]={choice:'positive',probabilities:{absent:.2,positive:.8,negative:0,both:0}};t.result=d}expect(deriveV9(h.reviews,h.tasks).findings.filter(f=>f.theme_key==='communication')).toHaveLength(97);const d=deriveV10(h.reviews,h.tasks);expect(d.findings.some(f=>f.theme_key==='communication')).toBe(false);expect(d.findings.filter(f=>f.theme_key==='attentiveness')).toHaveLength(97);expect(d.findings[0]).toMatchObject({evidence:null,threshold_version:'jev-theme-thresholds-v1',question_set_version:'themes_v10_calibrated_v1'});expect(d.cross_rating_analysis.review_analyses[0].axes.service.status).toBe('low_score_unexplained');expect(JSON.stringify(d.cross_rating_analysis)).not.toMatch(/price_rating/)})
it('replays human validation vs retained/removed findings, uncertain and unavailable never masquerade as removals',()=>{const h=syntheticV10();completeSyntheticTasks(h.tasks);const d=deriveV10(h.reviews,h.tasks);d.findings=d.findings.filter(f=>!h.reviews.slice(17,27).some(r=>r.id===f.review_id));const r=replayV10Audit(h.audit,d);expect(r).toMatchObject({human_valid:20,human_rejected:10,human_valid_retained:17,human_valid_removed:3,human_rejected_removed:7,human_rejected_retained:3,valid_signal_retention:.85,observed_validation_rate:.85,retention_target_met:true,target_valid_retained:16});expect(r.by_theme.food_quality?.human_valid_removed).toBe(3);h.audit.labels[0].choice='uncertain';d.cross_rating_analysis.analysis_unavailable_review_ids=[h.reviews[1].id];const partial=replayV10Audit(h.audit,d);expect(partial.uncertain).toBe(1);expect(partial.unavailable).toBe(1);expect(partial.comparable).toBe(28);expect(partial.retention_target_met).toBeNull()})
it('comparison reads persisted V9 costs/models and dataset/counts instead of hardcoding outcomes',()=>{const h=syntheticV10();completeSyntheticTasks(h.tasks);const d=deriveV10(h.reviews,h.tasks),cost=v10Costs({...h.usage,served_models:['jev-new'],jev_input_tokens:1000000,sol_narrative_input_tokens:2000,sol_narrative_output_tokens:1000},120000),c=compareV9V10(h.source,h.reviews,d,cost,h.audit);expect(c.dataset).toMatchObject({v9:103,v10:103,common:103,v9_only:0,v10_only:0,identical:true,identical_analysis_text:103,identical_google_context:103});expect(c.models.different).toBe(true);expect(c.cost.total.v9).toBe(h.source.snapshot.publication.consultant_report.analysis_pipeline.total_estimated_cost_usd);expect(cost.jev_cost_usd).toBe(.042);expect(cost.sol_narrative_cost_usd).toBe(.014);expect(c.elapsed.v9).toBe(300000);expect(c.findings.common).toBe(97)})
it('migration cannot start reports or write any immutable source, and experimental completion never publishes over V9',()=>{const sql=readFileSync(new URL('../../migrations/20261008083415_historical_jev_calibrated_v10.sql',import.meta.url),'utf8');expect(sql).not.toMatch(/from public\.(reviews|review_translations)|insert into public\.historical_establishment_reports|update public\.analysis_v9_finding|cron\./);expect(sql).toContain("'source_snapshot',s.snapshot");expect(sql).toContain("'calibration_audit',audit_snapshot");expect(sql).toContain('least(p_limit,8)');expect(sql).toContain('REPORT_V10_SOURCE_IMMUTABLE');expect(sql).toContain('complete_experimental_v10_report');expect(sql).toContain('pg_advisory_xact_lock');expect(sql).toContain('revoke all')})
