import {AXES,type Axis,type ConsultantReportData} from './consultant-contract.ts'
import {deriveV9,V9_THEME_AXES,type V9Job,type V9Task,type V9Usage} from './historical-v9-core.ts'
import {V11_THRESHOLD_VERSION,V11_QUESTION_SET,V11_THRESHOLDS,v11Threshold,meetsV11Threshold} from './jev-v11-calibration.ts'
import {GOLD_CHOICES,type GoldChoice} from './gold-taxonomy.ts'
import {type AuditItem,type AuditLabel} from './v9-finding-audit-core.ts'
import type {ReputationReview} from './reputation-metrics.ts'
const findingKey=(f:{review_id:string;theme_key:string;sentiment:string})=>f.review_id+':'+f.theme_key+':'+f.sentiment
export const FIRST_V11_SOURCE='91b77ec8-b58c-4735-a96d-496fa1a5404a',FIRST_V11_AUDIT='9da6153d-3501-4df1-8266-f27398d3f0de',FIRST_V11_ESTABLISHMENT='d57ed022-5924-41f2-a53f-685eb4de4d50',FIRST_V11_COMPARISON='a6780368-1170-4574-b0f9-b65baf2c249d'
export const V11_CONFIG={analysis_engine:'jev_hybrid_human_aligned',requested_model:'jev-latest',theme_repeat_count:3,sentiment_repeat_count:1,concurrency:8,threshold_version:V11_THRESHOLD_VERSION,question_set:V11_QUESTION_SET,thresholds:V11_THRESHOLDS} as const
export interface CalibrationAudit {id:string;status:string;source_v8_generation_id:string;source_v9_generation_id:string;taxonomy_version:string;comparison:Record<string,unknown>;items:AuditItem[];labels:AuditLabel[]}
export interface V11Job extends Omit<V9Job,'snapshot'>{snapshot:V9Job['snapshot']&{source_snapshot:V9Job['snapshot']['source_snapshot']&{analysis_version:number};v11_config:typeof V11_CONFIG;comparison_v10_generation_id:string;calibration_audit:CalibrationAudit}}
export function validateV11Snapshot(run:V11Job){const s=run.snapshot,a=s.calibration_audit;if(s.analysis_version!==11||s.analysis_engine!==V11_CONFIG.analysis_engine||s.source_generation_id!==FIRST_V11_SOURCE||s.comparison_v10_generation_id!==FIRST_V11_COMPARISON||s.source_snapshot.analysis_version!==9||JSON.stringify(s.reviews)!==JSON.stringify(s.source_snapshot.reviews)||new Set(s.reviews.map(r=>r.id)).size!==s.reviews.length||s.reviews.some(r=>typeof r.analysis_text!=='string'||r.analysis_text.trim()&&r.analysis_language!=='en'))throw new Error('REPORT_V11_SOURCE_CHANGED')
  if(!a||a.id!==FIRST_V11_AUDIT||a.status!=='completed'||a.source_v9_generation_id!==FIRST_V11_SOURCE||a.taxonomy_version!=='gold-taxonomy-v1'||a.items.length!==30||new Set(a.items.map(findingKey)).size!==30||a.labels.length!==30||new Set(a.labels.map(l=>l.item_id)).size!==30||a.items.some(i=>!s.reviews.some(r=>r.id===i.review_id)||!GOLD_CHOICES.includes(a.labels.find(l=>l.item_id===i.id)?.choice as GoldChoice)))throw new Error('REPORT_V11_AUDIT_REQUIRED')
  // JSONB reorders keys, so compare the versioned configuration semantically.
  const c=s.v11_config;if(!c||Object.entries(V11_CONFIG).some(([key,value])=>key!=='thresholds'&&c[key as keyof typeof c]!==value)||Object.keys(c.thresholds).length!==25||Object.keys(V11_THRESHOLDS).some(key=>{const k=key as keyof typeof V11_THRESHOLDS;return c.thresholds[k]?.positive_threshold!==V11_THRESHOLDS[k].positive_threshold||c.thresholds[k]?.negative_threshold!==V11_THRESHOLDS[k].negative_threshold}))throw new Error('REPORT_V11_CONFIG_CHANGED')
}
export function deriveV11(reviews:ReputationReview[],tasks:V9Task[]){const d=deriveV9(reviews,tasks,v11Threshold,meetsV11Threshold);return {...d,findings:d.findings.map(f=>({...f,threshold_used:v11Threshold(f.theme_key as keyof typeof V11_THRESHOLDS,f.sentiment),threshold_version:V11_THRESHOLD_VERSION,question_set_version:V11_QUESTION_SET}))}}
export type V11Usage=Omit<V9Usage,'threshold'>&{threshold_version:string;question_set:string;thresholds:typeof V11_THRESHOLDS}
export function v11Costs(m:V11Usage,endToEnd:number|null){const jev_cost_usd=m.jev_input_tokens/1_000_000*m.rates.jev_input,sol_narrative_cost_usd=(m.sol_narrative_input_tokens*m.rates.sol_input+m.sol_narrative_output_tokens*m.rates.sol_output)/1_000_000;return {...m,jev_cost_usd,sol_narrative_cost_usd,total_estimated_cost_usd:jev_cost_usd+sol_narrative_cost_usd,end_to_end_elapsed_ms:endToEnd,cost_label:'ESTIMATION_AT_CONFIGURED_RATE',per_review_sol_extraction_calls:0}}
export function replayV11Audit(a:CalibrationAudit,d:ReturnType<typeof deriveV11>){const findings=new Set(d.findings.map(findingKey)),unknown=new Set(d.cross_rating_analysis.analysis_unavailable_review_ids)
  const cases=a.items.map(i=>{const human=a.labels.find(l=>l.item_id===i.id)?.choice;if(!human)throw new Error('REPORT_V11_AUDIT_REQUIRED');const valid=human!=='uncertain'&&(human===i.sentiment||human==='both'),v11_retained=findings.has(findingKey(i)),unavailable=unknown.has(i.review_id),positive=findings.has(i.review_id+':'+i.theme_key+':positive'),negative=findings.has(i.review_id+':'+i.theme_key+':negative');return {review_id:i.review_id,theme_key:i.theme_key,v9_sentiment:i.sentiment,human,v11_choice:unavailable?null:positive?negative?'both':'positive':negative?'negative':'absent',v9_human_valid:valid,v11_retained:unavailable?null:v11_retained,uncertain:human==='uncertain',unavailable}})
  const tally=(rows:typeof cases)=>{const comparable=rows.filter(r=>!r.uncertain&&!r.unavailable),valid=comparable.filter(r=>r.v9_human_valid),rejected=comparable.filter(r=>!r.v9_human_valid),valid_retained=valid.filter(r=>r.v11_retained).length,rejected_retained=rejected.filter(r=>r.v11_retained).length;return {controlled:rows.length,uncertain:rows.filter(r=>r.uncertain).length,unavailable:rows.filter(r=>r.unavailable).length,comparable:comparable.length,human_valid:valid.length,human_rejected:rejected.length,human_valid_retained:valid_retained,human_valid_removed:valid.length-valid_retained,human_rejected_removed:rejected.length-rejected_retained,human_rejected_retained:rejected_retained,observed_validation_rate:valid_retained+rejected_retained?valid_retained/(valid_retained+rejected_retained):null,valid_signal_retention:valid.length?valid_retained/valid.length:null,target_valid_retained:Math.ceil(valid.length*.8),preferred_valid_retained:Math.ceil(valid.length*.9),false_positive_removal_rate:rejected.length?(rejected.length-rejected_retained)/rejected.length:null,retention_target_met:rows.some(r=>r.unavailable)?null:valid.length?valid_retained/valid.length>=.8:null}}
  const global=tally(cases),communication=tally(cases.filter(c=>c.theme_key==='communication')),interpretation=global.unavailable>0||global.uncertain>0?'NEEDS_REVIEW':global.valid_signal_retention!==null&&global.valid_signal_retention>=.80&&global.human_rejected_removed>=5&&communication.human_rejected>0&&communication.human_rejected_removed/communication.human_rejected>=2/3?'PROMISING':'NEEDS_REVIEW'
  return {source_audit_id:a.id,source_observed_comparison:a.comparison,...global,interpretation,communication_rejected_removed:communication.human_rejected_removed,communication_human_rejected:communication.human_rejected,by_theme:Object.fromEntries([...new Set(cases.map(c=>c.theme_key))].map(theme=>[theme,tally(cases.filter(c=>c.theme_key===theme))])),cases,note:'Replay on the same human cases used for calibration; sample-specific, not independent global validation. Unavailable and uncertain cases are not treated as removed findings.'}
}
export interface V11ComparisonSource {generation_id:string;findings:{review_id:string;theme_key:string;sentiment:'positive'|'negative'}[];snapshot:{reviews:ReputationReview[];analysis_version?:number;publication?:{consultant_report?:ConsultantReportData}}}
export function compareV11Reference(reference:V11ComparisonSource,version:9|10,reviews:ReputationReview[],derived:ReturnType<typeof deriveV11>,cost:ReturnType<typeof v11Costs>){
  const before=new Map(reference.snapshot.reviews.map(r=>[r.id,r])),current=new Map(reviews.map(r=>[r.id,r])),common=new Set([...before.keys()].filter(id=>current.has(id))),unavailable=new Set(derived.cross_rating_analysis.analysis_unavailable_review_ids)
  const counts=(a:Set<string>,b:Set<string>)=>({reference:a.size,v11:b.size,common:[...a].filter(k=>b.has(k)).length,reference_only:[...a].filter(k=>!b.has(k)).length,v11_only:[...b].filter(k=>!a.has(k)).length})
  const findings=(theme?:string,axis?:Axis)=>counts(new Set(reference.findings.filter(f=>common.has(f.review_id)&&(!theme||f.theme_key===theme)&&(!axis||V9_THEME_AXES[f.theme_key]===axis)).map(findingKey)),new Set(derived.findings.filter(f=>common.has(f.review_id)&&(!theme||f.theme_key===theme)&&(!axis||V9_THEME_AXES[f.theme_key]===axis)).map(findingKey)))
  const report=reference.snapshot.publication?.consultant_report,prior=version===9?report?.analysis_pipeline:report?.calibrated_analysis_pipeline,priorCross=report?.cross_rating_analysis,referenceUnavailable=new Set(priorCross?.analysis_unavailable_review_ids??[]),models=[...prior?.served_models??[]].sort(),models11=[...cost.served_models].sort(),delta=(a:number|null,b:number|null)=>({reference:a,v11:b,delta:a===null||b===null?null:b-a,delta_percent:a===null||b===null||a===0?null:(b-a)/a*100})
  const cross_rating=Object.fromEntries((['food','service','atmosphere'] as const).map(axis=>{const r=priorCross?.review_analyses.filter(r=>common.has(r.review_id)&&!unavailable.has(r.review_id)&&!referenceUnavailable.has(r.review_id))??[],v=derived.cross_rating_analysis.review_analyses.filter(r=>common.has(r.review_id)&&!unavailable.has(r.review_id)&&!referenceUnavailable.has(r.review_id));return [axis,{comparable_reviews:v.length,statuses:Object.fromEntries(['confirmed_negative','low_score_unexplained','textual_issue_despite_high_score','positive_consistent','mixed_text_signal','high_score_without_text_signal','no_category_rating'].map(status=>[status,{reference:r.filter(x=>x.axes[axis].status===status).length,v11:v.filter(x=>x.axes[axis].status===status).length}]))}]}))
  return {reference_version:version,source_generation_id:reference.generation_id,dataset:{...counts(new Set(before.keys()),new Set(current.keys())),identical:before.size===common.size&&current.size===common.size,identical_analysis_text:reviews.filter(r=>before.get(r.id)?.analysis_text===r.analysis_text).length},findings:findings(),axes:Object.fromEntries(AXES.map(axis=>[axis,findings(undefined,axis)])),themes:Object.fromEntries(['attentiveness','professionalism','coordination','communication','friendly_staff','atmosphere','wait_time'].map(theme=>[theme,findings(theme)])),cross_rating,cost:{total:delta(prior?.total_estimated_cost_usd??null,cost.total_estimated_cost_usd),jev:delta(prior?.jev_cost_usd??null,cost.jev_cost_usd),sol_narrative:delta(prior?.sol_narrative_cost_usd??null,cost.sol_narrative_cost_usd)},elapsed:{jev:delta(prior?.jev_elapsed_ms??null,cost.jev_elapsed_ms),sol_narrative:delta(prior?.sol_narrative_elapsed_ms??null,cost.sol_narrative_elapsed_ms),end_to_end:delta(prior?.end_to_end_elapsed_ms??null,cost.end_to_end_elapsed_ms)},models:{reference:models,v11:models11,different:JSON.stringify(models)!==JSON.stringify(models11)}}
}
export function compareV11Sources(v9:V11ComparisonSource,v10:V11ComparisonSource,reviews:ReputationReview[],derived:ReturnType<typeof deriveV11>,cost:ReturnType<typeof v11Costs>,audit:CalibrationAudit){
  const auditReplay=replayV11Audit(audit,derived),v10Keys=new Set(v10.findings.map(findingKey)),v11Keys=new Set(derived.findings.map(findingKey)),v10Unknown=new Set(v10.snapshot.publication?.consultant_report?.cross_rating_analysis?.analysis_unavailable_review_ids??[]),v11Unknown=new Set(derived.cross_rating_analysis.analysis_unavailable_review_ids)
  const humanValidLostByV10=audit.items.filter(i=>{const choice=audit.labels.find(l=>l.item_id===i.id)?.choice;return choice!=='uncertain'&&(choice===i.sentiment||choice==='both')&&!v10Unknown.has(i.review_id)&&!v10Keys.has(findingKey(i))}),restoration=humanValidLostByV10.filter(i=>!v11Unknown.has(i.review_id)&&v11Keys.has(findingKey(i)))
  return {v9:compareV11Reference(v9,9,reviews,derived,cost),v10:compareV11Reference(v10,10,reviews,derived,cost),findings_totals:{v9:new Set(v9.findings.map(findingKey)).size,v10:new Set(v10.findings.map(findingKey)).size,v11:derived.findings.length},audit_replay:auditReplay,v10_valid_signal_recovery:{human_valid_lost_by_v10:humanValidLostByV10.length,recovered_by_v11:restoration.length,still_missing:humanValidLostByV10.filter(i=>!v11Unknown.has(i.review_id)&&!v11Keys.has(findingKey(i))).length,unavailable:humanValidLostByV10.filter(i=>v11Unknown.has(i.review_id)).length},threshold_version:V11_THRESHOLD_VERSION,question_set:V11_QUESTION_SET}
}
