// @vitest-environment node
import {afterEach,it,expect,vi} from 'vitest'
import {FIRST_V11_ESTABLISHMENT,FIRST_V11_SOURCE,FIRST_V11_AUDIT,V11_CONFIG} from './historical-v11-core'
const auth=vi.hoisted(()=>({requireUser:vi.fn(),assertMembership:vi.fn()}));vi.mock('./auth.ts',()=>auth);afterEach(()=>{vi.unstubAllGlobals();vi.clearAllMocks()})
async function harness(mode='normal'){const rpc=vi.fn(async()=>({data:{generation_id:'v11-fixture',establishment_id:FIRST_V11_ESTABLISHMENT,language:'vi',status:'queued',cursor:0,total_steps:389,snapshot:{analysis_version:11}},error:null})),db={rpc,from:(table:string)=>({select(){return this},eq(){return this},single:async()=>({data:table==='profiles'?{preferred_language:'vi'}:{id:mode==='other'?'other':FIRST_V11_ESTABLISHMENT,organization_id:'org'},error:null})})};auth.requireUser.mockImplementation(async()=>{if(mode==='unauthorized')throw new Error('UNAUTHORIZED');return {client:db,admin:db,user:{id:'u'}}});auth.assertMembership.mockImplementation(async()=>{if(mode==='forbidden')throw new Error('FORBIDDEN')});let handler!:(r:Request)=>Promise<Response>;vi.stubGlobal('Deno',{env:{get:(key:string)=>key==='TYPESAFE_API_KEY'&&mode!=='missing'?'synthetic-key':undefined},serve:(fn:typeof handler)=>{handler=fn}});vi.resetModules();await import('../generate-historical-report/index.ts');return {rpc,post:(payload:object={})=>handler(new Request('https://fixture.test',{method:'POST',body:JSON.stringify({establishment_id:FIRST_V11_ESTABLISHMENT,preferred_language:'vi',first_v11:true,...payload})}))}}
it('manual V11 uses only the source-seeding RPC; client model/source overrides cannot alter the pinned snapshot',async()=>{const h=await harness();expect((await h.post({source_generation_id:'wrong',model:'wrong'})).status).toBe(202);expect(h.rpc).toHaveBeenCalledExactlyOnceWith('enqueue_first_v11_report',{p_establishment_id:FIRST_V11_ESTABLISHMENT,p_organization_id:'org',p_user_id:'u',p_language:'vi',p_source_generation_id:FIRST_V11_SOURCE,p_audit_id:FIRST_V11_AUDIT,p_config:V11_CONFIG,p_rates:{jev_input:.042,sol_input:2,sol_output:10}})})
it.each(['missing','other','unauthorized','forbidden'])('V11 rejects %s without creating any run or calling a provider',async mode=>{const h=await harness(mode),r=await h.post();expect(r.status).toBe(mode==='unauthorized'?401:mode==='forbidden'?403:409);expect(h.rpc).not.toHaveBeenCalled()})



