// @vitest-environment node
import {afterEach,it,expect,vi} from 'vitest'
import {syntheticV9,fakeThemeDecision,completeSyntheticTasks} from '../../../tests/fixtures/historical-v9'
import {THEME_KEYS} from './jev-themes'
import {processHistoricalV9Run} from './historical-v9-worker'
import {processHistoricalRun} from './historical-report-worker'
const mocks=vi.hoisted(()=>({sol:vi.fn(),extract:vi.fn(),jev:vi.fn(),peak:0,active:0}))
vi.mock('./reputation-themes.ts',async original=>({...await original<object>(),structuredCall:mocks.sol}))
vi.mock('./consultant-report.ts',async original=>({...await original<object>(),extractConsultantBatch:mocks.extract}))
vi.mock('./jev.ts',async original=>({...await original<object>(),createJevClient:(_key:string,options:{onAttempt:()=>void;onUsage:(u:object,m:string)=>void})=>({evaluatePayload:async(payload:{questions:object},parser:(r:unknown)=>unknown)=>{mocks.active++;mocks.peak=Math.max(mocks.peak,mocks.active);try{mocks.jev(payload);await Promise.resolve();options.onAttempt();options.onUsage({input_tokens:100,output_tokens:10},'jev-fixture');const sentiment=Object.keys(payload.questions).length===1,answers=sentiment?{overall:{type:'choice',choice:'positive',confidence:1,probabilities:{positive:1,negative:0,insufficient:0}}}:Object.fromEntries(THEME_KEYS.map(key=>[key,{type:'choice',...fakeThemeDecision().themes[key]}]));return parser({model:'jev-fixture',usage:{input_tokens:100,output_tokens:10},answers})}finally{mocks.active--}}})}))
afterEach(()=>{vi.unstubAllGlobals();vi.clearAllMocks();mocks.peak=0;mocks.active=0})
function harness(){const h=syntheticV9();let publication:Record<string,unknown>|null=null;const rpc=vi.fn(async(name:string,args:Record<string,unknown>)=>{if(name==='claim_historical_jev_tasks'){const next=h.tasks.filter(t=>t.status==='pending').slice(0,8);next.forEach(t=>t.status='running');return {data:structuredClone(next),error:null}}if(name==='complete_historical_jev_task'){const task=h.tasks.find(t=>t.id===args.p_task_id)!;Object.assign(task,args.p_values);h.job.cursor++;const m=h.usage;m.jev_input_tokens+=task.input_tokens;m.jev_output_tokens+=task.output_tokens;if(task.kind==='themes')m.jev_theme_requests+=task.request_count;else m.jev_sentiment_requests+=task.request_count;m.served_models=['jev-fixture'];return {data:true,error:null}}if(name==='checkpoint_historical_report_run'){Object.assign(h.job,args.p_values);return {data:true,error:null}}if(name==='historical_v9_metrics_update'){const p=args.p_values as Record<string,unknown>;if(args.p_action==='jev_elapsed')h.usage.jev_elapsed_ms+=p.duration_ms as number;if(args.p_action==='narrative_begin'){h.usage.narrative_state='attempted';h.usage.sol_narrative_calls=1;h.job.ai_calls=1}if(args.p_action==='narrative_usage'){h.usage.sol_narrative_input_tokens=p.input_tokens as number;h.usage.sol_narrative_output_tokens=p.output_tokens as number}if(args.p_action==='narrative_finish'){h.usage.narrative_state=p.success?'completed':'fallback';h.usage.narrative_result=p.result as Record<string,unknown>|null;h.usage.narrative_error=p.error_code as string|null;h.usage.sol_narrative_elapsed_ms=p.duration_ms as number;h.usage.usage_complete=p.usage_complete as boolean}return {data:true,error:null}}if(name==='complete_historical_report_run'){publication=args.p_report as Record<string,unknown>;h.job.status='completed';return {data:true,error:null}}throw new Error('unexpected RPC')})
 const db={rpc,from:(table:string)=>({select(){return this},eq(){return this},single:async()=>({data:table==='historical_jev_run_metrics'?structuredClone(h.usage):table==='historical_report_runs'?structuredClone(h.job):null,error:null}),limit:async()=>({data:structuredClone(h.tasks),error:null})})};let sourceRead=false;const from=db.from;db.from=(table:string)=>{const q=from(table);if(table==='historical_report_runs'){const eq=q.eq;q.eq=function(...args:unknown[]){if(args[0]==='generation_id')sourceRead=true;return eq.call(this)};q.single=async()=>({data:sourceRead?structuredClone(h.source):structuredClone(h.job),error:null})}return q as typeof q}
 vi.stubGlobal('Deno',{env:{get:(key:string)=>['TYPESAFE_API_KEY','OPENAI_API_KEY'].includes(key)?'synthetic-key':undefined}})
 mocks.sol.mockImplementation(async(_instructions,input,_schema,_max,record)=>{await record({input_tokens:1000,output_tokens:200});return {data:{axes:[],explanations:[],manager_summary:'Les avis évalués mettent en avant les plats.',summary_supporting_keys:input.allowed_summary_keys},usage:{input_tokens:1000,output_tokens:200}}})
 return {...h,db,rpc,get publication(){return publication}}
}
it('durable V9 dispatch:388 Jev evaluations max8 concurrent, zero Sol per-review, then exactly one aggregate-only narrative',async()=>{const h=harness(),before=JSON.stringify(h.source);expect(await processHistoricalRun(h.db as never,structuredClone(h.job) as never,'worker')).toMatchObject({status:'running'});expect(mocks.jev).toHaveBeenCalledTimes(388);expect(mocks.peak).toBeLessThanOrEqual(8);expect(mocks.extract).not.toHaveBeenCalled();expect(mocks.sol).not.toHaveBeenCalled();expect(h.job.cursor).toBe(388);expect(h.usage.jev_theme_requests).toBe(291);expect(h.usage.jev_sentiment_requests).toBe(97);expect(await processHistoricalV9Run(h.db as never,structuredClone(h.job),'worker')).toMatchObject({status:'completed'});expect(mocks.sol).toHaveBeenCalledTimes(1);expect(mocks.extract).not.toHaveBeenCalled();expect(JSON.stringify(mocks.sol.mock.calls[0][1])).not.toMatch(/ENGLISH_CUSTOMER_SENTINEL|Русский|analysis_text|original_text|review_ids/);expect(h.publication).toMatchObject({analysis_version:9,consultant_report:{analysis_engine:'jev_hybrid',cross_rating_analysis:{total_reviews:103},analysis_pipeline:{per_review_sol_extraction_calls:0,sol_narrative_calls:1,jev_theme_requests:291,jev_sentiment_requests:97}}});expect(JSON.stringify(h.source)).toBe(before);expect(h.db.from).not.toHaveProperty('reviews')})
it('Sol narrative failure uses deterministic fallback; resumed paid/attempted narrative is never called twice',async()=>{const h=harness();completeSyntheticTasks(h.tasks);h.job.cursor=388;mocks.sol.mockRejectedValueOnce(new Error('OPENAI_HTTP_500'));expect(await processHistoricalV9Run(h.db as never,h.job,'worker')).toMatchObject({status:'completed'});expect(mocks.sol).toHaveBeenCalledTimes(1);expect(h.usage.narrative_state).toBe('fallback');expect(h.usage.sol_narrative_calls).toBe(1);expect(mocks.extract).not.toHaveBeenCalled();const next=harness();completeSyntheticTasks(next.tasks);next.job.cursor=388;next.usage.narrative_state='attempted';next.usage.sol_narrative_calls=1;mocks.sol.mockClear();await processHistoricalV9Run(next.db as never,next.job,'worker');expect(mocks.sol).not.toHaveBeenCalled();expect(next.usage.narrative_state).toBe('fallback')})
