import {AXES,type Axis,type ConsultantReportData} from './consultant-contract.ts'
import {CATEGORY_THEMES,crossRatingAnalysis} from './cross-rating-analysis.ts'
import {THEME_KEYS,themePayload,themePresence,type ThemeDecision} from './jev-themes.ts'
import {benchmarkPayload,jevPayload,parseUsage,type Choice,type SystemOnePayload} from './jev.ts'
import type {ReputationReview} from './reputation-metrics.ts'
export const FIRST_V9_SOURCE='307025ef-05b1-401e-8f6d-e48ca5677553',FIRST_V9_ESTABLISHMENT='d57ed022-5924-41f2-a53f-685eb4de4d50'
export const V9_CONFIG={analysis_engine:'jev_hybrid',requested_model:'jev-latest',theme_repeat_count:3,sentiment_repeat_count:1,concurrency:8,threshold:.5,question_set:'themes_phase2_v7'} as const
export interface V9Task {id:string;run_id:string;review_id:string;review_alias:string;position:number;kind:'sentiment'|'themes';repeat:number;status:'pending'|'running'|'completed'|'failed';result:unknown;error_code:string|null;request_count:number;retry_count:number;input_tokens:number;output_tokens:number;duration_ms:number;served_model:string|null;usage_complete:boolean}
export interface V9Finding {review_id:string;theme_key:string;sentiment:'positive'|'negative';evidence:null;analysis_source:'jev';probability_positive:number;probability_negative:number;repeat_stable:boolean}
export interface V9Classification {review_id:string;sentiment:'positive'|'negative'|'unavailable';basis:'jev'|'rating'|'unavailable';evidence:null|'';analysis_source:string;overall_choice?:Choice;probabilities?:Record<Choice,number>;confidence?:number}
export interface SentimentAnswer {overall_choice:Choice;overall_probabilities:Record<Choice,number>;overall_confidence:number}
export function v9Payload(kind:'sentiment'|'themes',alias:string,text:string):SystemOnePayload {const payload=kind==='themes'?themePayload(V9_CONFIG.requested_model,alias,text):(()=>{const p=jevPayload(V9_CONFIG.requested_model,alias,text);return {...p,questions:{overall:p.questions.overall}}})();return benchmarkPayload(payload,7)}
export function parseV9Sentiment(raw:unknown){if(!raw||typeof raw!=='object')throw new Error('JEV_INVALID_RESPONSE');const d=raw as {model:unknown;answers?:{overall?:{type:unknown;choice:unknown;probabilities:Record<Choice,number>;confidence:number}};usage:unknown},a=d.answers?.overall;if(typeof d.model!=='string'||!d.model.trim()||a?.type!=='choice'||!['positive','negative','insufficient'].includes(String(a.choice))||!a.probabilities||['positive','negative','insufficient'].some(k=>!Number.isFinite(a.probabilities[k as Choice])||a.probabilities[k as Choice]<0||a.probabilities[k as Choice]>1)||Math.abs(Object.values(a.probabilities).reduce((n,p)=>n+p,0)-1)>.01||!Number.isFinite(a.confidence)||a.confidence<0||a.confidence>1)throw new Error('JEV_INVALID_RESPONSE');return {model:d.model,usage:parseUsage(d.usage),decision:{overall_choice:a.choice as Choice,overall_probabilities:a.probabilities,overall_confidence:a.confidence}}}
export const V9_THEME_AXES=Object.fromEntries(Object.entries(CATEGORY_THEMES).flatMap(([axis,keys])=>keys.map(k=>[k,axis==='food'?'quality':axis]))) as Record<string,Axis>
export function deriveV9(reviews:ReputationReview[],tasks:V9Task[]){
  const findings:V9Finding[]=[],classifications:V9Classification[]=[],unavailableThemes:string[]=[],unavailableSentiment:string[]=[],reviewStatus:{review_id:string;theme_analysis:string;sentiment_analysis:string;error_codes:string[]}[]=[]
  for(const review of reviews){if(!review.analysis_text?.trim()){classifications.push({review_id:review.id,sentiment:review.rating>=4?'positive':'negative',basis:'rating',evidence:'',analysis_source:'rating_fallback_textless'});reviewStatus.push({review_id:review.id,theme_analysis:'textless',sentiment_analysis:'textless',error_codes:[]});continue}
    const own=tasks.filter(t=>t.review_id===review.id),sentiment=own.find(t=>t.kind==='sentiment'),answer=sentiment?.status==='completed'?sentiment.result as SentimentAnswer:null
    if(answer&&answer.overall_choice!=='insufficient')classifications.push({review_id:review.id,sentiment:answer.overall_choice,basis:'jev',evidence:null,analysis_source:'jev',overall_choice:answer.overall_choice,probabilities:answer.overall_probabilities,confidence:answer.overall_confidence})
    else {unavailableSentiment.push(review.id);classifications.push({review_id:review.id,sentiment:'unavailable',basis:'unavailable',evidence:null,analysis_source:answer?'jev_insufficient':'jev_unavailable',...(answer?{overall_choice:answer.overall_choice,probabilities:answer.overall_probabilities,confidence:answer.overall_confidence}:{})})}
    const reps=[1,2,3].map(repeat=>own.find(t=>t.kind==='themes'&&t.repeat===repeat)),available=reps.every(t=>t?.status==='completed'&&t.result)
    if(!available)unavailableThemes.push(review.id)
    else for(const theme of THEME_KEYS){const answers=reps.map(t=>(t!.result as ThemeDecision).themes[theme]);if(answers.some(a=>!a))throw new Error('V9_THEMES_INCOMPLETE');const presence=answers.map(themePresence),positive=presence.reduce((n,p)=>n+p.positive_presence_probability,0)/3,negative=presence.reduce((n,p)=>n+p.negative_presence_probability,0)/3,stable=new Set(answers.map(a=>a.choice)).size===1;for(const polarity of ['positive','negative'] as const)if((polarity==='positive'?positive:negative)>=.5)findings.push({review_id:review.id,theme_key:theme,sentiment:polarity,evidence:null,analysis_source:'jev',probability_positive:positive,probability_negative:negative,repeat_stable:stable})}
    reviewStatus.push({review_id:review.id,theme_analysis:available?'completed':'unavailable',sentiment_analysis:answer&&answer.overall_choice!=='insufficient'?'completed':'unavailable',error_codes:own.filter(t=>t.status==='failed').map(t=>t.error_code??'JEV_UNAVAILABLE')})
  }
  const groups=new Map<string,{theme_key:string;axis:Axis;sentiment:'positive'|'negative';review_ids:string[];mentions:number}>();for(const f of findings){const key=f.theme_key+':'+f.sentiment,g=groups.get(key)??{theme_key:f.theme_key,axis:V9_THEME_AXES[f.theme_key],sentiment:f.sentiment,review_ids:[],mentions:0};g.review_ids.push(f.review_id);g.mentions=g.review_ids.length;groups.set(key,g)}
  const themes=[...groups.values()].sort((a,b)=>b.mentions-a.mentions||a.theme_key.localeCompare(b.theme_key)),metrics={total:reviews.length,positive:classifications.filter(c=>c.sentiment==='positive').length,negative:classifications.filter(c=>c.sentiment==='negative').length,classifications,classificationFallbackCount:classifications.filter(c=>c.basis==='rating').length,themes,axes:AXES.map(key=>({key,positive:new Set(themes.filter(t=>t.axis===key&&t.sentiment==='positive').flatMap(t=>t.review_ids)).size,negative:new Set(themes.filter(t=>t.axis===key&&t.sentiment==='negative').flatMap(t=>t.review_ids)).size}))}
  const cross=crossRatingAnalysis(reviews,findings),unavailable=new Set(unavailableThemes)
  // Keep Google rating averages on the exact full dataset. Unassessed Jev rows
  // do not masquerade as unexplained/absent textual opinions in status counts.
  for(const row of cross.review_analyses)if(unavailable.has(row.review_id))for(const key of ['food','service','atmosphere'] as const){const field=row.axes[key].status+'_count';(cross.axes[key] as unknown as Record<string,number>)[field]--}
  const assessed=crossRatingAnalysis(reviews.filter(r=>!unavailable.has(r.id)),findings);cross.high_signal_reviews=assessed.high_signal_reviews;cross.high_signal_review_count=assessed.high_signal_review_count
  return {metrics,findings,classifications,cross_rating_analysis:{...cross,analysis_unavailable_review_ids:unavailableThemes},analysis_unavailable_count:unavailableSentiment.length,unavailable_theme_reviews:unavailableThemes.length,review_status:reviewStatus}
}
export interface V9Usage {requested_model:string;served_models:string[];theme_repeat_count:number;sentiment_repeat_count:number;concurrency:number;threshold:number;jev_theme_requests:number;jev_sentiment_requests:number;jev_input_tokens:number;jev_output_tokens:number;jev_retry_count:number;jev_elapsed_ms:number;sol_narrative_calls:number;sol_narrative_input_tokens:number;sol_narrative_output_tokens:number;sol_narrative_elapsed_ms:number;usage_complete:boolean;rates:{jev_input:number;sol_input:number;sol_output:number};narrative_state:string;narrative_error:string|null}
export function v9Costs(m:V9Usage,endToEnd:number|null){const jev_cost_usd=m.jev_input_tokens/1_000_000*m.rates.jev_input,sol_narrative_cost_usd=(m.sol_narrative_input_tokens*m.rates.sol_input+m.sol_narrative_output_tokens*m.rates.sol_output)/1_000_000;return {...m,jev_cost_usd,sol_narrative_cost_usd,total_estimated_cost_usd:jev_cost_usd+sol_narrative_cost_usd,end_to_end_elapsed_ms:endToEnd,cost_label:'ESTIMATION_AT_CONFIGURED_RATE',per_review_sol_extraction_calls:0}}
export interface V9ComparisonSource {generation_id:string;input_tokens:number;output_tokens:number;started_at:string;completed_at:string;snapshot:{reviews:ReputationReview[];publication?:{consultant_report?:ConsultantReportData}};findings:{review_id:string;theme_key:string;sentiment:string}[]}
export function compareV8V9(source:V9ComparisonSource,reviews:ReputationReview[],derived:ReturnType<typeof deriveV9>,cost:ReturnType<typeof v9Costs>){const a=new Set(source.snapshot.reviews.map(r=>r.id)),b=new Set(reviews.map(r=>r.id)),commonIds=new Set([...a].filter(id=>b.has(id))),counts=(x:Set<string>,y:Set<string>)=>({v8:x.size,v9:y.size,common:[...x].filter(v=>y.has(v)).length,v8_only:[...x].filter(v=>!y.has(v)).length,v9_only:[...y].filter(v=>!x.has(v)).length}),match=(theme?:string,axis?:Axis)=>counts(new Set(source.findings.filter(f=>commonIds.has(f.review_id)&&(!theme||f.theme_key===theme)&&(!axis||V9_THEME_AXES[f.theme_key]===axis)).map(f=>f.review_id+':'+f.theme_key+':'+f.sentiment)),new Set(derived.findings.filter(f=>(!theme||f.theme_key===theme)&&(!axis||V9_THEME_AXES[f.theme_key]===axis)).map(f=>f.review_id+':'+f.theme_key+':'+f.sentiment)))
  const prior=source.snapshot.publication?.consultant_report?.cross_rating_analysis,unknown=new Set(derived.cross_rating_analysis.analysis_unavailable_review_ids),cross_rating=Object.fromEntries(['food','service','atmosphere'].map(axis=>{const key=axis as 'food'|'service'|'atmosphere',rows8=prior?.review_analyses.filter(r=>commonIds.has(r.review_id)&&!unknown.has(r.review_id))??[],rows9=derived.cross_rating_analysis.review_analyses.filter(r=>commonIds.has(r.review_id)&&!unknown.has(r.review_id));return [key,{comparable_reviews:rows9.length,unavailable_reviews:unknown.size,statuses:Object.fromEntries(['confirmed_negative','low_score_unexplained','textual_issue_despite_high_score','positive_consistent','mixed_text_signal'].map(status=>[status,{v8:rows8.filter(r=>r.axes[key].status===status).length,v9:rows9.filter(r=>r.axes[key].status===status).length}]))}]}))
  const v8cost=(source.input_tokens*cost.rates.sol_input+source.output_tokens*cost.rates.sol_output)/1_000_000
  return {source_generation_id:source.generation_id,dataset:{...counts(a,b),identical:a.size===commonIds.size&&b.size===commonIds.size,identical_analysis_text:reviews.filter(r=>source.snapshot.reviews.find(s=>s.id===r.id)?.analysis_text===r.analysis_text).length},findings:match(),axes:Object.fromEntries(AXES.map(axis=>[axis,match(undefined,axis)])),themes:Object.fromEntries(['attentiveness','professionalism','friendly_staff','wait_time','atmosphere','coordination','communication'].map(theme=>[theme,match(theme)])),cross_rating,cost:{v8_input_tokens:source.input_tokens,v8_output_tokens:source.output_tokens,v8_estimated_cost_usd:v8cost,v9_estimated_cost_usd:cost.total_estimated_cost_usd,difference_percent:v8cost?(cost.total_estimated_cost_usd-v8cost)/v8cost*100:null},elapsed:{v8_ms:Date.parse(source.completed_at)-Date.parse(source.started_at),v9_ms:cost.end_to_end_elapsed_ms},label:'V8 Sol / V9 Jev — deterministic comparison, not accuracy'}
}

export interface V9Job {id:string;generation_id:string;organization_id:string;establishment_id:string;language:'fr'|'vi';status:string;model:string;cursor:number;ai_calls:number;input_tokens:number;output_tokens:number;attempt_count:number;started_at:string|null;snapshot:{analysis_version:number;analysis_engine:string;source_generation_id:string;source_snapshot_sha256:string;source_snapshot:V9ComparisonSource['snapshot'];reviews:ReputationReview[];base:Record<string,unknown>;publication?:Record<string,unknown>}}
