// @vitest-environment node
import {afterEach,it,expect,vi} from 'vitest'
import {readFileSync} from 'node:fs'
import {FIRST_V8_ESTABLISHMENT,FIRST_V8_SOURCE} from './historical-v8'
const auth=vi.hoisted(()=>({requireUser:vi.fn(),assertMembership:vi.fn()}));vi.mock('./auth.ts',()=>auth)
afterEach(()=>{vi.unstubAllGlobals();vi.clearAllMocks()})
async function harness(endpoint:'generate'|'status',mode='normal'){
  const reads:{table:string;filters:Record<string,unknown>}[]=[],rpc=vi.fn(async()=>({data:{generation_id:'v8-fixture',establishment_id:FIRST_V8_ESTABLISHMENT,language:'vi',status:'queued',cursor:0,total_steps:null,snapshot:{analysis_version:8}},error:null}))
  class Query {filters:Record<string,unknown>={};constructor(private table:string){}select(){return this}eq(k:string,v:unknown){this.filters[k]=v;return this}order(){return this}limit(){return this}async single(){reads.push({table:this.table,filters:this.filters});if(this.table==='profiles')return {data:{preferred_language:'vi'},error:null};if(this.table==='establishments')return {data:{id:mode==='other'?'other':FIRST_V8_ESTABLISHMENT,organization_id:'org'},error:null};if(this.filters.generation_id===FIRST_V8_SOURCE)return {data:mode==='no-source'?null:{generation_id:FIRST_V8_SOURCE,status:'completed',snapshot:{analysis_version:7,base:{analysis_input_stats:{english_analysis_coverage_percent:100}}}},error:null};return {data:mode==='completed'?{generation_id:'v8-fixture',establishment_id:FIRST_V8_ESTABLISHMENT,language:'vi',status:'completed',cursor:1,total_steps:2,error_code:null,model:'gpt-6.1-sol',input_tokens:10,output_tokens:20,started_at:'2026-10-07T00:00:00Z',completed_at:'2026-10-07T00:00:01Z',snapshot:{analysis_version:8,reviews:[{id:'r',analysis_text:'Synthetic English text.',analysis_source:'original_en',analysis_language:'en',original_text:'PRIVATE ORIGINAL'}],publication:{consultant_report:{version:8,cross_rating_analysis:{total_reviews:1}}}}}:null,error:null}}maybeSingle(){return this.single()}}
  const db={from:(t:string)=>new Query(t),rpc};auth.requireUser.mockImplementation(async()=>{if(mode==='unauthorized')throw new Error('UNAUTHORIZED');return {client:db,admin:db,user:{id:'user'}}});auth.assertMembership.mockImplementation(async()=>{if(mode==='forbidden')throw new Error('FORBIDDEN')});let handler!:(r:Request)=>Promise<Response>;vi.stubGlobal('Deno',{env:{get:()=>undefined},serve:(fn:typeof handler)=>{handler=fn}});vi.resetModules();await import(endpoint==='generate'?'../generate-historical-report/index.ts':'../get-historical-report-status/index.ts')
  return {rpc,reads,post:(payload:object={})=>handler(new Request('https://fixture.test',{method:'POST',body:JSON.stringify({establishment_id:FIRST_V8_ESTABLISHMENT,preferred_language:'vi',first_v8:true,...payload})})),get:()=>handler(new Request(`https://fixture.test?establishment_id=${FIRST_V8_ESTABLISHMENT}&preferred_language=vi&analysis_version=8&generation_id=v8-fixture`))}
}
it('manual V8 enqueue uses the pinned-source coverage-checked RPC, exact user/org/profile language and does not call providers',async()=>{const h=await harness('generate'),response=await h.post();expect(response.status).toBe(202);expect(h.rpc).toHaveBeenCalledExactlyOnceWith('enqueue_first_v8_report',{p_establishment_id:FIRST_V8_ESTABLISHMENT,p_organization_id:'org',p_user_id:'user',p_language:'vi',p_source_generation_id:FIRST_V8_SOURCE});expect(auth.assertMembership).toHaveBeenCalledWith(expect.anything(),'user','org',['owner','admin','manager'])})
it.each(['other','forbidden','unauthorized'])('V8 rejects %s before enqueue',async mode=>{const h=await harness('generate',mode),r=await h.post();expect(r.status).toBe(mode==='other'?409:mode==='forbidden'?403:401);expect(h.rpc).not.toHaveBeenCalled()})
it('V8 rejects stale profile language or simultaneous V7/V8 requests rather than starting the wrong version',async()=>{const h=await harness('generate');expect((await h.post({preferred_language:'fr'})).status).toBe(409);expect((await h.post({first_v7:true})).status).toBe(400);expect(h.rpc).not.toHaveBeenCalled()})
it('V8 status GET is read-only, source gated and never exposes snapshots or a report before completed',async()=>{const h=await harness('status'),r=await h.get(),d=await r.json();expect(r.status).toBe(200);expect(d).toEqual({run:null,eligibility:{available:true,source_generation_id:FIRST_V8_SOURCE}});expect(h.reads.at(-1)?.filters).toMatchObject({organization_id:'org',establishment_id:FIRST_V8_ESTABLISHMENT,language:'vi',generation_id:'v8-fixture','snapshot->>analysis_version':'8'});expect(h.rpc).not.toHaveBeenCalled();const missing=await harness('status','no-source');expect((await (await missing.get()).json()).eligibility.available).toBe(false)})
it('completed V8 GET returns persisted cross analysis/usage and never recomputes or calls a model',async()=>{const h=await harness('status','completed'),d=await (await h.get()).json();expect(d.run.analysis_version).toBe(8);expect(d.run.report).toEqual({version:8,cross_rating_analysis:{total_reviews:1}});expect(d.run.summary).toMatchObject({model:'gpt-6.1-sol',input_tokens:10,output_tokens:20,elapsed_ms:1000});expect(JSON.stringify(d)).not.toContain('PRIVATE ORIGINAL');expect(JSON.stringify(d)).not.toContain('Synthetic English text');expect(h.rpc).not.toHaveBeenCalled()})
it('V8 DDL has no migration-time launch or existing-run upgrade and preserves service-only/manual idempotency',()=>{const sql=readFileSync(new URL('../../migrations/20261007090839_historical_cross_rating_v8.sql',import.meta.url),'utf8');expect(sql).toContain('not in (3,4,5,6,7,8)');expect(sql).toContain('pg_advisory_xact_lock');expect(sql).toContain("'gpt-6.1-sol',8");expect(sql).toContain('REPORT_OTHER_VERSION_RUNNING');expect(sql).toContain('ENGLISH_COVERAGE_REQUIRED');expect(sql).toContain('revoke all');expect(sql).not.toMatch(/cron\.|select public.enqueue_first_v8|set (?:snapshot|analysis_version)|update public\.(?:reviews|review_translations|jev_benchmark_runs|analysis_gold_)/)})
