import {describe,it,expect,vi,afterEach} from 'vitest'
import {readFileSync,readdirSync} from 'node:fs'
import {syntheticIndependent} from '../../../tests/fixtures/independent-jev'
import {INDEPENDENT_CONFIG,prepareIndependent,compareIndependent,independentPayload,verifyIndependent,postgresJsonbText} from './independent-jev-core'
import {independentHandler} from './independent-jev-api'
import {processIndependent} from './independent-jev-worker'
import {canonicalJson} from './jev-exploratory-core'
import {v11Payload,V11_THRESHOLDS} from './jev-v11-calibration'
import {v12Payload,V12_CONFIG} from './jev-v12-config'
import type {SupabaseClient} from '@supabase/supabase-js'
const jev=vi.hoisted(()=>({evaluate:vi.fn(),clients:vi.fn(),active:0,maximum:0}))
vi.mock('./jev.ts',async original=>({...await original() as object,createJevClient:(_key:unknown,options:unknown)=>{jev.clients(options);return {evaluatePayload:jev.evaluate}}}))
afterEach(()=>{vi.unstubAllGlobals();vi.clearAllMocks();jev.active=0;jev.maximum=0})
describe('sealed independent holdout (offline)',()=>{
 it('uses the precise PostgreSQL JSONB seal serialization',()=>{expect(postgresJsonbText({bbb:'é',aa:1,z:{negative:'absent',both:'positive'}})).toBe('{"z": {"both": "positive", "negative": "absent"}, "aa": 1, "bbb": "é"}')})
 it('prepares 32 disjoint English reviews, 800 AI labels, 11 uncertain, exactly 192 evaluations without providers',async()=>{const fetch=vi.fn();vi.stubGlobal('fetch',fetch);const f=await syntheticIndependent();expect(f.prepared.items).toHaveLength(32);expect(f.prepared.uncertain_labels).toBe(11);expect(f.prepared.expected_requests).toBe(192);expect(f.prepared.items.some(i=>f.trainingIds.includes(i.review_id))).toBe(false);expect(fetch).not.toHaveBeenCalled();expect(jev.clients).not.toHaveBeenCalled()})
 it.each(['text','labels','seal','english','overlap','duplicate','extra-theme','protocol'])('rejects %s anomalies',async kind=>{const f=await syntheticIndependent();if(kind==='text')f.items[0].analysis_text+=' changed';if(kind==='labels')f.refs[0].theme_choices.wait_time='absent';if(kind==='seal')f.seal.reference_fingerprint='bad';if(kind==='english')f.items[0].analysis_language='vi';if(kind==='overlap')f.trainingIds.push(f.items[0].review_id);if(kind==='duplicate')f.items[1].review_id=f.items[0].review_id;if(kind==='extra-theme')Object.assign(f.refs[0].theme_choices,{fake_theme:'absent'});if(kind==='protocol')f.refs[0].annotation_protocol='model-assisted';await expect(prepareIndependent(f.h,f.items,f.refs,f.seal,f.trainingIds,{input:.042,output:0})).rejects.toThrow(/INDEPENDENT_/)})
 it('does not rewrite texts for translation issues or known corrections',async()=>{const f=await syntheticIndependent(),before=structuredClone(f.items);f.refs[0].notes_fr='Doute de traduction';const p=await prepareIndependent(f.h,f.items,f.refs,f.seal,[],{input:.042,output:0},[f.items[1].review_id]);expect(p.translation_anomalies).toHaveLength(2);expect(f.items).toEqual(before);expect(p.items).toEqual(before)})
 it('reuses exact V11/V12 payloads and thresholds; ratings/labels/original text are absent',()=>{expect(INDEPENDENT_CONFIG.v11.thresholds).toEqual(V11_THRESHOLDS);expect(INDEPENDENT_CONFIG.v12).toEqual(V12_CONFIG);for(const v of ['v11','v12'] as const){const payload=independentPayload(v,'r1','Only English');expect(payload).toEqual(v==='v11'?v11Payload('themes','r1','Only English'):v12Payload('r1','Only English'));expect(Object.keys(payload.questions)).toHaveLength(25);for(const key of ['overall_rating','review_detailed_rating','original_text','reference','theme_choices','google_detailed_ratings'])expect(JSON.stringify(payload)).not.toContain(key)}})
 it('detects tampering of frozen run snapshots',async()=>{const f=await syntheticIndependent();f.run.prepared.reference[0].theme_choices.wait_time='absent';await expect(verifyIndependent(f.run)).rejects.toThrow('INDEPENDENT_INTEGRITY_CHANGED')})
 it('scores both polarities, excludes uncertain labels, and has deterministic paired bootstrap',async()=>{const f=await syntheticIndependent(),a=await compareIndependent(f.run,f.tasks),b=await compareIndependent(f.run,f.tasks);expect(a.v11.micro_f1).toBe(1);expect(a.v12.negative.f1).toBe(1);expect(a.v11.exact_compared).toBe(789);expect(a.uncertain_reference_labels).toBe(11);expect(a.v11.themes.presentation.negative.uncertain).toBe(11);expect(a.v11.axes.price.negative.f1).toBeNull();expect(a.bootstrap).toEqual(b.bootstrap);expect(a.bootstrap.negative.resamples).toBe(2000);expect(a.bootstrap.negative.delta).toBe(0);expect(a.human_validated).toBe(false)})
 it('retains honest paired coverage on an invalid V12 review and cannot claim complete confidence',async()=>{const f=await syntheticIndependent();f.tasks.find(t=>t.model_version==='v12')!.response=null;const c=await compareIndependent(f.run,f.tasks);expect(c.coverage).toEqual({v11:32,v12:31,common:31,total:32,complete:false});expect(c.bootstrap.overall.ci_95_low).toBeNull();expect(c.failures).toHaveLength(1)})
 it('reports positive false positives, negative misses, unstable repetitions and disagreements',async()=>{const f=await syntheticIndependent(),id=f.items[0].review_id;for(const t of f.tasks.filter(t=>t.model_version==='v12'&&t.review_id===id)){t.response!.themes.wait_time={choice:'absent',probabilities:{absent:1,positive:0,negative:0,both:0}};t.response!.themes.decor={choice:'positive',probabilities:{absent:0,positive:1,negative:0,both:0}}}f.tasks.find(t=>t.review_id===id&&t.model_version==='v11')!.response!.themes.decor={choice:'positive',probabilities:{absent:.3,positive:.7,negative:0,both:0}};const c=await compareIndependent(f.run,f.tasks);expect(c.v12.errors).toContainEqual(expect.objectContaining({review_id:id,theme_key:'wait_time',polarity:'negative',kind:'false_negative'}));expect(c.v12.errors).toContainEqual(expect.objectContaining({theme_key:'decor',polarity:'positive',kind:'false_positive'}));expect(c.reviews[0].reasons).toContainEqual(expect.objectContaining({code:'repeat_instability'}));expect(c.disagreement_count).toBeGreaterThan(0)})
 it('protects task identity, version, repeats and source text',async()=>{const f=await syntheticIndependent();f.tasks[0].analysis_text_sha256='different';await expect(compareIndependent(f.run,f.tasks)).rejects.toThrow('INDEPENDENT_TASKS_CHANGED')})
})
describe('manual independent API',()=>{
 async function setup(){const f=await syntheticIndependent(),start=vi.fn(async()=>f.run.id),config={id:INDEPENDENT_CONFIG.id,config:INDEPENDENT_CONFIG,config_sha256:f.prepared.config_sha256,frozen_at:'2026-10-09'},repo={configuration:async()=>config,get:vi.fn().mockResolvedValue(null),prepare:async()=>f.prepared,configured:()=>true,start,result:vi.fn(),progress:async()=>({total:192,completed:0,failed:0})};return {f,repo,start,handle:independentHandler(async()=>repo),body:{action:'start',confirm_cost:true,configuration_sha256:config.config_sha256,prepared_sha256:f.prepared.prepared_sha256}}}
 it('GET is read only and never exposes the sealed annotation choices or creates a run',async()=>{const s=await setup(),r=await s.handle(new Request('https://test/independent')),d=await r.json();expect(d.ready).toBe(true);expect(d.preview.uncertain_labels).toBe(11);expect(d.comparison).toBeNull();expect(JSON.stringify(d)).not.toContain('theme_choices');expect(s.start).not.toHaveBeenCalled()})
 it.each(['cost','hash'])('requires an explicit %s confirmation',async kind=>{const s=await setup();if(kind==='cost')s.body.confirm_cost=false;else s.body.prepared_sha256='changed';const r=await s.handle(new Request('https://test',{method:'POST',body:JSON.stringify(s.body)}));expect(r.status).toBe(409);expect(s.start).not.toHaveBeenCalled()})
 it('reuses an existing running job on ambiguous/double launch, without creating another',async()=>{const s=await setup();s.repo.get.mockResolvedValue({...s.f.run,status:'running'});const r=await s.handle(new Request('https://test',{method:'POST',body:JSON.stringify(s.body)}));expect(r.status).toBe(200);expect(s.start).not.toHaveBeenCalled();expect(s.repo.result).not.toHaveBeenCalled()})
 it('never reveals results before completion',async()=>{const s=await setup();s.repo.get.mockResolvedValue({...s.f.run,status:'running'});const d=await(await s.handle(new Request('https://test'))).json();expect(d.comparison).toBeNull();expect(s.repo.result).not.toHaveBeenCalled()})
})
describe('server worker and schema contracts',()=>{
 it('finalizes persisted tasks without calling a provider or Sol/Apify',async()=>{const f=await syntheticIndependent(),rpc=vi.fn(async(name:string)=>({data:name==='validate_independent_jev_source'?{reference_fingerprint:f.seal.reference_fingerprint,dataset_fingerprint:f.seal.frozen_dataset_fingerprint}:name==='claim_independent_jev_tasks'?[]:true,error:null})),query={select:()=>query,eq:()=>query,order:()=>query,limit:async()=>({data:f.tasks,error:null})},admin={rpc,from:()=>query};vi.stubGlobal('Deno',{env:{get:()=> 'fake'}});const result=await processIndependent(admin as unknown as SupabaseClient,f.run,'worker');expect(result.status).toBe('completed');expect(jev.clients).not.toHaveBeenCalled();expect(rpc).toHaveBeenCalledWith('finish_independent_jev_tick',expect.objectContaining({p_comparison:expect.objectContaining({human_validated:false})}))})
 it('limits concurrency to eight, makes only one attempt per task, and sends only frozen text/questions',async()=>{const f=await syntheticIndependent(),batch=f.tasks.slice(0,8);let calls=0;const rpc=vi.fn(async(name:string)=>({data:name==='validate_independent_jev_source'?{reference_fingerprint:f.seal.reference_fingerprint,dataset_fingerprint:f.seal.frozen_dataset_fingerprint}:name==='claim_independent_jev_tasks'?calls++===0?batch:[]:true,error:null})),query={select:()=>query,eq:()=>query,order:()=>query,limit:async()=>({data:[{status:'pending'}],error:null})};jev.evaluate.mockImplementation(async()=>{jev.active++;jev.maximum=Math.max(jev.maximum,jev.active);await Promise.resolve();jev.active--;throw new Error('JEV_NETWORK_ERROR')});vi.stubGlobal('Deno',{env:{get:()=> 'fake'}});await processIndependent({rpc,from:()=>query} as unknown as SupabaseClient,f.run,'worker');expect(jev.evaluate).toHaveBeenCalledTimes(8);expect(jev.maximum).toBeLessThanOrEqual(8);expect(jev.clients.mock.calls.every(([o])=>o.maxAttempts===1)).toBe(true);expect(jev.evaluate.mock.calls.every(([p])=>!canonicalJson(p).includes('theme_choices'))).toBe(true);expect(rpc.mock.calls.filter(([n])=>n==='complete_independent_jev_task')).toHaveLength(8)})
 it('schema contains only independent writes, tenant policies, zero retries and conditional scheduling',()=>{const names=readdirSync('supabase/migrations').filter(n=>n.endsWith('_independent_jev_holdout_benchmark.sql'));expect(names).toHaveLength(1);const sql=readFileSync('supabase/migrations/'+names[0],'utf8');for(const table of ['analysis_v11_independent_holdout_items','analysis_v11_independent_holdout_ai_references','analysis_v11_independent_holdout_ai_seals','analysis_jev_v12_runs','reviews','review_translations'])expect(sql).not.toMatch(new RegExp('(?:insert into|update|delete from)\\s+public\\.'+table+'\\b','i'));expect(sql).toContain('check(retry_count=0)');expect(sql).toContain('security invoker');expect(sql).toContain("m.role in (''owner'',''admin'',''manager'')");expect(sql).toContain('unique(run_id,model_version,review_id,repeat)');expect(sql).toContain('where exists(select 1 from public.analysis_jev_independent_runs');expect(sql).toContain("JEV_RESPONSE_UNCONFIRMED")})
})
