import {json,preflight} from './cors.ts'
import {canonicalJson} from './jev-exploratory-core.ts'
import {negativeHash} from './negative-validation-core.ts'
import {INDEPENDENT_CONFIG,verifyIndependent,compareIndependent,type IndependentRun,type IndependentPrepared} from './independent-jev-core.ts'
export interface IndependentConfiguration {id:string;config:typeof INDEPENDENT_CONFIG;config_sha256:string;frozen_at:string}
export interface IndependentRepository {configuration:()=>Promise<IndependentConfiguration>;get:()=>Promise<IndependentRun|null>;prepare:()=>Promise<IndependentPrepared>;configured:()=>boolean;start:(p:IndependentPrepared)=>Promise<string>;result:(id:string)=>Promise<Awaited<ReturnType<typeof compareIndependent>>|null>;progress:(id:string)=>Promise<{total:number;completed:number;failed:number}>}
export function independentHandler(repository:(r:Request)=>Promise<IndependentRepository>){return async(request:Request)=>{const pre=preflight(request);if(pre)return pre;try{if(!['GET','POST'].includes(request.method))return json({error:'METHOD_NOT_ALLOWED'},405);const repo=await repository(request),configuration=await repo.configuration();if(configuration.config_sha256!==await negativeHash(canonicalJson(INDEPENDENT_CONFIG))||canonicalJson(configuration.config)!==canonicalJson(INDEPENDENT_CONFIG)||!configuration.frozen_at)throw new Error('INDEPENDENT_CONFIG_CHANGED');let run=await repo.get(),p:IndependentPrepared|null=null,error_code:string|null=null;if(run){await verifyIndependent(run);p=run.prepared}else try{p=await repo.prepare()}catch(e){error_code=e instanceof Error&&/^[A-Z0-9_]+$/.test(e.message)?e.message:'INDEPENDENT_SOURCE_READ_FAILED'}
 if(request.method==='POST'){const b=await request.json();if(b.action!=='start'||b.confirm_cost!==true||b.configuration_sha256!==configuration.config_sha256)throw new Error('INDEPENDENT_COST_CONFIRMATION_REQUIRED');if(!run){if(!p)throw new Error(error_code??'INDEPENDENT_NOT_READY');if(b.prepared_sha256!==p.prepared_sha256)throw new Error('INDEPENDENT_PREPARATION_CHANGED');if(!repo.configured())throw new Error('JEV_NOT_CONFIGURED');await repo.start(p);run=await repo.get();if(!run)throw new Error('INDEPENDENT_START_UNCONFIRMED')}}
 return json({configuration,ready:!!p,error_code,run:run?{id:run.id,status:run.status,error_code:run.error_code,created_at:run.created_at}:null,preview:p?{reviews:p.items.length,reference_labels:p.seal.labeled_theme_choices,uncertain_labels:p.uncertain_labels,sealed_at:p.seal.sealed_at,reference_model:p.seal.model_source,reference_fingerprint:p.seal.reference_fingerprint,dataset_fingerprint:p.seal.frozen_dataset_fingerprint,config_sha256:p.config_sha256,prepared_sha256:p.prepared_sha256,expected_requests:p.expected_requests,estimated_input_tokens:p.estimated_input_tokens,estimated_cost_usd:p.estimated_cost_usd,rates:p.rates,translation_anomalies:p.translation_anomalies}:null,comparison:run?.status==='completed'?await repo.result(run.id):null,progress:run?await repo.progress(run.id):{total:0,completed:0,failed:0}})
 }catch(e){const code=e instanceof Error&&/^[A-Z0-9_]+$/.test(e.message)?e.message:'INDEPENDENT_REQUEST_FAILED';return json({error:code},code==='UNAUTHORIZED'?401:code==='FORBIDDEN'?403:/CHANGED|CONFIRM|JEV_NOT_CONFIGURED/.test(code)?409:500)}}}
