import {THEME_KEYS,type ThemeKey} from './jev-themes.ts'
import {V11_QUESTION_SET,V11_THRESHOLD_VERSION,V11_THRESHOLDS,v11Payload} from './jev-v11-calibration.ts'
import {V12_CONFIG,V12_THRESHOLDS,v12Payload} from './jev-v12-config.ts'
import {validThemeDecision,completeReview,type V12Task} from './jev-v12-core.ts'
import {negativePrediction,negativeModelScores,negativeBootstrap,type NegativeTask} from './negative-validation-score.ts'
import {negativeHash as sha,type NegativeLabel} from './negative-validation-core.ts'
import {canonicalJson} from './jev-exploratory-core.ts'
import {GOLD_CHOICES,type GoldChoice} from './gold-taxonomy.ts'
export const INDEPENDENT_HOLDOUT='d7d7142c-03ef-48c3-b36e-bacf6d923f40'
export const INDEPENDENT_CONFIGURATION='independent-v11-v12-holdout-v1'
export const INDEPENDENT_CONFIG=Object.freeze({id:INDEPENDENT_CONFIGURATION,experimental_only:true,production_enabled:false,requested_model:'jev-latest',repeat_count:3,concurrency:8,v11:{question_set:V11_QUESTION_SET,threshold_version:V11_THRESHOLD_VERSION,thresholds:V11_THRESHOLDS,questions:v11Payload('themes','__alias__','__analysis_text__').questions},v12:V12_CONFIG})
export type IndependentVersion='v11'|'v12'
export interface Holdout {id:string;organization_id:string;establishment_id:string;source_experiment_id:string;expected_count:number;selection_fingerprint:string}
export interface HoldoutItem {holdout_id:string;review_id:string;position:number;overall_rating:number;analysis_text:string;analysis_language:string;analysis_source:string;analysis_text_sha256:string;selection_bucket:string;google_detailed_ratings:Record<string,unknown>|null}
export interface BlindReference {holdout_id:string;review_id:string;analysis_text_sha256:string;rubric_version:string;model_source:string;reference_kind:string;annotation_protocol:string;theme_choices:Record<ThemeKey,GoldChoice>;overall_text_sentiment:string;notes_fr:string;uncertain_notes_fr:string;requires_review:boolean;created_at:string}
export interface BlindSeal {holdout_id:string;sealed_at:string;reference_kind:string;rubric_version:string;model_source:string;reference_records:number;labeled_theme_choices:number;uncertain_theme_choices:number;reference_fingerprint:string;frozen_dataset_fingerprint:string}
// The external seal uses PostgreSQL jsonb::text (space separators and length/byte-sorted keys).
// Only seven explicit string/object fields enter it; row bookkeeping must not alter the seal.
export function postgresJsonbText(value:unknown):string {if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return '['+value.map(postgresJsonbText).join(', ')+']';const bytes=(k:string)=>new TextEncoder().encode(k);const keys=Object.keys(value).sort((a,b)=>{const x=bytes(a),y=bytes(b);if(x.length!==y.length)return x.length-y.length;for(let i=0;i<x.length;i++)if(x[i]!==y[i])return x[i]-y[i];return 0});return '{'+keys.map(k=>JSON.stringify(k)+': '+postgresJsonbText((value as Record<string,unknown>)[k])).join(', ')+'}'}
export const sealedReferenceRow=(r:BlindReference)=>({review_id:r.review_id,analysis_text_sha256:r.analysis_text_sha256,rubric_version:r.rubric_version,model_source:r.model_source,reference_kind:r.reference_kind,theme_choices:r.theme_choices,overall_text_sentiment:r.overall_text_sentiment})
export async function sealedFingerprints(items:HoldoutItem[],refs:BlindReference[]){const sorted=[...items].sort((a,b)=>a.position-b.position);return {dataset:await sha(sorted.map(i=>i.review_id+':'+i.analysis_text_sha256).join('|')),reference:await sha(sorted.map(i=>postgresJsonbText(sealedReferenceRow(refs.find(r=>r.review_id===i.review_id)!))).join('|'))}}
export function independentPayload(version:IndependentVersion,alias:string,text:string){return version==='v11'?v11Payload('themes',alias,text):v12Payload(alias,text)}
export async function prepareIndependent(holdout:Holdout,items:HoldoutItem[],refs:BlindReference[],seal:BlindSeal,trainingIds:string[],rates:{input:number;output:number},overrideIds:string[]=[]){
 if(holdout.id!==INDEPENDENT_HOLDOUT||seal.holdout_id!==holdout.id||holdout.expected_count!==32||!seal.sealed_at||seal.reference_kind!=='blind_ai_reference_not_human_gold')throw new Error('INDEPENDENT_SEAL_REQUIRED')
 if(items.length!==32||refs.length!==32||new Set(items.map(i=>i.review_id)).size!==32||new Set(items.map(i=>i.position)).size!==32||new Set(refs.map(r=>r.review_id)).size!==32||items.some(i=>i.holdout_id!==holdout.id||trainingIds.includes(i.review_id)))throw new Error('INDEPENDENT_DATASET_INVALID')
 if(canonicalJson(V11_THRESHOLDS)!==canonicalJson(V12_THRESHOLDS)||!Number.isFinite(rates.input)||rates.input<0||!Number.isFinite(rates.output)||rates.output<0)throw new Error('INDEPENDENT_CONFIG_INVALID')
 const sorted=[...items].sort((a,b)=>a.position-b.position),reference:BlindReference[]=[];const translation_anomalies:{review_id:string;code:string;note:string}[]=[]
 for(const i of sorted){if(i.analysis_language!=='en'||!['original_en','google_translation_en'].includes(i.analysis_source)||!i.analysis_text.trim())throw new Error('INDEPENDENT_ENGLISH_REQUIRED');if(await sha(i.analysis_text)!==i.analysis_text_sha256)throw new Error('INDEPENDENT_TEXT_CHANGED');const r=refs.find(r=>r.review_id===i.review_id);if(!r||r.holdout_id!==holdout.id||r.analysis_text_sha256!==i.analysis_text_sha256||r.reference_kind!==seal.reference_kind||r.rubric_version!==seal.rubric_version||r.model_source!==seal.model_source||r.annotation_protocol!=='english_only_25_theme_blind_to_v11_v12_predictions'||Object.keys(r.theme_choices).length!==25||THEME_KEYS.some(k=>!GOLD_CHOICES.includes(r.theme_choices[k])))throw new Error('INDEPENDENT_REFERENCE_INVALID');reference.push({...r});if(overrideIds.includes(i.review_id))translation_anomalies.push({review_id:i.review_id,code:'known_translation_override_not_applied',note:'A correction exists; the sealed English text remains unchanged.'});if(/traduction|translation|traduit/i.test(r.notes_fr+' '+r.uncertain_notes_fr))translation_anomalies.push({review_id:i.review_id,code:'translation_concern_in_reference_note',note:r.notes_fr+' '+r.uncertain_notes_fr})}
 const fingerprints=await sealedFingerprints(sorted,reference),uncertain_labels=reference.reduce((n,r)=>n+THEME_KEYS.filter(k=>r.theme_choices[k]==='uncertain').length,0)
 if(fingerprints.dataset!==holdout.selection_fingerprint||fingerprints.dataset!==seal.frozen_dataset_fingerprint||fingerprints.reference!==seal.reference_fingerprint||seal.reference_records!==32||seal.labeled_theme_choices!==800||seal.uncertain_theme_choices!==uncertain_labels)throw new Error('INDEPENDENT_SEAL_CHANGED')
 const config_sha256=await sha(canonicalJson(INDEPENDENT_CONFIG)),dataset_sha256=await sha(canonicalJson(sorted)),reference_sha256=await sha(canonicalJson(reference)),seal_sha256=await sha(canonicalJson(seal)),expected_requests=sorted.length*6,estimated_input_tokens=Math.ceil(sorted.reduce((n,i)=>n+(['v11','v12'] as const).reduce((m,v)=>m+canonicalJson(independentPayload(v,'r'+i.position,i.analysis_text)).length,0),0)*3/4*1.25),estimated_cost_usd=estimated_input_tokens*rates.input/1_000_000,prepared_sha256=await sha(canonicalJson({holdout_id:holdout.id,config_sha256,dataset_sha256,reference_sha256,seal_sha256,rates,expected_requests,translation_anomalies}))
 return {holdout_id:holdout.id,items:sorted,reference,seal,translation_anomalies,uncertain_labels,config_sha256,dataset_sha256,reference_sha256,seal_sha256,expected_requests,estimated_input_tokens,estimated_cost_usd,rates,prepared_sha256}
}
export type IndependentPrepared=Awaited<ReturnType<typeof prepareIndependent>>
export interface IndependentRun {id:string;holdout_id:string;organization_id:string;establishment_id:string;status:'queued'|'running'|'completed'|'failed';config:typeof INDEPENDENT_CONFIG;prepared:IndependentPrepared;created_at:string;started_at:string|null;completed_at:string|null;error_code:string|null}
export interface IndependentTask extends V12Task {model_version:IndependentVersion;review_alias:string;question_set:string;analysis_text_sha256:string}
export async function verifyIndependent(run:IndependentRun){const p=run.prepared;const expected=await sha(canonicalJson({holdout_id:p.holdout_id,config_sha256:p.config_sha256,dataset_sha256:p.dataset_sha256,reference_sha256:p.reference_sha256,seal_sha256:p.seal_sha256,rates:p.rates,expected_requests:p.expected_requests,translation_anomalies:p.translation_anomalies}));if(run.holdout_id!==INDEPENDENT_HOLDOUT||p.holdout_id!==run.holdout_id||canonicalJson(run.config)!==canonicalJson(INDEPENDENT_CONFIG)||await sha(canonicalJson(INDEPENDENT_CONFIG))!==p.config_sha256||await sha(canonicalJson(p.items))!==p.dataset_sha256||await sha(canonicalJson(p.reference))!==p.reference_sha256||await sha(canonicalJson(p.seal))!==p.seal_sha256||p.items.length!==32||p.expected_requests!==192||expected!==p.prepared_sha256)throw new Error('INDEPENDENT_INTEGRITY_CHANGED');const f=await sealedFingerprints(p.items,p.reference);if(f.dataset!==p.seal.frozen_dataset_fingerprint||f.reference!==p.seal.reference_fingerprint)throw new Error('INDEPENDENT_SEAL_CHANGED')}
const has=(c:GoldChoice,p:'positive'|'negative')=>c===p||c==='both'
// V12 uses exactly V11's polarity thresholds. Reuse the proven scorer, without altering either version.
function scoringTasks(tasks:IndependentTask[],v:IndependentVersion):NegativeTask[]{return tasks.filter(t=>t.model_version===v).map(t=>({...t,model_version:'v11',experiment_id:t.run_id,question_set_version:t.question_set}))}
export async function compareIndependent(run:IndependentRun,tasks:IndependentTask[]){await verifyIndependent(run);const p=run.prepared,all=p.items.map(i=>i.review_id);if(tasks.length!==p.expected_requests||new Set(tasks.map(t=>t.model_version+':'+t.review_id+':'+t.repeat)).size!==tasks.length||tasks.some(t=>t.run_id!==run.id||!all.includes(t.review_id)||!['v11','v12'].includes(t.model_version)||![1,2,3].includes(t.repeat)||t.question_set!==run.config[t.model_version].question_set||t.analysis_text_sha256!==p.items.find(i=>i.review_id===t.review_id)!.analysis_text_sha256))throw new Error('INDEPENDENT_TASKS_CHANGED');const left=scoringTasks(tasks,'v11'),right=scoringTasks(tasks,'v12'),ids=all.filter(id=>completeReview(left,id)&&completeReview(right,id)),labels:NegativeLabel[]=p.reference.flatMap(r=>THEME_KEYS.map(theme_key=>({review_id:r.review_id,theme_key,choice:r.theme_choices[theme_key]}))),a=negativeModelScores(ids,labels,left,'v11'),b=negativeModelScores(ids,labels,right,'v11'),models={v11:a,v12:b};
 const prediction=(v:IndependentVersion,id:string,k:ThemeKey)=>negativePrediction(v==='v11'?left:right,id,k,'v11'),errors=(v:IndependentVersion)=>ids.flatMap(id=>THEME_KEYS.flatMap(theme_key=>{const reference=p.reference.find(r=>r.review_id===id)!.theme_choices[theme_key],predicted=prediction(v,id,theme_key)!.choice;if(reference==='uncertain')return [];return (['positive','negative'] as const).flatMap(polarity=>has(reference,polarity)===has(predicted,polarity)?[]:[{review_id:id,theme_key,polarity,kind:has(predicted,polarity)?'false_positive':'false_negative',ai_reference:reference,predicted}])})),score=(v:IndependentVersion)=>{const {errors:_errors,perReview:_reviews,...m}=models[v];void _errors;void _reviews;return {...m,errors:errors(v)}},usage=(v:IndependentVersion)=>{const own=tasks.filter(t=>t.model_version===v);return {requests:own.reduce((n,t)=>n+t.request_count,0),input_tokens:own.reduce((n,t)=>n+t.input_tokens,0),output_tokens:own.reduce((n,t)=>n+t.output_tokens,0),estimated_cost_usd:own.reduce((n,t)=>n+t.cost_usd,0),request_elapsed_sum_ms:own.reduce((n,t)=>n+t.duration_ms,0),served_models:[...new Set(own.flatMap(t=>t.served_model?[t.served_model]:[]))].sort(),usage_complete:own.every(t=>t.usage_complete)}}
 const reviews=p.items.map(i=>{const available=(v:IndependentVersion)=>completeReview(v==='v11'?left:right,i.review_id),preds=(v:IndependentVersion)=>available(v)?Object.fromEntries(THEME_KEYS.map(k=>[k,prediction(v,i.review_id,k)!])) as Record<ThemeKey,NonNullable<ReturnType<typeof negativePrediction>>>:null,v11=preds('v11'),v12=preds('v12'),ref=p.reference.find(r=>r.review_id===i.review_id)!,reasons:{code:string;theme_key?:ThemeKey;version?:IndependentVersion}[]=[];for(const k of THEME_KEYS){if(v11&&v12&&v11[k].choice!==v12[k].choice)reasons.push({code:'v11_v12_disagreement',theme_key:k});for(const v of ['v11','v12'] as const){const pred=v==='v11'?v11:v12;if(!pred){if(k===THEME_KEYS[0])reasons.push({code:'incomplete_response',version:v});continue}if(!pred[k].stable)reasons.push({code:'repeat_instability',version:v,theme_key:k});if(ref.theme_choices[k]!=='uncertain'&&pred[k].choice!==ref.theme_choices[k])reasons.push({code:has(ref.theme_choices[k],'negative')&&!has(pred[k].choice,'negative')?'potentially_missed_criticism':'ai_reference_disagreement',theme_key:k,version:v})}}for(const issue of p.translation_anomalies.filter(a=>a.review_id===i.review_id))reasons.push({code:issue.code});return {...i,v11,v12,ai_reference:ref.theme_choices,reference_notes:ref.notes_fr,uncertain_notes:ref.uncertain_notes_fr,reference_requires_review:ref.requires_review,reasons}}),u={v11:usage('v11'),v12:usage('v12')},bootstrap=async(kind:'overall'|'negative')=>{const {conclusion:_old,...interval}=await negativeBootstrap(run.id,a,b,kind,ids.length===all.length);void _old;return {...interval,comparison:'v12_minus_v11',human_validated:false}}
 return {configuration_id:INDEPENDENT_CONFIGURATION,holdout_id:run.holdout_id,experimental_only:true,production_enabled:false,human_validated:false,reference_type:'sealed_blind_ai_reference_not_human_gold',reference_sealed_at:p.seal.sealed_at,reference_model:p.seal.model_source,reference_labels:800,uncertain_reference_labels:p.uncertain_labels,coverage:{v11:all.filter(id=>completeReview(left,id)).length,v12:all.filter(id=>completeReview(right,id)).length,common:ids.length,total:all.length,complete:ids.length===all.length},v11:score('v11'),v12:score('v12'),bootstrap:{overall:await bootstrap('overall'),negative:await bootstrap('negative')},reviews,disagreement_count:reviews.reduce((n,r)=>n+r.reasons.filter(a=>a.code==='v11_v12_disagreement').length,0),failures:tasks.filter(t=>t.status==='failed'||!validThemeDecision(t.response)).map(t=>({review_id:t.review_id,version:t.model_version,repeat:t.repeat,error_code:t.error_code??'INVALID_RESPONSE'})),usage:u,total_estimated_cost_usd:u.v11.estimated_cost_usd+u.v12.estimated_cost_usd,model_version_confounded:canonicalJson(u.v11.served_models)!==canonicalJson(u.v12.served_models)||Object.values(u).some(a=>a.served_models.length>1),translation_anomalies:p.translation_anomalies,integrity:{dataset_sha256:p.dataset_sha256,reference_sha256:p.reference_sha256,sealed_dataset_fingerprint:p.seal.frozen_dataset_fingerprint,sealed_reference_fingerprint:p.seal.reference_fingerprint,identical_texts:true,training_overlap:0},end_to_end_elapsed_ms:run.started_at&&run.completed_at?Date.parse(run.completed_at)-Date.parse(run.started_at):null,warning:'Held-out reviews and AI references blinded to JEV predictions. Exploratory comparison, not independent human Gold. Star-enriched sample; no prevalence or automatic production decision.'}
}
