import type {SupabaseClient} from 'npm:@supabase/supabase-js@2.117.2'
import {createJevClient} from './jev.ts'
import {parseThemes} from './jev-themes.ts'
import {independentPayload,verifyIndependent,compareIndependent,type IndependentRun,type IndependentTask} from './independent-jev-core.ts'
const safe=(e:unknown)=>e instanceof Error&&/^[A-Z0-9_]+$/.test(e.message)?e.message:'INDEPENDENT_NETWORK_ERROR'
export async function processIndependent(admin:SupabaseClient,run:IndependentRun,worker:string){const begin=Date.now(),rpc=async(name:string,args:Record<string,unknown>)=>{const {data,error}=await admin.rpc(name,args);if(error)throw new Error('INDEPENDENT_SAVE_FAILED');return data},finish=async(comparison:unknown=null,error:string|null=null)=>{if(await rpc('finish_independent_jev_tick',{p_id:run.id,p_worker:worker,p_comparison:comparison,p_error:error})!==true)throw new Error('INDEPENDENT_LEASE_LOST')};try{
 await verifyIndependent(run);const {data:source,error:sourceError}=await admin.rpc('validate_independent_jev_source',{p_holdout:run.holdout_id});if(sourceError||source?.reference_fingerprint!==run.prepared.seal.reference_fingerprint||source?.dataset_fingerprint!==run.prepared.seal.frozen_dataset_fingerprint)throw new Error('INDEPENDENT_SEAL_CHANGED');const key=Deno.env.get('TYPESAFE_API_KEY');if(!key?.trim())throw new Error('JEV_NOT_CONFIGURED')
 while(Date.now()-begin<70_000){const tasks=await rpc('claim_independent_jev_tasks',{p_id:run.id,p_worker:worker}) as IndependentTask[];if(!tasks.length)break;if(tasks.length>8)throw new Error('INDEPENDENT_CONCURRENCY_INVALID');const outcomes=await Promise.allSettled(tasks.map(async t=>{const i=run.prepared.items.find(i=>i.review_id===t.review_id);if(!i||i.analysis_text_sha256!==t.analysis_text_sha256||t.question_set!==run.config[t.model_version].question_set)throw new Error('INDEPENDENT_TASK_INVALID');let input=0,output=0,requests=0,model:string|null=null,response:unknown=null,error_code:string|null=null,usage_complete=true;const start=Date.now(),client=createJevClient(key,{maxAttempts:1,onUsage:(u,m)=>{input+=u.input_tokens;output+=u.output_tokens;model=m},onAttempt:()=>requests++});try{const result=await client.evaluatePayload(independentPayload(t.model_version,t.review_alias,i.analysis_text),parseThemes);response=result.decision;model=result.model}catch(e){error_code=safe(e);if(['JEV_NETWORK_ERROR','JEV_INVALID_USAGE','JEV_INVALID_RESPONSE'].includes(error_code))usage_complete=false}if(await rpc('complete_independent_jev_task',{p_id:run.id,p_worker:worker,p_task:t.id,p_values:{status:error_code?'failed':'completed',response,served_model:model,input_tokens:input,output_tokens:output,request_count:requests,retry_count:0,duration_ms:Date.now()-start,error_code,usage_complete}})!==true)throw new Error('INDEPENDENT_LEASE_LOST')}));const rejected=outcomes.find(i=>i.status==='rejected');if(rejected?.status==='rejected')throw rejected.reason}
 const {data,error}=await admin.from('analysis_jev_independent_tasks').select('*').eq('run_id',run.id).order('id').limit(193);if(error||!data)throw new Error('INDEPENDENT_READ_FAILED');if(data.some(t=>['pending','running'].includes(t.status))){await finish();return {status:'running'}}await finish(await compareIndependent({...run,completed_at:new Date().toISOString()},data as IndependentTask[]));return {status:'completed'}
 }catch(e){const code=safe(e);if(code!=='INDEPENDENT_LEASE_LOST')try{await finish(null,code)}catch{/* Ambiguous billed work is never automatically retried. */}return {status:'error',error_code:code}}
}
