import {THEME_KEYS,type ThemeKey} from './jev-themes.ts'
import {v11Payload,V11_THRESHOLDS} from './jev-v11-calibration.ts'
import type {SystemOnePayload} from './jev.ts'
export const V12_QUESTION_SET='themes_v12_semantic_boundaries_v1'
export const V12_THRESHOLD_VERSION='jev-v12-thresholds-v1-same-values-as-v11'
// Independent immutable copy, never modifies V11 or its thresholds.
export const V12_THRESHOLDS=Object.freeze(Object.fromEntries(THEME_KEYS.map(k=>[k,Object.freeze({...V11_THRESHOLDS[k]})]))) as typeof V11_THRESHOLDS
export const V12_COMMON_RULES='Evaluate this theme independently using only the English analytical text. Never derive a theme or sentiment from Google ratings or metadata. Generic praise about the restaurant alone does not establish a specific theme; a clearly evaluated service execution follows the V11 professionalism rule. Both requires an explicit positive AND negative evaluation of THIS SAME theme, not different food/drink categories or different themes. Never automatically transfer polarity between themes. Reported symptoms after a meal are customer statements, not proof that the restaurant caused illness. Symptoms alone do not establish food_quality or cleanliness.'
export const V12_BOUNDARIES:Partial<Record<ThemeKey,string>>=Object.freeze({
 atmosphere:'General ambience, mood, vibe or overall feeling. Architecture/interior/design belongs to decor; physical temperature, seating or space belongs to comfort. A nice interior alone does not create atmosphere. Do not transfer a negative comfort judgment to atmosphere or decor.',
 decor:'Architecture, interior, design or decoration explicitly described/evaluated. Keep separate from general ambience (atmosphere) and physical comfort (comfort). A beautiful interior can be positive decor while an uncomfortable room is negative comfort; do not propagate either polarity.',
 comfort:'Physical comfort: room temperature, seats/seating, usable space. Keep separate from dish serving temperature, atmosphere and decor. A hot cramped room is negative comfort, not automatically negative atmosphere or decor.',
 friendly_staff:'Friendliness, kindness, warmth and politeness. Rudeness or lack of politeness may be negative friendly_staff. Friendliness alone must not automatically create attentiveness, coordination or professionalism.',
 wait_time:'Waiting, slowness or speed of service. Slow service alone belongs to wait_time; it does NOT by itself establish attentiveness, coordination or professionalism. Everything arrived quickly alone is positive wait_time.',
 attentiveness:'Retain V11 customer-care semantics, but slow service alone is NOT evidence of attentiveness. An absent/unavailable server or explicit lack of attention/taking care of the customer is negative attentiveness. Helpful, responsive or proactive care may be positive. Mere friendliness and timing alone are insufficient.',
 coordination:'Service organization/execution. Describe organizational errors for a negative coordination signal (confused staff, unsynchronized service, a breakdown in organization). Slow or fast service alone does not prove organization. Retain clearly evaluated overall organization/execution under V11; do not infer from friendliness.',
 professionalism:'Retain V11 clearly evaluated service execution: excellent/capable service, useful assistance or professional/helpful execution can qualify without the word professional. Slow service alone does NOT establish professionalism; nice or polite staff alone also does not qualify. Evaluate execution beyond just timing.',
 communication:'Require a described or evaluated interaction with the customer: explanation, information, understanding/misunderstanding, listening or direct exchange. They speak Russian alone is absent; the waiter clearly explained the menu is positive; they could not understand our order is negative. Friendliness/helpfulness or language ability alone does not qualify.',
 food_quality:'Taste/flavor or quality of food dishes. Drinks have their own drinks theme and must not be folded into food_quality. Excellent drinks and a bad food dish mean drinks positive and food_quality negative, NOT food_quality both. Reported illness alone is not proof of bad food quality.',
 drinks:'Drinks, coffee, beverages and cocktails evaluated independently of food dishes. Excellent drinks with bad food can be positive drinks and negative food_quality. A drink cooling during a long wait is not automatically a serving-temperature complaint under temperature.',
 cooking:'Explicit cooking/preparation: overcooked, undercooked, burnt, raw when clearly about insufficient cooking, or well prepared/cooked. An unpleasant, chewy or tough texture alone does not necessarily prove bad cooking; do not guess a cooking cause.',
 freshness:'Freshness only when the text explicitly supports fresh/stale/spoiled ingredients or food. Bad taste, texture or symptoms alone do not automatically establish freshness.',
 temperature:'Explicit wrong temperature of a dish as SERVED (for example the dish was served cold). Food or a drink cooling down while the customer waits does NOT automatically establish bad serving temperature. The room being hot belongs to comfort, not temperature.',
 portions:'Quantity/size of a dish or insufficient portion. A missing ordered element belongs to order_accuracy and does not automatically imply small portions.',
 order_accuracy:'Wrong order, wrong dish or an ordered item/component forgotten. A side dish omitted from the order belongs here; do not automatically classify it as portions.',
 variety:'Menu choice, range and dietary options. Several advertised options being unavailable can be negative variety. A single missing ordered item is order_accuracy, not automatically limited variety.',
 consistency:'Requires a REAL variation in quality across dishes or visits. The food was good last visit but bad this time can qualify. Experiences that are always bad do NOT alone show variation or establish consistency.',
 price_level:'Explicit high/low price level. Prices are high alone is negative price_level, not automatically billing or value.',
 billing:'Bill errors, extra charges, fees or surcharges. A surcharge or wrong total can be negative billing; do not automatically infer high price level or poor value.',
 value:'Explicitly evaluated value for money, what was received relative to price. Not worth the money is negative value. Expensive alone does not establish value or billing.',
})
export function v12Payload(alias:string,analysis_text:string):SystemOnePayload{const payload=structuredClone(v11Payload('themes',alias,analysis_text));for(const theme of THEME_KEYS){const q=payload.questions[theme] as Record<string,unknown>;q.instructions=String(q.instructions)+' '+V12_COMMON_RULES+' '+(V12_BOUNDARIES[theme]??'Retain the V11 definition for this theme.')}return payload}
export const V12_CONFIG=Object.freeze({analysis_version:12,experimental_only:true,production_enabled:false,question_set:V12_QUESTION_SET,threshold_version:V12_THRESHOLD_VERSION,thresholds:V12_THRESHOLDS,requested_model:'jev-latest',repeat_count:3,concurrency:8,macro_min_support:3,questions:v12Payload('__alias__','__analysis_text__').questions,semantic_diagnostic_version:'v12-reported-symptoms-v1'})
export function v12ReportedSymptoms(text:string){const cues=text.match(/\b(?:vomit(?:ed|ing)?|diarrh(?:ea|oea)|food poisoning|(?:felt|got|became) (?:sick|ill))\b/gi)??[];return cues.length?{signal:'symptom_mention_requires_review',causality_confirmed:false,reported_only:true,cues:[...new Set(cues.map(c=>c.toLowerCase()))],creates_theme:false}:null}
