import {describe,it,expect,vi} from 'vitest'
import {readFileSync} from 'node:fs'
import {THEME_KEYS} from './jev-themes'
import {EXPLORATORY_CONFIG,canonicalJson,exploratoryPredictions,exploratoryFingerprint,suspectReasons,validateAiCorrections,compareAiCorrections,reviewBundle,type ExploratoryRun,type ExploratoryItem} from './jev-exploratory-core'
import {exploratoryHandler,type ExplorationRepository} from './jev-exploratory-api'
import {negativeHash} from './negative-validation-core'
import {negativePayload} from './negative-validation-score'
import {syntheticNegative,syntheticNegativeTasks,negativeUuid} from '../../../tests/fixtures/negative-validation'
async function fixture(){const h=await syntheticNegative(),tasks=syntheticNegativeTasks(h),items:ExploratoryItem[]=h.items.map(i=>({review_id:i.review_id,position:i.position,analysis_text:i.analysis_text!,analysis_text_sha256:i.analysis_text_sha256!,overall_rating:i.overall_rating,normalized_category_ratings:i.normalized_category_ratings,v9:exploratoryPredictions(tasks,i.review_id,'v9'),v11:exploratoryPredictions(tasks,i.review_id,'v11')})),run:ExploratoryRun={id:negativeUuid(950),organization_id:h.run.organization_id,establishment_id:h.run.establishment_id,source_kind:'negative_validation',source_id:h.run.id,status:'completed',dataset_sha256:await exploratoryFingerprint(items),config:EXPLORATORY_CONFIG,rate:.042,created_at:h.run.created_at,started_at:null,completed_at:null,locked_by:null,error_code:null};return {h,items,run}}
const correction=(i:ExploratoryItem,theme_key:'wait_time'|'temperature'='wait_time')=>({review_id:i.review_id,theme_key,initial_prediction:i.v11[theme_key]!,choice:'absent' as const,justification:'Synthetic AI reasoning',corrector_model:'synthetic-corrector-v1',corrected_at:'2026-10-09T00:00:00Z',analysis_text_sha256:i.analysis_text_sha256,label_source:'chatgpt_ai_correction' as const})
describe('separate Jev exploratory path',()=>{
  it('permits AI correction of unavailable themes without fabricating an initial prediction',async()=>{const {items}=await fixture();const i=structuredClone(items[0]);delete i.v11.wait_time;const c={...correction(items[0]),initial_prediction:null};expect(validateAiCorrections([c],[i],[i.review_id])[0].initial_prediction).toBeNull();expect(compareAiCorrections([i],[c])).toMatchObject({compared_labels:0,unavailable_labels:1,human_validated:false})})
  it('flags probability drift even when repeated choices remain stable',async()=>{const {items}=await fixture();const i=structuredClone(items[0]);i.v11.wait_time!.probability_drift=.3;expect(suspectReasons(i)).toContainEqual({code:'repeat_instability',theme_key:'wait_time'})})
  it('flags a choice inconsistent with the frozen V11 thresholds',async()=>{const {items}=await fixture();const i=structuredClone(items[0]);i.v11.communication={choice:'positive',positive:.4,negative:0,stable:true};expect(suspectReasons(i)).toContainEqual({code:'invalid_result',theme_key:'communication'})})
  it('keeps V11 exact and sends English text only',()=>{const p=negativePayload('v11','r1','English text only');expect(Object.keys(p.state).sort()).toEqual(['analysis_text','review_alias']);expect(Object.keys(p.questions)).toHaveLength(25);expect(EXPLORATORY_CONFIG.repeat_count).toBe(3);expect(EXPLORATORY_CONFIG.concurrency).toBe(8);expect(EXPLORATORY_CONFIG.thresholds.professionalism).toEqual({positive_threshold:.60,negative_threshold:.80})})
  it('freezes text and ratings with canonical deterministic hashes',async()=>{const {items}=await fixture();expect(await exploratoryFingerprint([...items].reverse())).toBe(await exploratoryFingerprint(items));expect(await exploratoryFingerprint(items.map(i=>({...i,normalized_category_ratings:{atmosphere:4,service:2,food:5}})))).toBe(await exploratoryFingerprint(items));await expect(exploratoryFingerprint([{...items[0],analysis_text:'Changed'}])).rejects.toThrow('INTEGRITY');expect(canonicalJson({b:1,a:2})).toBe(canonicalJson({a:2,b:1}))})
  it('flags available V9 disagreement, repeat instability and incomplete results',async()=>{const {items}=await fixture();expect(suspectReasons(items[0])).toContainEqual({code:'v9_disagreement',theme_key:'wait_time'});const i=structuredClone(items[0]);i.v11.wait_time!.stable=false;delete i.v11.food_quality;expect(suspectReasons(i)).toContainEqual({code:'repeat_instability',theme_key:'wait_time'});expect(suspectReasons(i)).toContainEqual({code:'incomplete_result',theme_key:'food_quality'})})
  it('uses low Google scores only as potential triage, never a finding',async()=>{const {items}=await fixture();const i=structuredClone(items[0]);for(const k of THEME_KEYS)i.v11[k]={choice:'absent',positive:0,negative:0,stable:true};const before=structuredClone(i.v11);expect(suspectReasons(i).some(r=>r.code==='potential_missed_criticism')).toBe(true);expect(i.v11).toEqual(before)})
  it('flags borderline possible false positives without asserting an error',async()=>{const {items}=await fixture();const i=structuredClone(items[0]);i.v11.attentiveness={choice:'positive',positive:.62,negative:0,stable:true};expect(suspectReasons(i)).toContainEqual({code:'potential_false_positive',theme_key:'attentiveness',context:'near_threshold'})})
  it('missing V9 is unavailable and is not treated as absent',async()=>{const {items}=await fixture();const i={...items[0],v9:{}};expect(suspectReasons(i).some(r=>r.code==='v9_disagreement')).toBe(false)})
  it('exports only English and explicitly requires GO; excludes authors and original text',async()=>{const {items,run}=await fixture();const b=await reviewBundle(run,items,[items[0].review_id]);expect(b.instructions).toContain('explicitly gives GO');const raw=JSON.stringify(b);expect(raw).not.toContain('ORIGINAL_PRIVATE_SENTINEL');expect(raw).not.toContain('original_text');expect(b.reviews).toHaveLength(1);expect(b.bundle_sha256).toBe((await reviewBundle(run,items,[items[0].review_id])).bundle_sha256)})
  it('corrections need provenance, exact initial prediction and text hash',async()=>{const {items}=await fixture(),c=correction(items[0]),allow=[items[0].review_id];expect(validateAiCorrections([c],items,allow)[0].label_source).toBe('chatgpt_ai_correction');for(const change of [{corrector_model:''},{justification:''},{analysis_text_sha256:await negativeHash('wrong')},{label_source:'human'},{initial_prediction:{...c.initial_prediction,choice:'positive'}}])expect(()=>validateAiCorrections([{...c,...change}],items,allow)).toThrow();expect(()=>validateAiCorrections([c,c],items,allow)).toThrow();expect(()=>validateAiCorrections([c],items,[])).toThrow()})
  it('compares only AI corrected labels, excludes uncertain and true negatives from F1',async()=>{const {items}=await fixture();const c=correction(items[0]);const r=compareAiCorrections(items,[{...c,choice:'negative'},correction(items[1]),{...correction(items[2]),choice:'uncertain'}]);expect(r.human_validated).toBe(false);expect(r.reference_type).toBe('ai_corrections_exploratory');expect(r.negative).toMatchObject({tp:1,fp:1,fn:0,support:1,f1_vs_ai_corrections:2/3});expect(r.compared_labels).toBe(2);expect(r.uncertain_labels).toBe(1)})
  it('GET never creates or launches; a draft human source is eligible',async()=>{const {items,run,h}=await fixture();const write=vi.fn().mockResolvedValue({}),create=vi.fn().mockResolvedValue(run.id),repo:ExplorationRepository={user:'user',get:vi.fn().mockResolvedValue(null),sources:async()=>[{id:h.run.id,kind:'negative_validation',organization_id:run.organization_id,establishment_id:run.establishment_id,name:'Artisan',ready:32,total:32,reuses_predictions:false}],source:async()=>items,items:async()=>items,approvals:async()=>[],corrections:async()=>[],usage:async()=>({requests:0,input_tokens:0,output_tokens:0,cost_usd:0,served_models:[],complete:true}),create,write,configured:()=>true};const handler=exploratoryHandler(async()=>repo);expect((await handler(new Request('https://test'))).status).toBe(200);expect(create).not.toHaveBeenCalled();expect(write).not.toHaveBeenCalled();await handler(new Request('https://test',{method:'POST',body:JSON.stringify({action:'create',source_kind:'negative_validation',source_id:h.run.id})}));expect(create).toHaveBeenCalledTimes(1);expect(h.run.status).toBe('draft');expect(write).not.toHaveBeenCalled()})
  it('start requires explicit payment approval; import requires recorded GO',async()=>{const {items,run}=await fixture();const repo={user:'u',get:async()=>run,sources:async()=>[],items:async()=>items,write:vi.fn(),configured:()=>true,approvals:async()=>[]} as unknown as ExplorationRepository;const handler=exploratoryHandler(async()=>repo);for(const action of ['start','approve','import']){const response=await handler(new Request('https://test',{method:'POST',body:JSON.stringify({action,run_id:run.id})}));expect(response.status).toBe(400)}expect(repo.write).not.toHaveBeenCalled()})
  it('preserves old human gates and has no Sol or Apify call graph',()=>{const old=readFileSync('supabase/functions/_shared/negative-validation-api.ts','utf8');expect(old).toContain("throw new Error('NEGATIVE_HUMAN_REQUIRED')");for(const f of ['jev-exploratory-core.ts','jev-exploratory-api.ts','jev-exploratory-worker.ts']){const code=readFileSync('supabase/functions/_shared/'+f,'utf8');expect(code).not.toMatch(/createAiClient|writeV9Narrative|englishBackfillApi|APIFY_API_TOKEN|OPENAI_API_KEY|api\.openai/)}const sql=readFileSync('supabase/migrations/20261009015636_jev_exploratory_workflow.sql','utf8');expect(sql).not.toMatch(/update public\.(?:historical_report_runs|analysis_negative_validation_|jev_benchmark_runs|analysis_gold_)/);expect(sql).toContain('EXPLORATORY_EVALUATION_CONTAMINATION');expect(sql).toContain('JEV_RESPONSE_UNCONFIRMED');expect(sql).toContain("p_payload->>'confirm' is distinct from 'true'")})
})
