import {THEME_KEYS,type ThemeKey,type ThemeChoice,type ThemeDecision,themePresence} from './jev-themes.ts'
import {validThemeDecision} from './jev-v12-core.ts'
import {canonicalJson} from './jev-exploratory-core.ts'
import {negativeHash} from './negative-validation-core.ts'
import {ECONOMY_CONFIG,ECONOMY_THRESHOLDS} from './jev-economy-config.ts'
import {meetsV11Threshold} from './jev-v11-calibration.ts'
import {crossRatingAnalysis} from './cross-rating-analysis.ts'
export interface EconomyIdentity {organization_id:string;establishment_id:string;review_id:string;analysis_text_sha256:string;instruction_version:string;instruction_sha256:string;threshold_version:string;threshold_sha256:string;configuration_id:string;requested_model:string;expected_served_model:string}
export interface EconomyCache extends EconomyIdentity {id:string;cache_key:string;status:'reserved'|'dispatched'|'completed'|'billing_uncertain'|'failed_not_sent';response:ThemeDecision|null;served_model:string|null;input_tokens:number|null;output_tokens:number|null;cost_usd:number|null;usage_complete:boolean;processed_at:string|null;source_task_id:string|null}
export async function economyIdentity(organization_id:string,establishment_id:string,review_id:string,text:string,expected_served_model:string):Promise<EconomyIdentity>{if(!text.trim())throw new Error('ECONOMY_TEXTLESS');if(!expected_served_model.trim()||expected_served_model==='jev-latest')throw new Error('ECONOMY_SERVED_MODEL_REQUIRED');return {organization_id,establishment_id,review_id,analysis_text_sha256:await negativeHash(text),instruction_version:ECONOMY_CONFIG.instruction_version,instruction_sha256:await negativeHash(canonicalJson(ECONOMY_CONFIG.questions)),threshold_version:ECONOMY_CONFIG.threshold_version,threshold_sha256:await negativeHash(canonicalJson(ECONOMY_THRESHOLDS)),configuration_id:ECONOMY_CONFIG.id,requested_model:ECONOMY_CONFIG.requested_model,expected_served_model}}
export const economyCacheKey=(identity:EconomyIdentity)=>negativeHash(canonicalJson(identity))
export function reusableEconomyCache(row:EconomyCache,identity:EconomyIdentity,key:string){return row.cache_key===key&&canonicalJson(Object.fromEntries(Object.keys(identity).map(k=>[k,row[k as keyof EconomyIdentity]])))===canonicalJson(identity)&&row.status==='completed'&&row.served_model===identity.expected_served_model&&validThemeDecision(row.response)}
export function economicThemeResults(response:ThemeDecision){if(!validThemeDecision(response))throw new Error('ECONOMY_RESPONSE_INVALID');return Object.fromEntries(THEME_KEYS.map(k=>{const p=themePresence(response.themes[k]),pos=p.positive_presence_probability,neg=p.negative_presence_probability,yesP=meetsV11Threshold(pos,ECONOMY_THRESHOLDS[k].positive_threshold),yesN=meetsV11Threshold(neg,ECONOMY_THRESHOLDS[k].negative_threshold);return [k,{choice:(yesP?yesN?'both':'positive':yesN?'negative':'absent') as ThemeChoice,positive:pos,negative:neg,repeat_stable:null,evaluations:1}]})) as Record<ThemeKey,{choice:ThemeChoice;positive:number;negative:number;repeat_stable:null;evaluations:number}>}
export interface EconomyReview {id:string;establishment_id:string;analysis_text:string;analysis_language:string|null;rating:number;normalized_category_ratings?:{food:number|null;service:number|null;atmosphere:number|null}}
export async function planEconomy(organization_id:string,reviews:EconomyReview[],cache:EconomyCache[],served:string){let cached=0,blocked=0;const pending:EconomyIdentity[]=[],missing:string[]=[];for(const r of reviews){if(!r.analysis_text.trim())continue;if(r.analysis_language!=='en'){missing.push(r.id);continue}const identity=await economyIdentity(organization_id,r.establishment_id,r.id,r.analysis_text,served),key=await economyCacheKey(identity),row=cache.find(c=>c.cache_key===key);if(row&&reusableEconomyCache(row,identity,key))cached++;else if(row)blocked++;else pending.push(identity)}return {total_google_reviews:reviews.length,reviews_with_text:reviews.filter(r=>r.analysis_text.trim()).length,textless_reviews:reviews.filter(r=>!r.analysis_text.trim()).length,english_missing:missing.length,already_analyzed:cached,analyses_blocked:blocked,new_reviews_needing_jev:pending.length,planned_jev_calls:pending.length,three_pass_calls:pending.length*3,nominal_call_savings_percent:pending.length?100*2/3:0,expected_served_model:served,paid_enabled:false,production_enabled:false,pending}}
// Deliberately no provider dependency. No env flag can accidentally activate it.
export async function dispatchEconomicAnalysis():Promise<never>{throw new Error('ECONOMY_PAID_ENGINE_DISABLED')}
export async function consolidateEconomicResults(organization_id:string,reviews:EconomyReview[],cache:EconomyCache[],served:string){const usable=[];for(const r of reviews){if(!r.analysis_text.trim()||r.analysis_language!=='en')continue;const identity=await economyIdentity(organization_id,r.establishment_id,r.id,r.analysis_text,served),key=await economyCacheKey(identity),row=cache.find(c=>reusableEconomyCache(c,identity,key));if(row?.response)usable.push({review:r,results:economicThemeResults(row.response)})}const findings=usable.flatMap(({review:r,results})=>THEME_KEYS.flatMap(k=>(['positive','negative'] as const).filter(p=>results[k].choice===p||results[k].choice==='both').map(sentiment=>({review_id:r.id,theme_key:k,sentiment,evidence:null}))));return {total_google_reviews:reviews.length,reviews_with_text:reviews.filter(r=>r.analysis_text.trim()).length,jev_analyzed_reviews:usable.length,findings,cross_rating_analysis:crossRatingAnalysis(usable.map(x=>x.review),findings),sol_narrative_input:{total_reviews:reviews.length,analyzed_reviews:usable.length,theme_counts:THEME_KEYS.map(k=>({theme_key:k,positive:findings.filter(f=>f.theme_key===k&&f.sentiment==='positive').length,negative:findings.filter(f=>f.theme_key===k&&f.sentiment==='negative').length}))},report_generation_enabled:false}}
