import {THEME_KEYS,type ThemeKey} from './jev-themes.ts'
import {V12_CONFIG,V12_BOUNDARIES,V12_THRESHOLDS,v12Payload,v12ReportedSymptoms} from './jev-v12-config.ts'
export const V13_QUESTION_SET='themes_v13_targeted_recall_v1'
export const V13_THRESHOLD_VERSION='jev-v13-thresholds-v1-same-values-as-v12'
export const V13_THRESHOLDS=Object.freeze(Object.fromEntries(THEME_KEYS.map(k=>[k,Object.freeze({...V12_THRESHOLDS[k]})]))) as typeof V12_THRESHOLDS
export const V13_BOUNDARIES:Partial<Record<ThemeKey,string>>={
 cooking:'Cooking AND culinary preparation includes explicitly criticized seasoning or recipe execution: excessive salt, excessive sugar, excessive spices, insufficient seasoning, unbalanced seasoning/ingredient dosage, bad ingredient assembly, recipe/preparation defects, unneutralized baking soda, overcooked or undercooked food. These explicit preparation defects can establish negative cooking; the words cooked or burnt are NOT required. Generic not tasty alone belongs to food_quality; tough texture alone does not prove a cooking cause; not fresh alone belongs to freshness; a bad drink belongs to drinks. Do not automatically transfer polarity between these themes. Explicitly well-prepared or well-cooked food can be positive cooking.',
 cleanliness:'Cleanliness and hygiene includes explicitly reported unhygienic handling of served food, a server touching served food with bare hands, pests in the establishment, or other described hygiene problems. A described pest-control problem can qualify even if the customer also reports illness. Do NOT infer that the restaurant caused illness merely because symptoms or a diagnosis followed a visit. Keep reported safety/medical claims as separate diagnostics; symptoms alone do not establish cleanliness or food_quality.',
 variety:'Menu range and available choices, including advertised products or product families that cannot be ordered: unavailable burgers, several unavailable menu dishes or missing dietary options. A whole announced product family being unavailable is negative variety even without the phrase limited choice. Distinguish unavailable products BEFORE an order from an ordered product that was forgotten: a forgotten order belongs to order_accuracy, not automatically variety.',
 location:'Explicit geographic judgments about location, distance, remoteness, difficulty of access, or a trip judged not worth the journey. A customer explicitly criticizing travel from a town center to the restaurant may express negative location even when the reason for disappointment is food. Bad food alone without geographic evidence does NOT establish a location problem.',
 value:'Explicit value-for-money judgments comparing the price paid with the quantity received, meal quality or quality of service. Poor service or a small portion explicitly judged unacceptable for the price can establish negative value. Distinguish intrinsic price level (price_level), extra charges or billing errors (billing), and the received experience relative to the price (value). Expensive alone does not establish value; never reconstruct amounts or currencies from suspicious translations.',
 attentiveness:'Retain customer-care semantics: helpful, responsive or proactive care may be positive; an absent/unavailable server or explicit lack of attention, availability or taking care of guests may be negative. Waiting alone, a forgotten/wrong order alone, or bad staff attitude alone does NOT automatically establish attentiveness. Require a distinct expressed customer-care, availability or attention signal. Timing is wait_time; wrong/missing orders are order_accuracy; described organizational failures are coordination; attitude/execution or friendliness must be evaluated independently.',
 consistency:'Requires an explicitly described REAL variation in quality between food dishes or visits. Good side dishes contrasted with disappointing main dishes can be a meaningful difference between dishes. Repeated experiences that are always bad do NOT alone demonstrate variation. Good drinks alongside bad food do NOT automatically establish consistency because those are distinct categories. Never infer a variation merely from repeated complaints.',
 atmosphere:'An explicitly evaluated general ambience, mood, vibe or felt atmosphere. An explicit inability to enjoy the atmosphere or a bad perceived ambience can be negative even when caused by service. Bad service alone without an expressed atmosphere judgment is insufficient. Architecture/interior/design belongs to decor; physical seating, space or room temperature belongs to comfort. Do not automatically transfer an atmosphere polarity to decor or comfort.',
 price_level:'Explicit judgment that the intrinsic price level is high/expensive or low/cheap. A complaint that a meal or service was not worth its price belongs to value and does NOT by itself establish negative price_level. Extra charges or a wrong bill belong to billing. Do not automatically predict all three price themes from one criticism.',
}
function freeze<T>(v:T):T{if(v&&typeof v==='object'){for(const x of Object.values(v))freeze(x);Object.freeze(v)}return v}
function questions(){const q=structuredClone(V12_CONFIG.questions);for(const k of Object.keys(V13_BOUNDARIES) as ThemeKey[]){const item=q[k] as Record<string,unknown>,prior=V12_BOUNDARIES[k]??'Retain the V11 definition for this theme.',text=String(item.instructions);if(!text.endsWith(prior))throw new Error('V13_BASE_QUESTION_CHANGED');item.instructions=text.slice(0,-prior.length)+V13_BOUNDARIES[k]}return q}
export const V13_CONFIG=freeze({analysis_version:13,experimental_only:true,production_enabled:false,question_set:V13_QUESTION_SET,parent_question_set:V12_CONFIG.question_set,threshold_version:V13_THRESHOLD_VERSION,thresholds:V13_THRESHOLDS,requested_model:'jev-latest',repeat_count:3,concurrency:8,macro_min_support:3,questions:questions(),semantic_diagnostic_version:'v13-reported-safety-v1'})
export function v13Payload(alias:string,text:string){const p=structuredClone(v12Payload(alias,text));p.questions=structuredClone(V13_CONFIG.questions);return p}
export function v13ReportedSafety(text:string){const prior=v12ReportedSymptoms(text),cues=text.match(/\b(?:dengue|nausea|stomach pain|mosquito(?:es)?|pest(?:s)?)\b/gi)??[];return prior||cues.length?{signal:'reported_safety_requires_review',reported_only:true,causality_confirmed:false,creates_theme:false,cues:[...new Set([...(prior?.cues??[]),...cues.map(c=>c.toLowerCase())])]}:null}
