import {PILOT_AXES,type PilotSnapshot,type pilotStatistics} from './jev-pilot-core.ts'
import {negativeHash} from './negative-validation-core.ts'
import {canonicalJson} from './jev-exploratory-core.ts'
import {GOLD_TAXONOMY} from './gold-taxonomy.ts'
export type PilotNarrativeContext=ReturnType<typeof pilotNarrativeContext>
export function pilotNarrativeContext(snapshot:PilotSnapshot,stats:ReturnType<typeof pilotStatistics>,language:'fr'|'vi'){
 const topics=[...stats.positive_topics,...stats.negative_topics].map(t=>({key:t.key,theme_key:t.theme_key,axis:t.axis,sentiment:t.sentiment,mentions:t.mentions,affected_reviews:t.affected_reviews,label:GOLD_TAXONOMY[t.theme_key][language]})),proofs:{review_id:string;theme_keys:string[];english_excerpt:string;excerpt_truncated:boolean;source_sha256:string}[]=[];
 for(const axis of PILOT_AXES)for(const sentiment of ['negative','positive'] as const){const t=[...stats.negative_topics,...stats.positive_topics].find(t=>t.axis===axis&&t.sentiment===sentiment);if(t?.examples[0]){const e=t.examples[0],existing=proofs.find(p=>p.review_id===e.review_id);if(existing)existing.theme_keys.push(t.key);else proofs.push({review_id:e.review_id,theme_keys:[t.key],english_excerpt:e.analysis_text.slice(0,1200),excerpt_truncated:e.analysis_text.length>1200,source_sha256:snapshot.source.reviews.find(r=>r.id===e.review_id)!.analysis_text_sha256!})}}
 return {report_type:'experimental_pilot_not_production',language,snapshot_sha256:snapshot.source_sha256,coverage:stats.coverage,coverage_warnings:stats.warnings,star_distribution:stats.star_distribution,topics,axes:stats.axes,representative_evidence:proofs,google_context:stats.google_context,cross_rating_summary:{scope:'assessed_review_subset',axes:stats.cross_rating_analysis.axes,price:stats.cross_rating_analysis.price},structured_context_stats:stats.structured_context_stats,authoritative_numbers:true,restaurant_theme_frequencies:null}
}
import type {PilotProse} from './jev-pilot-types.ts'
export type {PilotProse} from './jev-pilot-types.ts'
export function validatePilotProse(raw:unknown,input:PilotNarrativeContext):PilotProse{const p=raw as PilotProse,keys=new Map(input.topics.map(t=>[t.key,t])),ids=new Set(input.representative_evidence.map(e=>e.review_id)),validString=(s:unknown)=>typeof s==='string'&&s.trim()&&s.length<5000&&!/\p{N}|https?:\/\//u.test(s);if(!p||!Array.isArray(p.axes)||p.axes.length!==4||new Set(p.axes.map(a=>a.key)).size!==4||p.axes.some(a=>!PILOT_AXES.includes(a.key)||!validString(a.description)||!Array.isArray(a.supporting_keys)||(input.topics.some(t=>t.axis===a.key)&&!a.supporting_keys.length)||a.supporting_keys.some(k=>keys.get(k)?.axis!==a.key))||!validString(p.conclusion)||!Array.isArray(p.positive_aspects)||!Array.isArray(p.negative_aspects)||!Array.isArray(p.recommendations))throw new Error('PILOT_NARRATIVE_UNGROUNDED');
 for(const sentiment of ['positive','negative'] as const)if(p[`${sentiment}_aspects`].some(a=>keys.get(a.key)?.sentiment!==sentiment||!validString(a.text)))throw new Error('PILOT_NARRATIVE_UNGROUNDED');for(const r of p.recommendations){if(!validString(r.text)||!Array.isArray(r.supporting_keys)||!r.supporting_keys.length||r.supporting_keys.some(k=>!keys.has(k))||!Array.isArray(r.evidence_review_ids)||!r.evidence_review_ids.length||r.evidence_review_ids.some(id=>!ids.has(id))||r.supporting_keys.some(k=>!input.representative_evidence.some(e=>r.evidence_review_ids.includes(e.review_id)&&e.theme_keys.includes(k))))throw new Error('PILOT_NARRATIVE_UNGROUNDED')}return p}
export function fallbackPilotProse(input:PilotNarrativeContext):PilotProse{const fr=input.language==='fr';return {axes:PILOT_AXES.map(key=>({key,description:fr?'Consulter les comptages exacts et les avis associés pour cet axe.':'Xem số lượng chính xác và đánh giá liên quan cho trục này.',supporting_keys:input.topics.filter(t=>t.axis===key).slice(0,2).map(t=>t.key)})),positive_aspects:input.topics.filter(t=>t.sentiment==='positive').map(t=>({key:t.key,text:fr?'Signal positif détecté par Jev dans les avis analysés.':'Tín hiệu tích cực do Jev phát hiện trong đánh giá đã phân tích.'})),negative_aspects:input.topics.filter(t=>t.sentiment==='negative').map(t=>({key:t.key,text:fr?'Signal négatif détecté par Jev dans les avis analysés.':'Tín hiệu tiêu cực do Jev phát hiện trong đánh giá đã phân tích.'})),conclusion:fr?'Cette lecture reste limitée au périmètre analysé. Vérifier la couverture et les avis avant toute décision globale.':'Kết quả chỉ giới hạn trong phạm vi đã phân tích. Kiểm tra mức bao phủ và đánh giá trước quyết định tổng thể.',recommendations:[]}}
export const pilotNarrativeHash=(context:PilotNarrativeContext)=>negativeHash(canonicalJson(context))
