import {THEME_KEYS,THEME_CHOICES,themePresence,type ThemeKey,type ThemeDecision,type ThemeChoice} from './jev-themes.ts'
import {V12_CONFIG,V12_THRESHOLDS,v12Payload,v12ReportedSymptoms} from './jev-v12-config.ts'
import {V11_THRESHOLDS,meetsV11Threshold} from './jev-v11-calibration.ts'
import {canonicalJson,exploratoryFingerprint,type ExploratoryItem} from './jev-exploratory-core.ts'
import type {NegativeTask} from './negative-validation-score.ts'
import {negativeHash as sha} from './negative-validation-core.ts'
import {verifyAiBenchmark,type AiBenchmarkRun,type AiPreannotation} from './ai-exploratory-benchmark.ts'
import {GOLD_TAXONOMY,type GoldChoice} from './gold-taxonomy.ts'
export const V12_SOURCE_EXPERIMENT='a80c5a80-c322-4c13-85d4-e7506f91ec93',V12_SOURCE_BENCHMARK='adfa4fdf-a8c7-4976-916f-339ebabb8d62',V12_PROTECTED_HOLDOUT='d7d7142c-03ef-48c3-b36e-bacf6d923f40'
export interface AiThemeRecheck {exploratory_run_id:string;review_id:string;theme_key:ThemeKey;initial_ai_choice:GoldChoice;jev_v9_choice:string;jev_v11_choice:string;reviewed_ai_choice:GoldChoice;judgement:'confirmed'|'revised'|'uncertain';confidence:string;reasoning_fr:string;supporting_excerpt:string;created_at:string}
export interface V12Reference {review_id:string;theme_key:ThemeKey;initial_choice:GoldChoice;choice:GoldChoice;origin:'chatgpt_initial_ai'|'chatgpt_ai_recheck';model_source:string;recheck:AiThemeRecheck|null}
export interface V12Task {id:string;run_id:string;review_id:string;repeat:number;status:'pending'|'running'|'completed'|'failed';response:ThemeDecision|null;served_model:string|null;input_tokens:number;output_tokens:number;request_count:number;retry_count:number;cost_usd:number;duration_ms:number;error_code:string|null;usage_complete:boolean}
export function validThemeDecision(d:ThemeDecision|null){return !!d?.themes&&Object.keys(d.themes).length===25&&THEME_KEYS.every(k=>{const a=d.themes[k];return !!a&&THEME_CHOICES.includes(a.choice)&&THEME_CHOICES.every(c=>Number.isFinite(a.probabilities?.[c])&&a.probabilities[c]>=0&&a.probabilities[c]<=1)&&Math.abs(THEME_CHOICES.reduce((n,c)=>n+a.probabilities[c],0)-1)<=.01+8*Number.EPSILON})}
export function completeReview(tasks:{review_id:string;repeat:number;status:string;response:ThemeDecision|null}[],id:string){const reps=tasks.filter(t=>t.review_id===id);return reps.length===3&&[1,2,3].every(r=>reps.filter(t=>t.repeat===r).length===1&&reps.find(t=>t.repeat===r)!.status==='completed'&&validThemeDecision(reps.find(t=>t.repeat===r)!.response))}
export async function prepareV12(source:AiBenchmarkRun,tasks:NegativeTask[],initial:AiPreannotation[],rechecks:AiThemeRecheck[],protectedIds:string[],rate:number){
 if(source.id!==V12_SOURCE_BENCHMARK||source.source_experiment_id!==V12_SOURCE_EXPERIMENT||source.status!=='completed')throw new Error('V12_SOURCE_REQUIRED');await verifyAiBenchmark(source)
 if(canonicalJson(source.model_config.v11.thresholds)!==canonicalJson(V12_THRESHOLDS)||canonicalJson(V11_THRESHOLDS)!==canonicalJson(V12_THRESHOLDS))throw new Error('V12_THRESHOLDS_CHANGED')
 const all=source.dataset_snapshot.map(i=>({...i})).sort((a,b)=>a.position-b.position),ids=new Set(all.map(i=>i.review_id));if(all.some(i=>protectedIds.includes(i.review_id)))throw new Error('V12_HOLDOUT_PROTECTED');if(all.some(i=>(i as ExploratoryItem&{analysis_language?:string}).analysis_language!=='en'))throw new Error('V12_ENGLISH_REQUIRED')
 if(initial.length!==all.length||new Set(initial.map(i=>i.review_id)).size!==initial.length||await sha(canonicalJson([...initial].sort((a,b)=>a.review_id.localeCompare(b.review_id))))!==source.reference_sha256)throw new Error('V12_INITIAL_REFERENCE_CHANGED')
 const updates=new Map<string,AiThemeRecheck>();for(const r of rechecks){const a=initial.find(a=>a.review_id===r.review_id);if(r.exploratory_run_id!==source.id||!ids.has(r.review_id)||!a||!THEME_KEYS.includes(r.theme_key)||!['absent','positive','negative','both','uncertain'].includes(r.reviewed_ai_choice)||r.initial_ai_choice!==a.theme_choices[r.theme_key]||updates.has(r.review_id+':'+r.theme_key))throw new Error('V12_RECHECK_INVALID');updates.set(r.review_id+':'+r.theme_key,r)}
 const v9=tasks.filter(t=>t.model_version==='v9'),v11=tasks.filter(t=>t.model_version==='v11'),selected=all.filter(i=>completeReview(v9,i.review_id)&&completeReview(v11,i.review_id));if(!selected.length)throw new Error('V12_NO_PAIRED_REVIEWS')
 const selectedIds=new Set(selected.map(i=>i.review_id)),items=selected.map(i=>({review_id:i.review_id,position:i.position,analysis_text:i.analysis_text,analysis_text_sha256:i.analysis_text_sha256,overall_rating:i.overall_rating,normalized_category_ratings:i.normalized_category_ratings,v9:{},v11:{}})),reference:V12Reference[]=items.flatMap(i=>THEME_KEYS.map(theme_key=>{const a=initial.find(a=>a.review_id===i.review_id)!,r=updates.get(i.review_id+':'+theme_key);return {review_id:i.review_id,theme_key,initial_choice:a.theme_choices[theme_key],choice:r?(r.judgement==='uncertain'?'uncertain':r.reviewed_ai_choice):a.theme_choices[theme_key],origin:r?'chatgpt_ai_recheck' as const:'chatgpt_initial_ai' as const,model_source:r?'not_recorded_in_legacy_rechecks':a.model_source,recheck:r??null}})),baseline=v11.filter(t=>selectedIds.has(t.review_id)).map(t=>({...t})),source_exclusions=all.filter(i=>!selectedIds.has(i.review_id)).map(i=>({review_id:i.review_id,errors:tasks.filter(t=>t.review_id===i.review_id&&(t.status!=='completed'||!validThemeDecision(t.response))).map(t=>({version:t.model_version,repeat:t.repeat,error_code:t.error_code??'INVALID_PERSISTED_RESPONSE'}))})),config_sha256=await sha(canonicalJson(V12_CONFIG)),dataset_sha256=await exploratoryFingerprint(items),reference_sha256=await sha(canonicalJson(reference)),baseline_sha256=await sha(canonicalJson(baseline)),prepared_sha256=await sha(canonicalJson({config_sha256,dataset_sha256,reference_sha256,baseline_sha256,source_benchmark_id:source.id,input_rate:rate,expected_requests:items.length*3})),estimated_input_tokens=Math.ceil(items.reduce((n,i)=>n+canonicalJson(v12Payload('r'+i.position,i.analysis_text)).length,0)*3/4*1.25)
 return {items,reference,initial_snapshot:initial,rechecks_snapshot:rechecks,baseline,source_exclusions,source_total_reviews:all.length,source_invalid_responses:tasks.filter(t=>t.status!=='completed'||!validThemeDecision(t.response)).length,rechecks_total:rechecks.length,rechecks_applied:reference.filter(r=>r.origin==='chatgpt_ai_recheck').length,config_sha256,dataset_sha256,reference_sha256,baseline_sha256,prepared_sha256,source_dataset_sha256:source.dataset_sha256,estimated_input_tokens,estimated_cost_usd:estimated_input_tokens*rate/1_000_000,expected_requests:items.length*3,input_rate:rate}
}
export type V12Prepared=Awaited<ReturnType<typeof prepareV12>>
export interface V12Run {id:string;organization_id:string;establishment_id:string;source_benchmark_id:string;status:'queued'|'running'|'completed'|'failed';config:typeof V12_CONFIG;prepared:V12Prepared;created_at:string;started_at:string|null;completed_at:string|null;error_code:string|null}
export async function verifyV12(run:V12Run){const p=run.prepared;if(run.source_benchmark_id!==V12_SOURCE_BENCHMARK||canonicalJson(run.config)!==canonicalJson(V12_CONFIG)||await sha(canonicalJson(V12_CONFIG))!==p.config_sha256||await exploratoryFingerprint(p.items)!==p.dataset_sha256||await sha(canonicalJson(p.reference))!==p.reference_sha256||await sha(canonicalJson(p.baseline))!==p.baseline_sha256||p.baseline.length!==p.items.length*3||p.expected_requests!==p.items.length*3)throw new Error('V12_INTEGRITY_CHANGED')}
function predictions(tasks:(V12Task|NegativeTask)[],id:string){if(!completeReview(tasks,id))return null;const reps=tasks.filter(t=>t.review_id===id);return Object.fromEntries(THEME_KEYS.map(k=>{const answers=reps.map(t=>t.response!.themes[k]),probs=answers.map(themePresence),positive=probs.reduce((n,p)=>n+p.positive_presence_probability,0)/3,negative=probs.reduce((n,p)=>n+p.negative_presence_probability,0)/3,p=meetsV11Threshold(positive,V12_THRESHOLDS[k].positive_threshold),n=meetsV11Threshold(negative,V12_THRESHOLDS[k].negative_threshold),ps=probs.map(a=>a.positive_presence_probability),ns=probs.map(a=>a.negative_presence_probability);return [k,{choice:(p?n?'both':'positive':n?'negative':'absent') as ThemeChoice,positive,negative,stable:new Set(answers.map(a=>a.choice)).size===1,probability_drift:Math.max(Math.max(...ps)-Math.min(...ps),Math.max(...ns)-Math.min(...ns))}]})) as Record<ThemeKey,{choice:ThemeChoice;positive:number;negative:number;stable:boolean;probability_drift:number}>}
const counts=()=>({tp:0,fp:0,fn:0,support:0}),sum=(rows:ReturnType<typeof counts>[])=>rows.reduce((a,b)=>({tp:a.tp+b.tp,fp:a.fp+b.fp,fn:a.fn+b.fn,support:a.support+b.support}),counts()),has=(c:GoldChoice,p:'positive'|'negative')=>c===p||c==='both'
const metrics=(c:ReturnType<typeof counts>)=>({...c,precision:c.tp+c.fp?c.tp/(c.tp+c.fp):null,recall:c.support?c.tp/c.support:null,f1:c.support?2*c.tp/(2*c.tp+c.fp+c.fn):null})
function modelScore(ids:string[],reference:V12Reference[],tasks:(V12Task|NegativeTask)[]){const themes=Object.fromEntries(THEME_KEYS.map(k=>[k,{positive:counts(),negative:counts()}])),perReview:{overall:ReturnType<typeof counts>;negative:ReturnType<typeof counts>}[]=[],errors:{review_id:string;theme_key:ThemeKey;polarity:'positive'|'negative';kind:'false_positive'|'false_negative';ai_reference:GoldChoice;predicted:ThemeChoice}[]=[],drifts:number[]=[];let compared=0,same=0,uncertain=0,stable=0,pairs=0
 for(const id of ids){const predicted=predictions(tasks,id)!,all=counts(),neg=counts();for(const k of THEME_KEYS){const r=reference.find(r=>r.review_id===id&&r.theme_key===k)!,p=predicted[k];pairs++;if(p.stable)stable++;drifts.push(p.probability_drift);if(r.choice==='uncertain'){uncertain++;continue}compared++;if(r.choice===p.choice)same++;for(const polarity of ['positive','negative'] as const){const a=has(r.choice,polarity),b=has(p.choice,polarity),c=themes[k][polarity];if(a){c.support++;all.support++;if(polarity==='negative')neg.support++}const key=b?a?'tp':'fp':a?'fn':null;if(key){c[key]++;all[key]++;if(polarity==='negative')neg[key]++;if(key==='fp'||key==='fn')errors.push({review_id:id,theme_key:k,polarity,kind:key==='fp'?'false_positive':'false_negative',ai_reference:r.choice,predicted:p.choice})}}}perReview.push({overall:all,negative:neg})}
 const pos=THEME_KEYS.map(k=>themes[k].positive),neg=THEME_KEYS.map(k=>themes[k].negative),supported=[...pos,...neg].filter(c=>c.support>=3),macro=supported.map(c=>metrics(c).f1!),sorted=[...drifts].sort((a,b)=>a-b);return {overall:metrics(sum([...pos,...neg])),positive:metrics(sum(pos)),negative:metrics(sum(neg)),micro_f1:metrics(sum([...pos,...neg])).f1,macro_f1:macro.length?macro.reduce((n,v)=>n+v,0)/macro.length:null,macro_supported_labels:supported.length,exact_choice_agreement:compared?same/compared:null,compared_labels:compared,uncertain_labels:uncertain,repeat_choice_stability:pairs?stable/pairs:null,mean_probability_drift:drifts.length?drifts.reduce((n,v)=>n+v,0)/drifts.length:null,p95_probability_drift:sorted.length?sorted[Math.ceil(sorted.length*.95)-1]:null,themes:Object.fromEntries(THEME_KEYS.map(k=>[k,{positive:metrics(themes[k].positive),negative:metrics(themes[k].negative)}])),axes:Object.fromEntries(['quality','service','atmosphere','price'].map(axis=>{const keys=THEME_KEYS.filter(k=>GOLD_TAXONOMY[k].axis===axis);return [axis,{positive:metrics(sum(keys.map(k=>themes[k].positive))),negative:metrics(sum(keys.map(k=>themes[k].negative)))}]})),errors,perReview}}
async function pairedBootstrap(id:string,a:ReturnType<typeof modelScore>,b:ReturnType<typeof modelScore>,kind:'overall'|'negative',complete:boolean){const seed=await sha(id+':'+kind);let state=parseInt(seed.slice(0,8),16)||1;const random=()=>{state^=state<<13;state^=state>>>17;state^=state<<5;return (state>>>0)/4294967296},values:number[]=[];let undefined_samples=0;for(let n=0;n<2000;n++){const x=[],y=[];for(let j=0;j<a.perReview.length;j++){const k=Math.floor(random()*a.perReview.length);x.push(a.perReview[k][kind]);y.push(b.perReview[k][kind])}const f=metrics(sum(x)).f1,g=metrics(sum(y)).f1;if(f===null||g===null)undefined_samples++;else values.push(g-f)}values.sort((x,y)=>x-y);const support_reviews=a.perReview.filter(r=>r[kind].support>0).length,valid=complete&&support_reviews>=3&&undefined_samples===0&&values.length===2000;return {method:'paired_review_bootstrap',resamples:2000,seed_sha256:seed,support_reviews,undefined_samples,delta:a[kind].f1===null||b[kind].f1===null?null:b[kind].f1-a[kind].f1,ci_95_low:valid?values[Math.floor(1999*.025)]:null,ci_95_high:valid?values[Math.floor(1999*.975)]:null,conclusive_interval_available:valid,independent_validation:false}}
export async function compareV12(run:V12Run,tasks:V12Task[]){await verifyV12(run);const p=run.prepared,ids=p.items.filter(i=>completeReview(tasks,i.review_id)).map(i=>i.review_id),a=modelScore(ids,p.reference,p.baseline),b=modelScore(ids,p.reference,tasks),{perReview:_a,...v11}=a,{perReview:_b,...v12}=b;void _a;void _b
 const usage=(rows:(V12Task|NegativeTask)[])=>({input_tokens:rows.reduce((n,t)=>n+t.input_tokens,0),output_tokens:rows.reduce((n,t)=>n+t.output_tokens,0),estimated_cost_usd:rows.reduce((n,t)=>n+t.cost_usd,0),requests:rows.reduce((n,t)=>n+t.request_count,0),request_elapsed_sum_ms:rows.reduce((n,t)=>n+t.duration_ms,0),served_models:[...new Set(rows.flatMap(t=>t.served_model?[t.served_model]:[]))].sort(),usage_complete:rows.every(t=>t.usage_complete)}),used11=usage(p.baseline),used12=usage(tasks),reviews=p.items.map(i=>{const before=predictions(p.baseline,i.review_id)!,after=predictions(tasks,i.review_id),reasons:{code:string;theme_key?:ThemeKey}[]=[];for(const k of THEME_KEYS){const r=p.reference.find(r=>r.review_id===i.review_id&&r.theme_key===k)!;if(!after){if(k===THEME_KEYS[0])reasons.push({code:'incomplete_v12'});continue}if(before[k].choice!==after[k].choice)reasons.push({code:'v11_v12_disagreement',theme_key:k});if(!after[k].stable||after[k].probability_drift>=.2)reasons.push({code:'repeat_instability',theme_key:k});if(r.choice!=='uncertain'&&r.choice!==after[k].choice)reasons.push({code:'ai_reference_disagreement',theme_key:k})}const safety=v12ReportedSymptoms(i.analysis_text);if(safety)reasons.push({code:'reported_symptoms_no_causality'});return {...i,v11:before,v12:after,ai_reference:Object.fromEntries(p.reference.filter(r=>r.review_id===i.review_id).map(r=>[r.theme_key,r.choice])),reasons,safety}})
 return {analysis_version:12,experimental_only:true,production_enabled:false,reference_type:'chatgpt_initial_plus_ai_rechecks_non_independent',human_validated:false,source_benchmark_id:run.source_benchmark_id,config:run.config,source_reviews:p.source_total_reviews,eligible_reviews:p.items.length,evaluable_reviews:ids.length,complete:ids.length===p.items.length,source_exclusions:p.source_exclusions,source_invalid_responses:p.source_invalid_responses,v12_failures:tasks.filter(t=>t.status==='failed').map(t=>({review_id:t.review_id,repeat:t.repeat,error_code:t.error_code})),v11,v12,bootstrap:{overall:await pairedBootstrap(run.id,a,b,'overall',ids.length===p.items.length),negative:await pairedBootstrap(run.id,a,b,'negative',ids.length===p.items.length)},rechecks_total:p.rechecks_total,rechecks_applied:p.rechecks_applied,reference_uncertain_total:p.reference.filter(r=>r.choice==='uncertain').length,usage:{v11:used11,v12:used12,new_paid_v11_requests:0},model_version_confounded:canonicalJson(used11.served_models)!==canonicalJson(used12.served_models)||used12.served_models.length>1,reviews,disagreement_count:reviews.reduce((n,r)=>n+r.reasons.filter(r=>r.code==='v11_v12_disagreement').length,0),end_to_end_elapsed_ms:run.started_at&&run.completed_at?Date.parse(run.completed_at)-Date.parse(run.started_at):null,translation_policy:'exact_frozen_source_no_overrides',warning:'Training/calibration sample and non-independent ChatGPT AI references. Exploratory metrics only; no production decision or automatic recalibration.'}
}
