import {describe,it,expect,vi,afterEach} from 'vitest'
import {readFileSync,readdirSync} from 'node:fs'
import {syntheticPilot,pilotRepo,pilotRates,pilotDecision} from '../../../tests/fixtures/jev-pilot'
import {auditPilotCache,pilotStatistics,pilotCosts,pilotComparison,verifyPilotSnapshot,resolvePilotReviews,pilotSourceHash} from './jev-pilot-core'
import {pilotHandler,pilotPlan} from './jev-pilot-api'
import {pilotNarrativeContext,validatePilotProse,fallbackPilotProse} from './jev-pilot-narrative'
import {canonicalJson} from './jev-exploratory-core'
import {ECONOMY_CONFIG,economyPayload} from './jev-economy-config'
import {economicThemeResults} from './jev-economy-cache'
import {negativeHash} from './negative-validation-core'
afterEach(()=>vi.unstubAllGlobals())
describe('frozen economic pilot and zero-cost preview',()=>{
 it('uses full V12 one-pass only; original English, overrides, missing English and textless remain distinct',async()=>{const f=await syntheticPilot();expect(f.snapshot.source.reviews[6].analysis_text).toBeNull();expect(f.snapshot.source.reviews[7].analysis_text).toBeNull();expect(f.snapshot.source.reviews[7].original_text).toBe('Texte sans traduction');expect(ECONOMY_CONFIG.repeat_count).toBe(1);expect(Object.keys(economyPayload('alias','English').state)).toEqual(['review_alias','analysis_text']);await expect(verifyPilotSnapshot(f.snapshot)).resolves.toBeUndefined()})
 it.each(['organization_id','establishment_id','analysis_text_sha256','instruction_sha256','threshold_version','threshold_sha256','served_model','expected_served_model','cache_key'] as const)('rejects cache mismatch in %s',async field=>{const f=await syntheticPilot();f.cache[0][field]='changed';expect((await auditPilotCache(f.snapshot.source.reviews,f.cache,f.snapshot.organization_id,f.snapshot.establishment_id)).used).toHaveLength(1)})
 it('changed corrected text invalidates old cache without mutation, and compact responses never count',async()=>{const f=await syntheticPilot(),before=canonicalJson(f.cache);f.snapshot.source.reviews[0].analysis_text+=' corrected';f.snapshot.source.reviews[0].analysis_text_sha256=await negativeHash(f.snapshot.source.reviews[0].analysis_text!);f.cache.push({...f.cache[1],id:'compact',configuration_id:'v12_economy_compact_experimental_v1'});const a=await auditPilotCache(f.snapshot.source.reviews,f.cache,f.snapshot.organization_id,f.snapshot.establishment_id);expect(a.used).toHaveLength(1);expect(a.rejected[0].reasons).toContain('ENGLISH_TEXT_CHANGED');expect(a.excluded_other_configuration_rows).toBe(1);expect(canonicalJson(f.cache.slice(0,2))).toBe(before)})
 it('25-theme response and stored choice must agree; uncertain billing remains blocked with zero retries',async()=>{const f=await syntheticPilot();f.cache[0].theme_results={};f.cache[1].status='billing_uncertain';const a=await auditPilotCache(f.snapshot.source.reviews,f.cache,f.snapshot.organization_id,f.snapshot.establishment_id);expect(a.used).toHaveLength(0);expect(a.blocked_review_ids).toHaveLength(1);expect(a.rejected[0].reasons).toContain('STORED_THEMES_INCONSISTENT')})
 it('deduplicates completed models/repeats by review, counts both once per polarity and reports biased partial coverage',async()=>{const f=await syntheticPilot();f.cache.push({...f.cache[0],id:'duplicate'});const a=await auditPilotCache(f.snapshot.source.reviews,f.cache,f.snapshot.organization_id,f.snapshot.establishment_id),s=pilotStatistics(f.snapshot.source.reviews,a,20);expect(s.coverage).toMatchObject({stored_reviews:8,reviews_with_text:7,textless_reviews:1,english_ready:6,analysed_reviews:2,missing_analyses:4,missing_english:1});expect(s.warnings).toEqual(expect.arrayContaining(['PARTIAL_TEXT_COVERAGE','PARTIAL_GOOGLE_DATASET','STAR_DISTRIBUTION_BIASED']));expect(s.positive_topics.find(t=>t.theme_key==='food_quality')?.mentions).toBe(2);expect(s.negative_topics.find(t=>t.theme_key==='food_quality')?.affected_reviews).toBe(2);expect(s.theme_frequencies_for_restaurant).toBeNull();expect(s.google_context.price.google_rating).toBeNull()})
 it('Google scores never create text findings; cross-rating excludes unanalysed reviews',async()=>{const f=await syntheticPilot();f.cache.forEach(c=>{c.response=pilotDecision();c.theme_results=economicThemeResults(c.response)});const s=pilotStatistics(f.snapshot.source.reviews,await auditPilotCache(f.snapshot.source.reviews,f.cache,f.snapshot.organization_id,f.snapshot.establishment_id),20);expect(s.findings).toEqual([]);expect(s.cross_rating_analysis.total_reviews).toBe(2);expect(s.cross_rating_analysis.axes.service.low_score_unexplained_count).toBe(1)})
 it('checks snapshot SHA/original SHA/tenant and never mutates source; idempotent previews',async()=>{const f=await syntheticPilot(),before=canonicalJson(f.snapshot);expect(pilotStatistics(f.snapshot.source.reviews,f.audit,20)).toEqual(pilotStatistics(f.snapshot.source.reviews,f.audit,20));expect(canonicalJson(f.snapshot)).toBe(before);f.snapshot.source.reviews[0].original_text+=' changed';await expect(verifyPilotSnapshot(f.snapshot)).rejects.toThrow('SNAPSHOT_CHANGED');f.snapshot.source_sha256=await pilotSourceHash(f.snapshot.source);await expect(verifyPilotSnapshot(f.snapshot)).rejects.toThrow('TEXT_CHANGED');await expect(resolvePilotReviews([{...f.raw[0],organization_id:'other'}],[],f.snapshot.organization_id,f.snapshot.establishment_id,'2026-10-11')).rejects.toThrow('TENANT')})
 it('uses existing validated English override hashes; rejected overrides signaled, provider/original unchanged',async()=>{const f=await syntheticPilot(),r={...f.raw[0],original_language:'fr',original_text:'Boissons agréables',review_translations:[{id:'provider',language:'en',translated_text:'Bad drinks'}]},o={review_id:r.id,original_text_sha256:await negativeHash(r.original_text),provider_translation_sha256:await negativeHash('Bad drinks'),correction_language:'en',corrected_english_text:'Pleasant drinks',corrected_english_sha256:await negativeHash('Pleasant drinks'),error_type:'polarity',evidence_fr:'test synthétique',source:'chatgpt_gpt_6_manual_audit',status:'candidate_for_future_analysis',benchmark_policy:'do_not_change_frozen_v9_v11_inputs',created_at:'2026-01-01'},before=canonicalJson(r);const rows=await resolvePilotReviews([r],[o],r.organization_id,r.establishment_id,'2026-10-11');expect(rows[0].analysis_text).toBe('Pleasant drinks');expect(canonicalJson(r)).toBe(before);o.provider_translation_sha256='bad';expect((await resolvePilotReviews([r],[o],r.organization_id,r.establishment_id,'2026-10-11'))[0].translation_provenance).toMatchObject({status:'rejected'})})
 it('prices known phases only, cached cost zero, tariffs unavailable stay null',()=>{const c=pilotCosts(pilotRates,361);expect(c.estimated_jev_cost_usd).toBeCloseTo(.121296);expect(c.estimated_sol_cost_usd).toBe(.018);expect(c.reused_extra_cost_usd).toBe(0);expect(c.apify_cost_usd).toBeNull();expect(c.translation_unit_cost_usd).toBeNull();expect(pilotCosts({...pilotRates,sol_input:null},361).total_known_usd).toBeNull();expect(pilotCosts(pilotRates,4,1).planned_jev_requests).toBe(3)})
 it('legacy difference disclosed, available IDs not invented and old price stays unknown',async()=>{const f=await syntheticPilot(),c=pilotComparison(f.snapshot.source,pilotStatistics(f.snapshot.source.reviews,f.audit,20));expect(c.directly_comparable).toBe(false);expect(c.dataset).toEqual({old_stored:7,pilot_stored:8,common_reviews:6,old_only:0,pilot_only:2});expect(c.legacy?.ai_cost_usd).toBeNull();expect(c.matched_snapshot_protocol.enabled).toBe(false)})
 it('Sol prepared aggregates and bounded real text excerpts; no original texts or all-review list',async()=>{const f=await syntheticPilot(),s=pilotStatistics(f.snapshot.source.reviews,f.audit,20),c=pilotNarrativeContext(f.snapshot,s,'vi');expect(c.representative_evidence.length).toBeLessThanOrEqual(8);expect(c.representative_evidence.every(e=>e.english_excerpt.length<=1200)).toBe(true);expect(JSON.stringify(c)).not.toContain('original_text');expect(JSON.stringify(c)).not.toContain(f.snapshot.source.reviews[4].analysis_text);expect(validatePilotProse(fallbackPilotProse(c),c)).toBeTruthy();const invalid=fallbackPilotProse(c);invalid.conclusion='Invented 900 problems';expect(()=>validatePilotProse(invalid,c)).toThrow('UNGROUNDED');invalid.conclusion='Conclusion';invalid.recommendations=[{text:'Action',supporting_keys:['invented:negative'],evidence_review_ids:['invented']}];expect(()=>validatePilotProse(invalid,c)).toThrow('UNGROUNDED')})
 it('no network during previews/context/plans',async()=>{const network=vi.fn();vi.stubGlobal('fetch',network);const f=await syntheticPilot();await pilotPlan(f.snapshot,f.cache,'fr');expect(network).not.toHaveBeenCalled()})
})
describe('manual two-stage pilot API and durable SQL fences',()=>{
 it('GET and reload are read-only; snapshot only on free explicit POST',async()=>{const f=await syntheticPilot(),r=pilotRepo(f),prepare=vi.fn();r.prepare=prepare;const h=pilotHandler(async()=>r);for(let i=0;i<2;i++){const b=await(await h(new Request('https://fixture'))).json();expect(b.can_complete_jev).toBe(false);expect(b.can_generate_sol).toBe(false);expect(b.jobs).toEqual([])}expect(prepare).not.toHaveBeenCalled();await h(new Request('https://fixture',{method:'POST',body:JSON.stringify({action:'prepare_snapshot'})}));expect(prepare).toHaveBeenCalledOnce()})
 it.each(['complete_jev','generate_sol'])('%s requires a new independent authorization and cost confirmation',async action=>{const f=await syntheticPilot(),r=pilotRepo(f),start=vi.fn();r.start=start;const h=pilotHandler(async()=>r),p=await pilotPlan(f.snapshot,f.cache,'fr'),body={action,confirm_cost:true,source_sha256:f.snapshot.source_sha256,input_sha256:action==='complete_jev'?p.jev_input_sha:p.sol_input_sha};expect(await(await h(new Request('https://fixture',{method:'POST',body:JSON.stringify(body)}))).json()).toEqual({error:'PILOT_NEW_AUTHORIZATION_REQUIRED'});expect(start).not.toHaveBeenCalled();expect(await(await h(new Request('https://fixture',{method:'POST',body:JSON.stringify({...body,confirm_cost:false})}))).json()).toEqual({error:'PILOT_COST_CONFIRMATION_REQUIRED'})})
 it('explicit Jev phase does not generate Sol; one-shot stage scope, unauthorized data refused',async()=>{const f=await syntheticPilot(),r=pilotRepo(f),p=await pilotPlan(f.snapshot,f.cache,'fr'),start=vi.fn();r.start=start;r.authorizations=async()=>[{id:'go',snapshot_id:f.snapshot.id,stage:'jev',language:'en',source_sha256:f.snapshot.source_sha256,config_sha256:f.snapshot.config_sha256,input_sha256:p.jev_input_sha,allowed_review_ids:p.review_ids,max_calls:4,allow_partial_report:false}];const h=pilotHandler(async()=>r);await h(new Request('https://fixture',{method:'POST',body:JSON.stringify({action:'complete_jev',confirm_cost:true,source_sha256:f.snapshot.source_sha256,input_sha256:p.jev_input_sha})}));expect(start).toHaveBeenCalledOnce();expect(start.mock.calls[0][0]).toBe('jev');expect((await pilotHandler(async()=>{throw new Error('FORBIDDEN')})(new Request('https://fixture'))).status).toBe(403)})
 it('SQL locks/cache identity, immutable new tables and authenticated RLS, no paid retry/no historical inserts',()=>{const dir='supabase/migrations/',sql=readFileSync(dir+readdirSync(dir).find(n=>n.endsWith('_jev_economy_pilot_preparation.sql')),'utf8');for(const text of ['enable row level security','pg_advisory_xact_lock','PILOT_NEW_AUTHORIZATION_REQUIRED','PILOT_IMMUTABLE','PILOT_NO_AUTOMATIC_RETRY','PILOT_SINGLE_PASS_ONLY','limit 8','retry_count=0','from public,anon,authenticated','where exists(select 1 from public.analysis_jev_pilot_jobs'])expect(sql).toContain(text);expect(sql).not.toMatch(/insert into public\.(historical|analysis_gold|jev_benchmark|review_translations|reviews)/);expect(sql).not.toContain('insert into public.analysis_jev_pilot_authorizations');expect(sql).toContain("configuration_id='v12_economy_1pass_v1'")})
})
