import {json,preflight} from './cors.ts'
import {canonicalJson} from './jev-exploratory-core.ts'
import {negativeHash} from './negative-validation-core.ts'
import {V13_BENCH_CONFIG,verifyV13,compareV13,type V13Run,type V13Prepared} from './jev-v13-core.ts'
export interface V13Configuration {id:string;config:typeof V13_BENCH_CONFIG;config_sha256:string;frozen_at:string}
export interface V13Repository {configuration:()=>Promise<V13Configuration>;get:()=>Promise<V13Run|null>;prepare:()=>Promise<V13Prepared>;configured:()=>boolean;start:(p:V13Prepared)=>Promise<string>;result:(id:string)=>Promise<Awaited<ReturnType<typeof compareV13>>|null>;progress:(id:string)=>Promise<{total:number;completed:number;failed:number}>;freshSources:()=>Promise<{id:string;name:string}[]>}
export function v13Handler(repository:(r:Request)=>Promise<V13Repository>){return async(request:Request)=>{const pre=preflight(request);if(pre)return pre;try{if(!['GET','POST'].includes(request.method))return json({error:'METHOD_NOT_ALLOWED'},405);const repo=await repository(request),configuration=await repo.configuration();if(configuration.config_sha256!==await negativeHash(canonicalJson(V13_BENCH_CONFIG))||canonicalJson(configuration.config)!==canonicalJson(V13_BENCH_CONFIG)||!configuration.frozen_at)throw new Error('V13_CONFIG_CHANGED');let run=await repo.get(),p:V13Prepared|null=null,error_code:string|null=null;if(run){await verifyV13(run);p=run.prepared}else try{p=await repo.prepare()}catch(e){error_code=e instanceof Error&&/^[A-Z0-9_]+$/.test(e.message)?e.message:'V13_SOURCE_READ_FAILED'}
 if(request.method==='POST'){const b=await request.json();if(b.action!=='start'||b.confirm_cost!==true||b.configuration_sha256!==configuration.config_sha256)throw new Error('V13_COST_CONFIRMATION_REQUIRED');if(!run){if(!p)throw new Error(error_code??'V13_NOT_READY');if(b.prepared_sha256!==p.prepared_sha256)throw new Error('V13_PREPARATION_CHANGED');if(!repo.configured())throw new Error('JEV_NOT_CONFIGURED');await repo.start(p);run=await repo.get();if(!run)throw new Error('V13_START_UNCONFIRMED')}}
 return json({configuration,ready:!!p,error_code,fresh_sources:await repo.freshSources(),run:run?{id:run.id,status:run.status,error_code:run.error_code,created_at:run.created_at}:null,preview:p?{reviews:p.items.length,source_reviews:p.total_source_reviews,source_kind:p.source_kind,source_id:p.source_id,reference_labels:p.reference.length,uncertain_labels:p.uncertain_labels,sealed_at:p.sealed_at??p.source_created_at,reference_model:[...new Set(p.reference.map(r=>r.model_source))].join(', '),reference_fingerprint:p.reference_sha256,dataset_fingerprint:p.dataset_sha256,config_sha256:p.config_sha256,prepared_sha256:p.prepared_sha256,expected_requests:p.expected_requests,new_v12_requests:p.source_kind==='fresh_blind_ai'?p.items.length*3:0,reused_v12_responses:p.baseline.length,estimated_input_tokens:p.estimated_input_tokens,estimated_cost_usd:p.estimated_cost_usd,rates:p.rates,translation_anomalies:p.audits.filter(a=>a.has_translation_concern).map(a=>({review_id:a.review_id,code:'translation_concern_in_ai_audit',note:a.rationale_fr})),audit_cases:p.audits.length,independent_for_v13:p.source_kind==='fresh_blind_ai'}:null,comparison:run?.status==='completed'?await repo.result(run.id):null,progress:run?await repo.progress(run.id):{total:0,completed:0,failed:0}})
 }catch(e){const code=e instanceof Error&&/^[A-Z0-9_]+$/.test(e.message)?e.message:'V13_REQUEST_FAILED';return json({error:code},code==='UNAUTHORIZED'?401:code==='FORBIDDEN'?403:/CHANGED|CONFIRM|JEV_NOT_CONFIGURED/.test(code)?409:500)}}}
