import {json,preflight} from './cors.ts'
import {V12_CONFIG,V12_QUESTION_SET} from './jev-v12-config.ts'
import {canonicalJson} from './jev-exploratory-core.ts'
import {negativeHash} from './negative-validation-core.ts'
import {verifyV12,type V12Run,type V12Prepared,compareV12} from './jev-v12-core.ts'
export interface V12Configuration {id:string;config:typeof V12_CONFIG;config_sha256:string;frozen_at:string}
export interface V12Repository {configuration:()=>Promise<V12Configuration>;prepare:()=>Promise<V12Prepared>;get:()=>Promise<V12Run|null>;start:(prepared:V12Prepared)=>Promise<string>;result:(id:string)=>Promise<Awaited<ReturnType<typeof compareV12>>|null>;progress:(id:string)=>Promise<{total:number;completed:number;failed:number}>;configured:()=>boolean}
export function v12Handler(repository:(r:Request)=>Promise<V12Repository>){return async(request:Request)=>{const pre=preflight(request);if(pre)return pre;try{if(!['GET','POST'].includes(request.method))return json({error:'METHOD_NOT_ALLOWED'},405);const repo=await repository(request),configuration=await repo.configuration();if(configuration.id!==V12_QUESTION_SET||configuration.config_sha256!==await negativeHash(canonicalJson(V12_CONFIG))||canonicalJson(configuration.config)!==canonicalJson(V12_CONFIG)||!configuration.frozen_at)throw new Error('V12_CONFIG_NOT_FROZEN');let run=await repo.get(),prepared:V12Prepared|null=null,error_code:string|null=null;if(run)await verifyV12(run);else try{prepared=await repo.prepare()}catch(e){error_code=e instanceof Error&&/^[A-Z0-9_]+$/.test(e.message)?e.message:'V12_SOURCE_READ_FAILED'}
 if(request.method==='POST'){const body=await request.json();if(body.action!=='start'||body.confirm_cost!==true||body.configuration_sha256!==configuration.config_sha256)throw new Error('V12_PAYMENT_CONFIRMATION_REQUIRED');if(!run){if(!prepared)throw new Error(error_code??'V12_NOT_READY');if(body.prepared_sha256!==prepared.prepared_sha256)throw new Error('V12_REFERENCE_CHANGED');if(!repo.configured())throw new Error('JEV_NOT_CONFIGURED');await repo.start(prepared);run=await repo.get();if(!run)throw new Error('V12_START_UNCONFIRMED')}}
 const p=run?.prepared??prepared;return json({configuration,ready:!!p,error_code,run:run?{id:run.id,status:run.status,error_code:run.error_code,created_at:run.created_at}:null,preview:p?{source_reviews:p.source_total_reviews,eligible_reviews:p.items.length,source_exclusions:p.source_exclusions,source_invalid_responses:p.source_invalid_responses,rechecks_total:p.rechecks_total,rechecks_applied:p.rechecks_applied,uncertain_labels:p.reference.filter(r=>r.choice==='uncertain').length,expected_requests:p.expected_requests,estimated_cost_usd:p.estimated_cost_usd,estimated_input_tokens:p.estimated_input_tokens,input_rate:p.input_rate,prepared_sha256:p.prepared_sha256,dataset_sha256:p.dataset_sha256}:null,comparison:run?.status==='completed'?await repo.result(run.id):null,progress:run?await repo.progress(run.id):{total:0,completed:0,failed:0}})
 }catch(e){const code=e instanceof Error&&/^[A-Z0-9_]+$/.test(e.message)?e.message:'V12_REQUEST_FAILED';return json({error:code},code==='UNAUTHORIZED'?401:code==='FORBIDDEN'?403:/CHANGED|FROZEN|JEV_NOT_CONFIGURED/.test(code)?409:code.startsWith('V12_')&&!code.endsWith('_FAILED')?400:500)}}}
