import type {SupabaseClient} from 'npm:@supabase/supabase-js@2.117.2'
import {createJevClient} from './jev.ts'
import {parseThemes} from './jev-themes.ts'
import {v12Payload} from './jev-v12-config.ts'
import {verifyV12,compareV12,type V12Run,type V12Task} from './jev-v12-core.ts'
const safe=(e:unknown)=>e instanceof Error&&/^[A-Z0-9_]+$/.test(e.message)?e.message:'V12_NETWORK_ERROR'
export async function processV12(admin:SupabaseClient,run:V12Run,worker:string){const start=Date.now(),rpc=async(name:string,args:Record<string,unknown>)=>{const {data,error}=await admin.rpc(name,args);if(error)throw new Error('V12_SAVE_FAILED');return data},finish=async(comparison:unknown=null,error:string|null=null)=>{if(await rpc('finish_experimental_v12_tick',{p_id:run.id,p_worker:worker,p_comparison:comparison,p_error:error})!==true)throw new Error('V12_LEASE_LOST')};try{await verifyV12(run);const key=Deno.env.get('TYPESAFE_API_KEY');if(!key?.trim())throw new Error('JEV_NOT_CONFIGURED');let processed=0
 while(Date.now()-start<70_000){const tasks=await rpc('claim_experimental_v12_tasks',{p_id:run.id,p_worker:worker}) as V12Task[];if(!tasks.length)break;if(tasks.length>8)throw new Error('V12_CONCURRENCY_INVALID');const outcomes=await Promise.allSettled(tasks.map(async t=>{const i=run.prepared.items.find(i=>i.review_id===t.review_id);if(!i)throw new Error('V12_TASK_INVALID');const begin=Date.now();let input=0,output=0,requests=0,model:string|null=null,response:unknown=null,errorCode:string|null=null,complete=true;const client=createJevClient(key,{maxAttempts:1,onUsage:(u,m)=>{input+=u.input_tokens;output+=u.output_tokens;model=m},onAttempt:()=>requests++});try{const result=await client.evaluatePayload(v12Payload('r'+i.position,i.analysis_text),parseThemes);response=result.decision;model=result.model}catch(e){errorCode=safe(e);if(['JEV_NETWORK_ERROR','JEV_INVALID_USAGE','JEV_INVALID_RESPONSE'].includes(errorCode))complete=false}if(await rpc('complete_experimental_v12_task',{p_id:run.id,p_worker:worker,p_task:t.id,p_values:{status:errorCode?'failed':'completed',response,served_model:model,input_tokens:input,output_tokens:output,request_count:requests,retry_count:0,duration_ms:Date.now()-begin,error_code:errorCode,usage_complete:complete}})!==true)throw new Error('V12_LEASE_LOST');processed++}));const rejected=outcomes.find(o=>o.status==='rejected');if(rejected?.status==='rejected')throw rejected.reason}
 if(processed){await finish();return {status:'running'}}const {data,error}=await admin.from('analysis_jev_v12_tasks').select('*').eq('run_id',run.id).order('id').limit(500);if(error||!data)throw new Error('V12_READ_FAILED');if(data.some(t=>['pending','running'].includes(t.status))){await finish();return {status:'running'}}await finish(await compareV12({...run,completed_at:new Date().toISOString()},data as V12Task[]));return {status:'completed'}
 }catch(e){const code=safe(e);if(code!=='V12_LEASE_LOST')try{await finish(null,code)}catch{/* Potentially billed responses are never re-enqueued. */}return {status:'error',error_code:code}}
}
