import {it,expect,vi,afterEach} from 'vitest'
import {syntheticPilot,pilotDecision} from '../../../tests/fixtures/jev-pilot'
import {pilotNarrativeContext,fallbackPilotProse} from './jev-pilot-narrative'
import {pilotStatistics} from './jev-pilot-core'
import {processPilot} from './jev-pilot-worker'
import type {PilotJob} from './jev-pilot-types'
const mocks=vi.hoisted(()=>({jev:vi.fn(),sol:vi.fn()}))
vi.mock('./jev.ts',async importOriginal=>({...await importOriginal<typeof import('./jev')>(),createJevClient:(_key:string,o:{maxAttempts:number;onAttempt:()=>void;onUsage:(u:{input_tokens:number;output_tokens:number},m:string)=>void})=>({evaluatePayload:async(p:unknown)=>{expect(o.maxAttempts).toBe(1);o.onAttempt();o.onUsage({input_tokens:8000,output_tokens:1000},'jev-1.13.0');return mocks.jev(p)}})}))
vi.mock('./reputation-themes.ts',()=>({structuredCall:mocks.sol}))
afterEach(()=>{vi.clearAllMocks();vi.unstubAllGlobals()})
async function harness(stage:'jev'|'sol',authorized=true){const f=await syntheticPilot(),statistics=pilotStatistics(f.snapshot.source.reviews,f.audit,20),input=pilotNarrativeContext(f.snapshot,statistics,'fr'),job={id:'job',organization_id:f.snapshot.organization_id,snapshot_id:f.snapshot.id,authorization_id:'auth',stage,language:stage==='jev'?'en':'fr',input_sha256:'sha',input_context:{narrative_input:input},status:'running'} as PilotJob,rpc=vi.fn(async(name:string,_args:Record<string,unknown>)=>({data:name==='claim_economy_pilot_tasks'?(rpc.mock.calls.filter(c=>c[0]===name).length===1?[{id:'task',review_id:f.snapshot.source.reviews[2].id,analysis_text_sha256:f.snapshot.source.reviews[2].analysis_text_sha256}]:[]):true,error:null})),from=vi.fn((table:string)=>{const q={select:()=>q,eq:()=>q,single:async()=>({data:table==='analysis_jev_pilot_snapshots'?f.snapshot:authorized?{organization_id:f.snapshot.organization_id,snapshot_id:f.snapshot.id,stage:job.stage,language:job.language,source_sha256:f.snapshot.source_sha256,config_sha256:f.snapshot.config_sha256}:null,error:null}),limit:async()=>({data:[{status:'completed'}],error:null})};return q});vi.stubGlobal('Deno',{env:{get:()=> 'fake-test-key'}});return {f,job,input,rpc,admin:{rpc,from} as unknown as Parameters<typeof processPilot>[0]}}
it('worker refuses missing authorization before any provider',async()=>{const h=await harness('jev',false);expect(await processPilot(h.admin,h.job,'worker')).toMatchObject({error_code:'PILOT_NEW_AUTHORIZATION_REQUIRED'});expect(mocks.jev).not.toHaveBeenCalled();expect(mocks.sol).not.toHaveBeenCalled()})
it('durable Jev task exactly one call, English alias/questions only; never Sol and no auto report',async()=>{const h=await harness('jev');mocks.jev.mockResolvedValue({decision:pilotDecision(),model:'jev-1.13.0'});expect(await processPilot(h.admin,h.job,'worker')).toEqual({status:'completed'});expect(mocks.jev).toHaveBeenCalledOnce();expect(Object.keys(mocks.jev.mock.calls[0][0].state)).toEqual(['review_alias','analysis_text']);expect(mocks.sol).not.toHaveBeenCalled();expect(h.rpc.mock.calls.at(-1)?.[1]).toMatchObject({p_result:{sol_calls:0,automatic_report_generation:false}})})
it('provider failure recorded once without retry',async()=>{const h=await harness('jev');mocks.jev.mockRejectedValue(new Error('INVALID_RESPONSE'));await processPilot(h.admin,h.job,'worker');expect(mocks.jev).toHaveBeenCalledOnce();expect(h.rpc.mock.calls.find(c=>c[0]==='complete_economy_pilot_task')?.[1]).toMatchObject({p_values:{request_count:1,status:'failed',usage_complete:false,error_code:'INVALID_RESPONSE'}})})
it('Sol is independent one aggregate call; bounded evidence, no per-review extraction',async()=>{const h=await harness('sol');mocks.sol.mockImplementation(async(_instructions,input,_schema,_limit,record)=>{await record({input_tokens:4000,output_tokens:1000});return {data:fallbackPilotProse(input)}});await processPilot(h.admin,h.job,'worker');expect(mocks.sol).toHaveBeenCalledOnce();expect(mocks.sol.mock.calls[0][1]).toEqual(h.input);expect(mocks.sol.mock.calls[0][5]).toBe('gpt-6.1-sol');expect(mocks.jev).not.toHaveBeenCalled();expect(h.rpc.mock.calls.at(-1)?.[1]).toMatchObject({p_result:{per_review_sol_extraction_calls:0},p_usage:{usage_complete:true}})})
it('Sol timeout yields deterministic fallback, unknown usage and zero retry',async()=>{const h=await harness('sol');mocks.sol.mockRejectedValue(new Error('TIMEOUT'));await processPilot(h.admin,h.job,'worker');expect(mocks.sol).toHaveBeenCalledOnce();expect(h.rpc.mock.calls.at(-1)?.[1]).toMatchObject({p_result:{origin:'deterministic_fallback_after_single_sol_attempt'},p_usage:{usage_complete:false}});expect(mocks.jev).not.toHaveBeenCalled()})
