import {json,preflight} from './cors.ts'
import {ECONOMY_CONFIG,COMPACT_CONFIG,instructionAudit} from './jev-economy-config.ts'
import {canonicalJson} from './jev-exploratory-core.ts'
import {negativeHash} from './negative-validation-core.ts'
import {estimateEconomyCosts,type EconomyRates} from './jev-economy-cost.ts'
import {planEconomy,type EconomyCache,type EconomyReview} from './jev-economy-cache.ts'
import type {EconomyComparison} from './jev-economy-score.ts'
export interface EconomyRepository {organization_id:string;establishment:{id:string;name:string};configurations:()=>Promise<{id:string;config:unknown;config_sha256:string}[]>;comparisons:()=>Promise<{comparison:EconomyComparison;rates:EconomyRates}[]>;reviews:()=>Promise<EconomyReview[]>;cache:()=>Promise<EconomyCache[]>}
export function economyHandler(repository:(r:Request)=>Promise<EconomyRepository>){return async(request:Request)=>{const pre=preflight(request);if(pre)return pre;try{if(request.method!=='GET')return json({error:request.method==='POST'?'ECONOMY_PAID_ENGINE_DISABLED':'METHOD_NOT_ALLOWED'},405);const repo=await repository(request),configurations=await repo.configurations();for(const expected of [ECONOMY_CONFIG,COMPACT_CONFIG]){const stored=configurations.find(c=>c.id===expected.id);if(!stored||stored.config_sha256!==await negativeHash(canonicalJson(expected))||canonicalJson(stored.config)!==canonicalJson(expected))throw new Error('ECONOMY_CONFIG_CHANGED')}const [rows,reviews,cache]=await Promise.all([repo.comparisons(),repo.reviews(),repo.cache()]);if(!rows.length)throw new Error('ECONOMY_OFFLINE_COMPARISON_REQUIRED');const comparisons=rows.map(r=>r.comparison),models=[...new Set(comparisons.flatMap(c=>c.variants.pass1.usage.served_models))].sort(),selected=new URL(request.url).searchParams.get('served_model')??models[0];if(!models.includes(selected))throw new Error('ECONOMY_SERVED_MODEL_REQUIRED');const plan=await planEconomy(repo.organization_id,reviews,cache,selected),{pending,...preview}=plan;void pending;return json({establishment:repo.establishment,configurations,comparisons,plan:preview,costs:estimateEconomyCosts(comparisons,rows.at(-1)!.rates,reviews.filter(r=>r.analysis_text.trim()&&r.analysis_language==='en').length,plan.planned_jev_calls),served_models:models,instruction_audit:instructionAudit(),paid_enabled:false,production_enabled:false,new_paid_calls:0})}catch(e){const code=e instanceof Error&&/^[A-Z0-9_]+$/.test(e.message)?e.message:'ECONOMY_READ_FAILED';return json({error:code},code==='UNAUTHORIZED'?401:code==='FORBIDDEN'?403:409)}}}
export type EconomyView={establishment:{id:string;name:string};configurations:{id:string;config:unknown;config_sha256:string}[];comparisons:EconomyComparison[];plan:Omit<Awaited<ReturnType<typeof planEconomy>>,'pending'>;costs:ReturnType<typeof estimateEconomyCosts>;served_models:string[];instruction_audit:ReturnType<typeof instructionAudit>;paid_enabled:false;production_enabled:false;new_paid_calls:0}
