import type {SupabaseClient} from 'npm:@supabase/supabase-js@2.117.2'
import {createJevClient} from './jev.ts'
import {parseThemes} from './jev-themes.ts'
import {v11Payload} from './jev-v11-calibration.ts'
import {EXPLORATORY_CONFIG,canonicalJson,exploratoryFingerprint,exploratoryPredictions,type ExploratoryRun,type ExploratoryItem} from './jev-exploratory-core.ts'
import type {NegativeTask} from './negative-validation-score.ts'
const safe=(e:unknown)=>e instanceof Error&&/^[A-Z0-9_]+$/.test(e.message)?e.message:'EXPLORATORY_NETWORK_ERROR'
export async function processJevExploration(admin:SupabaseClient,run:ExploratoryRun,worker:string){const begin=Date.now(),rpc=async(name:string,args:Record<string,unknown>)=>{const {data,error}=await admin.rpc(name,args);if(error)throw new Error('EXPLORATORY_SAVE_FAILED');return data},finish=async(items:unknown=null,error:string|null=null)=>{if(await rpc('finish_jev_exploratory_tick',{p_id:run.id,p_worker:worker,p_items:items,p_error:error})!==true)throw new Error('EXPLORATORY_LEASE_LOST')};try{
  const {data:rows,error}=await admin.from('analysis_jev_exploratory_items').select('*').eq('run_id',run.id).order('position').limit(1000);if(error||!rows)throw new Error('EXPLORATORY_READ_FAILED');const items=rows as ExploratoryItem[];if(await exploratoryFingerprint(items)!==run.dataset_sha256)throw new Error('EXPLORATORY_INTEGRITY_CHANGED');if(canonicalJson(run.config)!==canonicalJson(EXPLORATORY_CONFIG))throw new Error('EXPLORATORY_CONFIG_CHANGED');const key=Deno.env.get('TYPESAFE_API_KEY');if(!key?.trim())throw new Error('JEV_NOT_CONFIGURED');let processed=0
  while(Date.now()-begin<70_000){const tasks=await rpc('claim_jev_exploratory_tasks',{p_id:run.id,p_worker:worker}) as NegativeTask[];if(!tasks.length)break;if(tasks.length>8)throw new Error('EXPLORATORY_CONCURRENCY_INVALID');const outcomes=await Promise.allSettled(tasks.map(async task=>{const i=items.find(i=>i.review_id===task.review_id);if(!i)throw new Error('EXPLORATORY_SOURCE_INVALID');let input=0,output=0,requests=0,retries=0,model:string|null=null,response:unknown=null,code:string|null=null,complete=true;const start=Date.now(),client=createJevClient(key,{maxAttempts:1,onUsage:(u,m)=>{input+=u.input_tokens;output+=u.output_tokens;model=m},onAttempt:()=>requests++,onRetry:()=>retries++});try{const result=await client.evaluatePayload(v11Payload('themes','r'+i.position,i.analysis_text),parseThemes);response=result.decision;model=result.model}catch(e){code=safe(e);if(['JEV_NETWORK_ERROR','JEV_INVALID_USAGE','JEV_INVALID_RESPONSE'].includes(code))complete=false}if(await rpc('complete_jev_exploratory_task',{p_id:run.id,p_worker:worker,p_task:task.id,p_values:{status:code?'failed':'completed',response,served_model:model,input_tokens:input,output_tokens:output,request_count:requests,retry_count:retries,duration_ms:Date.now()-start,error_code:code,usage_complete:complete}})!==true)throw new Error('EXPLORATORY_LEASE_LOST');processed++}));const rejected=outcomes.find(o=>o.status==='rejected');if(rejected?.status==='rejected')throw rejected.reason}
  if(processed){await finish();return {status:'running'}}const {data:tasks,error:te}=await admin.from('analysis_jev_exploratory_tasks').select('*').eq('run_id',run.id).limit(1000);if(te||!tasks)throw new Error('EXPLORATORY_READ_FAILED');if(tasks.some(t=>['pending','running'].includes(t.status))){await finish();return {status:'running'}}const normalized=tasks.map(t=>({...t,model_version:'v11',experiment_id:run.id,review_alias:'',question_set_version:EXPLORATORY_CONFIG.question_set})) as NegativeTask[];await finish(items.map(i=>({review_id:i.review_id,v11:Object.keys(i.v11).length===25?i.v11:exploratoryPredictions(normalized,i.review_id,'v11')})));return {status:'completed'}
}catch(e){const code=safe(e);if(code!=='EXPLORATORY_LEASE_LOST')try{await finish(null,code)}catch{/* An ambiguous paid response is not re-enqueued. */}return {status:'error',error_code:code}}}
