import {json,preflight} from './cors.ts'
import {ECONOMY_CONFIG} from './jev-economy-config.ts'
import {canonicalJson} from './jev-exploratory-core.ts'
import {negativeHash} from './negative-validation-core.ts'
import {auditPilotCache,pilotStatistics,pilotCosts,pilotComparison,verifyPilotSnapshot,type PilotSnapshot} from './jev-pilot-core.ts'
import {pilotNarrativeContext,pilotNarrativeHash} from './jev-pilot-narrative.ts'
import type {EconomyCache} from './jev-economy-cache.ts'
import type {PilotJob,PilotAuthorization} from './jev-pilot-types.ts'
export type {PilotJob,PilotAuthorization,PilotView} from './jev-pilot-types.ts'
export interface PilotRepository {language:'fr'|'vi';configuration:()=>Promise<{config:unknown;config_sha256:string}>;snapshot:()=>Promise<PilotSnapshot|null>;prepare:()=>Promise<void>;cache:()=>Promise<(EconomyCache&{theme_results?:unknown;source_kind?:string})[]>;jobs:()=>Promise<PilotJob[]>;authorizations:()=>Promise<PilotAuthorization[]>;progress:()=>Promise<{total:number;completed:number;failed:number}>;start:(stage:'jev'|'sol',language:string,input_sha:string,context:Record<string,unknown>)=>Promise<void>}
export async function pilotPlan(s:PilotSnapshot,cache:Awaited<ReturnType<PilotRepository['cache']>>,language:'fr'|'vi'){await verifyPilotSnapshot(s);const audit=await auditPilotCache(s.source.reviews,cache,s.organization_id,s.establishment_id),statistics=pilotStatistics(s.source.reviews,audit,s.source.google_total_reviews),costs=pilotCosts(s.rates,audit.missing_review_ids.length,audit.blocked_review_ids.length),context=pilotNarrativeContext(s,statistics,language),sol_input_sha=await pilotNarrativeHash(context),ids=audit.missing_review_ids.filter(id=>!audit.blocked_review_ids.includes(id)).sort(),jev_input_sha=await negativeHash(canonicalJson({snapshot_sha256:s.source_sha256,review_ids:ids,configuration:s.config_sha256}));return {audit,statistics,costs,context,sol_input_sha,jev_input_sha,review_ids:ids}}
export function pilotHandler(repository:(r:Request)=>Promise<PilotRepository>){return async(request:Request)=>{const pre=preflight(request);if(pre)return pre;try{if(!['GET','POST'].includes(request.method))return json({error:'METHOD_NOT_ALLOWED'},405);const repo=await repository(request),cfg=await repo.configuration();if(cfg.config_sha256!==await negativeHash(canonicalJson(ECONOMY_CONFIG))||canonicalJson(cfg.config)!==canonicalJson(ECONOMY_CONFIG))throw new Error('PILOT_CONFIG_CHANGED');let snapshot=await repo.snapshot();const body=request.method==='POST'?await request.json():null;if(body?.action==='prepare_snapshot'){await repo.prepare();snapshot=await repo.snapshot()}if(!snapshot){if(body&&body.action!=='prepare_snapshot')throw new Error('PILOT_SNAPSHOT_REQUIRED');return json({snapshot:null,configuration_id:ECONOMY_CONFIG.id,new_paid_calls:0,production_enabled:false})}
 const p=await pilotPlan(snapshot,await repo.cache(),repo.language),auth=await repo.authorizations(),jobs=await repo.jobs(),jevAuth=auth.find(a=>a.stage==='jev'&&a.source_sha256===snapshot.source_sha256&&a.config_sha256===snapshot.config_sha256&&p.review_ids.every(id=>a.allowed_review_ids.includes(id))&&p.review_ids.length<=a.max_calls),solAuth=auth.find(a=>a.stage==='sol'&&a.language===repo.language&&a.input_sha256===p.sol_input_sha&&a.source_sha256===snapshot.source_sha256&&a.config_sha256===snapshot.config_sha256&&(p.statistics.coverage.missing_analyses===0||a.allow_partial_report));
 if(body&&body.action!=='prepare_snapshot'){if(body.confirm_cost!==true)throw new Error('PILOT_COST_CONFIRMATION_REQUIRED');if(body.source_sha256!==snapshot.source_sha256)throw new Error('PILOT_SNAPSHOT_CHANGED');if(body.action==='complete_jev'){if(!jevAuth)throw new Error('PILOT_NEW_AUTHORIZATION_REQUIRED');if(body.input_sha256!==p.jev_input_sha||!p.review_ids.length)throw new Error('PILOT_ANALYSIS_PLAN_CHANGED');await repo.start('jev','en',p.jev_input_sha,{review_ids:p.review_ids,expected_served_model:p.audit.served_models[0],estimated_cost_usd:p.costs.estimated_jev_cost_usd})}else if(body.action==='generate_sol'){if(!solAuth)throw new Error('PILOT_NEW_AUTHORIZATION_REQUIRED');if(body.input_sha256!==p.sol_input_sha||jobs.some(j=>j.stage==='jev'&&['queued','running'].includes(j.status)))throw new Error('PILOT_REPORT_SCOPE_CHANGED');await repo.start('sol',repo.language,p.sol_input_sha,{narrative_input:p.context,statistics:p.statistics,estimated_cost_usd:p.costs.estimated_sol_cost_usd})}else throw new Error('PILOT_ACTION_INVALID')}
 const currentJobs=await repo.jobs(),report=currentJobs.filter(j=>j.stage==='sol'&&j.language===repo.language&&j.status==='completed').sort((a,b)=>(b.completed_at??'').localeCompare(a.completed_at??''))[0]??null;return json({snapshot:{id:snapshot.id,name:snapshot.name,created_at:snapshot.created_at,source_sha256:snapshot.source_sha256,configuration_id:ECONOMY_CONFIG.id,config_sha256:snapshot.config_sha256},statistics:p.statistics,costs:p.costs,audit:{raw_completed_full_cache_rows:p.audit.raw_completed_full_cache_rows,reused_now:p.audit.used.length,rejected:p.audit.rejected,blocked:p.audit.blocked_review_ids,excluded_compact_or_other_rows:p.audit.excluded_other_configuration_rows,served_models:p.audit.served_models},initial_reused_reviews:(snapshot.preview_at_creation as {coverage:{analysed_reviews:number}}).coverage.analysed_reviews,unavailable_reviews:snapshot.source.reviews.filter(r=>!r.analysis_text).map(r=>({review_id:r.id,reason:r.original_text.trim()?'ENGLISH_UNAVAILABLE':'NO_REVIEW_TEXT'})),comparison:pilotComparison(snapshot.source,report?(report.input_context.statistics as typeof p.statistics):p.statistics),jobs:currentJobs,report,report_matches_current_analysis:!report||report.input_sha256===p.sol_input_sha,progress:await repo.progress(),plans:{jev_input_sha256:p.jev_input_sha,sol_input_sha256:p.sol_input_sha},can_complete_jev:!!jevAuth&&p.review_ids.length>0&&!currentJobs.some(j=>j.stage==='jev'),can_generate_sol:!!solAuth&&!currentJobs.some(j=>j.stage==='sol'&&j.language===repo.language&&j.input_sha256===p.sol_input_sha)&&!currentJobs.some(j=>j.stage==='jev'&&['queued','running'].includes(j.status)),authorization_required:{jev:!jevAuth,sol:!solAuth},new_paid_calls_in_this_http_request:0,production_enabled:false})
 }catch(e){const code=e instanceof Error&&/^[A-Z0-9_]+$/.test(e.message)?e.message:'PILOT_REQUEST_FAILED';return json({error:code},code==='UNAUTHORIZED'?401:code==='FORBIDDEN'?403:409)}}}
