import {ECONOMY_CONFIG,COMPACT_CONFIG} from './jev-economy-config.ts'
import {THEME_KEYS,THEME_CHOICES} from './jev-themes.ts'
import {canonicalJson} from './jev-exploratory-core.ts'
import {negativeHash as sha} from './negative-validation-core.ts'
import {economyIdentity,type EconomyIdentity,type EconomyCache} from './jev-economy-cache.ts'
import {economyScore,economyMetrics,economyPrediction,economyUsage,type EconomyTask,type EconomyLabel} from './jev-economy-score.ts'
import {validThemeDecision} from './jev-v12-core.ts'
export const COMPACT_EXPERIMENT='compact-paired-new-reviews-v1'
export const COMPACT_STRATA={low:17,four:11,five:4} as const
export type CompactBucket=keyof typeof COMPACT_STRATA
export type CompactVariant='A'|'B'
export const COMPACT_CONFIGS={A:ECONOMY_CONFIG,B:COMPACT_CONFIG} as const
export interface CompactCandidate {review_id:string;establishment_id:string;establishment_name:string;organization_id:string;overall_rating:number;original_text:string;original_language:string|null;english_text:string|null;english_source:string|null;translation_id:string|null}
export interface CompactItem extends CompactCandidate {set_id:string;position:number;selection_bucket:CompactBucket;selection_hash:string;original_text_sha256:string;text_id:string|null}
export interface CompactText {id:string;set_id:string;review_id:string;original_text_sha256:string;analysis_text:string;analysis_text_sha256:string;language:'en';source:string;model_source:string|null;provenance:Record<string,unknown>;created_at:string}
export interface CompactReference extends EconomyLabel {set_id:string;analysis_text_sha256:string;model_source:string;annotation_protocol:'blind_to_jev_predictions';reference_type:'ai_reference_not_human_gold'}
export interface CompactSeal {set_id:string;dataset_sha256:string;reference_sha256:string;configuration_a_sha256:string;configuration_b_sha256:string;sealed_at:string;uncertain_labels:number}
export interface CompactSet {id:string;organization_id:string;name:string;status:'draft'|'sealed';selection_method:string;selection_seed:string;candidate_stats:unknown;created_at:string;created_by:string}
export interface CompactTask extends EconomyTask {run_id:string;variant:CompactVariant;configuration_id:string;cache_id:string|null;reused:boolean;analysis_text_sha256:string}
export interface CompactRun {id:string;set_id:string;organization_id:string;status:'queued'|'running'|'completed'|'failed';created_by:string;created_at:string;started_at:string|null;completed_at:string|null;rates:{input:number;output:number};expected_served_model:string;estimated_cost_usd:number|null;cost_limit_usd:number|null;seal:CompactSeal;lease_owner:string|null;lease_until:string|null}
export const compactBucket=(rating:number):CompactBucket=>rating<=3?'low':rating===4?'four':'five'
export async function selectCompactCandidates(organization_id:string,candidates:CompactCandidate[],usedIds:string[]){const used=new Set(usedIds),eligible=candidates.filter(c=>c.organization_id===organization_id&&c.original_text.trim()&&Number.isInteger(c.overall_rating)&&c.overall_rating>=1&&c.overall_rating<=5&&!used.has(c.review_id)),unique=new Set(eligible.map(c=>c.review_id));if(unique.size!==eligible.length)throw new Error('COMPACT_DUPLICATE_CANDIDATE');const seed=organization_id+':'+COMPACT_EXPERIMENT,hashed=await Promise.all(eligible.map(async c=>({...c,selection_hash:await sha(seed+':'+c.review_id),selection_bucket:compactBucket(c.overall_rating)}))),selected=[];
 for(const bucket of Object.keys(COMPACT_STRATA) as CompactBucket[]){const group=hashed.filter(c=>c.selection_bucket===bucket);if(group.length<COMPACT_STRATA[bucket])throw new Error('COMPACT_INSUFFICIENT_'+bucket.toUpperCase());const establishments=[...new Set(group.map(c=>c.establishment_id))].sort(),ranked=group.map(c=>({...c,rank:group.filter(g=>g.establishment_id===c.establishment_id&&!!g.english_text?.trim()===!!c.english_text?.trim()&&(g.selection_hash<c.selection_hash||g.selection_hash===c.selection_hash&&g.review_id<c.review_id)).length})).sort((a,b)=>Number(!!b.english_text?.trim())-Number(!!a.english_text?.trim())||a.rank-b.rank||establishments.indexOf(a.establishment_id)-establishments.indexOf(b.establishment_id)||a.selection_hash.localeCompare(b.selection_hash));selected.push(...ranked.slice(0,COMPACT_STRATA[bucket]))}
 return {selection_seed:seed,selection_method:'english_availability_then_sha256_star_buckets_round_robin_establishments_v1',items:await Promise.all(selected.map(async(c,index)=>({...c,position:index+1,original_text_sha256:await sha(c.original_text)}))),candidate_stats:{total:eligible.length,english_ready:eligible.filter(c=>c.english_text?.trim()).length,buckets:Object.fromEntries(Object.keys(COMPACT_STRATA).map(k=>[k,{total:eligible.filter(c=>compactBucket(c.overall_rating)===k).length,english_ready:eligible.filter(c=>compactBucket(c.overall_rating)===k&&c.english_text?.trim()).length}])),establishments:eligible.reduce((a,c)=>{const v=a.find(v=>v.id===c.establishment_id);if(v){v.total++;if(c.english_text?.trim())v.english_ready++}else a.push({id:c.establishment_id,name:c.establishment_name,total:1,english_ready:c.english_text?.trim()?1:0});return a},[] as {id:string;name:string;total:number;english_ready:number}[])}}}
export async function compactIdentity(variant:CompactVariant,organization_id:string,establishment_id:string,review_id:string,text:string,served:string):Promise<EconomyIdentity>{const base=await economyIdentity(organization_id,establishment_id,review_id,text,served),config=COMPACT_CONFIGS[variant];return {...base,configuration_id:config.id,instruction_version:config.instruction_version,instruction_sha256:await sha(canonicalJson(config.questions)),threshold_version:config.threshold_version,threshold_sha256:await sha(canonicalJson(config.thresholds))}}
export function compactPayload(variant:CompactVariant,alias:string,analysis_text:string){if(!analysis_text.trim())throw new Error('COMPACT_ENGLISH_REQUIRED');return {model:COMPACT_CONFIGS[variant].requested_model,state:{review_alias:alias,analysis_text},questions:structuredClone(COMPACT_CONFIGS[variant].questions)}}
export async function compactFingerprints(items:CompactItem[],texts:CompactText[],references:CompactReference[]){const sorted=[...items].sort((a,b)=>a.position-b.position),dataset=[];for(const i of sorted){if(await sha(i.original_text)!==i.original_text_sha256)throw new Error('COMPACT_ORIGINAL_CHANGED');const t=texts.find(t=>t.id===i.text_id&&t.review_id===i.review_id&&t.set_id===i.set_id);if(!t||t.language!=='en'||!t.analysis_text.trim()||t.original_text_sha256!==i.original_text_sha256||await sha(t.analysis_text)!==t.analysis_text_sha256)throw new Error('COMPACT_ENGLISH_REQUIRED');dataset.push({review_id:i.review_id,establishment_id:i.establishment_id,position:i.position,original_text_sha256:i.original_text_sha256,analysis_text_sha256:t.analysis_text_sha256})}
 if(sorted.length!==32||new Set(sorted.map(i=>i.review_id)).size!==32||Object.keys(COMPACT_STRATA).some(k=>sorted.filter(i=>i.selection_bucket===k).length!==COMPACT_STRATA[k as CompactBucket]))throw new Error('COMPACT_DATASET_INVALID');const refs=references.map(r=>({set_id:r.set_id,review_id:r.review_id,theme_key:r.theme_key,choice:r.choice,analysis_text_sha256:r.analysis_text_sha256,model_source:r.model_source,annotation_protocol:r.annotation_protocol,reference_type:r.reference_type})).sort((a,b)=>a.review_id.localeCompare(b.review_id)||a.theme_key.localeCompare(b.theme_key));if(refs.length!==800||new Set(refs.map(r=>r.review_id+':'+r.theme_key)).size!==800||refs.some(r=>!THEME_KEYS.includes(r.theme_key)||![...THEME_CHOICES,'uncertain'].includes(r.choice)||!r.model_source.trim()||r.reference_type!=='ai_reference_not_human_gold'||r.annotation_protocol!=='blind_to_jev_predictions'||r.analysis_text_sha256!==texts.find(t=>t.id===items.find(i=>i.review_id===r.review_id)?.text_id)?.analysis_text_sha256))throw new Error('COMPACT_AI_REFERENCE_REQUIRED');return {dataset_sha256:await sha(canonicalJson(dataset)),reference_sha256:await sha(canonicalJson(refs)),configuration_a_sha256:await sha(canonicalJson(ECONOMY_CONFIG)),configuration_b_sha256:await sha(canonicalJson(COMPACT_CONFIG)),uncertain_labels:refs.filter(r=>r.choice==='uncertain').length}}
export async function verifyCompactSeal(items:CompactItem[],texts:CompactText[],refs:CompactReference[],seal:CompactSeal){const fp=await compactFingerprints(items,texts,refs);if(Object.entries(fp).some(([k,v])=>seal[k as keyof CompactSeal]!==v))throw new Error('COMPACT_SEAL_CHANGED');return fp}
export function compactCostPreview(measured:{input_tokens:number;output_tokens:number;reviews:number;input_rate:number;output_rate:number},cached:{A:number;B:number}={A:0,B:0}){if(!Number.isFinite(measured.reviews)||measured.reviews<=0||Object.values(measured).some(n=>!Number.isFinite(n)||n<0)||Object.values(cached).some(n=>!Number.isInteger(n)||n<0||n>32))throw new Error('COMPACT_COST_BASIS_INVALID');const full=(measured.input_tokens*measured.input_rate+measured.output_tokens*measured.output_rate)/1e6/measured.reviews;return {max_evaluations:64,planned_calls:64-cached.A-cached.B,cache_reused:cached,A:{new_calls:32-cached.A,measured_cost_per_review:full,estimate_usd:(32-cached.A)*full},B:{new_calls:32-cached.B,measured_cost_per_review:null,estimate_usd:cached.B===32?0:null},indicative_budget_if_B_costs_as_A_usd:(64-cached.A-cached.B)*full,combined_estimate_usd:cached.B===32?(32-cached.A)*full:null,compact_tokens_measured:false,character_reduction_is_not_token_savings:true,rates:{input:measured.input_rate,output:measured.output_rate},source:'measured historical complete V12 pass1 responses; B has no measured response',scenarios:[100,500,1000].map(n=>({reviews:n,A_usd:n*full,B_usd:null,savings_usd:null}))}}
export async function compareCompact(run:CompactRun,items:CompactItem[],texts:CompactText[],refs:CompactReference[],tasks:CompactTask[]){await verifyCompactSeal(items,texts,refs,run.seal);if(tasks.length!==64||new Set(tasks.map(t=>t.review_id+':'+t.variant)).size!==64||tasks.some(t=>t.repeat!==1||t.configuration_id!==COMPACT_CONFIGS[t.variant].id||t.analysis_text_sha256!==texts.find(x=>x.id===items.find(i=>i.review_id===t.review_id)?.text_id)?.analysis_text_sha256||t.request_count>1||t.retry_count>0))throw new Error('COMPACT_TASK_INTEGRITY');const ids=items.filter(i=>(['A','B'] as const).every(v=>tasks.some(t=>t.variant===v&&t.review_id===i.review_id&&t.status==='completed'&&validThemeDecision(t.response)))).map(i=>i.review_id),scores=Object.fromEntries((['A','B'] as const).map(v=>[v,economyScore(ids,refs,tasks.filter(t=>t.variant===v),'pass1')])) as Record<CompactVariant,ReturnType<typeof economyScore>>;
 const usage=(v:CompactVariant)=>{const own=tasks.filter(t=>t.variant===v),billed=own.filter(t=>!t.reused),u=economyUsage(billed);return {...u,reused:own.filter(t=>t.reused).length,cost_per_evaluated_review:u.cost_usd!==null&&billed.length?u.cost_usd/billed.length:null,served_models:[...new Set(own.flatMap(t=>t.served_model?[t.served_model]:[]))],scenarios:[100,500,1000].map(n=>({reviews:n,estimated_cost_usd:u.cost_usd!==null&&billed.length?n*u.cost_usd/billed.length:null}))}},a=usage('A'),b=usage('B'),savings=(x:number|null,y:number|null)=>x!==null&&x>0&&y!==null?1-y/x:null,strip=(v:CompactVariant)=>{const {perReview,...score}=scores[v];void perReview;return score},degraded=THEME_KEYS.flatMap(k=>(['negative','positive'] as const).flatMap(p=>{const x=scores.A.themes[k][p],y=scores.B.themes[k][p];return x.support>=3&&x.f1!==null&&y.f1!==null&&y.f1<x.f1-.03?[{theme_key:k,polarity:p,support:x.support,A_f1:x.f1,B_f1:y.f1,delta:y.f1-x.f1}]:[]}));
 const bootstrap=async(p:'negative'|'positive')=>{let state=parseInt((await sha(run.id+':'+p)).slice(0,8),16)||1;const values=[];for(let n=0;n<2000;n++){const x={tp:0,fp:0,fn:0,support:0},y={...x};for(let j=0;j<ids.length;j++){state^=state<<13;state^=state>>>17;state^=state<<5;const index=Math.floor((state>>>0)/4294967296*ids.length);for(const field of Object.keys(x) as (keyof typeof x)[]){x[field]+=scores.A.perReview[index][p][field];y[field]+=scores.B.perReview[index][p][field]}}const f=economyMetrics(x).f1,g=economyMetrics(y).f1;if(f!==null&&g!==null)values.push(g-f)}values.sort((x,y)=>x-y);const valid=values.length===2000&&scores.A.perReview.filter(r=>r[p].support>0).length>=3;return {resamples:2000,valid_resamples:values.length,delta:scores.A[p].f1===null||scores.B[p].f1===null?null:scores.B[p].f1!-scores.A[p].f1!,ci_95_low:valid?values[49]:null,ci_95_high:valid?values[1949]:null,method:'paired_review_bootstrap_B_minus_A'}};
 return {reference_type:'blind_AI_reference_not_human_gold',human_validated:false,production_enabled:false,coverage:{total:32,paired_reviews:ids.length,A:tasks.filter(t=>t.variant==='A'&&t.status==='completed'&&validThemeDecision(t.response)).length,B:tasks.filter(t=>t.variant==='B'&&t.status==='completed'&&validThemeDecision(t.response)).length},A:strip('A'),B:strip('B'),usage:{A:a,B:b},cost_savings:savings(a.cost_per_evaluated_review,b.cost_per_evaluated_review),input_token_savings:savings(a.input_tokens,b.input_tokens),output_token_savings:savings(a.output_tokens,b.output_tokens),degraded_themes:degraded,bootstrap:{negative:await bootstrap('negative'),positive:await bootstrap('positive')},models_changed:canonicalJson(a.served_models)!==canonicalJson(b.served_models)||a.served_models.length!==1||b.served_models.length!==1,failures:tasks.filter(t=>t.status!=='completed'||!validThemeDecision(t.response)).map(t=>({review_id:t.review_id,variant:t.variant,error_code:(t as CompactTask&{error_code?:string}).error_code??'INVALID_RESPONSE'})),reviews:items.map(i=>{const t=texts.find(t=>t.id===i.text_id)!;return {review_id:i.review_id,analysis_text:t.analysis_text,overall_rating:i.overall_rating,establishment_name:i.establishment_name,reasons:ids.includes(i.review_id)?THEME_KEYS.flatMap(k=>{const A=economyPrediction(tasks.filter(t=>t.variant==='A'),i.review_id,k,'pass1'),B=economyPrediction(tasks.filter(t=>t.variant==='B'),i.review_id,k,'pass1');return A.choice!==B.choice?[{theme_key:k,A,B}]:[]}):[{code:'incomplete_response'}]}}),elapsed_ms:run.started_at&&run.completed_at?Date.parse(run.completed_at)-Date.parse(run.started_at):null,warning:'New star-stratified reviews and AI references sealed before JEV. Not independent human Gold. One pass cannot measure repeat stability. No automatic recalibration.'}}
export type CompactComparison=Awaited<ReturnType<typeof compareCompact>>
export type CompactCache=EconomyCache
