import {describe,it,expect,vi} from 'vitest'
import {readFileSync} from 'node:fs'
import {V12_CONFIG,V12_THRESHOLDS,v12Payload,v12ReportedSymptoms} from './jev-v12-config'
import {V11_THRESHOLDS,v11Payload} from './jev-v11-calibration'
import {THEME_KEYS} from './jev-themes'
import {prepareV12,compareV12,verifyV12,validThemeDecision,V12_SOURCE_BENCHMARK} from './jev-v12-core'
import {v12Handler,type V12Repository} from './jev-v12-api'
import {canonicalJson} from './jev-exploratory-core'
import {negativeHash} from './negative-validation-core'
import {syntheticV12} from '../../../tests/fixtures/jev-v12'
const cases:[string,string,string,RegExp][]=[
 ['atmosphere','The vibe is lovely.','general ambience',/General ambience, mood, vibe/],['decor','The architecture and interior are beautiful.','architecture',/Architecture, interior, design/],['comfort','The room is hot and the seats are uncomfortable.','physical comfort',/Physical comfort: room temperature/],['atmosphere','Beautiful decor, uncomfortable chairs.','no polarity transfer',/Do not transfer a negative comfort/],
 ['wait_time','Service was very slow.','slowness only',/Slow service alone belongs to wait_time/],['attentiveness','Service was slow.','not attention by speed',/slow service alone is NOT evidence/],['coordination','Everything arrived quickly.','not organization by speed',/Slow or fast service alone does not prove/],['professionalism','We waited a long time.','not professionalism by speed',/Slow service alone does NOT establish/],['attentiveness','No waiter came to take care of us.','absence of server',/absent\/unavailable server/],['coordination','The staff mixed up tables and service was disorganized.','organization errors',/organizational errors/],['professionalism','Excellent service and useful assistance.','V11 execution retained',/excellent\/capable service/],['friendly_staff','The waitress was polite and friendly.','politeness',/Friendliness, kindness, warmth and politeness/],['communication','The waiter explained the menu clearly.','interaction',/described or evaluated interaction/],['communication','They speak Russian.','language alone',/They speak Russian alone is absent/],
 ['food_quality','The food tasted delicious.','dish quality',/Taste\/flavor or quality of food dishes/],['drinks','Excellent coffee, terrible food.','drinks separate',/evaluated independently of food dishes/],['food_quality','Excellent drinks but bad food.','not both across categories',/NOT food_quality both/],['cooking','The meat was overcooked.','explicit cooking',/Explicit cooking\/preparation/],['cooking','The meat was chewy and tough.','texture is not proof',/texture alone does not necessarily prove/],['freshness','The ingredients were fresh.','freshness evidence',/text explicitly supports fresh\/stale\/spoiled/],['freshness','The food tasted bad.','no freshness inference',/Bad taste, texture or symptoms alone/],['temperature','The dish was served cold.','serving temperature',/as SERVED/],['temperature','My coffee cooled down while waiting for the food.','cooling during wait',/cooling down while the customer waits does NOT/],['portions','The portion was too small.','quantity',/Quantity\/size of a dish/],['order_accuracy','They forgot the side dish I ordered.','forgotten element',/ordered item\/component forgotten/],['variety','Several advertised options were unavailable.','unavailable choices',/Several advertised options being unavailable/],['consistency','It was good last visit but bad today.','real variation',/REAL variation/],['consistency','It is always bad here.','always bad is not variation',/always bad do NOT alone/],
 ['price_level','The prices are high.','price level only',/not automatically billing or value/],['billing','They added a surcharge to my bill.','surcharge only',/Bill errors, extra charges, fees or surcharges/],['value','The meal was not worth the money.','explicit value',/Explicitly evaluated value for money/],['value','It is expensive.','no tripled price themes',/Expensive alone does not establish value/],['food_quality','5 stars, beautiful place.','no rating or generic praise',/Never derive a theme or sentiment from Google ratings/],['cleanliness','I got sick after the meal.','no inferred food safety causality',/Symptoms alone do not establish food_quality or cleanliness/],['food_quality','Good drinks and bad food.','both same theme only',/THIS SAME theme/],
]
describe('V12 semantic instruction contracts (offline; not model behavior validation)',()=>{
 it.each(cases)('%s · %s · %s',(theme,text,_label,rule)=>{const p=v12Payload('r',text);expect((p.questions[theme] as {instructions:string}).instructions).toMatch(rule);expect(p.state).toEqual({review_alias:'r',analysis_text:text});expect(Object.keys(p.questions)).toHaveLength(25)})
 it('keeps exactly the same 25 themes, four choices and independent V11 threshold values',()=>{const before=canonicalJson(v11Payload('themes','r','English'));v12Payload('r','English');expect(canonicalJson(v11Payload('themes','r','English'))).toBe(before);expect(V12_THRESHOLDS).toEqual(V11_THRESHOLDS);expect(V12_THRESHOLDS).not.toBe(V11_THRESHOLDS);for(const k of THEME_KEYS){expect(Object.keys((v12Payload('r','English').questions[k] as {criteria:object}).criteria)).toEqual(['absent','positive','negative','both']);expect(V12_THRESHOLDS[k]).not.toBe(V11_THRESHOLDS[k])}expect(V12_CONFIG).toMatchObject({requested_model:'jev-latest',repeat_count:3,concurrency:8,production_enabled:false,experimental_only:true})})
 it('diagnostic symptom cues never create a theme or confirm causality',()=>{expect(v12ReportedSymptoms('I felt sick and had diarrhea after the meal.')).toMatchObject({causality_confirmed:false,creates_theme:false,reported_only:true});expect(Object.keys(v12Payload('r','I felt sick after dinner.').questions)).toEqual(THEME_KEYS);expect(v12ReportedSymptoms('Delicious food.')).toBeNull()})
})
describe('independent paired V12 benchmark',()=>{
 it('accepts raw table rows with bookkeeping columns but excludes those columns from the immutable reference hash',async()=>{const f=await syntheticV12(),rows=f.initial.map(r=>({...r,experiment_id:'original-experiment',notes_fr:'Technical notes',needs_human_review:true})),p=await prepareV12(f.source,f.tasks,rows,f.rechecks,[],.042);expect(p.prepared_sha256).toBe(f.prepared.prepared_sha256);expect(p.items).toHaveLength(30);expect(p.initial_snapshot.every(r=>Object.keys(r).length===6)).toBe(true)})
 it('still rejects real IA-label, provenance-model or text-hash changes after projecting raw database rows',async()=>{const f=await syntheticV12();for(const field of ['analysis_text_sha256','model_source'] as const){const rows=f.initial.map(r=>({...r,experiment_id:'original-experiment'}));rows[0][field]='changed';await expect(prepareV12(f.source,f.tasks,rows,f.rechecks,[],.042)).rejects.toThrow('V12_INITIAL_REFERENCE_CHANGED')}})
 it('retains valid rounded source probabilities despite JSONB key order and still rejects invalid distributions',async()=>{const f=await syntheticV12(),d=structuredClone(f.v12Tasks[0].response!);d.themes.portions.probabilities={both:.06,absent:.41,negative:.18,positive:.34};expect(validThemeDecision(d)).toBe(true);d.themes.portions.probabilities.absent=.1;expect(validThemeDecision(d)).toBe(false)})
 it('selects exactly 30 complete common reviews, reuses 90 V11 responses and plans only 90 V12 requests',async()=>{const f=await syntheticV12();expect(f.prepared.items).toHaveLength(30);expect(f.prepared.source_total_reviews).toBe(32);expect(f.prepared.source_exclusions).toHaveLength(2);expect(f.prepared.source_invalid_responses).toBe(2);expect(f.prepared.baseline).toHaveLength(90);expect(f.prepared.expected_requests).toBe(90);expect(f.prepared.baseline.every(t=>t.model_version==='v11')).toBe(true)})
 it('preserves original IA labels and keeps corrected/uncertain labels in a separate layer',async()=>{const f=await syntheticV12();expect(f.initial.find(r=>r.review_id===f.rechecks[0].review_id)!.theme_choices.professionalism).toBe('absent');expect(f.prepared.reference.find(r=>r.review_id===f.rechecks[0].review_id&&r.theme_key==='professionalism')).toMatchObject({initial_choice:'absent',choice:'positive',origin:'chatgpt_ai_recheck'});expect(f.prepared.reference.some(r=>r.choice==='uncertain')).toBe(true)})
 it('blocks any holdout intersection, changed base reference or bad recheck',async()=>{const f=await syntheticV12();await expect(prepareV12(f.source,f.tasks,f.initial,f.rechecks,[f.source.dataset_snapshot[0].review_id],.042)).rejects.toThrow('HOLDOUT');const initial=structuredClone(f.initial);initial[0].theme_choices.food_quality='negative';await expect(prepareV12(f.source,f.tasks,initial,f.rechecks,[],.042)).rejects.toThrow('REFERENCE_CHANGED');await expect(prepareV12(f.source,f.tasks,f.initial,[{...f.rechecks[0],initial_ai_choice:'negative'}],[],.042)).rejects.toThrow('RECHECK_INVALID')})
 it('keeps frozen English text exactly and never applies live translation overrides',async()=>{const f=await syntheticV12();for(const i of f.prepared.items)expect(i.analysis_text).toBe(f.source.dataset_snapshot.find(r=>r.review_id===i.review_id)!.analysis_text);expect(readFileSync('supabase/functions/_shared/jev-v12-core.ts','utf8')).not.toMatch(/freshEnglishAnalysisInputs|analysis_review_english_translation_overrides|original_text/)})
 it('calculates positive/negative metrics, all 25 themes and four axes, excluding uncertain',async()=>{const f=await syntheticV12(),c=await compareV12(f.run,f.v12Tasks);expect(c.evaluable_reviews).toBe(30);expect(c.v11.positive.fn).toBe(1);expect(c.v12.positive.tp).toBe(1);expect(c.v12.negative.support).toBe(59);expect(c.v12.negative.f1).toBe(1);expect(c.v12.uncertain_labels).toBe(1);expect(Object.keys(c.v12.themes)).toHaveLength(25);expect(Object.keys(c.v12.axes)).toHaveLength(4);expect(c.v12.axes.price.negative.f1).toBeNull();expect(c.human_validated).toBe(false);expect(c.usage.new_paid_v11_requests).toBe(0);expect(c.model_version_confounded).toBe(true)})
 it('bootstrap is paired at review level, deterministic and 2000 resamples',async()=>{const f=await syntheticV12(),a=await compareV12(f.run,f.v12Tasks),b=await compareV12(f.run,f.v12Tasks);expect(a.bootstrap).toEqual(b.bootstrap);expect(a.bootstrap.overall).toMatchObject({method:'paired_review_bootstrap',resamples:2000,independent_validation:false});expect(a.bootstrap.negative.ci_95_low).toBe(0)})
 it('a failed V12 repetition is unavailable, not absent, and prevents a complete CI',async()=>{const f=await syntheticV12();f.v12Tasks[0].status='failed';f.v12Tasks[0].error_code='JEV_INVALID_RESPONSE';const c=await compareV12(f.run,f.v12Tasks);expect(c.evaluable_reviews).toBe(29);expect(c.complete).toBe(false);expect(c.bootstrap.overall.ci_95_low).toBeNull();expect(c.v12_failures).toHaveLength(1);expect(c.reviews[0].v12).toBeNull()})
 it('frozen preparation hash guards stop tampering before paid work',async()=>{const f=await syntheticV12(),r=structuredClone(f.run);r.prepared.items[0].analysis_text+=' changed';await expect(verifyV12(r)).rejects.toThrow('INTEGRITY_CHANGED')})
 it('GET never creates a benchmark; paid POST needs explicit cost/config/reference confirmation',async()=>{const f=await syntheticV12(),start=vi.fn(),repo:V12Repository={configuration:async()=>({id:V12_CONFIG.question_set,config:V12_CONFIG,config_sha256:await negativeHash(canonicalJson(V12_CONFIG)),frozen_at:'2026-10-09'}),prepare:async()=>f.prepared,get:async()=>null,start,result:async()=>null,progress:async()=>({total:0,completed:0,failed:0}),configured:()=>true},handler=v12Handler(async()=>repo);expect((await handler(new Request('https://test'))).status).toBe(200);expect(start).not.toHaveBeenCalled();expect((await handler(new Request('https://test',{method:'POST',body:JSON.stringify({action:'start'})}))).status).toBe(400);expect(start).not.toHaveBeenCalled()})
 it('has no Sol/Apify/report creation call graph and does not alter V11 source',()=>{for(const file of ['jev-v12-worker.ts','jev-v12-api.ts'])expect(readFileSync('supabase/functions/_shared/'+file,'utf8')).not.toMatch(/OPENAI|APIFY|writeV9Narrative|enqueue_historical_report|extractConsultantBatch/);expect(readFileSync('supabase/functions/_shared/jev-v12-worker.ts','utf8')).toContain('maxAttempts:1');expect(V12_SOURCE_BENCHMARK).toBe('adfa4fdf-a8c7-4976-916f-339ebabb8d62')})
})
