import {describe,it,expect,vi,afterEach} from 'vitest'
import {readFileSync,readdirSync} from 'node:fs'
import {V13_CONFIG,V13_THRESHOLDS,V13_BOUNDARIES,v13Payload,v13ReportedSafety} from './jev-v13-config'
import {V12_CONFIG,v12Payload} from './jev-v12-config'
import {THEME_KEYS} from './jev-themes'
import {V13_CASES} from '../../../tests/fixtures/jev-v13-cases'
import {syntheticV13} from '../../../tests/fixtures/jev-v13'
import {prepareV13,compareV13,verifyV13,freshV13Source,V13_BENCH_CONFIG} from './jev-v13-core'
import {v13Handler} from './jev-v13-api'
import {processV13} from './jev-v13-worker'
import {canonicalJson} from './jev-exploratory-core'
import type {SupabaseClient} from '@supabase/supabase-js'
const provider=vi.hoisted(()=>({evaluate:vi.fn(),clients:vi.fn()}))
vi.mock('./jev.ts',async original=>({...await original() as object,createJevClient:(_key:unknown,options:unknown)=>{provider.clients(options);return {evaluatePayload:provider.evaluate}}}))
afterEach(()=>{vi.unstubAllGlobals();vi.clearAllMocks()})
describe('V13 semantic instruction contracts, not real model quality tests',()=>{
 it('clones immutable V12 instructions/thresholds and preserves exactly 25 four-choice questions',()=>{const original=canonicalJson(V12_CONFIG);expect(V13_THRESHOLDS).toEqual(V12_CONFIG.thresholds);expect(V13_THRESHOLDS).not.toBe(V12_CONFIG.thresholds);expect(Object.keys(V13_CONFIG.questions)).toEqual(THEME_KEYS);for(const k of THEME_KEYS){expect(Object.keys((V13_CONFIG.questions[k] as {criteria:object}).criteria)).toEqual(['absent','positive','negative','both']);if(!(k in V13_BOUNDARIES))expect(V13_CONFIG.questions[k]).toEqual(V12_CONFIG.questions[k])}expect(Object.isFrozen(V13_CONFIG.questions.cooking)).toBe(true);expect(canonicalJson(V12_CONFIG)).toBe(original);expect(V13_CONFIG.repeat_count).toBe(3);expect(V13_CONFIG.concurrency).toBe(8)})
 it.each(V13_CASES)('short synthetic audit case $id gets the matching frozen theme question, not a real provider prediction',c=>{const payload=v13Payload('case_'+c.id,c.text);expect(payload.questions[c.theme]).toEqual(V13_CONFIG.questions[c.theme]);expect(canonicalJson(payload)).toContain(c.text);expect(Object.keys(payload.questions)).toHaveLength(25);expect(provider.clients).not.toHaveBeenCalled()})
 it('expands preparation to seasoning/recipe defects without moving generic flavor, texture or freshness',()=>{const text=String((V13_CONFIG.questions.cooking as {instructions:string}).instructions);for(const marker of ['excessive salt','excessive sugar','excessive spices','insufficient seasoning','unbalanced','ingredient assembly','baking soda','overcooked','undercooked','not tasty alone','tough texture alone','freshness','bad drink'])expect(text).toContain(marker)})
 it('retains hygiene and pest reports while forbidding medical causality or a 26th theme',()=>{const text=String((V13_CONFIG.questions.cleanliness as {instructions:string}).instructions);expect(text).toContain('server touching served food');expect(text).toContain('pests in the establishment');expect(text).toContain('Do NOT infer');expect(v13ReportedSafety('Mosquitoes were reported; later a dengue diagnosis.')).toMatchObject({causality_confirmed:false,creates_theme:false,reported_only:true});expect(Object.keys(v13Payload('r','I became ill.').questions)).toHaveLength(25)})
 it('distinguishes unavailability, missing order, care/organization, distance, price/value/billing and same-theme both',()=>{expect(V13_BOUNDARIES.variety).toContain('BEFORE an order');expect(V13_BOUNDARIES.attentiveness).toContain('forgotten/wrong order alone');expect(V13_BOUNDARIES.attentiveness).toContain('bad staff attitude alone');expect(V13_BOUNDARIES.location).toContain('without geographic evidence');expect(V13_BOUNDARIES.price_level).toContain('belongs to value');expect(V13_BOUNDARIES.value).toContain('quality of service');expect(V13_BOUNDARIES.consistency).toContain('always bad');expect(V13_BOUNDARIES.atmosphere).toContain('caused by service');expect(String((V13_CONFIG.questions.food_quality as {instructions:string}).instructions)).toContain('THIS SAME theme');expect(V13_CONFIG.questions.billing).toEqual(V12_CONFIG.questions.billing)})
 it('sends no original text, rating, previous findings or AI references; V12 payload stays exact',()=>{const p=v13Payload('r','English only');expect(p.model).toBe('jev-latest');for(const k of ['original_text','rating','review_context','reference','v12','food_rating'])expect(Object.keys(p)).not.toContain(k);expect(Object.keys(p)).toEqual(Object.keys(v12Payload('r','English only')));expect(canonicalJson(V13_CONFIG.questions)).not.toContain('e45be953');expect(canonicalJson(V13_CONFIG.questions)).not.toContain('analysis_jev_independent_ai_error_audits')})
})
describe('V13 replay and future separation',()=>{
 it.each(['first','second'] as const)('prepares %s source with only V13 paid tasks and preserves original AI labels',async kind=>{const f=await syntheticV13(kind),before=structuredClone(f.source.reference),p=await prepareV13(f.source,{input:.042,output:0});expect(p.items).toHaveLength(kind==='first'?30:31);expect(p.expected_requests).toBe((kind==='first'?30:31)*3);expect(p.baseline).toHaveLength(p.items.length*3);expect(p.blind_to_predictions).toBe(false);expect(p.reference).toEqual([...before].sort((a,b)=>a.review_id.localeCompare(b.review_id)||a.theme_key.localeCompare(b.theme_key)));expect(provider.clients).not.toHaveBeenCalled()})
 it('keeps 19 post-prediction decisions diagnostic, including 2 ambiguous and 2 reference corrections',async()=>{const f=await syntheticV13('second'),before=structuredClone(f.prepared.reference),c=await compareV13(f.run,f.tasks);expect(c.audit_summary).toMatchObject({total:19,probable_v12_errors:15,reference_corrections:2,ambiguous_excluded:2,diagnostic_only:true,primary_reference_unchanged:true});expect(f.prepared.reference).toEqual(before);expect(c.independent_for_v13).toBe(false);expect(c.new_paid_v12_requests).toBe(0);expect(c.reference_type).toContain('not_independent')})
 it('requires complete compatible V12 baselines; no silent paid V12 fallback',async()=>{const f=await syntheticV13();f.source.baseline[0].status='failed';await expect(prepareV13(f.source,{input:.042,output:0})).rejects.toThrow('V13_BASELINE_INCOMPATIBLE')})
 it('detects text, reference or prepared-run tampering',async()=>{const f=await syntheticV13();f.run.prepared.items[0].analysis_text+='changed';await expect(verifyV13(f.run)).rejects.toThrow(/V13_/);expect(provider.clients).not.toHaveBeenCalled()})
 it('returns paired polarity/axis/theme metrics, costs, served models, invalid rate and deterministic bootstrap',async()=>{const f=await syntheticV13(),a=await compareV13(f.run,f.tasks),b=await compareV13(f.run,f.tasks);expect(a.bootstrap).toEqual(b.bootstrap);expect(a.bootstrap.negative.resamples).toBe(2000);expect(a.usage.v12.reused).toBe(true);expect(a.new_paid_v12_requests).toBe(0);expect(a.total_estimated_cost_usd).toBeCloseTo(f.tasks.reduce((n,t)=>n+t.cost_usd,0));expect(Object.keys(a.v13.themes)).toHaveLength(25);expect(Object.keys(a.v13.axes)).toHaveLength(4);expect(a.invalid_response_rate).toBe(0);expect(a.human_validated).toBe(false)})
 it('excludes incomplete responses from paired scoring and withholds complete bootstrap bounds',async()=>{const f=await syntheticV13();f.tasks[0].response=null;const c=await compareV13(f.run,f.tasks);expect(c.coverage.common).toBe(29);expect(c.bootstrap.overall.ci_95_low).toBeNull();expect(c.failures).toHaveLength(1);expect(c.invalid_response_rate).toBeGreaterThan(0)})
 it('future sealed data supports paired V12/V13 only after configuration freeze and before predictions',async()=>{const f=await syntheticV13('fresh');expect(f.prepared.expected_requests).toBe(192);expect(f.prepared.baseline).toHaveLength(0);expect(f.prepared.audits).toHaveLength(0);const c=await compareV13(f.run,f.tasks);expect(c.independent_for_v13).toBe(true);expect(c.human_validated).toBe(false);expect(c.new_paid_v12_requests).toBe(96);expect(c.audit_summary.total).toBe(0)})
 it.each(['used','unsealed','before-config','tampered','artisan'])('blocks fresh input %s anomaly',async kind=>{const f=await syntheticV13('fresh'),i=f.freshInput!;if(kind==='unsealed')i.blind_to_predictions=false;if(kind==='before-config')i.sealed_at='2026-10-07';if(kind==='tampered')i.reference[0].choice='uncertain';if(kind==='artisan')i.items[0].establishment_id='252a8dca-14c7-4f09-bd1f-7b2c40ae97aa';await expect(freshV13Source(i,kind==='used'?[i.items[0].review_id]:[],'2026-10-08')).rejects.toThrow(/V13_/);expect(provider.clients).not.toHaveBeenCalled()})
})
describe('V13 manual API and worker',()=>{
 async function setup(){const f=await syntheticV13(),repo={configuration:async()=>({id:V13_CONFIG.question_set,config:V13_BENCH_CONFIG,config_sha256:f.prepared.config_sha256,frozen_at:'2026-10-10'}),get:vi.fn().mockResolvedValue(null),prepare:async()=>f.prepared,configured:()=>true,start:vi.fn(),result:vi.fn(),freshSources:async()=>[],progress:async()=>({total:90,completed:0,failed:0})};return {f,repo,handler:v13Handler(async()=>repo)}}
 it('GET is read only, exposes no predictions or labels, and never starts a benchmark',async()=>{const s=await setup(),d=await(await s.handler(new Request('https://fixture'))).json();expect(d.ready).toBe(true);expect(d.preview.new_v12_requests).toBe(0);expect(d.comparison).toBeNull();expect(s.repo.start).not.toHaveBeenCalled();expect(JSON.stringify(d)).not.toContain('theme_choices')})
 it('requires explicit cost and current configuration/preparation fingerprints',async()=>{const s=await setup();const r=await s.handler(new Request('https://fixture',{method:'POST',body:JSON.stringify({action:'start',confirm_cost:false})}));expect(r.status).toBe(409);expect(s.repo.start).not.toHaveBeenCalled()})
 it('reuses queued jobs after ambiguous/double launch without paying again',async()=>{const s=await setup();s.repo.get.mockResolvedValue({...s.f.run,status:'queued'});const r=await s.handler(new Request('https://fixture',{method:'POST',body:JSON.stringify({action:'start',confirm_cost:true,configuration_sha256:s.f.prepared.config_sha256})}));expect(r.status).toBe(200);expect(s.repo.start).not.toHaveBeenCalled();expect(s.repo.result).not.toHaveBeenCalled()})
 it('processes at most 8 V13 requests with one attempt each; never re-extracts V12 on development',async()=>{const f=await syntheticV13();let n=0;provider.evaluate.mockRejectedValue(new Error('JEV_NETWORK_ERROR'));const rpc=vi.fn(async(name:string)=>({data:name==='claim_experimental_v13_tasks'?n++===0?f.tasks.slice(0,8):[]:true,error:null})),query={select:()=>query,eq:()=>query,order:()=>query,limit:async()=>({data:[{status:'pending'}],error:null})};vi.stubGlobal('Deno',{env:{get:()=> 'fake'}});await processV13({rpc,from:()=>query} as unknown as SupabaseClient,f.run,'worker');expect(provider.evaluate).toHaveBeenCalledTimes(8);expect(provider.clients.mock.calls.every(([o])=>o.maxAttempts===1)).toBe(true);expect(provider.evaluate.mock.calls.every(([p])=>p.questions.cooking.instructions===V13_CONFIG.questions.cooking.instructions)).toBe(true)})
 it('finalizes saved tasks without any provider request',async()=>{const f=await syntheticV13(),rpc=vi.fn(async(name:string)=>({data:name==='claim_experimental_v13_tasks'?[]:true,error:null})),query={select:()=>query,eq:()=>query,order:()=>query,limit:async()=>({data:f.tasks,error:null})};vi.stubGlobal('Deno',{env:{get:()=> 'fake'}});const result=await processV13({rpc,from:()=>query} as unknown as SupabaseClient,f.run,'worker');expect(result.status).toBe('completed');expect(provider.clients).not.toHaveBeenCalled()})
 it('schema writes only new tables, has RLS, no auto retry, and no real future input is seeded',()=>{const name=readdirSync('supabase/migrations').find(n=>n.endsWith('_experimental_jev_v13_targeted_recall.sql'))!,sql=readFileSync('supabase/migrations/'+name,'utf8');for(const table of ['analysis_jev_v12_runs','analysis_jev_independent_runs','analysis_jev_independent_ai_error_audits','analysis_v11_independent_holdout_ai_references','analysis_v11_independent_holdout_ai_seals','reviews','review_translations'])expect(sql).not.toMatch(new RegExp('(?:insert into|update|delete from)\\s+public\\.'+table+'\\b','i'));expect(sql).not.toContain('insert into public.analysis_jev_v13_sealed_inputs');expect(sql).toContain('check(retry_count=0)');expect(sql).toContain('unique(source_kind,source_id,configuration_id)');expect(sql).toContain('limit 8');expect(sql).toContain("e.organization_id=input.organization_id");expect(sql).toContain("JEV_RESPONSE_UNCONFIRMED")})
})
