import {describe,it,expect,vi,afterEach} from 'vitest'
import {syntheticCompact,syntheticCompactTasks} from '../../../tests/fixtures/jev-compact'
import {processCompact} from './jev-compact-worker'
import type {CompactTask} from './jev-compact-core'
import type {SupabaseClient} from 'npm:@supabase/supabase-js@2.117.2'
const client=vi.hoisted(()=>vi.fn());vi.mock('./jev',async importOriginal=>({...await importOriginal<typeof import('./jev')>(),createJevClient:client}));
afterEach(()=>{vi.clearAllMocks();vi.unstubAllGlobals()})
async function harness(mode='ok'){const f=await syntheticCompact('done'),run={...f.run!,status:'running' as const,lease_owner:'worker',lease_until:'future'},all=syntheticCompactTasks(f).map(t=>({...t,status:'pending'})),claimed:number[]=[];let active=0,max=0;client.mockImplementation((_key,options)=>({evaluatePayload:async(payload:unknown)=>{active++;max=Math.max(max,active);options.onAttempt({duration_ms:1,status:200,model:'jev-fixed'});await Promise.resolve();active--;if(mode==='network')throw new Error('JEV_NETWORK_ERROR');options.onUsage({input_tokens:8000,output_tokens:1000},'jev-fixed');const task=all.find(t=>t.status==='running')!;expect(Object.keys((payload as {state:object}).state)).toEqual(['review_alias','analysis_text']);return {decision:task.response,model:'jev-fixed'}}}));const rpc=vi.fn(async(name,args)=>{if(name==='claim_compact_tasks'){const batch=all.filter(t=>t.status==='pending').slice(0,8);batch.forEach(t=>t.status='running');claimed.push(batch.length);return {data:batch,error:null}}if(name==='complete_compact_task'){Object.assign(all.find(t=>t.id===args.p_task)!,args.p_values);return {data:true,error:null}}return {data:true,error:null}}),admin={rpc,from:(table:string)=>({select(){return this},eq(){return this},limit:async()=>({data:table.endsWith('items')?f.items:table.endsWith('texts')?f.texts:table.endsWith('ai_references')?f.references:all,error:null}),maybeSingle:async()=>({data:mode==='unauthorized'?null:{dataset_sha256:run.seal.dataset_sha256,reference_sha256:run.seal.reference_sha256},error:null})})} as unknown as SupabaseClient;vi.stubGlobal('Deno',{env:{get:()=> 'synthetic-key'}});return {f,run,all:all as CompactTask[],admin,rpc,claimed,max:()=>max}}
describe('compact durable worker with mocked provider only',()=>{
 it('without paid authorization: zero provider calls and no claimed tasks',async()=>{const h=await harness('unauthorized');expect(await processCompact(h.admin,h.run,'worker')).toMatchObject({status:'error',error_code:'COMPACT_PAID_NOT_AUTHORIZED'});expect(client).not.toHaveBeenCalled();expect(h.rpc.mock.calls.some(([name])=>name==='claim_compact_tasks')).toBe(false)})
 it('one attempt per task, max concurrency8, both payloads English-only, immutable sealed references',async()=>{const h=await harness(),before=JSON.stringify(h.f.references);expect(await processCompact(h.admin,h.run,'worker')).toEqual({status:'completed'});expect(client).toHaveBeenCalledTimes(64);expect(client.mock.calls.every(([,options])=>options.maxAttempts===1)).toBe(true);expect(h.max()).toBeLessThanOrEqual(8);expect(Math.max(...h.claimed)).toBe(8);expect(JSON.stringify(h.f.references)).toBe(before);expect(h.rpc.mock.calls.filter(([name])=>name==='complete_compact_task')).toHaveLength(64)})
 it('network ambiguity never retries; failed calls kept for coverage, false usage completeness',async()=>{const h=await harness('network');expect(await processCompact(h.admin,h.run,'worker')).toEqual({status:'completed'});expect(client).toHaveBeenCalledTimes(64);expect(h.all.every(t=>t.status==='failed'&&t.usage_complete===false&&t.request_count===1)).toBe(true)})
 it('changed seal rejects before provider calls',async()=>{const h=await harness();h.run.seal.reference_sha256='bad';expect(await processCompact(h.admin,h.run,'worker')).toMatchObject({status:'error',error_code:'COMPACT_SEAL_CHANGED'});expect(client).not.toHaveBeenCalled()})
})
