import {preflight,json} from './cors.ts'
import {EXPLORATORY_CONFIG,canonicalJson,exploratoryFingerprint,suspectReasons,reviewBundle,validateAiCorrections,compareAiCorrections,type ExploratoryRun,type ExploratoryItem,type AiCorrection} from './jev-exploratory-core.ts'
export interface ExplorationSource {id:string;kind:ExploratoryRun['source_kind'];organization_id:string;establishment_id:string;name:string;ready:number;total:number;reuses_predictions:boolean}
export interface AiApproval {id:string;bundle_sha256:string;review_ids:string[];approved_at:string;approved_by:string}
export interface ExplorationRepository {user:string;sources:()=>Promise<ExplorationSource[]>;source:(s:ExplorationSource)=>Promise<ExploratoryItem[]>;get:(id?:string)=>Promise<ExploratoryRun|null>;items:(id:string)=>Promise<ExploratoryItem[]>;approvals:(id:string)=>Promise<AiApproval[]>;corrections:(id:string)=>Promise<AiCorrection[]>;usage:(id:string)=>Promise<{requests:number;input_tokens:number;output_tokens:number;cost_usd:number;served_models:string[];complete:boolean}>;create:(source:ExplorationSource,items:ExploratoryItem[],fingerprint:string)=>Promise<string>;write:(id:string,action:string,payload:Record<string,unknown>)=>Promise<Record<string,unknown>>;configured:()=>boolean}
export function exploratoryProjection(run:ExploratoryRun|null,items:ExploratoryItem[],sources:ExplorationSource[],approvals:AiApproval[],corrections:AiCorrection[],usage:Awaited<ReturnType<ExplorationRepository['usage']>>|null){const latest=new Map<string,AiCorrection>();corrections.forEach(c=>latest.set(c.review_id+':'+c.theme_key,c));return {sources,run:run?{id:run.id,status:run.status,source_kind:run.source_kind,source_id:run.source_id,config:run.config,dataset_sha256:run.dataset_sha256,created_at:run.created_at,error_code:run.error_code}:null,items:run?.status==='completed'?items.map(i=>({...i,reasons:suspectReasons(i)})):[],review_count:items.length,flagged_count:run?.status==='completed'?items.filter(i=>suspectReasons(i).length).length:0,approvals,corrections,comparison:corrections.length?compareAiCorrections(items,[...latest.values()]):null,usage,human_validation_required:false as const}}
export function exploratoryHandler(repository:(r:Request)=>Promise<ExplorationRepository>){return async(request:Request)=>{const options=preflight(request);if(options)return options;try{if(!['GET','POST'].includes(request.method))return json({error:'METHOD_NOT_ALLOWED'},405);const repo=await repository(request),sources=await repo.sources(),params=new URL(request.url).searchParams,body=request.method==='POST'?await request.json():null;let run=await repo.get(body?.run_id??params.get('id')??undefined),extra:Record<string,unknown>={}
  if(body){if(body.action==='create'){const source=sources.find(s=>s.id===body.source_id&&s.kind===body.source_kind);if(!source)throw new Error('FORBIDDEN');if(source.total!==source.ready||source.total===0)throw new Error('EXPLORATORY_ENGLISH_REQUIRED');const items=await repo.source(source),fp=await exploratoryFingerprint(items),id=await repo.create(source,items,fp);run=await repo.get(id)}else{if(!run)throw new Error('EXPLORATORY_NOT_FOUND');if(canonicalJson(run.config)!==canonicalJson(EXPLORATORY_CONFIG))throw new Error('EXPLORATORY_CONFIG_CHANGED');const items=await repo.items(run.id);if(await exploratoryFingerprint(items)!==run.dataset_sha256)throw new Error('EXPLORATORY_INTEGRITY_CHANGED')
    if(body.action==='start'){if(body.confirm!==true)throw new Error('EXPLORATORY_PAYMENT_CONFIRMATION_REQUIRED');if(run.status==='idle'&&!repo.configured())throw new Error('JEV_NOT_CONFIGURED');extra=await repo.write(run.id,'start',{confirm:true})}
    else if(body.action==='approve'){if(run.status!=='completed'||body.confirm!==true)throw new Error('EXPLORATORY_GO_REQUIRED');const bundle=await reviewBundle(run,items,body.review_ids??[]);const result=await repo.write(run.id,'approve',{confirm:true,review_ids:body.review_ids,bundle_sha256:bundle.bundle_sha256});extra={export_bundle:{...bundle,approval_id:result.approval_id,user_go:true}}}
    else if(body.action==='export'){const approval=(await repo.approvals(run.id)).find(a=>a.id===body.approval_id);if(!approval)throw new Error('EXPLORATORY_GO_REQUIRED');const bundle=await reviewBundle(run,items,approval.review_ids);if(bundle.bundle_sha256!==approval.bundle_sha256)throw new Error('EXPLORATORY_INTEGRITY_CHANGED');extra={export_bundle:{...bundle,approval_id:approval.id,user_go:true}}}
    else if(body.action==='import'){const approval=(await repo.approvals(run.id)).find(a=>a.id===body.approval_id);if(!approval||body.bundle_sha256!==approval.bundle_sha256||body.dataset_sha256!==run.dataset_sha256||typeof body.import_id!=='string'||!/^[a-f0-9-]{36}$/i.test(body.import_id))throw new Error('EXPLORATORY_GO_REQUIRED');const corrections=validateAiCorrections(body.corrections,items,approval.review_ids);extra=await repo.write(run.id,'import',{approval_id:approval.id,bundle_sha256:approval.bundle_sha256,import_id:body.import_id,corrections})}
    else if(body.action==='reserve'){if(body.confirm!==true||!Number.isInteger(body.future_version)||body.future_version<=11||!['calibration','evaluation'].includes(body.purpose)||!Array.isArray(body.review_ids)||!body.review_ids.length||body.review_ids.some((id:string)=>!items.some(i=>i.review_id===id)))throw new Error('EXPLORATORY_USAGE_INVALID');extra=await repo.write(run.id,'reserve',{future_version:body.future_version,purpose:body.purpose,review_ids:body.review_ids})}
    else throw new Error('EXPLORATORY_ACTION_INVALID');run=await repo.get(run.id)
  }}
  if(!run)return json({...exploratoryProjection(null,[],sources,[],[],null),...extra});const [items,approvals,corrections,usage]=await Promise.all([repo.items(run.id),repo.approvals(run.id),repo.corrections(run.id),repo.usage(run.id)]);if(await exploratoryFingerprint(items)!==run.dataset_sha256)throw new Error('EXPLORATORY_INTEGRITY_CHANGED');return json({...exploratoryProjection(run,items,sources,approvals,corrections,usage),...extra})
}catch(e){const code=e instanceof Error&&/^[A-Z0-9_]+$/.test(e.message)?e.message:'EXPLORATORY_REQUEST_FAILED';return json({error:code},code==='UNAUTHORIZED'?401:code==='FORBIDDEN'?403:/IMMUTABLE|CHANGED|CONTAMINATION|HOLDOUT/.test(code)?409:code.startsWith('EXPLORATORY_')&&!code.endsWith('_FAILED')?400:500)}}}
