import type {SupabaseClient} from 'npm:@supabase/supabase-js@2.117.2'
import {createJevClient} from './jev.ts'
import {parseThemes} from './jev-themes.ts'
import {economicThemeResults} from './jev-economy-cache.ts'
import {compactPayload,verifyCompactSeal,compareCompact,type CompactRun,type CompactTask,type CompactItem,type CompactText,type CompactReference} from './jev-compact-core.ts'
const safe=(e:unknown)=>e instanceof Error&&/^[A-Z0-9_]+$/.test(e.message)?e.message:'COMPACT_NETWORK_ERROR'
export async function processCompact(admin:SupabaseClient,run:CompactRun,worker:string){const begin=Date.now(),rpc=async(name:string,args:Record<string,unknown>)=>{const {data,error}=await admin.rpc(name,args);if(error)throw new Error('COMPACT_SAVE_FAILED');return data},finish=async(comparison:unknown=null,error:string|null=null)=>{if(await rpc('finish_compact_tick',{p_run:run.id,p_worker:worker,p_comparison:comparison,p_error:error})!==true)throw new Error('COMPACT_LEASE_LOST')};try{
 const {data:authorization,error:ae}=await admin.from('analysis_jev_compact_authorizations').select('*').eq('set_id',run.set_id).maybeSingle();if(ae||!authorization||authorization.dataset_sha256!==run.seal.dataset_sha256||authorization.reference_sha256!==run.seal.reference_sha256)throw new Error('COMPACT_PAID_NOT_AUTHORIZED');
 const loaded=await Promise.all(['items','texts','ai_references'].map(async name=>{const {data,error}=await admin.from('analysis_jev_compact_'+name).select('*').eq('set_id',run.set_id).limit(801);if(error)throw new Error('COMPACT_READ_FAILED');return data})),items=loaded[0] as CompactItem[],texts=loaded[1] as CompactText[],refs=loaded[2] as CompactReference[];await verifyCompactSeal(items,texts,refs,run.seal);const key=Deno.env.get('TYPESAFE_API_KEY');if(!key?.trim())throw new Error('JEV_NOT_CONFIGURED');
 while(Date.now()-begin<70_000){const tasks=await rpc('claim_compact_tasks',{p_run:run.id,p_worker:worker}) as CompactTask[];if(!tasks.length)break;if(tasks.length>8)throw new Error('COMPACT_CONCURRENCY_INVALID');const outcomes=await Promise.allSettled(tasks.map(async t=>{const i=items.find(i=>i.review_id===t.review_id),text=texts.find(x=>x.id===i?.text_id);if(!text||text.analysis_text_sha256!==t.analysis_text_sha256)throw new Error('COMPACT_TASK_INVALID');let input=0,output=0,requests=0,model:string|null=null,response=null,error_code:string|null=null,usage_complete=true;const start=Date.now(),client=createJevClient(key,{maxAttempts:1,onUsage:(u,m)=>{input=u.input_tokens;output=u.output_tokens;model=m},onAttempt:()=>requests++});try{const result=await client.evaluatePayload(compactPayload(t.variant,'r'+i!.position,text.analysis_text),parseThemes);response=result.decision;model=result.model}catch(e){error_code=safe(e);usage_complete=false}if(await rpc('complete_compact_task',{p_run:run.id,p_worker:worker,p_task:t.id,p_values:{status:error_code?'failed':'completed',response,theme_results:response?economicThemeResults(response):null,served_model:model,input_tokens:input,output_tokens:output,request_count:requests,retry_count:0,duration_ms:Date.now()-start,error_code,usage_complete}})!==true)throw new Error('COMPACT_LEASE_LOST')}));const failed=outcomes.find(o=>o.status==='rejected');if(failed?.status==='rejected')throw failed.reason}
 const {data:tasks,error}=await admin.from('analysis_jev_compact_tasks').select('*').eq('run_id',run.id).limit(65);if(error)throw new Error('COMPACT_READ_FAILED');if(tasks.some(t=>['pending','running'].includes(t.status))){await finish();return {status:'running'}}await finish(await compareCompact({...run,completed_at:new Date().toISOString()},items,texts,refs,tasks as CompactTask[]));return {status:'completed'}
 }catch(e){const code=safe(e);if(code!=='COMPACT_LEASE_LOST')try{await finish(null,code)}catch{/* Ambiguous paid attempts are never re-enqueued. */}return {status:'error',error_code:code}}}
