import {analysisTextForFreshReview,type AnalysisReview,type EnglishTranslationOverride} from './analysis-text.ts'
import {ECONOMY_CONFIG} from './jev-economy-config.ts'
import {economyIdentity,economyCacheKey,reusableEconomyCache,economicThemeResults,type EconomyCache} from './jev-economy-cache.ts'
import {THEME_KEYS} from './jev-themes.ts'
import {GOLD_TAXONOMY} from './gold-taxonomy.ts'
import {canonicalJson} from './jev-exploratory-core.ts'
import {negativeHash as sha} from './negative-validation-core.ts'
import {normalizeCategoryRatings,crossRatingAnalysis,type CategoryRatings} from './cross-rating-analysis.ts'
import {structuredContextStats} from './structured-review-context.ts'
export const PILOT_VERSION='jev-economy-pilot-v1'
export const PILOT_ESTABLISHMENT='252a8dca-14c7-4f09-bd1f-7b2c40ae97aa'
export const PILOT_AXES=['service','quality','price','atmosphere'] as const
export type PilotAxis=typeof PILOT_AXES[number]
export interface PilotRawReview extends AnalysisReview {id:string;organization_id:string;establishment_id:string;rating:number;review_detailed_rating:unknown;review_context:unknown;published_at:string|null}
export interface PilotReview {id:string;organization_id:string;establishment_id:string;rating:number;original_text:string;original_text_sha256:string;original_language:string|null;analysis_text:string|null;analysis_text_sha256:string|null;analysis_language:string|null;analysis_source:string;translation_provenance:unknown;normalized_category_ratings:CategoryRatings;review_detailed_rating:unknown;review_context:unknown;published_at:string|null}
export interface PilotLegacy {generation_id:string;analysis_version:number;preferred_language:string;stored_reviews_count:number;google_total_reviews:number|null;data_complete:boolean;ai_call_count:number|null;ai_input_tokens:number|null;ai_output_tokens:number|null;ai_cost_usd:number|null;ai_historical_summary:string|null;consultant_report:Record<string,unknown>|null;positive_themes:{theme_key:string;mentions:number;label_fr:string;label_vi:string;review_ids:string[]}[];negative_themes:{theme_key:string;mentions:number;label_fr:string;label_vi:string;review_ids:string[]}[];generated_at:string;source_ids?:string[];model?:string|null}
export interface PilotSnapshot {id:string;organization_id:string;establishment_id:string;name:string;created_by:string;created_at:string;source_sha256:string;config_sha256:string;source:{google_total_reviews:number|null;establishment_name:string;reviews:PilotReview[];legacy:PilotLegacy|null};rates:PilotRates;preview_at_creation:unknown;production_enabled:false}
export interface PilotRates {jev_input:number|null;jev_output:number|null;sol_input:number|null;sol_output:number|null;apify_import:number|null;english_translation:number|null;observed_jev_input_per_review:number|null;observed_jev_output_per_review:number|null;observed_sol_input:number|null;observed_sol_output:number|null;provenance:string[]}
export function normalizePilotLegacy(h:PilotLegacy|null):PilotLegacy|null{if(!h)return null;return {generation_id:h.generation_id,analysis_version:h.analysis_version,preferred_language:h.preferred_language,stored_reviews_count:h.stored_reviews_count,google_total_reviews:h.google_total_reviews,data_complete:h.data_complete,ai_call_count:h.ai_call_count,ai_input_tokens:h.ai_input_tokens,ai_output_tokens:h.ai_output_tokens,ai_cost_usd:h.ai_cost_usd,ai_historical_summary:h.ai_historical_summary,consultant_report:h.consultant_report,positive_themes:h.positive_themes,negative_themes:h.negative_themes,generated_at:h.generated_at,source_ids:h.source_ids??[],model:h.model??null}}
export async function resolvePilotReviews(rows:PilotRawReview[],overrides:EnglishTranslationOverride[],org:string,est:string,asOf:string){if(new Set(rows.map(r=>r.id)).size!==rows.length||rows.some(r=>r.organization_id!==org||r.establishment_id!==est))throw new Error('PILOT_TENANT_MISMATCH');return await Promise.all([...rows].sort((a,b)=>a.id.localeCompare(b.id)).map(async r=>{const t=await analysisTextForFreshReview(r,overrides.find(o=>o.review_id===r.id),asOf),ready=t.analysis_language==='en'&&!!t.analysis_text.trim();return {id:r.id,organization_id:org,establishment_id:est,rating:r.rating,original_text:r.original_text??'',original_text_sha256:await sha(r.original_text??''),original_language:r.original_language??null,analysis_text:ready?t.analysis_text:null,analysis_text_sha256:ready?await sha(t.analysis_text):null,analysis_language:t.analysis_language??null,analysis_source:t.analysis_source,translation_provenance:'analysis_translation_override' in t?t.analysis_translation_override:{source:t.analysis_source,provider_translation_id:r.review_translations?.find(t=>t.language==='en')?.id??null},normalized_category_ratings:normalizeCategoryRatings(r.review_detailed_rating),review_detailed_rating:r.review_detailed_rating,review_context:r.review_context,published_at:r.published_at} satisfies PilotReview}))}
export async function pilotSourceHash(source:PilotSnapshot['source']){return sha(canonicalJson({google_total_reviews:source.google_total_reviews,reviews:source.reviews,legacy:source.legacy,configuration:ECONOMY_CONFIG.id,config_sha256:await sha(canonicalJson(ECONOMY_CONFIG))}))}
export async function verifyPilotSnapshot(s:PilotSnapshot){if(s.establishment_id!==PILOT_ESTABLISHMENT||s.config_sha256!==await sha(canonicalJson(ECONOMY_CONFIG))||s.source_sha256!==await pilotSourceHash(s.source)||s.source.reviews.some(r=>r.organization_id!==s.organization_id||r.establishment_id!==s.establishment_id))throw new Error('PILOT_SNAPSHOT_CHANGED');for(const r of s.source.reviews){if(await sha(r.original_text)!==r.original_text_sha256||r.analysis_text!==null&&(r.analysis_language!=='en'||await sha(r.analysis_text)!==r.analysis_text_sha256))throw new Error('PILOT_TEXT_CHANGED')}}
export async function auditPilotCache(reviews:PilotReview[],cache:(EconomyCache&{theme_results?:unknown;source_kind?:string;source_run_id?:string})[],org:string,est:string){const used:EconomyCache[]=[],missing:string[]=[],blocked:string[]=[],rejected:{cache_id:string;review_id:string;reasons:string[]}[]=[],other=cache.filter(c=>c.configuration_id!==ECONOMY_CONFIG.id).length;
 for(const r of reviews){if(!r.analysis_text||r.analysis_language!=='en')continue;const own=cache.filter(c=>c.review_id===r.id&&c.configuration_id===ECONOMY_CONFIG.id).sort((a,b)=>(b.processed_at??'').localeCompare(a.processed_at??'')||a.id.localeCompare(b.id));let valid:EconomyCache|undefined;for(const c of own){const reasons:string[]=[];if(c.organization_id!==org||c.establishment_id!==est)reasons.push('TENANT_OR_ESTABLISHMENT_MISMATCH');if(c.analysis_text_sha256!==r.analysis_text_sha256)reasons.push('ENGLISH_TEXT_CHANGED');if(c.status!=='completed')reasons.push('CACHE_NOT_COMPLETED');if(!c.served_model||c.served_model==='jev-latest'||c.expected_served_model!==c.served_model)reasons.push('SERVED_MODEL_UNVERIFIED');if(c.instruction_version!==ECONOMY_CONFIG.instruction_version)reasons.push('INSTRUCTION_VERSION_MISMATCH');if(c.threshold_version!==ECONOMY_CONFIG.threshold_version)reasons.push('THRESHOLD_VERSION_MISMATCH');if(!reasons.length){const identity=await economyIdentity(org,est,r.id,r.analysis_text,c.served_model!),key=await economyCacheKey(identity);if(!reusableEconomyCache(c,identity,key))reasons.push('CACHE_IDENTITY_OR_RESPONSE_INVALID');else if(!c.theme_results||canonicalJson(c.theme_results)!==canonicalJson(economicThemeResults(c.response!)))reasons.push('STORED_THEMES_INCONSISTENT')}if(reasons.length)rejected.push({cache_id:c.id,review_id:r.id,reasons});else if(!valid)valid=c}
 if(valid)used.push(valid);else{missing.push(r.id);if(own.some(c=>c.analysis_text_sha256===r.analysis_text_sha256&&['reserved','dispatched','billing_uncertain','failed_not_sent'].includes(c.status)))blocked.push(r.id)}}
 return {used,missing_review_ids:missing,blocked_review_ids:blocked,rejected,excluded_other_configuration_rows:other,expected_configuration:ECONOMY_CONFIG.id,served_models:[...new Set(used.flatMap(c=>c.served_model?[c.served_model]:[]))].sort(),raw_completed_full_cache_rows:cache.filter(c=>c.configuration_id===ECONOMY_CONFIG.id&&c.status==='completed').length}}
export const pilotStarDistribution=(rows:{rating:number}[])=>Object.fromEntries([1,2,3,4,5].map(n=>[String(n),rows.filter(r=>r.rating===n).length])) as Record<string,number>
export function pilotStatistics(reviews:PilotReview[],audit:Awaited<ReturnType<typeof auditPilotCache>>,googleTotal:number|null){const ids=new Set(audit.used.map(c=>c.review_id)),assessed=reviews.filter(r=>ids.has(r.id)),text=reviews.filter(r=>r.original_text.trim()),fullStars=pilotStarDistribution(text),analysedStars=pilotStarDistribution(assessed),variation=text.length&&assessed.length?[1,2,3,4,5].reduce((n,k)=>n+Math.abs(fullStars[k]/text.length-analysedStars[k]/assessed.length),0)/2:null,knownBias=(assessed.length<text.length&&audit.used.filter(c=>['first','second','third','compact_benchmark','compact_benchmark_single_attempt'].includes((c as EconomyCache&{source_kind?:string}).source_kind??'')).length>assessed.length/2),warnings:string[]=[];if(assessed.length<text.length)warnings.push('PARTIAL_TEXT_COVERAGE');if(googleTotal!==null&&reviews.length<googleTotal)warnings.push('PARTIAL_GOOGLE_DATASET');if(knownBias||variation!==null&&variation>.1)warnings.push('STAR_DISTRIBUTION_BIASED');if(audit.served_models.length>1)warnings.push('MULTIPLE_SERVED_MODELS');if(reviews.some(r=>(r.translation_provenance as {status?:string})?.status==='rejected'))warnings.push('ENGLISH_OVERRIDE_ANOMALY');
 const findings=audit.used.flatMap(c=>{const result=economicThemeResults(c.response!);return THEME_KEYS.flatMap(theme=>(['positive','negative'] as const).filter(sentiment=>result[theme].choice===sentiment||result[theme].choice==='both').map(sentiment=>({review_id:c.review_id,theme_key:theme,sentiment,evidence:null})))}),topics=THEME_KEYS.flatMap(theme=>(['positive','negative'] as const).flatMap(sentiment=>{const own=findings.filter(f=>f.theme_key===theme&&f.sentiment===sentiment),review_ids=[...new Set(own.map(f=>f.review_id))].sort();return own.length?[{key:theme+':'+sentiment,theme_key:theme,axis:GOLD_TAXONOMY[theme].axis,sentiment,mentions:own.length,affected_reviews:review_ids.length,review_ids,examples:review_ids.slice(0,2).map(id=>({review_id:id,rating:reviews.find(r=>r.id===id)!.rating,analysis_text:reviews.find(r=>r.id===id)!.analysis_text!,evidence_kind:'full_analytical_review_text_not_a_fabricated_quote'}))}]:[]})).sort((a,b)=>b.mentions-a.mentions||a.key.localeCompare(b.key)),cross=crossRatingAnalysis(assessed.map(r=>({...r,analysis_text:r.analysis_text??undefined})),findings),allRatings=crossRatingAnalysis(reviews.map(r=>({...r,analysis_text:r.analysis_text??undefined})),[]),coverage={google_total:googleTotal,stored_reviews:reviews.length,reviews_with_text:text.length,textless_reviews:reviews.length-text.length,english_ready:reviews.filter(r=>r.analysis_text&&r.analysis_language==='en').length,analysed_reviews:assessed.length,reused_analyses:assessed.length,missing_analyses:audit.missing_review_ids.length,blocked_analyses:audit.blocked_review_ids.length,missing_english:text.filter(r=>!r.analysis_text).length,not_analysable_total:reviews.filter(r=>!r.analysis_text).length,analysis_text_coverage:text.length?assessed.length/text.length:null,analysis_english_coverage:reviews.filter(r=>r.analysis_text).length?assessed.length/reviews.filter(r=>r.analysis_text).length:null,stored_google_coverage:googleTotal?reviews.length/googleTotal:null,analysed_google_coverage:googleTotal?assessed.length/googleTotal:null};
 const completeUsage=audit.used.every(c=>c.usage_complete&&c.input_tokens!==null&&c.output_tokens!==null&&c.cost_usd!==null),cacheUsage={historical_calls:audit.used.length,input_tokens:completeUsage?audit.used.reduce((n,c)=>n+c.input_tokens!,0):null,output_tokens:completeUsage?audit.used.reduce((n,c)=>n+c.output_tokens!,0):null,cost_usd:completeUsage?audit.used.reduce((n,c)=>n+c.cost_usd!,0):null,additional_reuse_cost_usd:0};
 return {coverage,cache_usage:cacheUsage,warnings,not_representative_of_restaurant:warnings.length>0,theme_frequency_denominator:'assessed_review_subset_only',theme_frequencies_for_restaurant:null,star_distribution:{stored_text:fullStars,assessed:analysedStars,total_variation:variation,known_stratified_cache:knownBias},positive_topics:topics.filter(t=>t.sentiment==='positive'),negative_topics:topics.filter(t=>t.sentiment==='negative'),axes:PILOT_AXES.map(axis=>({key:axis,positive_mentions:findings.filter(f=>GOLD_TAXONOMY[f.theme_key].axis===axis&&f.sentiment==='positive').length,negative_mentions:findings.filter(f=>GOLD_TAXONOMY[f.theme_key].axis===axis&&f.sentiment==='negative').length,positive_review_count:new Set(findings.filter(f=>GOLD_TAXONOMY[f.theme_key].axis===axis&&f.sentiment==='positive').map(f=>f.review_id)).size,negative_review_count:new Set(findings.filter(f=>GOLD_TAXONOMY[f.theme_key].axis===axis&&f.sentiment==='negative').map(f=>f.review_id)).size})),google_context:{scope:'all_stored_snapshot_reviews',overall_average_rating:allRatings.overall_average_rating,axes:Object.fromEntries(['food','service','atmosphere'].map(k=>{const a=allRatings.axes[k as 'food'];return [k,{rating_count:a.rating_count,average_rating:a.average_rating,low_rating_count:a.low_rating_count,distribution:a.distribution}]})),price:{google_rating:null,description:'No dedicated Google Price rating'}},cross_rating_analysis:cross,structured_context_stats:structuredContextStats(reviews),findings,served_models:audit.served_models}}
export function pilotCosts(r:PilotRates,missing:number,blocked=0){const known=(x:number|null)=>x!==null&&Number.isFinite(x)&&x>=0,jevUnit=[r.jev_input,r.jev_output,r.observed_jev_input_per_review,r.observed_jev_output_per_review].every(known)?(r.jev_input!*r.observed_jev_input_per_review!+r.jev_output!*r.observed_jev_output_per_review!)/1e6:null,sol=[r.sol_input,r.sol_output,r.observed_sol_input,r.observed_sol_output].every(known)?(r.sol_input!*r.observed_sol_input!+r.sol_output!*r.observed_sol_output!)/1e6:null,requests=missing-blocked,jev=requests===0?0:jevUnit===null?null:requests*jevUnit;return {reused_extra_cost_usd:0,planned_jev_requests:requests,blocked_requests:blocked,estimated_jev_cost_usd:jev,estimated_sol_cost_usd:sol,total_known_usd:jev!==null&&sol!==null?jev+sol:null,apify_cost_usd:r.apify_import,translation_unit_cost_usd:r.english_translation,jev_per_review_cost_usd:jevUnit,estimate_basis:'Measured recorded usage at persisted configured rates; future usage may differ',rates:r}}
export function pilotComparison(source:PilotSnapshot['source'],stats:ReturnType<typeof pilotStatistics>){const old=source.legacy,nowIds=new Set(source.reviews.map(r=>r.id)),oldIds=new Set(old?.source_ids??[]),common=[...oldIds].filter(id=>nowIds.has(id));return {legacy:old,old_review_ids_available:oldIds.size>0,dataset:{old_stored:old?.stored_reviews_count??null,pilot_stored:source.reviews.length,common_reviews:oldIds.size?common.length:null,old_only:oldIds.size?oldIds.size-common.length:null,pilot_only:oldIds.size?nowIds.size-common.length:null},directly_comparable:false,reasons:['DIFFERENT_DATA_SNAPSHOT','DIFFERENT_ANALYSIS_ENGINE_AND_TAXONOMY','PILOT_COVERAGE_PARTIAL_OR_DIFFERENT'],old_positive_topics:old?.positive_themes??[],old_negative_topics:old?.negative_themes??[],pilot_positive_topics:stats.positive_topics,pilot_negative_topics:stats.negative_topics,recommendation_relevance_assessment:'manual_review_only_no_automatic_quality_verdict',matched_snapshot_protocol:{enabled:false,requires_separate_explicit_authorization:true,review_ids:[...nowIds].sort(),analysis_text_sha256:source.reviews.map(r=>({review_id:r.id,sha256:r.analysis_text_sha256})),description:'Future experiment must run both fixed engines on identical review IDs and identical English text hashes; never rewrite historical results'}}}
