import {describe,it,expect,vi} from 'vitest'
import {readFileSync,readdirSync} from 'node:fs'
import {join} from 'node:path'
import {ECONOMY_CONFIG,COMPACT_CONFIG,economyPayload,instructionAudit} from './jev-economy-config'
import {V12_CONFIG,V12_THRESHOLDS} from './jev-v12-config'
import {V11_THRESHOLDS} from './jev-v11-calibration'
import {V13_CONFIG} from './jev-v13-config'
import {THEME_KEYS} from './jev-themes'
import {compareEconomySource,economyMetrics,economyPrediction,economyUsage} from './jev-economy-score'
import {economyIdentity,economyCacheKey,reusableEconomyCache,economicThemeResults,planEconomy,dispatchEconomicAnalysis,consolidateEconomicResults,type EconomyCache} from './jev-economy-cache'
import {estimateEconomyCosts} from './jev-economy-cost'
import {economyHandler} from './jev-economy-api'
import {syntheticV12} from '../../../tests/fixtures/jev-v12'
import {canonicalJson} from './jev-exploratory-core'
import {negativeHash} from './negative-validation-core'
const fixture=async()=>{const f=await syntheticV12();return {id:f.run.id,kind:'first',organization_id:f.run.organization_id,prepared:{...f.prepared},tasks:f.v12Tasks}},rates={jev_input:.042,jev_output:0,apify_import_per_review:null,translation_per_review:null,sol_input:2,sol_output:10,sol_narrative_input_tokens:4000,sol_narrative_output_tokens:1000,provenance:['fixture']}
describe('Jev economy offline configuration and scores',()=>{
 it('preserves 25 exact V12 questions/thresholds, separate frozen configs and one pass',()=>{const before=canonicalJson({V11_THRESHOLDS,V12_CONFIG,V13_CONFIG});expect(ECONOMY_CONFIG.questions).toEqual(V12_CONFIG.questions);expect(ECONOMY_CONFIG.thresholds).toEqual(V12_THRESHOLDS);expect(ECONOMY_CONFIG.questions).not.toBe(V12_CONFIG.questions);expect(ECONOMY_CONFIG.repeat_count).toBe(1);expect(ECONOMY_CONFIG.production_enabled).toBe(false);expect(ECONOMY_CONFIG.paid_enabled).toBe(false);expect(Object.isFrozen(ECONOMY_CONFIG.questions)).toBe(true);expect(THEME_KEYS).toHaveLength(25);expect(canonicalJson({V11_THRESHOLDS,V12_CONFIG,V13_CONFIG})).toBe(before)})
 it('only text/alias/model/questions, no metadata; textless fails before a provider',()=>{expect(economyPayload('r','English')).toEqual({...economyPayload('r','English'),state:{review_alias:'r',analysis_text:'English'}});expect(()=>economyPayload('r',' ')).toThrow('TEXTLESS');expect(Object.keys(economyPayload('r','English'))).toEqual(['model','state','questions'])})
 it('compact candidate uses documented API shape with 25 choices; shorter is not validated precision',()=>{const audit=instructionAudit();expect(audit.character_reduction).toBeGreaterThan(.3);expect(audit.semantic_equivalence_verified).toBe(false);expect(Object.keys(COMPACT_CONFIG.questions)).toEqual(THEME_KEYS);for(const q of Object.values(COMPACT_CONFIG.questions) as {type:string;instructions:string;criteria:object}[]){expect(q.type).toBe('choice');expect(q.instructions).not.toContain('__analysis_text__');expect(Object.keys(q.criteria)).toEqual(['absent','positive','negative','both'])}})
 it('one pass probabilities are NOT averaged with other passes; both uses independent thresholds',async()=>{const f=await fixture(),id=f.tasks[0].review_id;f.tasks.find(t=>t.review_id===id&&t.repeat===1)!.response!.themes.food_quality={choice:'positive',probabilities:{absent:.2,positive:.7,negative:.1,both:0}};for(const t of f.tasks.filter(t=>t.review_id===id&&t.repeat!==1))t.response!.themes.food_quality={choice:'absent',probabilities:{absent:1,positive:0,negative:0,both:0}};expect(economyPrediction(f.tasks,id,'food_quality','pass1').positive).toBe(.7);expect(economyPrediction(f.tasks,id,'food_quality','pass1').choice).toBe('positive');expect(economyPrediction(f.tasks,id,'food_quality','mean3').choice).toBe('absent');const d=structuredClone(f.tasks[0].response!);d.themes.coordination={choice:'both',probabilities:{both:.8,positive:0,negative:0,absent:.2}};expect(economicThemeResults(d).coordination.choice).toBe('both')})
 it('paired cohort rejects invalid responses, no mutations, uncertain excluded, no TN F1',async()=>{const f=await fixture(),before=canonicalJson(f);f.tasks[0].status='failed';const c=await compareEconomySource(f);expect(c.evaluable_reviews).toBe(29);expect(c.variants.pass1.compared_labels+c.variants.pass1.uncertain_labels).toBe(29*25);expect(c.variants.pass1.repeat_stability).toBeNull();expect(c.variants.mean3.repeat_stability).toBe(1);expect(economyMetrics({tp:0,fp:0,fn:0,support:0}).f1).toBeNull();expect(economyMetrics({tp:3,fp:1,fn:2,support:5}).f1).toBe(2/3);expect(before).not.toBe(canonicalJson(f));const unchanged=canonicalJson(f);await compareEconomySource(f);expect(canonicalJson(f)).toBe(unchanged)})
 it('validates hashes, duplicate references and failed/incomplete usage',async()=>{const f=await fixture();f.prepared.items[0].analysis_text+=' changed';await expect(compareEconomySource(f)).rejects.toThrow('TEXT_CHANGED');f.prepared.items[0].analysis_text=f.prepared.items[0].analysis_text.replace(' changed','');f.prepared.reference[0].choice='both';await expect(compareEconomySource(f)).rejects.toThrow('REFERENCE_CHANGED');const t=f.tasks[0];t.usage_complete=false;expect(economyUsage([t]).cost_usd).toBeNull()})
 it('scores both polarities/all themes/axes, stable deterministic bootstrap and 2/3 measured savings',async()=>{const c=await compareEconomySource(await fixture()),again=await compareEconomySource(await fixture());expect(c).toEqual(again);expect(Object.keys(c.variants.pass1.themes)).toEqual(THEME_KEYS);expect(Object.keys(c.variants.pass1.axes)).toHaveLength(4);expect(c.variants.pass1.cost_savings_percent).toBeCloseTo(200/3);expect(c.variants.pass1.bootstrap!.negative.resamples).toBe(2000)})
 it('costs 100/500/1000/5000, incremental cache, unknown prices stay null, incomplete usage stays unknown',async()=>{const c=await compareEconomySource(await fixture()),cost=estimateEconomyCosts([c],rates,1000,50);expect(cost.scenarios.map(s=>s.new_reviews)).toEqual([100,500,1000,5000]);expect(cost.initial.jev_analysis_usd).toBeCloseTo(cost.incremental.jev_analysis_usd!*20);expect(cost.initial.total_with_import_and_translation_usd).toBeNull();expect(cost.initial.apify_import_usd).toBeNull();c.variants.pass1.usage.usage_complete=false;expect(estimateEconomyCosts([c],rates,1000,50).initial.jev_analysis_usd).toBeNull();expect(()=>estimateEconomyCosts([],rates,10,20)).toThrow('COUNTS_INVALID')})
})
describe('Jev cache, billing safeguards and disabled engine',()=>{
 async function cache(){const f=await fixture(),i=f.prepared.items[0],identity=await economyIdentity('org','est',i.review_id,i.analysis_text,'jev-pinned'),row:EconomyCache={...identity,id:'cache',cache_key:await economyCacheKey(identity),status:'completed',response:f.tasks[0].response,served_model:'jev-pinned',input_tokens:100,output_tokens:10,cost_usd:.1,usage_complete:true,processed_at:'now',source_task_id:'old-task'};return {f,i,identity,row}}
 it('reuses exact identities; text, tenant, config, thresholds, served model invalidate the cache',async()=>{const {identity,row}=await cache();expect(reusableEconomyCache(row,identity,row.cache_key)).toBe(true);for(const field of ['organization_id','establishment_id','review_id','analysis_text_sha256','instruction_sha256','threshold_version','expected_served_model'] as const)expect(reusableEconomyCache(row,{...identity,[field]:'changed'},row.cache_key)).toBe(false);await expect(economyIdentity('o','e','r','text','jev-latest')).rejects.toThrow('SERVED_MODEL_REQUIRED')})
 it('unconfirmed/running never retry; only English textful reviews planned, stars kept',async()=>{const {i,row}=await cache(),reviews=[{id:i.review_id,establishment_id:'est',analysis_text:i.analysis_text,analysis_language:'en',rating:1},{id:'textless',establishment_id:'est',analysis_text:'',analysis_language:null,rating:5},{id:'foreign',establishment_id:'est',analysis_text:'synthetic',analysis_language:'vi',rating:2}];expect(await planEconomy('org',reviews,[row],'jev-pinned')).toMatchObject({total_google_reviews:3,reviews_with_text:2,already_analyzed:1,planned_jev_calls:0,english_missing:1});row.status='billing_uncertain';expect(await planEconomy('org',reviews,[row],'jev-pinned')).toMatchObject({already_analyzed:0,analyses_blocked:1,planned_jev_calls:0})})
 it('zero provider calls; consolidation refuses stale text and sends only counts to future Sol',async()=>{const network=vi.fn();vi.stubGlobal('fetch',network);try{await expect(dispatchEconomicAnalysis()).rejects.toThrow('DISABLED');const {i,row}=await cache(),reviews=[{id:i.review_id,establishment_id:'est',analysis_text:i.analysis_text,analysis_language:'en',rating:1}];const aggregate=await consolidateEconomicResults('org',reviews,[row],'jev-pinned');expect(aggregate.jev_analyzed_reviews).toBe(1);expect(JSON.stringify(aggregate.sol_narrative_input)).not.toContain('analysis_text');reviews[0].analysis_text+='changed';expect((await consolidateEconomicResults('org',reviews,[row],'jev-pinned')).jev_analyzed_reviews).toBe(0);expect(network).not.toHaveBeenCalled()}finally{vi.unstubAllGlobals()}})
 it('atomic SQL reserve, unique identity, role/RLS fences, permanent completed data, paid dispatch disabled',()=>{const dir=join(process.cwd(),'supabase/migrations'),sql=readFileSync(join(dir,readdirSync(dir).find(n=>n.endsWith('_jev_economy_preparation.sql'))!),'utf8');expect(sql).toContain('pg_advisory_xact_lock');expect(sql).toContain('for update');expect(sql).toContain('unique(organization_id,establishment_id,review_id,analysis_text_sha256');expect(sql).toContain('enable row level security');expect(sql).toContain("'ECONOMY_PAID_ENGINE_DISABLED'");expect(sql).toContain("old.status in ('completed','billing_uncertain')");expect(sql).not.toMatch(/cron.schedule|update public.analysis_jev_v1[123]|insert into public.historical|net.http/);expect(sql).toContain('from public,anon,authenticated')})
 it('API denies all POST before any repository action and enforces auth/config before GET',async()=>{const repo=vi.fn(),handler=economyHandler(repo);expect((await handler(new Request('https://fixture',{method:'POST',body:'{}'}))).status).toBe(405);expect(repo).not.toHaveBeenCalled();repo.mockRejectedValue(new Error('FORBIDDEN'));expect((await handler(new Request('https://fixture'))).status).toBe(403);repo.mockResolvedValue({configurations:async()=>[]});expect(await (await handler(new Request('https://fixture'))).json()).toEqual({error:'ECONOMY_CONFIG_CHANGED'})})
 it('identities are canonical, semantic fingerprints exact across isolated copies',async()=>{expect(await negativeHash(canonicalJson(ECONOMY_CONFIG.questions))).toBe(await negativeHash(canonicalJson(V12_CONFIG.questions)))})
})
