import {THEME_KEYS,type ThemeKey,type ThemeDecision} from './jev-themes.ts'
import {V12_CONFIG} from './jev-v12-config.ts'
import {V13_CONFIG,V13_THRESHOLDS,v13Payload,v13ReportedSafety} from './jev-v13-config.ts'
import {verifyV12,completeReview,validThemeDecision,type V12Run} from './jev-v12-core.ts'
import {verifyIndependent,postgresJsonbText,type IndependentRun} from './independent-jev-core.ts'
import {negativeHash as sha,type NegativeLabel} from './negative-validation-core.ts'
import {negativeModelScores,negativePrediction,negativeBootstrap,type NegativeTask} from './negative-validation-score.ts'
import {canonicalJson} from './jev-exploratory-core.ts'
import {GOLD_CHOICES,type GoldChoice} from './gold-taxonomy.ts'
export const V13_FIRST_SOURCE='1b06d0d9-623b-4ee4-b267-d1078a2aaa74',V13_SECOND_SOURCE='696e6e36-a024-4f69-957e-9cd4e0b50d1b'
export const V13_BENCH_CONFIG=Object.freeze({id:V13_CONFIG.question_set,experimental_only:true,production_enabled:false,requested_model:'jev-latest',repeat_count:3,concurrency:8,v12:V12_CONFIG,v13:V13_CONFIG})
export type V13SourceKind='development_first'|'development_second'|'fresh_blind_ai'
export interface V13Item {review_id:string;position:number;establishment_id:string;analysis_text:string;analysis_text_sha256:string;overall_rating:number;analysis_language:'en'}
export interface V13Label extends NegativeLabel {origin:string;model_source:string}
export interface V13Audit {audit_id:string;run_id:string;review_id:string;theme_key:ThemeKey;analysis_text_sha256:string;initial_ai_choice:GoldChoice;reviewed_ai_choice:GoldChoice;verdict:'confirmed_v12_error'|'ai_reference_correction'|'ambiguous';error_kind:string;annotation_source:string;scoring_use:string;rationale_fr:string;has_translation_concern:boolean;created_at:string}
export interface V13Task {id:string;run_id:string;review_id:string;model_version:'v12'|'v13';repeat:number;review_alias:string;question_set:string;analysis_text_sha256:string;status:'pending'|'running'|'completed'|'failed';response:ThemeDecision|null;served_model:string|null;input_tokens:number;output_tokens:number;request_count:number;retry_count:number;cost_usd:number;duration_ms:number;error_code:string|null;usage_complete:boolean}
export interface V13Source {id:string;kind:V13SourceKind;organization_id:string;name:string;items:V13Item[];reference:V13Label[];baseline:V13Task[];audits:V13Audit[];total_source_reviews:number;source_created_at:string;source_fingerprint:string;sealed_at:string|null;blind_to_predictions:boolean}
export async function firstDevelopmentSource(run:V12Run,tasks:V13Task[]):Promise<V13Source>{await verifyV12(run);if(run.id!==V13_FIRST_SOURCE||run.status!=='completed')throw new Error('V13_SOURCE_REQUIRED');return {id:run.id,kind:'development_first',organization_id:run.organization_id,name:'Artisan — premier jeu de développement',items:run.prepared.items.map(i=>({review_id:i.review_id,position:i.position,analysis_text:i.analysis_text,analysis_text_sha256:i.analysis_text_sha256,establishment_id:run.establishment_id,overall_rating:i.overall_rating,analysis_language:'en'})),reference:run.prepared.reference.map(r=>({review_id:r.review_id,theme_key:r.theme_key,choice:r.choice,origin:r.origin,model_source:r.model_source})),baseline:tasks.map(t=>({...t,model_version:'v12'})),audits:[],total_source_reviews:run.prepared.source_total_reviews,source_created_at:run.completed_at!,source_fingerprint:run.prepared.prepared_sha256,sealed_at:null,blind_to_predictions:false}}
export async function secondDevelopmentSource(run:IndependentRun,tasks:V13Task[],pairedIds:string[],audits:V13Audit[]):Promise<V13Source>{await verifyIndependent(run);if(run.id!==V13_SECOND_SOURCE||run.status!=='completed'||new Set(pairedIds).size!==pairedIds.length)throw new Error('V13_SOURCE_REQUIRED');const items=run.prepared.items.filter(i=>pairedIds.includes(i.review_id));if(items.length!==pairedIds.length)throw new Error('V13_COHORT_CHANGED');return {id:run.id,kind:'development_second',organization_id:run.organization_id,name:'Artisan — deuxième jeu désormais de développement',items:items.map(i=>({review_id:i.review_id,position:i.position,analysis_text:i.analysis_text,analysis_text_sha256:i.analysis_text_sha256,overall_rating:i.overall_rating,establishment_id:run.establishment_id,analysis_language:'en'})),reference:run.prepared.reference.filter(r=>pairedIds.includes(r.review_id)).flatMap(r=>THEME_KEYS.map(theme_key=>({review_id:r.review_id,theme_key,choice:r.theme_choices[theme_key],origin:'legacy_sealed_ai_unchanged',model_source:r.model_source}))),baseline:tasks.filter(t=>pairedIds.includes(t.review_id)&&t.model_version==='v12'),audits,total_source_reviews:run.prepared.items.length,source_created_at:run.completed_at!,source_fingerprint:run.prepared.prepared_sha256,sealed_at:run.prepared.seal.sealed_at,blind_to_predictions:false}}
export interface V13FreshInput {id:string;organization_id:string;name:string;items:V13Item[];reference:V13Label[];dataset_sha256:string;reference_sha256:string;configuration_id:string;blind_to_predictions:boolean;reference_created_at:string;sealed_at:string;source_kind:'fresh_blind_ai'}
export async function freshV13Source(input:V13FreshInput,usedIds:string[],configurationFrozenAt:string):Promise<V13Source>{if(input.configuration_id!==V13_CONFIG.question_set||!input.blind_to_predictions||!Number.isFinite(Date.parse(input.sealed_at))||!Number.isFinite(Date.parse(input.reference_created_at))||!Number.isFinite(Date.parse(configurationFrozenAt))||Date.parse(input.sealed_at)>Date.now()||Date.parse(input.reference_created_at)>Date.parse(input.sealed_at)||Date.parse(configurationFrozenAt)>Date.parse(input.reference_created_at))throw new Error('V13_FRESH_SEAL_REQUIRED');if(input.items.some(i=>i.establishment_id==='252a8dca-14c7-4f09-bd1f-7b2c40ae97aa'))throw new Error('V13_FRESH_ARTISAN_EXCLUDED');if(input.items.some(i=>usedIds.includes(i.review_id)))throw new Error('V13_FRESH_DATASET_ALREADY_USED');if(await sha(postgresJsonbText(input.items))!==input.dataset_sha256||await sha(postgresJsonbText(input.reference))!==input.reference_sha256)throw new Error('V13_FRESH_SEAL_CHANGED');return {id:input.id,kind:'fresh_blind_ai',organization_id:input.organization_id,name:input.name,items:input.items,reference:input.reference,baseline:[],audits:[],total_source_reviews:input.items.length,source_created_at:input.reference_created_at,source_fingerprint:await sha(input.dataset_sha256+':'+input.reference_sha256),sealed_at:input.sealed_at,blind_to_predictions:true}}
export async function prepareV13(source:V13Source,rates:{input:number;output:number}){
 const items=[...source.items].sort((a,b)=>a.position-b.position),ids=items.map(i=>i.review_id);if(!items.length||items.length>128||new Set(ids).size!==ids.length||new Set(items.map(i=>i.position)).size!==items.length||!Number.isFinite(rates.input)||rates.input<0||!Number.isFinite(rates.output)||rates.output<0||canonicalJson(V13_THRESHOLDS)!==canonicalJson(V12_CONFIG.thresholds))throw new Error('V13_DATASET_INVALID')
 for(const i of items){if(!i.analysis_text?.trim()||i.analysis_language!=='en'||await sha(i.analysis_text)!==i.analysis_text_sha256)throw new Error('V13_ENGLISH_TEXT_CHANGED')}
 const reference=[...source.reference].sort((a,b)=>a.review_id.localeCompare(b.review_id)||a.theme_key.localeCompare(b.theme_key));if(reference.length!==items.length*25||new Set(reference.map(r=>r.review_id+':'+r.theme_key)).size!==reference.length||reference.some(r=>!ids.includes(r.review_id)||!THEME_KEYS.includes(r.theme_key)||!GOLD_CHOICES.includes(r.choice)||!r.origin||!r.model_source))throw new Error('V13_REFERENCE_CHANGED')
 const baseline=[...source.baseline].sort((a,b)=>a.id.localeCompare(b.id));if(source.kind==='fresh_blind_ai'){if(baseline.length||source.audits.length||!source.blind_to_predictions||!source.sealed_at)throw new Error('V13_FRESH_SEAL_REQUIRED')}else if(source.blind_to_predictions||baseline.length!==items.length*3||ids.some(id=>!completeReview(baseline,id))||baseline.some(t=>t.model_version!=='v12'||t.question_set!==V12_CONFIG.question_set||t.analysis_text_sha256!==items.find(i=>i.review_id===t.review_id)?.analysis_text_sha256))throw new Error('V13_BASELINE_INCOMPATIBLE')
 const audits=[...source.audits].sort((a,b)=>a.audit_id.localeCompare(b.audit_id));if(new Set(audits.map(a=>a.review_id+':'+a.theme_key)).size!==audits.length)throw new Error('V13_AUDIT_CHANGED');for(const a of audits){const ref=reference.find(r=>r.review_id===a.review_id&&r.theme_key===a.theme_key);if(!ref||a.run_id!==source.id||a.analysis_text_sha256!==items.find(i=>i.review_id===a.review_id)?.analysis_text_sha256||a.initial_ai_choice!==ref.choice||!GOLD_CHOICES.includes(a.reviewed_ai_choice)||!['confirmed_v12_error','ai_reference_correction','ambiguous'].includes(a.verdict)||a.scoring_use!=='diagnostic_only_no_sealed_reference_change')throw new Error('V13_AUDIT_CHANGED')}
 const config_sha256=await sha(canonicalJson(V13_BENCH_CONFIG)),dataset_sha256=await sha(canonicalJson(items)),reference_sha256=await sha(canonicalJson(reference)),baseline_sha256=await sha(canonicalJson(baseline)),audit_sha256=await sha(canonicalJson(audits)),expected_requests=items.length*(source.kind==='fresh_blind_ai'?6:3),estimated_input_tokens=Math.ceil(items.reduce((n,i)=>n+canonicalJson(v13Payload('r'+i.position,i.analysis_text)).length+(source.kind==='fresh_blind_ai'?canonicalJson({...v13Payload('r'+i.position,i.analysis_text),questions:V12_CONFIG.questions}).length:0),0)*3/4*1.25),estimated_cost_usd=estimated_input_tokens*rates.input/1_000_000,prepared_sha256=await sha(canonicalJson({source_id:source.id,source_kind:source.kind,source_fingerprint:source.source_fingerprint,config_sha256,dataset_sha256,reference_sha256,baseline_sha256,audit_sha256,expected_requests,rates}));return {source_id:source.id,source_kind:source.kind,organization_id:source.organization_id,source_name:source.name,source_fingerprint:source.source_fingerprint,source_created_at:source.source_created_at,sealed_at:source.sealed_at,blind_to_predictions:source.kind==='fresh_blind_ai',items,reference,baseline,audits,total_source_reviews:source.total_source_reviews,uncertain_labels:reference.filter(r=>r.choice==='uncertain').length,config_sha256,dataset_sha256,reference_sha256,baseline_sha256,audit_sha256,expected_requests,estimated_input_tokens,estimated_cost_usd,prepared_sha256,rates}
}
export type V13Prepared=Awaited<ReturnType<typeof prepareV13>>
export interface V13Run {id:string;source_id:string;source_kind:V13SourceKind;organization_id:string;config:typeof V13_BENCH_CONFIG;prepared:V13Prepared;status:'queued'|'running'|'completed'|'failed';created_at:string;started_at:string|null;completed_at:string|null;error_code:string|null}
export async function verifyV13(run:V13Run){const p=run.prepared;if(run.source_id!==p.source_id||run.source_kind!==p.source_kind||run.organization_id!==p.organization_id||canonicalJson(run.config)!==canonicalJson(V13_BENCH_CONFIG))throw new Error('V13_INTEGRITY_CHANGED');const s:V13Source={id:p.source_id,kind:p.source_kind,organization_id:p.organization_id,name:p.source_name,items:p.items,reference:p.reference,baseline:p.baseline,audits:p.audits,total_source_reviews:p.total_source_reviews,source_created_at:p.source_created_at,source_fingerprint:p.source_fingerprint,sealed_at:p.sealed_at,blind_to_predictions:p.blind_to_predictions},recomputed=await prepareV13(s,p.rates);if(recomputed.prepared_sha256!==p.prepared_sha256||p.config_sha256!==recomputed.config_sha256||p.dataset_sha256!==recomputed.dataset_sha256||p.reference_sha256!==recomputed.reference_sha256||p.baseline_sha256!==recomputed.baseline_sha256||p.audit_sha256!==recomputed.audit_sha256||p.expected_requests!==recomputed.expected_requests)throw new Error('V13_INTEGRITY_CHANGED')}
const has=(c:GoldChoice,p:'positive'|'negative')=>c===p||c==='both'
function scoreTasks(tasks:V13Task[],version:'v12'|'v13'):NegativeTask[]{return tasks.filter(t=>t.model_version===version).map(t=>({...t,model_version:'v11',experiment_id:t.run_id,question_set_version:t.question_set}))}
export async function compareV13(run:V13Run,tasks:V13Task[]){await verifyV13(run);const p=run.prepared,ids=p.items.map(i=>i.review_id);if(tasks.length!==p.expected_requests||new Set(tasks.map(t=>t.model_version+':'+t.review_id+':'+t.repeat)).size!==tasks.length||tasks.some(t=>t.run_id!==run.id||!ids.includes(t.review_id)||!['v12','v13'].includes(t.model_version)||p.source_kind!=='fresh_blind_ai'&&t.model_version!=='v13'||t.question_set!==run.config[t.model_version].question_set||t.analysis_text_sha256!==p.items.find(i=>i.review_id===t.review_id)?.analysis_text_sha256))throw new Error('V13_TASKS_CHANGED');const all=[...p.baseline,...tasks],left=scoreTasks(all,'v12'),right=scoreTasks(all,'v13'),common=ids.filter(id=>completeReview(left,id)&&completeReview(right,id)),a=negativeModelScores(common,p.reference,left,'v11'),b=negativeModelScores(common,p.reference,right,'v11'),prediction=(version:'v12'|'v13',id:string,k:ThemeKey)=>negativePrediction(version==='v12'?left:right,id,k,'v11'),errors=(v:'v12'|'v13')=>common.flatMap(id=>THEME_KEYS.flatMap(theme_key=>{const ref=p.reference.find(r=>r.review_id===id&&r.theme_key===theme_key)!.choice,pred=prediction(v,id,theme_key)!.choice;if(ref==='uncertain')return [];return (['positive','negative'] as const).flatMap(polarity=>has(ref,polarity)===has(pred,polarity)?[]:[{review_id:id,theme_key,polarity,kind:has(pred,polarity)?'false_positive':'false_negative',ai_reference:ref,predicted:pred}])})),score=(v:'v12'|'v13')=>{const {perReview:_rows,errors:_old,...stats}=v==='v12'?a:b;void _rows;void _old;return {...stats,errors:errors(v)}},usage=(v:'v12'|'v13')=>{const own=all.filter(t=>t.model_version===v);return {requests:own.reduce((n,t)=>n+t.request_count,0),input_tokens:own.reduce((n,t)=>n+t.input_tokens,0),output_tokens:own.reduce((n,t)=>n+t.output_tokens,0),estimated_cost_usd:own.reduce((n,t)=>n+t.cost_usd,0),request_elapsed_sum_ms:own.reduce((n,t)=>n+t.duration_ms,0),served_models:[...new Set(own.flatMap(t=>t.served_model?[t.served_model]:[]))].sort(),usage_complete:own.every(t=>t.usage_complete),reused:v==='v12'&&p.source_kind!=='fresh_blind_ai'}}
 const audit_cases=p.audits.map(a=>{const l=prediction('v12',a.review_id,a.theme_key),r=prediction('v13',a.review_id,a.theme_key),comparable=common.includes(a.review_id)&&a.verdict!=='ambiguous'&&a.reviewed_ai_choice!=='uncertain';return {...a,v12_choice:l?.choice??null,v13_choice:r?.choice??null,comparable,v12_matches_reviewed:comparable?l?.choice===a.reviewed_ai_choice:null,v13_matches_reviewed:comparable?r?.choice===a.reviewed_ai_choice:null}}),audit_summary={total:audit_cases.length,probable_v12_errors:audit_cases.filter(a=>a.verdict==='confirmed_v12_error').length,reference_corrections:audit_cases.filter(a=>a.verdict==='ai_reference_correction').length,ambiguous_excluded:audit_cases.filter(a=>a.verdict==='ambiguous'||a.reviewed_ai_choice==='uncertain').length,errors_resolved:audit_cases.filter(a=>a.verdict==='confirmed_v12_error'&&a.v13_matches_reviewed===true).length,errors_unresolved:audit_cases.filter(a=>a.verdict==='confirmed_v12_error'&&a.v13_matches_reviewed===false).length,unavailable:audit_cases.filter(a=>!common.includes(a.review_id)).length,diagnostic_only:true,primary_reference_unchanged:true}
 const reviews=p.items.map(i=>{const own=(v:'v12'|'v13')=>completeReview(v==='v12'?left:right,i.review_id)?Object.fromEntries(THEME_KEYS.map(k=>[k,prediction(v,i.review_id,k)!])) as Record<ThemeKey,NonNullable<ReturnType<typeof negativePrediction>>>:null,v12=own('v12'),v13=own('v13'),ai_reference=Object.fromEntries(p.reference.filter(r=>r.review_id===i.review_id).map(r=>[r.theme_key,r.choice])) as Record<ThemeKey,GoldChoice>,reasons:{code:string;theme_key?:ThemeKey;version?:'v12'|'v13'}[]=[];for(const k of THEME_KEYS){if(v12&&v13&&v12[k].choice!==v13[k].choice)reasons.push({code:'v12_v13_disagreement',theme_key:k});for(const v of ['v12','v13'] as const){const pred=v==='v12'?v12:v13;if(!pred){if(k===THEME_KEYS[0])reasons.push({code:'incomplete_response',version:v});continue}if(!pred[k].stable)reasons.push({code:'repeat_instability',theme_key:k,version:v});if(ai_reference[k]!=='uncertain'&&ai_reference[k]!==pred[k].choice)reasons.push({code:has(ai_reference[k],'negative')&&!has(pred[k].choice,'negative')?'potentially_missed_criticism':'ai_reference_disagreement',theme_key:k,version:v})}}const safety=v13ReportedSafety(i.analysis_text);if(safety)reasons.push({code:'reported_safety_no_causality'});return {...i,v12,v13,ai_reference,reasons,safety}}),u={v12:usage('v12'),v13:usage('v13')},bootstrap=async(kind:'overall'|'negative')=>{const {conclusion:_c,...interval}=await negativeBootstrap(run.id,a,b,kind,common.length===ids.length);void _c;return {...interval,comparison:'v13_minus_v12',human_validated:false}},v12=score('v12'),v13=score('v13'),key=(e:typeof v12.errors[number])=>e.review_id+':'+e.theme_key+':'+e.polarity
 return {configuration_id:V13_CONFIG.question_set,experimental_only:true,production_enabled:false,human_validated:false,independent_for_v13:p.source_kind==='fresh_blind_ai',reference_type:p.source_kind==='fresh_blind_ai'?'fresh_blind_ai_not_human_gold':'development_ai_reference_not_independent_for_v13',source_kind:p.source_kind,source_id:p.source_id,coverage:{v12:ids.filter(id=>completeReview(left,id)).length,v13:ids.filter(id=>completeReview(right,id)).length,common:common.length,total:ids.length,source_total:p.total_source_reviews,complete:common.length===ids.length},v12,v13,bootstrap:{overall:await bootstrap('overall'),negative:await bootstrap('negative')},audit_summary,audit_cases,translation_anomalies:p.audits.filter(a=>a.has_translation_concern).map(a=>({review_id:a.review_id,code:'translation_concern_in_ai_audit',note:a.rationale_fr})),reviews,disagreement_count:reviews.reduce((n,r)=>n+r.reasons.filter(a=>a.code==='v12_v13_disagreement').length,0),calibration_diagnostics:{missed_negative_recovered:v12.errors.filter(e=>e.kind==='false_negative'&&e.polarity==='negative'&&!v13.errors.some(x=>x.kind==='false_negative'&&key(x)===key(e))).length,new_missed_negative:v13.errors.filter(e=>e.kind==='false_negative'&&e.polarity==='negative'&&!v12.errors.some(x=>x.kind==='false_negative'&&key(x)===key(e))).length,new_false_positives:v13.errors.filter(e=>e.kind==='false_positive'&&!v12.errors.some(x=>x.kind==='false_positive'&&key(x)===key(e))).length},failures:tasks.filter(t=>t.status==='failed'||!validThemeDecision(t.response)).map(t=>({review_id:t.review_id,version:t.model_version,repeat:t.repeat,error_code:t.error_code??'INVALID_RESPONSE'})),invalid_response_rate:tasks.length?tasks.filter(t=>!validThemeDecision(t.response)).length/tasks.length:null,usage:u,new_paid_v12_requests:p.source_kind==='fresh_blind_ai'?u.v12.requests:0,total_estimated_cost_usd:tasks.reduce((n,t)=>n+t.cost_usd,0),historical_baseline_cost_usd:u.v12.reused?u.v12.estimated_cost_usd:0,model_version_confounded:canonicalJson(u.v12.served_models)!==canonicalJson(u.v13.served_models)||Object.values(u).some(u=>u.served_models.length>1),end_to_end_elapsed_ms:run.started_at&&run.completed_at?Date.parse(run.completed_at)-Date.parse(run.started_at):null,integrity:{dataset_sha256:p.dataset_sha256,reference_sha256:p.reference_sha256,baseline_sha256:p.baseline_sha256,audit_sha256:p.audit_sha256,identical_texts:true},warning:p.source_kind==='fresh_blind_ai'?'New reviews and blinded AI reference, not independent human Gold. Exploratory, star-stratified, no automatic production switch.':'Previously examined development reviews and non-independent AI references. Diagnostic scores cannot demonstrate generalization; sealed labels stay unchanged.'}
}
