import {json,preflight} from './cors.ts'
import {COMPACT_CONFIGS,compactCostPreview,verifyCompactSeal,type CompactSet,type CompactItem,type CompactText,type CompactReference,type CompactSeal,type CompactRun,type CompactComparison} from './jev-compact-core.ts'
import {canonicalJson} from './jev-exploratory-core.ts'
import {negativeHash} from './negative-validation-core.ts'
export interface CompactData {set:CompactSet|null;items:CompactItem[];texts:CompactText[];references:CompactReference[];seal:CompactSeal|null;run:CompactRun|null;comparison:CompactComparison|null;authorization:{cost_limit_usd:number;expected_served_model:string}|null;progress:{total:number;completed:number;failed:number}}
export interface CompactRepository {read:()=>Promise<CompactData>;configurations:()=>Promise<{id:string;config:unknown;config_sha256:string}[]>;inventory:()=>Promise<unknown>;costBasis:()=>Promise<Parameters<typeof compactCostPreview>[0]>;cacheCounts?:()=>Promise<{A:number;B:number}>;prepare:()=>Promise<void>;importTexts:(rows:unknown)=>Promise<void>;importReferences:(rows:unknown)=>Promise<void>;seal:()=>Promise<void>;start:(fingerprint:string,estimate:number,rates:{input:number;output:number})=>Promise<void>}
export function compactHandler(repository:(r:Request)=>Promise<CompactRepository>){return async(request:Request)=>{const pre=preflight(request);if(pre)return pre;try{if(!['GET','POST'].includes(request.method))return json({error:'METHOD_NOT_ALLOWED'},405);const repo=await repository(request),configurations=await repo.configurations();for(const c of Object.values(COMPACT_CONFIGS)){const stored=configurations.find(s=>s.id===c.id);if(!stored||canonicalJson(stored.config)!==canonicalJson(c)||stored.config_sha256!==await negativeHash(canonicalJson(c)))throw new Error('COMPACT_CONFIG_CHANGED')}let data=await repo.read();const cost=compactCostPreview(await repo.costBasis(),repo.cacheCounts?await repo.cacheCounts():{A:0,B:0});
 if(request.method==='POST'){const b=await request.json();if(b.action==='prepare'){await repo.prepare()}else if(b.action==='import_texts'){await repo.importTexts(b.rows)}else if(b.action==='import_references'){await repo.importReferences(b.rows)}else if(b.action==='seal'){if(b.confirm!==true)throw new Error('COMPACT_SEAL_CONFIRMATION_REQUIRED');await repo.seal()}else if(b.action==='start'){if(b.confirm_cost!==true)throw new Error('COMPACT_COST_CONFIRMATION_REQUIRED');if(!data.authorization)throw new Error('COMPACT_PAID_NOT_AUTHORIZED');if(!data.seal)throw new Error('COMPACT_SEAL_REQUIRED');await verifyCompactSeal(data.items,data.texts,data.references,data.seal);if(b.reference_sha256!==data.seal.reference_sha256)throw new Error('COMPACT_SEAL_CHANGED');await repo.start(data.seal.reference_sha256,cost.indicative_budget_if_B_costs_as_A_usd,cost.rates)}else throw new Error('COMPACT_ACTION_INVALID');data=await repo.read()}
 if(data.seal)await verifyCompactSeal(data.items,data.texts,data.references,data.seal);const ready=data.items.filter(i=>data.texts.some(t=>t.id===i.text_id&&t.language==='en')).length;
 return json({...data,configurations,inventory:await repo.inventory(),cost,english_ready:ready,english_missing:data.items.length-ready,reference_labels:data.references.length,can_seal:ready===32&&data.references.length===800&&!data.seal,can_start:!!data.authorization&&!!data.seal&&!data.run,paid_authorization_required:!data.authorization,production_enabled:false,new_paid_calls:0})
 }catch(e){const code=e instanceof Error&&/^[A-Z0-9_]+$/.test(e.message)?e.message:'COMPACT_REQUEST_FAILED';return json({error:code},code==='UNAUTHORIZED'?401:code==='FORBIDDEN'?403:409)}}}
export type CompactView=CompactData&{configurations:{id:string;config:unknown;config_sha256:string}[];inventory:unknown;cost:ReturnType<typeof compactCostPreview>;english_ready:number;english_missing:number;reference_labels:number;can_seal:boolean;can_start:boolean;paid_authorization_required:boolean;production_enabled:false;new_paid_calls:0}
export function compactBlindExport(data:CompactData){if(data.items.length!==32||data.items.some(i=>!data.texts.find(t=>t.id===i.text_id&&t.language==='en')))throw new Error('COMPACT_ENGLISH_REQUIRED');return {reference_type:'ai_reference_not_human_gold',annotation_protocol:'blind_to_jev_predictions',theme_keys:Object.keys(COMPACT_CONFIGS.A.questions),choices:['absent','positive','negative','both','uncertain'],reviews:data.items.map(i=>{const t=data.texts.find(t=>t.id===i.text_id)!;return {review_id:i.review_id,analysis_text:t.analysis_text,analysis_text_sha256:t.analysis_text_sha256}})}}
