import type {SupabaseClient} from 'npm:@supabase/supabase-js@2.117.2'
import {createJevClient} from './jev.ts'
import {parseThemes} from './jev-themes.ts'
import {economyPayload} from './jev-economy-config.ts'
import {economicThemeResults} from './jev-economy-cache.ts'
import {verifyPilotSnapshot,type PilotSnapshot} from './jev-pilot-core.ts'
import {writePilotProse} from './jev-pilot-sol.ts'
import {fallbackPilotProse,type PilotNarrativeContext} from './jev-pilot-narrative.ts'
import type {PilotJob} from './jev-pilot-api.ts'
const safe=(e:unknown)=>e instanceof Error&&/^[A-Z0-9_]+$/.test(e.message)?e.message:'PILOT_PROVIDER_ERROR'
export async function processPilot(admin:SupabaseClient,job:PilotJob,worker:string){const begin=Date.now(),rpc=async(name:string,args:Record<string,unknown>)=>{const {data,error}=await admin.rpc(name,args);if(error)throw new Error('PILOT_SAVE_FAILED');return data},finish=async(result:unknown=null,usage:unknown=null,error:string|null=null)=>{if(await rpc('finish_economy_pilot_tick',{p_job:job.id,p_worker:worker,p_result:result,p_usage:usage,p_error:error})!==true)throw new Error('PILOT_LEASE_LOST')};try{
 const {data:s,error:se}=await admin.from('analysis_jev_pilot_snapshots').select('*').eq('id',job.snapshot_id).single(),{data:a,error:ae}=await admin.from('analysis_jev_pilot_authorizations').select('*').eq('id',job.authorization_id).single();if(se||ae||!a||!s||a.organization_id!==s.organization_id||job.organization_id!==s.organization_id||a.snapshot_id!==s.id||a.source_sha256!==s.source_sha256||a.config_sha256!==s.config_sha256||a.stage!==job.stage||a.language!==job.language)throw new Error('PILOT_NEW_AUTHORIZATION_REQUIRED');const snapshot=s as PilotSnapshot;await verifyPilotSnapshot(snapshot);
 if(job.stage==='sol'){if(!Deno.env.get('OPENAI_API_KEY')?.trim())throw new Error('AI_NOT_CONFIGURED');if(await rpc('begin_economy_pilot_sol_attempt',{p_job:job.id,p_worker:worker})!==true)throw new Error('PILOT_LEASE_LOST');const input=job.input_context.narrative_input as PilotNarrativeContext;let tokens={input_tokens:0,output_tokens:0},known=false,prose,origin='sol_aggregate_writer',error_code:string|null=null;try{prose=await writePilotProse(input,async usage=>{tokens=usage;known=Number.isSafeInteger(usage.input_tokens)&&Number.isSafeInteger(usage.output_tokens)&&usage.input_tokens>0&&usage.output_tokens>=0})}catch(e){prose=fallbackPilotProse(input);origin='deterministic_fallback_after_single_sol_attempt';error_code=safe(e)}await finish({prose,origin,error_code,language:job.language,source_sha256:snapshot.source_sha256,input_sha256:job.input_sha256,per_review_sol_extraction_calls:0},{...tokens,usage_complete:known,duration_ms:Date.now()-begin});return {status:'completed'}}
 const key=Deno.env.get('TYPESAFE_API_KEY');if(!key?.trim())throw new Error('JEV_NOT_CONFIGURED');while(Date.now()-begin<70_000){const tasks=await rpc('claim_economy_pilot_tasks',{p_job:job.id,p_worker:worker}) as {id:string;review_id:string;analysis_text_sha256:string}[];if(!tasks.length)break;if(tasks.length>8)throw new Error('PILOT_CONCURRENCY_INVALID');const outcomes=await Promise.allSettled(tasks.map(async t=>{const r=snapshot.source.reviews.find(r=>r.id===t.review_id);if(!r?.analysis_text||r.analysis_language!=='en'||r.analysis_text_sha256!==t.analysis_text_sha256)throw new Error('PILOT_TASK_SCOPE_INVALID');let input=0,output=0,requests=0,model:string|null=null,response=null,error_code:string|null=null,usage_complete=true;const start=Date.now(),client=createJevClient(key,{maxAttempts:1,onUsage:(u,m)=>{input=u.input_tokens;output=u.output_tokens;model=m},onAttempt:()=>requests++});try{const result=await client.evaluatePayload(economyPayload('r'+snapshot.source.reviews.indexOf(r),r.analysis_text),parseThemes);response=result.decision;model=result.model}catch(e){error_code=safe(e);usage_complete=false}if(await rpc('complete_economy_pilot_task',{p_job:job.id,p_worker:worker,p_task:t.id,p_values:{status:error_code?'failed':'completed',response,theme_results:response?economicThemeResults(response):null,served_model:model,input_tokens:input,output_tokens:output,request_count:requests,duration_ms:Date.now()-start,error_code,usage_complete}})!==true)throw new Error('PILOT_LEASE_LOST')}));const bad=outcomes.find(o=>o.status==='rejected');if(bad?.status==='rejected')throw bad.reason}
 const {data:tasks,error}=await admin.from('analysis_jev_pilot_tasks').select('status,error_code,review_id,request_count,reused').eq('job_id',job.id).limit(5001);if(error)throw new Error('PILOT_READ_FAILED');if(tasks.some(t=>['pending','running'].includes(t.status))){await finish();return {status:'running'}}await finish({stage:'jev',failed_reviews:tasks.filter(t=>t.status==='failed').map(t=>({review_id:t.review_id,error_code:t.error_code})),sol_calls:0,automatic_report_generation:false});return {status:'completed'}
 }catch(e){const code=safe(e);if(code!=='PILOT_LEASE_LOST')try{await finish(null,null,code)}catch{/* Never resubmit an unconfirmed paid attempt. */}return {status:'error',error_code:code}}}
