import {THEME_KEYS,THEME_CHOICES,themePresence,type ThemeKey,type ThemeChoice,type ThemeDecision} from './jev-themes.ts'
import {GOLD_TAXONOMY,type GoldChoice} from './gold-taxonomy.ts'
import {validThemeDecision,completeReview} from './jev-v12-core.ts'
import {meetsV11Threshold} from './jev-v11-calibration.ts'
import {economyThreshold} from './jev-economy-config.ts'
import {negativeHash} from './negative-validation-core.ts'
import {canonicalJson} from './jev-exploratory-core.ts'

export type EconomyMode='pass1'|'pass2'|'pass3'|'mean3'
export const ECONOMY_MODES:EconomyMode[]=['pass1','pass2','pass3','mean3']
export interface EconomyTask {id:string;review_id:string;repeat:number;status:string;response:ThemeDecision|null;analysis_text_sha256?:string;served_model:string|null;input_tokens:number;output_tokens:number;cost_usd:number;request_count:number;retry_count:number;duration_ms:number;usage_complete:boolean}
export interface EconomyLabel {review_id:string;theme_key:ThemeKey;choice:GoldChoice}
export interface EconomyItem {review_id:string;analysis_text:string;analysis_text_sha256:string;establishment_id?:string}
export interface EconomySource {id:string;kind:string;organization_id:string;prepared:{items:EconomyItem[];reference:(EconomyLabel|{review_id:string;theme_choices:Record<ThemeKey,GoldChoice>})[];reference_sha256:string;[key:string]:unknown};tasks:EconomyTask[]}
export type EconomyCounts={tp:number;fp:number;fn:number;support:number}
const empty=():EconomyCounts=>({tp:0,fp:0,fn:0,support:0})
const sum=(rows:EconomyCounts[])=>rows.reduce((a,b)=>({tp:a.tp+b.tp,fp:a.fp+b.fp,fn:a.fn+b.fn,support:a.support+b.support}),empty())
export const economyMetrics=(c:EconomyCounts)=>({...c,precision:c.tp+c.fp?c.tp/(c.tp+c.fp):null,recall:c.support?c.tp/c.support:null,f1:c.support?2*c.tp/(2*c.tp+c.fp+c.fn):null})
const has=(c:GoldChoice,p:'positive'|'negative')=>c===p||c==='both'
export function economyPrediction(tasks:EconomyTask[],id:string,k:ThemeKey,mode:EconomyMode){const rows=tasks.filter(t=>t.review_id===id&&(mode==='mean3'||t.repeat===Number(mode.at(-1))));if(rows.length!==(mode==='mean3'?3:1)||rows.some(t=>t.status!=='completed'||!validThemeDecision(t.response)))throw new Error('ECONOMY_RESPONSE_INCOMPLETE');const ps=rows.map(t=>themePresence(t.response!.themes[k])),positive=ps.reduce((n,p)=>n+p.positive_presence_probability,0)/ps.length,negative=ps.reduce((n,p)=>n+p.negative_presence_probability,0)/ps.length,p=meetsV11Threshold(positive,economyThreshold(k,'positive')),n=meetsV11Threshold(negative,economyThreshold(k,'negative'));return {choice:(p?n?'both':'positive':n?'negative':'absent') as ThemeChoice,positive,negative}}
export function economyScore(ids:string[],labels:EconomyLabel[],tasks:EconomyTask[],mode:EconomyMode){const truth=new Map(labels.map(l=>[l.review_id+':'+l.theme_key,l.choice])),themes=Object.fromEntries(THEME_KEYS.map(k=>[k,{positive:empty(),negative:empty()}])) as Record<ThemeKey,{positive:EconomyCounts;negative:EconomyCounts}>,errors:{review_id:string;theme_key:ThemeKey;polarity:'positive'|'negative';kind:'false_positive'|'false_negative';reference:GoldChoice;prediction:ThemeChoice}[]=[],perReview:{negative:EconomyCounts;positive:EconomyCounts;overall:EconomyCounts}[]=[];let uncertain=0,same=0,compared=0;
 for(const id of ids){const row={negative:empty(),positive:empty(),overall:empty()};for(const k of THEME_KEYS){const h=truth.get(id+':'+k);if(!h)throw new Error('ECONOMY_REFERENCE_INCOMPLETE');const prediction=economyPrediction(tasks,id,k,mode);if(h==='uncertain'){uncertain++;continue}compared++;if(h===prediction.choice)same++;for(const polarity of ['positive','negative'] as const){const a=has(h,polarity),b=has(prediction.choice,polarity),key=b?a?'tp':'fp':a?'fn':null,c=themes[k][polarity];if(a){c.support++;row[polarity].support++;row.overall.support++}if(key){c[key]++;row[polarity][key]++;row.overall[key]++;if(key!=='tp')errors.push({review_id:id,theme_key:k,polarity,kind:key==='fp'?'false_positive':'false_negative',reference:h,prediction:prediction.choice})}}}perReview.push(row)}
 const positive=THEME_KEYS.map(k=>themes[k].positive),negative=THEME_KEYS.map(k=>themes[k].negative),supported=[...positive,...negative].filter(c=>c.support>=3);return {negative:economyMetrics(sum(negative)),positive:economyMetrics(sum(positive)),overall:economyMetrics(sum([...negative,...positive])),macro_f1:supported.length?supported.reduce((n,c)=>n+economyMetrics(c).f1!,0)/supported.length:null,macro_supported_labels:supported.length,uncertain_labels:uncertain,compared_labels:compared,exact_choice_agreement:compared?same/compared:null,repeat_stability:mode==='mean3'?ids.reduce((n,id)=>n+THEME_KEYS.filter(k=>new Set(tasks.filter(t=>t.review_id===id).map(t=>t.response!.themes[k].choice)).size===1).length,0)/(ids.length*25):null,themes:Object.fromEntries(THEME_KEYS.map(k=>[k,{positive:economyMetrics(themes[k].positive),negative:economyMetrics(themes[k].negative)}])) as Record<ThemeKey,{positive:ReturnType<typeof economyMetrics>;negative:ReturnType<typeof economyMetrics>}>,axes:Object.fromEntries(['quality','service','atmosphere','price'].map(axis=>{const keys=THEME_KEYS.filter(k=>GOLD_TAXONOMY[k].axis===axis);return [axis,{positive:economyMetrics(sum(keys.map(k=>themes[k].positive))),negative:economyMetrics(sum(keys.map(k=>themes[k].negative)))}]})),errors,perReview}
}
async function bootstrap(id:string,a:ReturnType<typeof economyScore>,b:ReturnType<typeof economyScore>,polarity:'positive'|'negative'){let state=parseInt((await negativeHash(id+':'+polarity)).slice(0,8),16)||1;const values:number[]=[];for(let n=0;n<2000;n++){const x=[],y=[];for(let j=0;j<a.perReview.length;j++){state^=state<<13;state^=state>>>17;state^=state<<5;const index=Math.floor((state>>>0)/4294967296*a.perReview.length);x.push(a.perReview[index][polarity]);y.push(b.perReview[index][polarity])}const f=economyMetrics(sum(x)).f1,g=economyMetrics(sum(y)).f1;if(f!==null&&g!==null)values.push(g-f)}values.sort((x,y)=>x-y);const valid=values.length===2000&&a.perReview.filter(r=>r[polarity].support>0).length>=3;return {resamples:2000,delta:a[polarity].f1===null||b[polarity].f1===null?null:b[polarity].f1!-a[polarity].f1!,ci_95_low:valid?values[49]:null,ci_95_high:valid?values[1949]:null,valid_resamples:values.length,method:'paired_review_bootstrap',direction:'single_pass_minus_mean3'}}
export function economyUsage(tasks:EconomyTask[]){const complete=tasks.length>0&&tasks.every(t=>t.usage_complete&&t.request_count===1&&t.retry_count===0&&[t.input_tokens,t.output_tokens,t.cost_usd].every(n=>Number.isFinite(n)&&n>=0));return {evaluations:tasks.length,requests:tasks.reduce((n,t)=>n+t.request_count,0),input_tokens:complete?tasks.reduce((n,t)=>n+t.input_tokens,0):null,output_tokens:complete?tasks.reduce((n,t)=>n+t.output_tokens,0):null,cost_usd:complete?tasks.reduce((n,t)=>n+t.cost_usd,0):null,duration_ms:tasks.reduce((n,t)=>n+t.duration_ms,0),served_models:[...new Set(tasks.flatMap(t=>t.served_model?[t.served_model]:[]))].sort(),usage_complete:complete}}
export async function compareEconomySource(source:EconomySource){const p=source.prepared;if(await negativeHash(canonicalJson(p.reference))!==p.reference_sha256)throw new Error('ECONOMY_REFERENCE_CHANGED');if(new Set(p.items.map(i=>i.review_id)).size!==p.items.length)throw new Error('ECONOMY_DUPLICATE_REVIEW');for(const item of p.items){if(!item.analysis_text.trim()||await negativeHash(item.analysis_text)!==item.analysis_text_sha256||source.tasks.some(t=>t.review_id===item.review_id&&t.analysis_text_sha256&&t.analysis_text_sha256!==item.analysis_text_sha256))throw new Error('ECONOMY_TEXT_CHANGED')}
 const ids=p.items.filter(i=>completeReview(source.tasks,i.review_id)).map(i=>i.review_id),labels=p.reference.flatMap(r=>'theme_choices' in r?THEME_KEYS.map(theme_key=>({review_id:r.review_id,theme_key,choice:r.theme_choices[theme_key]})):[r]);if(new Set(labels.map(l=>l.review_id+':'+l.theme_key)).size!==p.items.length*25||labels.length!==p.items.length*25||labels.some(l=>!THEME_KEYS.includes(l.theme_key)||![...THEME_CHOICES,'uncertain'].includes(l.choice)))throw new Error('ECONOMY_REFERENCE_INVALID');if(!ids.length)throw new Error('ECONOMY_NO_COMPLETE_REVIEWS');const tasks=source.tasks.filter(t=>ids.includes(t.review_id)),full=economyUsage(tasks),scores=Object.fromEntries(ECONOMY_MODES.map(mode=>[mode,economyScore(ids,labels,tasks,mode)])) as Record<EconomyMode,ReturnType<typeof economyScore>>;
 const variants=await Promise.all(ECONOMY_MODES.map(async mode=>{const {perReview,...score}=scores[mode];void perReview;const usage=economyUsage(tasks.filter(t=>mode==='mean3'||t.repeat===Number(mode.at(-1))));return [mode,{...score,usage,token_savings_percent:full.input_tokens!==null&&usage.input_tokens!==null&&full.input_tokens+full.output_tokens!>0?100*(1-(usage.input_tokens+usage.output_tokens!)/(full.input_tokens+full.output_tokens!)):null,cost_savings_percent:full.cost_usd!==null&&full.cost_usd>0&&usage.cost_usd!==null?100*(1-usage.cost_usd/full.cost_usd):null,bootstrap:mode==='mean3'?null:{negative:await bootstrap(source.id+mode,scores.mean3,scores[mode],'negative'),positive:await bootstrap(source.id+mode,scores.mean3,scores[mode],'positive')}}]}));
 const degraded=THEME_KEYS.flatMap(k=>(['negative','positive'] as const).flatMap(polarity=>{const baseline=scores.mean3.themes[k][polarity];return (['pass1','pass2','pass3'] as const).flatMap(mode=>{const candidate=scores[mode].themes[k][polarity],delta=baseline.f1===null||candidate.f1===null?null:candidate.f1-baseline.f1;return baseline.support>=3&&delta!==null&&delta<=-.03?[{theme_key:k,polarity,mode,support:baseline.support,delta_f1:delta,baseline_f1:baseline.f1,single_f1:candidate.f1}]:[]})}));
 return {source_id:source.id,source_kind:source.kind,source_reviews:p.items.length,evaluable_reviews:ids.length,excluded_review_ids:p.items.filter(i=>!ids.includes(i.review_id)).map(i=>i.review_id),reference_sha256:p.reference_sha256,source_sha256:await negativeHash(canonicalJson({prepared:p,tasks:source.tasks})),reference_type:'historical_AI_reference_exploratory_not_human_gold',human_validated:false,production_enabled:false,new_paid_calls:0,variants:Object.fromEntries(variants) as Record<EconomyMode,Omit<ReturnType<typeof economyScore>,'perReview'>&{usage:ReturnType<typeof economyUsage>;token_savings_percent:number|null;cost_savings_percent:number|null;bootstrap:{negative:Awaited<ReturnType<typeof bootstrap>>;positive:Awaited<ReturnType<typeof bootstrap>>}|null}>,degraded_themes:degraded,degradation_display_rule:{minimum_support:3,absolute_f1_drop:.03,interpretation:'diagnostic flag, not statistical proof'},models_changed:full.served_models.length!==1,stability_measured_from_three_existing_repeats:scores.mean3.repeat_stability,warning:'Retrospective paired replay of stored V12 responses. Historical AI references are preserved, uncertain excluded. Single-pass repeat stability cannot be measured from one response. No independent human validation.'}
}
export type EconomyComparison=Awaited<ReturnType<typeof compareEconomySource>>
