import {describe,it,expect,vi} from 'vitest'
import {readFileSync,readdirSync} from 'node:fs'
import {join} from 'node:path'
import {COMPACT_CONFIGS,selectCompactCandidates,compactIdentity,compactPayload,compactFingerprints,verifyCompactSeal,compactCostPreview,type CompactCandidate} from './jev-compact-core'
import {compactBlindExport,compactHandler} from './jev-compact-api'
import {economyCacheKey} from './jev-economy-cache'
import {THEME_KEYS} from './jev-themes'
import {canonicalJson} from './jev-exploratory-core'
import {V11_THRESHOLDS} from './jev-v11-calibration'
import {V12_CONFIG} from './jev-v12-config'
import {V13_CONFIG} from './jev-v13-config'
import {syntheticCompact} from '../../../tests/fixtures/jev-compact'
const candidates=():CompactCandidate[]=>Array.from({length:120},(_,n)=>({review_id:'r'+n,establishment_id:'e'+n%5,establishment_name:'Venue '+n%5,organization_id:'org',overall_rating:n<60?2:n<100?4:5,original_text:'Synthetic original '+n,original_language:'vi',english_text:n%2?'Synthetic English '+n:null,english_source:n%2?'google_translation_en':null,translation_id:null}));
describe('New compact paired preparation',()=>{
 it('17/11/4 deterministic, multiple establishments, same tenant, no textless/used ids, no predictions',async()=>{const c=candidates();c.push({...c[0],review_id:'foreign',organization_id:'other'});c[3].original_text=' ';const a=await selectCompactCandidates('org',c,['r0','r1']),b=await selectCompactCandidates('org',[...c].reverse(),['r1','r0']);expect(a.items).toEqual(b.items);expect(a.items).toHaveLength(32);expect(new Set(a.items.map(i=>i.review_id)).size).toBe(32);expect(a.items.filter(i=>i.selection_bucket==='low')).toHaveLength(17);expect(a.items.filter(i=>i.selection_bucket==='four')).toHaveLength(11);expect(a.items.filter(i=>i.selection_bucket==='five')).toHaveLength(4);expect(new Set(a.items.map(i=>i.establishment_id)).size).toBe(5);expect(a.items.some(i=>['foreign','r0','r1','r3'].includes(i.review_id))).toBe(false);expect(a.selection_method).toContain('english_availability');expect(JSON.stringify(a)).not.toContain('prediction')})
 it('insufficient strata and duplicate candidates rejected',async()=>{await expect(selectCompactCandidates('org',candidates().slice(0,10),[])).rejects.toThrow('INSUFFICIENT');const c=candidates();c.push({...c[0]});await expect(selectCompactCandidates('org',c,[])).rejects.toThrow('DUPLICATE')})
 it('config A/B frozen unchanged, exact V12 thresholds, one pass 25 choices text-only',async()=>{const before=canonicalJson({V11_THRESHOLDS,V12_CONFIG,V13_CONFIG,COMPACT_CONFIGS});expect(COMPACT_CONFIGS.A.thresholds).toEqual(COMPACT_CONFIGS.B.thresholds);for(const v of ['A','B'] as const){const p=compactPayload(v,'r','English');expect(p.state).toEqual({review_alias:'r',analysis_text:'English'});expect(Object.keys(p.questions)).toEqual(THEME_KEYS);expect(p.questions).toEqual(COMPACT_CONFIGS[v].questions);expect(COMPACT_CONFIGS[v].repeat_count).toBe(1);expect(Object.values(p.questions).every(q=>Object.keys((q as {criteria:object}).criteria).length===4)).toBe(true)}expect(canonicalJson({V11_THRESHOLDS,V12_CONFIG,V13_CONFIG,COMPACT_CONFIGS})).toBe(before)})
 it('cache identities differ for compact, text or served model, A compatible with permanent cache',async()=>{const A=await compactIdentity('A','o','e','r','English','jev-fixed'),B=await compactIdentity('B','o','e','r','English','jev-fixed');expect(A.threshold_sha256).toBe(B.threshold_sha256);expect(A.instruction_sha256).not.toBe(B.instruction_sha256);expect(await economyCacheKey(A)).not.toBe(await economyCacheKey(B));expect(await economyCacheKey(A)).not.toBe(await economyCacheKey(await compactIdentity('A','o','e','r','Changed','jev-fixed')))})
 it('blind export omits stars, original language/text, source buckets and predictions',async()=>{const f=await syntheticCompact(),exported=compactBlindExport(f);expect(exported.reviews).toHaveLength(32);expect(exported.theme_keys).toHaveLength(25);expect(Object.keys(exported.reviews[0])).toEqual(['review_id','analysis_text','analysis_text_sha256']);expect(JSON.stringify(exported)).not.toMatch(/overall_rating|original_text|selection_bucket|probabilities/);await expect(syntheticCompact('draft').then(f=>compactBlindExport(f))).rejects.toThrow('ENGLISH_REQUIRED')})
 it('real 800 labels required; uncertain preserved; exact text/reference/config seals',async()=>{const f=await syntheticCompact(),original=canonicalJson(f);expect((await compactFingerprints(f.items,f.texts,f.references)).uncertain_labels).toBe(1);await verifyCompactSeal(f.items,f.texts,f.references,f.seal!);expect(canonicalJson(f)).toBe(original);f.texts[0].analysis_text+=' changed';await expect(verifyCompactSeal(f.items,f.texts,f.references,f.seal!)).rejects.toThrow('ENGLISH_REQUIRED');const g=await syntheticCompact();g.references.pop();await expect(compactFingerprints(g.items,g.texts,g.references)).rejects.toThrow('AI_REFERENCE_REQUIRED')})
 it('cost A measured, B unknown, no invented compact token saving, scenarios 100/500/1000',()=>{const c=compactCostPreview({input_tokens:800000,output_tokens:100000,reviews:100,input_rate:.042,output_rate:0});expect(c.A.estimate_usd).toBeCloseTo(.010752);expect(c.B.estimate_usd).toBeNull();expect(c.combined_estimate_usd).toBeNull();expect(c.indicative_budget_if_B_costs_as_A_usd).toBeCloseTo(.021504);expect(c.max_evaluations).toBe(64);expect(c.scenarios.map(s=>s.reviews)).toEqual([100,500,1000]);expect(compactCostPreview({input_tokens:800000,output_tokens:100000,reviews:100,input_rate:.042,output_rate:0},{A:3,B:2}).planned_calls).toBe(59)})
 it('paired 64 single tasks and replay scores negative/positive, uncertain excluded, all themes/axes',async()=>{const f=await syntheticCompact('done'),c=f.comparison!;expect(c.coverage.paired_reviews).toBe(32);expect(c.A.uncertain_labels).toBe(1);expect(c.A.negative.f1).toBe(1);expect(c.B.negative.fn).toBe(3);expect(c.A.positive.f1).toBe(1);expect(c.degraded_themes.length).toBeGreaterThan(0);expect(Object.keys(c.A.themes)).toHaveLength(25);expect(Object.keys(c.B.axes)).toHaveLength(4);expect(c.bootstrap.negative.resamples).toBe(2000);expect(c.cost_savings).toBeCloseTo(.5);expect(c.input_token_savings).toBeCloseTo(.5);expect(c.A.repeat_stability).toBeNull()})
 it('paid actions rejected without authorization even if client confirms; GET never auto-prepares',async()=>{const f=await syntheticCompact(),repo={read:vi.fn(async()=>f),configurations:vi.fn(async()=>f.configurations),inventory:vi.fn(async()=>f.inventory),costBasis:vi.fn(async()=>({input_tokens:800000,output_tokens:100000,reviews:100,input_rate:.042,output_rate:0})),prepare:vi.fn(),importTexts:vi.fn(),importReferences:vi.fn(),seal:vi.fn(),start:vi.fn()},handler=compactHandler(async()=>repo);expect((await handler(new Request('https://fixture'))).status).toBe(200);expect(repo.prepare).not.toHaveBeenCalled();expect(repo.start).not.toHaveBeenCalled();const r=await handler(new Request('https://fixture',{method:'POST',body:JSON.stringify({action:'start',confirm_cost:true})}));expect(await r.json()).toEqual({error:'COMPACT_PAID_NOT_AUTHORIZED'});expect(repo.start).not.toHaveBeenCalled()})
 it('new SQL dedicated org roles, 64 maximum, one attempt, locking, no seeded labels/authorization/run',()=>{const dir=join(process.cwd(),'supabase/migrations'),sql=readFileSync(join(dir,readdirSync(dir).find(n=>n.endsWith('_jev_compact_paired_preparation.sql'))!),'utf8');expect(sql).toContain('enable row level security');expect(sql).toContain('pg_advisory_xact_lock');expect(sql).toContain('COMPACT_PAID_NOT_AUTHORIZED');expect(sql).toContain('check(retry_count=0)');expect(sql).toContain('check(repeat=1)');expect(sql).toContain("p_values->>'request_count'");expect(sql).not.toMatch(/update public\.analysis_jev_economy_configurations|insert into public\.analysis_jev_compact_authorizations|update public\.historical|update public\.review_translations/);expect(sql).toContain('compact_used_review_ids');expect(sql).toContain('for update skip locked limit 8')})
 it('API unauthorized cannot read data, config drift fails before any action',async()=>{const auth=compactHandler(async()=>{throw new Error('FORBIDDEN')});expect((await auth(new Request('https://fixture'))).status).toBe(403);const f=await syntheticCompact();f.configurations[0].config_sha256='bad';const handler=compactHandler(async()=>({configurations:async()=>f.configurations}) as never);expect(await (await handler(new Request('https://fixture'))).json()).toEqual({error:'COMPACT_CONFIG_CHANGED'})})
})
