// @vitest-environment node
import {it,expect,vi,afterEach} from 'vitest'
import {syntheticNegative,completeNegative,syntheticNegativeTasks,negativeDecision} from '../../../tests/fixtures/negative-validation'
import {processNegativeValidation} from './negative-validation-worker'
import {NEGATIVE_MODEL_CONFIG} from './negative-validation-score'
import {THEME_KEYS} from './jev-themes'
const calls=vi.hoisted(()=>({jev:vi.fn(),peak:0,active:0}))
vi.mock('./jev.ts',async original=>({...await original<object>(),createJevClient:(_key:string,o:{onAttempt:()=>void;onUsage:(u:object,m:string)=>void})=>({evaluatePayload:async(p:{questions:Record<string,{instructions:string}>},parse:(r:unknown)=>unknown)=>{calls.active++;calls.peak=Math.max(calls.peak,calls.active);try{calls.jev(p);await Promise.resolve();o.onAttempt();o.onUsage({input_tokens:100,output_tokens:10},'jev-test');return parse({model:'jev-test',usage:{input_tokens:100,output_tokens:10},answers:Object.fromEntries(THEME_KEYS.map(k=>[k,{type:'choice',...negativeDecision(['temperature','wait_time']).themes[k]}]))})}finally{calls.active--}}})}))
afterEach(()=>{vi.unstubAllGlobals();vi.clearAllMocks();calls.active=0;calls.peak=0})
it('server persists192 paid task outcomes at max8, resumes without re-evaluation, zero OpenAI and text-only English input',async()=>{const h=await syntheticNegative(),labels=await completeNegative(h),tasks=syntheticNegativeTasks(h);tasks.forEach(t=>{t.status='pending';t.response=null});h.run.benchmark_status='running';h.run.benchmark_started_at=new Date().toISOString();let result:unknown=null
 const rpc=vi.fn(async(name:string,p:Record<string,unknown>)=>{if(name==='claim_negative_validation_tasks'){const next=tasks.filter(t=>t.status==='pending').slice(0,8);next.forEach(t=>t.status='running');return {data:structuredClone(next),error:null}}if(name==='complete_negative_validation_task'){Object.assign(tasks.find(t=>t.id===p.p_task)!,p.p_values);return {data:true,error:null}}if(name==='finish_negative_validation_tick'){if(p.p_comparison)result=p.p_comparison;return {data:true,error:null}}throw new Error('unexpected write')})
 const seen:string[]=[],db={rpc,from:(table:string)=>{seen.push(table);return {select(){return this},eq(){return this},order(){return this},single:async()=>({data:{model_config:NEGATIVE_MODEL_CONFIG},error:null}),range:async(start:number,end:number)=>({data:(table==='analysis_negative_validation_reviews'?h.items:table==='analysis_negative_validation_labels'?labels:tasks).slice(start,end+1),error:null})}}};vi.stubGlobal('Deno',{env:{get:(key:string)=>key==='TYPESAFE_API_KEY'?'fixture-key':undefined}})
 expect(await processNegativeValidation(db as never,h.run,'worker')).toMatchObject({status:'running'});expect(calls.jev).toHaveBeenCalledTimes(192);expect(calls.peak).toBeLessThanOrEqual(8);expect(calls.jev.mock.calls.every(c=>Object.keys(c[0].state).sort().join(',')==='analysis_text,review_alias')).toBe(true);expect(JSON.stringify(calls.jev.mock.calls.map(c=>c[0].state))).not.toMatch(/rating|choices|human|ORIGINAL_PRIVATE/)
 expect(await processNegativeValidation(db as never,h.run,'worker')).toMatchObject({status:'completed'});expect(calls.jev).toHaveBeenCalledTimes(192);expect(result).toMatchObject({openai_calls:0,sol_calls:0,coverage:{complete:true,common_assessed:32}});expect(seen.every(t=>t.startsWith('analysis_negative_validation_'))).toBe(true)
})
