import {GOLD_KEYS,GOLD_CHOICES,GOLD_TAXONOMY,type GoldChoice,type GoldTheme} from './gold-taxonomy.ts'
import {normalizeReviewLanguage} from './review-language.ts'
import {normalizeCategoryRatings} from './cross-rating-analysis.ts'
export const NEGATIVE_ESTABLISHMENT='252a8dca-14c7-4f09-bd1f-7b2c40ae97aa',NEGATIVE_NAME='artisan-negative-validation-v1',NEGATIVE_METHOD='independent_negative_mixed_validation',NEGATIVE_VERSION='negative-validation-v1'
export const NEGATIVE_BUCKETS={low:20,mixed:8,control:4} as const
export type NegativeBucket=keyof typeof NEGATIVE_BUCKETS
export const HUMAN_RUBRIC_VERSION='human-aligned-review-rubric-v1'
// Human product rules, authored independently of predictions. The old Gold taxonomy is untouched.
export const HUMAN_RUBRIC={...GOLD_TAXONOMY,
  attentiveness:{...GOLD_TAXONOMY.attentiveness,definition_fr:'Attention et prise en charge du client, disponibilité, réactivité, aide utile, personnel attentionné ou bienveillant. Une appréciation claire de la façon dont le personnel s’occupe des clients suffit ; une vérification de table précise n’est pas obligatoire. La sympathie seule ne suffit pas.',definition_vi:'Sự quan tâm, chăm sóc khách, sẵn sàng hỗ trợ, phản hồi nhanh, giúp ích, chu đáo hoặc tận tâm. Đánh giá rõ về cách nhân viên chăm sóc khách là đủ; không bắt buộc có hành động kiểm tra bàn. Thân thiện đơn thuần chưa đủ.'},
  professionalism:{...GOLD_TAXONOMY.professionalism,definition_fr:'Qualité de réalisation du service, aide utile ou attitude de service clairement évaluée : excellent service, exécution capable, démonstration ou assistance utile au client. Les mots professionnel/expert ne sont pas obligatoires. « Serveuse très gentille » seul ne crée pas ce thème.',definition_vi:'Chất lượng thực hiện dịch vụ, hỗ trợ hữu ích hoặc thái độ phục vụ được đánh giá rõ: dịch vụ xuất sắc, xử lý có năng lực, hướng dẫn hoặc giúp ích cho khách. Không bắt buộc có từ chuyên nghiệp/chuyên gia. Chỉ « cô phục vụ rất dễ thương » không tạo chủ đề này.'},
  coordination:{...GOLD_TAXONOMY.coordination,definition_fr:'Organisation et bonne exécution du service. Une appréciation du bon/excellent service peut exprimer l’organisation globale. La rapidité seule relève d’abord de l’attente et ne suffit pas automatiquement.',definition_vi:'Tổ chức và thực hiện dịch vụ tốt. Nhận xét dịch vụ tốt/xuất sắc có thể thể hiện sự tổ chức tổng thể. Nhanh đơn thuần chủ yếu thuộc thời gian chờ và không tự động đủ.'},
  communication:{...GOLD_TAXONOMY.communication,definition_fr:'Explication, information, compréhension/incompréhension, écoute, échange ou problème linguistique concernant une interaction avec le client. « Ils parlent russe » seul est absent. Sympathie, aide, rapidité ou bon service seuls ne créent pas ce thème.',definition_vi:'Giải thích, thông tin, hiểu/không hiểu, lắng nghe, trao đổi hoặc vấn đề ngôn ngữ trong tương tác với khách. Chỉ « họ nói tiếng Nga » là không có. Thân thiện, giúp đỡ, nhanh hoặc dịch vụ tốt đơn thuần không tạo chủ đề này.'},
} as const
export interface NegativeCandidate {id:string;rating:number;original_text:string|null;original_language:string|null;published_at?:string|null;review_detailed_rating:Record<string,unknown>|null;review_translations:{language:string;translated_text:string}[]}
export interface NegativePoolRow {review_id:string;overall_rating:number;selection_bucket:NegativeBucket;selection_hash:string;original_language:string|null;original_text_sha256:string;published_at:string|null;normalized_category_ratings:ReturnType<typeof normalizeCategoryRatings>}
export interface NegativeReview extends NegativePoolRow {position:number;original_language:string|null;original_text_sha256:string;analysis_text:string|null;analysis_language:'en'|null;analysis_source:'original_en'|'google_translation_en'|'english_pending';analysis_text_sha256:string|null;normalized_category_ratings:ReturnType<typeof normalizeCategoryRatings>;published_at:string|null;excluded:boolean;exclusion_reason?:string|null;confirmed_at?:string|null;preparation_error:string|null}
export interface NegativeLabel {review_id:string;theme_key:GoldTheme;choice:GoldChoice}
export interface NegativeRun {id:string;organization_id:string;establishment_id:string;name:string;methodology:string;status:'draft'|'completed';revision:number;benchmark_status:'idle'|'queued'|'running'|'completed'|'failed';rubric:typeof HUMAN_RUBRIC;rubric_version:string;selection_pool:NegativePoolRow[];reference_at:string;human_completed_at:string|null;dataset_fingerprint:string|null;label_fingerprint:string|null;created_at:string;created_by:string;benchmark_started_at:string|null;benchmark_completed_at:string|null;benchmark_error:string|null;rates:{jev_input:number};lease_until?:string|null;locked_by?:string|null}
export async function negativeHash(value:string){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return Array.from(new Uint8Array(b),n=>n.toString(16).padStart(2,'0')).join('')}
export const negativeBucket=(rating:number):NegativeBucket|null=>rating>=1&&rating<=3?'low':rating===4?'mixed':rating===5?'control':null
export function strictEnglish(r:NegativeCandidate){const language=normalizeReviewLanguage(r.original_language);if(language==='en'&&r.original_text?.trim())return {analysis_text:r.original_text,analysis_language:'en' as const,analysis_source:'original_en' as const};const t=r.review_translations.find(t=>normalizeReviewLanguage(t.language)==='en'&&t.translated_text?.trim());return t?{analysis_text:t.translated_text,analysis_language:'en' as const,analysis_source:'google_translation_en' as const}:{analysis_text:null,analysis_language:null,analysis_source:'english_pending' as const}}
export async function negativePool(reviews:NegativeCandidate[]){const unique=new Map(reviews.map(r=>[r.id,r]));if(unique.size!==reviews.length)throw new Error('NEGATIVE_SOURCE_DUPLICATES');return await Promise.all(reviews.filter(r=>r.original_text?.trim()&&negativeBucket(r.rating)).map(async r=>({review_id:r.id,overall_rating:r.rating,selection_bucket:negativeBucket(r.rating)!,selection_hash:await negativeHash(NEGATIVE_ESTABLISHMENT+NEGATIVE_VERSION+r.id),original_language:r.original_language,original_text_sha256:await negativeHash(r.original_text!),published_at:r.published_at??null,normalized_category_ratings:normalizeCategoryRatings(r.review_detailed_rating)})))}
export async function freezeNegativeReview(r:NegativeCandidate,pool:NegativePoolRow,position:number):Promise<NegativeReview>{if(await negativeHash(r.original_text??'')!==pool.original_text_sha256||r.original_language!==pool.original_language)throw new Error('NEGATIVE_REPLACEMENT_SOURCE_CHANGED');const en=strictEnglish(r);return {...pool,position,...en,analysis_text_sha256:en.analysis_text?await negativeHash(en.analysis_text):null,excluded:false,confirmed_at:null,preparation_error:en.analysis_text?null:'ENGLISH_TRANSLATION_MISSING'}}
export async function selectNegativeReviews(reviews:NegativeCandidate[]){const pool=(await negativePool(reviews)).sort((a,b)=>a.selection_hash.localeCompare(b.selection_hash)||a.review_id.localeCompare(b.review_id)),byId=new Map(reviews.map(r=>[r.id,r])),selected:NegativePoolRow[]=[]
  for(const [bucket,count] of Object.entries(NEGATIVE_BUCKETS)){const group=pool.filter(p=>p.selection_bucket===bucket);if(group.length<count)throw new Error('NEGATIVE_POOL_INSUFFICIENT');selected.push(...group.slice(0,count))}
  // Hash presentation order also hides stratification during annotation.
  selected.sort((a,b)=>a.selection_hash.localeCompare(b.selection_hash)||a.review_id.localeCompare(b.review_id))
  return {pool,items:await Promise.all(selected.map((p,i)=>freezeNegativeReview(byId.get(p.review_id)!,p,i+1)))}
}
export function negativeCoverage(items:NegativeReview[]){const active=items.filter(r=>!r.excluded),ready=active.filter(r=>r.analysis_text?.trim()&&r.analysis_language==='en'&&['original_en','google_translation_en'].includes(r.analysis_source)&&r.analysis_text_sha256);return {selected:active.length,ready:ready.length,missing:active.length-ready.length,percent:active.length?ready.length/active.length*100:0,missing_reviews:active.filter(r=>!ready.includes(r)).map(r=>({review_id:r.review_id,cause:r.preparation_error??'ENGLISH_TRANSLATION_MISSING'}))}}
export async function verifyNegativeItems(run:NegativeRun,items:NegativeReview[],requireEnglish=false){const active=items.filter(i=>!i.excluded);if(run.establishment_id!==NEGATIVE_ESTABLISHMENT||run.name!==NEGATIVE_NAME||run.methodology!==NEGATIVE_METHOD||run.rubric_version!==HUMAN_RUBRIC_VERSION||active.length!==32||new Set(items.map(i=>i.review_id)).size!==items.length||new Set(active.map(i=>i.position)).size!==32)throw new Error('NEGATIVE_DATASET_INVALID');for(const [bucket,n] of Object.entries(NEGATIVE_BUCKETS))if(active.filter(i=>i.selection_bucket===bucket).length!==n)throw new Error('NEGATIVE_STRATA_CHANGED');for(const i of active){const source=run.selection_pool.find(p=>p.review_id===i.review_id);if(!source||source.selection_hash!==i.selection_hash||source.overall_rating!==i.overall_rating||source.selection_bucket!==i.selection_bucket)throw new Error('NEGATIVE_SELECTION_CHANGED');if(i.analysis_text!==null&&(i.analysis_language!=='en'||!['original_en','google_translation_en'].includes(i.analysis_source)||!i.analysis_text.trim()||await negativeHash(i.analysis_text)!==i.analysis_text_sha256))throw new Error('NEGATIVE_TEXT_CHANGED')}if(requireEnglish&&negativeCoverage(active).ready!==32)throw new Error('NEGATIVE_ENGLISH_REQUIRED')}
export async function fillNegativeEnglish(items:NegativeReview[],live:NegativeCandidate[]){const updates:Partial<NegativeReview>[]=[];for(const row of items.filter(i=>!i.excluded&&i.analysis_text===null)){const r=live.find(r=>r.id===row.review_id);if(!r){updates.push({review_id:row.review_id,preparation_error:'SOURCE_REVIEW_MISSING'});continue}if(await negativeHash(r.original_text??'')!==row.original_text_sha256||r.original_language!==row.original_language){updates.push({review_id:row.review_id,preparation_error:'ORIGINAL_SOURCE_CHANGED'});continue}const en=strictEnglish(r);updates.push({review_id:row.review_id,...en,analysis_text_sha256:en.analysis_text?await negativeHash(en.analysis_text):null,preparation_error:en.analysis_text?null:'ENGLISH_TRANSLATION_MISSING'})}return updates}
export async function negativeReplacement(run:NegativeRun,items:NegativeReview[],id:string,live:NegativeCandidate[]){const previous=items.find(i=>i.review_id===id&&!i.excluded);if(!previous)throw new Error('NEGATIVE_REVIEW_NOT_ACTIVE');const used=new Set(items.map(i=>i.review_id)),next=[...run.selection_pool].filter(p=>p.selection_bucket===previous.selection_bucket&&!used.has(p.review_id)).sort((a,b)=>a.selection_hash.localeCompare(b.selection_hash)||a.review_id.localeCompare(b.review_id))[0];if(!next)throw new Error('NEGATIVE_REPLACEMENT_UNAVAILABLE');const r=live.find(r=>r.id===next.review_id);if(!r?.original_text?.trim())throw new Error('NEGATIVE_REPLACEMENT_SOURCE_MISSING');return freezeNegativeReview(r,next,previous.position)}
export function negativeChoices(raw:Record<string,unknown>):Record<GoldTheme,GoldChoice>{if(Object.keys(raw).some(k=>!GOLD_KEYS.includes(k as GoldTheme))||Object.values(raw).some(v=>!GOLD_CHOICES.includes(v as GoldChoice)))throw new Error('NEGATIVE_CHOICES_INVALID');return Object.fromEntries(GOLD_KEYS.map(k=>[k,raw[k]??'absent'])) as Record<GoldTheme,GoldChoice>}
export async function negativeFingerprints(items:NegativeReview[],labels:NegativeLabel[]){const active=items.filter(i=>!i.excluded).sort((a,b)=>a.position-b.position),ids=new Set(active.map(i=>i.review_id)),truth=labels.filter(l=>ids.has(l.review_id)).sort((a,b)=>a.review_id.localeCompare(b.review_id)||a.theme_key.localeCompare(b.theme_key));if(truth.length!==800||new Set(truth.map(l=>l.review_id+':'+l.theme_key)).size!==800||truth.some(l=>!GOLD_CHOICES.includes(l.choice))||active.some(i=>!i.confirmed_at||GOLD_KEYS.some(k=>!truth.some(l=>l.review_id===i.review_id&&l.theme_key===k))))throw new Error('NEGATIVE_ANNOTATION_INCOMPLETE');return {dataset_fingerprint:await negativeHash(JSON.stringify(active.map(i=>({review_id:i.review_id,position:i.position,overall_rating:i.overall_rating,analysis_text_sha256:i.analysis_text_sha256,analysis_source:i.analysis_source,normalized_category_ratings:i.normalized_category_ratings,published_at:i.published_at})))),label_fingerprint:await negativeHash(JSON.stringify(truth.map(l=>({review_id:l.review_id,theme_key:l.theme_key,choice:l.choice}))))}}
