import {NEGATIVE_ESTABLISHMENT,NEGATIVE_NAME,NEGATIVE_METHOD,HUMAN_RUBRIC,HUMAN_RUBRIC_VERSION,selectNegativeReviews,verifyNegativeItems,negativeCoverage,fillNegativeEnglish,negativeReplacement,negativeChoices,negativeFingerprints,type NegativeCandidate,type NegativeRun,type NegativeReview,type NegativeLabel} from './negative-validation-core.ts'
import {NEGATIVE_MODEL_CONFIG,type NegativeTask,compareNegativeValidation} from './negative-validation-score.ts'
export type NegativeComparison=Awaited<ReturnType<typeof compareNegativeValidation>>
export interface NegativeRepository {user:string;get:(id?:string)=>Promise<NegativeRun|null>;live:()=>Promise<NegativeCandidate[]>;items:(id:string)=>Promise<NegativeReview[]>;labels:(id:string)=>Promise<NegativeLabel[]>;tasks:(id:string)=>Promise<NegativeTask[]>;result:(id:string)=>Promise<NegativeComparison|null>;backfill:()=>Promise<{id:string;status:string;error_code:string|null;provider_requests:number}|null>;create:(payload:Record<string,unknown>)=>Promise<string>;write:(id:string,revision:number,action:string,payload:Record<string,unknown>)=>Promise<void>;configured:()=>boolean}
export function negativeProjection(run:NegativeRun|null,items:NegativeReview[],labels:NegativeLabel[],result:NegativeComparison|null,annotation:boolean,backfill:Awaited<ReturnType<NegativeRepository['backfill']>>){const coverage=negativeCoverage(items),allowAnnotation=run?.status==='draft'&&coverage.ready===32,completed=items.filter(i=>!i.excluded&&i.confirmed_at&&labels.filter(l=>l.review_id===i.review_id).length===25).length
  return {eligible:true,run:run?{id:run.id,status:run.status,benchmark_status:run.benchmark_status,revision:run.revision,completed_reviews:completed,reference_at:run.reference_at,created_at:run.created_at,human_completed_at:run.human_completed_at,benchmark_started_at:run.benchmark_started_at,benchmark_completed_at:run.benchmark_completed_at,benchmark_error:run.benchmark_error}:null,coverage,rubric:run?.rubric??HUMAN_RUBRIC,backfill,
    items:annotation&&allowAnnotation?items.filter(i=>!i.excluded).sort((a,b)=>a.position-b.position).map(i=>({review_id:i.review_id,position:i.position,analysis_text:i.analysis_text!,confirmed_at:i.confirmed_at??null,choices:Object.fromEntries(labels.filter(l=>l.review_id===i.review_id).map(l=>[l.theme_key,l.choice])) as Partial<Record<keyof typeof HUMAN_RUBRIC,import('./gold-taxonomy.ts').GoldChoice>>})):[],
    ...(run?.status==='completed'&&run.benchmark_status==='completed'&&result?{comparison:result,error_texts:Object.fromEntries(items.filter(i=>!i.excluded).map(i=>[i.review_id,i.analysis_text]))}:{})}
}
const headers={'Content-Type':'application/json','Cache-Control':'no-store','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'GET, POST, OPTIONS'},json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers}),uuid=(v:unknown)=>typeof v==='string'&&/^[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12}$/i.test(v)
export function negativeValidationHandler(authenticate:(r:Request)=>Promise<NegativeRepository>){return async(request:Request)=>{if(request.method==='OPTIONS')return new Response('ok',{headers});if(!['GET','POST'].includes(request.method))return json({error:'METHOD_NOT_ALLOWED'},405)
  try{const repo=await authenticate(request),params=new URL(request.url).searchParams,body=request.method==='POST'?await request.json():null,id=body?.experiment_id??params.get('experiment_id');if(id&&!uuid(id))throw new Error('NEGATIVE_ID_INVALID');let run=await repo.get(id??undefined)
    if(request.method==='POST'){
      if(body?.action==='create'){if(!run){const selection=await selectNegativeReviews(await repo.live()),created=await repo.create({p_user:repo.user,p_pool:selection.pool,p_items:selection.items,p_rubric:HUMAN_RUBRIC,p_config:NEGATIVE_MODEL_CONFIG});run=await repo.get(created)}}
      else{if(!run)throw new Error('NEGATIVE_NOT_FOUND');const items=await repo.items(run.id);await verifyNegativeItems(run,items);if(run.status==='completed'&&body?.action!=='start_benchmark')throw new Error('NEGATIVE_HUMAN_IMMUTABLE');if(!Number.isInteger(body?.revision)||body.revision!==run.revision)throw new Error('NEGATIVE_REVISION_CHANGED');let payload:Record<string,unknown>
        if(body.action==='refresh_english'){payload={updates:await fillNegativeEnglish(items,await repo.live())}}
        else if(body.action==='confirm_review'){await verifyNegativeItems(run,items,true);if(!items.some(i=>i.review_id===body.review_id&&!i.excluded)||!body.choices||typeof body.choices!=='object'||Array.isArray(body.choices))throw new Error('NEGATIVE_CHOICES_INVALID');payload={review_id:body.review_id,choices:negativeChoices(body.choices)}}
        else if(body.action==='exclude_review'){if(body.confirm!==true)throw new Error('NEGATIVE_CONFIRMATION_REQUIRED');payload={review_id:body.review_id,replacement:await negativeReplacement(run,items,body.review_id,await repo.live())}}
        else if(body.action==='finalize_human'){if(body.confirm!==true)throw new Error('NEGATIVE_CONFIRMATION_REQUIRED');await verifyNegativeItems(run,items,true);payload=await negativeFingerprints(items,await repo.labels(run.id))}
        else if(body.action==='start_benchmark'){if(run.status!=='completed')throw new Error('NEGATIVE_HUMAN_REQUIRED');await verifyNegativeItems(run,items,true);const fp=await negativeFingerprints(items,await repo.labels(run.id));if(fp.dataset_fingerprint!==run.dataset_fingerprint||fp.label_fingerprint!==run.label_fingerprint)throw new Error('NEGATIVE_INTEGRITY_CHANGED');if(run.benchmark_status!=='idle'){payload={reuse:true}}else{if(!repo.configured())throw new Error('JEV_NOT_CONFIGURED');payload={}}}
        else throw new Error('NEGATIVE_ACTION_INVALID');if(!(body.action==='start_benchmark'&&run.benchmark_status!=='idle'))await repo.write(run.id,run.revision,body.action,payload);run=await repo.get(run.id)
      }
    }
    const backfill=await repo.backfill();if(!run)return json(negativeProjection(null,[],[],null,false,backfill));const [items,labels,result]=await Promise.all([repo.items(run.id),repo.labels(run.id),run.benchmark_status==='completed'?repo.result(run.id):Promise.resolve(null)]);await verifyNegativeItems(run,items);return json(negativeProjection(run,items,labels,result,request.method==='POST'||params.get('view')==='annotation',backfill))
  }catch(e){const code=e instanceof Error&&/^[A-Z0-9_]+$/.test(e.message)?e.message:'NEGATIVE_REQUEST_FAILED';return json({error:code},code==='UNAUTHORIZED'?401:code==='FORBIDDEN'?403:code==='NEGATIVE_NOT_FOUND'?404:code==='RATE_LIMITED'?429:code==='JEV_NOT_CONFIGURED'?409:/(IMMUTABLE|REVISION_CHANGED|INTEGRITY_CHANGED|TEXT_CHANGED)/.test(code)?409:code.startsWith('NEGATIVE_')&&!code.endsWith('_FAILED')?400:500)}
}}
export const NEGATIVE_IDENTITY={establishment_id:NEGATIVE_ESTABLISHMENT,name:NEGATIVE_NAME,methodology:NEGATIVE_METHOD,rubric_version:HUMAN_RUBRIC_VERSION}
