import {THEME_KEYS,themePresence,type ThemeDecision,type ThemeKey} from './jev-themes.ts'
import {themePayload} from './jev-themes.ts'
import {benchmarkPayload,type SystemOnePayload} from './jev.ts'
import {v11Payload,v11Threshold,meetsV11Threshold,V11_QUESTION_SET,V11_THRESHOLD_VERSION,V11_THRESHOLDS} from './jev-v11-calibration.ts'
import {GOLD_KEYS,GOLD_TAXONOMY,type GoldChoice,type GoldTheme} from './gold-taxonomy.ts'
import {negativeHash,negativeFingerprints,type NegativeReview,type NegativeLabel,type NegativeRun} from './negative-validation-core.ts'
import {crossRatingAnalysis} from './cross-rating-analysis.ts'
export const NEGATIVE_MODEL_CONFIG={v9:{question_set:'themes_phase2_v7',threshold:.50,repeat_count:3},v11:{question_set:V11_QUESTION_SET,threshold_version:V11_THRESHOLD_VERSION,thresholds:V11_THRESHOLDS,repeat_count:3},concurrency:8,requested_model:'jev-latest',macro_min_support:3} as const
export type NegativeVersion='v9'|'v11'
export const NEGATIVE_PRIORITY_THEMES:GoldTheme[]=['food_quality','freshness','cooking','cleanliness','wait_time','attentiveness','professionalism','communication','coordination','value','price_level','billing']
export interface NegativeTask {id:string;experiment_id:string;model_version:NegativeVersion;review_id:string;review_alias:string;question_set_version:string;repeat:number;status:'pending'|'running'|'completed'|'failed';response:ThemeDecision|null;served_model:string|null;input_tokens:number;output_tokens:number;request_count:number;retry_count:number;cost_usd:number;duration_ms:number;error_code:string|null;usage_complete:boolean}
export function negativePayload(version:NegativeVersion,alias:string,text:string):SystemOnePayload{return version==='v9'?benchmarkPayload(themePayload('jev-latest',alias,text),7):v11Payload('themes',alias,text)}
export function negativePrediction(tasks:NegativeTask[],reviewId:string,theme:ThemeKey,version:NegativeVersion){const reps=[1,2,3].map(n=>tasks.find(t=>t.model_version===version&&t.review_id===reviewId&&t.repeat===n));if(reps.some(t=>t?.status!=='completed'||!t.response?.themes[theme]))return null;const answers=reps.map(t=>t!.response!.themes[theme]),p=answers.map(themePresence),positive=p.reduce((n,a)=>n+a.positive_presence_probability,0)/3,negative=p.reduce((n,a)=>n+a.negative_presence_probability,0)/3,yesP=version==='v9'?positive>=.50:meetsV11Threshold(positive,v11Threshold(theme,'positive')),yesN=version==='v9'?negative>=.50:meetsV11Threshold(negative,v11Threshold(theme,'negative'));return {choice:(yesP?yesN?'both':'positive':yesN?'negative':'absent') as Exclude<GoldChoice,'uncertain'>,positive,negative,stable:new Set(answers.map(a=>a.choice)).size===1}}
type Counts={tp:number;tn:number;fp:number;fn:number;support:number;uncertain:number}
const empty=():Counts=>({tp:0,tn:0,fp:0,fn:0,support:0,uncertain:0})
const sum=(rows:Counts[])=>rows.reduce((a,b)=>({tp:a.tp+b.tp,tn:a.tn+b.tn,fp:a.fp+b.fp,fn:a.fn+b.fn,support:a.support+b.support,uncertain:a.uncertain+b.uncertain}),empty())
export const negativeMetrics=(c:Counts)=>({...c,precision:c.tp+c.fp?c.tp/(c.tp+c.fp):null,recall:c.support?c.tp/c.support:null,f1:c.support?2*c.tp/(2*c.tp+c.fp+c.fn):null})
const has=(choice:GoldChoice,polarity:'positive'|'negative')=>choice===polarity||choice==='both'
export function negativeModelScores(ids:string[],labels:NegativeLabel[],tasks:NegativeTask[],version:NegativeVersion){const truth=new Map(labels.map(l=>[l.review_id+':'+l.theme_key,l.choice])),themes=Object.fromEntries(GOLD_KEYS.map(k=>[k,{positive:empty(),negative:empty()}])),perReview:{overall:Counts;negative:Counts}[]=[],errors:{review_id:string;theme_key:GoldTheme;kind:'missed_negative'|'false_positive_negative';human:GoldChoice;predicted:GoldChoice}[]=[],exact={same:0,total:0};let stable=0,pairs=0
  for(const id of ids){const all=empty(),neg=empty();for(const theme of GOLD_KEYS){const h=truth.get(id+':'+theme),prediction=negativePrediction(tasks,id,theme,version);if(!h)throw new Error('NEGATIVE_LABELS_INCOMPLETE');if(!prediction)throw new Error('NEGATIVE_PREDICTIONS_INCOMPLETE');pairs++;if(prediction.stable)stable++;if(h==='uncertain'){themes[theme].positive.uncertain++;themes[theme].negative.uncertain++;continue}exact.total++;if(h===prediction.choice)exact.same++
    for(const polarity of ['positive','negative'] as const){const c=themes[theme][polarity],human=has(h,polarity),pred=has(prediction.choice,polarity),key=pred?human?'tp':'fp':human?'fn':'tn';c[key]++;all[key]++;if(polarity==='negative')neg[key]++;if(human){c.support++;all.support++;if(polarity==='negative')neg.support++}if(polarity==='negative'&&(key==='fp'||key==='fn'))errors.push({review_id:id,theme_key:theme,kind:key==='fn'?'missed_negative':'false_positive_negative',human:h,predicted:prediction.choice})}
  }perReview.push({overall:all,negative:neg})}
  const positives=GOLD_KEYS.map(k=>themes[k].positive),negatives=GOLD_KEYS.map(k=>themes[k].negative),all=[...positives,...negatives],macro=all.filter(c=>c.support>=3).map(c=>negativeMetrics(c).f1!).filter(n=>n!==null)
  return {overall:negativeMetrics(sum(all)),negative:negativeMetrics(sum(negatives)),positive:negativeMetrics(sum(positives)),micro_f1:negativeMetrics(sum(all)).f1,macro_f1:macro.length?macro.reduce((a,b)=>a+b,0)/macro.length:null,macro_supported_labels:macro.length,exact_choice_agreement:exact.total?exact.same/exact.total:null,exact_compared:exact.total,repeat_choice_stability:pairs?stable/pairs:null,themes:Object.fromEntries(GOLD_KEYS.map(k=>[k,{positive:negativeMetrics(themes[k].positive),negative:negativeMetrics(themes[k].negative)}])),axes:Object.fromEntries(['quality','service','atmosphere','price'].map(axis=>{const keys=GOLD_KEYS.filter(k=>GOLD_TAXONOMY[k].axis===axis);return [axis,{negative:negativeMetrics(sum(keys.map(k=>themes[k].negative))),positive:negativeMetrics(sum(keys.map(k=>themes[k].positive)))}]})),errors,perReview}
}
export async function negativeBootstrap(id:string,a:ReturnType<typeof negativeModelScores>,b:ReturnType<typeof negativeModelScores>,kind:'overall'|'negative',complete:boolean){const seed=await negativeHash(id);let state=parseInt(seed.slice(0,8),16)||1;const random=()=>{state^=state<<13;state^=state>>>17;state^=state<<5;return (state>>>0)/4294967296},distribution:number[]=[];let undefinedSamples=0;const reviews=a.perReview.length,supportReviews=a.perReview.filter(r=>r[kind].support>0).length
  for(let n=0;n<2000;n++){const left:Counts[]=[],right:Counts[]=[];for(let i=0;i<reviews;i++){const j=Math.floor(random()*reviews);left.push(a.perReview[j][kind]);right.push(b.perReview[j][kind])}const x=negativeMetrics(sum(left)).f1,y=negativeMetrics(sum(right)).f1;if(x===null||y===null)undefinedSamples++;else distribution.push(y-x)}distribution.sort((a,b)=>a-b);const calculable=complete&&supportReviews>=3&&undefinedSamples===0&&distribution.length===2000,x=a[kind].f1,y=b[kind].f1,low=calculable?distribution[Math.floor((distribution.length-1)*.025)]:null,high=calculable?distribution[Math.floor((distribution.length-1)*.975)]:null
  return {method:'review_level_paired_bootstrap',resamples:2000,seed_sha256:seed,support_reviews:supportReviews,valid_resamples:distribution.length,undefined_resamples:undefinedSamples,delta:x===null||y===null?null:y-x,ci_95_low:low,ci_95_high:high,conclusion:low===null||high===null?'inconclusive':low>0?'v11_higher_on_this_sample':high<0?'v9_higher_on_this_sample':'inconclusive'}
}
export async function compareNegativeValidation(run:NegativeRun,items:NegativeReview[],labels:NegativeLabel[],tasks:NegativeTask[]){const rows=items.filter(r=>!r.excluded).sort((a,b)=>a.position-b.position),ids=rows.map(r=>r.review_id),fp=await negativeFingerprints(items,labels);if(fp.dataset_fingerprint!==run.dataset_fingerprint||fp.label_fingerprint!==run.label_fingerprint)throw new Error('NEGATIVE_INTEGRITY_CHANGED')
  const available=(version:NegativeVersion)=>ids.filter(id=>THEME_KEYS.every(theme=>negativePrediction(tasks,id,theme,version)!==null)),v9Available=available('v9'),v11Available=available('v11'),common=ids.filter(id=>v9Available.includes(id)&&v11Available.includes(id)),complete=common.length===32,a=negativeModelScores(common,labels,tasks,'v9'),b=negativeModelScores(common,labels,tasks,'v11'),{perReview:_a,...v9}=a,{perReview:_b,...v11}=b;void _a;void _b
  const usage=(version:NegativeVersion)=>{const own=tasks.filter(t=>t.model_version===version),latencies=own.filter(t=>t.request_count>0).map(t=>t.duration_ms).sort((a,b)=>a-b),models=[...new Set(own.flatMap(t=>t.served_model?[t.served_model]:[]))].sort();return {served_models:models,input_tokens:own.reduce((n,t)=>n+t.input_tokens,0),output_tokens:own.reduce((n,t)=>n+t.output_tokens,0),estimated_cost_usd:own.reduce((n,t)=>n+t.cost_usd,0),requests:own.reduce((n,t)=>n+t.request_count,0),retries:own.reduce((n,t)=>n+t.retry_count,0),request_elapsed_sum_ms:own.reduce((n,t)=>n+t.duration_ms,0),latency:{p50_ms:latencies.length?latencies[Math.ceil(latencies.length*.50)-1]:null,p95_ms:latencies.length?latencies[Math.ceil(latencies.length*.95)-1]:null,max_ms:latencies.at(-1)??null},usage_complete:own.every(t=>t.usage_complete),errors:own.filter(t=>t.status==='failed').map(t=>({review_id:t.review_id,repeat:t.repeat,error_code:t.error_code}))}}
  const jevUsage={v9:usage('v9'),v11:usage('v11')},modelsDifferent=JSON.stringify(jevUsage.v9.served_models)!==JSON.stringify(jevUsage.v11.served_models)||Object.values(jevUsage).some(u=>u.served_models.length>1)
  const googleReviews=rows.filter(r=>common.includes(r.review_id)).map(r=>({id:r.review_id,rating:r.overall_rating,analysis_text:r.analysis_text??undefined,normalized_category_ratings:r.normalized_category_ratings})),findings=(version:NegativeVersion| 'human')=>googleReviews.flatMap(r=>GOLD_KEYS.flatMap(theme=>{const choice=version==='human'?labels.find(l=>l.review_id===r.id&&l.theme_key===theme)!.choice:negativePrediction(tasks,r.id,theme,version)!.choice;return choice==='uncertain'?[]:(['positive','negative'] as const).filter(p=>has(choice,p)).map(sentiment=>({review_id:r.id,theme_key:theme,sentiment,evidence:null}))})),google={human:crossRatingAnalysis(googleReviews,findings('human')),v9:crossRatingAnalysis(googleReviews,findings('v9')),v11:crossRatingAnalysis(googleReviews,findings('v11'))}
  return {name:run.name,methodology:run.methodology,rubric_version:run.rubric_version,sample_reviews:32,strata:{low:rows.filter(r=>r.selection_bucket==='low').length,mixed:rows.filter(r=>r.selection_bucket==='mixed').length,control:rows.filter(r=>r.selection_bucket==='control').length},reference_at:run.reference_at,end_to_end_elapsed_ms:run.benchmark_started_at&&run.benchmark_completed_at?Date.parse(run.benchmark_completed_at)-Date.parse(run.benchmark_started_at):null,priority_themes:NEGATIVE_PRIORITY_THEMES,period_start:rows.map(r=>r.published_at).filter((s):s is string=>!!s).sort()[0]??null,period_end:rows.map(r=>r.published_at).filter((s):s is string=>!!s).sort().at(-1)??null,integrity:{...fp,identical_review_ids:true,identical_analysis_text_hashes:true,identical_human_labels:true},coverage:{common_assessed:common.length,v9_assessed:v9Available.length,v11_assessed:v11Available.length,complete,unavailable_review_ids:ids.filter(id=>!common.includes(id))},human_negative_support_full:labels.filter(l=>ids.includes(l.review_id)&&has(l.choice,'negative')).length,config:NEGATIVE_MODEL_CONFIG,v9,v11,bootstrap:{negative:await negativeBootstrap(run.id,a,b,'negative',complete),overall:await negativeBootstrap(run.id,a,b,'overall',complete)},usage:jevUsage,model_version_confounded:modelsDifferent,google_cross_rating:google,openai_calls:0,sol_calls:0,sample_warning:'Star-stratified sample overrepresents low ratings; evaluates criticism detection, not restaurant problem prevalence. Labels use English text only. Google ratings are descriptive, never human truth.'}
}
