import type {SupabaseClient} from 'npm:@supabase/supabase-js@2.117.2'
import {createJevClient} from './jev.ts'
import {parseThemes} from './jev-themes.ts'
import {negativePayload,compareNegativeValidation,NEGATIVE_MODEL_CONFIG,type NegativeTask} from './negative-validation-score.ts'
import {verifyNegativeItems,negativeFingerprints,type NegativeRun,type NegativeReview,type NegativeLabel} from './negative-validation-core.ts'
const safe=(e:unknown)=>e instanceof Error&&/^[A-Z0-9_]+$/.test(e.message)?e.message:'NEGATIVE_NETWORK_ERROR'
export async function processNegativeValidation(admin:SupabaseClient,run:NegativeRun,worker:string){const started=Date.now(),rpc=async(name:string,args:Record<string,unknown>)=>{const {data,error}=await admin.rpc(name,args);if(error)throw new Error(error.message.includes('NEGATIVE_LEASE_LOST')?'NEGATIVE_LEASE_LOST':'NEGATIVE_SAVE_FAILED');return data},finish=async(comparison:unknown=null,error:string|null=null)=>{if(await rpc('finish_negative_validation_tick',{p_id:run.id,p_worker:worker,p_comparison:comparison,p_error:error})!==true)throw new Error('NEGATIVE_LEASE_LOST')}
  async function rows(table:string){const all=[];for(let offset=0;;offset+=500){let q=admin.from(table).select('*').eq('experiment_id',run.id);q=table==='analysis_negative_validation_labels'?q.order('review_id').order('theme_key'):table==='analysis_negative_validation_reviews'?q.order('review_id'):q.order('id');const {data,error}=await q.range(offset,offset+499);if(error)throw new Error('NEGATIVE_READ_FAILED');all.push(...data??[]);if((data?.length??0)<500)break}return all}
  try{
    if(run.status!=='completed'||run.benchmark_status!=='running')throw new Error('NEGATIVE_HUMAN_REQUIRED')
    const {data:configuration,error}=await admin.from('analysis_negative_validation_runs').select('model_config').eq('id',run.id).eq('organization_id',run.organization_id).single();if(error||!configuration)throw new Error('NEGATIVE_READ_FAILED');const config=configuration.model_config,expected=NEGATIVE_MODEL_CONFIG;if(config.v9?.question_set!==expected.v9.question_set||config.v9?.threshold!==.5||config.v9?.repeat_count!==3||config.v11?.question_set!==expected.v11.question_set||config.v11?.threshold_version!==expected.v11.threshold_version||config.v11?.repeat_count!==3||config.concurrency!==8||config.requested_model!=='jev-latest'||Object.keys(config.v11.thresholds??{}).length!==25||Object.entries(expected.v11.thresholds).some(([k,v])=>config.v11.thresholds[k]?.positive_threshold!==v.positive_threshold||config.v11.thresholds[k]?.negative_threshold!==v.negative_threshold))throw new Error('NEGATIVE_CONFIG_CHANGED')
    const [items,labels]=await Promise.all([rows('analysis_negative_validation_reviews') as Promise<NegativeReview[]>,rows('analysis_negative_validation_labels') as Promise<NegativeLabel[]>]);await verifyNegativeItems(run,items,true);const fp=await negativeFingerprints(items,labels);if(fp.dataset_fingerprint!==run.dataset_fingerprint||fp.label_fingerprint!==run.label_fingerprint)throw new Error('NEGATIVE_INTEGRITY_CHANGED')
    const key=Deno.env.get('TYPESAFE_API_KEY');if(!key?.trim())throw new Error('JEV_NOT_CONFIGURED');let processed=0
    while(Date.now()-started<70_000){const tasks=await rpc('claim_negative_validation_tasks',{p_id:run.id,p_worker:worker}) as NegativeTask[];if(!tasks.length)break;if(tasks.length>8)throw new Error('NEGATIVE_CONCURRENCY_INVALID');const outcomes=await Promise.allSettled(tasks.map(async t=>{const review=items.find(i=>i.review_id===t.review_id&&!i.excluded);if(!review?.analysis_text||t.question_set_version!==NEGATIVE_MODEL_CONFIG[t.model_version].question_set)throw new Error('NEGATIVE_TASK_SOURCE_INVALID');let input=0,output=0,requests=0,retries=0,model:string|null=null,response:unknown=null,errorCode:string|null=null,complete=true;const begin=Date.now(),client=createJevClient(key,{onUsage:(u,m)=>{input+=u.input_tokens;output+=u.output_tokens;model=m},onAttempt:()=>requests++,onRetry:()=>retries++});try{const result=await client.evaluatePayload(negativePayload(t.model_version,t.review_alias,review.analysis_text),parseThemes);response=result.decision;model=result.model}catch(e){errorCode=safe(e);if(['JEV_NETWORK_ERROR','JEV_INVALID_USAGE','JEV_INVALID_RESPONSE'].includes(errorCode))complete=false}
      if(await rpc('complete_negative_validation_task',{p_id:run.id,p_worker:worker,p_task:t.id,p_values:{status:errorCode?'failed':'completed',response,served_model:model,input_tokens:input,output_tokens:output,request_count:requests,retry_count:retries,duration_ms:Date.now()-begin,error_code:errorCode,usage_complete:complete}})!==true)throw new Error('NEGATIVE_LEASE_LOST');processed++;console.info('NEGATIVE_JEV_TASK_COMPLETED',{experiment_id:run.id,model_version:t.model_version,repeat:t.repeat,review_alias:t.review_alias,error_code:errorCode})}));const failed=outcomes.find(o=>o.status==='rejected');if(failed?.status==='rejected')throw failed.reason}
    if(processed){await finish();return {experiment_id:run.id,status:'running'}}
    const tasks=await rows('analysis_negative_validation_tasks') as NegativeTask[];if(tasks.some(t=>['pending','running'].includes(t.status))){await finish();return {experiment_id:run.id,status:'running'}}
    const comparison=await compareNegativeValidation({...run,benchmark_completed_at:new Date().toISOString()},items,labels,tasks);await finish({...comparison,end_to_end_elapsed_ms:run.benchmark_started_at?Date.now()-Date.parse(run.benchmark_started_at):null});return {experiment_id:run.id,status:'completed'}
  }catch(e){const code=safe(e);console.warn('NEGATIVE_VALIDATION_ERROR',{experiment_id:run.id,code});if(code!=='NEGATIVE_LEASE_LOST')try{await finish(null,code)}catch{/* A lost paid response remains unavailable, never re-enqueued. */}return {experiment_id:run.id,status:'error',error_code:code}}
}
