// @vitest-environment node
import {it,expect} from 'vitest'
import {readFileSync} from 'node:fs'
import {syntheticNegativeCandidates,syntheticNegative,completeNegative,syntheticNegativeTasks,negativeDecision} from '../../../tests/fixtures/negative-validation'
import {selectNegativeReviews,negativeCoverage,strictEnglish,negativeReplacement,fillNegativeEnglish,negativeChoices,verifyNegativeItems,negativeFingerprints} from './negative-validation-core'
import {negativePayload,negativePrediction,negativeModelScores,compareNegativeValidation,negativeBootstrap} from './negative-validation-score'
import {v9Payload} from './historical-v9-core'
import {v11Payload} from './jev-v11-calibration'
it('32 unique reviews, exact20/8/4, deterministic hash selection unaffected by stars within the same group or metadata/English availability',async()=>{const source=syntheticNegativeCandidates(),a=await selectNegativeReviews(source);expect(a.items).toHaveLength(32);expect(new Set(a.items.map(i=>i.review_id)).size).toBe(32);expect(a.items.filter(i=>i.selection_bucket==='low')).toHaveLength(20);expect(a.items.filter(i=>i.selection_bucket==='mixed')).toHaveLength(8);expect(a.items.filter(i=>i.selection_bucket==='control')).toHaveLength(4);source.reverse();source.forEach(r=>{r.review_detailed_rating={Food:1};r.review_translations=[];if(r.rating<=3)r.rating=1});expect((await selectNegativeReviews(source)).items.map(i=>i.review_id)).toEqual(a.items.map(i=>i.review_id));expect(a.items.every(i=>i.review_id!==source.find(r=>!r.original_text)?.id)).toBe(true)})
it('strict English only:originalEN, verifiedEN translation; no FR/VI/original non-English fallback',()=>{const r=syntheticNegativeCandidates(false)[0];expect(strictEnglish(r).analysis_text).toBeNull();r.original_language='en-US';expect(strictEnglish(r).analysis_source).toBe('original_en');r.original_language='ru';r.review_translations=[{language:'en',translated_text:'English'}];expect(strictEnglish(r)).toMatchObject({analysis_text:'English',analysis_source:'google_translation_en'});r.review_translations=[{language:'vi',translated_text:'Not English'}];expect(strictEnglish(r).analysis_text).toBeNull()})
it('English fill changes only pending items, never IDs or frozen text; missing originals are explicit',async()=>{const h=await syntheticNegative(),old=h.items[0].analysis_text;h.items[1].analysis_text=null;h.items[1].analysis_language=null;h.items[1].analysis_source='english_pending';h.items[1].analysis_text_sha256=null;expect(negativeCoverage(h.items)).toMatchObject({selected:32,ready:31,missing:1});await expect(verifyNegativeItems(h.run,h.items,true)).rejects.toThrow('ENGLISH_REQUIRED');const updates=await fillNegativeEnglish(h.items,h.live);expect(updates).toHaveLength(1);expect(h.items[0].analysis_text).toBe(old);h.live.find(r=>r.id===h.items[1].review_id)!.original_text='changed';expect((await fillNegativeEnglish(h.items,h.live))[0].preparation_error).toBe('ORIGINAL_SOURCE_CHANGED')})
it('translation exclusion replacement stays in same original stratum and stable pool, never filters by model or English availability',async()=>{const h=await syntheticNegative(),old=h.items[0],n=await negativeReplacement(h.run,h.items,old.review_id,h.live);expect(n.selection_bucket).toBe(old.selection_bucket);expect(n.position).toBe(old.position);expect(h.items.some(i=>i.review_id===n.review_id)).toBe(false);expect(n.overall_rating).toBe(h.run.selection_pool.find(i=>i.review_id===n.review_id)!.overall_rating)})
it('unselected choices become absent only on explicit review validation, both/uncertain retained; all800 labels required',async()=>{const h=await syntheticNegative();expect(Object.keys(negativeChoices({professionalism:'both',communication:'uncertain'}))).toHaveLength(25);expect(negativeChoices({professionalism:'both'}).food_quality).toBe('absent');await expect(negativeFingerprints(h.items,[])).rejects.toThrow('INCOMPLETE');const labels=await completeNegative(h);expect(labels).toHaveLength(800);expect(h.run.dataset_fingerprint).toHaveLength(64)})
it('V9 and V11 exact existing question sets, same text-only payload and three averaged repetitions',async()=>{expect(negativePayload('v9','r1','English')).toEqual(v9Payload('themes','r1','English'));expect(negativePayload('v11','r1','English')).toEqual(v11Payload('themes','r1','English'));expect(Object.keys(negativePayload('v11','r1','English').questions)).toHaveLength(25);expect(Object.keys(negativePayload('v11','r1','English').state)).toEqual(['review_alias','analysis_text']);const h=await syntheticNegative(),tasks=syntheticNegativeTasks(h),own=tasks.filter(t=>t.review_id===h.items[0].review_id);for(const t of own){t.response=negativeDecision([]);t.response.themes.professionalism={choice:'negative',probabilities:{absent:.21,positive:0,negative:.79,both:0}}}expect(negativePrediction(tasks,h.items[0].review_id,'professionalism','v9')?.choice).toBe('negative');expect(negativePrediction(tasks,h.items[0].review_id,'professionalism','v11')?.choice).toBe('absent')})
it('negative precision/recall/F1 exclude TNs, null support never produces100%, uncertain excluded',async()=>{const h=await syntheticNegative(),labels=await completeNegative(h),tasks=syntheticNegativeTasks(h),ids=h.items.map(i=>i.review_id),a=negativeModelScores(ids,labels,tasks,'v9'),b=negativeModelScores(ids,labels,tasks,'v11');expect(a.negative).toMatchObject({tp:32,fn:32,fp:0,support:64,precision:1,recall:.5});expect(a.negative.f1).toBeCloseTo(2/3);expect(b.negative.f1).toBe(1);expect(a.axes.price.negative.f1).toBeNull();expect(a.axes.atmosphere.negative.f1).toBeNull();labels.find(l=>l.review_id===ids[0]&&l.theme_key==='wait_time')!.choice='uncertain';expect(negativeModelScores(ids,labels,tasks,'v9').negative.support).toBe(63)})
it('paired bootstrap is deterministic by review, supports negative and overall, absent negatives inconclusive',async()=>{const h=await syntheticNegative(),labels=await completeNegative(h),tasks=syntheticNegativeTasks(h),ids=h.items.map(i=>i.review_id),a=negativeModelScores(ids,labels,tasks,'v9'),b=negativeModelScores(ids,labels,tasks,'v11'),one=await negativeBootstrap(h.run.id,a,b,'negative',true),two=await negativeBootstrap(h.run.id,a,b,'negative',true);expect(one).toEqual(two);expect(one).toMatchObject({resamples:2000,valid_resamples:2000,support_reviews:32});expect(one.delta).toBeCloseTo(1/3);expect(one.ci_95_low).toBeCloseTo(1/3);expect((await negativeBootstrap(h.run.id,a,b,'negative',false)).ci_95_low).toBeNull()})
it('no human negative labels gives null F1 and an inconclusive CI, regardless of negative predictions',async()=>{const h=await syntheticNegative(),labels=await completeNegative(h);labels.forEach(l=>l.choice='absent');const tasks=syntheticNegativeTasks(h),ids=h.items.map(i=>i.review_id),a=negativeModelScores(ids,labels,tasks,'v9'),b=negativeModelScores(ids,labels,tasks,'v11');expect(a.negative.f1).toBeNull();expect(b.negative.f1).toBeNull();const ci=await negativeBootstrap(h.run.id,a,b,'negative',true);expect(ci.delta).toBeNull();expect(ci.ci_95_low).toBeNull();expect(ci.conclusion).toBe('inconclusive')})
it('Google Service2 with no textual human Service label remains unexplained, never creates a complaint',async()=>{const h=await syntheticNegative(),labels=await completeNegative(h);labels.filter(l=>l.theme_key==='wait_time').forEach(l=>l.choice='absent');Object.assign(h.run,await negativeFingerprints(h.items,labels));const c=await compareNegativeValidation(h.run,h.items,labels,syntheticNegativeTasks(h));expect(c.google_cross_rating.human.axes.service.low_score_unexplained_count).toBe(32);expect(c.google_cross_rating.human.axes.service.confirmed_negative_count).toBe(0)})
it('same frozen IDs/hashes/labels for both versions, fair coverage and no Google-created human findings',async()=>{const h=await syntheticNegative(),labels=await completeNegative(h),tasks=syntheticNegativeTasks(h);h.run.benchmark_status='running';const before=JSON.stringify(h),c=await compareNegativeValidation(h.run,h.items,labels,tasks);expect(c.coverage).toMatchObject({complete:true,common_assessed:32});expect(c.strata).toEqual({low:20,mixed:8,control:4});expect(c.google_cross_rating.human.axes.service.confirmed_negative_count).toBe(32);expect(c.openai_calls).toBe(0);expect(JSON.stringify(h)).toBe(before);tasks[0].status='failed';const partial=await compareNegativeValidation(h.run,h.items,labels,tasks);expect(partial.coverage.common_assessed).toBe(31);expect(partial.bootstrap.negative.ci_95_low).toBeNull();expect(partial.v9.negative.support).toBe(62)})
it('no report/Gold/benchmark/source writes, no OpenAI provider route, no auto Apify or benchmark enqueue',()=>{const worker=readFileSync('supabase/functions/_shared/negative-validation-worker.ts','utf8'),api=readFileSync('supabase/functions/negative-review-validation/index.ts','utf8');expect(worker+api).not.toMatch(/structuredCall|api\.openai|consultantNarrative|extractConsultantBatch|startApifyRun/);expect(worker).not.toContain("from('historical_report_runs')");expect(api).not.toMatch(/from\('reviews'\)\.(insert|update|delete|upsert)/)})
