// @vitest-environment node
import {it,expect,vi} from 'vitest'
import {negativeValidationHandler,negativeProjection,type NegativeRepository} from './negative-validation-api'
import {syntheticNegative,completeNegative,syntheticNegativeTasks} from '../../../tests/fixtures/negative-validation'
import {negativeChoices,negativeFingerprints,type NegativeLabel} from './negative-validation-core'
async function harness(){const h=await syntheticNegative();let exists=false,labels:NegativeLabel[]=[];const repo:NegativeRepository={user:h.run.created_by,get:vi.fn(async()=>exists?h.run:null),live:vi.fn(async()=>h.live),items:async()=>h.items,labels:async()=>labels,tasks:async()=>syntheticNegativeTasks(h),result:async()=>null,backfill:async()=>null,configured:()=>true,create:vi.fn(async()=>{exists=true;return h.run.id}),write:vi.fn(async(_id,_rev,action,p)=>{if(action==='confirm_review'){labels=labels.filter(l=>l.review_id!==p.review_id);labels.push(...Object.entries(negativeChoices(p.choices as Record<string,unknown>)).map(([theme_key,choice])=>({review_id:p.review_id,theme_key,choice}) as NegativeLabel));h.items.find(i=>i.review_id===p.review_id)!.confirmed_at='2026-10-08T00:00:00Z'}else if(action==='finalize_human'){h.run.status='completed';Object.assign(h.run,p)}else if(action==='start_benchmark')h.run.benchmark_status='queued';h.run.revision++})},handler=negativeValidationHandler(async()=>repo),call=(body?:Record<string,unknown>,q='?view=annotation')=>handler(new Request('https://fixture.test'+q,body?{method:'POST',body:JSON.stringify(body)}:undefined));return {...h,repo,call,setLabels:(l:NegativeLabel[])=>{labels=l},exists:()=>{exists=true}}}
it('GET never creates/selects/provider-calls; create manual and idempotent',async()=>{const h=await harness();expect((await h.call()).status).toBe(200);expect(h.repo.live).not.toHaveBeenCalled();expect(h.repo.create).not.toHaveBeenCalled();await h.call({action:'create'});await h.call({action:'create'});expect(h.repo.create).toHaveBeenCalledTimes(1);expect(h.repo.live).toHaveBeenCalledTimes(1)})
it('annotation projection exposes only English text/own labels, never stars, selection or either model',async()=>{const h=await harness();await h.call({action:'create'});const data=await (await h.call()).json(),text=JSON.stringify(data.items);expect(data.items).toHaveLength(32);expect(text).not.toMatch(/overall_rating|normalized_category|original_language|selection_bucket|selection_hash|model_version|probabil|ORIGINAL_PRIVATE/);expect(data).not.toHaveProperty('comparison');expect(data).not.toHaveProperty('error_texts')})
it('32/32 English required server-side before any annotation, pending rows return no annotation texts',async()=>{const h=await harness();await h.call({action:'create'});h.items[0].analysis_text=null;h.items[0].analysis_text_sha256=null;h.items[0].analysis_language=null;h.items[0].analysis_source='english_pending';const data=await (await h.call()).json();expect(data.items).toEqual([]);expect(data.coverage.ready).toBe(31);expect((await h.call({action:'confirm_review',revision:0,review_id:h.items[1].review_id,choices:{}})).status).toBe(400);expect(h.repo.write).not.toHaveBeenCalled()})
it('validation saves25 explicit choices including absent defaults, resume GET retains them',async()=>{const h=await harness();await h.call({action:'create'});const d=await (await h.call({action:'confirm_review',revision:0,review_id:h.items[0].review_id,choices:{temperature:'negative',food_quality:'both',attentiveness:'uncertain'}})).json();expect(Object.keys(d.items[0].choices)).toHaveLength(25);expect(d.items[0].choices).toMatchObject({temperature:'negative',food_quality:'both',attentiveness:'uncertain',billing:'absent'});expect(d.run.completed_reviews).toBe(1);expect((await (await h.call()).json()).items[0].choices).toEqual(d.items[0].choices)})
it('human finalize needs32 validated reviews and confirmation; never starts benchmark; completed immutable',async()=>{const h=await harness();await h.call({action:'create'});expect((await h.call({action:'finalize_human',revision:0,confirm:true})).status).toBe(400);h.setLabels(await completeNegative(h));h.run.status='draft';expect((await h.call({action:'finalize_human',revision:0})).status).toBe(400);expect((await h.call({action:'finalize_human',revision:0,confirm:true})).status).toBe(200);expect(h.run.benchmark_status).toBe('idle');expect((await h.call({action:'confirm_review',revision:1,review_id:h.items[0].review_id,choices:{}})).status).toBe(409)})
it('benchmark requires completed human truth, explicit click; duplicate launch only reuses queued job',async()=>{const h=await harness();await h.call({action:'create'});expect((await h.call({action:'start_benchmark',revision:0})).status).toBe(400);h.setLabels(await completeNegative(h));Object.assign(h.run,await negativeFingerprints(h.items,await h.repo.labels(h.run.id)));expect((await h.call({action:'start_benchmark',revision:0})).status).toBe(200);expect(h.run.benchmark_status).toBe('queued');expect((await h.call({action:'start_benchmark',revision:1})).status).toBe(200);expect(h.repo.write).toHaveBeenCalledTimes(1);expect(negativeProjection(h.run,h.items,[],null,true,null)).not.toHaveProperty('comparison')})
it('anonymous/unauthorized rejected and private failures sanitized',async()=>{for(const [code,status] of [['UNAUTHORIZED',401],['FORBIDDEN',403],['SECRET_SENTINEL',500]] as const){const r=await negativeValidationHandler(async()=>{throw new Error(code==='SECRET_SENTINEL'?'private body with text':code)})(new Request('https://fixture'));expect(r.status).toBe(status);expect(await r.text()).not.toContain('private body')}})
