import {buildEvidenceAudit,evidenceAuditHash} from './pilot-evidence-audit.ts'
import type {EvidenceRecord} from './pilot-evidence-api.ts'
import {verifyPilotSnapshot,type PilotSnapshot,PILOT_AXES} from './jev-pilot-core.ts'
import type {PilotJob} from './jev-pilot-types.ts'
import type {EconomyCache} from './jev-economy-cache.ts'
import type {AuditedEvidence} from './pilot-evidence-audit.ts'
import {EVIDENCE_V21_RULES,EVIDENCE_V21_VERSION,EVIDENCE_V21_VERIFIER,verifyEvidenceV21,evidenceV21RuleHash,type EvidenceV21Check} from './pilot-evidence-v21-rules.ts'
import {negativeHash} from './negative-validation-core.ts'
import {canonicalJson} from './jev-exploratory-core.ts'
export interface EvidenceV21Binding extends Omit<AuditedEvidence,'status'|'reason'|'excerpt'>,EvidenceV21Check {v2_binding_id:string;v2_status:string}
export interface EvidenceV21Audit {version:typeof EVIDENCE_V21_VERSION;verifier:typeof EVIDENCE_V21_VERIFIER;rule_sha256:string;base_audit_id:string;base_result_sha256:string;snapshot_id:string;report_id:string;source_sha256:string;prediction_source_sha256:string;checks:EvidenceV21Binding[];selected:EvidenceV21Binding[];comparison:{v2:{supported:number;review_needed:number};v21:{supported:number;unsupported:number;review_needed:number};retained_supported:number;newly_supported:number;previously_supported_excluded:number;previously_supported_pending:number;selected_retained:number;changes:EvidenceV21Binding[]};summary:{jev_reviews:number;jev_findings:number;supported:number;unsupported:number;review_needed:number;selected:number;grounded_recommendations:number;old_recommendations_fully_grounded:number};recommendation_requirements:{axis:string;proof_ids:string[]}[];old_recommendations:EvidenceRecord['result']['recommendations'];statistics:EvidenceRecord['result']['source_context']['topics'];new_paid_calls:0;production_enabled:false;human_validated:false;ai_verified:false}
export const evidenceV21AuditHash=(a:EvidenceV21Audit)=>negativeHash(canonicalJson(a))
export async function buildEvidenceV21(snapshot:PilotSnapshot,report:PilotJob,cache:(EconomyCache&{theme_results?:unknown})[],base:EvidenceRecord):Promise<EvidenceV21Audit>{
 if(await evidenceAuditHash(base.result)!==base.result_sha256||await evidenceAuditHash(await buildEvidenceAudit(snapshot,report,cache))!==base.result_sha256)throw new Error('EVIDENCE_V21_BASE_CHANGED');
 const checks=await Promise.all(base.result.checks.map(async old=>{const r=snapshot.source.reviews.find(r=>r.id===old.review_id)!;const v=verifyEvidenceV21(r.analysis_text!,old.theme_key,old.polarity);return {...old,...v,binding_id:await negativeHash(canonicalJson({version:EVIDENCE_V21_VERSION,review_id:old.review_id,key:old.key,analysis_text_sha256:old.analysis_text_sha256})),quote_sha256:v.excerpt?await negativeHash(v.excerpt.quote):null,v2_binding_id:old.binding_id,v2_status:old.status} satisfies EvidenceV21Binding}));
 const selected:EvidenceV21Binding[]=[];for(const old of base.result.selected){const c=checks.find(c=>c.v2_binding_id===old.binding_id)!,r=snapshot.source.reviews.find(r=>r.id===old.review_id)!;const independent=verifyEvidenceV21(old.excerpt!.quote,old.theme_key,old.polarity);if(c.status!=='supported_by_rule'||independent.status!=='supported_by_rule'||r.analysis_text!.slice(old.excerpt!.start,old.excerpt!.end)!==old.excerpt!.quote)throw new Error('EVIDENCE_V21_PINNED_PROOF_INVALID');c.excerpt={...old.excerpt!,rule_id:independent.excerpt!.rule_id,claim:independent.excerpt!.claim};c.quote_sha256=old.quote_sha256;selected.push(c)}
 const supported=checks.filter(c=>c.status==='supported_by_rule').length,unsupported=checks.filter(c=>c.status==='unsupported_by_rule').length,review_needed=checks.filter(c=>c.status==='review_needed').length,old_recommendations=base.result.recommendations;
 return {version:EVIDENCE_V21_VERSION,verifier:EVIDENCE_V21_VERIFIER,rule_sha256:await evidenceV21RuleHash(),base_audit_id:base.id,base_result_sha256:base.result_sha256,snapshot_id:snapshot.id,report_id:report.id,source_sha256:snapshot.source_sha256,prediction_source_sha256:base.result.prediction_source_sha256,checks,selected,comparison:{v2:{supported:base.result.summary.supported,review_needed:base.result.summary.review_needed},v21:{supported,unsupported,review_needed},retained_supported:checks.filter(c=>c.v2_status==='supported_by_rule'&&c.status==='supported_by_rule').length,newly_supported:checks.filter(c=>c.v2_status==='review_needed'&&c.status==='supported_by_rule').length,previously_supported_excluded:checks.filter(c=>c.v2_status==='supported_by_rule'&&c.status==='unsupported_by_rule').length,previously_supported_pending:checks.filter(c=>c.v2_status==='supported_by_rule'&&c.status==='review_needed').length,selected_retained:selected.length,changes:checks.filter(c=>c.v2_status!==c.status)},summary:{jev_reviews:base.result.summary.jev_reviews,jev_findings:base.result.summary.jev_findings,supported,unsupported,review_needed,selected:selected.length,grounded_recommendations:PILOT_AXES.filter(axis=>selected.some(s=>s.axis===axis)).length,old_recommendations_fully_grounded:old_recommendations.filter(r=>r.status==='supported_by_rule').length},old_recommendations,recommendation_requirements:PILOT_AXES.map(axis=>({axis,proof_ids:selected.filter(p=>p.axis===axis).map(p=>p.binding_id)})),statistics:base.result.source_context.topics,new_paid_calls:0,production_enabled:false,human_validated:false,ai_verified:false}
}
export function recommendationFromEvidenceV21(audit:EvidenceV21Audit,axis:string,language:'fr'|'vi'){const required=audit.recommendation_requirements.find(r=>r.axis===axis)?.proof_ids??[],missing=required.filter(id=>!audit.selected.some(p=>p.binding_id===id&&p.status==='supported_by_rule')||!audit.checks.some(c=>c.binding_id===id&&c.status==='supported_by_rule'&&c.excerpt&&c.quote_sha256));if(!required.length)missing.push('NO_EXPLICIT_EVIDENCE');const used=audit.selected.filter(p=>required.includes(p.binding_id)&&!missing.includes(p.binding_id)),rules=used.map(p=>EVIDENCE_V21_RULES.find(r=>r.id===p.excerpt?.rule_id));if(rules.some(r=>!r))missing.push('RULE_NOT_FOUND');return {axis,required_evidence_ids:required,missing_evidence_ids:missing,status:missing.length?'review_needed' as const:'grounded_by_rules' as const,interpretation:rules.filter(r=>r!==undefined).map(r=>language==='fr'?r.statement_fr:r.statement_vi),actions:missing.length?[]:rules.map(r=>language==='fr'?r!.recommendation_fr:r!.recommendation_vi),proofs:used.map(p=>({id:p.binding_id,review_id:p.review_id,key:p.key,quote:p.excerpt!.quote,quote_sha256:p.quote_sha256}))}}
export async function previewEvidenceV21(snapshot:PilotSnapshot,base:EvidenceRecord,audit:EvidenceV21Audit,sha:string,language:'fr'|'vi'){
 await verifyPilotSnapshot(snapshot);if(await evidenceV21AuditHash(audit)!==sha||await evidenceV21RuleHash()!==audit.rule_sha256||await evidenceAuditHash(base.result)!==base.result_sha256||audit.base_result_sha256!==base.result_sha256||audit.base_audit_id!==base.id||audit.source_sha256!==snapshot.source_sha256||audit.selected.length!==base.result.selected.length||new Set(audit.selected.map(p=>p.v2_binding_id)).size!==base.result.selected.length)throw new Error('EVIDENCE_V21_CHANGED');
 for(const p of audit.selected){const old=base.result.selected.find(c=>c.binding_id===p.v2_binding_id),r=snapshot.source.reviews.find(r=>r.id===p.review_id);if(!old||!r?.analysis_text||p.status!=='supported_by_rule'||p.theme_key!==old.theme_key||p.polarity!==old.polarity||p.axis!==old.axis||canonicalJson(audit.checks.find(c=>c.binding_id===p.binding_id))!==canonicalJson(p)||p.key!==old.key||p.review_id!==old.review_id||p.analysis_text_sha256!==r.analysis_text_sha256||p.quote_sha256!==old.quote_sha256||p.excerpt?.quote!==old.excerpt!.quote||r.analysis_text.slice(p.excerpt.start,p.excerpt.end)!==p.excerpt.quote||await negativeHash(p.excerpt.quote)!==p.quote_sha256||verifyEvidenceV21(p.excerpt.quote,p.theme_key,p.polarity).status!=='supported_by_rule')throw new Error('EVIDENCE_V21_PROOF_CHANGED')}
 const recommendations=PILOT_AXES.map(axis=>recommendationFromEvidenceV21(audit,axis,language));return {statistics:{source:'historical_jev_predictions',counts_unchanged:true,jev_reviews:audit.summary.jev_reviews,jev_findings:audit.summary.jev_findings,themes:audit.statistics},evidence:{source:'deterministic_text_rules_not_independent_validation',selected:audit.selected},interpretation_and_recommendations:{source:'closed_rule_catalog',recommendations},can_generate_report:false as const,new_paid_calls:0 as const}
}
