import {auditPilotCache,pilotStatistics,verifyPilotSnapshot,PILOT_AXES,type PilotSnapshot} from './jev-pilot-core.ts'
import type {PilotJob} from './jev-pilot-types.ts'
import type {EconomyCache} from './jev-economy-cache.ts'
import {canonicalJson} from './jev-exploratory-core.ts'
import {negativeHash} from './negative-validation-core.ts'
import {pilotNarrativeHash,type PilotNarrativeContext} from './jev-pilot-narrative.ts'
import {EVIDENCE_VERSION,EVIDENCE_VERIFIER,EVIDENCE_RULES,evidenceRuleHash,verifyExplicitEvidence,type EvidenceCheck,type EvidencePolarity} from './pilot-evidence-rules.ts'
import {THEME_KEYS,type ThemeKey} from './jev-themes.ts'
import {GOLD_TAXONOMY} from './gold-taxonomy.ts'

export interface AuditedEvidence extends EvidenceCheck {binding_id:string;review_id:string;theme_key:ThemeKey;polarity:EvidencePolarity;key:string;axis:string;analysis_text_sha256:string;cache_id:string;cache_response_sha256:string;quote_sha256:string|null;served_model:string;analysis_source:string}
export interface EvidenceAudit {version:typeof EVIDENCE_VERSION;verifier:typeof EVIDENCE_VERIFIER;rule_sha256:string;snapshot_id:string;source_sha256:string;report_id:string;report_sha256:string;prediction_source_sha256:string;source_fingerprints:{cache_id:string;sha256:string}[];source_context:PilotNarrativeContext;checks:AuditedEvidence[];selected:AuditedEvidence[];previous:{review_id:string;key:string;status:string;reason:string;claim:string|null}[];recommendations:{position:number;text:string;status:'review_needed'|'supported_by_rule';reasons:string[]}[];summary:{jev_reviews:number;jev_findings:number;checked:number;supported:number;review_needed:number;previous_bindings:number;previous_supported:number;previous_review_needed:number;selected:number;unsupported_recommendations:number};counts_unchanged:true;independent_human_validation:false;new_paid_calls:0;production_enabled:false}
export const evidenceAuditHash=(a:EvidenceAudit)=>negativeHash(canonicalJson(a))
const hash=(v:unknown)=>negativeHash(canonicalJson(v))
const findingKey=(f:{review_id:string;theme_key:string;sentiment?:string;polarity?:string})=>`${f.review_id}:${f.theme_key}:${f.sentiment??f.polarity}`
export async function buildEvidenceAudit(snapshot:PilotSnapshot,report:PilotJob,cache:(EconomyCache&{theme_results?:unknown})[]):Promise<EvidenceAudit>{
 await verifyPilotSnapshot(snapshot);
 const source=report.input_context.narrative_input as PilotNarrativeContext,oldStats=report.input_context.statistics as ReturnType<typeof pilotStatistics>,result=report.result as {prose:{recommendations:{text:string;supporting_keys:string[];evidence_review_ids:string[]}[]};source_sha256:string};
 if(report.snapshot_id!==snapshot.id||report.organization_id!==snapshot.organization_id||report.stage!=='sol'||report.status!=='completed'||!source||source.snapshot_sha256!==snapshot.source_sha256||result?.source_sha256!==snapshot.source_sha256||await pilotNarrativeHash(source)!==report.input_sha256)throw new Error('EVIDENCE_REPORT_BINDING_CHANGED');
 const historicalCache=cache.filter(c=>c.status==='completed'&&c.processed_at&&Date.parse(c.processed_at)<=Date.parse(report.created_at)),used=await auditPilotCache(snapshot.source.reviews,historicalCache,snapshot.organization_id,snapshot.establishment_id),stats=pilotStatistics(snapshot.source.reviews,used,snapshot.source.google_total_reviews);
 if(stats.coverage.analysed_reviews!==oldStats.coverage.analysed_reviews||canonicalJson(stats.findings.map(findingKey).sort())!==canonicalJson(oldStats.findings.map(findingKey).sort()))throw new Error('EVIDENCE_PREDICTION_SCOPE_CHANGED');
 const fingerprints=await Promise.all(used.used.map(async c=>({cache_id:c.id,sha256:await hash({cache_key:c.cache_key,response:c.response,theme_results:(c as EconomyCache&{theme_results:unknown}).theme_results,served_model:c.served_model})})));fingerprints.sort((a,b)=>a.cache_id.localeCompare(b.cache_id));
 const checks=await Promise.all(stats.findings.map(async f=>{const r=snapshot.source.reviews.find(r=>r.id===f.review_id)!,c=used.used.find(c=>c.review_id===f.review_id)!,v=verifyExplicitEvidence(r.analysis_text!,f.theme_key,f.sentiment),binding_id=await hash({review_id:r.id,theme_key:f.theme_key,polarity:f.sentiment,text_sha256:r.analysis_text_sha256,version:EVIDENCE_VERSION});return {...v,binding_id,review_id:r.id,theme_key:f.theme_key,polarity:f.sentiment,key:f.theme_key+':'+f.sentiment,axis:GOLD_TAXONOMY[f.theme_key].axis,analysis_text_sha256:r.analysis_text_sha256!,cache_id:c.id,cache_response_sha256:fingerprints.find(x=>x.cache_id===c.id)!.sha256,quote_sha256:v.excerpt?await negativeHash(v.excerpt.quote):null,served_model:c.served_model!,analysis_source:r.analysis_source} satisfies AuditedEvidence}));checks.sort((a,b)=>findingKey(a).localeCompare(findingKey(b)));
 const topics=[...stats.positive_topics,...stats.negative_topics],rank=(a:AuditedEvidence,b:AuditedEvidence)=>(topics.find(t=>t.key===b.key)?.mentions??0)-(topics.find(t=>t.key===a.key)?.mentions??0)||(a.excerpt?.quote.length??0)-(b.excerpt?.quote.length??0)||a.binding_id.localeCompare(b.binding_id),selected:AuditedEvidence[]=[];
 for(const axis of PILOT_AXES)for(const polarity of ['negative','positive'] as const){const candidates=checks.filter(c=>c.status==='supported_by_rule'&&c.axis===axis&&c.polarity===polarity).sort(rank);if(candidates[0])selected.push(candidates[0])}
 const previous=source.representative_evidence.flatMap(p=>p.theme_keys.map(key=>{const c=checks.find(c=>c.review_id===p.review_id&&c.key===key),r=snapshot.source.reviews.find(r=>r.id===p.review_id),validText=r?.analysis_text_sha256===p.source_sha256&&r.analysis_text?.startsWith(p.english_excerpt);return {review_id:p.review_id,key,status:validText&&c?.status==='supported_by_rule'&&p.english_excerpt.includes(c.excerpt!.quote)?'supported_by_rule':'review_needed',reason:!validText?'PREVIOUS_TEXT_HASH_OR_EXCERPT_CHANGED':!c?'PREDICTION_BINDING_NOT_FOUND':c.status==='review_needed'?c.reason:!p.english_excerpt.includes(c.excerpt!.quote)?'PREVIOUS_PREFIX_OMITS_SUPPORT':'EXPLICIT_THEME_AND_POLARITY',claim:c?.status==='supported_by_rule'?c.excerpt!.claim:null}}));
 const recommendations=(result.prose.recommendations??[]).map((r,position)=>{const reasons:string[]=[];for(const key of r.supporting_keys)if(!previous.some(p=>p.key===key&&r.evidence_review_ids.includes(p.review_id)&&p.status==='supported_by_rule'))reasons.push('THEME_WITHOUT_EXPLICIT_CITED_SUPPORT:'+key);const normalized=r.text.normalize('NFD').replace(/\p{M}/gu,'').toLowerCase();if(/\b(?:acces|access|tiep can|reachability)\b/.test(normalized)&&r.supporting_keys.includes('location:negative')&&!previous.some(p=>p.key==='location:negative'&&p.claim==='location_access'&&r.evidence_review_ids.includes(p.review_id)))reasons.push('LOCATION_ACCESS_NOT_EXPRESSED');return {position,text:r.text,status:reasons.length?'review_needed' as const:'supported_by_rule' as const,reasons}});
 return {version:EVIDENCE_VERSION,verifier:EVIDENCE_VERIFIER,rule_sha256:await evidenceRuleHash(),snapshot_id:snapshot.id,source_sha256:snapshot.source_sha256,report_id:report.id,report_sha256:await hash({input_context:report.input_context,result:report.result}),prediction_source_sha256:await hash(fingerprints),source_fingerprints:fingerprints,source_context:source,checks,selected,previous,recommendations,summary:{jev_reviews:stats.coverage.analysed_reviews,jev_findings:stats.findings.length,checked:checks.length,supported:checks.filter(c=>c.status==='supported_by_rule').length,review_needed:checks.filter(c=>c.status==='review_needed').length,previous_bindings:previous.length,previous_supported:previous.filter(c=>c.status==='supported_by_rule').length,previous_review_needed:previous.filter(c=>c.status==='review_needed').length,selected:selected.length,unsupported_recommendations:recommendations.filter(c=>c.status==='review_needed').length},counts_unchanged:true,independent_human_validation:false,new_paid_calls:0,production_enabled:false}
}

/** A second text-only gate, run before any future V2 Sol call; never trusts stored approval alone. */
export async function prepareEvidenceV2Packet(snapshot:PilotSnapshot,audit:EvidenceAudit,resultSha:string,language:'fr'|'vi'){
 await verifyPilotSnapshot(snapshot);if(audit.version!==EVIDENCE_VERSION||audit.rule_sha256!==await evidenceRuleHash()||audit.source_sha256!==snapshot.source_sha256||audit.snapshot_id!==snapshot.id||await evidenceAuditHash(audit)!==resultSha||audit.selected.length>8)throw new Error('EVIDENCE_AUDIT_CHANGED');
 for(const p of audit.selected){const r=snapshot.source.reviews.find(r=>r.id===p.review_id);if(!r?.analysis_text||r.analysis_language!=='en'||r.analysis_text_sha256!==p.analysis_text_sha256||!THEME_KEYS.includes(p.theme_key)||p.status!=='supported_by_rule'||p.key!==p.theme_key+':'+p.polarity||p.axis!==GOLD_TAXONOMY[p.theme_key].axis||canonicalJson(audit.checks.find(c=>c.binding_id===p.binding_id))!==canonicalJson(p))throw new Error('EVIDENCE_TEXT_CHANGED');const independently=verifyExplicitEvidence(r.analysis_text,p.theme_key,p.polarity);if(independently.status!=='supported_by_rule'||canonicalJson(independently.excerpt)!==canonicalJson(p.excerpt)||await negativeHash(p.excerpt!.quote)!==p.quote_sha256||r.analysis_text.slice(p.excerpt!.start,p.excerpt!.end)!==p.excerpt!.quote)throw new Error('EVIDENCE_PREFLIGHT_REJECTED')}
 const statements=audit.selected.map(p=>{const r=EVIDENCE_RULES.find(r=>r.id===p.excerpt!.rule_id)!;return {id:p.binding_id,axis:p.axis,key:p.key,claim:r.claim,statement:language==='fr'?r.statement_fr:r.statement_vi,review_id:p.review_id,english_excerpt:p.excerpt!.quote,quote_sha256:p.quote_sha256,analysis_text_sha256:p.analysis_text_sha256,rule_id:r.id}}),recommendation_catalog=audit.selected.map(p=>{const r=EVIDENCE_RULES.find(r=>r.id===p.excerpt!.rule_id)!;return {id:p.binding_id,statement_id:p.binding_id,key:p.key,review_id:p.review_id,text:language==='fr'?r.recommendation_fr:r.recommendation_vi}});
 return {version:EVIDENCE_VERSION,language,source_sha256:snapshot.source_sha256,evidence_audit_sha256:resultSha,verification:{type:'deterministic_rule_check',verifier:EVIDENCE_VERIFIER,rule_sha256:audit.rule_sha256,human_validated:false,ai_verified:false},coverage:audit.source_context.coverage,coverage_warnings:audit.source_context.coverage_warnings,counts:audit.source_context.topics.map(t=>({key:t.key,mentions:t.mentions,affected_reviews:t.affected_reviews,explicit_selected_evidence:statements.some(s=>s.key===t.key)})),google_context:audit.source_context.google_context,statements,recommendation_catalog,counts_are_jev_predictions:true,unsupported_topics_are_not_proven:true,sol_generation_enabled:false as const}
}
