import {it,expect,vi,afterEach} from 'vitest'
import {readFileSync} from 'node:fs'
import {verifyEvidenceV21,EVIDENCE_V21_RULES,evidenceV21RuleHash} from './pilot-evidence-v21-rules'
import {evidenceRuleHash} from './pilot-evidence-rules'
import {buildEvidenceV21,evidenceV21AuditHash,previewEvidenceV21,recommendationFromEvidenceV21} from './pilot-evidence-v21-audit'
import {evidenceV21Handler,type EvidenceV21Repository} from './pilot-evidence-v21-api'
import {syntheticEvidenceV21,V21_REAL_PROFESSIONALISM_CASE} from '../../../tests/fixtures/pilot-evidence-v21'
import {ARTISAN_EVIDENCE_CASES} from '../../../tests/fixtures/pilot-evidence'
import {negativeHash} from './negative-validation-core'
import {canonicalJson} from './jev-exploratory-core'
import {THEME_KEYS} from './jev-themes'
afterEach(()=>vi.unstubAllGlobals())
it('V2 rule hash is exactly unchanged, V21 isolated/versioned with25 themes',async()=>{expect(await evidenceRuleHash()).toBe('8334b14f39be05b8cbaa4a403de198739469b8f1b4fe516168641b37ca95bd99');expect(await evidenceV21RuleHash()).not.toBe(await evidenceRuleHash());expect([...new Set(EVIDENCE_V21_RULES.map(r=>r.theme))].sort()).toEqual([...THEME_KEYS].sort());expect(Object.isFrozen(EVIDENCE_V21_RULES)).toBe(true);expect(readFileSync('supabase/functions/_shared/pilot-evidence-v21-api.ts','utf8')).not.toContain('structuredCall')})
it.each([ARTISAN_EVIDENCE_CASES[1],V21_REAL_PROFESSIONALISM_CASE])('real generic service case $id hash verified, professionalism proof excluded',async c=>{expect(await negativeHash(c.text)).toBe(c.sha);expect(verifyEvidenceV21(c.text,'professionalism','positive')).toMatchObject({status:'unsupported_by_rule',reason:'GENERIC_SERVICE_IS_NOT_PROFESSIONALISM'})})
it.each(['Excellent service.','Great service.','Top-notch service.'])('%s alone not professionalism',text=>expect(verifyEvidenceV21(text,'professionalism','positive').status).toBe('unsupported_by_rule'))
it.each(['Expert staff.','The staff were well trained.','The waiter handled the situation competently.','Professional staff.','The waiter was competent.','The staff knew all ingredients.','They knew the menu.','The waiter handled the complaint professionally.','The staff answered our questions accurately.'])('explicit professionalism retained: %s',text=>expect(verifyEvidenceV21(text,'professionalism','positive').status).toBe('supported_by_rule'))
it.each([
 ['The coffee was delicious.','food_quality','positive','unsupported_by_rule'],['The food was average, the coffee was excellent.','food_quality','positive','review_needed'],['The food was bad but the coffee was delicious.','food_quality','positive','review_needed'],['The food was delicious and the coffee was bad.','food_quality','positive','supported_by_rule'],['Amazing breakfasts and delicious coffee!','food_quality','positive','supported_by_rule'],['Amazing breakfasts and delicious coffee!','drinks','positive','supported_by_rule'],['The prices were very high.','value','negative','unsupported_by_rule'],['The prices were high but the meal was worth the money.','value','positive','supported_by_rule'],['The portions were small for the price.','value','negative','supported_by_rule'],['The place has an unimpressive location.','location','negative','supported_by_rule'],['The waiter could not understand our order.','attentiveness','negative','unsupported_by_rule'],['The waiter could not understand our order.','communication','negative','supported_by_rule'],['The staff were not professional.','professionalism','negative','supported_by_rule'],['The staff were not unprofessional.','professionalism','negative','review_needed'],['Great service. The staff helped us choose a dish.','professionalism','positive','review_needed'],['The service may have been professional.','professionalism','positive','review_needed'],
 ] as const)('boundary and genuine evidence: %s / %s', (text,theme,polarity,status)=>expect(verifyEvidenceV21(text,theme,polarity).status).toBe(status))
it('422-style paired workflow preserves all base/cached/report inputs, exact8 quotes and counts',async()=>{const f=await syntheticEvidenceV21(),before=canonicalJson({s:f.snapshot,r:f.report,c:f.cache,b:f.base}),a=await buildEvidenceV21(f.snapshot,f.report,f.cache,f.base);expect(canonicalJson({s:f.snapshot,r:f.report,c:f.cache,b:f.base})).toBe(before);expect(a.selected).toHaveLength(8);expect(a.selected.map(p=>({review:p.review_id,key:p.key,quote:p.excerpt!.quote,sha:p.quote_sha256}))).toEqual(f.base.result.selected.map(p=>({review:p.review_id,key:p.key,quote:p.excerpt!.quote,sha:p.quote_sha256})));expect(a.summary.supported+a.summary.unsupported+a.summary.review_needed).toBe(a.summary.jev_findings);expect(a.comparison.retained_supported+a.comparison.previously_supported_excluded+a.comparison.previously_supported_pending).toBe(a.comparison.v2.supported);expect(a.comparison.previously_supported_excluded).toBeGreaterThanOrEqual(2);expect(a.old_recommendations).toEqual(f.base.result.recommendations);expect(a.human_validated).toBe(false);expect(a.ai_verified).toBe(false)})
it('four deterministic recommendations each require BOTH actual proof IDs',async()=>{const f=await syntheticEvidenceV21(),p=await previewEvidenceV21(f.snapshot,f.base,f.audit,f.sha,'fr');expect(p.interpretation_and_recommendations.recommendations).toHaveLength(4);expect(p.interpretation_and_recommendations.recommendations.every(r=>r.status==='grounded_by_rules'&&r.proofs.length===2)).toBe(true);const gone=f.audit.selected.find(p=>p.axis==='service')!;f.audit.selected=f.audit.selected.filter(p=>p.binding_id!==gone.binding_id);const r=recommendationFromEvidenceV21(f.audit,'service','fr');expect(r.status).toBe('review_needed');expect(r.actions).toEqual([]);expect(r.missing_evidence_ids).toContain(gone.binding_id);await expect(previewEvidenceV21(f.snapshot,f.base,f.audit,await evidenceV21AuditHash(f.audit),'fr')).rejects.toThrow('V21_CHANGED')})
it('unchanged V2 hash, changed quote or missing support cannot be certified',async()=>{const f=await syntheticEvidenceV21();f.audit.selected[0].excerpt!.quote+=' invented';await expect(previewEvidenceV21(f.snapshot,f.base,f.audit,await evidenceV21AuditHash(f.audit),'fr')).rejects.toThrow('PROOF_CHANGED');f.base.result.summary.supported++;await expect(buildEvidenceV21(f.snapshot,f.report,f.cache,f.base)).rejects.toThrow('BASE_CHANGED')})
it('read-only reload, manual free recompute, paid action disabled and no network',async()=>{const net=vi.fn();vi.stubGlobal('fetch',net);const f=await syntheticEvidenceV21(),save=vi.fn(),repo:EvidenceV21Repository={language:'fr',source:async()=>({snapshot:f.snapshot,report:f.report,base:f.base}),cache:async()=>f.cache,read:async()=>null,save},handler=evidenceV21Handler(async()=>repo);await handler(new Request('https://fixture'));expect(save).not.toHaveBeenCalled();expect((await handler(new Request('https://fixture',{method:'POST',body:JSON.stringify({action:'generate_sol'})}))).status).toBe(405);await handler(new Request('https://fixture',{method:'POST',body:JSON.stringify({action:'audit_free'})}));expect(save).toHaveBeenCalledOnce();expect(net).not.toHaveBeenCalled();expect((await evidenceV21Handler(async()=>{throw new Error('FORBIDDEN')})(new Request('https://fixture'))).status).toBe(403)})
