import {EVIDENCE_RULES as V2_RULES,verifyExplicitEvidence as verifyV2,type EvidenceRule,type EvidencePolarity,type VerifiedExcerpt} from './pilot-evidence-rules.ts'
import type {ThemeKey} from './jev-themes.ts'
import {negativeHash} from './negative-validation-core.ts'
import {canonicalJson} from './jev-exploratory-core.ts'
export const EVIDENCE_V21_VERSION='pilot-evidence-explicit-v2.1'
export const EVIDENCE_V21_VERIFIER='explicit-evidence-rules-v2.1'
export type EvidenceV21Status='supported_by_rule'|'unsupported_by_rule'|'review_needed'
export interface EvidenceV21Check {status:EvidenceV21Status;reason:string;excerpt:VerifiedExcerpt|null;verification_type:'deterministic_rule_check';human_validated:false;ai_verified:false}
const food='(?:food|meals?|dishes|dish|breakfasts?|pancakes?|burgers?|steaks?|cakes?|shakshouka|pasta|pizza|salads?)',drink='(?:coffee|tea|drinks?|juices?|cocktails?|smoothies?|beverages?|lattes?|cappuccino|espresso|beer)',staff='(?:staff|waiters?|waitress|servers?|service|they|team)'
const good='(?:delicious|tasty|excellent|very good|best|amazing|great|good|wonderful)',bad='(?:terrible|bad|tasteless|bland|disappointing|too sweet|not living up)'
const local=(entity:string,adjective:string)=>`(?:${entity}\\s+(?:(?:is|was|were|are|tastes?|tasted)\\s+)?(?:(?:really|very|completely|absolutely|simply|so|quite|a little)\\s+)?${adjective}|${adjective}\\s+(?:(?!(?:coffee|tea|drink|and|but)\\b)[a-z-]+\\s+)?${entity})`
const overrides:Partial<Record<`${ThemeKey}:${EvidencePolarity}`,string>>={
 'professionalism:positive':`(?:\\b(?:professional|competent|knowledgeable|skilled|capable|experienced|serious|expert|well-trained|well trained)\\s+${staff}|${staff}.{0,35}\\b(?:professional|competent|knowledgeable|skilled|capable|experienced|serious|expert|well-trained|well trained)\\b|(?:behaved|acted|handled.{0,30}) (?:professionally|competently|expertly)|${staff}.{0,25}(?:knew|knows|understood).{0,25}(?:menu|ingredients|dietary|allergies)|${staff}.{0,30}answered.{0,20}(?:questions|requests).{0,15}accurately)`,
 'professionalism:negative':`(?:\\b(?:unprofessional|incompetent|unskilled)\\s+${staff}|${staff}.{0,35}\\b(?:unprofessional|incompetent|unskilled|not professional|not competent)\\b|${staff}.{0,20}(?:did not|didn't|could not|couldn't) know.{0,15}(?:menu|ingredients|allergies))`,
 'food_quality:positive':local(food,good),'food_quality:negative':local(food,bad),
 'drinks:positive':local(drink,good),'drinks:negative':local(drink,bad),
 'value:negative':'(?:not worth (?:the )?(?:money|price|cost|paying)|poor value|bad value|(?:too expensive|overpriced|too pricey) for (?:the |such |what )?(?:quality|portion|service|you (?:get|receive))|(?:(?:small|tiny) portions?|portions?.{0,15}(?:small|tiny)) for (?:the )?(?:price|cost))',
 'value:positive':'(?:well )?worth (?:the )?(?:money|price|cost|paying)|good value|great value|deserve(?:s)? to be paid for',
 'location:negative':V2_RULES.find(r=>r.id==='location.negative.location_appeal')!.pattern+'|(?:unimpressive|not impressive) location|location.{0,20}(?:unimpressive|not impressive)',
}
// Every rule is copied. V2 and all JEV configs remain untouched.
export const EVIDENCE_V21_RULES:readonly EvidenceRule[]=Object.freeze(V2_RULES.map(r=>{const key=`${r.theme}:${r.polarity}` as keyof typeof overrides,pattern=r.theme==='location'?(r.claim==='location_appeal'?overrides[key]!:r.pattern):overrides[key]??r.pattern;return Object.freeze({...r,pattern,...(r.theme==='professionalism'?{claim:'professional_competence',id:`professionalism.${r.polarity}.professional_competence`,statement_fr:r.polarity==='positive'?'Le texte décrit explicitement une compétence, une connaissance ou un comportement professionnel.':'Le texte décrit explicitement un défaut de compétence ou de comportement professionnel.',statement_vi:r.polarity==='positive'?'Nội dung mô tả rõ năng lực, kiến thức hoặc hành vi chuyên nghiệp.':'Nội dung mô tả rõ thiếu năng lực hoặc hành vi không chuyên nghiệp.',recommendation_fr:r.polarity==='positive'?'Maintenir les compétences et comportements professionnels explicitement appréciés.':'Examiner les difficultés de compétence ou de comportement professionnel décrites.',recommendation_vi:r.polarity==='positive'?'Duy trì năng lực và hành vi chuyên nghiệp được đánh giá cụ thể.':'Xem xét vấn đề năng lực hoặc hành vi chuyên nghiệp đã được mô tả.'}:{})})}))
export const evidenceV21RuleHash=()=>negativeHash(canonicalJson({version:EVIDENCE_V21_VERSION,verifier:EVIDENCE_V21_VERIFIER,rules:EVIDENCE_V21_RULES,policy:'local_entity_polarity_v1;definite_boundary_excluded;otherwise_review_needed;retain_valid_v2_quotes;hypotheses_may_v1;professional_assistance_uncertain_v1'}))
const base={verification_type:'deterministic_rule_check' as const,human_validated:false as const,ai_verified:false as const}
const absent=(status:'unsupported_by_rule'|'review_needed',reason:string):EvidenceV21Check=>({...base,status,reason,excerpt:null})
function units(text:string){return [...text.matchAll(/[^.!?\n;]+(?:[.!?;]+|$)/g)].flatMap(s=>{const out:{text:string;start:number;end:number}[]=[];let from=0;for(const m of s[0].matchAll(/\b(?:but|however|although|whereas)\b|,/gi)){append(from,m.index);from=m.index+m[0].length}append(from,s[0].length);function append(a:number,b:number){const part=s[0].slice(a,b),left=part.length-part.trimStart().length,right=part.trimEnd().length;if(right>left)out.push({text:part.slice(left,right),start:s.index+a+left,end:s.index+a+right})}return out})}
function localSupport(text:string,theme:ThemeKey,polarity:EvidencePolarity):EvidenceV21Check|null{for(const u of units(text)){if(u.text.length>1200||/\b(?:if|wish|should|might|perhaps|would|may)\b/i.test(u.text)||(['food_quality','cleanliness'].includes(theme)&&/\b(?:poisoning|sick|vomit|symptoms|hospital)\b/i.test(u.text)))continue;for(const r of EVIDENCE_V21_RULES.filter(r=>r.theme===theme&&r.polarity===polarity)){const m=new RegExp('\\b(?:'+r.pattern+')\\b','i').exec(u.text);if(!m)continue;const segment=u.text.slice(Math.max(0,m.index-18),m.index+m[0].length);if(polarity==='positive'&&/\b(?:not|never|no|wasn['’]t|weren['’]t|isn['’]t|didn['’]t|unprofessional|incompetent)\b/i.test(segment))continue;if(polarity==='negative'&&/\b(?:not|wasn['’]t|isn['’]t)\s+(?:very\s+|at all\s+)?(?:bad|terrible|bland|unprofessional|incompetent|poor value)\b/i.test(segment))continue;return {...base,status:'supported_by_rule',reason:'EXPLICIT_THEME_AND_POLARITY',excerpt:{rule_id:r.id,claim:r.claim,start:u.start,end:u.end,quote:u.text}}}}return null}
export function verifyEvidenceV21(text:string,theme:ThemeKey,polarity:EvidencePolarity):EvidenceV21Check{
 const changed=['professionalism','food_quality','drinks','value','location'].includes(theme);const explicit=changed?localSupport(text,theme,polarity):verifyV2(text,theme,polarity);if(explicit?.status==='supported_by_rule')return explicit;
 // Preserve valid punctuation/longer paraphrases only where there is no competing entity.
 if(['food_quality','drinks'].includes(theme)){const old=verifyV2(text,theme,polarity);if(old.status==='supported_by_rule'&&!new RegExp(theme==='food_quality'?drink:food,'i').test(old.excerpt!.quote))return old}
 if(theme==='professionalism'&&/(?:excellent|great|top-notch|superb).{0,25}(?:service|staff)|(?:staff|service).{0,25}(?:excellent|great|top-notch|superb)/i.test(text)&&!/(?:professional|competent|knowledge|skilled|capable|experienced|serious|expert|well-trained|well trained|knew|knows|accurately)/i.test(text)&&!/(?:staff|waiter|waitress|server|they).{0,35}(?:helped|assisted|advised|recommended|explained|handled|answered|guided)|dietary|allergies|special request/i.test(text))return absent('unsupported_by_rule','GENERIC_SERVICE_IS_NOT_PROFESSIONALISM');
 if(theme==='attentiveness'&&/\b(?:understand|translator|translation|language|speaks?|speak)\b/i.test(text)&&!/(?:attentive|responsive|caring|ignored|neglected|checked on|noticed|no waiter|nobody)/i.test(text))return absent('unsupported_by_rule','COMMUNICATION_IS_NOT_ATTENTION');
 if(theme==='location'&&/unassuming|nondescript/i.test(text)&&!/(?:access|too far|long drive|unappealing|disappointing|poor location|bad location)/i.test(text))return absent('unsupported_by_rule','DESCRIPTIVE_LOCATION_IS_NOT_ACCESS');
 if(theme==='food_quality'&&new RegExp(drink,'i').test(text)&&!new RegExp(food,'i').test(text))return absent('unsupported_by_rule','DRINK_QUALITY_IS_NOT_FOOD_QUALITY');
 if(theme==='value'&&/(?:expensive|overpriced|high prices|prices.{0,12}high|price.{0,12}high)/i.test(text)&&!/(?:value|worth|for|relative|compared|deserve|paid for)/i.test(text))return absent('unsupported_by_rule','PRICE_LEVEL_IS_NOT_VALUE');
 return absent('review_needed',explicit?.reason??'EXPLICIT_SUPPORT_NOT_ESTABLISHED')
}
