import {describe,it,expect,vi,afterEach} from 'vitest'
import {EVIDENCE_RULES,verifyExplicitEvidence,evidenceRuleHash} from './pilot-evidence-rules'
import {buildEvidenceAudit,evidenceAuditHash,prepareEvidenceV2Packet} from './pilot-evidence-audit'
import {evidenceHandler,type EvidenceRepository} from './pilot-evidence-api'
import {canonicalJson} from './jev-exploratory-core'
import {negativeHash} from './negative-validation-core'
import {THEME_KEYS} from './jev-themes'
import {V11_QUESTION_SET,V11_THRESHOLDS} from './jev-v11-calibration'
import {V12_CONFIG} from './jev-v12-config'
import {V13_CONFIG} from './jev-v13-config'
import {ARTISAN_EVIDENCE_CASES,syntheticEvidence} from '../../../tests/fixtures/pilot-evidence'
afterEach(()=>vi.unstubAllGlobals())
describe('separate explicit text evidence, never reclassification',()=>{
 it('all25 themes covered, fixed version/hash, V11/V12/V13 unchanged',async()=>{const before=canonicalJson({V11_QUESTION_SET,V11_THRESHOLDS,V12_CONFIG,V13_CONFIG});expect([...new Set(EVIDENCE_RULES.map(r=>r.theme))].sort()).toEqual([...THEME_KEYS].sort());expect(Object.isFrozen(EVIDENCE_RULES)).toBe(true);expect(await evidenceRuleHash()).toBe(await evidenceRuleHash());verifyExplicitEvidence('Staff checked on us.','attentiveness','positive');expect(canonicalJson({V11_QUESTION_SET,V11_THRESHOLDS,V12_CONFIG,V13_CONFIG})).toBe(before)})
 it.each(ARTISAN_EVIDENCE_CASES)('frozen real English case $id hash matches audited Supabase text',async r=>expect(await negativeHash(r.text)).toBe(r.sha))
 it('communication difficulty is not customer attention',()=>{const text=ARTISAN_EVIDENCE_CASES[0].text;expect(verifyExplicitEvidence(text,'attentiveness','negative')).toMatchObject({status:'review_needed',reason:'COMMUNICATION_IS_NOT_ATTENTION'});expect(verifyExplicitEvidence(text,'communication','negative')).toMatchObject({status:'supported_by_rule',excerpt:{claim:'customer_communication'}})})
 it('top-notch staff/service alone cannot justify particular attention',()=>expect(verifyExplicitEvidence(ARTISAN_EVIDENCE_CASES[1].text,'attentiveness','positive')).toMatchObject({status:'review_needed',reason:'GENERIC_SERVICE_IS_NOT_ATTENTION'}))
 it('unassuming location cannot establish access trouble; concrete attention in same review remains eligible',()=>{const t=ARTISAN_EVIDENCE_CASES[2].text;expect(verifyExplicitEvidence(t,'location','negative')).toMatchObject({status:'review_needed',reason:'DESCRIPTIVE_LOCATION_IS_NOT_ACCESS'});expect(verifyExplicitEvidence(t,'attentiveness','positive').status).toBe('supported_by_rule')})
 it.each([
 ['The staff was attentive and responsive.','attentiveness','positive'],['Staff checked on us and noticed our needs.','attentiveness','positive'],['The waiter ignored us when we asked for help.','attentiveness','negative'],['No waiter came to take our order.','attentiveness','negative'],['The waiter clearly explained the menu.','communication','positive'],['They could not understand our order.','communication','negative'],['The entrance was difficult to find.','location','negative'],['It was too far away for us.','location','negative'],['The unappealing location disappointed us.','location','negative'],['The food was delicious.','food_quality','positive'],['The food was terrible.','food_quality','negative'],['The coffee was tasteless.','drinks','negative'],['The room was too hot.','comfort','negative'],['The decor was beautiful.','decor','positive'],['There were dirty tables.','cleanliness','negative'],['The meal was not worth the price.','value','negative'],['We were charged an extra fee.','billing','negative'],['The prices were too high.','price_level','negative'],
 ] as const)('explicit case %s supports only scoped %s/%s', (text,theme,polarity)=>{const v=verifyExplicitEvidence(text,theme,polarity);expect(v.status).toBe('supported_by_rule');expect(text.slice(v.excerpt!.start,v.excerpt!.end)).toBe(v.excerpt!.quote)})
 it.each([
 ['Staff was unprofessional.','professionalism','positive'],['Bot expensive.','price_level','negative'],['They speak Russian.','communication','positive'],['We waited forty minutes.','attentiveness','negative'],['The order was wrong.','attentiveness','negative'],['The atmosphere was bad.','decor','negative'],['The coffee was delicious but the food was terrible.','food_quality','positive'],['The food was not terrible.','food_quality','negative'],['The staff was not attentive.','attentiveness','positive'],['The restaurant was not expensive.','price_level','negative'],['If the waiter were attentive, we would return.','attentiveness','positive'],['I was sick after eating food.','cleanliness','negative'],['The expensive food caused poisoning.','food_quality','negative'],
 ] as const)('rejects transfer/negation/hypothesis %s', (text,theme,polarity)=>expect(verifyExplicitEvidence(text,theme,polarity).status).toBe('review_needed'))
 it('both requires explicit support for each polarity of the same theme',()=>{const text='The food was delicious but the food was terrible on the next visit.';expect(verifyExplicitEvidence(text,'food_quality','positive').status).toBe('supported_by_rule');expect(verifyExplicitEvidence(text,'food_quality','negative').status).toBe('supported_by_rule');const different='The coffee was delicious but the food was terrible.';expect(verifyExplicitEvidence(different,'food_quality','positive').status).toBe('review_needed')})
})
describe('immutable audit, old/new comparisons and second preflight',()=>{
 it('independent selection uses exact quote/hashes and preserves all historical source/cache/report',async()=>{const f=await syntheticEvidence(),before=canonicalJson({s:f.snapshot,r:f.report,c:f.cache}),a=await buildEvidenceAudit(f.snapshot,f.report,f.cache);expect(a).toEqual(f.evidence);expect(canonicalJson({s:f.snapshot,r:f.report,c:f.cache})).toBe(before);expect(a.summary.previous_review_needed).toBeGreaterThanOrEqual(3);expect(a.summary.unsupported_recommendations).toBe(2);expect(a.selected.length).toBeLessThanOrEqual(8);expect(a.counts_unchanged).toBe(true);expect(a.independent_human_validation).toBe(false);expect(a.checks.every(c=>!c.human_validated&&!c.ai_verified)).toBe(true);expect(a.selected.some(c=>c.review_id===ARTISAN_EVIDENCE_CASES[0].id&&c.theme_key==='attentiveness')).toBe(false)})
 it('same counts and source scope, new proofs supported; proposed recommendations are tied to exact proof IDs',async()=>{const f=await syntheticEvidence(),p=await prepareEvidenceV2Packet(f.snapshot,f.evidence,f.sha,'fr');expect(p.counts.map(c=>({key:c.key,mentions:c.mentions}))).toEqual(f.evidence.source_context.topics.map(c=>({key:c.key,mentions:c.mentions})));expect(p.statements.every(s=>p.recommendation_catalog.find(r=>r.statement_id===s.id)?.review_id===s.review_id)).toBe(true);expect(p.sol_generation_enabled).toBe(false);expect(JSON.stringify(p)).not.toContain('original_text');expect(JSON.stringify(p)).not.toContain('probability');expect(p.statements.every(s=>s.english_excerpt.length<=1200)).toBe(true)})
 it('stale snapshot/report probabilities never silently used',async()=>{const f=await syntheticEvidence();f.cache[0].response!.themes.food_quality={choice:'positive',probabilities:{negative:0,positive:1,both:0,absent:0}};await expect(buildEvidenceAudit(f.snapshot,f.report,f.cache)).rejects.toThrow('PREDICTION_SCOPE_CHANGED');f.report.snapshot_id='another';await expect(buildEvidenceAudit(f.snapshot,f.report,f.cache)).rejects.toThrow('REPORT_BINDING_CHANGED')})
 it('untrusted stored approved status fails second gate even with freshly recomputed checksum',async()=>{const f=await syntheticEvidence(),bad=structuredClone(f.evidence),candidate=bad.checks.find(c=>c.review_id===ARTISAN_EVIDENCE_CASES[1].id&&c.theme_key==='attentiveness')!;candidate.status='supported_by_rule';candidate.excerpt={quote:ARTISAN_EVIDENCE_CASES[1].text,start:0,end:ARTISAN_EVIDENCE_CASES[1].text.length,claim:'customer_attention',rule_id:'attentiveness.positive.customer_attention'};candidate.quote_sha256=await negativeHash(candidate.excerpt.quote);bad.selected=[candidate];await expect(prepareEvidenceV2Packet(f.snapshot,bad,await evidenceAuditHash(bad),'vi')).rejects.toThrow('PREFLIGHT_REJECTED')})
 it('truncated/forged quote or changed audit SHA rejected before any provider',async()=>{const network=vi.fn();vi.stubGlobal('fetch',network);const f=await syntheticEvidence();f.evidence.selected[0].quote_sha256='bad';await expect(prepareEvidenceV2Packet(f.snapshot,f.evidence,f.sha,'fr')).rejects.toThrow('AUDIT_CHANGED');await expect(prepareEvidenceV2Packet(f.snapshot,f.evidence,await evidenceAuditHash(f.evidence),'fr')).rejects.toThrow('PREFLIGHT_REJECTED');expect(network).not.toHaveBeenCalled()})
 it('API GET never creates, manual audit free only, paid endpoints refused, role checked',async()=>{const f=await syntheticEvidence(),save=vi.fn(),r:EvidenceRepository={language:'fr',source:async()=>({snapshot:f.snapshot,report:f.report}),cache:async()=>f.cache,read:async()=>null,save},h=evidenceHandler(async()=>r);await h(new Request('https://fixture'));expect(save).not.toHaveBeenCalled();expect((await h(new Request('https://fixture',{method:'POST',body:JSON.stringify({action:'generate_sol'})}))).status).toBe(405);expect(save).not.toHaveBeenCalled();await h(new Request('https://fixture',{method:'POST',body:JSON.stringify({action:'audit_free'})}));expect(save).toHaveBeenCalledOnce();expect((await evidenceHandler(async()=>{throw new Error('FORBIDDEN')})(new Request('https://fixture'))).status).toBe(403)})
})
