import {GOLD_KEYS,type GoldChoice,type GoldTheme,type GOLD_TAXONOMY} from './gold-taxonomy.ts'
import {normalizeGoldLabels,validateGoldSources,type GoldSource,type GoldBenchmark,type GoldLabel} from './gold-core.ts'
import {holdoutHash,representativePool,selectRepresentativeItems,representativeReplacement,type AnalyticCandidate,type RepresentativeItem} from './representative-selection.ts'
import {scoreRepresentative,type PreviousDifficultResult} from './representative-score.ts'
export const PREVIOUS_ADJUDICATION='146615ca-d3cd-4914-8613-4e6e3d6219f7',REFERENCE_GOLD='1d5cfc8c-ac77-4e44-a7a7-6153eb132385'
export interface CorrectedReference {id:string;name:string;status:string;organization_id:string;source_gold_set_id:string;source_adjudication_id:string;source_generation_id:string;jev_benchmark_id:string;taxonomy_version:string;taxonomy:typeof GOLD_TAXONOMY;label_count:number;human_label_count:number;human_comparable_count:number;human_uncertain_count:number}
export interface SelectionContext {reference:CorrectedReference;reviews:AnalyticCandidate[];goldIds:string[];previousIds:string[];previous:PreviousDifficultResult}
export interface RepresentativeTest {id:string;organization_id:string;source_generation_id:string;gold_v2_reference_id:string;status:'draft'|'completed';revision:number;taxonomy:typeof GOLD_TAXONOMY;source_fingerprint:string;comparison:Awaited<ReturnType<typeof scoreRepresentative>>|null;created_at:string;completed_at:string|null}
export interface RepresentativeRepository {user:string;selection:()=>Promise<SelectionContext>;predictions:()=>Promise<{source:GoldSource;benchmark:GoldBenchmark}>;get:(id?:string)=>Promise<RepresentativeTest|null>;items:(id:string)=>Promise<RepresentativeItem[]>;labels:(id:string)=>Promise<GoldLabel[]>;create:(payload:Record<string,unknown>)=>Promise<string>;write:(id:string,revision:number,action:string,payload:Record<string,unknown>)=>Promise<void>}
function checkContext(c:SelectionContext){const r=c.reference;if(r.status!=='completed'||r.source_gold_set_id!==REFERENCE_GOLD||r.source_adjudication_id!==PREVIOUS_ADJUDICATION||r.source_generation_id!=='b73ec894-d5fd-4b11-9fe6-cd89c117e9de'||r.jev_benchmark_id!=='4c634678-17a9-47b3-89e1-fad0641f5d86'||r.taxonomy_version!=='gold-taxonomy-v1'||Object.keys(r.taxonomy).length!==25||GOLD_KEYS.some(k=>!r.taxonomy[k]))throw new Error('HOLDOUT_SOURCE_INVALID')}
async function fingerprint(c:SelectionContext){return await holdoutHash(JSON.stringify({reference_id:c.reference.id,taxonomy:c.reference.taxonomy,reviews:[...c.reviews].sort((a,b)=>a.id.localeCompare(b.id)),goldIds:[...c.goldIds].sort(),previousIds:[...c.previousIds].sort()}))}
async function checkItems(c:SelectionContext,items:RepresentativeItem[]){const active=items.filter(i=>!i.excluded);if(active.length!==12||new Set(items.map(i=>i.review_id)).size!==items.length||new Set(active.map(i=>i.position)).size!==12)throw new Error('HOLDOUT_ITEMS_INVALID');const forbidden=new Set([...c.goldIds,...c.previousIds]);for(const item of items){const r=c.reviews.find(r=>r.id===item.review_id);if(forbidden.has(item.review_id)||!r?.analysis_text.trim()||r.analysis_language!=='en'||await holdoutHash(r.analysis_text)!==item.analysis_text_sha256)throw new Error('HOLDOUT_TEXT_CHANGED')}}
export function representativeProjection(c:SelectionContext,t:RepresentativeTest|null,items:RepresentativeItem[],labels:GoldLabel[],annotation:boolean,poolStats:Awaited<ReturnType<typeof representativePool>>['stats']){
  return {eligible:true,reference:{id:c.reference.id,name:c.reference.name,label_count:c.reference.label_count,human_label_count:c.reference.human_label_count,human_comparable_count:c.reference.human_comparable_count,human_uncertain_count:c.reference.human_uncertain_count,assisted:true},pool_stats:poolStats,test:t?{id:t.id,status:t.status,revision:t.revision,completed_reviews:items.filter(i=>!i.excluded&&i.confirmed_at&&labels.filter(l=>l.review_id===i.review_id).length===25).length,created_at:t.created_at,completed_at:t.completed_at}:null,taxonomy:t?.taxonomy??c.reference.taxonomy,
    items:annotation?items.filter(i=>!i.excluded).sort((a,b)=>a.position-b.position).map(i=>({review_id:i.review_id,position:i.position,analysis_text:c.reviews.find(r=>r.id===i.review_id)!.analysis_text,confirmed_at:i.confirmed_at??null,choices:Object.fromEntries(labels.filter(l=>l.review_id===i.review_id).map(l=>[l.theme_key,l.choice])) as Partial<Record<GoldTheme,GoldChoice>>})):[],...(t?.status==='completed'?{comparison:t.comparison}:{})}
}
const headers={'Content-Type':'application/json','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'GET, POST, OPTIONS'},json=(v:unknown,status=200)=>new Response(JSON.stringify(v),{status,headers}),uuid=(v:unknown)=>typeof v==='string'&&/^[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12}$/i.test(v)
export function representativeHandler(authenticate:(r:Request)=>Promise<RepresentativeRepository>){return async(request:Request)=>{
  if(request.method==='OPTIONS')return new Response('ok',{headers});if(!['GET','POST'].includes(request.method))return json({error:'METHOD_NOT_ALLOWED'},405)
  try{const repo=await authenticate(request),params=new URL(request.url).searchParams,body=request.method==='POST'?await request.json():null,id=body?.test_id??params.get('test_id');if(id&&!uuid(id))throw new Error('HOLDOUT_ID_INVALID')
    const c=await repo.selection();checkContext(c);const pool=await representativePool(c.reference.source_generation_id,c.reviews,c.goldIds,c.previousIds),fp=await fingerprint(c);let t=await repo.get(id??undefined)
    if(t&&(t.organization_id!==c.reference.organization_id||t.gold_v2_reference_id!==c.reference.id))throw new Error('FORBIDDEN');if(t&&t.source_fingerprint!==fp)throw new Error('HOLDOUT_SOURCE_CHANGED')
    if(request.method==='POST'){
      if(body?.action==='create'){if(!t){const s=await selectRepresentativeItems(c.reference.source_generation_id,c.reviews,c.goldIds,c.previousIds),created=await repo.create({p_user:repo.user,p_reference:c.reference.id,p_items:s.items,p_stats:s.stats,p_seed:s.seed,p_fingerprint:fp});t=await repo.get(created)}}
      else {if(!t)throw new Error('HOLDOUT_NOT_FOUND');if(t.status!=='draft')throw new Error('HOLDOUT_IMMUTABLE');if(!Number.isInteger(body?.revision)||body.revision!==t.revision)throw new Error('HOLDOUT_REVISION_CHANGED');const items=await repo.items(t.id);await checkItems(c,items);let payload:Record<string,unknown>
        if(body.action==='confirm_review'){if(!items.some(i=>i.review_id===body.review_id&&!i.excluded)||!body.choices||typeof body.choices!=='object'||Array.isArray(body.choices))throw new Error('HOLDOUT_CHOICES_INVALID');payload={review_id:body.review_id,choices:normalizeGoldLabels(body.choices)}}
        else if(body.action==='exclude_review'){payload={review_id:body.review_id,replacement:await representativeReplacement(c.reference.source_generation_id,c.reviews,c.goldIds,c.previousIds,items,body.review_id)}}
        else if(body.action==='finalize'){const labels=await repo.labels(t.id);if(body.confirm!==true)throw new Error('HOLDOUT_CONFIRMATION_REQUIRED');if(items.filter(i=>!i.excluded).some(i=>!i.confirmed_at||labels.filter(l=>l.review_id===i.review_id).length!==25))throw new Error('HOLDOUT_INCOMPLETE');const {source,benchmark}=await repo.predictions();validateGoldSources(source,benchmark);if(source.organization_id!==c.reference.organization_id)throw new Error('FORBIDDEN');payload={comparison:await scoreRepresentative(t.id,source,benchmark,items,labels,c.previous)}}
        else throw new Error('HOLDOUT_ACTION_INVALID');await repo.write(t.id,t.revision,body.action,payload);t=await repo.get(t.id)
      }
    }
    if(!t)return json(representativeProjection(c,null,[],[],false,pool.stats));const [items,labels]=await Promise.all([repo.items(t.id),repo.labels(t.id)]);await checkItems(c,items);return json(representativeProjection(c,t,items,labels,request.method==='POST'||params.get('view')==='annotation',pool.stats))
  }catch(e){const code=e instanceof Error&&/^[A-Z0-9_]+$/.test(e.message)?e.message:'HOLDOUT_REQUEST_FAILED';return json({error:code},code==='UNAUTHORIZED'?401:code==='FORBIDDEN'?403:code==='HOLDOUT_NOT_FOUND'?404:['HOLDOUT_IMMUTABLE','HOLDOUT_REVISION_CHANGED','HOLDOUT_SOURCE_CHANGED'].includes(code)?409:code.startsWith('HOLDOUT_')||code.startsWith('GOLD_')?400:500)}
}}
