// @vitest-environment node
import {it,expect,vi} from 'vitest'
import {readFileSync} from 'node:fs'
import {syntheticRepresentative,fakeRepresentativeId} from '../../../tests/fixtures/representative'
import {holdoutHash,representativePool,selectRepresentativeItems,representativeReplacement} from './representative-selection'
import {scoreRepresentative} from './representative-score'
import {representativeHandler,type RepresentativeRepository} from './representative-api'
import {GOLD_KEYS} from './gold-taxonomy'
it('hash sampling is deterministic, model-independent, English-only, unique and excludes all previously seen IDs including overlapping exclusions',async()=>{
  const h=await syntheticRepresentative(),before=JSON.stringify(h),a=await selectRepresentativeItems(h.source.generation_id,h.context.reviews,h.context.goldIds,h.context.previousIds),b=await selectRepresentativeItems(h.source.generation_id,[...h.context.reviews].reverse(),[...h.context.goldIds].reverse(),[...h.context.previousIds].reverse())
  expect(a).toEqual(b);expect(a.items).toHaveLength(12);expect(new Set(a.items.map(r=>r.review_id)).size).toBe(12);expect(a.stats).toEqual({total_text_reviews:95,excluded_gold_reviews:40,excluded_previous_adjudication:12,excluded_previous_additional:0,eligible_holdout_reviews:55});expect(JSON.stringify(h)).toBe(before)
  expect(a.items.every(i=>!h.context.goldIds.includes(i.review_id)&&!h.context.previousIds.includes(i.review_id))).toBe(true)
  const changed=h.context.reviews.map(r=>({...r,rating:1,sol:'negative',jev:'positive',gold:'negative'}));expect((await selectRepresentativeItems(h.source.generation_id,changed,h.context.goldIds,h.context.previousIds)).items).toEqual(a.items)
  expect(a.items.map(r=>r.selection_rank_hash)).toEqual([...a.items.map(r=>r.selection_rank_hash)].sort());for(const i of a.items)expect(i.selection_rank_hash).toBe(await holdoutHash(a.seed+i.review_id));expect(JSON.stringify(a.items)).not.toMatch(/analysis_text":|rating|probabilities|original_text/)
  h.context.reviews[0].analysis_language='ru';await expect(representativePool(h.source.generation_id,h.context.reviews,[],[])).rejects.toThrow('HOLDOUT_ENGLISH_SOURCE_REQUIRED')
})
it('exclusion replacement advances through the hash order and never recycles selected, excluded or seen reviews',async()=>{const h=await syntheticRepresentative(),old=h.items[0],pool=await representativePool(h.source.generation_id,h.context.reviews,h.context.goldIds,h.context.previousIds),next=await representativeReplacement(h.source.generation_id,h.context.reviews,h.context.goldIds,h.context.previousIds,h.items,old.review_id);expect(next.review_id).toBe(pool.ranked[12].review_id);expect(next.position).toBe(old.position);old.excluded=true;h.items.push({...next,confirmed_at:null});expect((await representativeReplacement(h.source.generation_id,h.context.reviews,h.context.goldIds,h.context.previousIds,h.items,next.review_id)).review_id).toBe(pool.ranked[13].review_id)})
it('review-level paired bootstrap is deterministic with 2000 draws and raw source data remains unchanged',async()=>{const h=await syntheticRepresentative(),before=JSON.stringify(h),a=await scoreRepresentative(fakeRepresentativeId,h.source,h.benchmark,h.items,h.labels,h.context.previous),b=await scoreRepresentative(fakeRepresentativeId,h.source,h.benchmark,h.items,h.labels,h.context.previous);expect(a).toEqual(b);expect(a.bootstrap.resamples).toBe(2000);expect(a.bootstrap.valid_resamples+a.bootstrap.undefined_resamples).toBe(2000);expect(a.bootstrap.seed_sha256).toBe(await holdoutHash(fakeRepresentativeId));expect(a.label_count).toBe(300);expect(a.principal_threshold).toBe(.5);expect(JSON.stringify(h)).toBe(before);expect(a.previous_difficult_test).toEqual(h.context.previous)})
it('presence F1 ignores true negatives, excludes uncertain, macro uses support >=3 and axes aggregate correct labels once per review',async()=>{
  const h=await syntheticRepresentative();h.source.findings=h.items.flatMap(i=>[{review_id:i.review_id,theme_key:'food_quality',sentiment:'positive'}]);h.labels.forEach(l=>l.choice=l.theme_key==='food_quality'?'positive':'absent')
  const c=await scoreRepresentative(fakeRepresentativeId,h.source,h.benchmark,h.items,h.labels,h.context.previous);expect(c.sol.micro_f1_human).toBe(1);expect(c.sol.precision).toBe(1);expect(c.sol.recall).toBe(1);expect(c.sol.macro_supported_labels).toBe(1);expect(c.sol.axes.quality.f1).toBe(1);expect(c.sol.axes.service.f1).toBeNull();expect(c.sol.themes.food_quality.positive.support).toBe(12)
  h.labels.filter(l=>l.theme_key==='food_quality').slice(0,10).forEach(l=>l.choice='uncertain');const u=await scoreRepresentative(fakeRepresentativeId,h.source,h.benchmark,h.items,h.labels,h.context.previous);expect(u.sol.themes.food_quality.positive.support).toBe(2);expect(u.sol.themes.food_quality.positive.uncertain).toBe(10);expect(u.sol.macro_f1_human).toBeNull();expect(u.sol.micro_f1_human).toBe(1);expect(u.sol.exact_choice_compared).toBe(290)
})
it('Jev uses average presence probabilities at 0.50 instead of treating repeats as three reviews',async()=>{const h=await syntheticRepresentative();h.source.findings=[];h.labels.forEach(l=>l.choice='absent');const review=h.items[0].review_id,decision=h.benchmark.decisions.find(r=>r.review_id===review)!;decision.repetitions.forEach((r,index)=>{r!.themes.attentiveness={choice:index===0?'positive':'absent',probabilities:{positive:index===0?1:.4,negative:0,both:0,absent:index===0?0:.6}}});h.labels.find(l=>l.review_id===review&&l.theme_key==='attentiveness')!.choice='positive';const c=await scoreRepresentative(fakeRepresentativeId,h.source,h.benchmark,h.items,h.labels,h.context.previous);expect(c.jev.themes.attentiveness.positive.tp).toBe(1);expect(c.jev.themes.attentiveness.positive.support).toBe(1);expect(c.sol.themes.attentiveness.positive.fn).toBe(1)})
async function harness(){const h=await syntheticRepresentative();let test:typeof h.test|null=null;const labels:typeof h.labels=[];const repo:RepresentativeRepository={user:'human',selection:vi.fn(async()=>h.context),predictions:vi.fn(async()=>({source:h.source,benchmark:h.benchmark})),get:vi.fn(async()=>test),items:vi.fn(async()=>h.items),labels:vi.fn(async()=>labels),create:vi.fn(async p=>{h.test.source_fingerprint=p.p_fingerprint as string;test=h.test;return h.test.id}),write:vi.fn(async(_id,_revision,action,p)=>{if(action==='confirm_review'){labels.push(...Object.entries(p.choices as object).map(([theme_key,choice])=>({review_id:p.review_id as string,theme_key,choice})) as typeof labels);h.items.find(i=>i.review_id===p.review_id)!.confirmed_at='2026-10-07T00:00:00Z'}test!.revision++})};return {...h,repo,labels,handler:representativeHandler(async()=>repo)}}
const post=(action:string,payload:object={})=>new Request('https://fixture.test',{method:'POST',body:JSON.stringify({test_id:fakeRepresentativeId,revision:0,action,...payload})})
it('loading creates nothing and neither samples nor loads model predictions; creation is explicit and idempotent',async()=>{const h=await harness();const get=await h.handler(new Request('https://fixture.test'));expect(get.status).toBe(200);expect((await get.json()).test).toBeNull();expect(h.repo.create).not.toHaveBeenCalled();expect(h.repo.predictions).not.toHaveBeenCalled();await h.handler(post('create'));await h.handler(post('create'));expect(h.repo.create).toHaveBeenCalledTimes(1);expect(h.repo.predictions).not.toHaveBeenCalled()})
it('annotation GET is blind and only English analysis text + own human responses are serialized',async()=>{const h=await harness();await h.handler(post('create'));const r=await h.handler(new Request('https://fixture.test?view=annotation')),d=await r.json();expect(d.items).toHaveLength(12);expect(d.items.every((i:{choices:object})=>Object.keys(i.choices).length===0)).toBe(true);expect(JSON.stringify(d)).not.toMatch(/"comparison"|"sol"|"jev"|rating|original_text|original_language|findings|probabilities|selection_bucket/);expect(h.repo.predictions).not.toHaveBeenCalled()})
it('explicit confirm normalizes all25 themes to absent except human-selected choices, autosaves, resumes and rejects stale writes',async()=>{const h=await harness();await h.handler(post('create'));expect((await h.handler(post('confirm_review',{review_id:h.items[0].review_id,choices:{attentiveness:'uncertain',friendly_staff:'positive'}}))).status).toBe(200);const payload=vi.mocked(h.repo.write).mock.calls[0][3];expect(Object.keys(payload.choices as object)).toHaveLength(25);expect(payload.choices).toHaveProperty('professionalism','absent');expect(payload.choices).toHaveProperty('attentiveness','uncertain');const d=await (await h.handler(new Request('https://fixture.test?view=annotation'))).json();expect(d.test.completed_reviews).toBe(1);expect(d.items[0].choices.friendly_staff).toBe('positive');expect((await h.handler(post('confirm_review',{review_id:h.items[0].review_id,choices:{}}))).status).toBe(409)})
it('validates hash and authorization; only finalization loads predictions after 12 explicit confirmed reviews, ignores forged comparisons and completed is immutable',async()=>{
  const h=await harness();await h.handler(post('create'));expect((await h.handler(post('finalize',{confirm:true}))).status).toBe(400);expect(h.repo.predictions).not.toHaveBeenCalled();h.items.forEach(i=>i.confirmed_at='2026-10-07T00:00:00Z');h.labels.push(...h.items.flatMap(i=>GOLD_KEYS.map(theme_key=>({review_id:i.review_id,theme_key,choice:'absent' as const}))));expect((await h.handler(post('finalize',{confirm:true,comparison:{forged:true}}))).status).toBe(200);expect(h.repo.predictions).toHaveBeenCalledTimes(1);expect(vi.mocked(h.repo.write).mock.calls[0][3].comparison).not.toHaveProperty('forged');h.test.status='completed';expect((await h.handler(post('confirm_review'))).status).toBe(409)
  h.test.organization_id='other';expect((await h.handler(new Request('https://fixture.test'))).status).toBe(403);expect((await representativeHandler(async()=>{throw new Error('FORBIDDEN')})(new Request('https://fixture.test'))).status).toBe(403)
})
it('no source table mutations, no provider calls and V2 SQL overlays human uncertain with explicit provenance instead of updating Gold',()=>{
  const selector=readFileSync(new URL('representative-selection.ts',import.meta.url),'utf8');expect(selector).not.toMatch(/import .*gold-core|\.rating|\.findings|\.decisions|\.probabilities|solChoice|jevChoice/)
  for(const name of ['representative-api.ts','representative-score.ts','representative-selection.ts','../representative-human-test/index.ts'])expect(readFileSync(new URL(name,import.meta.url),'utf8')).not.toMatch(/fetch\(|api\.openai|api\.typesafe|api\.apify|structuredCall|consultantNarrative/)
  const sql=readFileSync(new URL('../../migrations/20261007071613_corrected_reference_representative_holdout.sql',import.meta.url),'utf8');expect(sql).not.toMatch(/(?:update|insert into|delete from|alter table) public\.(?:analysis_gold_sets\b|analysis_gold_labels\b|analysis_gold_adjudications\b|analysis_gold_adjudication_labels\b|reviews\b|historical_report_runs\b|jev_benchmark_runs\b|review_translations\b)/);expect(sql).toContain('coalesce(h.choice,l.choice)');expect(sql).toContain("then 'gold_v1' else 'human_adjudication'");expect(sql).toContain("choice='uncertain'");expect(sql).toContain('REFERENCE_IMMUTABLE');expect(sql).toContain('HOLDOUT_IMMUTABLE');expect(sql).toContain('HOLDOUT_REVISION_CHANGED');expect(sql).toContain('revoke all');expect(sql).not.toMatch(/cron\./)
})
