import type {SupabaseClient} from 'npm:@supabase/supabase-js@2.117.2'
import {analyzeWithOpenAI} from './ai.ts'
import {createReviewProvider,type ProviderReview} from './review-provider.ts'

export async function insertAndClassifyReview(admin:SupabaseClient,establishment:{id:string;organization_id:string},providerName:string,item:ProviderReview,historical:boolean){
  const initialStatus=item.rating<=2?'to_process':item.rating===3?'new':'ignored';const initialAction=item.rating<=2
  const {data:review,error}=await admin.from('reviews').upsert({organization_id:establishment.organization_id,establishment_id:establishment.id,source_provider:providerName,external_review_id:item.externalReviewId,author_name:item.authorName,author_avatar_url:item.authorAvatarUrl,rating:item.rating,review_text:item.text,review_language:item.language,published_at:item.publishedAt,source_url:item.sourceUrl,is_historical_import:historical,requires_action:initialAction,status:initialStatus},{onConflict:'establishment_id,source_provider,external_review_id',ignoreDuplicates:true}).select().maybeSingle()
  if(error)throw error;if(!review)return false
  if(item.rating<=3){try{const analysis=await analyzeWithOpenAI(item.rating,item.text);const requires=item.rating<=2?true:analysis.requires_action;const urgency=item.rating===1&&['low','medium'].includes(analysis.urgency)?'high':analysis.urgency;await admin.from('review_ai_analyses').insert({review_id:review.id,model:Deno.env.get('OPENAI_MODEL')??'mock',sentiment:analysis.sentiment,primary_category:analysis.primary_category,secondary_categories:analysis.secondary_categories,urgency,summary:analysis.summary,key_points:analysis.key_points,response_language:analysis.response_language,analysis_status:'ok'});await admin.from('reviews').update({requires_action:requires,status:requires?'to_process':'ignored'}).eq('id',review.id);if(requires&&!historical)await admin.from('notifications').insert({organization_id:establishment.organization_id,establishment_id:establishment.id,review_id:review.id,type:'new_negative_review',title:`Nouvel avis ${item.rating}★`,body:analysis.summary,severity:urgency==='critical'?'critical':item.rating===1?'high':'warning'})}catch(error){await admin.from('review_ai_analyses').insert({review_id:review.id,model:Deno.env.get('OPENAI_MODEL')??'unavailable',analysis_status:'error',error_code:error instanceof Error?error.message.slice(0,80):'AI_ERROR'});if(item.rating<=2)await admin.from('reviews').update({requires_action:true,status:'to_process'}).eq('id',review.id)}}return true
}

export async function syncEstablishment(admin:SupabaseClient,establishment:{id:string;organization_id:string;provider_place_ref:string;last_synced_at?:string|null},historical=false){const provider=createReviewProvider();const run=(await admin.from('sync_runs').insert({organization_id:establishment.organization_id,establishment_id:establishment.id,provider:provider.name,status:'running'}).select('id').single()).data;try{const page=await provider.fetchReviews(establishment.provider_place_ref,{sort:'newest',limit:historical?50:20,since:establishment.last_synced_at??undefined});let inserted=0;for(const item of page.reviews){if(await insertAndClassifyReview(admin,establishment,provider.name,item,historical))inserted++}await admin.from('establishments').update({last_synced_at:new Date().toISOString(),next_sync_at:new Date(Date.now()+60*60000).toISOString(),sync_status:'ok',source_provider:provider.name}).eq('id',establishment.id);if(run)await admin.from('sync_runs').update({finished_at:new Date().toISOString(),status:'success',reviews_fetched:page.reviews.length,reviews_inserted:inserted}).eq('id',run.id);return{fetched:page.reviews.length,inserted,provider:provider.name}}catch(error){await admin.from('establishments').update({sync_status:'error'}).eq('id',establishment.id);if(run)await admin.from('sync_runs').update({finished_at:new Date().toISOString(),status:'failed',error_code:error instanceof Error?error.message.slice(0,80):'SYNC_ERROR',error_message:'External provider synchronization failed'}).eq('id',run.id);throw error}}
