import {describe,it,expect} from 'vitest'
import {AUDIT_V8,AUDIT_V9,AUDIT_QUOTAS,selectFindingAuditItems,validateAuditSources,validateStoredAuditItems,v9OnlyFindings,findingKey,auditSha256,compareFindingAudit,sameStoredProbability} from './v9-finding-audit-core'
import {syntheticFindingBundle,syntheticFindingAudit} from '../../../tests/fixtures/v9-finding-audit'
describe('finding-level audit selection',()=>{
  it('accepts only double-precision serialization noise, including PostgreSQL 15-digit output',()=>{expect(sameStoredProbability(.943333333333333,.9433333333333334)).toBe(true);expect(sameStoredProbability(.0533333333333333,.05333333333333334)).toBe(true);expect(sameStoredProbability(.7,.7+1e-12)).toBe(false);expect(sameStoredProbability(NaN,.7)).toBe(false);expect(sameStoredProbability(.7,undefined)).toBe(false);expect(sameStoredProbability(1.01,1)).toBe(false)})
  it('retains source integrity through database float serialization, rejects real probability/stability changes',async()=>{const {bundle,items}=await syntheticFindingAudit();for(const i of items){i.probability_positive=Number(i.probability_positive.toPrecision(15));i.probability_negative=Number(i.probability_negative.toPrecision(15))}await expect(validateStoredAuditItems(items,bundle)).resolves.toBeUndefined();items[0].probability_positive+=1e-10;await expect(validateStoredAuditItems(items,bundle)).rejects.toThrow('SOURCE_CHANGED')})
  it('selects 30 unique additional findings with exact quotas, never shared keys',async()=>{const {bundle,items}=await syntheticFindingAudit();expect(items).toHaveLength(30);expect(new Set(items.map(findingKey)).size).toBe(30);expect(new Set(items.map(i=>i.review_id)).size).toBeLessThan(30);for(const [theme,n] of Object.entries(AUDIT_QUOTAS))expect(items.filter(i=>theme==='other'?!Object.keys(AUDIT_QUOTAS).includes(i.theme_key):i.theme_key===theme)).toHaveLength(n);expect(items.every(i=>!bundle.v8.findings.some(f=>findingKey(f)===findingKey(i)))).toBe(true)})
  it('hashes the prescribed concatenation and is invariant to input order, probabilities and ratings',async()=>{const b=syntheticFindingBundle(),first=(await selectFindingAuditItems(b)).items;for(const i of first)expect(i.selection_hash).toBe(await auditSha256(AUDIT_V9+i.theme_key+i.review_id+i.sentiment));b.v9.findings.reverse();b.v8.snapshot.reviews.reverse();b.v9.snapshot.reviews.reverse();b.v9.findings.forEach(f=>{f.probability_positive=.8;f.probability_negative=.7;f.repeat_stable=!f.repeat_stable});expect((await selectFindingAuditItems(b)).items.map(findingKey)).toEqual(first.map(findingKey))})
  it('fills missing quotas using stable hash order without textless findings',async()=>{const b=syntheticFindingBundle();b.v9.findings=b.v9.findings.filter(f=>!['attentiveness','professionalism'].includes(f.theme_key));b.v9.findings.push({review_id:b.v9.snapshot.reviews.at(-1)!.id,theme_key:'friendly_staff',sentiment:'positive',probability_positive:.9,probability_negative:0,repeat_stable:true});const selected=await selectFindingAuditItems(b);expect(selected.items).toHaveLength(30);expect(selected.items.some(i=>i.review_id===b.v9.snapshot.reviews.at(-1)!.id)).toBe(false);expect(selected.selection.quota_achieved.attentiveness).toBe(0)})
  it('checks full polarity key: a positive common finding does not exclude a negative extra',()=>{const b=syntheticFindingBundle();b.v9.findings.push({...b.v9.findings[0],sentiment:'negative'});expect(v9OnlyFindings(b).some(f=>f.review_id===b.v8.findings[0].review_id&&f.sentiment==='negative')).toBe(true)})
  it('rejects incomplete/wrong-language/changed datasets and non-completed sources',()=>{for(const mutate of [(b:ReturnType<typeof syntheticFindingBundle>)=>b.v9.snapshot.reviews.pop(),(b:ReturnType<typeof syntheticFindingBundle>)=>{b.v9.snapshot.reviews[0].analysis_language='ru'},(b:ReturnType<typeof syntheticFindingBundle>)=>{b.v9.snapshot.reviews[0].analysis_text='changed'},(b:ReturnType<typeof syntheticFindingBundle>)=>{b.v8.status='running'}]){const b=syntheticFindingBundle();mutate(b);expect(()=>validateAuditSources(b)).toThrow()}})
  it('fails safely when fewer than 30 candidates exist',async()=>{const b=syntheticFindingBundle();b.v9.findings=b.v9.findings.slice(0,20);await expect(selectFindingAuditItems(b)).rejects.toThrow('INSUFFICIENT')})
  it('persists only hashes and finding metadata, validates retained source integrity',async()=>{const {bundle,items,selection}=await syntheticFindingAudit();expect(JSON.stringify(selection)).not.toMatch(/analysis_text":|original_text|Synthetic review|rating/);await expect(validateStoredAuditItems(items,bundle)).resolves.toBeUndefined();items[0].analysis_text_sha256='0'.repeat(64);await expect(validateStoredAuditItems(items,bundle)).rejects.toThrow('SOURCE_CHANGED')})
})
describe('observed precision of sampled additional findings',()=>{
  it('maps both to valid for either polarity, uncertain excluded; absence/opposite reject',async()=>{const {items}=await syntheticFindingAudit(),labels=items.map((i,n)=>({item_id:i.id,choice:n<10?'both' as const:n<20?'uncertain' as const:n<25?'absent' as const:i.sentiment==='positive'?'negative' as const:'positive' as const}));const c=compareFindingAudit(items,labels);expect(c.validated).toBe(10);expect(c.rejected).toBe(10);expect(c.uncertain).toBe(10);expect(c.validation_rate).toBe(.5);expect(Object.values(c.by_theme).reduce((n,v)=>n+v.controlled,0)).toBe(30)})
  it('uses the finding polarity probability for exploratory filtering, handles empty slices',async()=>{const {items}=await syntheticFindingAudit();items.forEach((i,n)=>{i.probability_positive=i.sentiment==='positive'?(n<15?.55:.85):.99;i.probability_negative=i.sentiment==='negative'?(n<15?.55:.85):.99});const c=compareFindingAudit(items,items.map((i,n)=>({item_id:i.id,choice:n<15?'absent':'both'})));expect(c.exploratory_thresholds.map(t=>t.threshold)).toEqual([.5,.6,.7,.8,.9]);expect(c.exploratory_thresholds[1]).toMatchObject({controlled:15,validated:15,rejected:0,removed_rejected:15,removed_validated:0,retained_validated_fraction:1,validation_rate:1,exploratory:true});expect(c.exploratory_thresholds[4].validation_rate).toBeNull()})
  it('computes stable/unstable groups and null rates for all-uncertain answers',async()=>{const {items}=await syntheticFindingAudit();const c=compareFindingAudit(items,items.map(i=>({item_id:i.id,choice:i.repeat_stable?'both':'absent'})));expect(c.stability.stable.validation_rate).toBe(1);expect(c.stability.unstable.validation_rate).toBe(0);const u=compareFindingAudit(items,items.map(i=>({item_id:i.id,choice:'uncertain'})));expect(u.validation_rate).toBeNull();expect(u.interpretation).toBe('not_evaluable')})
  it.each([[26,'very_good_additional_signal'],[21,'useful_requires_calibration'],[20,'probable_over_detection']] as const)('uses descriptive interpretation with %s valid findings',async(n,interpretation)=>{const {items}=await syntheticFindingAudit();expect(compareFindingAudit(items,items.map((i,j)=>({item_id:i.id,choice:j<n?'both':'absent'}))).interpretation).toBe(interpretation)})
  it('cannot finalize without all explicit responses',async()=>{const {items}=await syntheticFindingAudit();expect(()=>compareFindingAudit(items,[])).toThrow('INCOMPLETE')})
  it('leaves both frozen sources intact',async()=>{const b=syntheticFindingBundle(),before=JSON.stringify(b);expect(b.v8.generation_id).toBe(AUDIT_V8);await selectFindingAuditItems(b);expect(JSON.stringify(b)).toBe(before)})
})
