import {describe,it,expect,vi} from 'vitest'
import {readFileSync} from 'node:fs'
import {findingAuditHandler,findingAuditProjection,type FindingAuditRepository} from './v9-finding-audit-api'
import {compareFindingAudit,type AuditLabel} from './v9-finding-audit-core'
import {syntheticFindingAudit,fixtureUuid} from '../../../tests/fixtures/v9-finding-audit'
async function fixture(){const f=await syntheticFindingAudit();let audit:typeof f.audit|null=null,labels:AuditLabel[]=[]
  const repo:FindingAuditRepository={user:fixtureUuid(999),loadBundle:vi.fn(async()=>f.bundle),get:vi.fn(async id=>{if(id&&id!==f.audit.id)throw new Error('FINDING_AUDIT_NOT_FOUND');return audit}),items:vi.fn(async()=>f.items),labels:vi.fn(async()=>labels),create:vi.fn(async()=>{audit=f.audit;return audit.id}),write:vi.fn(async(_id,revision,action,payload)=>{if(audit!.status==='completed')throw new Error('FINDING_AUDIT_IMMUTABLE');if(revision!==audit!.revision)throw new Error('FINDING_AUDIT_REVISION_CHANGED');if(action==='save_choice'){labels=labels.filter(l=>l.item_id!==payload.item_id);labels.push({item_id:payload.item_id,choice:payload.choice} as AuditLabel)}else{audit!.status='completed';audit!.comparison=compareFindingAudit(f.items,labels)}audit!.revision++})}
  const handler=findingAuditHandler(async()=>repo),call=(body?:Record<string,unknown>,query='')=>handler(new Request('https://test/audit'+query,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined));return {...f,repo,call,setLabels:(value:AuditLabel[])=>{labels=value},getAudit:()=>audit}
}
describe('private blind human audit API',()=>{
  it('GET/foreground never creates or selects items; POST create is idempotent',async()=>{const f=await fixture();expect(await (await f.call()).json()).toEqual({eligible:true,audit:null,items:[]});expect(f.repo.create).not.toHaveBeenCalled();await f.call({action:'create'});await f.call({action:'create'});expect(f.repo.create).toHaveBeenCalledTimes(1);const input=(f.repo.create as ReturnType<typeof vi.fn>).mock.calls[0][0];expect(JSON.stringify(input)).not.toMatch(/Synthetic review|original_text|analysis_text":/);expect(input.p_items).toHaveLength(30)})
  it('whitelists draft fields, including POST response; no model/metadata clues',async()=>{const f=await fixture(),response=await (await f.call({action:'create'})).json();expect(response.audit.status).toBe('draft');expect(response.items[0]).toHaveProperty('analysis_text');const json=JSON.stringify(response);expect(json).not.toMatch(/comparison|v9.only|probability|sentiment|repeat_stable|rating|original_text|original_language|analysis_source|selection_hash|source_fingerprint/);expect(Object.keys(response.items[0]).sort()).toEqual(['analysis_text','id','position','theme_key']);const summary=await (await f.call(undefined,'?view=status')).json();expect(summary.items).toEqual([])})
  it('requires explicit valid choice and selected item UUID, persists absent and uncertain',async()=>{const f=await fixture();await f.call({action:'create'});expect((await f.call({action:'save_choice',revision:0,item_id:f.items[0].id})).status).toBe(400);expect((await f.call({action:'save_choice',revision:0,item_id:fixtureUuid(888),choice:'positive'})).status).toBe(400);const saved=await (await f.call({action:'save_choice',revision:0,item_id:f.items[0].id,choice:'uncertain'})).json();expect(saved.audit.completed_findings).toBe(1);expect(saved.items[0].choice).toBe('uncertain');const resumed=await (await f.call(undefined,'?view=annotation')).json();expect(resumed.items[0].choice).toBe('uncertain');expect((await f.call({action:'save_choice',revision:1,item_id:f.items[0].id,choice:'absent'})).status).toBe(200)})
  it('rejects stale revisions, incomplete or unconfirmed finalization',async()=>{const f=await fixture();await f.call({action:'create'});expect((await f.call({action:'save_choice',revision:42,item_id:f.items[0].id,choice:'both'})).status).toBe(409);expect((await f.call({action:'finalize',revision:0,confirm:true})).status).toBe(400);f.setLabels(f.items.map(i=>({item_id:i.id,choice:'both'})));expect((await f.call({action:'finalize',revision:0})).status).toBe(400)})
  it('only reveals stored results after finalization, then prevents all corrections',async()=>{const f=await fixture();await f.call({action:'create'});f.setLabels(f.items.map(i=>({item_id:i.id,choice:'both'})));const result=await (await f.call({action:'finalize',revision:0,confirm:true})).json();expect(result.audit.status).toBe('completed');expect(result.comparison.validated).toBe(30);expect(result.comparison.cases[0]).toHaveProperty('probability_positive');expect((await f.call({action:'save_choice',revision:1,item_id:f.items[0].id,choice:'absent'})).status).toBe(409);expect(f.repo.write).toHaveBeenCalledTimes(1)})
  it('rejects foreign tenants, IDs and changed source texts before writing',async()=>{const f=await fixture();await f.call({action:'create'});f.getAudit()!.organization_id=fixtureUuid(444);expect((await f.call()).status).toBe(403);f.getAudit()!.organization_id=f.bundle.v9.organization_id;expect((await f.call(undefined,'?audit_id='+fixtureUuid(222))).status).toBe(404);f.bundle.v8.findings=[];expect((await f.call()).status).toBe(409);expect(f.repo.write).not.toHaveBeenCalled()})
  it('rejects anonymous and unauthorized roles, sanitizes failures',async()=>{for(const [code,status] of [['UNAUTHORIZED',401],['FORBIDDEN',403],['private customer text',500]] as const){const handler=findingAuditHandler(async()=>{throw new Error(code)}),r=await handler(new Request('https://test/'));expect(r.status).toBe(status);expect(await r.text()).not.toContain('private customer text')}})
  it('draft projection never leaks persisted probabilities through spread',async()=>{const f=await syntheticFindingAudit();expect(findingAuditProjection(f.audit,f.items,[],f.bundle,true)).not.toHaveProperty('comparison')})
  it('new production path contains no model, backfill or existing-resource writes',()=>{const paths=['supabase/functions/v9-finding-human-audit/index.ts','supabase/functions/_shared/v9-finding-audit-api.ts','supabase/functions/_shared/v9-finding-audit-core.ts'],all=paths.map(p=>readFileSync(p,'utf8')).join('\n');expect(all).not.toMatch(/fetch\(|structuredCall|extractConsultantBatch|consultantNarrative|api\.openai|api\.typesafe|apify|backfill-review/);expect(all).not.toMatch(/\.from\([^)]*\)\.(insert|update|upsert|delete)\(/);expect(all).toContain("['owner','admin','manager']");expect(all).toContain("rpc('create_v9_finding_audit'")})
})
