import {requireUser,assertMembership} from '../_shared/auth.ts'
import {enforceRateLimit} from '../_shared/rate-limit.ts'
import {v12Handler,type V12Configuration} from '../_shared/jev-v12-api.ts'
import {prepareV12,V12_SOURCE_BENCHMARK,V12_PROTECTED_HOLDOUT,type V12Run,type AiThemeRecheck} from '../_shared/jev-v12-core.ts'
import {V12_QUESTION_SET} from '../_shared/jev-v12-config.ts'
import type {AiBenchmarkRun,AiPreannotation} from '../_shared/ai-exploratory-benchmark.ts'
import type {NegativeTask} from '../_shared/negative-validation-score.ts'
Deno.serve(v12Handler(async request=>{const ctx=await requireUser(request);if(request.method==='POST')enforceRateLimit('v12:'+ctx.user.id,20,60_000);const {data:source,error}=await ctx.admin.from('analysis_negative_ai_exploratory_runs').select('*').eq('id',V12_SOURCE_BENCHMARK).eq('status','completed').single();if(error||!source)throw new Error('V12_SOURCE_REQUIRED');await assertMembership(ctx.client,ctx.user.id,source.organization_id,['owner','admin','manager']);const get=async()=>{const {data,error}=await ctx.admin.from('analysis_jev_v12_runs').select('*').eq('organization_id',source.organization_id).eq('source_benchmark_id',source.id).eq('configuration_id',V12_QUESTION_SET).maybeSingle();if(error)throw new Error('V12_READ_FAILED');return data as V12Run|null},rows=async(table:string,field:string,id:string)=>{const result=[];for(let n=0;;n+=500){const {data,error}=await ctx.admin.from(table).select('*').eq(field,id).order(table.includes('preannotations')||table.includes('rechecks')?'review_id':'id').range(n,n+499);if(error)throw new Error('V12_SOURCE_READ_FAILED');result.push(...data);if(data.length<500)break}return result}
 return {get,configured:()=>!!Deno.env.get('TYPESAFE_API_KEY')?.trim(),configuration:async()=>{const {data,error}=await ctx.admin.from('analysis_jev_experimental_configurations').select('*').eq('id',V12_QUESTION_SET).single();if(error||!data)throw new Error('V12_CONFIG_NOT_FROZEN');return data as V12Configuration},prepare:async()=>{const [tasks,initial,rechecks]=await Promise.all([rows('analysis_negative_ai_exploratory_tasks','run_id',source.id),rows('analysis_negative_validation_ai_preannotations','experiment_id',source.source_experiment_id),rows('analysis_negative_ai_theme_rechecks','exploratory_run_id',source.id)]);const sourceIds=source.dataset_snapshot.map((i:{review_id:string})=>i.review_id),{data:protectedRows,error:pe}=await ctx.admin.from('analysis_v11_independent_holdout_items').select('review_id').eq('holdout_id',V12_PROTECTED_HOLDOUT).in('review_id',sourceIds);if(pe)throw new Error('V12_HOLDOUT_CHECK_FAILED');const envRate=Number(Deno.env.get('JEV_INPUT_USD_PER_MILLION')??source.input_rate_usd_per_million);return await prepareV12(source as AiBenchmarkRun,tasks as NegativeTask[],initial as AiPreannotation[],rechecks as AiThemeRecheck[],protectedRows.map(r=>r.review_id),Number.isFinite(envRate)&&envRate>=0?envRate:Number(source.input_rate_usd_per_million))},result:async id=>{await get();const {data,error}=await ctx.admin.from('analysis_jev_v12_results').select('comparison').eq('run_id',id).maybeSingle();if(error)throw new Error('V12_READ_FAILED');return data?.comparison??null},progress:async id=>{await get();const {data,error}=await ctx.admin.from('analysis_jev_v12_tasks').select('status').eq('run_id',id);if(error)throw new Error('V12_READ_FAILED');return {total:data.length,completed:data.filter(t=>t.status==='completed').length,failed:data.filter(t=>t.status==='failed').length}},start:async prepared=>{const {data,error}=await ctx.admin.rpc('start_experimental_jev_v12',{p_user:ctx.user.id,p_source:source.id,p_configuration:V12_QUESTION_SET,p_confirm_cost:true,p_prepared:prepared});if(error)throw new Error(/HOLDOUT/.test(error.message)?'V12_HOLDOUT_PROTECTED':'V12_START_FAILED');return data as string}}
}))
