import { Check, CheckCircle2, ChevronRight, Link2, LoaderCircle, MapPin, Search, ShieldCheck } from 'lucide-react'
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useApp } from '../app/AppContext'
import { EstablishmentAvatar } from '../components/ui/EstablishmentAvatar'
import { PageHeader } from '../components/ui/PageHeader'
import { Stars } from '../components/ui/Stars'
import { MockReviewProvider, type PlaceCandidate } from '../services/review-provider'

type Step='input'|'results'|'confirm'|'import'
const provider=new MockReviewProvider()

export function AddEstablishmentPage(){
  const navigate=useNavigate();const {addEstablishment,establishments,plan}=useApp();const [step,setStep]=useState<Step>('input');const [query,setQuery]=useState('');const [results,setResults]=useState<PlaceCandidate[]>([]);const [selected,setSelected]=useState<PlaceCandidate>();const [confirmed,setConfirmed]=useState(false);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [progress,setProgress]=useState(0)
  const quotaReached=establishments.length>=plan.maxEstablishments
  const search=async()=>{if(!query.trim()){setError('Collez un lien Google Maps ou saisissez un nom et une ville.');return}setLoading(true);setError('');try{const found=await provider.resolvePlace(query);setResults(found);setStep('results')}catch{setError('Le fournisseur est momentanément indisponible. Réessayez dans quelques instants.')}finally{setLoading(false)}}
  const activate=async()=>{if(!selected||!confirmed)return;setStep('import');for(const value of [25,55,82,100]){await new Promise((resolve)=>setTimeout(resolve,330));setProgress(value)}const item=addEstablishment(selected);window.setTimeout(()=>navigate(`/etablissements/${item.id}`),450)}
  return <><PageHeader title="Ajouter un établissement" back/>
    <div className="stepper" aria-label="Progression"><i className="done"/><i className={step!=='input'?'done':''}/><i className={['confirm','import'].includes(step)?'done':''}/><i className={step==='import'?'done':''}/></div>
    {quotaReached&&<div className="quota-alert"><ShieldCheck/><div><strong>Quota atteint</strong><span>Votre plan autorise {plan.maxEstablishments} établissements. Modifiez votre plan pour continuer.</span></div></div>}
    {step==='input'&&<section className="flow-card card"><span className="flow-icon"><MapPin/></span><h2>Quel établissement surveiller ?</h2><p>Collez son lien Google Maps ou recherchez-le par nom et adresse.</p><label className="search-field"><Search/><input value={query} onChange={(e)=>setQuery(e.target.value)} onKeyDown={(e)=>e.key==='Enter'&&search()} placeholder="Nom, ville ou lien Google Maps" autoFocus/></label><div className="input-hint"><Link2 size={15}/>Ex. Le Petit Hanoi, Paris</div>{error&&<p className="field-error">{error}</p>}<button className="primary-button full-width" onClick={search} disabled={loading||quotaReached}>{loading?<LoaderCircle className="spin"/>:<Search/>}{loading?'Recherche…':'Rechercher'}</button></section>}
    {step==='results'&&<section><div className="flow-heading"><h2>{results.length} établissement{results.length>1?'s':''} trouvé{results.length>1?'s':''}</h2><p>Choisissez la fiche publique à surveiller.</p></div><div className="candidate-list">{results.map((candidate)=><button key={candidate.placeRef} className="candidate-card card" onClick={()=>{setSelected(candidate);setStep('confirm')}}><EstablishmentAvatar id={candidate.placeRef} name={candidate.name} large/><span><strong>{candidate.name}</strong><small>{candidate.address}</small><span className="rating-line"><b>{candidate.rating}</b><Stars rating={Math.round(candidate.rating)} compact/><em>{candidate.reviewCount} avis</em></span></span><ChevronRight/></button>)}</div><button className="secondary-button full-width" onClick={()=>setStep('input')}>Modifier la recherche</button></section>}
    {step==='confirm'&&selected&&<section className="flow-card card"><span className="flow-icon success"><CheckCircle2/></span><h2>Confirmer la fiche</h2><div className="confirm-place"><EstablishmentAvatar id={selected.placeRef} name={selected.name} large/><div><strong>{selected.name}</strong><p>{selected.address}</p><span className="rating-line"><b>{selected.rating}</b><Stars rating={Math.round(selected.rating)} compact/><em>{selected.reviewCount} avis</em></span></div></div><label className="consent-check"><input type="checkbox" checked={confirmed} onChange={(e)=>setConfirmed(e.target.checked)}/><span><Check/> </span><p>Je confirme gérer ou être autorisé à surveiller cet établissement.</p></label><button className="primary-button full-width" disabled={!confirmed} onClick={activate}><ShieldCheck/>Activer la surveillance</button><button className="text-button full-width" onClick={()=>setStep('results')}>Choisir une autre fiche</button></section>}
    {step==='import'&&<section className="flow-card import-card card"><span className="flow-icon"><LoaderCircle className={progress<100?'spin':''}/></span><h2>{progress<100?'Préparation en cours':'Tout est prêt'}</h2><p>Vous pouvez quitter cet écran : les analyses continueront en arrière-plan.</p><div className="progress-track"><i style={{width:`${progress}%`}}/></div><ul><li className={progress>=25?'done':''}><Check/>Fiche identifiée</li><li className={progress>=55?'done':''}><Check/>Avis récupérés</li><li className={progress>=82?'done':''}><Check/>Analyse des avis utiles</li><li className={progress>=100?'done':''}><Check/>Finalisation</li></ul></section>}
  </>
}
