import {useEffect,useRef,useState} from 'react'
import {Link,useNavigate} from 'react-router-dom'
import {useQuery,useQueryClient} from '@tanstack/react-query'
import {useApp} from '../app/AppContext'
import {useI18n} from '../i18n'
import {useJevAccess} from '../lib/use-jev-access'
import {PageHeader} from '../components/ui/PageHeader'
import {aiBenchmarkApi,type AiBenchmarkView} from '../lib/ai-exploratory-benchmark'
import {aiBenchmarkMessages} from '../i18n/ai-exploratory-benchmark'
import {exploratoryApi} from '../lib/jev-exploratory'
import {ARTISAN_AI_SOURCE} from '../../supabase/functions/_shared/ai-exploratory-benchmark'
import {GOLD_TAXONOMY} from '../../supabase/functions/_shared/gold-taxonomy'
import './JevBenchmarkPage.css'
import './GoldSetPage.css'
import './JevExploratoryPage.css'
export function AiExploratoryBenchmarkEntry(){const {language}=useI18n(),t=aiBenchmarkMessages[language];return <section className="card jev-card"><h2>{t.title}</h2><p>{t.intro}</p><p>{t.reference}</p><Link className="primary-button full-width exploratory-link" to="/plus/ai-exploratory-benchmark">{t.open}</Link></section>}
export function AiExploratoryBenchmarkPage(){const {currentUser,demoMode}=useApp(),{language}=useI18n(),t=aiBenchmarkMessages[language],access=useJevAccess(currentUser.id,demoMode),client=useQueryClient(),navigate=useNavigate(),lock=useRef(false),[busy,setBusy]=useState(false),[error,setError]=useState(false),key=['ai-benchmark',currentUser.id],markerKey='ai-benchmark-pending:'+currentUser.id,marker=()=>{try{return localStorage.getItem(markerKey)==='1'}catch{return false}},mark=(v:boolean)=>{try{if(v)localStorage.setItem(markerKey,'1');else localStorage.removeItem(markerKey)}catch{/* Server state remains authoritative. */}}
 const q=useQuery({queryKey:key,enabled:access.data===true,retry:false,staleTime:0,queryFn:async()=>{const d=await aiBenchmarkApi();mark(false);return d},refetchInterval:query=>!document.hidden&&(marker()||['queued','running'].includes(query.state.data?.run?.status??''))?2500:false})
 useEffect(()=>{const refresh=()=>{if(!document.hidden)void client.invalidateQueries({queryKey:['ai-benchmark',currentUser.id]})};window.addEventListener('pageshow',refresh);document.addEventListener('visibilitychange',refresh);return()=>{window.removeEventListener('pageshow',refresh);document.removeEventListener('visibilitychange',refresh)}},[client,currentUser.id])
 async function start(){if(lock.current||q.isError||q.isPending||marker())return;lock.current=true;setBusy(true);setError(false);mark(true);try{client.setQueryData(key,await aiBenchmarkApi(true));mark(false)}catch{setError(true);await q.refetch()}finally{lock.current=false;setBusy(false)}}
 async function review(){if(lock.current||q.isError)return;lock.current=true;setBusy(true);setError(false);try{const d=await exploratoryApi(undefined,'create',{source_id:ARTISAN_AI_SOURCE,source_kind:'negative_validation'});if(!d.run||d.run.status!=='completed')throw new Error();navigate('/plus/jev-exploratory?id='+d.run.id)}catch{setError(true)}finally{lock.current=false;setBusy(false)}}
 return <><PageHeader title={t.title} back/><div className="jev-page gold-page exploratory-page">{access.isPending||q.isPending&&access.data===true?<p>{t.loading}</p>:access.data!==true?<p>{t.denied}</p>:<>{(error||q.isError)&&<section className="card jev-card" role="alert"><p>{t.error}</p><button className="secondary-button" disabled={busy||q.isFetching} onClick={()=>void q.refetch()}>{t.check}</button></section>}{q.data&&<AiBenchmarkWorkspace data={q.data} busy={busy||q.isError||marker()} start={start} review={review}/>}</>}<Link to="/plus/jev-benchmark">{t.back}</Link></div></>
}
export function AiBenchmarkWorkspace({data,busy,start,review}:{data:AiBenchmarkView;busy:boolean;start:()=>Promise<void>;review:()=>Promise<void>}){const {language}=useI18n(),t=aiBenchmarkMessages[language],[confirm,setConfirm]=useState(false),c=data.comparison,n=(v:number|null,d=3)=>v===null?t.insufficient:v.toLocaleString(language==='fr'?'fr-FR':'vi-VN',{maximumFractionDigits:d}),pct=(v:number|null)=>v===null?t.insufficient:n(v*100,1)+' %',metrics=(m:{precision:number|null;recall:number|null;f1:number|null;support:number})=><dl className="jev-pairs"><dt>{t.support}</dt><dd>{m.support}</dd><dt>{t.precision}</dt><dd>{n(m.precision)}</dd><dt>{t.recall}</dt><dd>{n(m.recall)}</dd><dt>{t.f1}</dt><dd>{n(m.f1)}</dd></dl>
 const errors=(kind:'missed_negative'|'false_positive_theme')=>(['v9','v11'] as const).map(v=><div key={v}><h3>{v.toUpperCase()} · {c![v].errors.filter(e=>e.kind===kind).length}</h3>{c![v].errors.filter(e=>e.kind===kind).map(e=><article className="jev-theme-detail" key={e.review_id+e.theme_key+e.polarity}><h4>{GOLD_TAXONOMY[e.theme_key][language]} · {t[e.polarity]}</h4><p className="jev-id">{e.review_id}</p><p>{t.initial} : {e.predicted} · {t.ai} : {e.ai_reference}</p><details><summary>{t.text}</summary><p className="gold-text" lang="en">{c!.reviews.find(i=>i.review_id===e.review_id)?.analysis_text}</p></details></article>)}</div>)
 return <><section className="card jev-card"><h2>{t.reference}</h2><p>{t.intro}</p><p>{t.ready} : {data.english_ready} / 32</p><p>{t.labels} : {data.reference_labels} · {data.reference_models.join(', ')}</p><p>{t.warning}</p><p>{t.bias}</p>{data.eligibility_error&&<p role="alert">{data.eligibility_error}</p>}{!data.run&&<button className="primary-button full-width" disabled={busy||!data.ready} onClick={()=>setConfirm(true)}>{t.start}</button>}{confirm&&!data.run&&<div role="alertdialog" aria-modal="true" aria-label={t.start}><p>{t.cost}</p><button className="primary-button" disabled={busy} onClick={()=>void start().then(()=>setConfirm(false))}>{t.confirm}</button><button className="secondary-button" disabled={busy} onClick={()=>setConfirm(false)}>{t.cancel}</button></div>}{data.run&&<p className="jev-id">{data.run.id} · {data.run.status}</p>}</section>
 {data.run&&['queued','running'].includes(data.run.status)&&<section className="card jev-card" role="status"><p>{t.waiting}</p><p>{data.progress.completed} / {data.progress.total} · {data.progress.failed} unavailable</p><progress max={data.progress.total||192} value={data.progress.completed+data.progress.failed}/></section>}{data.run?.error_code&&<p role="alert">{data.run.error_code}</p>}
 {c&&<><section className="card jev-card"><h2>{t.results}</h2><p>{t.warning}</p><p>{c.coverage.common} / {c.sample_reviews} · {c.uncertain_reference_labels} uncertain</p>{!c.coverage.complete&&<p role="alert">{t.partial}</p>}{(['v9','v11'] as const).map(v=><div key={v}><h3>{v.toUpperCase()}</h3>{metrics(c[v].overall)}<p>{t.micro} : {n(c[v].micro_f1)}</p><p>{t.macro} : {n(c[v].macro_f1)}</p><p>{t.exact} : {pct(c[v].exact_choice_agreement)}</p><p>{t.stability} : {pct(c[v].repeat_choice_stability)}</p></div>)}</section>
 <section className="card jev-card"><h3>{t.negative}</h3>{(['v9','v11'] as const).map(v=><div key={v}><h4>{v.toUpperCase()}</h4>{metrics(c[v].negative)}</div>)}</section><section className="card jev-card"><h3>{t.positive}</h3>{(['v9','v11'] as const).map(v=><div key={v}><h4>{v.toUpperCase()}</h4>{metrics(c[v].positive)}</div>)}</section>
 {(['quality','service','atmosphere','price'] as const).map(axis=><section className="card jev-card" key={axis}><h3>{t[axis]}</h3>{(['negative','positive'] as const).map(p=><div key={p}><p>{t[p]} · {t.support} {c.v9.axes[axis][p].support}</p><p>V9 F1 {n(c.v9.axes[axis][p].f1)} · V11 F1 {n(c.v11.axes[axis][p].f1)}</p></div>)}</section>)}
 <section className="card jev-card"><h3>{t.disagreement} : {c.disagreements.length}</h3><p>{t.reviewHelp}</p><button className="primary-button full-width" disabled={busy} onClick={()=>void review()}>{t.review}</button></section>
 {(['missed_negative','false_positive_theme'] as const).map(kind=><details className="card jev-card" key={kind}><summary>{kind==='missed_negative'?t.fn:t.fp}</summary>{errors(kind)}</details>)}
 <section className="card jev-card"><h3>{t.usage}</h3>{(['v9','v11'] as const).map(v=><div key={v}><h4>{v.toUpperCase()}</h4><p>{t.models} : {c[v].usage.served_models.join(', ')}</p><p>{c[v].usage.requests} requests · Tokens {c[v].usage.input_tokens} / {c[v].usage.output_tokens}</p><p>USD {n(c[v].usage.estimated_cost_usd,6)}</p><p>{t.requestTime} : {n(c[v].usage.request_elapsed_sum_ms/1000)} s</p>{!c[v].usage.usage_complete&&<p>{t.partial}</p>}</div>)}<p>USD {n(c.total_estimated_cost_usd,6)} · {t.total} : {n(c.end_to_end_elapsed_ms===null?null:c.end_to_end_elapsed_ms/1000)} s</p>{c.model_version_confounded&&<p role="alert">{t.changed}</p>}</section>
 </>}</>
}
