import {useState,useRef,useEffect} from 'react'
import {useQuery,useQueryClient} from '@tanstack/react-query'
import {Link,useSearchParams,useNavigate} from 'react-router-dom'
import {Info} from 'lucide-react'
import {useApp} from '../app/AppContext'
import {useJevAccess} from '../lib/use-jev-access'
import {PageHeader} from '../components/ui/PageHeader'
import {useI18n} from '../i18n'
import {goldMessages} from '../i18n/gold'
import {goldApi,type GoldData} from '../lib/human-gold'
import type {GoldChoice,GoldTheme} from '../../supabase/functions/_shared/gold-taxonomy'
import type {blindGoldProjection} from '../../supabase/functions/_shared/gold-api'
import './JevBenchmarkPage.css'
import './GoldSetPage.css'
type Existing=ReturnType<typeof blindGoldProjection>
export function GoldSetEntry(){
  const {currentUser}=useApp(),{language}=useI18n(),t=goldMessages[language],navigate=useNavigate(),lock=useRef(false),[busy,setBusy]=useState(false),[error,setError]=useState(false)
  const query=useQuery({queryKey:['human-gold-entry',currentUser.id],queryFn:()=>goldApi(undefined,undefined,{},true),retry:false,staleTime:0})
  async function open(){if(lock.current||query.isPending||query.isError)return;const existing=query.data?.gold_set;if(existing){navigate('/plus/gold-set?id='+existing.id);return}lock.current=true;setBusy(true);setError(false);try{const data=await goldApi(undefined,'create');if(!data.gold_set)throw new Error('GOLD_CREATE_FAILED');navigate('/plus/gold-set?id='+data.gold_set.id)}catch{setError(true);await query.refetch()}finally{lock.current=false;setBusy(false)}}
  return <section className="card jev-card"><h3>{t.title}</h3><p>{t.intro}</p><p>{t.ready}</p><button className="primary-button full-width" disabled={busy||query.isPending||query.isError} onClick={()=>void open()}>{busy?t.saving:query.data?.gold_set?.status==='completed'?t.results:query.data?.gold_set?t.resume:t.create}</button>{(error||query.isError)&&<p role="alert">{t.error}<button className="secondary-button" onClick={()=>void query.refetch()}>{t.check}</button></p>}</section>
}
export function GoldSetPage(){
  const {currentUser,demoMode}=useApp(),{language}=useI18n(),t=goldMessages[language],access=useJevAccess(currentUser.id,demoMode),[params,setParams]=useSearchParams(),client=useQueryClient(),[busy,setBusy]=useState(false),[error,setError]=useState(''),lock=useRef(false)
  const [reconciliation,setReconciliation]=useState(0),id=params.get('id')??undefined,key=['human-gold',currentUser.id,id]
  const query=useQuery<GoldData>({queryKey:key,queryFn:()=>goldApi(id),enabled:access.data===true,retry:false,staleTime:0})
  useEffect(()=>{const resume=()=>{if(!document.hidden)void client.invalidateQueries({queryKey:['human-gold',currentUser.id]})};window.addEventListener('pageshow',resume);document.addEventListener('visibilitychange',resume);return()=>{window.removeEventListener('pageshow',resume);document.removeEventListener('visibilitychange',resume)}},[client,currentUser.id])
  async function action(kind:string,payload:Record<string,unknown>={}) {
    if(lock.current||query.isPending||query.isError)return false
    lock.current=true;setBusy(true);setError('')
    try{const data=await goldApi(query.data?.gold_set?.id,kind,{revision:query.data?.gold_set?.revision,...payload});client.setQueryData(key,data);if(data.gold_set&&!id){client.setQueryData(['human-gold',currentUser.id,data.gold_set.id],data);setParams({id:data.gold_set.id},{replace:true})}return true}
    catch(e){const code=e instanceof Error?e.message:'GOLD_CONNECTION_ERROR';setError(code);await query.refetch();if(code==='GOLD_REVISION_CHANGED')setReconciliation(v=>v+1);return false}
    finally{lock.current=false;setBusy(false)}
  }
  return <><PageHeader title={t.title} back/><main className="jev-page gold-page"><h2>{t.title}</h2><p>{t.bias}</p>
    {access.isPending||query.isPending&&access.data===true?<p role="status">{t.loading}</p>:access.data!==true?<p>{t.denied}</p>:<>
      {(query.isError||error)&&<section role="alert" className="card jev-card"><p>{error==='GOLD_REVISION_CHANGED'?t.conflict:error==='GOLD_REPLACEMENT_UNAVAILABLE'?t.noReplacement:t.error}</p><button className="secondary-button" onClick={()=>void query.refetch()} disabled={busy||query.isFetching}>{t.check}</button></section>}
      {query.data?.gold_set?query.data.gold_set.status==='completed'?<GoldResults data={query.data as Existing}/>:<GoldAnnotation key={query.data.gold_set.id+':'+reconciliation} data={query.data as Existing} user={currentUser.id??''} busy={busy||query.isError} action={action}/>:!query.isError&&<section className="card jev-card"><h3>{t.source}</h3><p>{t.intro}</p><p>{t.ready}</p><button className="primary-button full-width" disabled={busy||query.isPending} onClick={()=>void action('create')}>{busy?t.saving:t.create}</button></section>}
    </>}<Link to="/plus/jev-benchmark">{t.return}</Link></main></>
}
export function GoldAnnotation({data,user,busy,action}:{data:Existing;user:string;busy:boolean;action:(kind:string,payload?:Record<string,unknown>)=>Promise<boolean>}){
  const {language}=useI18n(),t=goldMessages[language],set=data.gold_set,storageKey='gold-review:'+user+':'+set.id
  const [selected,setSelected]=useState(()=>{try{return localStorage.getItem(storageKey)??data.reviews.find(r=>!r.validated)?.review_id??data.reviews[0]?.review_id}catch{return data.reviews[0]?.review_id}}),[drafts,setDrafts]=useState<Record<string,Record<string,GoldChoice>>>({}),[info,setInfo]=useState<GoldTheme|null>(null),[expanded,setExpanded]=useState<GoldTheme|null>(null),[confirmation,setConfirmation]=useState<'translation'|'finalize'|null>(null)
  const [position,setPosition]=useState(()=>{try{return Number(localStorage.getItem(storageKey+':position'))||data.reviews.find(r=>!r.validated)?.position||1}catch{return 1}}),found=data.reviews.findIndex(r=>r.review_id===selected),index=found>=0?found:Math.max(0,data.reviews.findIndex(r=>r.position===position)),review=data.reviews[index],choices=drafts[review.review_id]??review.choices??{}
  const select=(review_id:string)=>{setSelected(review_id);setPosition(data.reviews.find(r=>r.review_id===review_id)?.position??1);setExpanded(null);setInfo(null);try{localStorage.setItem(storageKey,review_id);localStorage.setItem(storageKey+':position',String(data.reviews.find(r=>r.review_id===review_id)?.position??1))}catch{/* Server keeps confirmed progress. */}}
  const change=(key:GoldTheme,choice:GoldChoice)=>setDrafts({...drafts,[review.review_id]:{...choices,[key]:choice}})
  async function save(values:Record<string,unknown>){if(await action('confirm_review',{review_id:review.review_id,choices:values})){setDrafts(previous=>{const next={...previous};delete next[review.review_id];return next});if(index<39)select(data.reviews[index+1].review_id)}}
  return <><section className="card jev-card"><h3>{set.completed_reviews} / 40 {t.done}</h3><progress value={set.completed_reviews} max={40}/><p>{data.rules[language]}</p></section><section className="card jev-card"><h3>{t.review} {index+1} / 40</h3><p className="gold-text" lang="en">{review.analysis_text}</p><span className="jev-tag">{review.validated&&!drafts[review.review_id]?t.saved:t.unsaved}</span></section><p className="jev-note">{t.default}</p><button className="secondary-button full-width" disabled={busy} onClick={()=>void save({})}>{t.noTheme}</button>
    {(['quality','service','atmosphere','price'] as const).map(axis=><details className="card jev-card gold-axis" key={axis}><summary>{t[axis]}</summary>{Object.entries(data.taxonomy).filter(([,definition])=>definition.axis===axis).map(([key,definition])=>{const theme=key as GoldTheme,current=(choices[key]??'absent') as GoldChoice;return <div className="gold-theme" key={key}><div className="gold-theme-heading"><button className="gold-theme-button" disabled={busy} aria-expanded={expanded===theme} onClick={()=>setExpanded(expanded===theme?null:theme)}>{definition[language]}<small>{t[current]}</small></button><button className="gold-info" aria-label={'Info · '+definition[language]} onClick={()=>setInfo(info===theme?null:theme)}><Info size={18}/></button></div>{info===theme&&<p className="jev-note">{definition[language==='fr'?'definition_fr':'definition_vi']}</p>}{expanded===theme&&<div className="gold-choices">{(['positive','negative','both','uncertain','absent'] as const).map(choice=><button key={choice} disabled={busy} aria-pressed={current===choice} onClick={()=>change(theme,choice)}>{t[choice]}</button>)}</div>}</div>})}</details>)}
    <section className="card jev-card gold-actions"><button className="primary-button full-width" disabled={busy} onClick={()=>void save(choices)}>{busy?t.saving:t.confirm}</button><div className="gold-navigation"><button className="secondary-button" disabled={busy||index===0} onClick={()=>select(data.reviews[index-1].review_id)}>{t.previous}</button><button className="secondary-button" disabled={busy||index===39} onClick={()=>select(data.reviews[index+1].review_id)}>{t.next}</button></div><button className="gold-translation" disabled={busy} onClick={()=>setConfirmation('translation')}>{t.translation}</button>{set.completed_reviews===40&&<button className="primary-button full-width" disabled={busy||Object.keys(drafts).length>0} onClick={()=>setConfirmation('finalize')}>{t.finalize}</button>}
      {confirmation&&<div role="alertdialog" aria-modal="true" aria-label={confirmation==='finalize'?t.finalize:t.translation}><p>{confirmation==='finalize'?t.finalizeConfirm:t.translationConfirm}</p><button className="primary-button" disabled={busy} onClick={()=>void (async()=>{const accepted=await action(confirmation==='finalize'?'finalize':'exclude_review',confirmation==='finalize'?{confirm:true}:{review_id:review.review_id});if(accepted){setConfirmation(null);if(confirmation==='translation'){setDrafts(previous=>{const next={...previous};delete next[review.review_id];return next});setPosition(review.position);setSelected('');try{localStorage.removeItem(storageKey);localStorage.setItem(storageKey+':position',String(review.position))}catch{/* Navigation hint is optional. */}}}})()}>{t.finish}</button><button className="secondary-button" disabled={busy} onClick={()=>setConfirmation(null)}>{t.cancel}</button></div>}
    </section></>
}
export function GoldResults({data}:{data:Existing}) {
  const {language}=useI18n(),t=goldMessages[language],c=data.comparison!;const n=(x:number|null,d=3)=>x===null?'—':x.toLocaleString(language==='fr'?'fr-FR':'vi-VN',{maximumFractionDigits:d,minimumFractionDigits:d})
  const theme=(key:string)=><article key={key} className="jev-theme-detail"><h4>{data.taxonomy[key as GoldTheme][language]}</h4>{(['positive','negative'] as const).map(polarity=><div key={polarity}><strong>{t[polarity]}</strong><p>{t.support} : {c.sol.themes[key][polarity].support}</p><p>Sol · {t.precision} {n(c.sol.themes[key][polarity].precision)} · {t.recall} {n(c.sol.themes[key][polarity].recall)} · F1 {n(c.sol.themes[key][polarity].f1)}</p><p>Jev · {t.precision} {n(c.jev.themes[key][polarity].precision)} · {t.recall} {n(c.jev.themes[key][polarity].recall)} · F1 {n(c.jev.themes[key][polarity].f1)}</p>{c.sol.themes[key][polarity].support<3&&<small>{t.low}</small>}</div>)}</article>
  return <div className="jev-results"><section className="card jev-card"><h3>GOLD SET RESULT</h3><p>40 · {t.title}</p><p>{t.immutable}</p><span className="jev-tag">{t[c.verdict]}</span></section>
    <section className="card jev-card"><div className="jev-dual">{(['sol','jev'] as const).map(model=><div key={model}><h3>{model.toUpperCase()} V7</h3><p>{t.micro} : <strong>{n(c[model].micro_f1_gold)}</strong></p><p>{t.macro} : <strong>{n(c[model].macro_f1_gold)}</strong></p></div>)}</div><dl className="jev-pairs"><dt>{t.delta}</dt><dd>{n(c.bootstrap.delta)}</dd><dt>{t.ci}</dt><dd>[{n(c.bootstrap.ci_95_low)} ; {n(c.bootstrap.ci_95_high)}]</dd><dt>{t.stability}</dt><dd>{n(c.jev_repeat_stability*100,1)} %</dd></dl></section>
    {(['service','quality','price','atmosphere'] as const).map(axis=><section className="card jev-card" key={axis}><h3>{t[axis]}</h3><dl className="jev-pairs"><dt>Sol</dt><dd>{n(c.sol.axes[axis].f1)}</dd><dt>Jev</dt><dd>{n(c.jev.axes[axis].f1)}</dd></dl></section>)}
    <section className="card jev-card">{['friendly_staff','attentiveness','professionalism','wait_time','atmosphere'].map(theme)}</section>
    <section className="card jev-card"><h3>{t.resolution}</h3><dl className="jev-pairs">{[[t.solOnly,c.disagreement_resolution.gold_matches_sol_only],[t.jevOnly,c.disagreement_resolution.gold_matches_jev_only],[t.bothModels,c.disagreement_resolution.gold_matches_both],[t.neither,c.disagreement_resolution.gold_matches_neither],[t.goldUncertain,c.disagreement_resolution.gold_uncertain]].map(([label,value])=><div key={label} className="gold-resolution"><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="jev-note">{t.bothNote}</p></section>
    <details className="card jev-card jev-theme-list"><summary>{t.allThemes}</summary>{Object.keys(data.taxonomy).map(theme)}</details><details className="card jev-card jev-technical"><summary>{t.technical}</summary><p>{data.gold_set.id}</p><p>{data.gold_set.taxonomy_version} · {data.gold_set.methodology}</p><p>{c.source_generation_id}<br/>{c.jev_benchmark_id}</p><p>Jev: {c.served_models.join(', ')}</p><p>{t.exact} · Sol {n(c.sol.exact_choice_agreement_with_gold)} · Jev {n(c.jev.exact_choice_agreement_with_gold)}</p><p>Bootstrap: {c.bootstrap.valid_resamples} / 2000 · {c.bootstrap.method}</p><h4>{t.exploratory}</h4>{Object.entries(c.exploratory).map(([threshold,scores])=><p key={threshold}>{threshold} · Jev {t.micro}: {n(scores.micro_f1_gold)}</p>)}</details>
  </div>
}
