import {render,screen,fireEvent,cleanup,waitFor} from '@testing-library/react'
import {QueryClient,QueryClientProvider} from '@tanstack/react-query'
import {afterEach,it,expect,vi} from 'vitest'
import {I18nProvider} from '../i18n'
import {HistoricalV11Test} from './HistoricalV11Test'
const api=vi.hoisted(()=>vi.fn());vi.mock('../lib/historical-v11',()=>({historicalV11Api:api}));afterEach(()=>{cleanup();vi.clearAllMocks();localStorage.clear()})
function mount(language:'fr'|'vi'='fr'){return render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false,gcTime:0}}})}><I18nProvider language={language}><HistoricalV11Test user="u" establishment="synthetic" name="Shabu" visible/></I18nProvider></QueryClientProvider>)}
const eligible={available:true,jev_configured:true,source_generation_id:'v8-frozen',analysis_input_stats:{total_reviews:103,reviews_with_text:97,textless_reviews:6,english_analysis_coverage_percent:100}}
it('opening reads only the frozen source/status; unavailable secret/source disables manual launch',async()=>{api.mockResolvedValue({eligibility:{...eligible,jev_configured:false},run:null});const a=mount();expect(await screen.findByRole('button',{name:'Lancer le rapport V11'})).toBeDisabled();expect(await screen.findByText('Jev n’est pas configuré côté serveur.')).toBeVisible();expect(api.mock.calls.every(c=>!c[2])).toBe(true);a.unmount();api.mockResolvedValue({eligibility:{...eligible,available:false},run:null});mount();expect(await screen.findByRole('button',{name:'Lancer le rapport V11'})).toBeDisabled()})
it('explicit double tap creates one run, persists generation, then reopening/foreground GET only',async()=>{let started=false;api.mockImplementation(async(_e,_l,start)=>{if(start)started=true;return {eligibility:eligible,run:started?{generation_id:'v11-fixture',status:'running',progress:8,total_steps:389}:null}});const a=mount(),button=await screen.findByRole('button',{name:'Lancer le rapport V11'});await waitFor(()=>expect(button).toBeEnabled());fireEvent.click(button);fireEvent.click(button);await screen.findByText('Analyse Jev human-aligned en cours');expect(api.mock.calls.filter(c=>c[2])).toHaveLength(1);expect(localStorage.getItem('historical-v11:u:synthetic:fr')).toBe('v11-fixture');a.unmount();mount();await screen.findByText('Analyse Jev human-aligned en cours');fireEvent(window,new Event('pageshow'));await waitFor(()=>expect(api.mock.calls.filter(c=>!c[2]).length).toBeGreaterThan(3));expect(api.mock.calls.filter(c=>c[2])).toHaveLength(1)})
it('pending marker survives reload without repeating POST; VI captions are localized',async()=>{localStorage.setItem('historical-v11:u:synthetic:vi','pending');api.mockResolvedValue({eligibility:eligible,run:null});mount('vi');expect(await screen.findByRole('button',{name:'Tạo báo cáo V11'})).toBeDisabled();expect(api.mock.calls.every(c=>!c[2])).toBe(true)})


