import {useState,useRef,useEffect} from 'react'
import {useQuery,useQueryClient} from '@tanstack/react-query'
import {useI18n} from '../i18n'
import {historicalV8Api,type V8Status} from '../lib/historical-v8'
import type {EnglishCoverage} from '../lib/english-backfill'
import {ConsultantReport} from '../components/ConsultantReport'
const words={fr:{title:'Rapport V8 — Notes + texte',start:'Lancer le rapport V8',running:'Rapport V8 en cours',continue:'Les avis sont analysés en anglais. Le croisement des notes est calculé côté serveur. Vous pouvez quitter l’application et revenir plus tard.',completed:'Rapport V8 terminé',coverage:'Un rapport V7 terminé et une préparation anglaise complète sont nécessaires pour ce premier test Shabu.',loading:'Lecture du statut V8…',starting:'Démarrage…',error:'Impossible de confirmer le statut. Vérifiez avant une nouvelle tentative.',check:'Vérifier le statut',retry:'Réessayer le rapport V8',failed:'Le rapport V8 a échoué.',reviews:'Avis',text:'Avec texte',english:'Couverture anglaise',model:'Modèle',cost:'Coût estimé USD',time:'Durée de bout en bout',tokens:'Tokens entrée / sortie / total',view:'Voir le rapport V8',note:'Le croisement des notes est déterministe et ne consomme aucun token IA supplémentaire. Aucun benchmark Jev ne sera lancé.',uncertain:'Lancement non confirmé. Le bouton reste bloqué jusqu’à récupération du run.'},vi:{title:'Báo cáo V8 — Điểm số + nội dung',start:'Tạo báo cáo V8',running:'Báo cáo V8 đang được tạo',continue:'Các đánh giá được phân tích bằng tiếng Anh. Việc đối chiếu điểm số được tính trên máy chủ. Bạn có thể rời ứng dụng và quay lại sau.',completed:'Báo cáo V8 đã hoàn thành',coverage:'Cần báo cáo V7 đã hoàn thành và nội dung tiếng Anh đầy đủ cho lần thử đầu tiên tại Shabu.',loading:'Đang đọc trạng thái V8…',starting:'Đang khởi động…',error:'Không thể xác nhận trạng thái. Hãy kiểm tra trước khi thử lại.',check:'Kiểm tra trạng thái',retry:'Thử lại báo cáo V8',failed:'Báo cáo V8 không thành công.',reviews:'Đánh giá',text:'Có nội dung',english:'Tỷ lệ tiếng Anh',model:'Mô hình',cost:'Chi phí ước tính USD',time:'Thời gian toàn quy trình',tokens:'Tokens đầu vào / đầu ra / tổng',view:'Xem báo cáo V8',note:'Đối chiếu điểm số được tính theo quy tắc cố định, không dùng thêm token AI. Không tự động chạy benchmark Jev.',uncertain:'Chưa xác nhận khởi chạy. Nút bị khóa cho đến khi tìm được báo cáo.'}}
const locks=new Set<string>(),active=(data?:V8Status)=>['queued','running','retry'].includes(data?.run?.status??'')
export function HistoricalV8Test({user,establishment,name,coverage,visible}:{user:string;establishment:string;name:string;coverage?:EnglishCoverage;visible:boolean}){
  const {language}=useI18n(),t=words[language],client=useQueryClient(),busy=useRef(false),[starting,setStarting]=useState(false),[error,setError]=useState(''),storageKey=`historical-v8:${user}:${establishment}:${language}`,key=['historical-v8',user,establishment,language]
  const stored=()=>{try{return localStorage.getItem(storageKey)}catch{return null}},save=(v:string)=>{try{localStorage.setItem(storageKey,v)}catch{/* Server is authoritative. */}}
  const query=useQuery<V8Status>({queryKey:key,enabled:visible,retry:false,staleTime:0,queryFn:async()=>{const generation=stored(),data=await historicalV8Api(establishment,language,false,generation&&generation!=='pending'?generation:undefined);if(data.run)save(data.run.generation_id);return data},refetchInterval:q=>visible&&!document.hidden&&(active(q.state.data)||stored()==='pending')?2500:false})
  useEffect(()=>{const resume=()=>{if(!document.hidden&&visible)void client.invalidateQueries({queryKey:['historical-v8',user,establishment,language]})};window.addEventListener('pageshow',resume);document.addEventListener('visibilitychange',resume);return()=>{window.removeEventListener('pageshow',resume);document.removeEventListener('visibilitychange',resume)}},[client,user,establishment,language,visible])
  async function start(){if(busy.current||locks.has(storageKey)||active(query.data)||stored()==='pending'||coverage?.coverage_percent!==100||query.data?.eligibility?.available!==true||query.isPending||query.isError||query.data?.run?.status==='completed')return;busy.current=true;locks.add(storageKey);setStarting(true);setError('')
    async function launch(){const current=await historicalV8Api(establishment,language);if(current.run&&current.run.status!=='failed'){save(current.run.generation_id);client.setQueryData(key,current);return}if(stored()==='pending')return;save('pending');const result=await historicalV8Api(establishment,language,true);if(!result.run)throw new Error('REPORT_LAUNCH_UNCONFIRMED');save(result.run.generation_id);client.setQueryData(key,result);await query.refetch()}
    try{if(navigator.locks)await navigator.locks.request(storageKey,launch);else await launch()}catch(e){const code=e instanceof Error?e.message:'REPORT_LAUNCH_UNCONFIRMED';if(['ENGLISH_COVERAGE_REQUIRED','REPORT_OTHER_VERSION_RUNNING','REPORT_V8_SOURCE_REQUIRED','REPORT_LANGUAGE_CHANGED','UNAUTHORIZED','FORBIDDEN'].includes(code)){try{localStorage.removeItem(storageKey)}catch{/* Storage optional. */}}setError(code);await query.refetch()}finally{busy.current=false;locks.delete(storageKey);setStarting(false)}
  }
  const run=query.data?.run,summary=run?.summary,uncertain=stored()==='pending',number=(n:number|null|undefined,d=1)=>n==null?'—':n.toLocaleString(language==='fr'?'fr-FR':'vi-VN',{maximumFractionDigits:d})
  return <section className="card jev-card historical-v8-test"><h3>{t.title}</h3><strong>{name}</strong>{!active(query.data)&&run?.status!=="completed"&&coverage&&<p className="jev-note">{coverage.stored_reviews} {t.reviews.toLowerCase()} · {coverage.reviews_with_text} {t.text.toLowerCase()} · {number(coverage.coverage_percent)} % EN</p>}{query.isPending&&<p role="status">{t.loading}</p>}{(query.isError||error||uncertain)&&<div role="alert"><p>{uncertain?t.uncertain:t.error}</p>{error&&<small>{error}</small>}<button className="secondary-button" disabled={query.isFetching} onClick={()=>void query.refetch()}>{t.check}</button></div>}
    {active(query.data)&&<div role="status"><h4>{t.running}</h4><p>{t.continue}</p><small>{run?.progress} / {run?.total_steps}</small></div>}{run?.status==='failed'&&<p role="alert">{t.failed} <small>{run.error_code}</small></p>}
    {run?.status!=='completed'&&!active(query.data)&&<><p className="jev-note">{t.coverage}</p><button className="primary-button full-width jev-launch" disabled={starting||uncertain||query.isPending||query.isError||!visible||coverage?.coverage_percent!==100||query.data?.eligibility?.available!==true} onClick={()=>void start()}>{starting?t.starting:run?.status==='failed'?t.retry:t.start}</button></>}
    {run?.status==='completed'&&summary&&<><h4>{t.completed}</h4><dl className="jev-pairs"><dt>{t.reviews}</dt><dd>{summary.analysis_input_stats.total_reviews}</dd><dt>{t.text}</dt><dd>{summary.analysis_input_stats.reviews_with_text}</dd><dt>{t.english}</dt><dd>{number(summary.analysis_input_stats.english_analysis_coverage_percent)} %</dd><dt>{t.model}</dt><dd>{summary.model}</dd><dt>{t.tokens}</dt><dd>{summary.input_tokens} / {summary.output_tokens} / {summary.total_tokens}</dd><dt>{t.cost}</dt><dd>{number(summary.estimated_cost_usd,6)}</dd><dt>{t.time}</dt><dd>{number(summary.elapsed_ms==null?null:summary.elapsed_ms/1000)} s</dd></dl><small className="jev-id">{run.generation_id}</small>{run.report&&<details><summary>{t.view}</summary><ConsultantReport report={run.report}/></details>}</>}
    <p className="jev-note">{t.note}</p></section>
}
