import {useState,useRef,useEffect} from 'react'
import {useQuery,useQueryClient} from '@tanstack/react-query'
import {useI18n} from '../i18n'
import {historicalV10Api,type V10Status} from '../lib/historical-v10'
import {ConsultantReport} from '../components/ConsultantReport'
import {v10Messages as words} from '../i18n/historical-v10'
const locks=new Set<string>(),active=(d?:V10Status)=>['queued','running','retry'].includes(d?.run?.status??'')
export function HistoricalV10Test({user,establishment,name,visible}:{user:string;establishment:string;name:string;visible:boolean}){
 const {language}=useI18n(),t=words[language],client=useQueryClient(),busy=useRef(false),[starting,setStarting]=useState(false),[error,setError]=useState(''),storage=`historical-v10:${user}:${establishment}:${language}`,key=['historical-v10',user,establishment,language],stored=()=>{try{return localStorage.getItem(storage)}catch{return null}},save=(v:string)=>{try{localStorage.setItem(storage,v)}catch{/* Server authoritative. */}}
 const q=useQuery<V10Status>({queryKey:key,enabled:visible,retry:false,staleTime:0,queryFn:async()=>{const id=stored(),data=await historicalV10Api(establishment,language,false,id&&id!=='pending'?id:undefined);if(data.run)save(data.run.generation_id);return data},refetchInterval:query=>visible&&!document.hidden&&(active(query.state.data)||stored()==='pending')?2500:false})
 useEffect(()=>{const resume=()=>{if(!document.hidden&&visible)void client.invalidateQueries({queryKey:["historical-v10",user,establishment,language]})};document.addEventListener('visibilitychange',resume);window.addEventListener('pageshow',resume);return()=>{document.removeEventListener('visibilitychange',resume);window.removeEventListener('pageshow',resume)}},[client,user,establishment,language,visible])
 async function start(){if(busy.current||locks.has(storage)||active(q.data)||stored()==='pending'||q.isPending||q.isError||q.data?.eligibility?.available!==true||!q.data.eligibility.jev_configured||q.data?.run?.status==='completed')return;busy.current=true;locks.add(storage);setStarting(true);setError('');const launch=async()=>{const current=await historicalV10Api(establishment,language);if(current.run&&current.run.status!=='failed'){save(current.run.generation_id);client.setQueryData(key,current);return}if(stored()==='pending')return;save('pending');const data=await historicalV10Api(establishment,language,true);if(!data.run)throw new Error('REPORT_LAUNCH_UNCONFIRMED');save(data.run.generation_id);client.setQueryData(key,data);await q.refetch()};try{if(navigator.locks)await navigator.locks.request(storage,launch);else await launch()}catch(e){const code=e instanceof Error?e.message:'REPORT_LAUNCH_UNCONFIRMED';if(['JEV_NOT_CONFIGURED','REPORT_V10_AUDIT_REQUIRED','REPORT_V10_CONFIG_INVALID','REPORT_V10_SOURCE_REQUIRED','REPORT_OTHER_VERSION_RUNNING','REPORT_LANGUAGE_CHANGED','UNAUTHORIZED','FORBIDDEN','RATE_LIMITED'].includes(code)){try{localStorage.removeItem(storage)}catch{/* optional navigation hint */}}setError(code);await q.refetch()}finally{busy.current=false;locks.delete(storage);setStarting(false)}}
 const run=q.data?.run,eligible=q.data?.eligibility,pending=stored()==='pending',dataset=eligible?.analysis_input_stats
 return <section className="card jev-card historical-v10-test"><h3>{t.title}</h3><strong>{name}</strong><p>{t.intro}</p><small>{t.experiment}</small>{eligible?.audit_summary&&<p>{t.audit} · {eligible.audit_summary.validated} {t.validated} · {eligible.audit_summary.rejected} {t.rejected}</p>}{dataset&&<p className="jev-note">{t.snapshot} · {dataset.total_reviews} {t.reviews} · {dataset.reviews_with_text} {t.text} · {dataset.english_analysis_coverage_percent} % EN</p>}{q.isPending&&<p role="status">{t.loading}</p>}{eligible&&!eligible.jev_configured&&<p role="alert">{t.notConfigured}</p>}{eligible&&!eligible.available&&<p>{t.source}</p>}{(q.isError||error||pending)&&<div role="alert"><p>{pending?t.uncertain:error==='JEV_NOT_CONFIGURED'?t.notConfigured:t.error}</p><button className="secondary-button" disabled={q.isFetching} onClick={()=>void q.refetch()}>{t.check}</button></div>}{active(q.data)&&<div role="status"><h4>{(run?.usage?.sol_narrative_calls??0)>0||run&&run.progress+1>=run.total_steps?t.narrative:t.running}</h4><p>{t.continue}</p><small>{run?.progress} / {run?.total_steps}</small></div>}{run?.status==='failed'&&<p>{t.failed} <small>{run.error_code}</small></p>}
 {run?.status!=='completed'&&!active(q.data)&&<button className="primary-button full-width" disabled={starting||pending||q.isPending||q.isError||!visible||eligible?.available!==true||!eligible.jev_configured} onClick={()=>void start()}>{starting?t.starting:run?.status==='failed'?t.retry:t.start}</button>}{run?.status==='completed'&&<><h4>{t.completed}</h4><small className="jev-id">{run.generation_id}</small>{run.report&&<details><summary>{t.view}</summary><ConsultantReport report={run.report}/></details>}</>}</section>
}


