import {useState,useRef,useEffect} from 'react'
import {useQuery,useQueryClient} from '@tanstack/react-query'
import {useI18n} from '../i18n'
import {historicalV9Api,type V9Status} from '../lib/historical-v9'
import {ConsultantReport} from '../components/ConsultantReport'
const words={fr:{title:'Rapport V9 — Jev + notes',intro:'Jev analyse les commentaires, les notes Google sont croisées séparément et Sol rédige uniquement la synthèse.',start:'Lancer le rapport V9',running:'Analyse Jev en cours',narrative:'Rédaction de la synthèse manager',continue:'Le traitement continue sur le serveur. Vous pouvez fermer l’application et revenir plus tard.',completed:'Rapport V9 terminé',loading:'Lecture du statut V9…',starting:'Démarrage…',source:'Un rapport V8 terminé est nécessaire pour ce premier test Shabu.',notConfigured:'Jev n’est pas configuré côté serveur.',error:'Impossible de confirmer le statut. Vérifiez avant une nouvelle tentative.',check:'Vérifier le statut',retry:'Réessayer le rapport V9',failed:'Le rapport V9 a échoué.',view:'Voir le rapport V9',reviews:'avis',text:'avec texte',snapshot:'Snapshot V8 figé',uncertain:'Lancement non confirmé. Le bouton reste bloqué jusqu’à récupération du run.'},vi:{title:'Báo cáo V9 — Jev + điểm số',intro:'Jev phân tích nội dung đánh giá, điểm Google được đối chiếu riêng và Sol chỉ viết phần tổng hợp.',start:'Tạo báo cáo V9',running:'Đang phân tích bằng Jev',narrative:'Đang viết tổng hợp cho quản lý',continue:'Quá trình tiếp tục trên máy chủ. Bạn có thể đóng ứng dụng và quay lại sau.',completed:'Báo cáo V9 đã hoàn thành',loading:'Đang đọc trạng thái V9…',starting:'Đang khởi động…',source:'Cần báo cáo V8 đã hoàn thành cho lần thử đầu tiên tại Shabu.',notConfigured:'Jev chưa được cấu hình trên máy chủ.',error:'Không thể xác nhận trạng thái. Hãy kiểm tra trước khi thử lại.',check:'Kiểm tra trạng thái',retry:'Thử lại báo cáo V9',failed:'Báo cáo V9 không thành công.',view:'Xem báo cáo V9',reviews:'đánh giá',text:'có nội dung',snapshot:'Dữ liệu V8 cố định',uncertain:'Chưa xác nhận khởi chạy. Nút bị khóa cho đến khi tìm được báo cáo.'}}
const locks=new Set<string>(),active=(d?:V9Status)=>['queued','running','retry'].includes(d?.run?.status??'')
export function HistoricalV9Test({user,establishment,name,visible}:{user:string;establishment:string;name:string;visible:boolean}){
 const {language}=useI18n(),t=words[language],client=useQueryClient(),busy=useRef(false),[starting,setStarting]=useState(false),[error,setError]=useState(''),storage=`historical-v9:${user}:${establishment}:${language}`,key=['historical-v9',user,establishment,language],stored=()=>{try{return localStorage.getItem(storage)}catch{return null}},save=(v:string)=>{try{localStorage.setItem(storage,v)}catch{/* Server authoritative. */}}
 const q=useQuery<V9Status>({queryKey:key,enabled:visible,retry:false,staleTime:0,queryFn:async()=>{const id=stored(),data=await historicalV9Api(establishment,language,false,id&&id!=='pending'?id:undefined);if(data.run)save(data.run.generation_id);return data},refetchInterval:query=>visible&&!document.hidden&&(active(query.state.data)||stored()==='pending')?2500:false})
 useEffect(()=>{const resume=()=>{if(!document.hidden&&visible)void client.invalidateQueries({queryKey:["historical-v9",user,establishment,language]})};document.addEventListener('visibilitychange',resume);window.addEventListener('pageshow',resume);return()=>{document.removeEventListener('visibilitychange',resume);window.removeEventListener('pageshow',resume)}},[client,user,establishment,language,visible])
 async function start(){if(busy.current||locks.has(storage)||active(q.data)||stored()==='pending'||q.isPending||q.isError||q.data?.eligibility?.available!==true||!q.data.eligibility.jev_configured||q.data?.run?.status==='completed')return;busy.current=true;locks.add(storage);setStarting(true);setError('');const launch=async()=>{const current=await historicalV9Api(establishment,language);if(current.run&&current.run.status!=='failed'){save(current.run.generation_id);client.setQueryData(key,current);return}if(stored()==='pending')return;save('pending');const data=await historicalV9Api(establishment,language,true);if(!data.run)throw new Error('REPORT_LAUNCH_UNCONFIRMED');save(data.run.generation_id);client.setQueryData(key,data);await q.refetch()};try{if(navigator.locks)await navigator.locks.request(storage,launch);else await launch()}catch(e){const code=e instanceof Error?e.message:'REPORT_LAUNCH_UNCONFIRMED';if(['JEV_NOT_CONFIGURED','REPORT_V9_SOURCE_REQUIRED','REPORT_OTHER_VERSION_RUNNING','REPORT_LANGUAGE_CHANGED','UNAUTHORIZED','FORBIDDEN','RATE_LIMITED'].includes(code)){try{localStorage.removeItem(storage)}catch{/* optional navigation hint */}}setError(code);await q.refetch()}finally{busy.current=false;locks.delete(storage);setStarting(false)}}
 const run=q.data?.run,eligible=q.data?.eligibility,pending=stored()==='pending',dataset=eligible?.analysis_input_stats
 return <section className="card jev-card historical-v9-test"><h3>{t.title}</h3><strong>{name}</strong><p>{t.intro}</p>{dataset&&<p className="jev-note">{t.snapshot} · {dataset.total_reviews} {t.reviews} · {dataset.reviews_with_text} {t.text} · {dataset.english_analysis_coverage_percent} % EN</p>}{q.isPending&&<p role="status">{t.loading}</p>}{eligible&&!eligible.jev_configured&&<p role="alert">{t.notConfigured}</p>}{eligible&&!eligible.available&&<p>{t.source}</p>}{(q.isError||error||pending)&&<div role="alert"><p>{pending?t.uncertain:error==='JEV_NOT_CONFIGURED'?t.notConfigured:t.error}</p><button className="secondary-button" disabled={q.isFetching} onClick={()=>void q.refetch()}>{t.check}</button></div>}{active(q.data)&&<div role="status"><h4>{(run?.usage?.sol_narrative_calls??0)>0||run&&run.progress+1>=run.total_steps?t.narrative:t.running}</h4><p>{t.continue}</p><small>{run?.progress} / {run?.total_steps}</small></div>}{run?.status==='failed'&&<p>{t.failed} <small>{run.error_code}</small></p>}
 {run?.status!=='completed'&&!active(q.data)&&<button className="primary-button full-width" disabled={starting||pending||q.isPending||q.isError||!visible||eligible?.available!==true||!eligible.jev_configured} onClick={()=>void start()}>{starting?t.starting:run?.status==='failed'?t.retry:t.start}</button>}{run?.status==='completed'&&<><h4>{t.completed}</h4><small className="jev-id">{run.generation_id}</small>{run.report&&<details><summary>{t.view}</summary><ConsultantReport report={run.report}/></details>}</>}</section>
}
