import {render,screen,fireEvent,cleanup,waitFor} from '@testing-library/react'
import {QueryClient,QueryClientProvider} from '@tanstack/react-query'
import {afterEach,beforeEach,it,expect,vi} from 'vitest'
import {I18nProvider} from '../i18n'
import {HistoricalV8Test} from './HistoricalV8Test'
const api=vi.hoisted(()=>vi.fn());vi.mock('../lib/historical-v8',()=>({historicalV8Api:api}))
const coverage={stored_reviews:6,reviews_with_text:5,original_english:5,english_translation_found:0,english_translation_missing:0,coverage_percent:100}
function mount(percent=100,language:'fr'|'vi'='fr'){return render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false,gcTime:0}}})}><I18nProvider language={language}><HistoricalV8Test user="u" establishment="shabu" name="Shabu" coverage={{...coverage,coverage_percent:percent}} visible/></I18nProvider></QueryClientProvider>)}
beforeEach(()=>api.mockResolvedValue({eligibility:{available:true},run:null}));afterEach(()=>{cleanup();localStorage.clear();api.mockReset()})
it('GET only at opening; requires both complete English preparation and completed V7 source',async()=>{const first=mount(99),button=await screen.findByRole('button',{name:'Lancer le rapport V8'});expect(button).toBeDisabled();expect(api.mock.calls.every(c=>!c[2])).toBe(true);first.unmount();api.mockResolvedValue({eligibility:{available:false},run:null});mount();expect(await screen.findByRole('button',{name:'Lancer le rapport V8'})).toBeDisabled()})
it('explicit double tap starts once, persists generation and reopening/foreground only reads existing status',async()=>{let started=false;api.mockImplementation(async(_e,_l,start)=>{if(start)started=true;return {eligibility:{available:true},run:started?{generation_id:'v8-fixture',status:'running',progress:0,total_steps:2}:null}});const view=mount(),button=await screen.findByRole('button',{name:'Lancer le rapport V8'});await waitFor(()=>expect(button).toBeEnabled());fireEvent.click(button);fireEvent.click(button);await screen.findByText('Rapport V8 en cours');expect(api.mock.calls.filter(c=>c[2])).toHaveLength(1);expect(localStorage.getItem('historical-v8:u:shabu:fr')).toBe('v8-fixture');view.unmount();mount();await screen.findByText('Rapport V8 en cours');fireEvent(window,new Event('pageshow'));await waitFor(()=>expect(api.mock.calls.filter(c=>!c[2]).length).toBeGreaterThan(3));expect(api.mock.calls.filter(c=>c[2])).toHaveLength(1)})
it('an ambiguous start remains blocked through reload and never retries POST automatically',async()=>{localStorage.setItem('historical-v8:u:shabu:fr','pending');mount();expect(await screen.findByRole('button',{name:'Lancer le rapport V8'})).toBeDisabled();expect(api.mock.calls.every(c=>!c[2])).toBe(true)})
it('VI explicit retry and running status stay localized',async()=>{api.mockResolvedValue({eligibility:{available:true},run:{generation_id:'failed',status:'failed',error_code:'FIXTURE',progress:0,total_steps:1}});mount(100,'vi');expect(await screen.findByRole('button',{name:'Thử lại báo cáo V8'})).toBeEnabled();expect(api.mock.calls.every(c=>!c[2])).toBe(true)})
