import {render,screen,fireEvent,cleanup,waitFor} from '@testing-library/react'
import {MemoryRouter} from 'react-router-dom'
import {QueryClient,QueryClientProvider} from '@tanstack/react-query'
import {describe,it,expect,vi,afterEach} from 'vitest'
import {I18nProvider} from '../i18n'
import {IndependentJevEntry,IndependentWorkspace,IndependentJevPage} from './IndependentJevPage'
import {INDEPENDENT_CONFIG,compareIndependent} from '../../supabase/functions/_shared/independent-jev-core'
import {syntheticIndependent} from '../../tests/fixtures/independent-jev'
import type {IndependentView} from '../lib/independent-jev'
import {restorableRoute} from '../lib/navigation-state'
vi.mock('../lib/supabase',()=>({supabase:null}))
const calls=vi.hoisted(()=>({api:vi.fn()}))
vi.mock('../lib/independent-jev',()=>({independentJevApi:calls.api}))
vi.mock('../app/AppContext',()=>({useApp:()=>({currentUser:{id:'fixture-owner'},demoMode:false})}))
vi.mock('../lib/use-jev-access',()=>({useJevAccess:()=>({data:true,isPending:false})}))
vi.mock('../components/ui/PageHeader',()=>({PageHeader:()=>null}))
afterEach(()=>{cleanup();vi.clearAllMocks();localStorage.clear()})
export async function independentView():Promise<IndependentView>{const f=await syntheticIndependent(),p=f.prepared;return {configuration:{id:INDEPENDENT_CONFIG.id,config:INDEPENDENT_CONFIG,config_sha256:p.config_sha256,frozen_at:'2026-10-09'},ready:true,error_code:null,run:null,preview:{reviews:32,reference_labels:800,uncertain_labels:11,sealed_at:p.seal.sealed_at,reference_model:p.seal.model_source,reference_fingerprint:p.seal.reference_fingerprint,dataset_fingerprint:p.seal.frozen_dataset_fingerprint,config_sha256:p.config_sha256,prepared_sha256:p.prepared_sha256,expected_requests:192,estimated_input_tokens:p.estimated_input_tokens,estimated_cost_usd:p.estimated_cost_usd,rates:p.rates,translation_anomalies:[]},comparison:null,progress:{total:0,completed:0,failed:0}}}
const mount=(node:React.ReactNode,language:'fr'|'vi'='fr')=>render(<MemoryRouter><I18nProvider language={language}>{node}</I18nProvider></MemoryRouter>)
describe('independent mobile benchmark',()=>{
 it('the actual page blocks double tap, restores persisted server progress and never auto-POSTs on remount',async()=>{let server=await independentView();calls.api.mockImplementation(async confirm=>{if(confirm)server={...server,run:{id:'persisted-run',status:'running',error_code:null,created_at:'now'},progress:{total:192,completed:32,failed:0}};return structuredClone(server)});const page=()=>mount(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><IndependentJevPage/></QueryClientProvider>);const first=page();fireEvent.click(await screen.findByRole('button',{name:'Lancer la comparaison V11/V12'}));const confirm=screen.getByRole('button',{name:'Confirmer le coût et lancer'});fireEvent.click(confirm);fireEvent.click(confirm);await waitFor(()=>expect(screen.getByRole('status')).toHaveTextContent('32 / 192'));expect(calls.api.mock.calls.filter(([confirm])=>confirm)).toHaveLength(1);first.unmount();page();await waitFor(()=>expect(screen.getByRole('status')).toHaveTextContent('32 / 192'));expect(calls.api.mock.calls.filter(([confirm])=>confirm)).toHaveLength(1);expect(screen.queryByRole('button',{name:'Lancer la comparaison V11/V12'})).not.toBeInTheDocument()})
 it('is accessible without launching and restorable after PWA closure',()=>{mount(<IndependentJevEntry/>);expect(screen.getByRole('link')).toHaveAttribute('href','/plus/jev-independent-test');expect(restorableRoute('/plus/jev-independent-test')).toBe(true)})
 it('shows sealed counts and IA warning, and requires manual cost confirmation',async()=>{const start=vi.fn().mockResolvedValue(undefined);mount(<IndependentWorkspace data={await independentView()} busy={false} start={start}/>);expect(screen.getByText('32')).toBeInTheDocument();expect(screen.getByText('800')).toBeInTheDocument();expect(screen.getByText('11')).toBeInTheDocument();expect(screen.getByText(/non Gold humain indépendant/)).toBeInTheDocument();expect(start).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Lancer la comparaison V11/V12'}));expect(screen.getByRole('alertdialog')).toHaveTextContent('USD');expect(start).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Confirmer le coût et lancer'}));await waitFor(()=>expect(start).toHaveBeenCalledTimes(1))})
 it('refresh never launches a paid test; invalid seals disable launch',async()=>{const d=await independentView(),refresh=vi.fn(),start=vi.fn();d.ready=false;d.error_code='INDEPENDENT_SEAL_CHANGED';mount(<IndependentWorkspace data={d} busy={false} start={start} refresh={refresh}/>);fireEvent.click(screen.getByRole('button',{name:'Vérifier le statut'}));expect(refresh).toHaveBeenCalledTimes(1);expect(start).not.toHaveBeenCalled();expect(screen.getByRole('button',{name:'Lancer la comparaison V11/V12'})).toBeDisabled()})
 it('an existing running job prevents double launch and hides all comparative predictions',async()=>{const d=await independentView();d.run={id:'existing',status:'running',error_code:null,created_at:'now'};d.progress={total:192,completed:64,failed:0};mount(<IndependentWorkspace data={d} busy={false} start={vi.fn()}/>);expect(screen.queryByRole('button',{name:'Lancer la comparaison V11/V12'})).not.toBeInTheDocument();expect(screen.getByRole('status')).toHaveTextContent('64 / 192');expect(screen.queryByRole('heading',{name:'Comparaison exploratoire indépendante V11 / V12'})).not.toBeInTheDocument()})
 it('localizes the path and explicit launch in Vietnamese',async()=>{mount(<IndependentWorkspace data={await independentView()} busy={false} start={vi.fn()}/>, 'vi');expect(screen.getByRole('heading',{name:'Sẵn sàng'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'Chạy so sánh V11/V12'})).toBeInTheDocument();expect(screen.getByText(/không phải Gold thủ công độc lập/)).toBeInTheDocument()})
 it('completed results include both polarities, axes, themes, bootstrap, costs and never claim human accuracy',async()=>{const f=await syntheticIndependent(),d=await independentView();d.run={id:f.run.id,status:'completed',error_code:null,created_at:'now'};d.comparison=await compareIndependent(f.run,f.tasks);d.comparison.usage.v12.usage_complete=false;mount(<IndependentWorkspace data={d} busy={false} start={vi.fn()}/>);expect(screen.getByRole('heading',{name:'Comparaison exploratoire indépendante V11 / V12'})).toBeInTheDocument();expect(screen.getByText('Résultats des 25 thèmes')).toBeInTheDocument();expect(screen.getByRole('heading',{name:'Bootstrap apparié par avis · 2000 rééchantillonnages'})).toBeInTheDocument();expect(screen.getByRole('heading',{name:'Coûts, tokens et durée'})).toBeInTheDocument();expect(screen.getByText('Faux négatifs potentiels')).toBeInTheDocument();expect(screen.getByRole('heading',{name:'Service'})).toBeInTheDocument();expect(screen.getByRole('alert')).toHaveTextContent('Le coût peut être incomplet')})
})
