import {useEffect,useRef,useState} from 'react'
import {Link} from 'react-router-dom'
import {useQuery,useQueryClient} from '@tanstack/react-query'
import {useApp} from '../app/AppContext'
import {useI18n} from '../i18n'
import {useJevAccess} from '../lib/use-jev-access'
import {PageHeader} from '../components/ui/PageHeader'
import {compactApi,downloadCompactJson,type CompactView} from '../lib/jev-compact'
import {compactBlindExport} from '../../supabase/functions/_shared/jev-compact-api'
import {compactMessages} from '../i18n/jev-compact'
import {THEME_KEYS} from '../../supabase/functions/_shared/jev-themes'
import {GOLD_TAXONOMY} from '../../supabase/functions/_shared/gold-taxonomy'
import './JevBenchmarkPage.css'
import './GoldSetPage.css'
import './JevExploratoryPage.css'
import './JevCompactPage.css'
export function JevCompactEntry(){const {language}=useI18n(),t=compactMessages[language];return <section className="card jev-card"><h2>{t.title}</h2><p>{t.intro}</p><Link className="primary-button full-width exploratory-link" to="/plus/jev-compact">{t.open}</Link></section>}
export function JevCompactPage(){const {currentUser,demoMode,establishments}=useApp(),{language}=useI18n(),t=compactMessages[language],access=useJevAccess(currentUser.id,demoMode),client=useQueryClient(),organizations=[...new Set(establishments.map(e=>e.organizationId))],[selected,setSelected]=useState(()=>{try{return localStorage.getItem('compact-org:'+currentUser.id)??''}catch{return ''}}),org=organizations.includes(selected)?selected:organizations[0],key=['jev-compact',currentUser.id,org],lock=useRef(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),q=useQuery({queryKey:key,enabled:access.data===true&&!!org,retry:false,staleTime:0,queryFn:()=>compactApi(org!),refetchInterval:query=>!document.hidden&&['queued','running'].includes(query.state.data?.run?.status??'')?2500:false});
 useEffect(()=>{const refresh=()=>{if(!document.hidden)void client.invalidateQueries({queryKey:['jev-compact',currentUser.id]})};window.addEventListener('pageshow',refresh);document.addEventListener('visibilitychange',refresh);return()=>{window.removeEventListener('pageshow',refresh);document.removeEventListener('visibilitychange',refresh)}},[client,currentUser.id]);
 async function act(action:Parameters<typeof compactApi>[1]){if(lock.current||!org)return;lock.current=true;setBusy(true);setError('');try{client.setQueryData(key,await compactApi(org,action))}catch(e){setError(e instanceof Error?e.message:'COMPACT_CONNECTION_ERROR');await q.refetch()}finally{setBusy(false);lock.current=false}}
 return <><PageHeader title={t.title} back/><div className="jev-page gold-page exploratory-page">{organizations.length>1&&<section className="card jev-card"><label htmlFor="compact-org">{t.org}</label><select id="compact-org" className="full-width" value={org} onChange={e=>{setSelected(e.target.value);try{localStorage.setItem('compact-org:'+currentUser.id,e.target.value)}catch{/* Choice only. */}}}>{organizations.map(o=><option key={o} value={o}>{o}</option>)}</select></section>}{access.isPending||q.isPending&&access.data===true?<p>{t.loading}</p>:access.data!==true?<p>{t.denied}</p>:q.isError?<section className="card jev-card" role="alert"><p>{t.error}</p><button className="secondary-button" onClick={()=>void q.refetch()}>{t.refresh}</button></section>:q.data?<CompactWorkspace data={q.data} busy={busy||q.isFetching} act={act} refresh={()=>void q.refetch()}/>:null}{error&&<p role="alert" className="jev-id">{t.error} · {error}</p>}<Link to="/plus/jev-benchmark">{t.back}</Link></div></>}
export function CompactWorkspace({data,busy=false,act,refresh}:{data:CompactView;busy?:boolean;act:(action:Parameters<typeof compactApi>[1])=>Promise<void>;refresh?:()=>void}){const {language}=useI18n(),t=compactMessages[language],[confirm,setConfirm]=useState<'seal'|'start'|null>(null),[fileError,setFileError]=useState(''),n=(x:number|null,d=3)=>x===null?t.unknown:x.toLocaleString(language==='fr'?'fr-FR':'vi-VN',{maximumFractionDigits:d}),money=(x:number|null)=>x===null?t.unknown:'USD '+n(x,6),c=data.comparison,metrics=(v:{precision:number|null;recall:number|null;f1:number|null;support:number;fp:number;fn:number})=><dl className="jev-pairs"><dt>{t.support}</dt><dd>{v.support}</dd><dt>{t.precision}</dt><dd>{n(v.precision)}</dd><dt>{t.recall}</dt><dd>{n(v.recall)}</dd><dt>{t.f1}</dt><dd>{n(v.f1)}</dd><dt>FP / FN</dt><dd>{v.fp} / {v.fn}</dd></dl>;
 async function file(e:React.ChangeEvent<HTMLInputElement>,action:string){setFileError('');try{const selected=e.target.files?.[0];if(!selected)return;if(selected.size>2_000_000)throw new Error('FILE_TOO_LARGE');const json=JSON.parse(await selected.text());if(!Array.isArray(json))throw new Error('ARRAY_REQUIRED');await act({action,rows:json})}catch{setFileError(t.fileInvalid)}finally{e.target.value=''}}
 return <><section className="card jev-card"><h2>{data.run?data.run.status==='completed'?t.completed:data.run.status==='failed'?t.failed:t.running:t.ready}</h2><p>{t.intro}</p><p>{t.warning}</p><p>{t.noSwitch}</p><p>{t.selection}</p><dl className="jev-pairs"><dt>{t.candidates}</dt><dd>{(data.inventory as {total?:number})?.total??0}</dd><dt>{t.reviews}</dt><dd>{data.items.length} / 32</dd><dt>{t.english}</dt><dd>{data.english_ready} / 32</dd><dt>{t.missing}</dt><dd>{data.english_missing}</dd><dt>{t.labels}</dt><dd>{data.reference_labels} / 800</dd><dt>{t.planned}</dt><dd>{data.cost.planned_calls}</dd><dt>{t.max}</dt><dd>64</dd></dl><p>{t.noTranslation}</p><p>{data.seal?t.sealed:t.preparation}</p>{!data.set&&<button className="primary-button full-width" disabled={busy} onClick={()=>void act({action:'prepare'})}>{t.prepare}</button>}{refresh&&<button className="secondary-button full-width" disabled={busy} onClick={refresh}>{t.refresh}</button>}{data.set&&<p className="jev-id">{data.set.id}</p>}</section>
 {data.set&&!data.run&&<section className="card jev-card"><h2>{t.preparation}</h2><button className="secondary-button full-width" onClick={()=>downloadCompactJson('compact-originals.json',data.items.map(i=>({review_id:i.review_id,original_text:i.original_text,original_language:i.original_language,original_text_sha256:i.original_text_sha256})))}>{t.originalExport}</button><p className="compact-format">{t.textFormat}</p><label className="secondary-button full-width compact-upload">{t.importTexts}<input type="file" accept=".json,application/json" disabled={busy||!!data.seal||data.reference_labels>0} onChange={e=>void file(e,'import_texts')}/></label><h3>{t.reference}</h3><button className="secondary-button full-width" disabled={data.english_ready!==32} onClick={()=>downloadCompactJson('compact-blind-english-reference-input.json',compactBlindExport(data))}>{t.blindExport}</button><p className="compact-format">{t.refFormat}</p><label className="secondary-button full-width compact-upload">{t.importRefs}<input type="file" accept=".json,application/json" disabled={busy||data.english_ready!==32||!!data.seal||data.reference_labels>0} onChange={e=>void file(e,'import_references')}/></label>{fileError&&<p role="alert">{fileError}</p>}<button className="primary-button full-width" disabled={busy||!data.can_seal} onClick={()=>setConfirm('seal')}>{t.seal}</button></section>}
 <section className="card jev-card"><h2>{t.budget}</h2><h3>{t.A}</h3><p>{money(data.cost.A.estimate_usd)}</p><h3>{t.B}</h3><p>{money(data.cost.B.estimate_usd)}</p><p>{t.indicative}: {money(data.cost.indicative_budget_if_B_costs_as_A_usd)}</p><p>{t.estimateNote}</p>{data.paid_authorization_required&&<p>{t.notAuthorized}</p>}{data.authorization&&(data.authorization.cost_limit_usd===null||data.authorization.cost_limit_usd===0)&&<p>{t.noCeiling}</p>}{!data.run&&<button className="primary-button full-width" disabled={busy||!data.can_start} onClick={()=>setConfirm('start')}>{t.start}</button>}{confirm&&<div role="alertdialog" aria-modal="true" aria-label={confirm==='seal'?t.seal:t.paid}><p>{confirm==='seal'?t.sealConfirm:t.paid}</p>{confirm==='start'&&<><p>{data.cost.planned_calls} · {money(data.cost.indicative_budget_if_B_costs_as_A_usd)}</p><p>{t.estimateNote}</p></>}<button className="primary-button" disabled={busy} onClick={()=>void act(confirm==='seal'?{action:'seal',confirm:true}:{action:'start',confirm_cost:true,reference_sha256:data.seal!.reference_sha256}).then(()=>setConfirm(null))}>{confirm==='seal'?t.confirmSeal:t.confirmStart}</button><button className="secondary-button" disabled={busy} onClick={()=>setConfirm(null)}>{t.cancel}</button></div>}{data.run&&['queued','running'].includes(data.run.status)&&<div role="status"><p>{t.background}</p><p>{data.progress.completed} / {data.progress.total} · {data.progress.failed}</p><progress value={data.progress.completed+data.progress.failed} max={64}/></div>}</section>
 <details className="card jev-card"><summary>{t.configuration}</summary>{data.configurations.map(c=><p className="jev-id" key={c.id}>{c.id}<br/>{c.config_sha256}</p>)}</details><details className="card jev-card"><summary>{t.items}</summary>{data.items.map(i=>{const text=data.texts.find(t=>t.id===i.text_id);return <article className="jev-theme-detail" key={i.review_id}><h3>{i.position} · {i.establishment_name} · {i.overall_rating}★</h3><p className="jev-id">{t.id}: {i.review_id}</p><p>{text?.source??t.missing}</p><details><summary>{t.original}</summary><p className="gold-text">{i.original_text}</p><p className="jev-id">{i.original_text_sha256}</p></details>{text&&<details><summary>{t.englishText}</summary><p className="gold-text" lang="en">{text.analysis_text}</p><p className="jev-id">{text.analysis_text_sha256}</p></details>}</article>})}</details>
 {c&&<><section className="card jev-card"><h2>{t.results}</h2><p>{t.warning}</p><p>{t.coverage}: {c.coverage.paired_reviews} / 32</p><p>{t.onePass}</p>{c.models_changed&&<p role="alert">{t.modelChanged}</p>}{(['A','B'] as const).map(v=><div key={v}><h3>{t[v]}</h3><h4>{t.negative}</h4>{metrics(c[v].negative)}<h4>{t.positive}</h4>{metrics(c[v].positive)}<p>Macro F1: {n(c[v].macro_f1)} · {t.uncertain}: {c[v].uncertain_labels}</p></div>)}</section>
 <section className="card jev-card"><h2>{t.usage}</h2>{(['A','B'] as const).map(v=><div key={v}><h3>{t[v]}</h3><p>{t.model}: {c.usage[v].served_models.join(', ')}</p><p>{c.usage[v].input_tokens??t.unknown} / {c.usage[v].output_tokens??t.unknown} tokens · {money(c.usage[v].cost_usd)} · {c.usage[v].duration_ms} ms</p>{c.usage[v].scenarios.map(s=><p key={s.reviews}>{s.reviews}: {money(s.estimated_cost_usd)}</p>)}</div>)}<p>{t.savings}: {c.cost_savings===null?t.unknown:n(c.cost_savings*100,1)+' %'}</p><p>Input tokens: {c.input_token_savings===null?t.unknown:n(c.input_token_savings*100,1)+' %'}</p></section>
 <details className="card jev-card"><summary>{t.bootstrap}</summary>{(['negative','positive'] as const).map(p=><p key={p}>{t[p]} · Δ {n(c.bootstrap[p].delta)} · [{n(c.bootstrap[p].ci_95_low)} ; {n(c.bootstrap[p].ci_95_high)}]</p>)}</details><details className="card jev-card"><summary>{t.axes}</summary>{(['quality','service','atmosphere','price'] as const).map(axis=><div key={axis}><h3>{t[axis]}</h3>{(['A','B'] as const).map(v=><div key={v}><h4>{v} · {t.negative}</h4>{metrics(c[v].axes[axis].negative)}<h4>{t.positive}</h4>{metrics(c[v].axes[axis].positive)}</div>)}</div>)}</details><details className="card jev-card"><summary>{t.themes}</summary>{THEME_KEYS.map(k=><div key={k}><h3>{GOLD_TAXONOMY[k][language]}</h3>{(['A','B'] as const).map(v=><div key={v}><h4>{v} · {t.negative}</h4>{metrics(c[v].themes[k].negative)}<h4>{t.positive}</h4>{metrics(c[v].themes[k].positive)}</div>)}</div>)}</details><details className="card jev-card"><summary>{t.degraded} · {c.degraded_themes.length}</summary>{c.degraded_themes.map(d=><p key={d.theme_key+d.polarity}>{GOLD_TAXONOMY[d.theme_key][language]} · {t[d.polarity]} · Δ F1 {n(d.delta)}</p>)}</details><details className="card jev-card"><summary>{t.errors}</summary>{(['A','B'] as const).map(v=><div key={v}><h3>{v}</h3>{c[v].errors.map((e,index)=><p key={index} className="jev-id">{e.review_id} · {GOLD_TAXONOMY[e.theme_key][language]} · {t[e.polarity]} · {e.kind==='false_positive'?'FP':'FN'}</p>)}</div>)}</details><details className="card jev-card"><summary>{t.suspects}</summary>{c.reviews.filter(r=>r.reasons.length).map(r=><article className="jev-theme-detail" key={r.review_id}><p className="jev-id">{r.review_id}</p><p>{r.overall_rating}★ · {r.establishment_name}</p><p className="gold-text" lang="en">{r.analysis_text}</p>{r.reasons.map((reason,index)=><p key={index}>{'theme_key' in reason?GOLD_TAXONOMY[reason.theme_key][language]+' · A: '+reason.A.choice+' / B: '+reason.B.choice:'incomplete'}</p>)}</article>)}</details></>}
 </>
}
