import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react'
import {QueryClient,QueryClientProvider} from '@tanstack/react-query'
import {MemoryRouter} from 'react-router-dom'
import {describe,it,expect,vi,afterEach} from 'vitest'
import {I18nProvider} from '../i18n'
import {CompactWorkspace,JevCompactPage,JevCompactEntry} from './JevCompactPage'
import {syntheticCompact} from '../../tests/fixtures/jev-compact'
import {restorableRoute} from '../lib/navigation-state'
const api=vi.hoisted(()=>vi.fn());const gate=vi.hoisted(()=>({data:true,isPending:false}));
vi.mock('../lib/jev-compact',()=>({compactApi:api,downloadCompactJson:vi.fn()}))
vi.mock('../lib/use-jev-access',()=>({useJevAccess:()=>gate}))
vi.mock('../app/AppContext',()=>({useApp:()=>({currentUser:{id:'fixture-owner'},demoMode:false,notifications:[],establishments:[{organizationId:'org',id:'venue',name:'Synthetic venue'}]})}))
const mount=(ui:React.ReactNode,language:'fr'|'vi'='fr')=>render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false,gcTime:0}}})}><MemoryRouter><I18nProvider language={language}>{ui}</I18nProvider></MemoryRouter></QueryClientProvider>);
afterEach(()=>{cleanup();vi.clearAllMocks();gate.data=true;localStorage.clear()})
describe('compact preparation iPhone interface',()=>{
 it('entry and resume route registered',()=>{mount(<JevCompactEntry/>);expect(screen.getByRole('link',{name:'Préparer la comparaison compacte'})).toHaveAttribute('href','/plus/jev-compact');expect(restorableRoute('/plus/jev-compact')).toBe(true)})
 it.each(['fr','vi'] as const)('draft %s has real English deficit, zero fake labels, paid/seal blocked',async language=>{const f=await syntheticCompact('draft'),act=vi.fn();mount(<CompactWorkspace data={f} act={act}/>,language);expect(screen.getByRole('button',{name:language==='fr'?'Lancer la comparaison JEV':'Chạy so sánh JEV'})).toBeDisabled();expect(screen.getByRole('button',{name:language==='fr'?'Sceller les textes et références IA':'Niêm phong nội dung và tham chiếu AI'})).toBeDisabled();expect(screen.getByRole('button',{name:language==='fr'?'Exporter les avis anglais pour annotation IA aveugle':'Xuất tiếng Anh để gán nhãn AI không xem dự đoán'})).toBeDisabled();expect(act).not.toHaveBeenCalled()})
 it('sealing requires confirmation and does not start JEV',async()=>{const f=await syntheticCompact();f.set!.status='draft';f.seal=null;f.can_seal=true;const act=vi.fn().mockResolvedValue(undefined);mount(<CompactWorkspace data={f} act={act}/>);fireEvent.click(screen.getByRole('button',{name:'Sceller les textes et références IA'}));expect(act).not.toHaveBeenCalled();expect(screen.getByRole('alertdialog')).toHaveTextContent('Aucun appel JEV');fireEvent.click(screen.getByRole('button',{name:'Confirmer le scellement'}));await waitFor(()=>expect(act).toHaveBeenCalledExactlyOnceWith({action:'seal',confirm:true}))})
 it('future paid launch needs both separate authorization and explicit cost confirmation',async()=>{const f=await syntheticCompact();f.authorization={cost_limit_usd:.05,expected_served_model:'jev-fixed'};f.paid_authorization_required=false;f.can_start=true;const act=vi.fn().mockResolvedValue(undefined);mount(<CompactWorkspace data={f} act={act}/>);fireEvent.click(screen.getByRole('button',{name:'Lancer la comparaison JEV'}));expect(act).not.toHaveBeenCalled();expect(screen.getByRole('alertdialog')).toHaveTextContent('USD');fireEvent.click(screen.getByRole('button',{name:'Confirmer le coût et lancer'}));await waitFor(()=>expect(act).toHaveBeenCalledExactlyOnceWith({action:'start',confirm_cost:true,reference_sha256:f.seal!.reference_sha256}))})
 it('GET-only on load/refresh/remount: persisted draft is not recreated or paid',async()=>{const f=await syntheticCompact('draft');api.mockResolvedValue(f);const p=mount(<JevCompactPage/>);await screen.findByText('Benchmark non lancé');expect(api).toHaveBeenCalledExactlyOnceWith('org');fireEvent.click(screen.getByRole('button',{name:'Vérifier le statut sans appel IA'}));await waitFor(()=>expect(api).toHaveBeenCalledTimes(2));p.unmount();mount(<JevCompactPage/>);await screen.findByText('Benchmark non lancé');expect(api).toHaveBeenCalledTimes(3);expect(api.mock.calls.every(args=>args.length===1)).toBe(true)})
 it('results show exploratory scores and measured savings, no human-performance claim',async()=>{mount(<CompactWorkspace data={await syntheticCompact('done')} act={vi.fn()}/>);expect(screen.getByRole('heading',{name:'Comparaison complète / compacte'})).toBeInTheDocument();expect(screen.getAllByText(/pas un Gold humain/).length).toBeGreaterThan(0);expect(screen.getByText('Avis comparables: 32 / 32')).toBeInTheDocument();expect(screen.getByText('Un seul passage : stabilité entre répétitions non mesurable.')).toBeInTheDocument()})
 it('unauthorized roles request no data',()=>{gate.data=false;mount(<JevCompactPage/>);expect(api).not.toHaveBeenCalled();expect(screen.getByText('Réservé aux propriétaires, administrateurs et managers.')).toBeInTheDocument()})
})
