import {useEffect,useRef,useState} from 'react'
import {Link} from 'react-router-dom'
import {useQuery,useQueryClient} from '@tanstack/react-query'
import {useApp} from '../app/AppContext'
import {useI18n} from '../i18n'
import {useJevAccess} from '../lib/use-jev-access'
import {PageHeader} from '../components/ui/PageHeader'
import {pilotApi,type PilotView} from '../lib/jev-pilot'
import {pilotMessages} from '../i18n/jev-pilot'
import {GOLD_TAXONOMY} from '../../supabase/functions/_shared/gold-taxonomy'
import type {PilotProse} from '../../supabase/functions/_shared/jev-pilot-types'
import './JevBenchmarkPage.css'
import './GoldSetPage.css'
import './JevExploratoryPage.css'
import './JevEconomyPilotPage.css'
export function JevEconomyPilotEntry(){const {language}=useI18n(),t=pilotMessages[language];return <section className="card jev-card"><h2>{t.title}</h2><p>{t.intro}</p><Link className="primary-button full-width exploratory-link" to="/plus/jev-economy-pilot">{t.open}</Link></section>}
export function JevEconomyPilotPage(){const {currentUser,demoMode}=useApp(),{language}=useI18n(),t=pilotMessages[language],access=useJevAccess(currentUser.id,demoMode),client=useQueryClient(),key=['jev-pilot',currentUser.id,language],lock=useRef(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),q=useQuery({queryKey:key,enabled:access.data===true,retry:false,staleTime:0,queryFn:()=>pilotApi(language),refetchInterval:query=>!document.hidden&&query.state.data?.jobs?.some(j=>['queued','running'].includes(j.status))?2500:false});
 useEffect(()=>{const refresh=()=>{if(!document.hidden)void client.invalidateQueries({queryKey:['jev-pilot',currentUser.id]})};window.addEventListener('pageshow',refresh);document.addEventListener('visibilitychange',refresh);return()=>{window.removeEventListener('pageshow',refresh);document.removeEventListener('visibilitychange',refresh)}},[client,currentUser.id]);
 async function act(body:Parameters<typeof pilotApi>[1]){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{client.setQueryData(key,await pilotApi(language,body))}catch(e){setError(e instanceof Error?e.message:'PILOT_CONNECTION_ERROR');await q.refetch()}finally{lock.current=false;setBusy(false)}}
 return <><PageHeader title={t.title} back/><div className="jev-page gold-page exploratory-page">{access.isPending||q.isPending&&access.data===true?<p>{t.loading}</p>:access.data!==true?<p>{t.denied}</p>:q.isError?<section className="card jev-card" role="alert"><p>{t.error}</p><button className="secondary-button" onClick={()=>void q.refetch()}>{t.refresh}</button></section>:q.data?<PilotWorkspace data={q.data} busy={busy||q.isFetching} act={act} refresh={()=>void q.refetch()}/>:null}{error&&<p role="alert" className="jev-id">{t.error} · {error}</p>}<Link to="/plus/jev-benchmark">{t.back}</Link></div></>}
export function PilotWorkspace({data,busy=false,act,refresh}:{data:PilotView;busy?:boolean;act:(body:Parameters<typeof pilotApi>[1])=>Promise<void>;refresh?:()=>void}){const {language}=useI18n(),t=pilotMessages[language],[confirm,setConfirm]=useState<'jev'|'sol'|null>(null),n=(v:number|null,d=2)=>v===null?t.unknown:v.toLocaleString(language==='fr'?'fr-FR':'vi-VN',{maximumFractionDigits:d}),pct=(v:number|null)=>v===null?t.unknown:n(v*100)+' %',usd=(v:number|null)=>v===null?t.unknown:'USD '+n(v,6);if(!data.snapshot)return <section className="card jev-card"><h2>Artisan Cafe & Eatery</h2><p>{t.intro}</p><button className="primary-button full-width" disabled={busy} onClick={()=>void act({action:'prepare_snapshot'})}>{t.prepare}</button><p>{t.authorization}</p></section>;
 const s=data.statistics,c=s.coverage,old=data.comparison.legacy,report=data.report?.result as {prose:PilotProse;origin:string}|null,reportStats=(data.report?.input_context.statistics??s) as typeof s,jobCost=data.jobs.every(j=>j.usage_complete)?data.jobs.reduce((sum,j)=>sum+Number(j.cost_usd),0):null,jobCalls=data.jobs.reduce((sum,j)=>sum+j.request_count,0),scopeLabel=data.snapshot.created_at;
 const topics=(rows:typeof s.positive_topics)=><>{rows.map(a=><article className="jev-theme-detail" key={a.key}><h4>{GOLD_TAXONOMY[a.theme_key][language]}</h4><p>{t.mentions}: {a.mentions} · {t.reviews}: {a.affected_reviews}</p><details><summary>{t.examples}</summary>{a.examples.map(e=><div key={e.review_id}><p className="jev-id">{e.review_id} · {e.rating}★</p><p className="gold-text" lang="en">{e.analysis_text}</p></div>)}</details></article>)}</>;
 return <><section className="card jev-card"><h2>Artisan Cafe & Eatery</h2><p>{t.intro}</p><p>{t.noReport}</p><p>{t.snapshot}: {scopeLabel}</p><p className="jev-id">{data.snapshot.id}<br/>{data.snapshot.configuration_id}</p><dl className="jev-pairs"><dt>{t.google}</dt><dd>{n(c.google_total,0)}</dd><dt>{t.stored}</dt><dd>{c.stored_reviews}</dd><dt>{t.text}</dt><dd>{c.reviews_with_text}</dd><dt>{t.textless}</dt><dd>{c.textless_reviews}</dd><dt>{t.english}</dt><dd>{c.english_ready}</dd><dt>{t.analysed}</dt><dd>{c.analysed_reviews}</dd><dt>{t.reused}</dt><dd>{data.initial_reused_reviews}</dd><dt>{t.missing}</dt><dd>{c.missing_analyses}</dd><dt>{t.noEnglish}</dt><dd>{c.missing_english}</dd><dt>{t.blocked}</dt><dd>{c.blocked_analyses}</dd><dt>{t.coverage}</dt><dd>{pct(c.analysis_text_coverage)}</dd><dt>{t.englishCoverage}</dt><dd>{pct(c.analysis_english_coverage)}</dd></dl>{s.warnings.includes('PARTIAL_TEXT_COVERAGE')&&<p className="pilot-warning">{t.partial}</p>}{s.warnings.includes('STAR_DISTRIBUTION_BIASED')&&<p className="pilot-warning">{t.biased}</p>}{s.warnings.includes('PARTIAL_GOOGLE_DATASET')&&<p className="pilot-warning">{t.googlePartial}</p>}{s.warnings.includes('MULTIPLE_SERVED_MODELS')&&<p className="pilot-warning">{t.modelMixed}</p>}{s.warnings.includes('ENGLISH_OVERRIDE_ANOMALY')&&<p className="pilot-warning">{t.override}</p>}<p>{t.model}: {data.audit.served_models.join(', ')}</p><details><summary>{t.cacheUsage}</summary><p>{t.calls}: {s.cache_usage.historical_calls} · {t.tokens}: {n(s.cache_usage.input_tokens,0)} / {n(s.cache_usage.output_tokens,0)}</p><p>{t.paidCost}: {usd(s.cache_usage.cost_usd)} · {t.reusedCost}: {usd(0)}</p></details>{refresh&&<button className="secondary-button full-width" disabled={busy} onClick={refresh}>{t.refresh}</button>}<details><summary>{t.initial}</summary><button className="secondary-button full-width" disabled={busy} onClick={()=>void act({action:'prepare_snapshot'})}>{t.refreshSnapshot}</button></details></section>
 <section className="card jev-card"><h2>{t.cost}</h2><dl className="jev-pairs"><dt>{t.reusedCost}</dt><dd>{usd(data.costs.reused_extra_cost_usd)}</dd><dt>{t.jevCost}</dt><dd>{usd(data.costs.estimated_jev_cost_usd)}</dd><dt>{t.solCost}</dt><dd>{usd(data.costs.estimated_sol_cost_usd)}</dd><dt>{t.total}</dt><dd>{usd(data.costs.total_known_usd)}</dd><dt>{t.apify}</dt><dd>{usd(data.costs.apify_cost_usd)}</dd><dt>{t.translation}</dt><dd>{usd(data.costs.translation_unit_cost_usd)}</dd></dl><p>{t.costNote}</p><p>{t.authorization}</p><button className="primary-button full-width" disabled={busy||!data.can_complete_jev} onClick={()=>setConfirm('jev')}>{t.complete}</button><button className="primary-button full-width" disabled={busy||!data.can_generate_sol} onClick={()=>setConfirm('sol')}>{t.generate}</button><p>{t.noChain}</p>{confirm&&<div role="alertdialog" aria-modal="true" aria-label={confirm==='jev'?t.confirmJev:t.confirmSol}><p>{confirm==='jev'?t.confirmJev:t.confirmSol}</p><p>{confirm==='jev'?data.costs.planned_jev_requests:1} · {usd(confirm==='jev'?data.costs.estimated_jev_cost_usd:data.costs.estimated_sol_cost_usd)}</p><p>{t.costNote}</p><button className="primary-button" disabled={busy} onClick={()=>void act({action:confirm==='jev'?'complete_jev':'generate_sol',confirm_cost:true,source_sha256:data.snapshot!.source_sha256,input_sha256:confirm==='jev'?data.plans.jev_input_sha256:data.plans.sol_input_sha256}).then(()=>setConfirm(null))}>{t.confirm}</button><button className="secondary-button" disabled={busy} onClick={()=>setConfirm(null)}>{t.cancel}</button></div>}</section>
 <section className="card jev-card"><h2>{t.free}</h2><p>{t.partial}</p>{s.axes.map(axis=><details key={axis.key}><summary>{t[axis.key]} · +{axis.positive_mentions} / −{axis.negative_mentions}</summary><p>{t.reviews}: +{axis.positive_review_count} / −{axis.negative_review_count}</p><h3>{t.positive}</h3>{topics(s.positive_topics.filter(a=>a.axis===axis.key))}<h3>{t.negative}</h3>{topics(s.negative_topics.filter(a=>a.axis===axis.key))}{axis.positive_mentions+axis.negative_mentions===0&&<p>{t.noSignal}</p>}</details>)}</section>
 <details className="card jev-card"><summary>{t.context}</summary><p>{t.contextNote}</p>{Object.entries(s.google_context.axes).map(([k,a])=><p key={k}>{k==='food'?t.quality:k==='service'?t.service:t.atmosphere}: {n(a.average_rating)} / 5 · {a.rating_count}</p>)}<p>{t.noPrice}</p></details>
 <section className="card jev-card"><h2>{t.comparison}</h2><p className="pilot-warning">{t.scopeWarning}</p><div className="pilot-comparison-grid"><article><h3>{t.old}</h3>{old&&<><dl className="jev-pairs"><dt>{t.version}</dt><dd>V{old.analysis_version}</dd><dt>{t.model}</dt><dd>{old.model??t.unknown}</dd><dt>{t.date}</dt><dd>{old.generated_at}</dd><dt>{t.language}</dt><dd>{old.preferred_language}</dd><dt>{t.stored}</dt><dd>{old.stored_reviews_count}</dd><dt>{t.oldIds}</dt><dd>{old.source_ids?.length??t.unknown}</dd><dt>{t.completeData}</dt><dd>{String(old.data_complete)}</dd><dt>{t.calls}</dt><dd>{n(old.ai_call_count,0)}</dd><dt>{t.tokens}</dt><dd>{n(old.ai_input_tokens,0)} / {n(old.ai_output_tokens,0)}</dd><dt>{t.paidCost}</dt><dd>{usd(old.ai_cost_usd)}</dd></dl><p lang={old.preferred_language}>{old.ai_historical_summary}</p><details><summary>{t.negative}</summary>{old.negative_themes.map(a=><p key={a.theme_key}>{language==='fr'?a.label_fr:a.label_vi} · {a.mentions}</p>)}</details><details><summary>{t.positive}</summary>{old.positive_themes.map(a=><p key={a.theme_key}>{language==='fr'?a.label_fr:a.label_vi} · {a.mentions}</p>)}</details><details><summary>{t.oldRecommendations}</summary>{((old.consultant_report?.axes??[]) as {key:string;recommendation:string}[]).map(a=><p key={a.key} lang={old.preferred_language}>{a.recommendation}</p>)}</details></>}</article><article><h3>{t.pilot}</h3><p>{t.newUsage}</p><dl className="jev-pairs"><dt>{t.stored}</dt><dd>{c.stored_reviews}</dd><dt>{t.analysed}</dt><dd>{reportStats.coverage.analysed_reviews}</dd><dt>{t.calls}</dt><dd>{jobCalls}</dd><dt>{t.tokens}</dt><dd>{data.jobs.reduce((n,j)=>n+j.input_tokens,0)} / {data.jobs.reduce((n,j)=>n+j.output_tokens,0)}</dd><dt>{t.paidCost}</dt><dd>{usd(jobCost)}</dd></dl><details><summary>{t.positive}</summary>{reportStats.positive_topics.map(a=><p key={a.key}>{GOLD_TAXONOMY[a.theme_key][language]} · {a.mentions}</p>)}</details><details><summary>{t.negative}</summary>{reportStats.negative_topics.map(a=><p key={a.key}>{GOLD_TAXONOMY[a.theme_key][language]} · {a.mentions}</p>)}</details>{report?<><p>{!data.report_matches_current_analysis?t.stale:''}</p>{report.origin!=='sol_aggregate_writer'&&<p>{t.fallback}</p>}{report.prose.axes.map(a=><div key={a.key}><h4>{t[a.key]}</h4><p>{a.description}</p></div>)}<h4>{t.positive}</h4>{report.prose.positive_aspects.map(a=><p key={a.key}>{a.text}</p>)}<h4>{t.negative}</h4>{report.prose.negative_aspects.map(a=><p key={a.key}>{a.text}</p>)}<h4>{t.newRecommendations}</h4><p>{report.prose.conclusion}</p>{report.prose.recommendations.map((r,index)=><p key={index}>{r.text}</p>)}</>:<p>{t.notGenerated}</p>}</article></div><p>{t.matched}</p></section>
 <details className="card jev-card"><summary>{t.audit}</summary><p>{t.rawCache}: {data.audit.raw_completed_full_cache_rows}</p><p>{t.excluded}: {data.audit.excluded_compact_or_other_rows}</p>{data.audit.rejected.map(r=><div key={r.cache_id}><p className="jev-id">{r.review_id}</p><p>{r.reasons.includes('ENGLISH_TEXT_CHANGED')?t.changedText:r.reasons.join(', ')}</p></div>)}</details><details className="card jev-card"><summary>{t.unavailable}</summary>{data.unavailable_reviews.filter(r=>r.reason!=='NO_REVIEW_TEXT').map(r=><p className="jev-id" key={r.review_id}>{r.review_id} · {t.noEnglish}</p>)}</details><section className="card jev-card"><h2>{t.jobs}</h2>{data.jobs.map(j=><p className="jev-id" key={j.id}>{j.stage.toUpperCase()} · {j.status} · {t.calls}: {j.request_count} · {t.tokens}: {j.input_tokens} / {j.output_tokens} · {t.paidCost}: {usd(j.usage_complete?Number(j.cost_usd):null)} · {t.duration}: {n(j.duration_ms/1000)} s · {j.error_code}</p>)}{data.jobs.some(j=>['queued','running'].includes(j.status))&&<div role="status"><p>{t.background}</p><p>{data.progress.completed} / {data.progress.total} · {data.progress.failed}</p><progress value={data.progress.completed+data.progress.failed} max={data.progress.total||1}/></div>}</section>
 </>
}
