import {useEffect,useState} from 'react'
import {Link} from 'react-router-dom'
import {useQuery,useQueryClient} from '@tanstack/react-query'
import {useApp} from '../app/AppContext'
import {useI18n} from '../i18n'
import {useJevAccess} from '../lib/use-jev-access'
import {PageHeader} from '../components/ui/PageHeader'
import {economyApi,type EconomyView} from '../lib/jev-economy'
import {economyMessages} from '../i18n/jev-economy'
import {THEME_KEYS} from '../../supabase/functions/_shared/jev-themes'
import {GOLD_TAXONOMY} from '../../supabase/functions/_shared/gold-taxonomy'
import {ECONOMY_MODES,type EconomyMode} from '../../supabase/functions/_shared/jev-economy-score'
import './JevBenchmarkPage.css'
import './GoldSetPage.css'
import './JevExploratoryPage.css'
export function JevEconomyEntry(){const {language}=useI18n(),t=economyMessages[language];return <section className="card jev-card"><h2>{t.title}</h2><p>{t.intro}</p><Link className="primary-button full-width exploratory-link" to="/plus/jev-economy">{t.open}</Link></section>}
export function JevEconomyPage(){const {currentUser,demoMode,establishments}=useApp(),{language}=useI18n(),t=economyMessages[language],access=useJevAccess(currentUser.id,demoMode),client=useQueryClient(),[selected,setSelected]=useState(()=>{try{return localStorage.getItem('jev-economy-est:'+currentUser.id)??'252a8dca-14c7-4f09-bd1f-7b2c40ae97aa'}catch{return '252a8dca-14c7-4f09-bd1f-7b2c40ae97aa'}}),id=establishments.some(e=>e.id===selected)?selected:establishments[0]?.id,key=['jev-economy',currentUser.id,id],q=useQuery({queryKey:key,enabled:access.data===true&&!!id,retry:false,staleTime:0,queryFn:()=>economyApi(id!)});
 useEffect(()=>{const refresh=()=>{if(!document.hidden)void client.invalidateQueries({queryKey:['jev-economy',currentUser.id]})};window.addEventListener('pageshow',refresh);document.addEventListener('visibilitychange',refresh);return()=>{window.removeEventListener('pageshow',refresh);document.removeEventListener('visibilitychange',refresh)}},[client,currentUser.id]);
 function choose(value:string){setSelected(value);try{localStorage.setItem('jev-economy-est:'+currentUser.id,value)}catch{/* Server records persist independently. */}}
 return <><PageHeader title={t.title} back/><div className="jev-page gold-page exploratory-page">{access.data===true&&<section className="card jev-card"><label htmlFor="economy-est">{t.establishment}</label><select className="full-width" id="economy-est" value={id??''} onChange={e=>choose(e.target.value)}>{establishments.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></section>}{access.isPending||q.isPending&&access.data===true?<p>{t.loading}</p>:access.data!==true?<p>{t.denied}</p>:q.isError?<section className="card jev-card" role="alert"><p>{t.error}</p><button className="secondary-button" disabled={q.isFetching} onClick={()=>void q.refetch()}>{t.refresh}</button></section>:q.data?<EconomyWorkspace data={q.data} refresh={()=>void q.refetch()} busy={q.isFetching}/>:null}<Link to="/plus/jev-benchmark">{t.back}</Link></div></>}
export function EconomyWorkspace({data,refresh,busy=false}:{data:EconomyView;refresh?:()=>void;busy?:boolean}){const {language}=useI18n(),t=economyMessages[language],[confirm,setConfirm]=useState(false),[mode,setMode]=useState<EconomyMode>('pass1'),n=(v:number|null,d=3)=>v===null?t.insufficient:v.toLocaleString(language==='fr'?'fr-FR':'vi-VN',{maximumFractionDigits:d}),pct=(v:number|null)=>v===null?t.insufficient:n(v*100,1)+' %',usd=(v:number|null)=>v===null?t.unknown:'USD '+n(v,6),p=data.plan,metrics=(v:{precision:number|null;recall:number|null;f1:number|null;support:number;fp:number;fn:number})=><dl className="jev-pairs"><dt>{t.support}</dt><dd>{v.support}</dd><dt>{t.precision}</dt><dd>{n(v.precision)}</dd><dt>{t.recall}</dt><dd>{n(v.recall)}</dd><dt>{t.f1}</dt><dd>{n(v.f1)}</dd><dt>FP / FN</dt><dd>{v.fp} / {v.fn}</dd></dl>,budget=(b:EconomyView['costs']['initial'])=><dl className="jev-pairs"><dt>{t.new}</dt><dd>{b.new_reviews}</dd><dt>{t.apify}</dt><dd>{usd(b.apify_import_usd)}</dd><dt>{t.translation}</dt><dd>{usd(b.translation_if_all_needed_usd)}</dd><dt>{t.jev}</dt><dd>{usd(b.jev_analysis_usd)}</dd><dt>3 × JEV</dt><dd>{usd(b.three_pass_jev_usd)}</dd><dt>{t.sol}</dt><dd>{usd(b.sol_final_report_usd)}</dd><dt>{t.subtotal}</dt><dd>{usd(b.known_jev_plus_sol_subtotal_usd)}</dd><dt>{t.fullCost}</dt><dd>{usd(b.total_with_import_and_translation_usd)}</dd><dt>{t.saving}</dt><dd>{b.jev_savings_percent===null?t.unknown:n(b.jev_savings_percent,1)+' %'}</dd></dl>;
 return <><section className="card jev-card"><h2>{t.ready}</h2><p>{t.intro}</p><p>{t.disabled}</p><h3>{data.establishment.name}</h3><dl className="jev-pairs"><dt>{t.total}</dt><dd>{p.total_google_reviews}</dd><dt>{t.text}</dt><dd>{p.reviews_with_text}</dd><dt>{t.cached}</dt><dd>{p.already_analyzed}</dd><dt>{t.missing}</dt><dd>{p.english_missing}</dd><dt>{t.blocked}</dt><dd>{p.analyses_blocked}</dd><dt>{t.new}</dt><dd>{p.new_reviews_needing_jev}</dd><dt>{t.calls}</dt><dd>{p.planned_jev_calls}</dd><dt>{t.estimate}</dt><dd>{usd(data.costs.incremental.jev_analysis_usd)}</dd><dt>{t.saving}</dt><dd>{n(p.nominal_call_savings_percent,1)} %</dd></dl><p>{t.cacheNote}</p><p>{t.model}: {p.expected_served_model}</p>{refresh&&<button className="secondary-button full-width" disabled={busy} onClick={refresh}>{t.refresh}</button>}<button className="secondary-button full-width" onClick={()=>setConfirm(true)}>{t.future}</button>{confirm&&<div role="alertdialog" aria-modal="true" aria-label={t.paid}><p>{t.paid}</p><p>{p.planned_jev_calls} · {usd(data.costs.incremental.jev_analysis_usd)}</p><p>{t.disabled}</p><button className="primary-button full-width" disabled>{t.launch}</button><button className="secondary-button" onClick={()=>setConfirm(false)}>{t.cancel}</button></div>}</section>
 <section className="card jev-card"><h2>{t.results}</h2><p>{t.warning}</p><p>{t.cohortNote}</p><p>{t.repeatNotice}</p><label htmlFor="economy-mode">{t.results}</label><select className="full-width" id="economy-mode" value={mode} onChange={e=>setMode(e.target.value as EconomyMode)}>{ECONOMY_MODES.map(m=><option key={m} value={m}>{t[m]}</option>)}</select></section>
 {data.comparisons.map(c=>{const v=c.variants[mode];return <section className="card jev-card" key={c.source_id}><h2>{c.source_kind==='first'?t.first:c.source_kind==='second'?t.second:t.third}</h2><p>{t.cohort}: {c.evaluable_reviews} / {c.source_reviews}</p><p>{t.uncertain}: {v.uncertain_labels}</p><h3>{t[mode]} · {t.negative}</h3>{metrics(v.negative)}<h3>{t.positive}</h3>{metrics(v.positive)}<p>{t.macro}: {n(v.macro_f1)}</p><p>{t.stability}: {pct(c.stability_measured_from_three_existing_repeats)}</p>{mode!=='mean3'&&<p>{t.oneStability}</p>}<p>{t.model}: {v.usage.served_models.join(', ')}</p><p>{t.tokens}: {v.usage.input_tokens??t.unknown} / {v.usage.output_tokens??t.unknown}</p><p>{t.observedCost}: {usd(v.usage.cost_usd)}</p><p>{t.saving}: {v.cost_savings_percent===null?t.unknown:n(v.cost_savings_percent,1)+' %'}</p>{v.bootstrap&&<details><summary>{t.ci}</summary>{(['negative','positive'] as const).map(pol=><p key={pol}>{t[pol]}: {n(v.bootstrap![pol].delta)} · [{n(v.bootstrap![pol].ci_95_low)} ; {n(v.bootstrap![pol].ci_95_high)}]</p>)}</details>}
 <details><summary>{t.axes}</summary>{(['quality','service','atmosphere','price'] as const).map(axis=><div key={axis}><h3>{t[axis]}</h3>{(['negative','positive'] as const).map(pol=><div key={pol}><h4>{t[pol]}</h4>{metrics(v.axes[axis][pol])}</div>)}</div>)}</details><details><summary>{t.themes}</summary>{THEME_KEYS.map(k=><article className="jev-theme-detail" key={k}><h3>{GOLD_TAXONOMY[k][language]}</h3>{(['negative','positive'] as const).map(pol=><div key={pol}><h4>{t[pol]}</h4>{metrics(v.themes[k][pol])}</div>)}</article>)}</details>
 <details><summary>{t.degraded} · {c.degraded_themes.length}</summary><p>{t.degradedNote}</p>{c.degraded_themes.map(d=><p key={d.theme_key+d.mode+d.polarity}>{GOLD_TAXONOMY[d.theme_key][language]} · {t[d.polarity]} · {t[d.mode]} · Δ F1 {n(d.delta_f1)}</p>)}</details><details><summary>{t.errors} · {v.errors.length}</summary>{v.errors.map((e,i)=><article className="jev-theme-detail" key={i}><p>{GOLD_TAXONOMY[e.theme_key][language]} · {t[e.polarity]} · {e.kind==='false_positive'?'FP':'FN'}</p><p className="jev-id">{t.review}: {e.review_id}</p><p>{t.reference}: {e.reference} · {t.prediction}: {e.prediction}</p></article>)}</details></section>})}
 <section className="card jev-card"><h2>{t.budget}</h2><p>{t.budgetNote}</p><h3>{t.initial}</h3>{budget(data.costs.initial)}<h3>{t.incremental}</h3>{budget(data.costs.incremental)}{data.costs.scenarios.map(s=><details key={s.new_reviews}><summary>{s.new_reviews} · {t.text}</summary>{budget(s)}</details>)}</section>
 <section className="card jev-card"><h2>{t.instructions}</h2><p>{t.instructionsNote}</p><p>{t.characters}: {data.instruction_audit.full_question_characters} → {data.instruction_audit.compact_question_characters}</p><p>{t.reduction}: {pct(data.instruction_audit.character_reduction)}</p><details><summary>{t.config}</summary>{data.configurations.map(c=><p className="jev-id" key={c.id}>{c.id}<br/>{c.config_sha256}</p>)}</details></section></>
}
