import {render,screen,fireEvent,cleanup,waitFor} from '@testing-library/react'
import {MemoryRouter} from 'react-router-dom'
import {afterEach,describe,it,expect,vi} from 'vitest'
import {I18nProvider} from '../i18n'
import {ExploratoryWorkspace,JevExploratoryEntry} from './JevExploratoryPage'
import {exploratoryProjection} from '../../supabase/functions/_shared/jev-exploratory-api'
import {EXPLORATORY_CONFIG,exploratoryFingerprint,exploratoryPredictions,type ExploratoryRun} from '../../supabase/functions/_shared/jev-exploratory-core'
import {syntheticNegative,syntheticNegativeTasks} from '../../tests/fixtures/negative-validation'
import {restorableRoute} from '../lib/navigation-state'
vi.mock('../lib/supabase',()=>({supabase:null}))
afterEach(cleanup)
async function fixture(status:'idle'|'completed'='completed'){const h=await syntheticNegative(),tasks=syntheticNegativeTasks(h),items=h.items.slice(0,1).map(i=>({review_id:i.review_id,position:i.position,analysis_text:i.analysis_text!,analysis_text_sha256:i.analysis_text_sha256!,overall_rating:i.overall_rating,normalized_category_ratings:i.normalized_category_ratings,v9:exploratoryPredictions(tasks,i.review_id,'v9'),v11:exploratoryPredictions(tasks,i.review_id,'v11')})),run:ExploratoryRun={id:h.run.id,source_id:h.run.id,source_kind:'negative_validation',organization_id:h.run.organization_id,establishment_id:h.run.establishment_id,status,config:EXPLORATORY_CONFIG,dataset_sha256:await exploratoryFingerprint(items),created_at:'2026-10-09',completed_at:null,started_at:null,rate:.042,error_code:null,locked_by:null};return exploratoryProjection(run,items,[],[],[],null)}
const mount=(node:React.ReactNode,language:'fr'|'vi'='fr')=>render(<MemoryRouter><I18nProvider language={language}>{node}</I18nProvider></MemoryRouter>)
describe('exploratory iPad workflow',()=>{
 it('entry is a navigation link, not a provider launch',()=>{mount(<JevExploratoryEntry/>);expect(screen.getByRole('link')).toHaveAttribute('href','/plus/jev-exploratory');expect(restorableRoute('/plus/jev-exploratory?id=abc')).toBe(true)})
 it('starts only after a manual click and payment confirmation',async()=>{const d=await fixture('idle'),action=vi.fn().mockResolvedValue(d);mount(<ExploratoryWorkspace data={d} busy={false} action={action}/>);expect(action).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Lancer l’analyse Jev V11'}));expect(action).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Confirmer'}));await waitFor(()=>expect(action).toHaveBeenCalledWith('start',{confirm:true}))})
 it('shows full English, rating, ID and probabilities without original identity',async()=>{const d=await fixture();mount(<ExploratoryWorkspace data={d} busy={false} action={vi.fn()}/>);expect(screen.getByText(d.items[0].analysis_text)).toBeInTheDocument();expect(screen.getByText(d.items[0].review_id)).toBeInTheDocument();expect(screen.getByText(/Note Google/)).toBeInTheDocument();expect(document.body.textContent).not.toContain('ORIGINAL_PRIVATE_SENTINEL');expect(screen.queryByText(/Écarts exploratoires/)).not.toBeInTheDocument()})
 it('requires selection and explicit GO before export',async()=>{const d=await fixture(),action=vi.fn().mockResolvedValue(d);mount(<ExploratoryWorkspace data={d} busy={false} action={action}/>);const go=screen.getByRole('button',{name:'GO — autoriser la réanalyse ChatGPT'});expect(go).toBeDisabled();fireEvent.click(screen.getByRole('checkbox',{name:'Sélectionner cet avis'}));fireEvent.click(go);expect(action).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Confirmer'}));await waitFor(()=>expect(action).toHaveBeenCalledWith('approve',{confirm:true,review_ids:[d.items[0].review_id]}))})
 it('renders Vietnamese and never asks to finalize human annotations',async()=>{mount(<ExploratoryWorkspace data={await fixture()} busy={false} action={vi.fn()}/>, 'vi');expect(screen.getByText('Đánh giá cần kiểm tra',{exact:false})).toBeInTheDocument();expect(screen.getByRole('button',{name:'GO — cho phép ChatGPT phân tích lại'})).toBeInTheDocument();expect(document.body.textContent).not.toContain('Finaliser les annotations humaines')})
})
