import {useEffect,useRef,useState} from 'react'
import {Link,useSearchParams} from 'react-router-dom'
import {useQuery,useQueryClient} from '@tanstack/react-query'
import {useApp} from '../app/AppContext'
import {useI18n} from '../i18n'
import {useJevAccess} from '../lib/use-jev-access'
import {PageHeader} from '../components/ui/PageHeader'
import {exploratoryApi,type ExploratoryData} from '../lib/jev-exploratory'
import {exploratoryMessages} from '../i18n/jev-exploratory'
import {GOLD_TAXONOMY} from '../../supabase/functions/_shared/gold-taxonomy'
import {THEME_KEYS} from '../../supabase/functions/_shared/jev-themes'
import './JevBenchmarkPage.css'
import './GoldSetPage.css'
import './JevExploratoryPage.css'
type Action=(action:string,payload?:Record<string,unknown>)=>Promise<ExploratoryData|null>
export function JevExploratoryEntry(){const {language}=useI18n(),t=exploratoryMessages[language];return <section className="card jev-card"><h2>{t.title}</h2><p>{t.intro}</p><Link className="primary-button full-width exploratory-link" to="/plus/jev-exploratory">{t.open}</Link></section>}
export function JevExploratoryPage(){const {currentUser,demoMode}=useApp(),{language}=useI18n(),t=exploratoryMessages[language],access=useJevAccess(currentUser.id,demoMode),[params,setParams]=useSearchParams(),id=params.get('id')??undefined,client=useQueryClient(),lock=useRef(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),key=['jev-exploration',currentUser.id,id],markerKey='jev-exploratory-paid:'+currentUser.id+':'+id
  const marker=()=>{try{return localStorage.getItem(markerKey)==='pending'}catch{return false}},mark=(v:boolean)=>{try{if(v)localStorage.setItem(markerKey,'pending');else localStorage.removeItem(markerKey)}catch{/* Server state is authoritative. */}}
  const query=useQuery({queryKey:key,enabled:access.data===true,retry:false,staleTime:0,queryFn:async()=>{const d=await exploratoryApi(id);if(d.run)mark(false);return d},refetchInterval:q=>!document.hidden&&(marker()||['queued','running'].includes(q.state.data?.run?.status??''))?2500:false})
  useEffect(()=>{const resume=()=>{if(!document.hidden)void client.invalidateQueries({queryKey:['jev-exploration',currentUser.id]})};window.addEventListener('pageshow',resume);document.addEventListener('visibilitychange',resume);return()=>{window.removeEventListener('pageshow',resume);document.removeEventListener('visibilitychange',resume)}},[client,currentUser.id])
  async function action(kind:string,payload:Record<string,unknown>={}){if(lock.current||query.isPending||query.isError||kind==='start'&&marker())return null;lock.current=true;setBusy(true);setError('');if(kind==='start')mark(true);try{const d=await exploratoryApi(query.data?.run?.id,kind,payload);if(kind==='start')mark(false);client.setQueryData(key,d);if(d.run&&d.run.id!==id){client.setQueryData(['jev-exploration',currentUser.id,d.run.id],d);setParams({id:d.run.id},{replace:true})}return d}catch(e){const code=e instanceof Error?e.message:'EXPLORATORY_CONNECTION_ERROR';if(['JEV_NOT_CONFIGURED','UNAUTHORIZED','FORBIDDEN'].includes(code))mark(false);setError(code);await query.refetch();return null}finally{lock.current=false;setBusy(false)}}
  return <><PageHeader title={t.title} back/><div className="jev-page gold-page exploratory-page">{access.isPending||query.isPending&&access.data===true?<p>{t.loading}</p>:access.data!==true?<p>{t.denied}</p>:<>{(error||query.isError||marker())&&<section className="card jev-card" role="alert"><p>{error.includes('CONTAMINATION')||error.includes('HOLDOUT')?t.conflict:t.error}</p><p className="jev-id">{error}</p><button className="secondary-button" disabled={busy||query.isFetching} onClick={()=>void query.refetch()}>{t.check}</button></section>}{query.data&&<ExploratoryWorkspace key={query.data.run?.id??'new'} data={query.data} busy={busy||query.isError||marker()} action={action}/>}</>}<Link to="/plus/jev-benchmark">{t.back}</Link></div></>
}
export function ExploratoryWorkspace({data,busy,action}:{data:ExploratoryData;busy:boolean;action:Action}){const {language}=useI18n(),t=exploratoryMessages[language],[source,setSource]=useState(()=>data.run?data.run.source_kind+':'+data.run.source_id:''),[confirm,setConfirm]=useState<'start'|'approve'|null>(null),[selected,setSelected]=useState<string[]>([]),[all,setAll]=useState(false),[bundle,setBundle]=useState<Record<string,unknown>|null>(null),[raw,setRaw]=useState(''),[localError,setLocalError]=useState(''),[notice,setNotice]=useState(''),[future,setFuture]=useState(''),importId=useRef<{raw:string;id:string}|null>(null),run=data.run,sourceEntry=data.sources.find(s=>s.kind+':'+s.id===source),number=(v:number|null)=>v===null?t.insufficient:v.toLocaleString(language==='fr'?'fr-FR':'vi-VN',{maximumFractionDigits:3})
  async function execute(kind:string,payload:Record<string,unknown>={}){setLocalError('');const d=await action(kind,payload);if(d){setConfirm(null);if(d.export_bundle)setBundle(d.export_bundle);if(kind==='reserve')setNotice(t.reserved)}return d}
  async function importCorrections(){try{const p=JSON.parse(raw);if(!p||typeof p!=='object'||Array.isArray(p)||p.experiment_id!==run?.id)throw new Error();if(importId.current?.raw!==raw)importId.current={raw,id:crypto.randomUUID()};await execute('import',{approval_id:p.approval_id,bundle_sha256:p.bundle_sha256,dataset_sha256:p.dataset_sha256,corrections:p.corrections,import_id:importId.current.id})}catch{setLocalError(t.importNote)}}
  const download=()=>{if(!bundle)return;const url=URL.createObjectURL(new Blob([JSON.stringify(bundle,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='home-reviews-chatgpt-'+String(bundle.approval_id)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  const items=data.items.filter(i=>all||i.reasons.length),metric=data.comparison
  return <><section className="card jev-card"><h2>{t.intro}</h2><label>{t.source}<select aria-label={t.source} value={source} onChange={e=>setSource(e.target.value)}><option value="">—</option>{data.sources.map(s=><option key={s.kind+s.id} value={s.kind+':'+s.id}>{s.name} · {s.ready}/{s.total} EN</option>)}</select></label>{sourceEntry&&<><p>{t.english} : {sourceEntry.ready} / {sourceEntry.total}</p><p>{sourceEntry.reuses_predictions?t.reused:t.fresh}</p><button className="secondary-button full-width" disabled={busy||sourceEntry.ready!==sourceEntry.total||!sourceEntry.total} onClick={()=>void execute('create',{source_id:sourceEntry.id,source_kind:sourceEntry.kind})}>{t.create}</button></>}{run&&<p className="jev-id">{run.id} · {run.status} · {data.review_count} · V11</p>}</section>
    {run&&run.status==='idle'&&<section className="card jev-card"><p>{t.fresh}</p><button className="primary-button full-width" disabled={busy} onClick={()=>setConfirm('start')}>{t.start}</button></section>}
    {run&&['queued','running'].includes(run.status)&&<section className="card jev-card" role="status"><p>{t.waiting}</p></section>}{run?.status==='failed'&&<p role="alert">{run.error_code}</p>}
    {run?.status==='completed'&&<><section className="card jev-card"><h2>{t.complete}</h2><p>{data.flagged_count} / {data.review_count} · {t.flagged}</p><p>{t.note}</p><label><input type="checkbox" checked={all} onChange={e=>setAll(e.target.checked)}/>{t.all}</label></section>
      {items.map(item=><article className="card jev-card" key={item.review_id}><p className="jev-id">{item.review_id}</p><p>{t.rating} : {item.overall_rating} / 5</p><p className="gold-text" lang="en">{item.analysis_text}</p>{item.reasons.length>0&&<><h3>{t.reasons}</h3><ul>{item.reasons.map((r,n)=><li key={n}>{t[r.code]}{r.theme_key?' · '+GOLD_TAXONOMY[r.theme_key][language]:''}{r.context?' · '+(t[r.context as keyof typeof t]??r.context):''}</li>)}</ul></>}<label><input type="checkbox" checked={selected.includes(item.review_id)} onChange={e=>setSelected(ids=>e.target.checked?[...ids,item.review_id]:ids.filter(id=>id!==item.review_id))}/>{t.select}</label>
        <details><summary>{t.themes}</summary>{THEME_KEYS.map(k=>{const p=item.v11[k];return <div className="jev-theme-detail" key={k}><strong>{GOLD_TAXONOMY[k][language]}</strong><p>{p?`${t[p.choice]} · + ${number(p.positive)} / − ${number(p.negative)} · ${p.stable?t.stable:t.unstable} · Δp ${number(p.probability_drift??null)}`:t.missing}</p>{item.v9[k]&&<p>{t.v9} : {t[item.v9[k]!.choice]}</p>}</div>})}</details></article>)}
      <section className="card jev-card"><h3>{t.go}</h3><p>{t.goNote}</p><p>{selected.length} / {data.flagged_count}</p><button className="primary-button full-width" disabled={busy||selected.length===0||selected.some(id=>!data.items.find(i=>i.review_id===id)?.reasons.length)} onClick={()=>setConfirm('approve')}>{t.go}</button>{data.approvals.length>0&&<details><summary>{t.approvals}</summary>{data.approvals.map(a=><div key={a.id}><p>{a.review_ids.length} · {a.approved_at}</p><button className="secondary-button full-width" disabled={busy} onClick={()=>void execute('export',{approval_id:a.id})}>{t.export}</button></div>)}</details>}{bundle&&<><button className="primary-button full-width" onClick={download}>{t.export}</button><button className="secondary-button full-width" onClick={()=>void navigator.clipboard.writeText(JSON.stringify(bundle,null,2)).then(()=>setNotice(t.copied)).catch(()=>setLocalError(t.export))}>{t.copy}</button><details><summary>JSON</summary><textarea aria-label="JSON export" readOnly value={JSON.stringify(bundle,null,2)}/></details></>}</section>
      <section className="card jev-card"><h3>{t.importTitle}</h3><p>{t.importNote}</p><label>{t.paste}<textarea aria-label={t.paste} value={raw} onChange={e=>setRaw(e.target.value)}/></label><button className="primary-button full-width" disabled={busy||!raw.trim()} onClick={()=>void importCorrections()}>{t.import}</button></section>
      {metric&&<section className="card jev-card"><h2>{t.comparison}</h2><p>{t.notHuman}</p><p>{t.compared} : {metric.compared_labels} · {t.differences} : {metric.different_labels} · {t.uncertain} : {metric.uncertain_labels} · {t.missing} : {metric.unavailable_labels}</p>{(['negative','positive'] as const).map(p=><div key={p}><h3>{t[p]} · {metric[p].support}</h3><dl className="jev-pairs"><dt>{t.precision}</dt><dd>{number(metric[p].precision_vs_ai_corrections)}</dd><dt>{t.recall}</dt><dd>{number(metric[p].recall_vs_ai_corrections)}</dd><dt>{t.f1}</dt><dd>{number(metric[p].f1_vs_ai_corrections)}</dd></dl></div>)}<details><summary>{t.importTitle} · {data.corrections.length}</summary>{data.corrections.map((c,n)=><article key={n} className="jev-theme-detail"><p className="jev-id">{c.review_id}</p><p>{GOLD_TAXONOMY[c.theme_key][language]} · V11 {c.initial_prediction?t[c.initial_prediction.choice]:t.missing} → ChatGPT {t[c.choice]}</p><p>{c.justification}</p><p>{c.corrector_model} · {c.corrected_at}</p></article>)}</details></section>}
      <details className="card jev-card"><summary>{t.future}</summary><p>{t.futureNote}</p><label>{t.version}<input type="number" min="12" value={future} onChange={e=>setFuture(e.target.value)}/></label><p>{selected.length}</p>{(['calibration','evaluation'] as const).map(p=><button key={p} className="secondary-button full-width" disabled={busy||selected.length===0||!Number.isInteger(Number(future))||Number(future)<=11} onClick={()=>void execute('reserve',{confirm:true,future_version:Number(future),purpose:p,review_ids:selected})}>{t[p]}</button>)}</details>
      {data.usage&&<section className="card jev-card"><h3>{t.usage}</h3><p>{data.usage.requests} · USD {data.usage.cost_usd.toFixed(6)}</p><p>Tokens {data.usage.input_tokens} / {data.usage.output_tokens}</p><p>{data.usage.served_models.join(', ')}</p>{data.usage.requests===0&&<p>{t.noCalls}</p>}</section>}
    </>}
    {confirm&&<section className="card jev-card" role="alertdialog" aria-modal="true" aria-label={confirm==='start'?t.start:t.go}><p>{confirm==='start'?t.paid:t.goNote}</p><button className="primary-button" disabled={busy} onClick={()=>void execute(confirm,{confirm:true,...(confirm==='approve'?{review_ids:selected}:{})})}>{t.confirm}</button><button className="secondary-button" disabled={busy} onClick={()=>setConfirm(null)}>{t.cancel}</button></section>}{localError&&<p role="alert">{localError}</p>}{notice&&<p role="status">{notice}</p>}
  </>
}
