import {useI18n} from '../i18n'
import {themeLabels} from '../i18n/jev-themes'
import type {compareLanguageEffect} from '../../supabase/functions/_shared/jev-language-effect'
type Effect=NonNullable<ReturnType<typeof compareLanguageEffect>>
const wording={fr:{title:'Comparaison langue',old:'V6 · Langues originales',new:'V7 · Analyse EN',delta:'Delta',common:'Avis communs',different:'Les datasets diffèrent : cette comparaison ne permet pas d’isoler la langue.',models:'La version Jev servie diffère : facteur de confusion.',parameters:'Les paramètres diffèrent : facteur de confusion.',support:'Support Sol',weak:'Échantillon insuffisant dans au moins un run',precision:'Précision',recall:'Rappel',stability:'Stabilité interne',cost:'Coût estimé',time:'Temps',choices:'Accord des Choice V6/V7',same:'Identiques',changed:'Différentes',miss:'Manquantes',technical:'Détails de la comparaison',note:'Seuil 0,50. Chaque benchmark utilise sa propre référence Sol ; les supports peuvent changer. Les différences ne prouvent pas une meilleure qualité. Aucun changement production.',strong_improvement:'Forte amélioration',moderate_improvement:'Amélioration modérée',neutral:'Effet neutre',regression:'Régression',not_evaluable:'Non mesurable',service:'Service',quality:'Qualité',price:'Prix',atmosphere:'Ambiance'},vi:{title:'So sánh ngôn ngữ',old:'V6 · Ngôn ngữ gốc',new:'V7 · Phân tích tiếng Anh',delta:'Chênh lệch',common:'Đánh giá chung',different:'Tập dữ liệu khác nhau: chưa thể tách riêng ảnh hưởng của ngôn ngữ.',models:'Phiên bản Jev khác nhau: yếu tố gây nhiễu.',parameters:'Tham số khác nhau: yếu tố gây nhiễu.',support:'Số tham chiếu Sol',weak:'Chưa đủ mẫu ở ít nhất một lần thử',precision:'Precision',recall:'Recall',stability:'Độ ổn định nội bộ',cost:'Chi phí ước tính',time:'Thời gian',choices:'Đồng thuận Choice V6/V7',same:'Giống nhau',changed:'Khác nhau',miss:'Còn thiếu',technical:'Chi tiết so sánh',note:'Ngưỡng 0,50. Mỗi benchmark dùng tham chiếu Sol riêng; số mẫu hỗ trợ có thể thay đổi. Khác biệt không chứng minh chất lượng tốt hơn. Không thay đổi hệ thống thực tế.',strong_improvement:'Cải thiện mạnh',moderate_improvement:'Cải thiện vừa',neutral:'Trung tính',regression:'Giảm hiệu quả',not_evaluable:'Chưa đo được',service:'Dịch vụ',quality:'Chất lượng',price:'Giá',atmosphere:'Không gian'}}
export function JevLanguageEffectResults({effect:e}:{effect:Effect}) {
  const {language}=useI18n(),t=wording[language]
  const n=(value:number|null,digits=3)=>value===null?'—':value.toLocaleString(language==='fr'?'fr-FR':'vi-VN',{minimumFractionDigits:digits,maximumFractionDigits:digits})
  const delta=(v:number|null,digits=3)=>v===null?'—':(v>0?'+':'')+n(v,digits)
  const pair=(a:number|null,b:number|null,d:number|null,digits=3)=><dl className="jev-pairs"><dt>{t.old}</dt><dd>{n(a,digits)}</dd><dt>{t.new}</dt><dd>{n(b,digits)}</dd><dt>{t.delta}</dt><dd>{delta(d,digits)}</dd></dl>
  const label=(key:string)=>{const row=e.themes[key].positive;return <article className="jev-theme-detail" key={key} data-language-target={key}><h4>{themeLabels[key][language]} · {language==='fr'?'positif':'tích cực'}</h4>{pair(row.v6.f1_vs_sol_reference,row.v7.f1_vs_sol_reference,row.delta)}<p className="jev-note">{t.support} : V6 {row.v6.support_sol_reference} · V7 {row.v7.support_sol_reference}</p>{!row.sufficient_support_both&&<span className="jev-tag jev-warning">{t.weak}</span>}<div className="jev-dual">{(['v6','v7'] as const).map(version=><div key={version}><h4>{version.toUpperCase()}</h4><p>{t.precision} : {n(row[version].precision_vs_sol_reference)}</p><p>{t.recall} : {n(row[version].recall_vs_sol_reference)}</p><p>F1 : {n(row[version].f1_vs_sol_reference)}</p></div>)}</div></article>}
  return <section className="card jev-card jev-language-effect"><h3>{t.title}</h3><span className="jev-tag">{t[e.language_effect_verdict]}</span><p>{t.old} → {t.new}</p><p>{t.common} : {e.common_reviews} · V6 {e.v6_reviews} · V7 {e.v7_reviews}</p><p className="jev-note">V6-only : {e.v6_only} · V7-only : {e.v7_only}</p>
    {!e.datasets_identical&&<p className="jev-warning">{t.different}</p>}{e.served_models.different&&<p className="jev-warning">{t.models}</p>}{!e.parameters_match&&<p className="jev-warning">{t.parameters}</p>}
    <h4>Micro F1</h4>{pair(e.micro_f1_v6,e.micro_f1_v7,e.micro_f1_delta)}<h4>Macro F1</h4>{pair(e.macro_f1_v6,e.macro_f1_v7,e.macro_f1_delta)}<h4>{t.stability}</h4>{pair(e.stability_v6,e.stability_v7,e.stability_delta)}
    {Object.entries(e.axes).map(([axis,a])=><div key={axis} data-language-axis={axis}><h4>{t[axis as 'service']}</h4>{pair(a.v6_micro_f1,a.v7_micro_f1,a.delta)}{!a.sufficient_support&&<small>{t.weak}</small>}</div>)}
    {['friendly_staff','attentiveness','professionalism','wait_time'].map(label)}
    <h4>{t.cost} · USD</h4>{pair(e.cost.v6,e.cost.v7,e.cost.cost_delta,6)}<p>Δ : {n(e.cost.cost_delta_percent,1)} %</p><h4>{t.time} · s</h4>{pair(e.latency.v6_elapsed_ms/1000,e.latency.v7_elapsed_ms/1000,e.latency.elapsed_delta_ms/1000)}<p>Δ : {n(e.latency.elapsed_delta_percent,1)} %</p><p className="jev-note">Jev V6 : {e.served_models.v6.join(', ')}<br/>Jev V7 : {e.served_models.v7.join(', ')}</p><p className="jev-note">{t.note}</p>
    <details className="jev-theme-list"><summary>{t.technical}</summary><p className="jev-note">Benchmark V6 : {e.v6_benchmark_id}</p><dl className="jev-pairs"><dt>Input V6 / V7</dt><dd>{e.cost.v6_input_tokens} / {e.cost.v7_input_tokens}</dd><dt>Output V6 / V7</dt><dd>{e.cost.v6_output_tokens} / {e.cost.v7_output_tokens}</dd></dl>{Object.entries(e.themes).map(([theme,rows])=><article className="jev-theme-detail" key={theme}><h4>{themeLabels[theme][language]}</h4>{(['positive','negative'] as const).map(sentiment=><div key={sentiment}><strong>{sentiment}</strong>{rows[sentiment].sufficient_support_both?pair(rows[sentiment].v6.f1_vs_sol_reference,rows[sentiment].v7.f1_vs_sol_reference,rows[sentiment].delta):<p>{t.weak}</p>}</div>)}<p className="jev-note">{t.choices} : {n(e.choices[theme].choice_agreement_percent,1)} % · {t.same} {e.choices[theme].same_choice_count} · {t.changed} {e.choices[theme].different_choice_count} · {t.miss} {e.choices[theme].missing_choice_count}</p></article>)}</details>
  </section>
}
