import {useEffect,useRef,useState} from 'react'
import {Link} from 'react-router-dom'
import {useQuery,useQueryClient} from '@tanstack/react-query'
import {useApp} from '../app/AppContext'
import {useI18n} from '../i18n'
import {useJevAccess} from '../lib/use-jev-access'
import {PageHeader} from '../components/ui/PageHeader'
import {v13Api,type V13View} from '../lib/jev-v13'
import {v13Messages} from '../i18n/jev-v13'
import {GOLD_TAXONOMY} from '../../supabase/functions/_shared/gold-taxonomy'
import {THEME_KEYS} from '../../supabase/functions/_shared/jev-themes'
import './JevBenchmarkPage.css'
import './GoldSetPage.css'
import './JevExploratoryPage.css'
export function JevV13Entry(){const {language}=useI18n(),t=v13Messages[language];return <section className="card jev-card"><h2>{t.title}</h2><p>{t.intro}</p><p>{t.noSwitch}</p><Link className="primary-button full-width exploratory-link" to="/plus/jev-v13-test">{t.open}</Link></section>}
export function JevV13Page(){const {currentUser,demoMode}=useApp(),{language}=useI18n(),t=v13Messages[language],access=useJevAccess(currentUser.id,demoMode),client=useQueryClient(),[source,setSource]=useState(()=>{try{const s=localStorage.getItem('v13-source:'+currentUser.id);return s&&(/^(development_first|development_second)$/.test(s)||/^fresh_blind_ai:[a-f0-9-]{36}$/.test(s))?s:'development_first'}catch{return 'development_first'}}),key=['v13',currentUser.id,source],markerKey='v13-paid-pending:'+currentUser.id+':'+source,lock=useRef(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),marker=()=>{try{return localStorage.getItem(markerKey)==='1'}catch{return false}},mark=(v:boolean)=>{try{if(v)localStorage.setItem(markerKey,'1');else localStorage.removeItem(markerKey)}catch{/* The server remains authoritative. */}}
 const q=useQuery({queryKey:key,enabled:access.data===true,retry:false,staleTime:0,queryFn:async()=>{const data=await v13Api(source);mark(false);return data},refetchInterval:query=>!document.hidden&&(marker()||['queued','running'].includes(query.state.data?.run?.status??''))?2500:false})
 useEffect(()=>{const refresh=()=>{if(!document.hidden)void client.invalidateQueries({queryKey:['v13',currentUser.id]})};window.addEventListener('pageshow',refresh);document.addEventListener('visibilitychange',refresh);return()=>{window.removeEventListener('pageshow',refresh);document.removeEventListener('visibilitychange',refresh)}},[client,currentUser.id])
 function choose(value:string){if(busy)return;setSource(value);setError('');try{localStorage.setItem('v13-source:'+currentUser.id,value)}catch{/* Navigation choice only. */}}
 async function start(){if(lock.current||q.isError||q.isPending||marker()||!q.data?.preview||q.data.run)return;lock.current=true;setBusy(true);setError('');mark(true);try{client.setQueryData(key,await v13Api(source,{configuration_sha256:q.data.configuration.config_sha256,prepared_sha256:q.data.preview.prepared_sha256}));mark(false)}catch(e){setError(e instanceof Error?e.message:'V13_CONNECTION_ERROR');await q.refetch()}finally{lock.current=false;setBusy(false)}}
 return <><PageHeader title={t.title} back/><div className="jev-page gold-page exploratory-page">{access.data===true&&<section className="card jev-card"><label htmlFor="v13-source">{t.source}</label><select id="v13-source" className="full-width" value={source} disabled={busy} onChange={e=>choose(e.target.value)}><option value="development_first">{t.first}</option><option value="development_second">{t.second}</option>{q.data?.fresh_sources.map(s=><option value={'fresh_blind_ai:'+s.id} key={s.id}>{s.name}</option>)}</select></section>}{access.isPending||q.isPending&&access.data===true?<p>{t.loading}</p>:access.data!==true?<p>{t.denied}</p>:<>{(error||q.isError)&&<section className="card jev-card" role="alert"><p>{t.error}</p><p className="jev-id">{error}</p><button className="secondary-button" disabled={busy||q.isFetching} onClick={()=>void q.refetch()}>{t.check}</button></section>}{q.data&&<V13Workspace data={q.data} busy={busy||q.isError||marker()} start={start} refresh={()=>void q.refetch()}/>}</>}<section className="card jev-card"><h2>{t.future}</h2><p>{q.data?.fresh_sources.length?t.futureAvailable:t.futurePending}</p></section><Link to="/plus/jev-benchmark">{t.back}</Link></div></>
}
export function V13Workspace({data,busy,start,refresh}:{data:V13View;busy:boolean;start:()=>Promise<void>;refresh?:()=>void}){const {language}=useI18n(),base=v13Messages[language],t={...base,warning:data.preview?.independent_for_v13?base.freshWarning:base.warning},[confirm,setConfirm]=useState(false),p=data.preview,c=data.comparison,n=(v:number|null,d=3)=>v===null?t.insufficient:v.toLocaleString(language==='fr'?'fr-FR':'vi-VN',{maximumFractionDigits:d}),percent=(v:number|null)=>v===null?t.insufficient:n(v*100,1)+' %',choice=(v:string)=>v==='uncertain'?t.uncertainChoice:v in t?t[v as 'positive'|'negative'|'absent'|'both']:v,m=(v:{precision:number|null;recall:number|null;f1:number|null;support:number;tp:number;fp:number;fn:number})=><dl className="jev-pairs"><dt>{t.support}</dt><dd>{v.support}</dd><dt>{t.precision}</dt><dd>{n(v.precision)}</dd><dt>{t.recall}</dt><dd>{n(v.recall)}</dd><dt>{t.f1}</dt><dd>{n(v.f1)}</dd><dt>TP / FP / FN</dt><dd>{v.tp} / {v.fp} / {v.fn}</dd></dl>,status=data.run?['queued','running'].includes(data.run.status)?t.running:data.run.status==='completed'?t.completed:t.failed:data.ready?t.ready:t.failed
 const errorCards=(kind:string)=>(['v12','v13'] as const).map(v=><div key={v}><h3>{v.toUpperCase()} · {c![v].errors.filter(e=>e.kind===kind).length}</h3>{c![v].errors.filter(e=>e.kind===kind).map(e=><article className="jev-theme-detail" key={e.review_id+e.theme_key+e.polarity}><h4>{GOLD_TAXONOMY[e.theme_key][language]} · {t[e.polarity]}</h4><p className="jev-id">{e.review_id}</p><p>{t.prediction}: {choice(e.predicted)} · {t.ai}: {choice(e.ai_reference)}</p><details><summary>{t.text}</summary><p className="gold-text" lang="en">{c!.reviews.find(r=>r.review_id===e.review_id)?.analysis_text}</p></details></article>)}</div>)
 return <><section className="card jev-card"><h2>{status}</h2><p>{t.intro}</p><p>{t.warning}</p><p>{t.frozen}</p><p>{t.noSwitch}</p>{!data.run&&<p>{t.notStarted}</p>}{p&&<><dl className="jev-pairs"><dt>{t.reviews}</dt><dd>{p.reviews}</dd><dt>{t.sourceReviews}</dt><dd>{p.source_reviews}</dd><dt>{t.reused}</dt><dd>{p.reused_v12_responses}</dd><dt>{t.newParent}</dt><dd>{p.new_v12_requests}</dd><dt>{t.labels}</dt><dd>{p.reference_labels}</dd><dt>{t.uncertain}</dt><dd>{p.uncertain_labels}</dd><dt>{t.requests}</dt><dd>{p.expected_requests}</dd><dt>{t.estimate}</dt><dd>USD {n(p.estimated_cost_usd,6)}</dd></dl><p>{t.estimateNote}</p><details><summary>{t.seal}</summary><p>{p.sealed_at} · {p.reference_model}</p><p className="jev-id">{p.dataset_fingerprint}<br/>{p.reference_fingerprint}</p></details>{p.translation_anomalies.length>0&&<details><summary>{t.translation} · {p.translation_anomalies.length}</summary>{p.translation_anomalies.map(a=><p className="jev-id" key={a.review_id+a.code}>{a.review_id} · {a.note}</p>)}</details>}</>}{data.error_code&&<p role="alert">{data.error_code}</p>}{refresh&&<button className="secondary-button full-width" disabled={busy} onClick={refresh}>{t.check}</button>}{!data.run&&<button className="primary-button full-width" disabled={busy||!data.ready||!p} onClick={()=>setConfirm(true)}>{t.start}</button>}{confirm&&!data.run&&<div role="alertdialog" aria-modal="true" aria-label={t.start}><p>{t.paid}</p><p>{p?.expected_requests} · USD {n(p?.estimated_cost_usd??null,6)}</p><p>{t.estimateNote}</p><button className="primary-button" disabled={busy} onClick={()=>void start().then(()=>setConfirm(false))}>{t.confirm}</button><button className="secondary-button" disabled={busy} onClick={()=>setConfirm(false)}>{t.cancel}</button></div>}{data.run&&<p className="jev-id">{data.run.id} · {data.run.error_code}</p>}</section>
 <details className="card jev-card"><summary>{t.config}</summary><p className="jev-id">{data.configuration.id}<br/>{data.configuration.config_sha256}</p><p>jev-latest · 3 repeats · concurrency 8</p>{(['v12','v13'] as const).map(v=><div key={v}><h3>{v.toUpperCase()}</h3><p className="jev-id">{data.configuration.config[v].question_set}<br/>{data.configuration.config[v].threshold_version}</p>{THEME_KEYS.map(k=><details key={k}><summary>{GOLD_TAXONOMY[k][language]} · +{data.configuration.config[v].thresholds[k].positive_threshold} / −{data.configuration.config[v].thresholds[k].negative_threshold}</summary><p className="gold-text" lang="en">{String((data.configuration.config[v].questions[k] as {instructions:string}).instructions)}</p></details>)}</div>)}</details>
 {data.run&&['queued','running'].includes(data.run.status)&&<section className="card jev-card" role="status"><p>{t.background}</p><p>{data.progress.completed} / {data.progress.total} · {data.progress.failed}</p><progress max={data.progress.total||192} value={data.progress.completed+data.progress.failed}/></section>}
 {c&&<><section className="card jev-card"><h2>{t.results}</h2><p>{t.warning}</p><p>{t.coverage}: {c.coverage.common} / {c.coverage.total} · V12 {c.coverage.v12} · V13 {c.coverage.v13}</p>{!c.coverage.complete&&<p role="alert">{t.partial}</p>}{(['v12','v13'] as const).map(v=><div key={v}><h3>{v.toUpperCase()}</h3>{m(c[v].overall)}<p>{t.micro}: {n(c[v].micro_f1)}</p><p>{t.macro}: {n(c[v].macro_f1)} · {c[v].macro_supported_labels}</p><h4>{t.negative}</h4>{m(c[v].negative)}<h4>{t.positive}</h4>{m(c[v].positive)}<p>{t.exact}: {percent(c[v].exact_choice_agreement)} · {c[v].exact_compared}</p><p>{t.stability}: {percent(c[v].repeat_choice_stability)}</p></div>)}<p>{t.disagreements}: {c.disagreement_count}</p><p>{t.recovery}: {c.calibration_diagnostics.missed_negative_recovered}</p><p>{t.regression}: {c.calibration_diagnostics.new_missed_negative}</p><p>{t.newFp}: {c.calibration_diagnostics.new_false_positives}</p></section>
 {c.audit_summary.total>0&&<section className="card jev-card"><h2>{t.audit}</h2><p>{t.auditNote}</p><dl className="jev-pairs"><dt>{t.auditTotal}</dt><dd>{c.audit_summary.total}</dd><dt>{t.probable}</dt><dd>{c.audit_summary.probable_v12_errors}</dd><dt>{t.corrections}</dt><dd>{c.audit_summary.reference_corrections}</dd><dt>{t.ambiguous}</dt><dd>{c.audit_summary.ambiguous_excluded}</dd><dt>{t.resolved}</dt><dd>{c.audit_summary.errors_resolved}</dd><dt>{t.unresolved}</dt><dd>{c.audit_summary.errors_unresolved}</dd></dl><details><summary>{t.audit}</summary>{c.audit_cases.map(a=><article className="jev-theme-detail" key={a.audit_id}><h4>{GOLD_TAXONOMY[a.theme_key][language]}</h4><p className="jev-id">{a.review_id}</p><p>V12: {a.v12_choice} · V13: {a.v13_choice} · {t.reviewed}: {choice(a.reviewed_ai_choice)}</p><p>{a.rationale_fr}</p><p>{a.verdict}</p></article>)}</details></section>}<section className="card jev-card"><h2>{t.bootstrap}</h2>{(['negative','overall'] as const).map(kind=><div key={kind}><h3>{kind==='negative'?t.negative:t.micro}</h3><p>{t.delta}: {n(c.bootstrap[kind].delta)}</p><p>{t.ci}: [{n(c.bootstrap[kind].ci_95_low)} ; {n(c.bootstrap[kind].ci_95_high)}]</p></div>)}</section>
 {(['quality','service','atmosphere','price'] as const).map(axis=><section className="card jev-card" key={axis}><h2>{t[axis]}</h2>{(['v12','v13'] as const).map(v=><div key={v}><h3>{v.toUpperCase()} · {t.negative}</h3>{m(c[v].axes[axis].negative)}<h3>{t.positive}</h3>{m(c[v].axes[axis].positive)}</div>)}</section>)}
 <details className="card jev-card"><summary>{t.themes}</summary>{THEME_KEYS.map(k=><article className="jev-theme-detail" key={k}><h3>{GOLD_TAXONOMY[k][language]}</h3>{(['v12','v13'] as const).map(v=><div key={v}><h4>{v.toUpperCase()} · {t.negative}</h4>{m(c[v].themes[k].negative)}<h4>{t.positive}</h4>{m(c[v].themes[k].positive)}</div>)}</article>)}</details>
 <details className="card jev-card"><summary>{t.fp}</summary>{errorCards('false_positive')}</details><details className="card jev-card"><summary>{t.fn}</summary>{errorCards('false_negative')}</details>
 <details className="card jev-card"><summary>{t.suspects} · {c.reviews.filter(r=>r.reasons.length).length}</summary>{c.reviews.filter(r=>r.reasons.length).map(r=><article className="jev-theme-detail" key={r.review_id}><p className="jev-id">{r.review_id}</p><p>{t.rating}: {r.overall_rating} / 5</p><p className="gold-text" lang="en">{r.analysis_text}</p>{r.reasons.map((a,j)=><p key={j}>{a.code in t?t[a.code as 'v12_v13_disagreement']:a.code} · {a.version?.toUpperCase()} · {a.theme_key?GOLD_TAXONOMY[a.theme_key][language]:''}</p>)}{THEME_KEYS.filter(k=>r.v12?.[k].choice!=='absent'||r.v13?.[k].choice!=='absent'||r.reasons.some(a=>a.theme_key===k)).map(k=><details key={k}><summary>{GOLD_TAXONOMY[k][language]}</summary>{(['v12','v13'] as const).map(v=><p key={v}>{v.toUpperCase()}: {r[v]?choice(r[v]![k].choice):t.insufficient} · +{n(r[v]?.[k].positive??null)} / −{n(r[v]?.[k].negative??null)} · {t.stability}: {String(r[v]?.[k].stable??t.insufficient)}</p>)}<p>{t.ai}: {choice(r.ai_reference[k])}</p></details>)}</article>)}</details>
 <section className="card jev-card"><h2>{t.usage}</h2>{c.model_version_confounded&&<p role="alert">{t.modelChanged}</p>}{(['v12','v13'] as const).map(v=><div key={v}><h3>{v.toUpperCase()}</h3>{!c.usage[v].usage_complete&&<p role="alert">{t.usageIncomplete}</p>}<p>{t.model}: {c.usage[v].served_models.join(', ')}</p><p>USD {n(c.usage[v].estimated_cost_usd,6)} · {c.usage[v].input_tokens} / {c.usage[v].output_tokens} tokens</p><p>{c.usage[v].requests} · {c.usage[v].request_elapsed_sum_ms} ms</p></div>)}<p>{t.historicalCost}: USD {n(c.historical_baseline_cost_usd,6)}</p><p>Total: USD {n(c.total_estimated_cost_usd,6)}</p><p>{t.invalidRate}: {percent(c.invalid_response_rate)}</p><p>{t.duration}: {n(c.end_to_end_elapsed_ms)} ms</p></section>
 <details className="card jev-card"><summary>{t.errors} · {c.failures.length}</summary>{c.failures.map((e,i)=><p className="jev-id" key={i}>{e.version} · {e.review_id} · {e.repeat} · {e.error_code}</p>)}</details>{c.translation_anomalies.length>0&&<details className="card jev-card"><summary>{t.translation}</summary>{c.translation_anomalies.map(a=><p key={a.review_id+a.code}>{a.review_id} · {a.note}</p>)}</details>}</>}
 </>
}
