import {render,screen,fireEvent,cleanup,waitFor} from '@testing-library/react'
import {MemoryRouter} from 'react-router-dom'
import {QueryClient,QueryClientProvider} from '@tanstack/react-query'
import {describe,it,expect,vi,afterEach} from 'vitest'
import {I18nProvider} from '../i18n'
import {JevV13Entry,JevV13Page,V13Workspace} from './JevV13Page'
import {syntheticV13View} from '../../tests/fixtures/jev-v13-view'
import {syntheticV13} from '../../tests/fixtures/jev-v13'
import {compareV13} from '../../supabase/functions/_shared/jev-v13-core'
import {restorableRoute} from '../lib/navigation-state'
const api=vi.hoisted(()=>vi.fn())
vi.mock('../lib/supabase',()=>({supabase:null}))
vi.mock('../lib/jev-v13',()=>({v13Api:api}))
vi.mock('../app/AppContext',()=>({useApp:()=>({currentUser:{id:'fixture-owner'},demoMode:false})}))
vi.mock('../lib/use-jev-access',()=>({useJevAccess:()=>({data:true,isPending:false})}))
vi.mock('../components/ui/PageHeader',()=>({PageHeader:()=>null}))
afterEach(()=>{cleanup();vi.clearAllMocks();localStorage.clear()})
const mount=(node:React.ReactNode,language:'fr'|'vi'='fr')=>render(<MemoryRouter><I18nProvider language={language}>{node}</I18nProvider></MemoryRouter>)
describe('manual V13 mobile replay',()=>{
 it('is accessible from Test Jev and its route is restorable',()=>{mount(<JevV13Entry/>);expect(screen.getByRole('link')).toHaveAttribute('href','/plus/jev-v13-test');expect(restorableRoute('/plus/jev-v13-test')).toBe(true)})
 it('shows configuration ready, benchmark not launched, reused V12 and diagnostic non-independent warning',async()=>{const start=vi.fn().mockResolvedValue(undefined);mount(<V13Workspace data={await syntheticV13View()} busy={false} start={start}/>);expect(screen.getByRole('heading',{name:'Configuration prête'})).toBeInTheDocument();expect(screen.getByText('Benchmark non lancé')).toBeInTheDocument();expect(screen.getByText(/ne démontrent aucune généralisation/)).toBeInTheDocument();expect(start).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Lancer le test V13'}));expect(start).not.toHaveBeenCalled();expect(screen.getByRole('alertdialog')).toHaveTextContent('USD');fireEvent.click(screen.getByRole('button',{name:'Confirmer le coût et lancer'}));await waitFor(()=>expect(start).toHaveBeenCalledTimes(1))})
 it('checks status without starting and blocks incompatible source/duplicates',async()=>{const d=await syntheticV13View(),refresh=vi.fn(),start=vi.fn();d.ready=false;d.error_code='V13_BASELINE_INCOMPATIBLE';mount(<V13Workspace data={d} busy={false} start={start} refresh={refresh}/>);fireEvent.click(screen.getByRole('button',{name:'Vérifier le statut'}));expect(start).not.toHaveBeenCalled();expect(refresh).toHaveBeenCalledTimes(1);expect(screen.getByRole('button',{name:'Lancer le test V13'})).toBeDisabled()})
 it('renders VI with the correct configuration/launch and no global quality claim',async()=>{mount(<V13Workspace data={await syntheticV13View()} busy={false} start={vi.fn()}/>, 'vi');expect(screen.getByRole('heading',{name:'Cấu hình sẵn sàng'})).toBeInTheDocument();expect(screen.getByText('Chưa chạy benchmark')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Chạy kiểm tra V13'})).toBeInTheDocument();expect(screen.getByText(/không chứng minh khả năng tổng quát/)).toBeInTheDocument()})
 it('completed second replay exposes 19 diagnostic audits, metrics/axes/themes/bootstrap and correct V12/V13 labels',async()=>{const f=await syntheticV13('second'),d=await syntheticV13View('second');d.run={id:f.run.id,status:'completed',created_at:'now',error_code:null};d.comparison=await compareV13(f.run,f.tasks);mount(<V13Workspace data={d} busy={false} start={vi.fn()}/>);expect(screen.getByRole('heading',{name:'Comparaison diagnostique V12 / V13'})).toBeInTheDocument();expect(screen.getByRole('heading',{name:'Replay des audits IA après consultation des prédictions'})).toBeInTheDocument();expect(screen.getByText(/référence des scores principaux ne sont pas réécrites/)).toBeInTheDocument();expect(screen.getByText('Résultats des 25 thèmes')).toBeInTheDocument();expect(screen.getByText(/Avis évaluables: 31 \/ 31 · V12 31 · V13 31/)).toBeInTheDocument()})
 it('restores the chosen second dataset and server run after remount; double tap never repeats paid POST',async()=>{const ready=await syntheticV13View('second');let server=ready;api.mockImplementation(async(_source,confirm)=>{if(confirm)server={...ready,run:{id:'saved',status:'running',created_at:'now',error_code:null},progress:{total:93,completed:20,failed:0}};return structuredClone(server)});localStorage.setItem('v13-source:fixture-owner','development_second');const page=()=>mount(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><JevV13Page/></QueryClientProvider>);const first=page();fireEvent.click(await screen.findByRole('button',{name:'Lancer le test V13'}));const confirm=screen.getByRole('button',{name:'Confirmer le coût et lancer'});fireEvent.click(confirm);fireEvent.click(confirm);await waitFor(()=>expect(screen.getByRole('status')).toHaveTextContent('20 / 93'));expect(api.mock.calls.filter(([,confirm])=>confirm)).toHaveLength(1);first.unmount();page();await waitFor(()=>expect(screen.getByRole('status')).toHaveTextContent('20 / 93'));expect(api.mock.calls.every(([source])=>source==='development_second')).toBe(true);expect(api.mock.calls.filter(([,confirm])=>confirm)).toHaveLength(1)})
})
