import {useEffect,useRef,useState} from 'react'
import {Link} from 'react-router-dom'
import {useQuery,useQueryClient} from '@tanstack/react-query'
import {useApp} from '../app/AppContext'
import {useI18n} from '../i18n'
import {useJevAccess} from '../lib/use-jev-access'
import {PageHeader} from '../components/ui/PageHeader'
import {v12Api,type V12View} from '../lib/jev-v12'
import {v12Messages} from '../i18n/jev-v12'
import {GOLD_TAXONOMY} from '../../supabase/functions/_shared/gold-taxonomy'
import {THEME_KEYS} from '../../supabase/functions/_shared/jev-themes'
import './JevBenchmarkPage.css'
import './GoldSetPage.css'
import './JevExploratoryPage.css'
export function JevV12Entry(){const {language}=useI18n(),t=v12Messages[language];return <section className="card jev-card"><h2>{t.title}</h2><p>{t.intro}</p><p>{t.noSwitch}</p><Link className="primary-button full-width exploratory-link" to="/plus/jev-v12-test">{t.open}</Link></section>}
export function JevV12TestPage(){const {currentUser,demoMode}=useApp(),{language}=useI18n(),t=v12Messages[language],access=useJevAccess(currentUser.id,demoMode),client=useQueryClient(),key=['v12',currentUser.id],markerKey='v12-paid-pending:'+currentUser.id,lock=useRef(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),marker=()=>{try{return localStorage.getItem(markerKey)==='1'}catch{return false}},mark=(v:boolean)=>{try{if(v)localStorage.setItem(markerKey,'1');else localStorage.removeItem(markerKey)}catch{/* Server state is authoritative. */}}
 const q=useQuery({queryKey:key,enabled:access.data===true,retry:false,staleTime:0,queryFn:async()=>{const data=await v12Api();mark(false);return data},refetchInterval:query=>!document.hidden&&(marker()||['queued','running'].includes(query.state.data?.run?.status??''))?2500:false})
 useEffect(()=>{const refresh=()=>{if(!document.hidden)void client.invalidateQueries({queryKey:['v12',currentUser.id]})};window.addEventListener('pageshow',refresh);document.addEventListener('visibilitychange',refresh);return()=>{window.removeEventListener('pageshow',refresh);document.removeEventListener('visibilitychange',refresh)}},[client,currentUser.id])
 async function start(){if(lock.current||q.isError||q.isPending||marker()||!q.data?.preview||q.data.run)return;lock.current=true;setBusy(true);setError('');mark(true);try{client.setQueryData(key,await v12Api({configuration_sha256:q.data.configuration.config_sha256,prepared_sha256:q.data.preview.prepared_sha256}));mark(false)}catch(e){setError(e instanceof Error?e.message:'V12_CONNECTION_ERROR');await q.refetch()}finally{lock.current=false;setBusy(false)}}
 return <><PageHeader title={t.title} back/><div className="jev-page gold-page exploratory-page">{access.isPending||q.isPending&&access.data===true?<p>{t.loading}</p>:access.data!==true?<p>{t.denied}</p>:<>{(error||q.isError)&&<section className="card jev-card" role="alert"><p>{t.error}</p><p className="jev-id">{error}</p><button className="secondary-button" disabled={busy||q.isFetching} onClick={()=>void q.refetch()}>{t.check}</button></section>}{q.data&&<V12Workspace data={q.data} busy={busy||q.isError||marker()} start={start}/>}</>}<Link to="/plus/jev-benchmark">{t.back}</Link></div></>
}
export function V12Workspace({data,busy,start}:{data:V12View;busy:boolean;start:()=>Promise<void>}){const {language}=useI18n(),t=v12Messages[language],[confirm,setConfirm]=useState(false),p=data.preview,c=data.comparison,n=(v:number|null,d=3)=>v===null?t.insufficient:v.toLocaleString(language==='fr'?'fr-FR':'vi-VN',{maximumFractionDigits:d}),percent=(v:number|null)=>v===null?t.insufficient:n(v*100,1)+' %',m=(v:{precision:number|null;recall:number|null;f1:number|null;support:number;tp:number;fp:number;fn:number})=><dl className="jev-pairs"><dt>{t.support}</dt><dd>{v.support}</dd><dt>{t.precision}</dt><dd>{n(v.precision)}</dd><dt>{t.recall}</dt><dd>{n(v.recall)}</dd><dt>{t.f1}</dt><dd>{n(v.f1)}</dd><dt>TP / FP / FN</dt><dd>{v.tp} / {v.fp} / {v.fn}</dd></dl>,status=data.run?['queued','running'].includes(data.run.status)?t.running:data.run.status==='completed'?t.completed:t.failed:data.ready?t.ready:t.failed
 const errors=(kind:'false_positive'|'false_negative')=>(['v11','v12'] as const).map(v=><div key={v}><h3>{v.toUpperCase()} · {c![v].errors.filter(e=>e.kind===kind).length}</h3>{c![v].errors.filter(e=>e.kind===kind).map(e=><article key={e.review_id+e.theme_key+e.polarity} className="jev-theme-detail"><h4>{GOLD_TAXONOMY[e.theme_key][language]} · {t[e.polarity]}</h4><p className="jev-id">{e.review_id}</p><p>{t.prediction} : {e.predicted} · {t.ai} : {e.ai_reference}</p><details><summary>{t.text}</summary><p className="gold-text" lang="en">{c!.reviews.find(r=>r.review_id===e.review_id)?.analysis_text}</p></details></article>)}</div>)
 return <><section className="card jev-card"><h2>{status}</h2><p>{t.intro}</p><p>{t.warning}</p><p>{t.holdout}</p><p>{t.frozenText}</p>{p&&<><dl className="jev-pairs"><dt>{t.source}</dt><dd>{p.source_reviews}</dd><dt>{t.eligible}</dt><dd>{p.eligible_reviews}</dd><dt>{t.invalid}</dt><dd>{p.source_invalid_responses}</dd><dt>{t.rechecks}</dt><dd>{p.rechecks_total}</dd><dt>{t.applied}</dt><dd>{p.rechecks_applied}</dd><dt>{t.uncertain}</dt><dd>{p.uncertain_labels}</dd><dt>{t.requests}</dt><dd>{p.expected_requests}</dd><dt>{t.estimate}</dt><dd>USD {n(p.estimated_cost_usd,6)}</dd></dl><p>{t.estimateNote}</p><details><summary>{t.excluded} · {p.source_exclusions.length}</summary>{p.source_exclusions.map(r=><p className="jev-id" key={r.review_id}>{r.review_id} · {r.errors.map(e=>e.version+': '+e.error_code).join(', ')}</p>)}</details></>}{data.error_code&&<p role="alert">{data.error_code}</p>}{!data.run&&<button className="primary-button full-width" disabled={busy||!data.ready||!p} onClick={()=>setConfirm(true)}>{t.start}</button>}{confirm&&!data.run&&<div role="alertdialog" aria-modal="true" aria-label={t.start}><p>{t.paid}</p><p>{p?.expected_requests} · USD {n(p?.estimated_cost_usd??null,6)}</p><p>{t.estimateNote}</p><button className="primary-button" disabled={busy} onClick={()=>void start().then(()=>setConfirm(false))}>{t.confirm}</button><button className="secondary-button" disabled={busy} onClick={()=>setConfirm(false)}>{t.cancel}</button></div>}{data.run&&<p className="jev-id">{data.run.id} · {data.run.error_code}</p>}</section>
 <details className="card jev-card"><summary>{t.config}</summary><p className="jev-id">{data.configuration.id}<br/>{data.configuration.config_sha256}</p><p>{data.configuration.frozen_at}</p><p>jev-latest · {data.configuration.config.repeat_count} repeats · {data.configuration.config.concurrency} concurrent</p><p>{t.threshold}</p>{THEME_KEYS.map(k=><div key={k} className="jev-theme-detail"><h4>{GOLD_TAXONOMY[k][language]}</h4><p>+ {data.configuration.config.thresholds[k].positive_threshold} / − {data.configuration.config.thresholds[k].negative_threshold}</p><details><summary>{t.definitions}</summary><p className="gold-text" lang="en">{String((data.configuration.config.questions[k] as {instructions:string}).instructions)}</p></details></div>)}</details>
 {data.run&&['queued','running'].includes(data.run.status)&&<section className="card jev-card" role="status"><p>{t.background}</p><p>{data.progress.completed} / {data.progress.total} · {data.progress.failed}</p><progress max={data.progress.total||p?.expected_requests||1} value={data.progress.completed+data.progress.failed}/></section>}
 {c&&<><section className="card jev-card"><h2>{t.results}</h2><p>{c.evaluable_reviews} / {c.eligible_reviews} · {t.eligible}</p><p>{t.warning}</p>{!c.complete&&<p role="alert">{t.partial}</p>}{(['v11','v12'] as const).map(v=><div key={v}><h3>{v.toUpperCase()}</h3>{m(c[v].overall)}<p>{t.micro} : {n(c[v].micro_f1)}</p><p>{t.macro} : {n(c[v].macro_f1)} · {c[v].macro_supported_labels}</p><p>{t.exact} : {percent(c[v].exact_choice_agreement)}</p><p>{t.stability} : {percent(c[v].repeat_choice_stability)}</p><p>{t.drift} : {n(c[v].mean_probability_drift)} / {n(c[v].p95_probability_drift)}</p></div>)}</section>
 {(['negative','positive'] as const).map(polarity=><section key={polarity} className="card jev-card"><h3>{t[polarity]}</h3>{(['v11','v12'] as const).map(v=><div key={v}><h4>{v.toUpperCase()}</h4>{m(c[v][polarity])}</div>)}</section>)}
 {(['quality','service','atmosphere','price'] as const).map(axis=><section className="card jev-card" key={axis}><h3>{t[axis]}</h3>{(['negative','positive'] as const).map(polarity=><div key={polarity}><p>{t[polarity]} · {t.support} {c.v11.axes[axis][polarity].support}</p><p>V11 F1 {n(c.v11.axes[axis][polarity].f1)} · V12 F1 {n(c.v12.axes[axis][polarity].f1)}</p><details><summary>{t.precision} / {t.recall}</summary>{(['v11','v12'] as const).map(v=><div key={v}><h4>{v.toUpperCase()}</h4>{m(c[v].axes[axis][polarity])}</div>)}</details></div>)}</section>)}
 <details className="card jev-card"><summary>{t.themes}</summary>{THEME_KEYS.map(k=><article key={k} className="jev-theme-detail"><h3>{GOLD_TAXONOMY[k][language]}</h3>{(['positive','negative'] as const).map(polarity=><div key={polarity}><h4>{t[polarity]}</h4>{(['v11','v12'] as const).map(v=><div key={v}><p>{v.toUpperCase()}</p>{m(c[v].themes[k][polarity])}</div>)}</div>)}</article>)}</details>
 <section className="card jev-card"><h3>{t.bootstrap}</h3>{(['negative','overall'] as const).map(kind=><div key={kind}><h4>{kind==='negative'?t.negative:t.micro}</h4><p>{t.delta} : {n(c.bootstrap[kind].delta)}</p><p>{t.ci} : {c.bootstrap[kind].ci_95_low===null?t.insufficient:`[${n(c.bootstrap[kind].ci_95_low)} ; ${n(c.bootstrap[kind].ci_95_high)}]`}</p></div>)}<p>{t.warning}</p></section>
 {(['false_positive','false_negative'] as const).map(kind=><details className="card jev-card" key={kind}><summary>{kind==='false_positive'?t.fp:t.fn}</summary>{errors(kind)}</details>)}
 <section className="card jev-card"><h3>{t.suspects} · {c.reviews.filter(r=>r.reasons.length).length}</h3><p>V11 / V12 : {c.disagreement_count}</p>{c.reviews.filter(r=>r.reasons.length).map(r=><details key={r.review_id} className="jev-theme-detail"><summary className="jev-id">{r.review_id} · {r.reasons.length}</summary><p>{t.rating} : {r.overall_rating} / 5</p><p className="gold-text" lang="en">{r.analysis_text}</p><ul>{r.reasons.map((reason,n)=><li key={n}>{t[reason.code as keyof typeof t]??reason.code}{reason.theme_key?' · '+GOLD_TAXONOMY[reason.theme_key][language]:''}</li>)}</ul>{THEME_KEYS.filter(k=>r.reasons.some(reason=>reason.theme_key===k)).map(k=><p key={k}>{GOLD_TAXONOMY[k][language]} · V11 {r.v11[k].choice} (+{n(r.v11[k].positive)} / −{n(r.v11[k].negative)}) · V12 {r.v12?`${r.v12[k].choice} (+${n(r.v12[k].positive)} / −${n(r.v12[k].negative)})`:t.incomplete_v12} · {t.ai} : {r.ai_reference[k]}</p>)}{r.safety&&<p>{t.reported_symptoms_no_causality}</p>}</details>)}</section>
 <section className="card jev-card"><h3>{t.errors} · {c.v12_failures.length}</h3>{c.v12_failures.map((e,n)=><p className="jev-id" key={n}>{e.review_id} · {e.repeat} · {e.error_code}</p>)}</section>
 <section className="card jev-card"><h3>{t.usage}</h3><p>{t.historical}</p>{(['v11','v12'] as const).map(v=><div key={v}><h4>{v.toUpperCase()}</h4><p>{t.model} : {c.usage[v].served_models.join(', ')}</p><p>Tokens {c.usage[v].input_tokens} / {c.usage[v].output_tokens} · {c.usage[v].requests} requests</p><p>USD {n(c.usage[v].estimated_cost_usd,6)}</p><p>{t.requestDuration} : {n(c.usage[v].request_elapsed_sum_ms/1000)} s</p>{!c.usage[v].usage_complete&&<p>{t.partial}</p>}</div>)}<p>{t.duration} : {n(c.end_to_end_elapsed_ms===null?null:c.end_to_end_elapsed_ms/1000)} s</p>{c.model_version_confounded&&<p role="alert">{t.modelChanged}</p>}<p>{t.noSwitch}</p></section>
 </>}</>
}
