import {render,screen,fireEvent,waitFor,cleanup} from '@testing-library/react'
import {QueryClient,QueryClientProvider} from '@tanstack/react-query'
import {MemoryRouter} from 'react-router-dom'
import {afterEach,it,expect,vi} from 'vitest'
import {I18nProvider} from '../i18n'
import {NegativeValidationEntry,NegativeValidationPage} from './NegativeValidationPage'
import {syntheticNegative,completeNegative} from '../../tests/fixtures/negative-validation'
import {negativeProjection} from '../../supabase/functions/_shared/negative-validation-api'
const api=vi.hoisted(()=>vi.fn())
const backfill=vi.hoisted(()=>vi.fn())
vi.mock('../lib/negative-validation',()=>({negativeValidationApi:api,ARTISAN_NEGATIVE:'252a8dca-14c7-4f09-bd1f-7b2c40ae97aa'}));vi.mock('../lib/english-backfill',()=>({englishBackfillApi:backfill}));vi.mock('../lib/use-jev-access',()=>({useJevAccess:()=>({data:true,isPending:false})}));vi.mock('../app/AppContext',()=>({useApp:()=>({currentUser:{id:'user'},demoMode:false,notifications:[]})}));vi.mock('../components/ui/PageHeader',()=>({PageHeader:({title}:{title:string})=><header>{title}</header>}))
afterEach(()=>{cleanup();vi.clearAllMocks();localStorage.clear()})
function mount(entry=false){return render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false,gcTime:0}}})}><MemoryRouter initialEntries={['/plus/negative-validation']}><I18nProvider language="fr">{entry?<NegativeValidationEntry/>:<NegativeValidationPage/>}</I18nProvider></MemoryRouter></QueryClientProvider>)}
it('entry reads only; explicit double tap creates one experiment, no models/backfill',async()=>{const h=await syntheticNegative();api.mockImplementation(async(_id,action)=>negativeProjection(action?h.run:null,action?h.items:[],[],null,false,null));mount(true);const btn=await screen.findByRole('button',{name:'Créer l’expérience'});await waitFor(()=>expect(btn).toBeEnabled());expect(api.mock.calls.every(c=>!c[1])).toBe(true);fireEvent.click(btn);fireEvent.click(btn);await waitFor(()=>expect(api.mock.calls.filter(c=>c[1]==='create')).toHaveLength(1));expect(backfill).not.toHaveBeenCalled()})
it('incomplete English blocks annotation and model launch; Apify needs cost confirmation and explicit click',async()=>{const h=await syntheticNegative();h.items[0].analysis_text=null;h.items[0].analysis_source='english_pending';h.items[0].analysis_language=null;h.items[0].analysis_text_sha256=null;api.mockResolvedValue(negativeProjection(h.run,h.items,[],null,true,null));backfill.mockImplementation(async(_est,method)=>({job:method==='POST'?{id:'job',status:'queued'}:null,coverage:{}}));mount();await screen.findByText('Préparation anglaise incomplète');expect(screen.queryByText('Avis 1 / 32')).toBeNull();expect(screen.queryByRole('button',{name:'Comparer Jev V9 et V11'})).toBeNull();fireEvent(window,new Event('pageshow'));expect(backfill).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Préparer les textes en anglais'}));await screen.findByRole('alertdialog');expect(backfill).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Confirmer'}));await waitFor(()=>expect(backfill.mock.calls.filter(c=>c[1]==='POST')).toHaveLength(1));expect(api.mock.calls.every(c=>!c[1])).toBe(true)})
it('entire annotation page is blind; completed human labels expose a manual benchmark only',async()=>{const h=await syntheticNegative();api.mockResolvedValue(negativeProjection(h.run,h.items,[],null,true,null));const a=mount();await screen.findByText('Avis 1 / 32');expect(document.body.textContent).not.toMatch(/V9|V11|Jev|Sol|rating|★/);a.unmount();const labels=await completeNegative(h);api.mockImplementation(async(_id,action)=>{if(action==='start_benchmark'){h.run.benchmark_status='queued'}return negativeProjection(h.run,h.items,labels,null,false,null)});mount();const btn=await screen.findByRole('button',{name:'Comparer Jev V9 et V11'});expect(api.mock.calls.every(c=>!c[1])).toBe(true);fireEvent.click(btn);fireEvent.click(btn);await screen.findByText('Comparaison Jev en cours');expect(api.mock.calls.filter(c=>c[1]==='start_benchmark')).toHaveLength(1);expect(backfill).not.toHaveBeenCalled()})
