import {useState,useRef,useEffect} from 'react'
import {Link,useNavigate,useSearchParams} from 'react-router-dom'
import {useQuery,useQueryClient} from '@tanstack/react-query'
import {Info} from 'lucide-react'
import {useApp} from '../app/AppContext'
import {useI18n} from '../i18n'
import {useJevAccess} from '../lib/use-jev-access'
import {PageHeader} from '../components/ui/PageHeader'
import {negativeMessages} from '../i18n/negative-validation'
import {negativeValidationApi,ARTISAN_NEGATIVE,type NegativeData} from '../lib/negative-validation'
import {englishBackfillApi} from '../lib/english-backfill'
import type {GoldChoice,GoldTheme} from '../../supabase/functions/_shared/gold-taxonomy'
import './JevBenchmarkPage.css'
import './GoldSetPage.css'
type Action=(kind:string,payload?:Record<string,unknown>)=>Promise<boolean>
export function NegativeValidationEntry(){const {currentUser}=useApp(),{language}=useI18n(),t=negativeMessages[language],navigate=useNavigate(),lock=useRef(false),[busy,setBusy]=useState(false),[error,setError]=useState(false),q=useQuery({queryKey:['negative-entry',currentUser.id],queryFn:()=>negativeValidationApi(undefined,undefined,{},true),retry:false,staleTime:0})
  async function start(){if(lock.current||q.isPending||q.isError)return;if(q.data?.run){navigate('/plus/negative-validation?id='+q.data.run.id);return}lock.current=true;setBusy(true);try{const d=await negativeValidationApi(undefined,'create');if(!d.run)throw new Error('NEGATIVE_CREATE_FAILED');navigate('/plus/negative-validation?id='+d.run.id)}catch{setError(true);await q.refetch()}finally{lock.current=false;setBusy(false)}}
  return <section className="card jev-card"><h3>{t.title}</h3><p>{t.intro}</p><ol>{t.steps.map(s=><li key={s}>{s}</li>)}</ol><p>{t.selection}</p><p>{t.bias}</p>{q.data?.run&&<p>{q.data.coverage.ready} / 32 · {t.ready}</p>}<button className="primary-button full-width" disabled={busy||q.isPending||q.isError} onClick={()=>void start()}>{busy?t.saving:q.data?.run?.benchmark_status==='completed'?t.show:q.data?.run?t.resume:t.create}</button>{(error||q.isError)&&<div role="alert"><p>{t.error}</p><button className="secondary-button" onClick={()=>void q.refetch()}>{t.check}</button></div>}</section>
}
export function NegativeValidationPage(){const {currentUser,demoMode}=useApp(),{language}=useI18n(),t=negativeMessages[language],access=useJevAccess(currentUser.id,demoMode),[params,setParams]=useSearchParams(),client=useQueryClient(),lock=useRef(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[prepareConfirm,setPrepareConfirm]=useState(false),id=params.get('id')??undefined,key=['negative-validation',currentUser.id,id],storage='negative-paid:'+currentUser.id+':'+id
  const marker=()=>{try{return localStorage.getItem(storage)}catch{return null}},setMarker=(v:string|null)=>{try{if(v)localStorage.setItem(storage,v);else localStorage.removeItem(storage)}catch{/* Server jobs remain authoritative. */}}
  const q=useQuery<NegativeData>({queryKey:key,enabled:access.data===true,retry:false,staleTime:0,queryFn:async()=>{const d=await negativeValidationApi(id);if(marker()==='benchmark'&&d.run?.benchmark_status!=='idle'||marker()==='backfill'&&d.backfill)setMarker(null);return d},refetchInterval:query=>!document.hidden&&(marker()||['queued','running'].includes(query.state.data?.run?.benchmark_status??'')||['queued','starting','running'].includes(query.state.data?.backfill?.status??''))?2500:false})
  useEffect(()=>{const resume=()=>{if(!document.hidden)void client.invalidateQueries({queryKey:['negative-validation',currentUser.id]})};window.addEventListener('pageshow',resume);document.addEventListener('visibilitychange',resume);return()=>{window.removeEventListener('pageshow',resume);document.removeEventListener('visibilitychange',resume)}},[client,currentUser.id])
  async function action(kind:string,payload:Record<string,unknown>={}){if(lock.current||q.isPending||q.isError||kind==='start_benchmark'&&marker())return false;lock.current=true;setBusy(true);setError('');try{if(kind==='start_benchmark')setMarker('benchmark');const data=await negativeValidationApi(q.data?.run?.id,kind,{revision:q.data?.run?.revision,...payload});if(kind==='start_benchmark')setMarker(null);client.setQueryData(key,data);if(data.run&&!id){client.setQueryData(['negative-validation',currentUser.id,data.run.id],data);setParams({id:data.run.id},{replace:true})}return true}catch(e){const code=e instanceof Error?e.message:'NEGATIVE_CONNECTION_ERROR';if(['JEV_NOT_CONFIGURED','UNAUTHORIZED','FORBIDDEN','NEGATIVE_HUMAN_REQUIRED','NEGATIVE_REVISION_CHANGED'].includes(code))setMarker(null);setError(code);await q.refetch();return false}finally{lock.current=false;setBusy(false)}}
  async function prepare(){if(lock.current||marker())return;lock.current=true;setBusy(true);setError('');try{const current=await englishBackfillApi(ARTISAN_NEGATIVE);if(!['queued','starting','running'].includes(current.job?.status??'')){setMarker('backfill');await englishBackfillApi(ARTISAN_NEGATIVE,'POST')}setMarker(null);setPrepareConfirm(false);await q.refetch()}catch(e){const code=e instanceof Error?e.message:'NEGATIVE_CONNECTION_ERROR';if(['APIFY_TOKEN_MISSING','FORBIDDEN','UNAUTHORIZED'].includes(code))setMarker(null);setError(code);await q.refetch()}finally{lock.current=false;setBusy(false)}}
  const data=q.data,run=data?.run,annotating=run?.status==='draft'&&data?.coverage.ready===32,backfillActive=['queued','starting','running'].includes(data?.backfill?.status??'')
  return <><PageHeader title={annotating?t.annotationTitle:t.title} back/><div className="jev-page gold-page">{access.isPending||q.isPending&&access.data===true?<p>{t.loading}</p>:access.data!==true?<p>{t.denied}</p>:<>
    {(q.isError||error||marker())&&<section className="card jev-card" role="alert"><p>{marker()?t.pending:error==='NEGATIVE_REVISION_CHANGED'?t.conflict:t.error}</p><button className="secondary-button" disabled={busy||q.isFetching} onClick={()=>void q.refetch()}>{t.check}</button></section>}
    {!run&&!q.isError&&<section className="card jev-card"><h2>{t.title}</h2><p>{t.selection}</p><p>{t.bias}</p><button className="primary-button full-width" disabled={busy} onClick={()=>void action('create')}>{t.create}</button></section>}
    {run&&data&&(annotating?<NegativeAnnotation data={data} user={currentUser.id??''} busy={busy||q.isError} action={action}/>:run.status==='draft'?<section className="card jev-card"><h2>{t.incomplete}</h2><dl className="jev-pairs"><dt>{t.selected}</dt><dd>{data.coverage.selected}</dd><dt>{t.ready}</dt><dd>{data.coverage.ready}</dd><dt>{t.missing}</dt><dd>{data.coverage.missing}</dd></dl><p>{t.noReplacement}</p><p>{t.apifyCost}</p>{backfillActive&&<p role="status">{t.loading} · {data.backfill?.status}<br/>{t.continue}</p>}{data.backfill?.error_code&&<p role="alert">{data.backfill.error_code}</p>}<button className="primary-button full-width" disabled={busy||backfillActive||!!marker()} onClick={()=>setPrepareConfirm(true)}>{t.prepare}</button><button className="secondary-button full-width" disabled={busy||backfillActive} onClick={()=>void action('refresh_english')}>{t.refresh}</button><p>{t.newAttempt}</p><details><summary>{t.missingIds}</summary>{data.coverage.missing_reviews.map(r=><p className="jev-id" key={r.review_id}>{r.review_id}<br/>{r.cause}</p>)}</details>{prepareConfirm&&<div role="alertdialog" aria-modal="true" aria-label={t.prepare}><p>{t.prepareConfirm}</p><p>{t.apifyCost}</p><button className="primary-button" disabled={busy} onClick={()=>void prepare()}>{t.confirm}</button><button className="secondary-button" disabled={busy} onClick={()=>setPrepareConfirm(false)}>{t.cancel}</button></div>}</section>:run.benchmark_status==='completed'&&data.comparison?<NegativeResults data={data}/>:<section className="card jev-card"><h2>{t.humanComplete}</h2><p>{t.immutable}</p><p>{t.bias}</p>{run.benchmark_status==='idle'?<button className="primary-button full-width" disabled={busy||!!marker()} onClick={()=>void action('start_benchmark')}>{t.benchmark}</button>:<><h3>{run.benchmark_status==='failed'?t.failed:t.benchmarking}</h3><p>{t.continue}</p>{run.benchmark_error&&<p role="alert">{run.benchmark_error}</p>}</>}</section>)}
  </>}<Link to="/plus/jev-benchmark">{t.back}</Link></div></>
}
export function NegativeAnnotation({data,user,busy,action}:{data:NegativeData;user:string;busy:boolean;action:Action}){const {language}=useI18n(),t=negativeMessages[language],run=data.run!,storage='negative-cursor:'+user+':'+run.id,[position,setPosition]=useState(()=>{try{return Number(localStorage.getItem(storage))||data.items.find(i=>!i.confirmed_at)?.position||1}catch{return 1}}),[drafts,setDrafts]=useState<Record<string,Partial<Record<GoldTheme,GoldChoice>>>>({}),[info,setInfo]=useState<GoldTheme|null>(null),[confirm,setConfirm]=useState<'finalize_human'|'exclude_review'|null>(null),index=Math.max(0,data.items.findIndex(i=>i.position===position)),item=data.items[index],choices=drafts[item.review_id]??item.choices,dirty=Object.keys(drafts).length>0
  const select=(n:number)=>{setPosition(n);setInfo(null);try{localStorage.setItem(storage,String(n))}catch{/* Server labels are authoritative. */}}
  async function save(empty=false){if(await action('confirm_review',{review_id:item.review_id,choices:empty?{}:choices})){setDrafts(old=>{const next={...old};delete next[item.review_id];return next});if(index<31)select(index+2)}}
  return <><section className="card jev-card"><h2>{t.annotationTitle}</h2><h3>{run.completed_reviews} / 32 {t.done}</h3><progress value={run.completed_reviews} max={32}/><p>{t.reminder}</p><p>{t.draftNote}</p><small role="status">{busy?t.saving:item.confirmed_at&&!drafts[item.review_id]?t.saved:''}</small></section><section className="card jev-card"><h3>{t.review} {index+1} / 32</h3><p className="gold-text" lang="en">{item.analysis_text}</p></section>
    {(['quality','service','atmosphere','price'] as const).map(axis=><details className="card jev-card gold-axis" key={axis} open={axis==='service'||undefined}><summary>{t[axis]}</summary>{(Object.keys(data.rubric) as GoldTheme[]).filter(k=>data.rubric[k].axis===axis).map(theme=><article className="jev-theme-detail" key={theme} data-negative-theme={theme}><div className="gold-theme-heading"><h4>{data.rubric[theme][language]}</h4><button className="gold-info" aria-label={'Info · '+data.rubric[theme][language]} onClick={()=>setInfo(info===theme?null:theme)}><Info size={18}/></button></div>{info===theme&&<p>{data.rubric[theme][language==='fr'?'definition_fr':'definition_vi']}</p>}<div className="gold-choices">{(['absent','positive','negative','both','uncertain'] as const).map(choice=><button key={choice} disabled={busy} aria-pressed={(choices[theme]??'absent')===choice} onClick={()=>setDrafts(old=>({...old,[item.review_id]:{...choices,[theme]:choice}}))}>{t[choice]}</button>)}</div></article>)}</details>)}
    <section className="card jev-card gold-actions"><button className="primary-button full-width" disabled={busy} onClick={()=>void save()}>{t.save}</button><button className="secondary-button full-width" disabled={busy} onClick={()=>void save(true)}>{t.noTheme}</button><div className="gold-navigation"><button className="secondary-button" disabled={busy||index===0} onClick={()=>select(index)}>{t.previous}</button><button className="secondary-button" disabled={busy||index===31} onClick={()=>select(index+2)}>{t.next}</button></div><button className="text-button" disabled={busy} onClick={()=>setConfirm('exclude_review')}>{t.translation}</button>{run.completed_reviews===32&&<button className="primary-button full-width" disabled={busy||dirty} onClick={()=>setConfirm('finalize_human')}>{t.finalize}</button>}{confirm&&<div role="alertdialog" aria-modal="true" aria-label={confirm==='finalize_human'?t.finalize:t.translation}><p>{confirm==='finalize_human'?t.finalizeConfirm:t.translationConfirm}</p><button className="primary-button" disabled={busy} onClick={()=>void(async()=>{if(await action(confirm,confirm==='finalize_human'?{confirm:true}:{review_id:item.review_id,confirm:true})){setConfirm(null);setDrafts({})}})()}>{t.confirm}</button><button className="secondary-button" disabled={busy} onClick={()=>setConfirm(null)}>{t.cancel}</button></div>}</section>
  </>
}
export function NegativeResults({data}:{data:NegativeData}){const {language}=useI18n(),t=negativeMessages[language],c=data.comparison!,n=(v:number|null,d=3)=>v===null?t.insufficient:v.toLocaleString(language==='fr'?'fr-FR':'vi-VN',{maximumFractionDigits:d}),percent=(v:number|null)=>v===null?t.insufficient:n(v*100,1)+' %',metrics=(m:{precision:number|null;recall:number|null;f1:number|null;support:number})=><dl className="jev-pairs"><dt>{t.support}</dt><dd>{m.support}</dd><dt>{t.precision}</dt><dd>{n(m.precision)}</dd><dt>{t.recall}</dt><dd>{n(m.recall)}</dd><dt>F1</dt><dd>{n(m.f1)}</dd></dl>
  const priorityTheme=(theme:GoldTheme)=><article className="jev-theme-detail" key={theme}><h4>{data.rubric[theme][language]}</h4><p>{t.support} {c.v9.themes[theme].negative.support}</p>{(['v9','v11'] as const).map(v=><p key={v}>{v.toUpperCase()} · TP {c[v].themes[theme].negative.tp} · FP {c[v].themes[theme].negative.fp} · FN {c[v].themes[theme].negative.fn} · F1 {n(c[v].themes[theme].negative.f1)}</p>)}</article>
  const errors=(version:'v9'|'v11',kind:'missed_negative'|'false_positive_negative')=>c[version].errors.filter(e=>e.kind===kind).map(e=><article key={e.review_id+e.theme_key} className="jev-theme-detail"><h4>{data.rubric[e.theme_key][language]}</h4><p>{t.human} : {t[e.human]} · {version.toUpperCase()} : {t[e.predicted]}</p><details><summary>{t.englishText}</summary><p className="gold-text" lang="en">{data.error_texts?.[e.review_id]}</p></details></article>)
  return <div className="jev-results"><section className="card jev-card"><h2>{t.result}</h2><p>{c.sample_reviews} {t.review.toLowerCase()} · {c.strata.low} 1–3★ · {c.strata.mixed} 4★ · {c.strata.control} 5★</p><p>{t.bias}</p><p>{t.noSwitch}</p><p>{t.coverage} : {c.coverage.common_assessed} / 32</p>{!c.coverage.complete&&<p role="alert">{t.partial}</p>}</section><section className="card jev-card"><h3>{t.criticism}</h3>{(['v9','v11'] as const).map(version=><div key={version}><h4>{version.toUpperCase()}</h4>{metrics(c[version].negative)}</div>)}<p>{t.delta} : {n(c.bootstrap.negative.delta)}</p><p>{t.ci} : {c.bootstrap.negative.ci_95_low===null?t.inconclusive:`[${n(c.bootstrap.negative.ci_95_low)} ; ${n(c.bootstrap.negative.ci_95_high)}]`}</p><p>{t.unsupported}</p></section>
    <section className="card jev-card"><h3>{t.positiveResult}</h3>{(['v9','v11'] as const).map(v=><div key={v}><h4>{v.toUpperCase()}</h4>{metrics(c[v].positive)}<p>{t.micro} : {n(c[v].micro_f1)}</p><p>{t.macro} : {n(c[v].macro_f1)}</p><p>{t.exact} : {percent(c[v].exact_choice_agreement)}</p></div>)}<p>{t.delta} · {t.micro} : {n(c.bootstrap.overall.delta)}</p><p>{t.ci} : {c.bootstrap.overall.ci_95_low===null?t.inconclusive:`[${n(c.bootstrap.overall.ci_95_low)} ; ${n(c.bootstrap.overall.ci_95_high)}]`}</p></section>
    {(['quality','service','atmosphere','price'] as const).map(axis=><section className="card jev-card" key={axis}><h3>{t[axis]}</h3><p>{t.negative} · {t.support} : {c.v9.axes[axis].negative.support}</p><p>V9 F1 {n(c.v9.axes[axis].negative.f1)} · V11 F1 {n(c.v11.axes[axis].negative.f1)}</p><p>{t.positive} · {t.support} : {c.v9.axes[axis].positive.support}</p><p>V9 F1 {n(c.v9.axes[axis].positive.f1)} · V11 F1 {n(c.v11.axes[axis].positive.f1)}</p><p>V9 FP {c.v9.axes[axis].negative.fp} / FN {c.v9.axes[axis].negative.fn} · V11 FP {c.v11.axes[axis].negative.fp} / FN {c.v11.axes[axis].negative.fn}</p></section>)}
    <section className="card jev-card"><h3>{t.priority}</h3>{c.priority_themes.map(priorityTheme)}</section><details className="card jev-card"><summary>{t.allThemes}</summary>{Object.keys(data.rubric).map(key=>{const theme=key as GoldTheme;return <article className="jev-theme-detail" key={theme}><h4>{data.rubric[theme][language]}</h4><p>{t.negative} · {t.support} {c.v9.themes[theme].negative.support}</p>{(['v9','v11'] as const).map(v=><p key={v}>{v.toUpperCase()} · TP {c[v].themes[theme].negative.tp} · FP {c[v].themes[theme].negative.fp} · FN {c[v].themes[theme].negative.fn} · F1 {n(c[v].themes[theme].negative.f1)}</p>)}</article>})}</details>
    {(['missed_negative','false_positive_negative'] as const).map(kind=><details className="card jev-card" key={kind}><summary>{kind==='missed_negative'?t.missed:t.falsePositive}</summary>{(['v9','v11'] as const).map(v=><div key={v}><h3>{v.toUpperCase()} · {c[v].errors.filter(e=>e.kind===kind).length}</h3>{errors(v,kind)}</div>)}</details>)}
    <section className="card jev-card"><h3>{t.usage}</h3>{(['v9','v11'] as const).map(v=><div key={v}><h4>{v.toUpperCase()}</h4><p>{c.usage[v].served_models.join(', ')}</p><p>Tokens {c.usage[v].input_tokens} / {c.usage[v].output_tokens}</p><p>USD {n(c.usage[v].estimated_cost_usd,6)} · {c.usage[v].requests} requests · {c.usage[v].retries} retries</p><p>{t.requestTime} : {n(c.usage[v].request_elapsed_sum_ms/1000)} s · p50 {n(c.usage[v].latency.p50_ms)} ms · p95 {n(c.usage[v].latency.p95_ms)} ms</p>{!c.usage[v].usage_complete&&<p role="alert">{t.partialUsage}</p>}</div>)}<p>{t.totalTime} : {n(c.end_to_end_elapsed_ms===null?null:c.end_to_end_elapsed_ms/1000)} s</p>{c.model_version_confounded&&<p role="alert">{t.modelChanged}</p>}</section><details className="card jev-card"><summary>{t.google}</summary><p>{t.googleNote}</p>{(['food','service','atmosphere'] as const).map(axis=><p key={axis}>{axis} · {t.human} {c.google_cross_rating.human.axes[axis].confirmed_negative_count} · V9 {c.google_cross_rating.v9.axes[axis].confirmed_negative_count} · V11 {c.google_cross_rating.v11.axes[axis].confirmed_negative_count}</p>)}</details>
  </div>
}
