import {useState,useRef,useEffect} from 'react'
import {Link,useNavigate,useSearchParams} from 'react-router-dom'
import {useQuery,useQueryClient} from '@tanstack/react-query'
import {Info} from 'lucide-react'
import {useApp} from '../app/AppContext'
import {useI18n} from '../i18n'
import {useJevAccess} from '../lib/use-jev-access'
import {PageHeader} from '../components/ui/PageHeader'
import {representativeMessages} from '../i18n/representative'
import {representativeApi,type RepresentativeData} from '../lib/representative-human'
import type {GoldChoice,GoldTheme} from '../../supabase/functions/_shared/gold-taxonomy'
import './JevBenchmarkPage.css'
import './GoldSetPage.css'
type Action=(kind:string,payload?:Record<string,unknown>)=>Promise<boolean>
export function RepresentativeEntry(){const {currentUser}=useApp(),{language}=useI18n(),t=representativeMessages[language],navigate=useNavigate(),lock=useRef(false),[busy,setBusy]=useState(false),[error,setError]=useState(false)
  const q=useQuery({queryKey:['representative-entry',currentUser.id],queryFn:()=>representativeApi(undefined,undefined,{},true),retry:false,staleTime:0})
  async function start(){if(lock.current||q.isPending||q.isError)return;if(q.data?.test){navigate('/plus/representative-test?id='+q.data.test.id);return}lock.current=true;setBusy(true);try{const data=await representativeApi(undefined,'create');if(!data.test)throw new Error('HOLDOUT_CREATE_FAILED');navigate('/plus/representative-test?id='+data.test.id)}catch{setError(true);await q.refetch()}finally{lock.current=false;setBusy(false)}}
  return <section className="card jev-card"><h3>{t.title}</h3><p>{t.intro}</p>{q.data&&<><h4>{t.reference}</h4><p>{t.assisted}</p><p>{q.data.reference.human_label_count} {t.provenance} · {q.data.reference.label_count-q.data.reference.human_label_count} {t.retained}</p><p>{t.pool} : {q.data.pool_stats.eligible_holdout_reviews}</p></>}<button className="primary-button full-width" disabled={busy||q.isPending||q.isError} onClick={()=>void start()}>{busy?t.saving:q.data?.test?.status==='completed'?t.show:q.data?.test?t.resume:t.start}</button>{(error||q.isError)&&<p role="alert">{t.error}<button className="secondary-button" onClick={()=>void q.refetch()}>{t.check}</button></p>}</section>
}
export function RepresentativeHumanPage(){const {currentUser,demoMode}=useApp(),{language}=useI18n(),t=representativeMessages[language],access=useJevAccess(currentUser.id,demoMode),[params,setParams]=useSearchParams(),client=useQueryClient(),lock=useRef(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),id=params.get('id')??undefined,key=['representative',currentUser.id,id]
  const q=useQuery({queryKey:key,enabled:access.data===true,queryFn:()=>representativeApi(id),retry:false,staleTime:0})
  useEffect(()=>{const resume=()=>{if(!document.hidden)void client.invalidateQueries({queryKey:['representative',currentUser.id]})};window.addEventListener('pageshow',resume);document.addEventListener('visibilitychange',resume);return()=>{window.removeEventListener('pageshow',resume);document.removeEventListener('visibilitychange',resume)}},[client,currentUser.id])
  async function action(kind:string,payload:Record<string,unknown>={}){if(lock.current||q.isPending||q.isError)return false;lock.current=true;setBusy(true);setError('');try{const data=await representativeApi(q.data?.test?.id,kind,{revision:q.data?.test?.revision,...payload});client.setQueryData(key,data);if(data.test&&!id){client.setQueryData(['representative',currentUser.id,data.test.id],data);setParams({id:data.test.id},{replace:true})}return true}catch(e){setError(e instanceof Error?e.message:'HOLDOUT_CONNECTION_ERROR');await q.refetch();return false}finally{lock.current=false;setBusy(false)}}
  return <><PageHeader title={t.title} back/><div className="jev-page gold-page"><h2>{t.title}</h2>{access.isPending||q.isPending&&access.data===true?<p>{t.loading}</p>:access.data!==true?<p>{t.denied}</p>:<>{(q.isError||error)&&<section className="card jev-card" role="alert"><p>{error==='HOLDOUT_REVISION_CHANGED'?t.conflict:t.error}</p><button className="secondary-button" disabled={busy} onClick={()=>void q.refetch()}>{t.check}</button></section>}{q.data?.test?q.data.test.status==='completed'?<RepresentativeResults data={q.data}/>:<RepresentativeAnnotation data={q.data} user={currentUser.id??''} busy={busy||q.isError} action={action}/>:!q.isError&&<section className="card jev-card"><p>{t.intro}</p><button className="primary-button full-width" disabled={busy||q.isPending} onClick={()=>void action('create')}>{t.start}</button></section>}</>}<Link to="/plus/gold-check?id=146615ca-d3cd-4914-8613-4e6e3d6219f7">{t.back}</Link></div></>
}
export function RepresentativeAnnotation({data,user,busy,action}:{data:RepresentativeData;user:string;busy:boolean;action:Action}){
  const {language}=useI18n(),t=representativeMessages[language],a=data.test!,storage='representative-review:'+user+':'+a.id,[selected,setSelected]=useState(()=>{try{return Number(localStorage.getItem(storage))||data.items.find(i=>!i.confirmed_at)?.position||1}catch{return 1}}),[drafts,setDrafts]=useState<Record<string,Partial<Record<GoldTheme,GoldChoice>>>>({}),[info,setInfo]=useState<GoldTheme|null>(null),[confirmation,setConfirmation]=useState<'finalize'|'translation'|null>(null)
  const index=Math.max(0,data.items.findIndex(i=>i.position===selected)),item=data.items[index],choices=drafts[item.review_id]??item.choices,dirty=Object.keys(drafts).length>0
  const select=(position:number)=>{setSelected(position);setInfo(null);try{localStorage.setItem(storage,String(position))}catch{/* Server remains authoritative. */}}
  async function save(empty=false){const accepted=await action('confirm_review',{review_id:item.review_id,choices:empty?{}:choices});if(accepted){setDrafts(old=>{const next={...old};delete next[item.review_id];return next});if(index<11)select(index+2)}}
  return <><section className="card jev-card"><h3>{a.completed_reviews} / 12 {t.done}</h3><progress max={12} value={a.completed_reviews}/><p>{t.reminder}</p><p>{t.draftNote}</p><small role="status">{busy?t.saving:item.confirmed_at&&!drafts[item.review_id]?t.saved:''}</small></section><section className="card jev-card"><h3>{t.review} {index+1} / 12</h3><p className="gold-text" lang="en">{item.analysis_text}</p></section>
    {(['quality','service','atmosphere','price'] as const).map(axis=><details className="card jev-card gold-axis" key={axis} open={axis==='service'||undefined}><summary>{t[axis]}</summary>{(Object.keys(data.taxonomy) as GoldTheme[]).filter(k=>data.taxonomy[k].axis===axis).map(theme=>{const definition=data.taxonomy[theme];return <article className="jev-theme-detail" key={theme} data-holdout-theme={theme}><div className="gold-theme-heading"><h4>{definition[language]}</h4><button className="gold-info" aria-label={'Info · '+definition[language]} onClick={()=>setInfo(info===theme?null:theme)}><Info size={18}/></button></div>{info===theme&&<p>{definition[language==='fr'?'definition_fr':'definition_vi']}</p>}<div className="gold-choices">{(['absent','positive','negative','both','uncertain'] as const).map(choice=><button key={choice} disabled={busy} aria-pressed={(choices[theme]??'absent')===choice} onClick={()=>setDrafts(old=>({...old,[item.review_id]:{...choices,[theme]:choice}}))}>{t[choice]}</button>)}</div></article>})}</details>)}
    <section className="card jev-card gold-actions"><button className="primary-button full-width" disabled={busy} onClick={()=>void save()}>{t.save}</button><button className="secondary-button full-width" disabled={busy} onClick={()=>void save(true)}>{t.noTheme}</button><div className="gold-navigation"><button className="secondary-button" disabled={busy||index===0} onClick={()=>select(index)}>{t.previous}</button><button className="secondary-button" disabled={busy||index===11} onClick={()=>select(index+2)}>{t.next}</button></div><button className="text-button" disabled={busy} onClick={()=>setConfirmation('translation')}>{t.translation}</button>{a.completed_reviews===12&&<button className="primary-button full-width" disabled={busy||dirty} onClick={()=>setConfirmation('finalize')}>{t.finalize}</button>}
      {confirmation&&<div role="alertdialog" aria-modal="true" aria-label={confirmation==='finalize'?t.finalize:t.translation}><p>{confirmation==='finalize'?t.confirmation:t.translationConfirm}</p><button className="primary-button" disabled={busy} onClick={()=>void (async()=>{if(await action(confirmation==='finalize'?'finalize':'exclude_review',confirmation==='finalize'?{confirm:true}:{review_id:item.review_id})){setConfirmation(null);setDrafts(old=>{const next={...old};delete next[item.review_id];return next})}})()}>{t.confirm}</button><button className="secondary-button" disabled={busy} onClick={()=>setConfirmation(null)}>{t.cancel}</button></div>}
    </section></>
}
export function RepresentativeResults({data}:{data:RepresentativeData}){const {language}=useI18n(),t=representativeMessages[language],c=data.comparison!,n=(v:number|null,d=3)=>v===null?'—':v.toLocaleString(language==='fr'?'fr-FR':'vi-VN',{minimumFractionDigits:d,maximumFractionDigits:d}),percent=(v:number|null)=>v===null?'—':n(v,1)+' %'
  const theme=(key:GoldTheme)=><article key={key} className="jev-theme-detail"><h4>{data.taxonomy[key][language]}</h4>{(['positive','negative'] as const).map(p=><div key={p}><strong>{t[p]}</strong><p>{t.support} : {c.sol.themes[key][p].support}</p>{(['sol','jev'] as const).map(model=><p key={model}>{model.toUpperCase()} · {t.precision} {n(c[model].themes[key][p].precision)} · {t.recall} {n(c[model].themes[key][p].recall)} · F1 {n(c[model].themes[key][p].f1)}</p>)}{c.sol.themes[key][p].support<3&&<small>{t.low}</small>}</div>)}</article>
  return <div className="jev-results"><section className="card jev-card"><h3>{t.result}</h3><p>{c.review_count} {t.review.toLowerCase()}</p><p>{t.immutable}</p><p>{t.note}</p><span className="jev-tag">{t[c.verdict]}</span></section><section className="card jev-card"><div className="jev-dual">{(['sol','jev'] as const).map(model=><div key={model}><h3>{model.toUpperCase()} V7</h3><p>{t.micro} : <strong>{n(c[model].micro_f1_human)}</strong></p><p>{t.macro} : <strong>{n(c[model].macro_f1_human)}</strong></p><p>{t.precision} : {n(c[model].precision)}</p><p>{t.recall} : {n(c[model].recall)}</p></div>)}</div><dl className="jev-pairs"><dt>{t.delta}</dt><dd>{n(c.bootstrap.delta)}</dd><dt>{t.ci}</dt><dd>[{n(c.bootstrap.ci_95_low)} ; {n(c.bootstrap.ci_95_high)}]</dd></dl></section>
    {(['quality','service','atmosphere','price'] as const).map(axis=><section className="card jev-card" key={axis}><h3>{t[axis]}</h3><p>Micro F1 · Sol {n(c.sol.axes[axis].f1)} · Jev {n(c.jev.axes[axis].f1)}</p></section>)}
    {(['friendly_staff','attentiveness','professionalism','wait_time','atmosphere','coordination','communication'] as GoldTheme[]).some(k=>c.sol.themes[k].positive.support+c.sol.themes[k].negative.support>0)&&<section className="card jev-card">{(['friendly_staff','attentiveness','professionalism','wait_time','atmosphere','coordination','communication'] as GoldTheme[]).filter(k=>c.sol.themes[k].positive.support+c.sol.themes[k].negative.support>0).map(theme)}</section>}<details className="card jev-card jev-theme-list"><summary>{t.allThemes}</summary>{(Object.keys(data.taxonomy) as GoldTheme[]).map(theme)}</details>
    <section className="card jev-card"><h3>{t.difficult}</h3><p>{c.previous_difficult_test.comparable_labels} {t.comparable}</p><p>Jev : {percent(c.previous_difficult_test.jev_agreement_percent)} · Sol : {percent(c.previous_difficult_test.sol_agreement_percent)}</p><p>{t.difficultNote}</p></section><section className="card jev-card"><h3>{t.exact}</h3><p>Sol : {percent(c.sol.exact_choice_agreement_with_human===null?null:c.sol.exact_choice_agreement_with_human*100)} · Jev : {percent(c.jev.exact_choice_agreement_with_human===null?null:c.jev.exact_choice_agreement_with_human*100)}</p></section>
    <details className="card jev-card jev-technical"><summary>{t.technical}</summary><p>{data.test!.id}</p><p>{c.source_generation_id}</p><p>{c.jev_benchmark_id}</p><p>Bootstrap : {c.bootstrap.valid_resamples} / 2000</p><p>{data.reference.name}</p><p>{t.assisted}</p><p>{c.served_models.join(', ')}</p></details></div>
}
