import {render,screen,fireEvent,cleanup,waitFor} from '@testing-library/react'
import {MemoryRouter,Routes,Route} from 'react-router-dom'
import {QueryClient,QueryClientProvider} from '@tanstack/react-query'
import {afterEach,beforeEach,it,expect,vi} from 'vitest'
import {webcrypto} from 'node:crypto'
import {I18nProvider} from '../i18n'
import {RepresentativeAnnotation,RepresentativeEntry,RepresentativeHumanPage} from './RepresentativeHumanPage'
import {syntheticRepresentative,fakeRepresentativeId} from '../../tests/fixtures/representative'
import {representativeProjection} from '../../supabase/functions/_shared/representative-api'
import {normalizeGoldLabels,type GoldLabel} from '../../supabase/functions/_shared/gold-core'
import {scoreRepresentative} from '../../supabase/functions/_shared/representative-score'
const api=vi.hoisted(()=>vi.fn());vi.mock('../lib/representative-human',()=>({representativeApi:api}));vi.mock('../app/AppContext',()=>({useApp:()=>({currentUser:{id:'human'},demoMode:false,notifications:[]})}));vi.mock('../lib/use-jev-access',()=>({useJevAccess:()=>({data:true,isPending:false})}))
beforeEach(()=>vi.stubGlobal('crypto',webcrypto));afterEach(()=>{cleanup();localStorage.clear();vi.unstubAllGlobals();api.mockReset()})
function mount(content=<RepresentativeHumanPage/>,language:'fr'|'vi'='fr'){return render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false,gcTime:0}}})}><MemoryRouter initialEntries={['/plus/representative-test?id='+fakeRepresentativeId]}><I18nProvider language={language}>{content}</I18nProvider></MemoryRouter></QueryClientProvider>)}
it('shows English only, 25 frozen themes, absent defaults and sparse choices are saved solely after explicit validation',async()=>{const h=await syntheticRepresentative(),data=representativeProjection(h.context,h.test,h.items,[],true,h.selection.stats),action=vi.fn(async()=>true),view=mount(<RepresentativeAnnotation data={data} user="human" busy={false} action={action}/>);expect(view.container.querySelectorAll('[data-holdout-theme]')).toHaveLength(25);expect(view.container.querySelectorAll('[aria-pressed=true]')).toHaveLength(25);expect(screen.queryByText(/Sol|Jev|Gold|rating|original_text|probabilities/)).not.toBeInTheDocument();fireEvent.click(view.container.querySelector('[data-holdout-theme=attentiveness] button[aria-pressed]:last-child')!);expect(action).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Valider cet avis'}));expect(action).toHaveBeenCalledWith('confirm_review',{review_id:h.items[0].review_id,choices:{attentiveness:'uncertain'}})})
it('validated review autosaves and reopening resumes server progress; foreground fetches GET only',async()=>{const h=await syntheticRepresentative(),labels:GoldLabel[]=[];api.mockImplementation(async(_id,action,payload)=>{if(action==='confirm_review'){labels.push(...Object.entries(normalizeGoldLabels(payload.choices)).map(([theme_key,choice])=>({review_id:payload.review_id,theme_key,choice})) as GoldLabel[]);h.items.find(i=>i.review_id===payload.review_id)!.confirmed_at='2026-10-07T00:00:00Z';h.test.revision++}return representativeProjection(h.context,h.test,h.items,labels,true,h.selection.stats)});const view=mount();await screen.findByText('Avis 1 / 12');expect(api.mock.calls.every(c=>!c[1])).toBe(true);fireEvent.click(screen.getByRole('button',{name:'Aucun thème explicite'}));await screen.findByText('Avis 2 / 12');view.unmount();mount();await screen.findByText('Avis 2 / 12');expect(screen.getByText('1 / 12 terminés')).toBeVisible();fireEvent(window,new Event('pageshow'));await waitFor(()=>expect(api.mock.calls.length).toBeGreaterThan(2));expect(api.mock.calls.filter(c=>c[1]==='confirm_review')).toHaveLength(1)})
it('manual start double tap creates one test and completed reference is transparently assisted',async()=>{const h=await syntheticRepresentative();api.mockResolvedValueOnce(representativeProjection(h.context,null,[],[],false,h.selection.stats)).mockImplementation(async()=>{await new Promise(resolve=>setTimeout(resolve,10));return representativeProjection(h.context,h.test,h.items,[],true,h.selection.stats)});render(<QueryClientProvider client={new QueryClient()}><MemoryRouter initialEntries={['/entry']}><I18nProvider language="fr"><Routes><Route path="/entry" element={<RepresentativeEntry/>}/><Route path="/plus/representative-test" element={<p>opened</p>}/></Routes></I18nProvider></MemoryRouter></QueryClientProvider>);const button=await screen.findByRole('button',{name:'Commencer le test représentatif'});await waitFor(()=>expect(button).toBeEnabled());expect(api.mock.calls.some(c=>c[1]==='create')).toBe(false);expect(screen.getByText(/une partie des labels/)).toBeVisible();fireEvent.click(button);fireEvent.click(button);await screen.findByText('opened');expect(api.mock.calls.filter(c=>c[1]==='create')).toHaveLength(1)})
it('finalization requires12 confirmed reviews and confirmation, only then reveals model scores and removes editing',async()=>{const h=await syntheticRepresentative();h.items.forEach(i=>i.confirmed_at='2026-10-07T00:00:00Z');api.mockImplementation(async(_id,action)=>{if(action==='finalize'){h.test.status='completed';h.test.comparison=await scoreRepresentative(h.test.id,h.source,h.benchmark,h.items,h.labels,h.context.previous)}return representativeProjection(h.context,h.test,h.items,h.labels,true,h.selection.stats)});mount();await screen.findByText('12 / 12 terminés');expect(screen.queryByText('SOL V7')).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Finaliser le test représentatif'}));expect(api.mock.calls.some(c=>c[1]==='finalize')).toBe(false);fireEvent.click(screen.getByRole('button',{name:/^Confirmer$/}));await screen.findByText('Résultat du test représentatif');expect(screen.getByText('SOL V7')).toBeVisible();expect(screen.queryByRole('button',{name:'Valider cet avis'})).not.toBeInTheDocument()})
it('VI uses unchanged taxonomy definitions and distinct representative text',async()=>{const h=await syntheticRepresentative(),action=vi.fn(async()=>true);mount(<RepresentativeAnnotation data={representativeProjection(h.context,h.test,h.items,[],true,h.selection.stats)} user="human" busy={false} action={action}/>,'vi');fireEvent.click(screen.getByRole('button',{name:'Info · Sự quan tâm'}));expect(screen.getByText(/Quan tâm cụ thể đến nhu cầu/)).toBeVisible();expect(screen.getByText('Các chủ đề không được chọn sẽ được xem là không xuất hiện.')).toBeVisible();fireEvent.click(screen.getByRole('button',{name:'Không có chủ đề rõ ràng'}));expect(action).toHaveBeenCalledWith('confirm_review',{review_id:h.items[0].review_id,choices:{}})})
