import { Bell, Building2, ChevronRight, CreditCard, Database, LogOut, Shield, Sparkles, User } from 'lucide-react'
import { useState } from 'react'
import { useApp } from '../app/AppContext'
import { PageHeader } from '../components/ui/PageHeader'
import { relativeTime } from '../lib/format'

export function SettingsPage(){const {currentUser,plan,establishments,aiUsage,demoMode,pushToast}=useApp();const [inApp,setInApp]=useState(true);const [pushState,setPushState]=useState<NotificationPermission>(typeof Notification==='undefined'?'denied':Notification.permission);const lastSync=new Date(Math.max(...establishments.map((item)=>new Date(item.lastSyncedAt).getTime()))).toISOString();const requestPush=async()=>{if(!('Notification'in window)){pushToast('Notifications push non prises en charge');return}const value=await Notification.requestPermission();setPushState(value);if(value==='granted')pushToast('Notifications push activées')};return <><PageHeader title="Plus"/>
  <section className="profile-card card"><div className="profile-avatar">LN</div><div><h2>{currentUser.name}</h2><p>{currentUser.email}</p><span>HOME France</span></div></section>
  {demoMode&&<div className="demo-banner"><Sparkles/><div><strong>Mode démonstration</strong><span>Données locales, aucun service externe requis.</span></div></div>}
  <SettingsSection title="Compte"><SettingLink icon={<User/>} title="Profil" detail="Nom et adresse email"/><SettingLink icon={<Building2/>} title="Organisation" detail="HOME France · Propriétaire"/><SettingLink icon={<LogOut/>} title="Déconnexion" detail="Fermer la session"/></SettingsSection>
  <SettingsSection title="Notifications"><div className="setting-row"><div className="setting-icon"><Bell/></div><div><strong>Notifications in-app</strong><span>Alertes visibles dans l’application</span></div><Switch value={inApp} onChange={()=>setInApp(!inApp)}/></div><button className="setting-row clickable" onClick={requestPush}><div className="setting-icon"><Bell/></div><div><strong>Notifications push</strong><span>État : {pushState==='granted'?'autorisées':pushState==='denied'?'refusées':'à activer'}</span></div><ChevronRight/></button></SettingsSection>
  <SettingsSection title="Surveillance"><div className="settings-info card"><span>Fréquence du plan</span><strong>Toutes les {plan.syncIntervalMinutes} minutes</strong><span>Dernière synchronisation globale</span><strong>{relativeTime(lastSync)}</strong></div></SettingsSection>
  <SettingsSection title="Abonnement"><div className="subscription-card card"><div><span>Plan actuel</span><strong>Professionnel</strong><em>Statut actif</em></div><CreditCard/><div className="quota"><span>Établissements <b>{establishments.length} / {plan.maxEstablishments}</b></span><i><b style={{width:`${establishments.length/plan.maxEstablishments*100}%`}}/></i><span>Réponses IA <b>{aiUsage} / {plan.maxAiResponsesMonth}</b></span><i><b style={{width:`${aiUsage/plan.maxAiResponsesMonth*100}%`}}/></i></div><button className="secondary-button full-width" onClick={()=>pushToast('Gestion du plan simulée en mode démo')}>Changer de plan</button></div></SettingsSection>
  <SettingsSection title="Données & confidentialité"><SettingLink icon={<Shield/>} title="Confidentialité" detail="Politique et gestion des données"/><SettingLink icon={<Database/>} title="Supprimer mon compte" detail="Demande avec confirmation forte" danger/></SettingsSection>
  <p className="version">HOME Reviews v1.0 · Données de démonstration</p>
  </>}

function SettingsSection({title,children}:{title:string;children:React.ReactNode}){return <section className="settings-section"><h2>{title}</h2><div className="settings-group card">{children}</div></section>}
function SettingLink({icon,title,detail,danger=false}:{icon:React.ReactNode;title:string;detail:string;danger?:boolean}){return <button className={`setting-row clickable${danger?' danger':''}`}><div className="setting-icon">{icon}</div><div><strong>{title}</strong><span>{detail}</span></div><ChevronRight/></button>}
function Switch({value,onChange}:{value:boolean;onChange:()=>void}){return <button role="switch" aria-checked={value} className={`switch ${value?'on':''}`} onClick={onChange}><span/></button>}
