import {requireUser,assertMembership} from '../_shared/auth.ts'
import {pilotHandler,type PilotJob,type PilotAuthorization} from '../_shared/jev-pilot-api.ts'
import {PILOT_ESTABLISHMENT,resolvePilotReviews,auditPilotCache,pilotStatistics,pilotSourceHash,normalizePilotLegacy,type PilotRawReview,type PilotLegacy,type PilotSnapshot,type PilotRates} from '../_shared/jev-pilot-core.ts'
import {ECONOMY_CONFIG} from '../_shared/jev-economy-config.ts'
import {canonicalJson} from '../_shared/jev-exploratory-core.ts'
import {negativeHash} from '../_shared/negative-validation-core.ts'
import type {EconomyCache} from '../_shared/jev-economy-cache.ts'
import type {EnglishTranslationOverride} from '../_shared/analysis-text.ts'
Deno.serve(pilotHandler(async request=>{const ctx=await requireUser(request),language=new URL(request.url).searchParams.get('language')??'vi';if(!['fr','vi'].includes(language))throw new Error('PILOT_LANGUAGE_INVALID');const {data:est,error}=await ctx.admin.from('establishments').select('id,name,organization_id,total_reviews').eq('id',PILOT_ESTABLISHMENT).single();if(error||!est)throw new Error('FORBIDDEN');await assertMembership(ctx.client,ctx.user.id,est.organization_id,['owner','admin','manager']);
 const read=async(table:string,fields:string,column:string,value:string)=>{const rows:Record<string,unknown>[]=[];for(let n=0;;n+=500){const {data,error}=await ctx.admin.from(table).select(fields).eq(column,value).order('id').range(n,n+499);if(error)throw new Error('PILOT_READ_FAILED');rows.push(...data as unknown as Record<string,unknown>[]);if(data.length<500)break}return rows},snapshot=async()=>{const {data,error}=await ctx.admin.from('analysis_jev_pilot_snapshots').select('*').eq('organization_id',est.organization_id).eq('establishment_id',est.id).order('created_at',{ascending:false}).limit(1).maybeSingle();if(error)throw new Error('PILOT_READ_FAILED');return data as PilotSnapshot|null},cache=async()=>await read('analysis_jev_review_cache','*','establishment_id',est.id) as unknown as (EconomyCache&{theme_results?:unknown;source_kind?:string})[],rpc=async(name:string,args:Record<string,unknown>)=>{const {data,error}=await ctx.admin.rpc(name,args);if(error)throw new Error(/PILOT_[A-Z_]+|FORBIDDEN/.exec(error.message)?.[0]??'PILOT_SAVE_FAILED');return data};
 return {language:language as 'fr'|'vi',snapshot,cache,configuration:async()=>{const {data,error}=await ctx.admin.from('analysis_jev_economy_configurations').select('config,config_sha256').eq('id',ECONOMY_CONFIG.id).single();if(error)throw new Error('PILOT_CONFIG_CHANGED');return data},prepare:async()=>{
 const raw=await rpc('read_economy_pilot_source',{p_user:ctx.user.id,p_est:est.id});const sourceReviews=raw.reviews as PilotRawReview[],reviews=await resolvePilotReviews(sourceReviews,raw.overrides as EnglishTranslationOverride[],est.organization_id,est.id,raw.captured_at),currentCache=raw.cache as Awaited<ReturnType<typeof cache>>,audit=await auditPilotCache(reviews,currentCache,est.organization_id,est.id),preview=pilotStatistics(reviews,audit,raw.establishment.total_reviews),legacy=normalizePilotLegacy(raw.legacy as PilotLegacy|null),source={google_total_reviews:raw.establishment.total_reviews,establishment_name:raw.establishment.name,reviews,legacy},config_sha256=await negativeHash(canonicalJson(ECONOMY_CONFIG));
 const own=currentCache.filter(c=>c.configuration_id===ECONOMY_CONFIG.id&&c.status==='completed'&&c.usage_complete&&c.input_tokens!==null&&c.output_tokens!==null),past=raw.narrative_usage as {input:number;output:number;rates:{sol_input:number;sol_output:number}}|null,rates: PilotRates={jev_input:raw.jev_rates?.jev_input??null,jev_output:raw.jev_rates?.jev_output??null,sol_input:past?.rates.sol_input??null,sol_output:past?.rates.sol_output??null,apify_import:null,english_translation:null,observed_jev_input_per_review:own.length?own.reduce((n,c)=>n+c.input_tokens!,0)/own.length:null,observed_jev_output_per_review:own.length?own.reduce((n,c)=>n+c.output_tokens!,0)/own.length:null,observed_sol_input:past?.input??null,observed_sol_output:past?.output??null,provenance:['Recorded Artisan completed full-configuration cache usage','Recorded Jev and aggregate Sol narrative rates/usage','Apify and translation tariff unavailable']};
 await rpc('create_economy_pilot_snapshot',{p_user:ctx.user.id,p_org:est.organization_id,p_est:est.id,p_source:source,p_source_sha:await pilotSourceHash(source),p_config_sha:config_sha256,p_rates:rates,p_preview:preview})},jobs:async()=>{const s=await snapshot();return s?await read('analysis_jev_pilot_jobs','*','snapshot_id',s.id) as unknown as PilotJob[]:[]},authorizations:async()=>{const s=await snapshot();return s?await read('analysis_jev_pilot_authorizations','*','snapshot_id',s.id) as unknown as PilotAuthorization[]:[]},progress:async()=>{const s=await snapshot();if(!s)return {total:0,completed:0,failed:0};const jobs=await read('analysis_jev_pilot_jobs','id,stage','snapshot_id',s.id),j=jobs.find(j=>j.stage==='jev');if(!j)return {total:0,completed:0,failed:0};const tasks=await read('analysis_jev_pilot_tasks','id,status','job_id',j.id as string);return {total:tasks.length,completed:tasks.filter(t=>t.status==='completed').length,failed:tasks.filter(t=>t.status==='failed').length}},start:async(stage,lang,input_sha,context)=>{const s=await snapshot();if(!s)throw new Error('PILOT_SNAPSHOT_REQUIRED');await rpc('start_economy_pilot_job',{p_user:ctx.user.id,p_snapshot:s.id,p_stage:stage,p_language:lang,p_input_sha:input_sha,p_context:context,p_confirm:true})}}
}))
