import type { ReactNode } from 'react'
import { useI18n } from '../i18n'
import { AXES, type Axis, type ConsultantReportData, type DiagnosticTopic } from '../../supabase/functions/_shared/consultant-contract'
import './ReputationReport.css'
import './ConsultantReportV5.css'
import { GoogleContextInfo } from './GoogleContextInfo'

const copy={fr:{overview:'Vue d’ensemble',quick:'Diagnostic rapide',analyzed:'Avis analysés',average:'Note moyenne de l’échantillon',notes:'notes Google détaillées',noRating:'Pas de sous-note Google',noData:'Sous-notes non disponibles',coverage:'Couverture',textCoverage:'des avis analysés abordent cet axe',appreciated:'Ce que les clients apprécient',watch:'Points de vigilance',none:'Aucun thème négatif n’atteint le seuil de récurrence.',noPositive:'Pas de thème positif documenté.',mentions:'mentions',note:'Les mentions désignent des avis qui abordent explicitement un thème, pas un nombre de clients satisfaits. Un avis peut mentionner plusieurs thèmes.',coverageNote:'La couverture indique la part de l’échantillon documentant cet axe, pas une certitude statistique.',takeaway:'À retenir',strengths:'Ce qui fonctionne très bien',limited:'Pas assez de données pour conclure',manager:'Priorité manager',conclusion:'Conclusion',recommendation:'Orientation',empty:'Aucun signal suffisamment documenté.',axes:{service:'Service',quality:'Qualité',price:'Prix',atmosphere:'Ambiance'},levels:{strong:'Couverture forte',medium:'Couverture moyenne',limited:'Couverture limitée'},statuses:{major_strength:'Point fort majeur',strength:'Point fort',watch:'À surveiller',priority:'Priorité',limited_data:'Données limitées',neutral:'Pas de signal majeur'}},
vi:{overview:'Tổng quan',quick:'Chẩn đoán nhanh',analyzed:'Đánh giá đã phân tích',average:'Điểm trung bình của mẫu',notes:'điểm chi tiết Google',noRating:'Google không có điểm riêng cho giá',noData:'Chưa có điểm chi tiết',coverage:'Độ bao phủ',textCoverage:'đánh giá được phân tích đề cập đến khía cạnh này',appreciated:'Điều khách hàng đánh giá cao',watch:'Điểm cần theo dõi',none:'Không có chủ đề tiêu cực đạt ngưỡng lặp lại.',noPositive:'Chưa có chủ đề tích cực được ghi nhận.',mentions:'lượt đề cập',note:'Lượt đề cập là số đánh giá nói rõ về một chủ đề, không phải số khách hàng hài lòng. Một đánh giá có thể đề cập nhiều chủ đề.',coverageNote:'Độ bao phủ thể hiện tỷ lệ đánh giá có dữ liệu về khía cạnh này, không phải mức độ chắc chắn thống kê.',takeaway:'Điểm cần ghi nhớ',strengths:'Điểm đang làm rất tốt',limited:'Chưa đủ dữ liệu để kết luận',manager:'Ưu tiên cho quản lý',conclusion:'Kết luận',recommendation:'Định hướng',empty:'Chưa có tín hiệu đủ rõ.',axes:{service:'Dịch vụ',quality:'Chất lượng',price:'Giá cả',atmosphere:'Không gian'},levels:{strong:'Độ bao phủ cao',medium:'Độ bao phủ trung bình',limited:'Độ bao phủ hạn chế'},statuses:{major_strength:'Điểm mạnh nổi bật',strength:'Điểm mạnh',watch:'Cần theo dõi',priority:'Ưu tiên cải thiện',limited_data:'Dữ liệu còn hạn chế',neutral:'Không có tín hiệu nổi bật'}}}
function Section({index,title,children}:{index:number;title:string;children:ReactNode}) {
  return <section className="weekly-section"><article className="card reputation-theme-card consultant-section-card"><header className="weekly-section-heading consultant-section-banner"><span className="eyebrow">{String(index).padStart(2,'0')}</span><h2>{title}</h2></header><div className="consultant-section-body">{children}</div></article></section>
}
export function ConsultantReportV5({report}:{report:ConsultantReportData}) {
  const {language}=useI18n(),m=copy[language]
  const diagnostics=report.axis_diagnostics,decision=report.decision_summary
  if(!diagnostics || !decision) return <p role="status">{m.empty}</p>
  const number=(n:number)=>n.toLocaleString(language==='fr'?'fr-FR':'vi-VN',{minimumFractionDigits:2,maximumFractionDigits:2})
  const topics=(items:DiagnosticTopic[],empty:string)=>items.length?<ul className="v5-topics">{items.map(t=><li key={t.key}><span>{t.label}</span><small>{t.mentions} {m.mentions}</small></li>)}</ul>:<p className="v5-muted">{empty}</p>
  const metric=(key:Axis,compact=false)=>{
    const d=diagnostics[key]
    return <>{d.subrating_average!==null?<><p className="v5-score">{number(d.subrating_average)} <span>/ 5</span></p><small>{d.subrating_count} {m.notes}</small></>:<p className="v5-muted">{key==='price'?m.noRating:m.noData}</p>}
      <p className="v5-coverage">{m.levels[d.coverage_level]} · <span style={{whiteSpace:'nowrap'}}>{Math.round(d.coverage_rate*100)} %</span></p>{key==='price'&&!compact&&<small>{Math.round(d.textual_coverage_rate*100)} % {m.textCoverage}</small>}
      <p><span className={`v5-status v5-${d.status}`}>{m.statuses[d.status]}</span></p></>
  }
  return <div className="consultant-report consultant-v5" lang={language}>
    <Section index={1} title={m.overview}><dl className="reputation-replies"><div><dt>{m.analyzed}</dt><dd>{report.total}</dd></div>{report.sample_average_rating!=null&&<div><dt>{m.average}</dt><dd>{number(report.sample_average_rating)} / 5</dd></div>}</dl></Section>
    <Section index={2} title={m.quick}><div className="v5-grid">{AXES.map(key=><div className="v5-quick-axis" key={key} data-axis={key}><h3>{m.axes[key]}</h3>{metric(key,true)}<p className="v5-signal">{diagnostics[key].recurring_negative[0]?.label??diagnostics[key].top_positive[0]?.label??m.empty}</p></div>)}</div><small>{m.coverageNote}</small></Section>
    {AXES.map((key,i)=><Section index={i+3} key={key} title={m.axes[key]}><div className="v5-axis" data-axis={key}>{metric(key)}<h3>{m.appreciated}</h3>{topics(diagnostics[key].top_positive,m.noPositive)}<h3>{m.watch}</h3>{topics(diagnostics[key].recurring_negative,m.none)}<p className="consultant-prose">{diagnostics[key].summary}</p><h3>{m.recommendation}</h3><p className="consultant-prose">{report.axes.find(a=>a.key===key)?.recommendation}</p>{report.version===6&&<GoogleContextInfo stats={report.structured_context_stats} axis={key} language={language}/>}</div></Section>)}
    <Section index={7} title={m.takeaway}><div className="v5-decisions"><div><h3>{m.strengths}</h3>{topics(decision.strengths,m.empty)}</div><div><h3>{m.statuses.watch}</h3>{topics(decision.watch,m.none)}</div><div><h3>{m.limited}</h3>{decision.limited_axes.length?<ul>{decision.limited_axes.map(key=><li key={key}>{m.axes[key]}</li>)}</ul>:<p>{m.empty}</p>}</div><div><h3>{m.manager}</h3><p>{decision.manager_summary}</p></div></div><small>{m.note}</small></Section>
    <Section index={8} title={m.conclusion}><p className="consultant-prose">{report.conclusion}</p></Section>
  </div>
}
