import {Info} from 'lucide-react'
import {useI18n} from '../i18n'
import {crossRatingMessages} from '../i18n/cross-rating'
import {RATING_CATEGORIES,type CrossRatingAnalysis} from '../../supabase/functions/_shared/cross-rating-analysis'
import {GOLD_TAXONOMY,type GoldTheme} from '../../supabase/functions/_shared/gold-taxonomy'
import './CrossRatingSection.css'
export function CrossRatingSection({analysis}:{analysis:CrossRatingAnalysis}){
  const {language}=useI18n(),t=crossRatingMessages[language],number=(n:number)=>n.toLocaleString(language==='fr'?'fr-FR':'vi-VN',{minimumFractionDigits:2,maximumFractionDigits:2})
  return <div className="v8-cross-rating"><details className="v8-cross-info"><summary><Info size={16}/>{t.info}</summary><p>{t.tooltip}</p></details><div className="v8-rating-grid">
    {RATING_CATEGORIES.map(category=>{const a=analysis.axes[category];return <article className="v8-rating-card" key={category} data-category={category}><h3>{t.categories[category]}</h3><small>{t.google}</small><p className="v5-score">{a.average_rating===null?t.none:<>{number(a.average_rating)} <span>/ 5</span></>}</p><p>{a.rating_count} {t.available}</p><p>{a.low_rating_count} {t.low}</p><dl className="v8-rating-counts"><dt>{t.confirmed}</dt><dd>{a.confirmed_negative_count}</dd><dt>{t.unexplained}</dt><dd>{a.low_score_unexplained_count}</dd><dt>{t.hidden}</dt><dd>{a.textual_issue_despite_high_score_count}</dd>{a.mixed_text_signal_count>0&&<><dt>{t.mixed}</dt><dd>{a.mixed_text_signal_count}</dd></>}</dl><details><summary>{t.distribution}</summary>{[5,4,3,2,1].map(score=><p key={score}>{score}★ : {a.distribution[String(score) as keyof typeof a.distribution]}</p>)}</details></article>})}
    <article className="v8-rating-card" data-category="price"><h3>{t.price}</h3><p>{t.noPrice}</p><small>{t.comments}</small><dl className="v8-rating-counts"><dt>{t.positiveMentions}</dt><dd>{analysis.price.positive_finding_count}</dd><dt>{t.negativeMentions}</dt><dd>{analysis.price.negative_finding_count}</dd></dl><p>{analysis.price.price_per_person_count} {t.priceContext}</p></article>
  </div>{analysis.overall_vs_category_counts.low_overall_high_categories>0&&<p className="v5-muted">{t.lowOverall} : {analysis.overall_vs_category_counts.low_overall_high_categories}</p>}
  <h3>{t.high}</h3>{analysis.high_signal_reviews.length?analysis.high_signal_reviews.slice(0,5).map(review=><article className="v8-high-signal" key={review.review_id} data-high-signal={review.review_id}><p className="v8-stars" aria-label={t.google+' '+review.overall_rating}>{review.overall_rating===null?'—':'★'.repeat(review.overall_rating)+'☆'.repeat(5-review.overall_rating)}</p>{review.overall_vs_category_flags.high_overall_low_category.length>0&&<p><span className="v8-rating-badge">{t.highOverall} · {review.overall_vs_category_flags.high_overall_low_category.map(k=>t.categories[k]).join(', ')}</span></p>}{review.overall_vs_category_flags.low_overall_high_categories&&<span className="v8-rating-badge">{t.lowOverall}</span>}
    {RATING_CATEGORIES.filter(k=>review.overall_vs_category_flags.high_overall_low_category.includes(k)||['confirmed_negative','low_score_unexplained','textual_issue_despite_high_score','mixed_text_signal'].includes(review.axes[k].status)||(review.overall_vs_category_flags.low_overall_high_categories&&review.axes[k].category_rating!==null)).map(k=>{const a=review.axes[k];return <div key={k}><strong>{t.google} · {t.categories[k]} : {a.category_rating===null?'—':a.category_rating+' / 5'}</strong><p><span className="v8-rating-badge">{t.statuses[a.status]}</span></p>{a.themes.length>0&&<><small>{t.comments}</small><ul>{a.themes.map(f=><li key={f.theme_key+f.sentiment}>{GOLD_TAXONOMY[f.theme_key as GoldTheme]?.[language]??f.theme_key} · {f.sentiment==='positive'?t.positiveLabel:t.negative}</li>)}</ul></>}</div>})}
    {review.analysis_text.trim()&&<blockquote lang="en">{review.analysis_text}</blockquote>}
  </article>):<p className="v5-muted">{t.empty}</p>}</div>
}
