import {afterEach,it,expect} from 'vitest'
import {cleanup,render,screen} from '@testing-library/react'
import {I18nProvider} from '../i18n'
import {ConsultantReport} from './ConsultantReport'
import {syntheticV8} from '../../tests/fixtures/cross-rating-v8'
import {shabuReport} from '../../tests/fixtures/consultant-v5'
import {mapHistoricalReport,type HistoricalReportRow} from '../lib/historical-report'
afterEach(cleanup)
it.each(['fr','vi'] as const)('V8 shows separate Google/text sources, four cards, descriptive Price, explicit anomalies and no inferred Service cause (%s)',language=>{const report=syntheticV8(language),before=JSON.stringify(report),{container}=render(<I18nProvider language={language}><ConsultantReport report={report}/></I18nProvider>);expect(screen.getByRole('heading',{name:language==='fr'?'Lecture croisée des notes':'Đối chiếu điểm đánh giá'})).toBeVisible();expect(container.querySelectorAll('.v8-rating-card')).toHaveLength(4);expect(container.querySelectorAll('.v8-high-signal').length).toBeLessThanOrEqual(5);const price=container.querySelector('[data-category=price]')!;expect(price).toHaveTextContent(language==='fr'?'Pas de sous-note Google dédiée':'Google không có điểm riêng cho giá');expect(price.textContent).not.toContain('/ 5');expect(container.querySelector('[data-high-signal=unexplained]')).toHaveTextContent(language==='fr'?'Note faible sans explication textuelle':'Điểm thấp nhưng nội dung không giải thích');expect(container.querySelector('[data-high-signal=unexplained] ul')).toBeNull();expect(container.querySelector('[data-high-signal=hidden]')).toHaveTextContent('45 minutes');expect(container.querySelectorAll('.v8-category-line')).toHaveLength(3);expect(container.querySelectorAll('.weekly-section')).toHaveLength(9);expect(mapHistoricalReport({analysis_version:8,consultant_report:report} as HistoricalReportRow).consultant).toBe(report);expect(JSON.stringify(report)).toBe(before)})
it.each([6,7] as const)('old V%i renders exactly8 existing sections without cross-rating data or migration',version=>{const report={...shabuReport('fr',6),version},{container}=render(<I18nProvider language="fr"><ConsultantReport report={report}/></I18nProvider>);expect(container.querySelectorAll('.weekly-section')).toHaveLength(8);expect(container.querySelector('.v8-cross-rating')).toBeNull();expect(container.querySelector('.v8-category-line')).toBeNull()})
