import {useI18n} from '../i18n'
import {v10Messages} from '../i18n/historical-v10'
import {GOLD_TAXONOMY,type GoldTheme} from '../../supabase/functions/_shared/gold-taxonomy'
import type {ConsultantReportData} from '../../supabase/functions/_shared/consultant-contract'
import '../pages/JevBenchmarkPage.css'
export function V10ReportInfo({report,comparisonOnly=false}:{report:ConsultantReportData;comparisonOnly?:boolean}){
  const {language}=useI18n(),t=v10Messages[language],p=report.calibrated_analysis_pipeline,c=report.v9_v10_comparison,n=(v:number|null,d=3)=>v===null?'—':v.toLocaleString(language==='fr'?'fr-FR':'vi-VN',{maximumFractionDigits:d}),percent=(v:number|null)=>v===null?'—':n(v*100,1)+' %'
  if(!p)return null
  const counts=(v:{v9:number;v10:number;common:number;v9_only:number;v10_only:number})=><dl className="jev-pairs"><dt>V9</dt><dd>{v.v9}</dd><dt>V10</dt><dd>{v.v10}</dd><dt>{t.common}</dt><dd>{v.common}</dd><dt>V9 {t.only}</dt><dd>{v.v9_only}</dd><dt>V10 {t.only}</dt><dd>{v.v10_only}</dd></dl>
  const matrix=(a:NonNullable<typeof c>['audit_replay']['by_theme'][string])=><dl className="jev-pairs"><dt>{t.validRetained}</dt><dd>{a.human_valid_retained}</dd><dt>{t.validRemoved}</dt><dd>{a.human_valid_removed}</dd><dt>{t.rejectedRemoved}</dt><dd>{a.human_rejected_removed}</dd><dt>{t.rejectedRetained}</dt><dd>{a.human_rejected_retained}</dd><dt>{t.precision}</dt><dd>{percent(a.observed_validation_rate)}</dd><dt>{t.retention}</dt><dd>{percent(a.valid_signal_retention)}</dd><dt>{t.unavailable}</dt><dd>{a.unavailable}</dd></dl>
  if(comparisonOnly){if(!c)return null;const audit=c.audit_replay;return <div className="jev-results"><section className="card jev-card"><h3>{t.comparison}</h3><h4>Dataset</h4>{counts(c.dataset)}<p>{c.dataset.identical_analysis_text} · {language==='fr'?'textes analytiques identiques':'nội dung phân tích giống nhau'}</p><h4>Findings</h4>{counts(c.findings)}</section>
    <section className="card jev-card"><h3>{t.auditReplay}</h3><p>{t.audit} · {audit.human_valid} {t.validated} · {audit.human_rejected} {t.rejected}</p>{matrix(audit)}<p>{t.target} · {audit.human_valid_retained} / {audit.human_valid} · {audit.retention_target_met===null?'—':audit.retention_target_met?t.targetYes:t.targetNo}</p><p>{t.note}</p></section>
    {Object.entries(c.themes).map(([theme,v])=><section className="card jev-card" key={theme}><h3>{GOLD_TAXONOMY[theme as GoldTheme][language]}</h3>{counts(v)}<dl className="jev-pairs"><dt>{t.retained}</dt><dd>{v.retained_count}</dd><dt>{t.removed}</dt><dd>{v.removed_count}</dd><dt>{t.added}</dt><dd>{v.added_count}</dd></dl>{audit.by_theme[theme as GoldTheme]&&matrix(audit.by_theme[theme as GoldTheme])}</section>)}
    <section className="card jev-card"><h3>{t.cost}</h3>{Object.entries(c.cost).map(([key,v])=><p key={key}>{key==='total'?'Total':key==='jev'?'Jev':'Sol'} · V9 {n(v.v9,6)} USD → V10 {n(v.v10,6)} USD · Δ {n(v.delta,6)} USD ({n(v.delta_percent,1)} %)</p>)}<h4>{t.duration}</h4><p>V9 {n(c.elapsed.v9===null?null:c.elapsed.v9/1000)} s → V10 {n(c.elapsed.v10===null?null:c.elapsed.v10/1000)} s</p><h4>{t.models}</h4><p>V9 {c.models.v9.join(', ')} → V10 {c.models.v10.join(', ')}</p>{c.models.different&&<p role="alert">{t.modelChanged}</p>}</section>
    {Object.entries(c.axes).map(([axis,v])=><details className="card jev-card" key={axis}><summary>{axis}</summary>{counts(v)}</details>)}
  </div>}
  return <section className="card jev-card"><div className="jev-meta"><span>{t.analysis}<strong>{language==='fr'?'Jev calibré':'Jev đã hiệu chỉnh'}</strong></span><span>{t.set}<strong>V10</strong></span><span>{t.synthesis}<strong>{p.narrative_state==='completed'?'GPT-6.1 Sol':language==='fr'?'Déterministe':'Theo quy tắc'}</strong></span><span>{t.cross}<strong>Google + {language==='fr'?'texte':'nội dung'}</strong></span></div><small>{p.question_set} · {p.threshold_version}</small><dl className="jev-pairs"><dt>Jev USD</dt><dd>{n(p.jev_cost_usd,6)}</dd><dt>Sol USD</dt><dd>{n(p.sol_narrative_cost_usd,6)}</dd><dt>Total USD</dt><dd>{n(p.total_estimated_cost_usd,6)}</dd><dt>Jev tokens</dt><dd>{p.jev_input_tokens} / {p.jev_output_tokens}</dd><dt>Sol tokens</dt><dd>{p.sol_narrative_input_tokens} / {p.sol_narrative_output_tokens}</dd><dt>Jev · s</dt><dd>{n(p.jev_elapsed_ms/1000)}</dd><dt>Sol · s</dt><dd>{n(p.sol_narrative_elapsed_ms/1000)}</dd><dt>{t.duration}</dt><dd>{n(p.end_to_end_elapsed_ms===null?null:p.end_to_end_elapsed_ms/1000)} s</dd></dl>{p.unavailable_theme_reviews>0&&<p role="alert">{t.unavailable} · {p.unavailable_theme_reviews}</p>}<details><summary>{t.thresholds}</summary>{Object.entries(p.thresholds).map(([key,v])=><p key={key}>{GOLD_TAXONOMY[key as GoldTheme][language]} · + {v.positive_threshold} / − {v.negative_threshold}</p>)}</details></section>
}
