import {useI18n} from '../i18n'
import {v11Messages} from '../i18n/historical-v11'
import {crossRatingMessages} from '../i18n/cross-rating'
import {GOLD_TAXONOMY,type GoldTheme} from '../../supabase/functions/_shared/gold-taxonomy'
import type {ConsultantReportData} from '../../supabase/functions/_shared/consultant-contract'
import '../pages/JevBenchmarkPage.css'
export function V11ReportInfo({report,comparisonOnly=false}:{report:ConsultantReportData;comparisonOnly?:boolean}){
  const {language}=useI18n(),t=v11Messages[language],g=crossRatingMessages[language],p=report.human_aligned_analysis_pipeline,c=report.v11_comparison,n=(v:number|null,d=3)=>v===null?'—':v.toLocaleString(language==='fr'?'fr-FR':'vi-VN',{maximumFractionDigits:d}),percent=(v:number|null)=>v===null?'—':n(v*100,1)+' %',axisName=(axis:string)=>axis==='quality'?g.categories.food:axis==='price'?g.price:g.categories[axis as 'service'|'atmosphere']
  if(!p)return null
  const counts=(v:{reference:number;v11:number;common:number;reference_only:number;v11_only:number},version:number)=><dl className="jev-pairs"><dt>V{version}</dt><dd>{v.reference}</dd><dt>V11</dt><dd>{v.v11}</dd><dt>{t.common}</dt><dd>{v.common}</dd><dt>V{version} {t.only}</dt><dd>{v.reference_only}</dd><dt>V11 {t.only}</dt><dd>{v.v11_only}</dd></dl>
  const matrix=(a:NonNullable<typeof c>['audit_replay']['by_theme'][string])=><dl className="jev-pairs"><dt>{t.validRetained}</dt><dd>{a.human_valid_retained}</dd><dt>{t.validRemoved}</dt><dd>{a.human_valid_removed}</dd><dt>{t.rejectedRemoved}</dt><dd>{a.human_rejected_removed}</dd><dt>{t.rejectedRetained}</dt><dd>{a.human_rejected_retained}</dd><dt>{t.precision}</dt><dd>{percent(a.observed_validation_rate)}</dd><dt>{t.retention}</dt><dd>{percent(a.valid_signal_retention)}</dd><dt>{t.falseRemoval}</dt><dd>{percent(a.false_positive_removal_rate)}</dd><dt>{t.unavailable}</dt><dd>{a.unavailable}</dd></dl>
  if(comparisonOnly){if(!c)return null;const a=c.audit_replay;return <div className="jev-results"><section className="card jev-card"><h3>{t.findings}</h3><dl className="jev-pairs"><dt>V9</dt><dd>{c.findings_totals.v9}</dd><dt>V10</dt><dd>{c.findings_totals.v10}</dd><dt>V11</dt><dd>{c.findings_totals.v11}</dd></dl></section>
    <section className="card jev-card"><h3>{t.auditReplay}</h3><p>{t.audit} · {a.controlled} · {a.human_valid} {t.validated} · {a.human_rejected} {t.rejected}</p>{matrix(a)}<p>{t.target} · {a.target_valid_retained} / {a.human_valid} · {a.retention_target_met===null?'—':a.retention_target_met?t.targetYes:t.targetNo}</p><p>{t.preferred} · {a.preferred_valid_retained} / {a.human_valid}</p><p>{a.interpretation==='PROMISING'?t.promising:t.needsReview}</p><p>{t.indicative}</p><p>{t.note}</p></section>
    <section className="card jev-card"><h3>{t.recovery}</h3><dl className="jev-pairs"><dt>{t.lostByV10}</dt><dd>{c.v10_valid_signal_recovery.human_valid_lost_by_v10}</dd><dt>{t.recovered}</dt><dd>{c.v10_valid_signal_recovery.recovered_by_v11}</dd><dt>{t.stillMissing}</dt><dd>{c.v10_valid_signal_recovery.still_missing}</dd><dt>{t.unavailable}</dt><dd>{c.v10_valid_signal_recovery.unavailable}</dd></dl></section>
    {(['v9','v10'] as const).map(key=>{const ref=c[key];return <section className="card jev-card" key={key}><h3>{t.comparison} V{ref.reference_version} / V11</h3><h4>Dataset</h4>{counts(ref.dataset,ref.reference_version)}<p>{ref.dataset.identical_analysis_text} · {language==='fr'?'textes analytiques identiques':'nội dung phân tích giống nhau'}</p><h4>{t.findings}</h4>{counts(ref.findings,ref.reference_version)}{Object.entries(ref.axes).map(([axis,v])=><details key={axis}><summary>{axisName(axis)}</summary>{counts(v,ref.reference_version)}</details>)}<h4>{t.cost}</h4>{Object.entries(ref.cost).map(([type,v])=><p key={type}>{type==='total'?'Total':type==='jev'?'Jev':'Sol'} · V{ref.reference_version} {n(v.reference,6)} USD → V11 {n(v.v11,6)} USD · Δ {n(v.delta,6)} USD ({n(v.delta_percent,1)} %)</p>)}<h4>{t.duration}</h4>{Object.entries(ref.elapsed).map(([type,v])=><p key={type}>{type==='jev'?t.timeJev:type==='sol_narrative'?t.timeSol:t.timeTotal} · V{ref.reference_version} {n(v.reference===null?null:v.reference/1000)} s → V11 {n(v.v11===null?null:v.v11/1000)} s</p>)}<h4>{t.models}</h4><p>V{ref.reference_version} {ref.models.reference.join(', ')} → V11 {ref.models.v11.join(', ')}</p>{ref.models.different&&<p role="alert">{t.modelChanged}</p>}<details><summary>{t.crossComparison}</summary>{Object.entries(ref.cross_rating).map(([axis,v])=><article key={axis}><h4>{g.categories[axis as 'food'|'service'|'atmosphere']}</h4>{Object.entries(v.statuses).map(([status,s])=><p key={status}>{g.statuses[status as keyof typeof g.statuses]} · V{ref.reference_version} {s.reference} → V11 {s.v11}</p>)}</article>)}</details></section>})}
    {Object.keys(c.v9.themes).map(theme=><section className="card jev-card" key={theme}><h3>{GOLD_TAXONOMY[theme as GoldTheme][language]}</h3><dl className="jev-pairs"><dt>V9</dt><dd>{c.v9.themes[theme].reference}</dd><dt>V10</dt><dd>{c.v10.themes[theme].reference}</dd><dt>V11</dt><dd>{c.v9.themes[theme].v11}</dd></dl>{a.by_theme[theme]&&matrix(a.by_theme[theme])}</section>)}
  </div>}
  return <section className="card jev-card"><div className="jev-meta"><span>{t.analysis}<strong>Jev human-aligned</strong></span><span>Threshold config<strong>v2</strong></span><span>{t.set}<strong>V11</strong></span><span>{t.synthesis}<strong>{p.narrative_state==='completed'?'GPT-6.1 Sol':language==='fr'?'Déterministe':'Theo quy tắc'}</strong></span></div><small>{p.question_set} · {p.threshold_version}</small><dl className="jev-pairs"><dt>Jev USD</dt><dd>{n(p.jev_cost_usd,6)}</dd><dt>Sol USD</dt><dd>{n(p.sol_narrative_cost_usd,6)}</dd><dt>Total USD</dt><dd>{n(p.total_estimated_cost_usd,6)}</dd><dt>Jev tokens</dt><dd>{p.jev_input_tokens} / {p.jev_output_tokens}</dd><dt>Sol tokens</dt><dd>{p.sol_narrative_input_tokens} / {p.sol_narrative_output_tokens}</dd><dt>{t.timeJev}</dt><dd>{n(p.jev_elapsed_ms/1000)} s</dd><dt>{t.timeSol}</dt><dd>{n(p.sol_narrative_elapsed_ms/1000)} s</dd><dt>{t.timeTotal}</dt><dd>{n(p.end_to_end_elapsed_ms===null?null:p.end_to_end_elapsed_ms/1000)} s</dd></dl>{p.unavailable_theme_reviews>0&&<p role="alert">{t.unavailable} · {p.unavailable_theme_reviews}</p>}<details><summary>{t.thresholds}</summary>{Object.entries(p.thresholds).map(([theme,v])=><p key={theme}>{GOLD_TAXONOMY[theme as GoldTheme][language]} · + {v.positive_threshold} / − {v.negative_threshold}</p>)}</details></section>
}
