import '../pages/JevBenchmarkPage.css'
import {useI18n} from '../i18n'
import type {ConsultantReportData} from '../../supabase/functions/_shared/consultant-contract'
import {GOLD_TAXONOMY,type GoldTheme} from '../../supabase/functions/_shared/gold-taxonomy'
import {crossRatingMessages} from '../i18n/cross-rating'
export function V9ReportInfo({report,comparisonOnly=false}:{report:ConsultantReportData;comparisonOnly?:boolean}){const {language}=useI18n(),fr=language==='fr',p=report.analysis_pipeline,t=crossRatingMessages[language],axisLabel=(axis:string)=>axis==="quality"?t.categories.food:axis==="price"?t.price:t.categories[axis as "service"],c=report.v8_v9_comparison,n=(v:number|null,d=3)=>v===null?'—':v.toLocaleString(fr?'fr-FR':'vi-VN',{maximumFractionDigits:d}),counts=(v:{v8:number;v9:number;common:number;v8_only:number;v9_only:number})=><dl className="jev-pairs"><dt>V8 · Sol</dt><dd>{v.v8}</dd><dt>V9 · Jev</dt><dd>{v.v9}</dd><dt>{fr?'Communs':'Chung'}</dt><dd>{v.common}</dd><dt>V8 {fr?'uniquement':'riêng'}</dt><dd>{v.v8_only}</dd><dt>V9 {fr?'uniquement':'riêng'}</dt><dd>{v.v9_only}</dd></dl>
 if(!p)return null
 if(comparisonOnly)return c?<section className="card jev-card"><h3>{fr?'Comparaison V8 / V9':'So sánh V8 / V9'}</h3><p>{fr?'Même snapshot. Comparaison des décisions, sans verdict automatique sur leur qualité.':'Cùng dữ liệu cố định. So sánh quyết định, không tự động kết luận về chất lượng.'}</p><h4>Dataset</h4>{counts(c.dataset)}<h4>Findings</h4>{counts(c.findings)}{Object.entries(c.axes).map(([axis,v])=><details key={axis}><summary>{axisLabel(axis)}</summary>{counts(v)}</details>)}{Object.entries(c.themes).map(([theme,v])=><details key={theme}><summary>{GOLD_TAXONOMY[theme as GoldTheme][language]}</summary>{counts(v)}</details>)}<h4>{fr?'Lecture croisée des notes':'Đối chiếu điểm số'}</h4>{Object.entries(c.cross_rating).map(([axis,v])=><details key={axis}><summary>{axis==="food"?t.categories.food:axisLabel(axis)} · {v.comparable_reviews} {fr?'avis comparables':'đánh giá có thể so sánh'}</summary>{Object.entries(v.statuses).map(([status,s])=><p key={status}>{t.statuses[status as keyof typeof t.statuses]} · V8 {s.v8} → V9 {s.v9}</p>)}</details>)}<p>{fr?'Coût estimé':'Chi phí ước tính'} V8 {n(c.cost.v8_estimated_cost_usd,6)} USD · V9 {n(c.cost.v9_estimated_cost_usd,6)} USD · Δ {n(c.cost.difference_percent)} %</p><p>V8 {n(c.elapsed.v8_ms/1000)} s · V9 {n(c.elapsed.v9_ms===null?null:c.elapsed.v9_ms/1000)} s</p></section>:null
 return <section className="card jev-card"><div className="jev-meta"><span>{fr?'Analyse des thèmes':'Phân tích chủ đề'}<strong>Jev</strong></span><span>{fr?'Synthèse':'Tổng hợp'}<strong>{p.narrative_state==='completed'?'GPT-6.1 Sol':fr?'Déterministe':'Theo quy tắc'}</strong></span><span>Google<strong>{fr?'Croisement déterministe':'Đối chiếu theo quy tắc'}</strong></span></div><p>{p.served_models.join(', ')} · {p.theme_repeat_count} {fr?'répétitions':'lần lặp'} · {p.threshold}</p>{(report.analysis_unavailable_count??0)+p.unavailable_theme_reviews>0&&<p role="alert" className="jev-warning">{fr?'Analyses Jev indisponibles':'Phân tích Jev chưa có kết quả'} · {fr?'sentiment':'cảm xúc'} {report.analysis_unavailable_count??0} · {fr?'thèmes':'chủ đề'} {p.unavailable_theme_reviews}</p>}<dl className="jev-pairs"><dt>Jev · {fr?'thèmes / sentiment':'chủ đề / cảm xúc'}</dt><dd>{p.jev_theme_requests} / {p.jev_sentiment_requests}</dd><dt>Jev tokens</dt><dd>{p.jev_input_tokens} / {p.jev_output_tokens}</dd><dt>Jev USD</dt><dd>{n(p.jev_cost_usd,6)}</dd><dt>Sol · {fr?'appels narrative':'lần gọi tổng hợp'}</dt><dd>{p.sol_narrative_calls}</dd><dt>Sol tokens</dt><dd>{p.sol_narrative_input_tokens} / {p.sol_narrative_output_tokens}</dd><dt>Sol USD</dt><dd>{n(p.sol_narrative_cost_usd,6)}</dd><dt>Total USD</dt><dd>{n(p.total_estimated_cost_usd,6)}</dd><dt>Jev</dt><dd>{n(p.jev_elapsed_ms/1000)} s</dd><dt>Sol</dt><dd>{n(p.sol_narrative_elapsed_ms/1000)} s</dd><dt>{fr?'Durée totale':'Tổng thời gian'}</dt><dd>{n(p.end_to_end_elapsed_ms===null?null:p.end_to_end_elapsed_ms/1000)} s</dd></dl><small>{fr?'Estimation aux tarifs configurés. Le temps Jev cumule le traitement actif ; le total inclut l’orchestration serveur.':'Ước tính theo giá cấu hình. Thời gian Jev cộng thời gian xử lý; tổng thời gian bao gồm điều phối máy chủ.'}</small>{!p.usage_complete&&<p className="jev-warning">{fr?'Usage incomplet : estimation partielle.':'Usage chưa đầy đủ: ước tính một phần.'}</p>}</section>
}
