import {requireUser,assertMembership} from '../_shared/auth.ts'
import {json} from '../_shared/cors.ts'
import {compactHandler,type CompactData} from '../_shared/jev-compact-api.ts'
import {economyCacheKey,reusableEconomyCache,type EconomyCache} from '../_shared/jev-economy-cache.ts'
import {COMPACT_EXPERIMENT,COMPACT_CONFIGS,compactIdentity} from '../_shared/jev-compact-core.ts'
Deno.serve(compactHandler(async request=>{const ctx=await requireUser(request),org=new URL(request.url).searchParams.get('organization_id');if(!org||!/^[a-f0-9-]{36}$/i.test(org))throw new Error('FORBIDDEN');await assertMembership(ctx.client,ctx.user.id,org,['owner','admin','manager']);
 const rpc=async(name:string,args:Record<string,unknown>)=>{const {data,error}=await ctx.admin.rpc(name,args);if(error)throw new Error(/COMPACT_[A-Z_]+|FORBIDDEN/.exec(error.message)?.[0]??'COMPACT_SAVE_FAILED');return data},read=async():Promise<CompactData>=>{const {data:s,error}=await ctx.admin.from('analysis_jev_compact_sets').select('*').eq('organization_id',org).eq('name',COMPACT_EXPERIMENT).maybeSingle();if(error)throw new Error('COMPACT_READ_FAILED');if(!s)return {set:null,items:[],texts:[],references:[],seal:null,run:null,comparison:null,authorization:null,progress:{total:0,completed:0,failed:0}};
 const queries=await Promise.all(['items','texts','ai_references','seals','runs','authorizations'].map(async table=>{const {data,error}=await ctx.admin.from('analysis_jev_compact_'+table).select('*').eq('set_id',s.id).limit(801);if(error)throw new Error('COMPACT_READ_FAILED');return data}));const [items,texts,references,seals,runs,authorizations]=queries,run=runs[0]??null;let comparison=null,progress={total:0,completed:0,failed:0};if(run){const {data:result,error:re}=await ctx.admin.from('analysis_jev_compact_results').select('comparison').eq('run_id',run.id).maybeSingle(),{data:tasks,error:te}=await ctx.admin.from('analysis_jev_compact_tasks').select('status').eq('run_id',run.id).limit(65);if(re||te)throw new Error('COMPACT_READ_FAILED');comparison=result?.comparison??null;progress={total:tasks.length,completed:tasks.filter(t=>t.status==='completed').length,failed:tasks.filter(t=>t.status==='failed').length}}
 return {set:s,items:items.sort((a,b)=>a.position-b.position),texts,references,seal:seals[0]??null,run,comparison,authorization:authorizations[0]?{cost_limit_usd:Number(authorizations[0].cost_limit_usd),expected_served_model:authorizations[0].expected_served_model}:null,progress} as CompactData};
 const cacheCounts=async()=>{const d=await read();if(!d.items.length)return {A:0,B:0};let model=d.authorization?.expected_served_model;const {data:old,error:oe}=await ctx.admin.from('analysis_jev_economy_comparisons').select('comparison').eq('organization_id',org).limit(1);if(oe)throw new Error('COMPACT_READ_FAILED');model??=old?.[0]?.comparison.variants.pass1.usage.served_models[0];if(!model)throw new Error('COMPACT_SERVED_MODEL_REQUIRED');const {data:cached,error}=await ctx.admin.from('analysis_jev_review_cache').select('*').eq('organization_id',org).in('review_id',d.items.map(i=>i.review_id)).in('configuration_id',Object.values(COMPACT_CONFIGS).map(c=>c.id));if(error)throw new Error('COMPACT_READ_FAILED');const counts={A:0,B:0};for(const i of d.items){const t=d.texts.find(t=>t.id===i.text_id);if(!t)continue;for(const v of ['A','B'] as const){const identity=await compactIdentity(v,org,i.establishment_id,i.review_id,t.analysis_text,model),key=await economyCacheKey(identity);if(cached.some(c=>reusableEconomyCache(c as EconomyCache,identity,key)))counts[v]++}}return counts};
 return {read,cacheCounts,configurations:async()=>{const {data,error}=await ctx.admin.from('analysis_jev_economy_configurations').select('id,config,config_sha256').in('id',Object.values(COMPACT_CONFIGS).map(c=>c.id));if(error)throw new Error('COMPACT_CONFIG_CHANGED');return data},inventory:async()=>{const d=await read();return d.set?.candidate_stats??await rpc('compact_candidate_inventory',{p_org:org})},costBasis:async()=>{const {data,error}=await ctx.admin.from('analysis_jev_economy_comparisons').select('comparison,rates').eq('organization_id',org);if(error||!data.length)throw new Error('COMPACT_COST_BASIS_REQUIRED');return {input_tokens:data.reduce((n,r)=>n+(r.comparison.variants.pass1.usage.input_tokens??0),0),output_tokens:data.reduce((n,r)=>n+(r.comparison.variants.pass1.usage.output_tokens??0),0),reviews:data.reduce((n,r)=>n+r.comparison.evaluable_reviews,0),input_rate:Number(data[0].rates.jev_input),output_rate:Number(data[0].rates.jev_output)}},prepare:async()=>{await rpc('prepare_compact_set',{p_user:ctx.user.id,p_org:org})},importTexts:async rows=>{const d=await read();if(!d.set)throw new Error('COMPACT_SET_REQUIRED');await rpc('import_compact_texts',{p_user:ctx.user.id,p_set:d.set.id,p_rows:rows})},importReferences:async rows=>{const d=await read();if(!d.set)throw new Error('COMPACT_SET_REQUIRED');await rpc('import_compact_references',{p_user:ctx.user.id,p_set:d.set.id,p_rows:rows})},seal:async()=>{const d=await read();if(!d.set)throw new Error('COMPACT_SET_REQUIRED');await rpc('seal_compact_set',{p_user:ctx.user.id,p_set:d.set.id})},start:async(fingerprint,estimate,rates)=>{const d=await read();if(!d.set)throw new Error('COMPACT_SET_REQUIRED');await rpc('start_compact_run',{p_user:ctx.user.id,p_set:d.set.id,p_confirm:true,p_seal_sha:fingerprint,p_rates:rates,p_estimate:estimate})}}
}))
