-- Pilot preparation only. No authorization, analysis task or report is created.
create function public.read_economy_pilot_source(p_user uuid,p_est uuid) returns jsonb language plpgsql stable security invoker set search_path='' as $$
declare e public.establishments;begin
 select * into e from public.establishments where id=p_est;if not found or p_est<>'252a8dca-14c7-4f09-bd1f-7b2c40ae97aa' or not exists(select 1 from public.organization_members where organization_id=e.organization_id and user_id=p_user and role in ('owner','admin','manager')) then raise exception 'FORBIDDEN';end if;
 return jsonb_build_object('captured_at',now(),'establishment',jsonb_build_object('id',e.id,'organization_id',e.organization_id,'name',e.name,'total_reviews',e.total_reviews),
 'reviews',(select jsonb_agg(to_jsonb(x) order by x.id) from (select r.id,r.organization_id,r.establishment_id,r.rating,r.original_text,r.original_language,r.review_detailed_rating,r.review_context,r.published_at,coalesce((select jsonb_agg(jsonb_build_object('id',t.id,'language',t.language,'translated_text',t.translated_text,'created_at',t.created_at) order by t.created_at desc,t.id) from public.review_translations t where t.review_id=r.id and t.language='en'),'[]'::jsonb) review_translations from public.reviews r where r.establishment_id=e.id and r.organization_id=e.organization_id) x),
 'overrides',coalesce((select jsonb_agg(to_jsonb(o)) from public.analysis_review_english_translation_overrides o join public.reviews r on r.id=o.review_id where r.organization_id=e.organization_id and r.establishment_id=e.id),'[]'::jsonb),
 'cache',coalesce((select jsonb_agg(to_jsonb(c)) from public.analysis_jev_review_cache c where c.organization_id=e.organization_id and c.establishment_id=e.id),'[]'::jsonb),
 'legacy',(select to_jsonb(h)||jsonb_build_object('source_ids',(select jsonb_agg(coalesce(x->>'id',x->>'review_id')) from public.historical_report_runs r cross join lateral jsonb_array_elements(r.snapshot->'reviews') x where r.generation_id=h.generation_id),'model',(select model from public.historical_report_runs r where r.generation_id=h.generation_id)) from public.historical_establishment_reports h where h.establishment_id=e.id order by h.generated_at desc limit 1),
 'jev_rates',(select rates from public.analysis_jev_economy_comparisons where organization_id=e.organization_id order by created_at desc limit 1),
 'narrative_usage',(select jsonb_build_object('input',sol_narrative_input_tokens,'output',sol_narrative_output_tokens,'rates',rates) from public.historical_jev_run_metrics where organization_id=e.organization_id and sol_narrative_calls>0 order by created_at desc limit 1));end $$;
revoke all on function public.read_economy_pilot_source(uuid,uuid) from public,anon,authenticated;
grant execute on function public.read_economy_pilot_source(uuid,uuid) to service_role;
create table public.analysis_jev_pilot_snapshots(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),establishment_id uuid not null references public.establishments(id),
 name text not null default 'jev-economy-pilot-v1',configuration_id text not null references public.analysis_jev_economy_configurations(id),config_sha256 text not null,
 source_sha256 text not null check(source_sha256~'^[a-f0-9]{64}$'),source jsonb not null,rates jsonb not null,preview_at_creation jsonb not null,
 created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),production_enabled boolean not null default false check(not production_enabled),
 unique(organization_id,establishment_id,source_sha256),check(configuration_id='v12_economy_1pass_v1'),check(establishment_id='252a8dca-14c7-4f09-bd1f-7b2c40ae97aa')
);
create index pilot_snapshot_est on public.analysis_jev_pilot_snapshots(establishment_id,created_at desc);
create index pilot_snapshot_config on public.analysis_jev_pilot_snapshots(configuration_id);
create index pilot_snapshot_creator on public.analysis_jev_pilot_snapshots(created_by);
create table public.analysis_jev_pilot_authorizations(
 id uuid primary key default gen_random_uuid(),snapshot_id uuid not null references public.analysis_jev_pilot_snapshots(id),organization_id uuid not null references public.organizations(id),
 stage text not null check(stage in ('jev','sol')),language text not null check(language in ('en','fr','vi')),source_sha256 text not null,config_sha256 text not null,
 input_sha256 text not null,allowed_review_ids jsonb not null default '[]',max_calls integer not null check(max_calls>=1),allow_partial_report boolean not null default false,
 authorized_by uuid not null references auth.users(id),authorized_at timestamptz not null,user_instruction text not null check(btrim(user_instruction)<>''),
 unique(snapshot_id,stage,language,input_sha256),check(stage='jev' and language='en' or stage='sol' and language in ('fr','vi') and max_calls=1)
);
create index pilot_auth_org on public.analysis_jev_pilot_authorizations(organization_id);
create index pilot_auth_actor on public.analysis_jev_pilot_authorizations(authorized_by);
create table public.analysis_jev_pilot_jobs(
 id uuid primary key default gen_random_uuid(),snapshot_id uuid not null references public.analysis_jev_pilot_snapshots(id),organization_id uuid not null references public.organizations(id),
 authorization_id uuid not null references public.analysis_jev_pilot_authorizations(id),stage text not null check(stage in ('jev','sol')),language text not null,
 status text not null default 'queued' check(status in ('queued','running','completed','failed')),input_sha256 text not null,input_context jsonb not null,
 expected_served_model text,created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),cost_confirmed_at timestamptz not null,
 started_at timestamptz,completed_at timestamptz,lease_owner uuid,lease_until timestamptz,request_count integer not null default 0,
 input_tokens bigint not null default 0,output_tokens bigint not null default 0,cost_usd numeric not null default 0,duration_ms bigint not null default 0,
 usage_complete boolean not null default true,result jsonb,error_code text,unique(snapshot_id,stage,language,input_sha256),check(stage<>'sol' or request_count between 0 and 1)
);
create unique index pilot_one_jev_job on public.analysis_jev_pilot_jobs(snapshot_id) where stage='jev';
create index pilot_jobs_org on public.analysis_jev_pilot_jobs(organization_id);
create index pilot_jobs_auth on public.analysis_jev_pilot_jobs(authorization_id);
create index pilot_jobs_creator on public.analysis_jev_pilot_jobs(created_by);
create table public.analysis_jev_pilot_tasks(
 id uuid primary key default gen_random_uuid(),job_id uuid not null references public.analysis_jev_pilot_jobs(id),review_id uuid not null references public.reviews(id),analysis_text_sha256 text not null,
 status text not null default 'pending' check(status in ('pending','running','completed','failed')),cache_id uuid references public.analysis_jev_review_cache(id),response jsonb,served_model text,
 input_tokens bigint not null default 0,output_tokens bigint not null default 0,cost_usd numeric not null default 0,duration_ms bigint not null default 0,
 request_count integer not null default 0 check(request_count between 0 and 1),retry_count integer not null default 0 check(retry_count=0),reused boolean not null default false,
 usage_complete boolean not null default true,error_code text,lease_owner uuid,started_at timestamptz,completed_at timestamptz,unique(job_id,review_id)
);
create index pilot_tasks_review on public.analysis_jev_pilot_tasks(review_id);
create index pilot_tasks_cache on public.analysis_jev_pilot_tasks(cache_id) where cache_id is not null;
create table public.analysis_jev_pilot_events(id bigint generated always as identity primary key,snapshot_id uuid not null references public.analysis_jev_pilot_snapshots(id),organization_id uuid not null references public.organizations(id),actor_id uuid references auth.users(id),action text not null,details jsonb not null default '{}',created_at timestamptz not null default now());
create index pilot_events_scope on public.analysis_jev_pilot_events(organization_id,snapshot_id);
create index pilot_events_snapshot on public.analysis_jev_pilot_events(snapshot_id);
create index pilot_events_actor on public.analysis_jev_pilot_events(actor_id) where actor_id is not null;
do $$declare t text;begin foreach t in array array['analysis_jev_pilot_snapshots','analysis_jev_pilot_authorizations','analysis_jev_pilot_jobs','analysis_jev_pilot_tasks','analysis_jev_pilot_events'] loop
 execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from anon,authenticated',t);execute format('grant select on public.%I to authenticated',t);execute format('grant all on public.%I to service_role',t);
 if t='analysis_jev_pilot_tasks' then execute format('create policy pilot_read on public.%I for select to authenticated using(exists(select 1 from public.analysis_jev_pilot_jobs j join public.organization_members m on m.organization_id=j.organization_id where j.id=job_id and m.user_id=(select auth.uid()) and m.role in (''owner'',''admin'',''manager'')))',t);
 else execute format('create policy pilot_read on public.%I for select to authenticated using(exists(select 1 from public.organization_members m where m.organization_id=%I.organization_id and m.user_id=(select auth.uid()) and m.role in (''owner'',''admin'',''manager'')))',t,t);end if;end loop;end $$;
grant usage,select on sequence public.analysis_jev_pilot_events_id_seq to service_role;
create function public.pilot_immutable() returns trigger language plpgsql security invoker set search_path='' as $$begin
 if tg_table_name in ('analysis_jev_pilot_snapshots','analysis_jev_pilot_authorizations','analysis_jev_pilot_events') or tg_op='DELETE' then raise exception 'PILOT_IMMUTABLE';end if;
 if old.status in ('completed','failed') then raise exception 'PILOT_NO_AUTOMATIC_RETRY';end if;
 if tg_table_name='analysis_jev_pilot_jobs' and to_jsonb(new)-array['status','started_at','completed_at','lease_owner','lease_until','request_count','input_tokens','output_tokens','cost_usd','duration_ms','usage_complete','result','error_code']<>to_jsonb(old)-array['status','started_at','completed_at','lease_owner','lease_until','request_count','input_tokens','output_tokens','cost_usd','duration_ms','usage_complete','result','error_code'] then raise exception 'PILOT_JOB_SCOPE_IMMUTABLE';end if;
 if tg_table_name='analysis_jev_pilot_tasks' and to_jsonb(new)-array['status','cache_id','response','served_model','input_tokens','output_tokens','cost_usd','duration_ms','request_count','reused','usage_complete','error_code','lease_owner','started_at','completed_at']<>to_jsonb(old)-array['status','cache_id','response','served_model','input_tokens','output_tokens','cost_usd','duration_ms','request_count','reused','usage_complete','error_code','lease_owner','started_at','completed_at'] then raise exception 'PILOT_TASK_SCOPE_IMMUTABLE';end if;return new;end $$;
do $$declare t text;begin foreach t in array array['analysis_jev_pilot_snapshots','analysis_jev_pilot_authorizations','analysis_jev_pilot_jobs','analysis_jev_pilot_tasks','analysis_jev_pilot_events'] loop execute format('create trigger pilot_immutable before update or delete on public.%I for each row execute function public.pilot_immutable()',t);end loop;end $$;
create function public.create_economy_pilot_snapshot(p_user uuid,p_org uuid,p_est uuid,p_source jsonb,p_source_sha text,p_config_sha text,p_rates jsonb,p_preview jsonb) returns uuid language plpgsql security invoker set search_path='' as $$
declare sid uuid;c public.analysis_jev_economy_configurations;begin
 if p_est<>'252a8dca-14c7-4f09-bd1f-7b2c40ae97aa' or not exists(select 1 from public.establishments where id=p_est and organization_id=p_org) or not exists(select 1 from public.organization_members where organization_id=p_org and user_id=p_user and role in ('owner','admin','manager')) then raise exception 'FORBIDDEN';end if;
 select * into c from public.analysis_jev_economy_configurations where id='v12_economy_1pass_v1';if not found or c.config_sha256<>p_config_sha then raise exception 'PILOT_CONFIG_CHANGED';end if;
 if jsonb_array_length(p_source->'reviews')<>(select count(distinct x->>'id') from jsonb_array_elements(p_source->'reviews') x) or exists(select 1 from jsonb_array_elements(p_source->'reviews') x left join public.reviews r on r.id=(x->>'id')::uuid where r.id is null or r.organization_id<>p_org or r.establishment_id<>p_est or x->>'original_text_sha256'<>encode(extensions.digest(coalesce(r.original_text,''),'sha256'),'hex') or (x->>'analysis_text') is not null and ((x->>'analysis_language')<>'en' or x->>'analysis_text_sha256'<>encode(extensions.digest(x->>'analysis_text','sha256'),'hex'))) then raise exception 'PILOT_SOURCE_CHANGED';end if;
 perform pg_advisory_xact_lock(hashtextextended(p_org::text||':'||p_est::text||':'||p_source_sha,0));select id into sid from public.analysis_jev_pilot_snapshots where organization_id=p_org and establishment_id=p_est and source_sha256=p_source_sha;if found then return sid;end if;
 insert into public.analysis_jev_pilot_snapshots(organization_id,establishment_id,configuration_id,config_sha256,source_sha256,source,rates,preview_at_creation,created_by) values(p_org,p_est,c.id,p_config_sha,p_source_sha,p_source,p_rates,p_preview,p_user) returning id into sid;
 insert into public.analysis_jev_pilot_events(snapshot_id,organization_id,actor_id,action,details) values(sid,p_org,p_user,'free_snapshot_and_cache_preview_no_models',jsonb_build_object('stored_reviews',jsonb_array_length(p_source->'reviews'),'new_paid_calls',0));return sid;end $$;
create function public.start_economy_pilot_job(p_user uuid,p_snapshot uuid,p_stage text,p_language text,p_input_sha text,p_context jsonb,p_confirm boolean) returns uuid language plpgsql security invoker set search_path='' as $$
declare s public.analysis_jev_pilot_snapshots;a public.analysis_jev_pilot_authorizations;jid uuid;begin
 select * into s from public.analysis_jev_pilot_snapshots where id=p_snapshot for update;if not found or not exists(select 1 from public.organization_members where organization_id=s.organization_id and user_id=p_user and role in ('owner','admin','manager')) then raise exception 'FORBIDDEN';end if;
 if p_confirm is distinct from true then raise exception 'PILOT_COST_CONFIRMATION_REQUIRED';end if;
 select id into jid from public.analysis_jev_pilot_jobs where snapshot_id=s.id and stage=p_stage and language=p_language and(stage='jev' or input_sha256=p_input_sha);if found then return jid;end if;
 select * into a from public.analysis_jev_pilot_authorizations where snapshot_id=s.id and stage=p_stage and language=p_language and source_sha256=s.source_sha256 and config_sha256=s.config_sha256 and(stage='jev' or input_sha256=p_input_sha) order by authorized_at desc limit 1;if not found or a.organization_id<>s.organization_id then raise exception 'PILOT_NEW_AUTHORIZATION_REQUIRED';end if;
 if p_stage='jev' then
 if p_language<>'en' or jsonb_array_length(p_context->'review_ids')=0 or jsonb_array_length(p_context->'review_ids')>a.max_calls or exists(select 1 from jsonb_array_elements_text(p_context->'review_ids') x where not(a.allowed_review_ids?x) or not exists(select 1 from jsonb_array_elements(s.source->'reviews') r where r->>'id'=x and r->>'analysis_language'='en' and btrim(r->>'analysis_text')<>'')) then raise exception 'PILOT_ANALYSIS_SCOPE_INVALID';end if;
 elsif p_stage='sol' then
 if p_language not in ('fr','vi') or p_context->'narrative_input'->>'language'<>p_language or (coalesce((p_context->'statistics'->'coverage'->>'missing_analyses')::int,0)>0 and not a.allow_partial_report) then raise exception 'PILOT_PARTIAL_REPORT_NOT_AUTHORIZED';end if;
 if exists(select 1 from public.analysis_jev_pilot_jobs where snapshot_id=s.id and stage='jev' and status in ('queued','running')) then raise exception 'PILOT_ANALYSES_STILL_RUNNING';end if;
 else raise exception 'PILOT_STAGE_INVALID';end if;
 insert into public.analysis_jev_pilot_jobs(snapshot_id,organization_id,authorization_id,stage,language,input_sha256,input_context,expected_served_model,created_by,cost_confirmed_at) values(s.id,s.organization_id,a.id,p_stage,p_language,p_input_sha,p_context,p_context->>'expected_served_model',p_user,now()) returning id into jid;
 if p_stage='jev' then insert into public.analysis_jev_pilot_tasks(job_id,review_id,analysis_text_sha256) select jid,(x->>'id')::uuid,x->>'analysis_text_sha256' from jsonb_array_elements(s.source->'reviews') x where p_context->'review_ids'?(x->>'id');end if;
 insert into public.analysis_jev_pilot_events(snapshot_id,organization_id,actor_id,action,details) values(s.id,s.organization_id,p_user,'manual_paid_phase_confirmed',jsonb_build_object('job_id',jid,'stage',p_stage));return jid;end $$;
create function public.pilot_cache_dispatch_allowed(p_cache uuid,p_org uuid,p_config text) returns boolean language sql stable security invoker set search_path='' as $$
 select p_config='v12_economy_1pass_v1' and exists(select 1 from public.analysis_jev_pilot_tasks t join public.analysis_jev_pilot_jobs j on j.id=t.job_id join public.analysis_jev_pilot_snapshots s on s.id=j.snapshot_id join public.analysis_jev_pilot_authorizations a on a.id=j.authorization_id where t.cache_id=p_cache and t.status='running' and j.status='running' and j.stage='jev' and j.organization_id=p_org and a.organization_id=p_org and a.source_sha256=s.source_sha256 and a.config_sha256=s.config_sha256 and a.allowed_review_ids?t.review_id::text)
$$;
do $$declare src text;begin select pg_get_functiondef('public.jev_economy_guard()'::regprocedure) into src;
 if position('then raise exception ''ECONOMY_PAID_ENGINE_DISABLED'';end if;' in src)=0 then raise exception 'PILOT_CACHE_GUARD_SHAPE_CHANGED';end if;
 src=replace(src,'then raise exception ''ECONOMY_PAID_ENGINE_DISABLED'';end if;','and not public.pilot_cache_dispatch_allowed(new.id,new.organization_id,new.configuration_id) then raise exception ''ECONOMY_PAID_ENGINE_DISABLED'';end if;');execute src;end $$;
revoke all on function public.pilot_immutable(),public.create_economy_pilot_snapshot(uuid,uuid,uuid,jsonb,text,text,jsonb,jsonb),public.start_economy_pilot_job(uuid,uuid,text,text,text,jsonb,boolean),public.pilot_cache_dispatch_allowed(uuid,uuid,text) from public,anon,authenticated;
grant execute on function public.create_economy_pilot_snapshot(uuid,uuid,uuid,jsonb,text,text,jsonb,jsonb),public.start_economy_pilot_job(uuid,uuid,text,text,text,jsonb,boolean),public.pilot_cache_dispatch_allowed(uuid,uuid,text) to service_role;
create function public.pilot_response_valid(p_response jsonb) returns boolean language plpgsql immutable security invoker set search_path='' as $$
declare t record;p text;total numeric;begin
 if jsonb_typeof(p_response->'themes') is distinct from 'object' or (select count(*) from jsonb_object_keys(p_response->'themes'))<>25 then return false;end if;
 for t in select key,value from jsonb_each(p_response->'themes') loop
 if t.key not in ('food_quality','freshness','cooking','temperature','portions','presentation','drinks','variety','consistency','friendly_staff','attentiveness','wait_time','coordination','communication','order_accuracy','professionalism','atmosphere','decor','noise','comfort','cleanliness','location','value','billing','price_level') or t.value->>'choice' is null or t.value->>'choice' not in ('absent','positive','negative','both') then return false;end if;total=0;
 foreach p in array array['absent','positive','negative','both'] loop if jsonb_typeof(t.value->'probabilities'->p) is distinct from 'number' then return false;end if;
 if (t.value->'probabilities'->>p)::numeric not between 0 and 1 then return false;end if;total=total+(t.value->'probabilities'->>p)::numeric;end loop;if abs(total-1)>.01000000001 then return false;end if;end loop;return true;end $$;
create function public.claim_economy_pilot_job(p_worker uuid) returns jsonb language plpgsql security invoker set search_path='' as $$
declare j public.analysis_jev_pilot_jobs;begin perform pg_advisory_xact_lock(hashtextextended('economy-pilot-worker-v1',0));
 if exists(select 1 from public.analysis_jev_pilot_jobs where status='running' and lease_until>now()) then return null;end if;
 select q.* into j from public.analysis_jev_pilot_jobs q join public.analysis_jev_pilot_authorizations a on a.id=q.authorization_id where q.status='queued' or(q.status='running' and (q.lease_until is null or q.lease_until<=now())) order by q.created_at for update of q skip locked limit 1;if not found then return null;end if;
 if j.stage='sol' and j.status='running' then update public.analysis_jev_pilot_jobs set status='failed',error_code='PILOT_SOL_RESPONSE_UNCONFIRMED_NO_RETRY',usage_complete=false,completed_at=now(),lease_owner=null,lease_until=null where id=j.id;return null;end if;
 update public.analysis_jev_review_cache c set status='billing_uncertain',processed_at=now(),error_code='PILOT_RESPONSE_UNCONFIRMED',usage_complete=false where c.status='dispatched' and c.id in(select cache_id from public.analysis_jev_pilot_tasks where job_id=j.id and status='running');
 update public.analysis_jev_pilot_tasks set status='failed',request_count=1,error_code='PILOT_RESPONSE_UNCONFIRMED_NO_RETRY',usage_complete=false,completed_at=now() where job_id=j.id and status='running';
 update public.analysis_jev_pilot_jobs set status='running',lease_owner=p_worker,lease_until=now()+interval '240 seconds',started_at=coalesce(started_at,now()),request_count=request_count where id=j.id returning * into j;return to_jsonb(j);end $$;
create function public.claim_economy_pilot_tasks(p_job uuid,p_worker uuid) returns setof public.analysis_jev_pilot_tasks language plpgsql security invoker set search_path='' as $$
declare j public.analysis_jev_pilot_jobs;s public.analysis_jev_pilot_snapshots;t public.analysis_jev_pilot_tasks;c public.analysis_jev_economy_configurations;r jsonb;found_cache public.analysis_jev_review_cache;identity jsonb;reservation jsonb;begin
 select * into j from public.analysis_jev_pilot_jobs where id=p_job and stage='jev' and status='running' and lease_owner=p_worker and lease_until>now() for update;if not found then raise exception 'PILOT_LEASE_LOST';end if;
 select * into s from public.analysis_jev_pilot_snapshots where id=j.snapshot_id;select * into c from public.analysis_jev_economy_configurations where id=s.configuration_id;
 for t in select * from public.analysis_jev_pilot_tasks where job_id=p_job and status='pending' order by review_id for update skip locked limit 8 loop
 select x into r from jsonb_array_elements(s.source->'reviews') x where x->>'id'=t.review_id::text;
 select ca.* into found_cache from public.analysis_jev_review_cache ca where ca.organization_id=j.organization_id and ca.establishment_id=s.establishment_id and ca.review_id=t.review_id and ca.configuration_id=c.id and ca.analysis_text_sha256=t.analysis_text_sha256 and ca.instruction_version=c.config->>'instruction_version' and ca.instruction_sha256=c.instruction_sha256 and ca.threshold_version=c.config->>'threshold_version' and ca.threshold_sha256=c.threshold_sha256 and ca.status='completed' and ca.served_model=ca.expected_served_model and ca.served_model<>'jev-latest' and public.pilot_response_valid(ca.response) and (select count(*) from jsonb_object_keys(ca.theme_results))=25 order by ca.processed_at desc,ca.id limit 1;
 if found then update public.analysis_jev_pilot_tasks set status='completed',cache_id=found_cache.id,reused=true,response=found_cache.response,served_model=found_cache.served_model,completed_at=now() where id=t.id;
 else
 identity=jsonb_build_object('organization_id',j.organization_id,'establishment_id',s.establishment_id,'review_id',t.review_id,'analysis_text_sha256',t.analysis_text_sha256,'configuration_id',c.id,'instruction_version',c.config->>'instruction_version','instruction_sha256',c.instruction_sha256,'threshold_version',c.config->>'threshold_version','threshold_sha256',c.threshold_sha256,'requested_model','jev-latest','expected_served_model',j.expected_served_model);
 reservation=public.reserve_jev_economy_cache(j.created_by,identity);if reservation->>'claimed'<>'true' then update public.analysis_jev_pilot_tasks set status='failed',cache_id=(reservation->>'id')::uuid,error_code='PILOT_CACHE_BLOCKED_NO_RETRY',usage_complete=false,completed_at=now() where id=t.id;
 else update public.analysis_jev_pilot_tasks set status='running',cache_id=(reservation->>'id')::uuid,lease_owner=p_worker,started_at=now() where id=t.id returning * into t;
 update public.analysis_jev_review_cache set status='dispatched',attempt_id=t.id,confirmed_by=j.created_by,confirmed_at=j.cost_confirmed_at where id=t.cache_id;return next t;end if;
 end if;end loop;end $$;
create function public.begin_economy_pilot_sol_attempt(p_job uuid,p_worker uuid) returns boolean language plpgsql security invoker set search_path='' as $$begin
 update public.analysis_jev_pilot_jobs set request_count=1 where id=p_job and stage='sol' and status='running' and request_count=0 and lease_owner=p_worker and lease_until>now();return found;end $$;
create function public.complete_economy_pilot_task(p_job uuid,p_worker uuid,p_task uuid,p_values jsonb) returns boolean language plpgsql security invoker set search_path='' as $$
declare j public.analysis_jev_pilot_jobs;s public.analysis_jev_pilot_snapshots;t public.analysis_jev_pilot_tasks;c public.analysis_jev_review_cache;cost numeric;actual_id uuid;identity jsonb;begin
 select * into j from public.analysis_jev_pilot_jobs where id=p_job and status='running' and lease_owner=p_worker and lease_until>now() for update;if not found then return false;end if;
 select * into t from public.analysis_jev_pilot_tasks where id=p_task and job_id=j.id and status='running' and lease_owner=p_worker for update;if not found then return false;end if;
 select * into s from public.analysis_jev_pilot_snapshots where id=j.snapshot_id;if p_values->>'status' not in ('completed','failed') or(p_values->>'request_count')::int<>1 then raise exception 'PILOT_SINGLE_PASS_ONLY';end if;
 cost=((p_values->>'input_tokens')::numeric*(s.rates->>'jev_input')::numeric+(p_values->>'output_tokens')::numeric*(s.rates->>'jev_output')::numeric)/1000000;
 select * into c from public.analysis_jev_review_cache where id=t.cache_id for update;actual_id=c.id;
 if p_values->>'status'='completed' and p_values->>'served_model'=c.expected_served_model then
 update public.analysis_jev_review_cache set status='completed',response=p_values->'response',theme_results=p_values->'theme_results',served_model=p_values->>'served_model',input_tokens=(p_values->>'input_tokens')::bigint,output_tokens=(p_values->>'output_tokens')::bigint,cost_usd=cost,usage_complete=(p_values->>'usage_complete')::boolean,processed_at=now() where id=c.id;
 else
 update public.analysis_jev_review_cache set status='billing_uncertain',served_model=p_values->>'served_model',input_tokens=(p_values->>'input_tokens')::bigint,output_tokens=(p_values->>'output_tokens')::bigint,cost_usd=cost,usage_complete=(p_values->>'usage_complete')::boolean,error_code=coalesce(p_values->>'error_code','PILOT_SERVED_MODEL_CHANGED'),processed_at=now() where id=c.id;
 if p_values->>'status'='completed' then
 identity=jsonb_build_object('organization_id',c.organization_id,'establishment_id',c.establishment_id,'review_id',c.review_id,'analysis_text_sha256',c.analysis_text_sha256,'configuration_id',c.configuration_id,'instruction_version',c.instruction_version,'instruction_sha256',c.instruction_sha256,'threshold_version',c.threshold_version,'threshold_sha256',c.threshold_sha256,'requested_model',c.requested_model,'expected_served_model',p_values->>'served_model');
 insert into public.analysis_jev_review_cache(cache_key,organization_id,establishment_id,review_id,analysis_text_sha256,configuration_id,instruction_version,instruction_sha256,threshold_version,threshold_sha256,requested_model,expected_served_model,status,response,theme_results,served_model,input_tokens,output_tokens,cost_usd,usage_complete,processed_at,source_kind,source_run_id,source_task_id)
 values(encode(extensions.digest(public.jev_economy_canonical(identity),'sha256'),'hex'),c.organization_id,c.establishment_id,c.review_id,c.analysis_text_sha256,c.configuration_id,c.instruction_version,c.instruction_sha256,c.threshold_version,c.threshold_sha256,c.requested_model,p_values->>'served_model','completed',p_values->'response',p_values->'theme_results',p_values->>'served_model',(p_values->>'input_tokens')::bigint,(p_values->>'output_tokens')::bigint,cost,(p_values->>'usage_complete')::boolean,now(),'pilot_jev',j.id,t.id) on conflict(cache_key) do nothing;
 select id into actual_id from public.analysis_jev_review_cache where cache_key=encode(extensions.digest(public.jev_economy_canonical(identity),'sha256'),'hex');end if;end if;
 update public.analysis_jev_pilot_tasks set status=p_values->>'status',cache_id=actual_id,response=p_values->'response',served_model=p_values->>'served_model',input_tokens=(p_values->>'input_tokens')::bigint,output_tokens=(p_values->>'output_tokens')::bigint,cost_usd=cost,duration_ms=(p_values->>'duration_ms')::bigint,request_count=1,usage_complete=(p_values->>'usage_complete')::boolean,error_code=p_values->>'error_code',completed_at=now() where id=t.id;
 insert into public.analysis_jev_review_cache_events(cache_id,organization_id,actor_id,action,details) values(actual_id,j.organization_id,j.created_by,'pilot_single_pass_finished',jsonb_build_object('job_id',j.id,'task_id',t.id));update public.analysis_jev_pilot_jobs set lease_until=now()+interval '240 seconds' where id=j.id;return true;end $$;
create function public.finish_economy_pilot_tick(p_job uuid,p_worker uuid,p_result jsonb default null,p_usage jsonb default null,p_error text default null) returns boolean language plpgsql security invoker set search_path='' as $$
declare j public.analysis_jev_pilot_jobs;s public.analysis_jev_pilot_snapshots;begin
 select * into j from public.analysis_jev_pilot_jobs where id=p_job and status='running' and lease_owner=p_worker and lease_until>now() for update;if not found then return false;end if;select * into s from public.analysis_jev_pilot_snapshots where id=j.snapshot_id;
 if p_error is not null then update public.analysis_jev_pilot_jobs set status='failed',error_code=p_error,usage_complete=false,completed_at=now(),lease_owner=null,lease_until=null where id=j.id;
 elsif p_result is not null then
 if j.stage='jev' then
 if exists(select 1 from public.analysis_jev_pilot_tasks where job_id=j.id and status in ('pending','running')) then raise exception 'PILOT_TASKS_PENDING';end if;
 update public.analysis_jev_pilot_jobs set request_count=(select coalesce(sum(request_count),0) from public.analysis_jev_pilot_tasks where job_id=j.id),input_tokens=(select coalesce(sum(input_tokens),0) from public.analysis_jev_pilot_tasks where job_id=j.id),output_tokens=(select coalesce(sum(output_tokens),0) from public.analysis_jev_pilot_tasks where job_id=j.id),cost_usd=(select coalesce(sum(cost_usd),0) from public.analysis_jev_pilot_tasks where job_id=j.id),duration_ms=(select coalesce(sum(duration_ms),0) from public.analysis_jev_pilot_tasks where job_id=j.id),usage_complete=(select bool_and(usage_complete) from public.analysis_jev_pilot_tasks where job_id=j.id),result=p_result where id=j.id;
 else update public.analysis_jev_pilot_jobs set input_tokens=(p_usage->>'input_tokens')::bigint,output_tokens=(p_usage->>'output_tokens')::bigint,duration_ms=(p_usage->>'duration_ms')::bigint,usage_complete=(p_usage->>'usage_complete')::boolean,cost_usd=((p_usage->>'input_tokens')::numeric*(s.rates->>'sol_input')::numeric+(p_usage->>'output_tokens')::numeric*(s.rates->>'sol_output')::numeric)/1000000,result=p_result where id=j.id;end if;
 update public.analysis_jev_pilot_jobs set status='completed',completed_at=now(),lease_owner=null,lease_until=null where id=j.id;
 else update public.analysis_jev_pilot_jobs set lease_owner=null,lease_until=null where id=j.id;end if;return true;end $$;
revoke all on function public.pilot_response_valid(jsonb),public.claim_economy_pilot_job(uuid),public.claim_economy_pilot_tasks(uuid,uuid),public.complete_economy_pilot_task(uuid,uuid,uuid,jsonb),public.finish_economy_pilot_tick(uuid,uuid,jsonb,jsonb,text) from public,anon,authenticated;
grant execute on function public.pilot_response_valid(jsonb),public.claim_economy_pilot_job(uuid),public.claim_economy_pilot_tasks(uuid,uuid),public.complete_economy_pilot_task(uuid,uuid,uuid,jsonb),public.finish_economy_pilot_tick(uuid,uuid,jsonb,jsonb,text) to service_role;
revoke all on function public.begin_economy_pilot_sol_attempt(uuid,uuid) from public,anon,authenticated;
grant execute on function public.begin_economy_pilot_sol_attempt(uuid,uuid) to service_role;
select cron.schedule('home-reviews-economy-pilot-worker-v1','* * * * *',$cron$
 select net.http_post(url:='https://ihuztjkblywzjdruusdj.supabase.co/functions/v1/process-jev-economy-pilot',headers:=jsonb_build_object('Content-Type','application/json','x-home-reviews-scheduler',(select decrypted_secret from vault.decrypted_secrets where name='home_reviews_scheduler_token')),body:='{}'::jsonb,timeout_milliseconds:=180000)
 where exists(select 1 from public.analysis_jev_pilot_jobs j join public.analysis_jev_pilot_authorizations a on a.id=j.authorization_id where j.status in ('queued','running') and (j.lease_until is null or j.lease_until<=now()));
$cron$);
