-- Separate, free V2.1 record. V2 rows/functions/constraints are not changed.
create table public.analysis_jev_pilot_evidence_v21(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),base_audit_id uuid not null references public.analysis_jev_pilot_evidence_audits(id),
 snapshot_id uuid not null references public.analysis_jev_pilot_snapshots(id),report_id uuid not null references public.analysis_jev_pilot_jobs(id),
 version text not null check(version='pilot-evidence-explicit-v2.1'),verifier text not null check(verifier='explicit-evidence-rules-v2.1'),rule_sha256 text not null check(rule_sha256~'^[a-f0-9]{64}$'),
 base_result_sha256 text not null,result_sha256 text not null check(result_sha256~'^[a-f0-9]{64}$'),result jsonb not null,
 verification_type text not null default 'deterministic_rule_check' check(verification_type='deterministic_rule_check'),human_validated boolean not null default false check(not human_validated),ai_verified boolean not null default false check(not ai_verified),
 new_paid_calls int not null default 0 check(new_paid_calls=0),production_enabled boolean not null default false check(not production_enabled),created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),unique(base_audit_id,rule_sha256)
);
create index pilot_evidence21_org on public.analysis_jev_pilot_evidence_v21(organization_id);
create index pilot_evidence21_snapshot on public.analysis_jev_pilot_evidence_v21(snapshot_id);
create index pilot_evidence21_report on public.analysis_jev_pilot_evidence_v21(report_id);
create index pilot_evidence21_actor on public.analysis_jev_pilot_evidence_v21(created_by);
alter table public.analysis_jev_pilot_evidence_v21 enable row level security;
revoke all on public.analysis_jev_pilot_evidence_v21 from anon,authenticated;
grant select on public.analysis_jev_pilot_evidence_v21 to authenticated;
grant all on public.analysis_jev_pilot_evidence_v21 to service_role;
create policy pilot_evidence21_read on public.analysis_jev_pilot_evidence_v21 for select to authenticated using(exists(select 1 from public.organization_members m where m.organization_id=analysis_jev_pilot_evidence_v21.organization_id and m.user_id=(select auth.uid()) and m.role in ('owner','admin','manager')));
create trigger pilot_evidence21_immutable before update or delete on public.analysis_jev_pilot_evidence_v21 for each row execute function public.pilot_evidence_immutable();
create function public.save_pilot_evidence_v21(p_user uuid,p_base uuid,p_result jsonb,p_sha text) returns uuid language plpgsql security invoker set search_path='' as $$
declare parent public.analysis_jev_pilot_evidence_audits;aid uuid;begin
 select * into parent from public.analysis_jev_pilot_evidence_audits where id=p_base;
 if parent.id is null or not exists(select 1 from public.organization_members where organization_id=parent.organization_id and user_id=p_user and role in ('owner','admin','manager')) then raise exception 'FORBIDDEN';end if;
 if p_result->>'version' is distinct from 'pilot-evidence-explicit-v2.1' or p_result->>'verifier' is distinct from 'explicit-evidence-rules-v2.1' or p_result->>'base_audit_id' is distinct from parent.id::text or p_result->>'base_result_sha256' is distinct from parent.result_sha256 or p_result->>'source_sha256' is distinct from parent.source_sha256 or p_result->>'snapshot_id' is distinct from parent.snapshot_id::text or p_result->>'report_id' is distinct from parent.report_id::text or p_result->>'prediction_source_sha256' is distinct from parent.prediction_source_sha256 or p_result->>'human_validated' is distinct from 'false' or p_result->>'ai_verified' is distinct from 'false' or p_result->>'new_paid_calls' is distinct from '0' or p_result->>'production_enabled' is distinct from 'false' then raise exception 'EVIDENCE_V21_SOURCE_CHANGED';end if;
 if p_sha is distinct from encode(extensions.digest(public.jev_economy_canonical(p_result),'sha256'),'hex') or parent.result_sha256<>encode(extensions.digest(public.jev_economy_canonical(parent.result),'sha256'),'hex') then raise exception 'EVIDENCE_V21_HASH_CHANGED';end if;
 if p_result->'statistics' is distinct from parent.result->'source_context'->'topics' or p_result->'old_recommendations' is distinct from parent.result->'recommendations' or jsonb_array_length(p_result->'checks')<>jsonb_array_length(parent.result->'checks') or (p_result->'summary'->>'jev_reviews')::int<>(parent.result->'summary'->>'jev_reviews')::int or (p_result->'summary'->>'jev_findings')::int<>(parent.result->'summary'->>'jev_findings')::int then raise exception 'EVIDENCE_V21_COUNTS_CHANGED';end if;
 if jsonb_array_length(p_result->'selected')<>jsonb_array_length(parent.result->'selected') or (select count(distinct x->>'v2_binding_id') from jsonb_array_elements(p_result->'selected') x)<>jsonb_array_length(parent.result->'selected') or exists(select 1 from jsonb_array_elements(p_result->'selected') x where x->>'status'<>'supported_by_rule' or not exists(select 1 from jsonb_array_elements(parent.result->'selected') prev where prev->>'binding_id'=x->>'v2_binding_id' and prev->>'review_id'=x->>'review_id' and prev->>'key'=x->>'key' and prev->>'quote_sha256'=x->>'quote_sha256' and prev->'excerpt'->>'quote'=x->'excerpt'->>'quote')) then raise exception 'EVIDENCE_V21_PINNED_PROOF_CHANGED';end if;
 if exists(select 1 from jsonb_array_elements(p_result->'checks') x where not exists(select 1 from jsonb_array_elements(parent.result->'checks') prev where prev->>'binding_id'=x->>'v2_binding_id' and prev->>'review_id'=x->>'review_id' and prev->>'key'=x->>'key' and prev->>'analysis_text_sha256'=x->>'analysis_text_sha256' and prev->>'cache_response_sha256'=x->>'cache_response_sha256')) then raise exception 'EVIDENCE_V21_PREDICTIONS_CHANGED';end if;
 perform pg_advisory_xact_lock(hashtextextended(parent.id::text||':'||(p_result->>'rule_sha256'),0));select id into aid from public.analysis_jev_pilot_evidence_v21 where base_audit_id=parent.id and rule_sha256=p_result->>'rule_sha256';if found then return aid;end if;
 insert into public.analysis_jev_pilot_evidence_v21(organization_id,base_audit_id,snapshot_id,report_id,version,verifier,rule_sha256,base_result_sha256,result_sha256,result,created_by) values(parent.organization_id,parent.id,parent.snapshot_id,parent.report_id,p_result->>'version',p_result->>'verifier',p_result->>'rule_sha256',parent.result_sha256,p_sha,p_result,p_user) returning id into aid;return aid;end $$;
revoke all on function public.save_pilot_evidence_v21(uuid,uuid,jsonb,text) from public,anon,authenticated;
grant execute on function public.save_pilot_evidence_v21(uuid,uuid,jsonb,text) to service_role;
