import {requireUser} from '../_shared/auth.ts'
import {enforceRateLimit} from '../_shared/rate-limit.ts'
import {exploratoryHandler,type ExplorationSource,type AiApproval} from '../_shared/jev-exploratory-api.ts'
import {EXPLORATORY_CONFIG,exploratoryPredictions,type ExploratoryItem,type ExploratoryRun,type AiCorrection} from '../_shared/jev-exploratory-core.ts'
import {negativeHash} from '../_shared/negative-validation-core.ts'
import type {NegativeTask} from '../_shared/negative-validation-score.ts'
import type {V9Task} from '../_shared/historical-v9-core.ts'
import type {ThemeDecision} from '../_shared/jev-themes.ts'
Deno.serve(exploratoryHandler(async request=>{const ctx=await requireUser(request);if(request.method==='POST')enforceRateLimit('jev-exploration:'+ctx.user.id,40,60_000);const {data:members,error:me}=await ctx.client.from('organization_members').select('organization_id').eq('user_id',ctx.user.id).in('role',['owner','admin','manager']);if(me||!members?.length)throw new Error('FORBIDDEN');const orgs=members.map(m=>m.organization_id)
  const read=async(table:string,field:string,value:string)=>{const rows:Record<string,unknown>[]=[];for(let n=0;;n+=500){const {data,error}=await ctx.admin.from(table).select('*').eq(field,value).order(table==='historical_jev_analysis_tasks'||table.endsWith('_tasks')?'id':'review_id').range(n,n+499);if(error)throw new Error('EXPLORATORY_READ_FAILED');rows.push(...data);if(data.length<500)break}return rows}
  const aiBenchmark=async(source:string)=>{const {data,error}=await ctx.admin.from('analysis_negative_ai_exploratory_runs').select('id,dataset_snapshot,organization_id').eq('source_experiment_id',source).eq('status','completed').in('organization_id',orgs).maybeSingle();if(error)throw new Error('EXPLORATORY_READ_FAILED');return data}
  const get=async(id?:string)=>{let q=ctx.admin.from('analysis_jev_exploratory_runs').select('*').in('organization_id',orgs);if(id)q=q.eq('id',id);else q=q.order('created_at',{ascending:false}).limit(1);const {data,error}=await q.maybeSingle();if(error)throw new Error('EXPLORATORY_READ_FAILED');if(id&&!data)throw new Error('FORBIDDEN');return data as ExploratoryRun|null}
  const historicalTasks=async(id:string,version:'v9'|'v11')=>(await read('historical_jev_analysis_tasks','run_id',id) as unknown as V9Task[]).filter(t=>t.kind==='themes').map(t=>({...t,experiment_id:id,model_version:version,response:t.result as ThemeDecision,question_set_version:version==='v11'?EXPLORATORY_CONFIG.question_set:'themes_phase2_v7',cost_usd:0})) as NegativeTask[]
  const sources=async()=>{const list:ExplorationSource[]=[];const {data:a,error:ae}=await ctx.admin.from('analysis_negative_validation_runs').select('id,organization_id,establishment_id,name').in('organization_id',orgs);if(ae)throw new Error('EXPLORATORY_READ_FAILED');for(const s of a){const benchmark=await aiBenchmark(s.id),rows=benchmark?.dataset_snapshot??await read('analysis_negative_validation_reviews','experiment_id',s.id),active=rows.filter((i:Record<string,unknown>)=>!i.excluded);list.push({...s,kind:'negative_validation',name:'Artisan · dataset anglais figé',total:active.length,ready:active.filter((i:Record<string,unknown>)=>i.analysis_language==='en'&&typeof i.analysis_text==='string'&&i.analysis_text.trim()).length,reuses_predictions:!!benchmark})}
    const {data:b,error:be}=await ctx.admin.from('historical_report_runs').select('id,organization_id,establishment_id,generation_id,snapshot').in('organization_id',orgs).eq('status','completed').eq('snapshot->>analysis_version','11');if(be)throw new Error('EXPLORATORY_READ_FAILED');for(const s of b){const rows=s.snapshot.reviews.filter((i:{analysis_text?:string})=>i.analysis_text?.trim());const {data:e}=await ctx.admin.from('establishments').select('name').eq('id',s.establishment_id).single();list.push({id:s.id,organization_id:s.organization_id,establishment_id:s.establishment_id,kind:'historical_v11',name:(e?.name??'V11')+' · V11 '+s.generation_id,total:rows.length,ready:rows.filter((i:{analysis_language:string})=>i.analysis_language==='en').length,reuses_predictions:true})}return list}
  return {user:ctx.user.id,sources,get,configured:()=>!!Deno.env.get('TYPESAFE_API_KEY')?.trim(),source:async s=>{let items:ExploratoryItem[];let tasks:NegativeTask[]=[]
    if(s.kind==='negative_validation'){const benchmark=await aiBenchmark(s.id);if(benchmark){items=benchmark.dataset_snapshot as ExploratoryItem[];tasks=await read('analysis_negative_ai_exploratory_tasks','run_id',benchmark.id) as unknown as NegativeTask[]}else{const sourceRows=await read('analysis_negative_validation_reviews','experiment_id',s.id);items=sourceRows.filter(i=>!i.excluded).map(i=>({review_id:i.review_id,position:i.position,analysis_text:i.analysis_text,analysis_text_sha256:i.analysis_text_sha256,overall_rating:i.overall_rating,normalized_category_ratings:i.normalized_category_ratings,v9:{},v11:{}})) as ExploratoryItem[];tasks=await read('analysis_negative_validation_tasks','experiment_id',s.id) as unknown as NegativeTask[]}}
    else {const {data:h,error}=await ctx.admin.from('historical_report_runs').select('snapshot').eq('id',s.id).eq('organization_id',s.organization_id).single();if(error)throw new Error('EXPLORATORY_READ_FAILED');items=await Promise.all(h.snapshot.reviews.filter((i:{analysis_text?:string})=>i.analysis_text?.trim()).map(async(i:{id:string;analysis_text:string;rating:number;normalized_category_ratings:ExploratoryItem['normalized_category_ratings']},index:number)=>({review_id:i.id,position:index+1,analysis_text:i.analysis_text,analysis_text_sha256:await negativeHash(i.analysis_text),overall_rating:i.rating,normalized_category_ratings:i.normalized_category_ratings,v9:{},v11:{}})));tasks=await historicalTasks(s.id,'v11');const {data:v9}=await ctx.admin.from('historical_report_runs').select('id,snapshot').eq('generation_id',h.snapshot.source_generation_id).eq('organization_id',s.organization_id).eq('status','completed').maybeSingle();if(v9){const hashById=new Map(v9.snapshot.reviews.map((r:{id:string;analysis_text?:string})=>[r.id,r.analysis_text]));const previous=await historicalTasks(v9.id,'v9');tasks.push(...previous.filter(t=>items.some(i=>i.review_id===t.review_id&&hashById.get(i.review_id)===i.analysis_text)))}}
    return items.map(i=>({...i,v9:exploratoryPredictions(tasks,i.review_id,'v9'),v11:exploratoryPredictions(tasks,i.review_id,'v11')}))},
    items:async id=>{await get(id);return await read('analysis_jev_exploratory_items','run_id',id) as unknown as ExploratoryItem[]},
    approvals:async id=>{await get(id);const {data,error}=await ctx.admin.from('analysis_jev_exploratory_approvals').select('id,bundle_sha256,review_ids,approved_at,approved_by').eq('run_id',id).order('approved_at',{ascending:false});if(error)throw new Error('EXPLORATORY_READ_FAILED');return data as AiApproval[]},
    corrections:async id=>{await get(id);const {data,error}=await ctx.admin.from('analysis_jev_exploratory_corrections').select('*').eq('run_id',id).order('imported_at').order('id').limit(5000);if(error)throw new Error('EXPLORATORY_READ_FAILED');return data as AiCorrection[]},
    usage:async id=>{await get(id);const tasks=await read('analysis_jev_exploratory_tasks','run_id',id);return {requests:tasks.reduce((n,t)=>n+Number(t.request_count),0),input_tokens:tasks.reduce((n,t)=>n+Number(t.input_tokens),0),output_tokens:tasks.reduce((n,t)=>n+Number(t.output_tokens),0),cost_usd:tasks.reduce((n,t)=>n+Number(t.cost_usd),0),served_models:[...new Set(tasks.flatMap(t=>typeof t.served_model==='string'?[t.served_model]:[]))],complete:tasks.every(t=>t.usage_complete===true)}},
    create:async(s,items,fingerprint)=>{const rate=Number(Deno.env.get('JEV_INPUT_USD_PER_MILLION')??.042);const {data,error}=await ctx.admin.rpc('create_jev_exploration',{p_user:ctx.user.id,p_org:s.organization_id,p_establishment:s.establishment_id,p_kind:s.kind,p_source:s.id,p_items:items,p_fingerprint:fingerprint,p_config:EXPLORATORY_CONFIG,p_rate:Number.isFinite(rate)&&rate>=0?rate:.042});if(error)throw new Error('EXPLORATORY_CREATE_FAILED');return data as string},
    write:async(id,action,payload)=>{await get(id);const {data,error}=await ctx.admin.rpc('write_jev_exploration',{p_user:ctx.user.id,p_id:id,p_action:action,p_payload:payload});if(error){const code=['FORBIDDEN','EXPLORATORY_GO_REQUIRED','EXPLORATORY_IMPORT_IMMUTABLE','EXPLORATORY_EVALUATION_CONTAMINATION','EXPLORATORY_PROTECTED_HOLDOUT','EXPLORATORY_CORRECTIONS_INVALID'].find(c=>error.message.includes(c));throw new Error(code??'EXPLORATORY_SAVE_FAILED')}return data},
  }
}))
